### ISSUE TITLE
Hide check and update for external link

### ISSUE THREAD

**Issue by onlineapps-cloud** [IceWhaleTech/CasaOS#1001]
Hi, please hide this option for external link:
![image](https://user-images.githubusercontent.com/69077240/230719365-02b458e4-2bef-4cf0-87f7-68b637b1a07a.png)

**Comment by CosmoFox** [comment]
For?

**Comment by onlineapps-cloud** [comment]
because check and update is suitable only for docker container.

**Comment by CosmoFox** [comment]
> because check and update is suitable only for docker container.
my bad, forgot about that funcional

**Comment by zhanghengxin** [comment]
It will change in the next version（0.4.4）
