### ISSUE TITLE
App store doesn't work

### ISSUE THREAD

**Issue by mamortensen** [IceWhaleTech/CasaOS#1005]
**Describe the bug**
When I click on the app store I just get a wait wheel that spins forever

**To Reproduce**
Connect to casaos.local
click on the app store button

**Expected behavior**
The app store should open up so I can pick an app

**Screenshots**
![image](https://user-images.githubusercontent.com/7896138/231017575-f0713a73-e148-4492-ae88-ceaa891c52f4.png)

**Desktop (please complete the following information):**
Windows 11
Firefox 111.0.1

**Logs**

run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
```

**Additional context**

**Comment by raller1028** [comment]
can you provide your casaos version?

**Comment by mamortensen** [comment]
version 0.3.2.1

Martin Mortensen

**Comment by raller1028** [comment]
Does your app shop keep failing to open? Can you try upgrading to v0.4.3 to see if the shop opens properly?
upgrade command: curl -fsSL https://get.casaos.io/update | bash

**Comment by mamortensen** [comment]
The command gives this error.

***@***.***:~$ curl -fsSL https://get.casaos.io/update | bash
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Martin Mortensen

**Comment by raller1028** [comment]
The error message means that the curl command encountered a certificate issue when trying to connect to get.casaos.io over HTTPS. Specifically, the SSL certificate has expired, so curl cannot verify the legitimacy of the server and therefore cannot establish a secure connection.

One way to resolve this issue is to use the -k or --insecure option in the curl command to ignore the certificate verification, for example:

curl -fsSLk https://get.casaos.io/update | bash

**Comment by mamortensen** [comment]
Well, I got a slightly different error with that.

***@***.***:~$ curl -fsSLk https://get.casaos.io/update | bash

   _____                 ____   _____
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___
 | |    / _` / __|/ _` | |  | |\___ \
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/

   --- Made by IceWhale with YOU ---

[sudo] password for casaos:
- OK Your hardware architecture is : x86_64
Get:1 http://security.debian.org/debian-security bullseye-security
InRelease [48.4 kB]
Hit:2 http://deb.debian.org/debian bullseye InRelease
Err:3 https://download.docker.com/linux/debian bullseye InRelease
  Certificate verification failed: The certificate is NOT trusted. The
revocation or OCSP data are old and have been superseded. The certificate
chain uses expired certificate.  Could not handshake: Error in the
certificate verification. [IP: 18.154.144.82 443]
Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Reading package lists... Done
E: Release file for
http://security.debian.org/debian-security/dists/bullseye-security/InRelease
is expired (invalid since 32568d 14h 19min 56s). Updates for this
repository will not be applied.
E: Release file for
http://deb.debian.org/debian/dists/bullseye-updates/InRelease is expired
(invalid since 32568d 12h 38min 19s). Updates for this repository will not
be applied.
***@***.***:~$

Martin Mortensen

**Comment by raller1028** [comment]
Please make sure that your system time is correct, as an incorrect system time can also cause curl to consider the certificate expired.
`date -s "2023-04-13 xx:xx:xx"`

**Comment by mamortensen** [comment]
Ok it took a couple of tries but I finally got it updated and that did fix
the app store.

Thank you
Martin Mortensen
