### ISSUE TITLE
i'm having problem to update

### ISSUE THREAD

**Issue by RSerejo** [IceWhaleTech/CasaOS#1009]
update screen take long time without effect, any other way to update?

**Comment by RSerejo** [comment]
i finde "curl -fsSL https://get.casaos.io/update | sudo bash" on other bug report so i tried to update again with success.

**Comment by raller1028** [comment]
From which version did you update to the latest version, I also tried to update from the web-ui side using the update button

**Comment by raller1028** [comment]
If you still have problems, please reopen
