### ISSUE TITLE
Bug: Delete userdata ( config folder ) not working

### ISSUE THREAD

**Issue by onlineapps-cloud** [IceWhaleTech/CasaOS#1010]
https://user-images.githubusercontent.com/69077240/232197490-ec963185-9d74-4248-9917-312f08e663e1.mp4

**Comment by raller1028** [comment]
![image](https://user-images.githubusercontent.com/57336867/232717253-cd4b9d6b-5698-47bd-88a0-29b33b2505df.png)
As you can see, our delete operation will only delete the container folder containing '/config'

**Comment by raller1028** [comment]
If still have problems, please reopen
