### ISSUE TITLE
[Bug] 桌面存储空间无法正常显示空间大小。

### ISSUE THREAD

**Issue by iamyangyiok** [IceWhaleTech/CasaOS#1016]
桌面存储空间无法正常显示空间大小。使用0，可用0，创建空间按钮也是灰的，无法点。
Desktop storage space does not display space size properly. Use 0, Available 0, and the Create Space button is also grayed out and cannot be clicked.

硬件环境如下：
The hardware environment is as follows:
UBUNTU 18.04 LTS , ARM CPU:A311D MEM:4G  EMMC:32G,

执行DF   分区结构如下：
Implement the DF partition structure as follows:

1. _root@750E:~# df
2. Filesystem     1K-blocks    Used Available Use% Mounted on
3. /dev/system     28201040 3958104  22811080  15% /
4. devtmpfs         1915424       0   1915424   0% /dev
5. tmpfs            1919884       0   1919884   0% /dev/shm
6. tmpfs            1919884    3364   1916520   1% /run
7. tmpfs               5120       0      5120   0% /run/lock
8. tmpfs            1919884       0   1919884   0% /sys/fs/cgroup
9. /dev/sda1       30309372   42568  30266804   1% /media/devmon/sda1-usb-Lexar_USB                                                             _Flash_
10. overlay         28201040 3958104  22811080  15% /var/lib/docker/overlay2/dfb8618                                                             60d242014ecee035be4a7a131d50da032fd4670324a017f42e5f46e8c/merged
11. overlay         28201040 3958104  22811080  15% /var/lib/docker/overlay2/874a98e                                                             71944699274da581f8867d7b803731dfb5c94b832b7593ead2c6bfa59/merged
12. overlay         28201040 3958104  22811080  15% /var/lib/docker/overlay2/53d794b                                                             1f8c3efc89344d88021f52887cfd92354c51a418c9475d3225563c48d/merged
13. overlay         28201040 3958104  22811080  15% /var/lib/docker/overlay2/9b9c733                                                             5a5efa7b8886b77fc04aad5a9dfe34e0fb3e9aad923cb9099b00cfcfb/merged
14. tmpfs             383976       0    383976   0% /run/user/0
15. root@750E:~#_

**Comment by raller1028** [comment]
你可以加微信(reelfy2570),让我们远程查看一下是什么问题吗？
Can you add WeChat (reelfy2570) so we can take a look at what's wrong remotely?
