### ISSUE TITLE
[Feedback]【问题】存储空间管理，看不到USB挂的多块硬盘，只看到一块

### ISSUE THREAD

**Issue by ufocat000** [IceWhaleTech/CasaOS#1018]
### Description

1、主页这里看到，文件管理也能看到，2块USB硬盘，存储空间设置里面没有。
2、挂多硬盘的磁盘盒，只能用一块硬盘

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 7040 
	 - Disk Used: 2381 
	 - System Info: [Armbian 23.05.0-trunk Bullseye \l Bit:32 Mem:989M Core:4 Linux onecloud 6.1.22-meson #1 SMP Thu Mar 30 10:49:31 UTC 2023 armv7l GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Edge 
	 - Version: 112.0.1722.58

**Comment by raller1028** [comment]
你可以加微信(reelfy2570),让我们远程查看一下是什么问题吗？
Can you add me on WeChat (reelfy2570) so we can remotely check what the problem is?
