### ISSUE TITLE
App Store not loading 

### ISSUE THREAD

**Issue by sysadmin103** [IceWhaleTech/CasaOS#1019]
**Describe the bug**
App store will just spin and not load. I have a feeling this may be due to DNS, or a larger issue. 

When running nslookup, dig,  I get the following error:
timer.c:617: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed
Aborted

Also, my system is showing up to date with version: v0.3.2.1

**To Reproduce**
1. Click App Store link on main page

**Expected behavior**
App store should load 

**Screenshots**
![image](https://user-images.githubusercontent.com/131499338/233868550-0e1957ae-bcda-46f9-8a3d-8d28189c788f.png)

**Desktop (please complete the following information):**
- OS: linux
 - CasaOS Version: 0.3.2.1
 - Disk Total: 13253 
 - Disk Used: 3925 
 - Sync State: Sync img: true
linuxserver/syncthing:latest,
Sync Key length: 32
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1826M Core:2 Linux CasaOS 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux]
 - Browser: Chrome 
 - Version: 112.0.0.0

**Logs**

run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
```
Log commands don't produce output and need to ctrl+c to exit them:
![image](https://user-images.githubusercontent.com/131499338/233868919-7086a6aa-5515-4ecd-abf8-72baebb04c1c.png)

**Additional context**

**Comment by wusaby-rush** [comment]
I installed casaOS on my rpi now, and I love it so much, but I faced this problem, I wish they fix as soon as possible

**Comment by raller1028** [comment]
@sysadmin103 I suggest upgrading casaos to the latest version before checking if the App Store is displaying.
Upgrade command: `curl -fsSL https://get.casaos.io/update | sudo bash`

**Comment by raller1028** [comment]
@wusaby-rush Excuse me, what is the version of your casaos?

**Comment by wusaby-rush** [comment]
> @wusaby-rush Excuse me, what is the version of your casaos?

I use 0.4.3 today apps opened from my iPad but installing apps failed

**Comment by raller1028** [comment]
@wusaby-rush Can you tell me what generation of Raspberry Pi you are and which application you failed to download, if convenient you can type `sudo journalctl -xef -u casaos-app-management` in the terminal when you failed to install

**Comment by raller1028** [comment]
if still have problems please reopen
