### ISSUE TITLE
[Feedback][Issue] Vaulwarden admin page - You are using a plain text `ADMIN_TOKEN` which is insecure

### ISSUE THREAD

**Issue by iyadmn** [IceWhaleTech/CasaOS#1020]
### Description

In the Vaultwarden administrator panel, the following message appears:

You are using a plain text `ADMIN_TOKEN` which is insecure.
Please generate a secure Argon2 PHC string by using `vaultwarden hash` or `argon2`.

[https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token)

![Captura de pantalla 2023-04-24 050030](https://user-images.githubusercontent.com/13158747/233891183-9dd6bfdb-2891-479f-baff-3ae6110e89e7.png)

If I put the ADMIN_TOKEN as a plain text format it works correctly:
dR9N+NEIevYk706obHqf0U7+Ld80bGJ7VUYVbOVF995D5I3s6l9NbN3uTJDiJN4v

After generating the hash using Argon2, on Casa OS Vaultwarden Container Settings, putting the new HASH in the ADMIN_TOKEN environment variable and saving it, not correctly store is left empty.

$argon2id$v=19$m=65540,t=3,p=4$Qm5ZY1E3NS9LL3VYREJqQWVSOWhiUlQyN3V1RTBQbjcxNTNCRkd3TG9nST0$948JqA+TXew2RboSDJXEDvjWYdwlouQ2ig5i9K6jstw

![Captura de pantalla 2023-04-24 050431](https://user-images.githubusercontent.com/13158747/233891220-97068dc3-a41d-4fbb-81f4-aa7fb843e1f0.png)

If I put the ADMIN_TOKEN as an Argon2 HASH and save the changes, the ADMIN_TOKEN environment variable is left empty.

![Captura de pantalla 2023-04-24 050740](https://user-images.githubusercontent.com/13158747/233891476-496aa473-db7c-49eb-b3f2-a8a8023740c1.png)

**Comment by tigerinus** [comment]
Not sure if this is the same issue as

- #993

**Comment by CorrectRoadH** [comment]
Suppose you want to set $ as the value in the environment. You must write two `$`. like `$$argon2id$$v=19$$m=65540,t=3,`
