### ISSUE TITLE
App store doesn't open

### ISSUE THREAD

**Issue by JVTEAM** [IceWhaleTech/CasaOS#103]
**Describe the bug**

When I click the app store button it just spins without opening.  Occured after mounting network drive in Fstab.  After removing the share the app store returned

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.8
	 - Disk Total: 13105 
	 - Disk Used: 6996 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1826M Core:4 Linux CasaOS 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 97.0.4692.99

**Comment by LinkLeong** [comment]
Yes, I noticed the problem, I am trying to find a solution

**Comment by leaf918** [comment]
I second.

**Comment by dan3577** [comment]
problem still exist

**Comment by LinkLeong** [comment]
We have solved the problem in the latest version, please upgrade to experience!

**Comment by mexup** [comment]
Same, installe CasaOS on Debian 10 64 Bit (VPS)
But appstore is not opening! https://i.imgur.com/LQ7aJWI.png

**Comment by jcwatson11** [comment]
Same issue. Just got my long awaited ZimaBoard, and overall I'm very impressed. However, this bug appears to cause some frustration.

The local web interface is calling XHR URL http://casaos.local/v1/app/list?index=1&size=5
This local server responds with JSON object: {"success":200,"message":"ok","data":{"count":0,"items":[]}}

How can this be fixed? I would love to install more software on my new Zima board.

**Comment by HongLouWang** [comment]
same issue still exist
