### ISSUE TITLE
[Feedback][ISSUE] all app install fail same as #988

### ISSUE THREAD

**Issue by lyte0ne** [IceWhaleTech/CasaOS#1033]
### Description

When I try to install an app all I get is an message that the install failed

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 110638 
	 - Disk Used: 11049 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7826M Core:4 Linux CasaOS 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 112.0.0.0

**Comment by lyte0ne** [comment]
is a DNS issue ... if I add google only DNS it works but if I use pi-hole DNS is getting blocked and hence the error

**Comment by raller1028** [comment]
Can this question be closed please?
