### ISSUE TITLE
[Feedback] Works on arch but it requires two AUR packages.

### ISSUE THREAD

**Issue by dhaumya** [IceWhaleTech/CasaOS#1035]
### Description

I apologise if this is not the correct place or format for this feedback / tutorial, please inform me if so.
And also for my spelling mistakes as English is my second language.

Update System:
`sudo pacman -Syu`

System Packages:
`sudo pacman -S wget(or curl) smartmontools ntfs-3g net-tools samba apparmor docker`

AUR packages(They are up to date with offical versions but udevil hasn't had released for years and probably is an abandoned project):
`udevil` and `mergerfs`

Enable and Start Docker:
`sudo systemctl enable --now docker`

Run the Script (If you want to use curl, install curl instead of wget in System Packages Section):
`wget -qO- https://get.casaos.io | sudo bash`
 Or
`curl -fsSL https://get.caraos.io | sudo bash`

If you wish to check the script before running it, pipe it in a file:
`wget -qO- https://get.casaos.io > check`
 Or
`curl -fsSL https://get.caraos.io > check`

Then check by:
`nano check`
 Or
`cat check`

This is one of the most coolest projects I know, keep it up devs. 
And thank you for you dedication in this project.

### Additional Information

This is about ×86_64 for arm check for @rmszc81 's comments.

**Comment by Ns2Kracy** [comment]
I recommend using `paru/yay`, it can easily install AUR packages.

Install yay:
```
git clone https://aur.archlinux.org/yay-bin
cd yay-bin
makepkg -si
```

Install all dependencies casaos need manually:
```
yay -Syu
yay -S wget curl smartmontools parted ntfs-3g net-tools \
udevil samba cifs-utils mergerfs unzip apparmor \
docker docker-compose rclone
```

Download the install script and just comment out two lines in the last of the script:
```
# Step 5: Install Depends
# Update_Package_Resource
# Install_Depends
```

Enable docker:
```
sudo systemctl enable --now docker
```

Run install Script:
```
sudo bash install.sh
```

**Comment by dhaumya** [comment]
I have tested it on arch for about a week now and have faced no issues. I had problem with one docker but that was more an config error then CasaOS error. I have tried App Store, docker run commands and docker compose scripts, they have worked perfectly. I don't think anyone with a bit of knowledge about Dockers would have an issue using CasaOS UI. I do wish if there was more theme customisation but I am a KDE user so no amount of customisation will ever be able to please me lol.

Hope this feedback helps and Thank you for such a Wonderful Application.

**Comment by dhaumya** [comment]
And to clarify, I did not mean the title to sound complaining or I am just being paranoid, thinking that it does sound that way lol. it was more of a caution as many people are warry of aur.

@Ns2Kracy Yay! A fellow yay user.

**Comment by tigerinus** [comment]
Thanks both @dhaumya and @Ns2Kracy for contributing steps of how to install CasaOS on Arch Linux.

I've incorporated your contribution into CasaOS Wiki at https://wiki.casaos.io/e/en/guides/install-on-arch-linux

Let me know if there is anything missing, OR even better, feel free to get register at Wiki and update the article by yourself. :)

**Comment by dhaumya** [comment]
@tigerinus After verifying the wiki with the install script and @Ns2Kracy comment,I have realised I forgot some packages in "System Packages" I tried to edit it at wiki but it's says I don't have been authorized. So could you add the following packages in "System Packages"?

`parted cifs-utils unzip docker-compose rclone`

Thanks

**Comment by dhaumya** [comment]
?

**Comment by tigerinus** [comment]
my bad.. totally forgot this.

updated.

**Comment by dhaumya** [comment]
> I guess that @dhaumya tested on x86/64, right?

Yes, that is indeed correct. Sorry that I forgot to mention this in the main issue.

**Comment by rmszc81** [comment]
So, after my research, the `udevil` package that's necessary is not available for `arch linux arm`. I also tried to build from the `aur` repository and I got the following message during the build: `==> ERROR: udevil is not available for the 'aarch64' architecture.`

I'll research a bit more to see if I can make this work in a simple way. For now, I'm assuming that it's not possible to run CasaOS  in the arch linux arm at this very moment.

**Comment by Ns2Kracy** [comment]
> So, after my research, the `udevil` package that's necessary is not available for `arch linux arm`. I also tried to build from the `aur` repository and I got the following message during the build: `==> ERROR: udevil is not available for the 'aarch64' architecture.`
> 
> I'll research a bit more to see if I can make this work in a simple way. For now, I'm assuming that it's not possible to run CasaOS in the arch linux arm at this very moment.

Try using udevil-git?

**Comment by jerrykuku** [comment]
I will do some research to see if udevil can be replaced with udisk2+devmon.
Maybe udisk2 is included in aur packages and devmon is just a shell script.

**Comment by dhaumya** [comment]
That's weird cuz udevil seems to have an rpm aarch64 pakage.

**Comment by dhaumya** [comment]
Have you tried this?
https://ignorantguru.github.io/udevil/#installer
Or 
https://github.com/IgnorantGuru/udevil/blob/master/README
Build or install section.

**Comment by pieterhouwen** [comment]
FYI you need a valid C compiler already installed to use this solution. The installation of this is not yet present in current documentation

**Comment by dhaumya** [comment]
Hmm I see, @rmszc81 did you try using makepkg with 'A' flag rather than usin aur helper?

**Comment by Natetronn** [comment]
Looks like I'm hitting an issue with the latest 0.4.4 update and udevil. It gets stuck at second step of trying to install Udevil. I got past this originally during initial isntall by installing mergerfs with yay and I think udisk2, if I remember correctly.

**Comment by Natetronn** [comment]
I was able to install udevil with `yay -S udevil`, since yay asks if you want to install as aarch64 even if not supported. Everything is fine as far as I can tell, but not sure. Could probably uninstall udevil now that CasaOS has been updated, but also not sure how that would affect things, either way.

**Comment by jerrykuku** [comment]
Uninstalling udevil will cause the automatic mounting functionality of USB drives to stop working.

**Comment by WSHAPER** [comment]
@tigerinus

This CasaOS installation method for Arch Linux uses `pacman` for most dependencies and `yay` for `udevil` and `mergerfs `. The script is designed to be easily pasted into `bash` for convenience. As of May 31, 2024, I've personally tested this approach and confirmed it works.
Looking forward to your feedback!

---

## Install CasaOS on Arch Linux

- [x]  #self-tested-working ✅ 2024-05-31

1. Install `yay`, referring to (#Yay Installation).
2. Run (possible to paste in `bash`):

```bash
# Update the system
sudo pacman -Syu && \

# Install system packages
sudo pacman -S wget smartmontools ntfs-3g net-tools samba apparmor docker parted cifs-utils unzip docker-compose rclone --noconfirm && \

# Install CasaOS Dependencies (as of 2024-05-31)
yay -S udevil mergerfs --noconfirm && \

# Print `yay` version
yay -S --version && \

# Enable and start Docker service
sudo systemctl enable --now docker && \

# Check if wget is available
WGET_AVAILABLE=false && \
if command -v wget &> /dev/null; then \
  WGET_AVAILABLE=true; \
fi && \

# Prompt user whether to check the script before running
read -p "Do you want to check the script before running? (y/n): " CHECK_SCRIPT && \

if [ "$CHECK_SCRIPT" = "y" ]; then \
  # Download the CasaOS script for inspection using wget if available, otherwise use curl
  if [ "$WGET_AVAILABLE" = true ]; then \
    wget -qO- https://get.casaos.io > check; \
  else \
    curl -fsSL https://get.casaos.io > check; \
  fi && \
  # Check the downloaded script using nano
  nano check; \
fi

# Download and run the CasaOS installation script using wget if available, otherwise use curl
if [ "$WGET_AVAILABLE" = true ]; then \
  wget -qO- https://get.casaos.io | sudo bash; \
else \
  curl -fsSL https://get.casaos.io | sudo bash; \
fi && \

# Enable CasaOS on startup
systemctl enable casaos
```

## Yay Installation
### Update Your System (Optional)  
   Before installing `yay`, it's a good practice to update your system. You can do this with the following command:

   ```bash
   sudo pacman -Syu
   ```

### Installation

```bash
# Install git without confirmation
sudo pacman -S git --noconfirm && \
# Change directory to /opt
cd /opt && \
# Clone yay-git repository
sudo git clone https://aur.archlinux.org/yay-git.git && \
# Change ownership to current user and their group
sudo chown -R $(whoami):$(id -gn $(whoami)) ./yay-git && \
# Navigate into yay-git directory
cd yay-git && \
# Build and install the 'yay-git' package. The 'makepkg' command is used to build packages for Arch Linux.
# '-s' flag will resolve and install dependencies.
# '-i' flag will install the package after building.
makepkg -si --noconfirm
```

**Comment by dhaumya** [comment]
@WSHAPER I have read your script and it looks fine but I am out of town so I can't run it right now and I have three questions:

1. Shouldn't `yay -S --version` be above `yay -S udevil mergerfs` and I don't think it need to have the install (-S) flag.
2. Add `sudo` to your last line `systemctl enable casaos`
3. I dont see the point of using `/opt` and not in home `Downloads` and the git clone is practically useless after the install and should be deleted so it doesn't give issues when reinstalling it.

Good Work and Thank you.

**Comment by WSHAPER** [comment]
@dhaumya
Thanks for the valuable feedback! I've updated the comment to:

- Move the `yay --version` command above `yay -S udevil mergerfs` and remove the `-S` flag
- Add `sudo` to `systemctl enable casaos`
- Change the `yay` installation directory to `~/Downloads` and clean up the cloned repository after installation

**Comment by dhaumya** [comment]
@WSHAPER idk about the regulations in this repo but u should probably open a new issue titled "Modify the bash script to include Arch Linux" because this issue was about feedback and has been closed once so I doubt it will be noticed and I shall close it again as I forgot to before.

Thanks again.

**Comment by DealsBeam** [comment]
Thanks for this, im using it to install casaos on orange pi zero 3 4gb running orange pi os (arch)
