### ISSUE TITLE
随身WiFi的Debian11使用CasaOS无法自动挂载USB驱动器

### ISSUE THREAD

**Issue by gujiangjiang** [IceWhaleTech/CasaOS#1036]
CasaOS版本：0.4.3
Linux版本：Debian GNU/Linux 11
内核版本：5.15.0

随身WIFI配置：高通MSM8916，RAM461MB，存储8GB，使用公转母和母数据线拓展充电和数据传输。

CasaOS已设置为自动挂载USB存储器：
<img width="472" alt="image" src="https://user-images.githubusercontent.com/13273955/235301393-9010473a-e5c2-476a-b95e-817fd6a1cb4f.png">

目前可以正常识别优盘、移动硬盘、移动固态，但是均无法自动挂载，磁盘管理里面也看不到信息
<img width="738" alt="image" src="https://user-images.githubusercontent.com/13273955/235301374-dfffc67b-0e29-4a20-b183-9bed237f3ec7.png">

<img width="705" alt="image" src="https://user-images.githubusercontent.com/13273955/235301301-0ce003ad-15b7-4836-ae0e-10164a7ac13a.png">

通过fdisk手动格式化分区，依然无法自动挂载，通过mount命令手动挂载分区后能在磁盘管理里显示为如下：
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13273955/235301339-8282235d-0fcd-43ef-a07b-110bab0acfbf.png">

但是文件管理器里仍然没有：
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/13273955/235301429-2d5c2b57-cc5c-4912-96f6-5e0d6957a5a9.png">

新建本地存储空间也无法选择：
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/13273955/235301473-8b2c2cb1-60ec-4a52-9995-8f8289ccfa0d.png">

所以目前拔掉硬盘后再插上并不会自动挂载，每次都需要手动挂载，然后无法在文件管理器里看到USB设备，只能进手动挂载点才能看到USB驱动器内的文件，如下：（我是手动挂载到/data）
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/13273955/235301553-cc0fb698-1993-4db0-a545-43331cf4eb2a.png">

目前不知道是WIFI棒子的问题，还是Linux版本的问题，还是Linux内核的问题，如果可以的话能修复一下最好。

劳动节快乐！

**Comment by kang000feng** [comment]
请问这个bug修复了吗？我也碰到了同样问题
