### ISSUE TITLE
[Feedback] 怎样重置密码

### ISSUE THREAD

**Issue by sys-liqian** [IceWhaleTech/CasaOS#1037]
### Description

忘记CasaOS密码后，该如何重置密码，或者如何获取到原用户信息

### Additional Information

![image](https://user-images.githubusercontent.com/38576008/235329905-76ac02eb-bb6e-421d-92bf-0596247bbd56.png)

**Comment by raller1028** [comment]
你需要先删除user.db 再重启user-service
命令如下：
```
sudo rm -rf /var/lib/casaos/db/user.db
systemctl restart casaos-user-service.service
```

You need to delete user.db and then restart user-service
The command is as follows:
```
sudo rm -rf /var/lib/casaos/db/user.db
systemctl restart casaos-user-service.service
```

**Comment by raller1028** [comment]
If still have problems please reopen
