### ISSUE TITLE
[Feedback] QB not support ?

### ISSUE THREAD

**Issue by Amychan67899123** [IceWhaleTech/CasaOS#1038]
### Description

![image](https://user-images.githubusercontent.com/111632440/235344782-8040a65c-bcca-4acb-971d-5f51bf4e8476.png)
* 硬件信息-玩客云
CPU 型号 : S805
CPU Model : ARMv7 Processor rev 1 (v7l)
CPU 核心 : 4

OS 版本 : Ubuntu 20.04.6 LTS
内核版本 : 5.15.79-meson
内核详情 : #trunk SMP Fri Nov 18 04:13:49 UTC 2022 armv7l armv7l armv7l GNU/Linux

你好，通过AppStore安装qbittorrent提示不兼容armv7设备，实际qbittorrent兼容的，我已通过其他方式安装并运行。
请检查一下AppStore的匹配逻辑。

**Comment by zhanghengxin** [comment]
In version 4.3, the application version was locked. In version 4.4, third-party stores are now supported, and you can specify the version of the application.
