### ISSUE TITLE
[Feedback]omada controller

### ISSUE THREAD

**Issue by mffa** [IceWhaleTech/CasaOS#1039]
### Description

How install omada conroller in container?
thanks

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 118147 
	 - Disk Used: 4431 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:5355M Core:4 Linux aflitoshome 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 112.0.0.0

**Comment by raller1028** [comment]
You can install omada-controller by running the following command via docker-cli
```
docker run -d \
  --name omada-controller \
  --restart unless-stopped \
  --ulimit nofile=4096:8192 \
  -p 8088:8088 \
  -p 8043:8043 \
  -p 8843:8843 \
  -p 27001:27001/udp \
  -p 29810:29810/udp \
  -p 29811:29811 \
  -p 29812:29812 \
  -p 29813:29813 \
  -p 29814:29814 \
  -e MANAGE_HTTP_PORT=8088 \
  -e MANAGE_HTTPS_PORT=8043 \
  -e PGID="508" \
  -e PORTAL_HTTP_PORT=8088 \
  -e PORTAL_HTTPS_PORT=8843 \
  -e PORT_ADOPT_V1=29812 \
  -e PORT_APP_DISCOVERY=27001 \
  -e PORT_DISCOVERY=29810 \
  -e PORT_MANAGER_V1=29811 \
  -e PORT_MANAGER_V2=29814 \
  -e PORT_UPGRADE_V1=29813 \
  -e PUID="508" \
  -e SHOW_SERVER_LOGS=true \
  -e SHOW_MONGODB_LOGS=false \
  -e SSL_CERT_NAME="tls.crt" \
  -e SSL_KEY_NAME="tls.key" \
  -e TZ=Etc/UTC \
  -v /DATA/AppData/omada/omada-data:/opt/tplink/EAPController/data \
  -v /DATA/AppData/omada/omada-logs:/opt/tplink/EAPController/logs \
  mbentley/omada-controller:5.9
```
![image](https://user-images.githubusercontent.com/57336867/236185899-36282205-8867-4256-9767-55be256da5d3.png)


Then click on import the application on the casaos web ui and select port 8088, wait a moment and you will be able to use the omada-controller normally
![image](https://user-images.githubusercontent.com/57336867/236186243-62df06f6-f69e-4f77-a0b2-18b46ef4dd2c.png)

**Comment by raller1028** [comment]
If still have problems please reopen
