### ISSUE TITLE
[Feedback] SMB共享添加用户验证，主页外部链接排序调整

### ISSUE THREAD

**Issue by lutinglt** [IceWhaleTech/CasaOS#1051]
### Description

1. 希望SMB共享可以添加当前用户的验证，保证一些安全
2. 目前添加的外部链接的所有图标似乎整体视为一个对象，与容器的图标排序要么在所有外部链接前面，要么在所有外部链接后面，所有外部链接本身不能排序，手动排序后不保存刷新丢失，自己按照字符顺序排序，我认为这是一个BUG
1. I hope SMB share can add the current user's authentication to ensure some security
2. Currently added external links of all icons seem to be considered as a whole as an object, with the container icon sorted either in front of all external links or behind all external links, all external links themselves can not be sorted, not save refresh lost after manual sorting, sorted by themselves in the order of characters, I think this is a bug

Translated with www.DeepL.com/Translator (free version)

**Comment by ETWang1991** [comment]
第二个问题我没复现出来，您方便录屏吗？我自己试下来是可以排序的
The second question I did not reproduce, are you convenient to record the screen? I tried it myself and it is sortable

**Comment by lutinglt** [comment]
![Image](https://github.com/IceWhaleTech/CasaOS/assets/131967983/d5808e33-6585-44bf-a3fd-307cca81a5a1)
这些是容器
![Image](https://github.com/IceWhaleTech/CasaOS/assets/131967983/89899773-24dc-421e-a02b-65a42768a963)
这些是外部链接
![Image](https://github.com/IceWhaleTech/CasaOS/assets/131967983/63c7b4cf-76aa-43aa-9213-b52bfa7de797)
这个是录屏的GIF

这边测试容器是可以正常排序的，但是添加的外部链接不是，容器要么在所有外部链接的前面，要么在所有外部链接的后面，外部链接本身是不能排序的，没有走反代，版本是 0.4.3 ，操作系统用的ubuntu 22.04 LTS

**Comment by lutinglt** [comment]
可否在终端日志里在添加一个任务，可以编写命令，有快捷的运行和删除按钮，任务设置选项可以计划执行，或者按一段时间循环执行，然后有记录可以查看运行的时间和结果

**Comment by tigerinus** [comment]
> ![Image](https://user-images.githubusercontent.com/131967983/239565059-d5808e33-6585-44bf-a3fd-307cca81a5a1.png) 这些是容器 ![Image](https://user-images.githubusercontent.com/131967983/239565204-89899773-24dc-421e-a02b-65a42768a963.png) 这些是外部链接 ![GIF 2023-5-19 23-27-01](https://user-images.githubusercontent.com/131967983/239573120-3c3abcfa-c023-4e4e-833a-1da18623ab88.gif) 这个是录屏的GIF
> 
> 这边测试容器是可以正常排序的，但是添加的外部链接不是，容器要么在所有外部链接的前面，要么在所有外部链接的后面，外部链接本身是不能排序的，没有走反代，版本是 0.4.3 ，操作系统用的ubuntu 22.04 LTS

![image](https://github.com/IceWhaleTech/CasaOS/assets/7172560/e6469518-f20c-4a08-b671-90a0de231473)

I can order the app icon in between two external links.

Please try upgrading to v0.4.4 once it is released, and re-open this bug if it is still an issue.

For other issues, please open each separately so it's easier for us to track.
