### ISSUE TITLE
[Bug]  "Sorted" Dashboard Icons do not stay where placed

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS#1052]
**Describe the bug**
 "Sorted" Dashboard Icons do not stay where placed once moved by drag-N-drop UI interface.

**To Reproduce**
1. Go to Dashboard
2. Click and hold on any Icon, then move to a new position
3. Repeat several times with other icons
4. Refresh browser page
5. Notice one or more icons revert back to previous positions in lineup
6. Did not test to see if "External Links" are treated/sorted differently than Docker Container icons

**Expected behavior**
Regardless of Icon type, the dashboard should "remember" where icons were placed immediately after user moves/sorts to a new position. Refreshing browser should not revert icons to any previous location. There seems to be an issue with persistence/permanence by dashboard UI.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Latest Rasbian Lite from Raspberry Pi Foundation]
 - Browser: Tested on both Chrome based (Brave) and MacOS Safari
 - Version: Latest

**Logs**
N/A

**Additional context**
Perhaps a recommended feature would be to show the user a visual page of icon png files when assigning to dashboard tiles.
Especially from Remote and Local sources:
1. Remote: https://icon.casaos.io/main/all/...
2. Remote: https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md
3. Local directory on CasaOS Server: /DATA/Gallery/dashboard-icons
    $ cd /DATA/Gallery
    $ git clone https://github.com/walkxcode/dashboard-icons.git

**Comment by zhanghengxin** [comment]
The sorting issue has been fixed in the new version, which is unrelated to the icon. Thank you for providing the information.

**Comment by zhanghengxin** [comment]
It has now been fixed in 0.4.4.
