### ISSUE TITLE
[Bug on website]  Just misspelled at an email input

### ISSUE THREAD

**Issue by joaquinlarroca** [IceWhaleTech/CasaOS#1054]
**Describe the bug**
In the website _casaos.io_ at the end where you have to enter to email the input text placeholder  says "Enter your emvail"

**To Reproduce**
1. Go to casaos.io
2. Scroll down to the end of the page
4. And see the email input

**Expected behavior**
I expect the correct text "email"

**Screenshots**
![imagen](https://user-images.githubusercontent.com/52870198/236647436-c278dfbe-7cc8-4a37-a310-ef3c38cec142.png)
![imagen](https://user-images.githubusercontent.com/52870198/236647494-cc3acc1c-a679-4b70-9f93-a93a8c3a2aa5.png)
![imagen](https://user-images.githubusercontent.com/52870198/236647513-3508d2ea-696d-45cc-995c-838bb5afd45f.png)

**Desktop (please complete the following information):**
 - OS: win11
 - Browser: firefox

**Comment by raller1028** [comment]
Fixed
