### ISSUE TITLE
[Bug] 代码编辑器自动格式化 The code editor automatically formats the code

### ISSUE THREAD

**Issue by Cp0204** [IceWhaleTech/CasaOS#1055]
**Describe the bug**
1、代码编辑器保存 json 时，强制自动格式化。 When saving a JSON file in the code editor, it is automatically formatted.
2、当 json 有错误时，保存时会自动转义，将会是一场灾难。When there is an error in the JSON file, it is automatically escaped when saved, which can be a disaster.

**To Reproduce**

1. 新建文件 test.json 。Create a new file named test.json.
2. 输入以下内容保存（不换行），将被强制格式化。Enter the following content and save it (No line break), it will be forced to format.
```
[{"tag":"direct","protocol":"freedom"}]
```
![image](https://user-images.githubusercontent.com/5239753/236661815-73ad023c-ad70-4370-a9c9-17c1dbafe3f0.png)

4. 输入以下内容保存，将被强制转义。Enter the following content and save it. It will be forced to escape.
```
[{"tag":"direct","protocol":"freedom"}XXXX]
```
![image](https://user-images.githubusercontent.com/5239753/236661339-2387cdf4-d8ef-4da2-9cc4-99e0df388679.png)

**Expected behavior**
保存时不强制处理，仅做错误提示。
When saving files, only error prompts are given without any forced formatting or escaping.
![image](https://user-images.githubusercontent.com/5239753/236661396-5d040624-7c9c-4b02-86a3-cf841b8482b6.png)

**Desktop (please complete the following information):**
 - CasaOS 0.4.3

**Comment by lixuhai** [comment]
We will fix the forced formatting issue and enable some lang lintting(css, js, html, json, yaml) in the next release
