### ISSUE TITLE
[Feedback]MacOS: Safari browser tab image does not show CasaOS favicon logo

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS#1056]
### Description

Safari browser tab image does not show CasaOS favicon logo. Instead,  shows the icon of the last created docker container. Seems to work as designed in Chrome based browsers.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 14239 
	 - Disk Used: 7702 
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:744M Core:4 Linux RPi2-CUPS 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Safari 
	 - Version: 16.4.1

**Comment by zhanghengxin** [comment]
@rodhammond 
Can you provide the current images?

**Comment by rodhammond** [comment]
Image shows CasaOS tab selected in MacOS Safari browser. The browser tab icon is not CasaOS. This doesn't happen in Chrome browsers.

https://lh3.googleusercontent.com/fjcO7OFB8Db2jKw8V_NnAVDbOvbcO9LDP7WJmqozMECQ3zAZGjZPh8xoc01I0sfrxRZR2JBJ8_3QjcY6D3ZLZfbhOGWuzoNNKJMBoAvcUg=s960


________________________________

**Comment by DareDareHub** [comment]
Same problem here :
Safari browser tab image does not show CasaOS favicon logo. Instead, shows the icon of the last created docker container.
