### ISSUE TITLE
[Feedback]CasaOS "Files" utility does not render *.svg picture files

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS#1057]
### Description

Unlike jpg and png files, the CasaOS "Files" utility does not render *.svg picture files.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 14239 
	 - Disk Used: 7705 
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:744M Core:4 Linux RPi2-CUPS 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Safari 
	 - Version: 16.4.1

**Comment by ETWang1991** [comment]
We'll fix this later

**Comment by rodhammond** [comment]
Hi - Does "To be verified (QA)" mean you are still trying to understand the issue, or the code fix needs to be verified?

**Comment by zhanghengxin** [comment]
It has been fixed in the feature branch, but will be released to the community in the next version.
