### ISSUE TITLE
[Feedback]Issue: Files "Download" zip feature

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS#1059]
### Description

Zipped files are not placed within directory structure within the zip archive. All files appear at root level  instead of being placed within their appropriate subdirectories.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 14239 
	 - Disk Used: 3912 
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:744M Core:4 Linux rpi2-cups 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Safari 
	 - Version: 16.4.1

**Comment by raller1028** [comment]
Thank you for your feedback, this issue has been fixed in v0.4.4
