### ISSUE TITLE
[Feedback] Disallow port change on demo site

### ISSUE THREAD

**Issue by SamBouwer** [IceWhaleTech/CasaOS#1061]
### Description

I was able to change the port setting on the demosite, breaking the site when accessed from the home page.

Steps to reproduce:

1. Open https://casaos.io/
2. Click the "Live demo" button
3. Login using the credentials as shared on the page
4. Go to Settings > Port and change the port to for example 8081
5. ![image](https://user-images.githubusercontent.com/6918900/236819661-64cf5416-1770-4e99-86d0-7f7b473fd022.png)
6. Go back to https://casaos.io/
7. Click the "Live demo" button
8. See that the demo page doesn't load

**Comment by jerrykuku** [comment]
The current demo website is a fully functional CasaOS that allows modification of the web UI port. However, the demo site will automatically reset every hour, and in the future, we will impose some limitations on this feature.
