### ISSUE TITLE
[Feedback]App store list not loading

### ISSUE THREAD

**Issue by joseppires88** [IceWhaleTech/CasaOS#1063]
### Description

while installing any app, it gives an error failed to get app list please refresh.

But nothing happens

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 14668 
	 - Disk Used: 2348 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:909M Core:4 Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 112.0.0.0

**Comment by zhanghengxin** [comment]
This was an issue with the backend service, which was starting up slowly. It has now been fixed.
