### ISSUE TITLE
Magasin d'application non accessible

### ISSUE THREAD

**Issue by COLAS64** [IceWhaleTech/CasaOS#107]
**Describe the bug**

Bonjour, 

Je viens d'installer CasaOS, lorsque je clique sur magasin d'application, rien ne se passe, j'ai un écran qui s'ouvre mais aucune application n'est proposée
Merci

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.8
	 - Disk Total: 42812 
	 - Disk Used: 2067 
	 - Sync State: Sync img: false
	Sync Key length: 0
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:910M Core:2 Linux CasaOs 5.10.0-11-arm64 #1 SMP Debian 5.10.92-1 (2022-01-18) aarch64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 98.0.4758.82

**Comment by leolivier** [comment]
I think if you want to get an answer, you should write your question in English

**Comment by JohnGuan** [comment]
Please use English and re-edit according to the issue template.

**Comment by tigerinus** [comment]
This should no longer be an issue. Please re-open if it still happens.
