### ISSUE TITLE
[Feedback]Default Wallpaper Unavailable After Selection

### ISSUE THREAD

**Issue by iancobb** [IceWhaleTech/CasaOS#1076]
### Description

The default wallpaper--a mountain range in low sunlight--is not available amongst the wallpaper choices.  As far as I can tell, if one selects either of the alternative wallpapers, the default does not replace the now active wallpaper and cannot be re-enabled.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 232587 
	 - Disk Used: 7602 
	 - System Info: [Ubuntu 20.04.6 LTS   \l Bit:64 Mem:12970M Core:12 Linux ethernetermine 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Safari 
	 - Version: 16.0

**Comment by raller1028** [comment]
Thank you for your feedback, that is our earliest wallpaper, now the default options change can not be cut back to the original wallpaper

**Comment by raller1028** [comment]
https://github.com/IceWhaleTech/CasaOS/assets/57336867/67c0a0ae-48cf-4855-8c84-47eefb821a5f

**Comment by pangloss84** [comment]
This is still an issue in version 4.9 for me too 👎

**Comment by gurkanucar** [comment]
same issue, please help :(

**Comment by gurkanucar** [comment]
> This is still an issue in version 4.9 for me too 👎

> Thank you for your feedback, that is our earliest wallpaper, now the default options change can not be cut back to the original wallpaper


Finally found image: https://wall.alphacoders.com/big.php?i=1170832

**Comment by MiguelClydo** [comment]
> > This is still an issue in version 4.9 for me too 👎
> 
> > Thank you for your feedback, that is our earliest wallpaper, now the default options change can not be cut back to the original wallpaper
> 
> Finally found image: https://wall.alphacoders.com/big.php?i=1170832

Give this man a medal
