### ISSUE TITLE
[Feedback]SSH authentication error

### ISSUE THREAD

**Issue by griffinmic88** [IceWhaleTech/CasaOS#1077]
### Description

I can't seem to login to the terminal due to an SSH error, and all my ports are opened on my firewall 22. I can't seem to install apps either. 

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 297898 
	 - Disk Used: 6456 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7537M Core:2 Linux debian1 5.10.0-22-amd64 #1 SMP Debian 5.10.178-3 (2023-04-22) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 113.0.0.0

**Comment by mdstoll** [comment]
Not sure if this solves your issue, but the username and password you enter to login to CasaOS aren't the SSH login credentials. You can login to SSH through port 22 via username **casaos** and password **casaos**.

If this isn't what you were looking for, sorry.
