### ISSUE TITLE
Install on Pi4 with containers

### ISSUE THREAD

**Issue by titou4307** [IceWhaleTech/CasaOS#108]
Hi
I have try the install of CasaOs into my raspberry Pi4 8Go with many containers under Docker (and with Portainer...)

Does it exist an solution/option into CasaOs for to find the "old" containers (installed before install casaOs)

I have not find this solution.....

Other question : 
With the install of CasaOs I have seen a new container installed (in the portainer) who register and transmit data to server (where goes this data, why ??)

Best regard

**Comment by JohnGuan** [comment]
It is already possible to import containers after v0.3.1.

Also, the separately installed container is Syncthing
