### ISSUE TITLE
[Feedback] Add blank app icon to have as template

### ISSUE THREAD

**Issue by charagender** [IceWhaleTech/CasaOS#1083]
Hi! So, while trying to create an icon for a new app, I noticed I couldn't just overlay the logo onto another app's icon, so I'd like to request a "blank" icon image to have as template for new apps.

This is a problem I first encountered while working on MineOS, but worked around by overlaying its logo on top of the Syncthing's app logo.

The problem is that the icon background is a gradient, so it's not as simple as selecting a color from the image and painting over another app's logo. I've attached an image of Syncthing's logo, and a very crude attempt at painting over it so the problem can be better observed.

![icon](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/129703415/2829a4ca-b5c1-4947-a14f-09664268395d)
![problem](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/129703415/d41ef899-f2fe-43eb-9b8b-4f95e210d54f)

**Comment by tigerinus** [comment]
Transferred the issue here from CasaOS-AppStore because it's not app specific.

**Comment by ETWang1991** [comment]
@charagender 
[CasaStoreicon.zip](https://github.com/IceWhaleTech/CasaOS/files/11754961/CasaStoreicon.zip)

**Comment by ETWang1991** [comment]
[CasaStoreicon.zip](https://github.com/IceWhaleTech/CasaOS/files/11755030/CasaStoreicon.zip)
@charagender

**Comment by charagender** [comment]
> @charagender [CasaStoreicon.zip](https://github.com/IceWhaleTech/CasaOS/files/11754961/CasaStoreicon.zip)
That's perfect, thank you!
