### ISSUE TITLE
[Feedback]问题

### ISSUE THREAD

**Issue by joker-or-king** [IceWhaleTech/CasaOS#1089]
### Description

卸载应用或部署应用失败后都产生多余的文件.在root/data/appdata里

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 29558 
	 - Disk Used: 6862 
	 - System Info: [Ubuntu 20.04.6 LTS   \l Bit:64 Mem:1878M Core:2 Linux k 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Edge 
	 - Version: 113.0.1774.42

**Comment by LinkLeong** [comment]
Can you list a detailed application?

**Comment by LinkLeong** [comment]
We will close the issue and reopen it if you have any questions.
