### ISSUE TITLE
[Issue] Connect network storage only supports "simple" passwords

### ISSUE THREAD

**Issue by iAlchemy** [IceWhaleTech/CasaOS#1095]
### Description

It seems that connecting to network storage only works for "guest" and if the password does not contain any special characters.  Why?

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 15010 
	 - Disk Used: 5948 
	 - System Info: [Ubuntu 22.04.2 LTS   \l Bit:64 Mem:1975M Core:2 Linux casaos 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 113.0.0.0

**Comment by iAlchemy** [comment]
Connect network storage only "appears" to work. It accepts a path, username and password then creates a mount point for the host and correctly shows the Shares but no content. 

Also ... why is the IPC$ "share" shown?

**Comment by zhanghengxin** [comment]
> ### Description
> It seems that connecting to network storage only works for "guest" and if the password does not contain any special characters. Why?看来，连接到网络存储只适用于“客人”，如果密码不包含任何特殊字符。为什么？
> 
> ### Additional Information 其他信息
> ```
>  - OS: linux
>  - CasaOS Version: 0.4.3
>  - Disk Total: 15010 
>  - Disk Used: 5948 
>  - System Info: [Ubuntu 22.04.2 LTS   \l Bit:64 Mem:1975M Core:2 Linux casaos 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
>  - Remote Version: 0.4.3
>  - Browser: Chrome 
>  - Version: 113.0.0.0
> ```

 Special characters can pose security risks.

**Comment by zhanghengxin** [comment]
> Connect network storage only "appears" to work. It accepts a path, username and password then creates a mount point for the host and correctly shows the Shares but no content.连接网络存储只有“看起来”工作。它接受路径、用户名和密码，然后为主机创建装载点，并正确显示共享，但不显示内容。
> 
> Also ... why is the IPC$ "share" shown?还有...为什么显示IPC$“share”？



> Connect network storage only "appears" to work. It accepts a path, username and password then creates a mount point for the host and correctly shows the Shares but no content.连接网络存储只有“看起来”工作。它接受路径、用户名和密码，然后为主机创建装载点，并正确显示共享，但不显示内容。
> 
> Also ... why is the IPC$ "share" shown?还有...为什么显示IPC$“share”？

If it's not a related issue, it's recommended to create a new issue for your question. You may need to confirm if the network storage requires authentication.

**Comment by iAlchemy** [comment]
Yes ... that's my point. Network Storage does require authentication and when I connect the error says "Special Characters are a security risk" which simply does not make sense as it's a very common if not mandatory requirement when setting a password. 

When I changed the password on the Network Storage to not include special characters the share "mounts" but does not show any content.

Happy to raise a separate issue ... "Mounting Network Storage does not work".

**Comment by cleanmachine** [comment]
Using a PW with special characters to connect to local storage is still broken. I am attempting to connect to my local storage server and yes, my PW uses special characters. "Special characters may cause security problems" is the message that pops up. 

Special characters is a good and standard security practice and definitely NOT a security risk.
