### ISSUE TITLE
[Feature Request] Add support to a Portainer-like custom app templates list

### ISSUE THREAD

**Issue by WisdomSky** [IceWhaleTech/CasaOS#1105]
**Is your feature request related to a problem? Please describe.**
The current listing in the AppStore is very limited and adding multiple docker containers requires us to enter them manually one by one.

**Describe the solution you'd like**
Portainer has this feature where it allows us to set a json file which is like a "directory" of apps which allows us to search through the listed apps in the json and deploy them easily. 

The only limitation with the implementation of portainer is that you can only set one app template json at a time, so if there is an another json file built by someone else that contains an app that you needed, you would need to change the json file url in the portainer settings in order to see that app that you needed in the portainer apps list. 
But this can be solved by using using [Portainer Tools](https://www.technorabilia.com/portainer-tools-merge-and-host-app-template-definitions/) which allows us to merge multiple json files into a single one so that we don't have to manually change the json file url in the portainer settings if ever we want to load an another list. We just have to open portainer tools and add that new url into the list and generate a new merged json file. 

It would be awesome if CasaOS can implement something the same to gives more flexibility and this will also encourage the community to create and maintain a directory of apps that can be shared to everyone. If ever the CasaOS team decides to implement this. It would also be a good idea it would allow us to put multiple json file urls rather than just with one (like the portainer did), and also implement a deduping algorithm to rid of duplicate entries if there are any. Portainer Tools' doesn't rid of duplicates when 2 or more lists have same entries, so if you added 3 lists, and all of them contain Sonarr, then the portainer app templates list will show those three which can cause confusion.
 It would also be more awesome if the team can utilize the current json format used in portainer app templates json as there are tons of lists out there that are already maintained by the community, so that we just have to re-use portainer app templates lists that we are using.

**Describe alternatives you've considered**
No alternatives

**Additional context**

app templates setting:
![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/d9755069-3d58-4afc-a79a-e78676a0c53b)

contents of the json file:
![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/e255d537-1158-43f5-b676-e6b48b90108e)

portainer app templates list (generated from the json):
![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/1c9c3863-3caa-44ee-8881-62e3e525357b)

**Comment by tigerinus** [comment]
@WisdomSky - Not exactly the same, but since v0.4.4 - 3rd party CasaOS AppStore is possible.

E.g. https://github.com/tigerinus/yet-another-casaos-appstore

This idea gives people an option to share and promote their own apps without involving CasaOS team.

**Comment by WisdomSky** [comment]
@tigerinus 

How do you exactly activate it? I've tried adding it to see if it works and it does get downloaded into `/var/lib/casaos/appstore` but when I open the appstore in the WebUI, I can't see the two example apps (ElastiSearch and Flink) in there. 
I've also already tried restarting CasaOS, but still they don't reflect in the appstore.
