### ISSUE TITLE
[Feedback]Feature Request —- Installing Nextcloud to Rapberry PI with Maria DB and on External USB

### ISSUE THREAD

**Issue by inhousejay** [IceWhaleTech/CasaOS#1112]
### Description

I am a newbie and I am stuck on how to install Nextcloud app from casaos but when I try to install it it defaults to sql lite I want to have it install with MariaDB and to an attached USB drive on the PI. I dont know whether I should just have the data on the external drive or also have the program also.  Any help would be greatly appreciated. Maybe something in the code of the install giving a choice. I know there is nextcloudpi which gives you a choice of where to install.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 29768 
	 - Disk Used: 2414 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:3794M Core:4 Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Safari 
	 - Version: 16.0

**Comment by zhanghengxin** [comment]
In version 0.4.4, Compose is fully supported. 

please visit:https://github.com/docker/awesome-compose/tree/master/nextcloud-postgres  OR 
https://github.com/docker/awesome-compose/tree/master/nextcloud-redis-mariadb

**Comment by zhanghengxin** [comment]
My suggestion is to install version 0.4.4 and then import and install the Compose file from the link I provided using CasaOS. However, please note that there are significant changes in version 0.4.4, so I recommend checking the changelog before deciding whether to upgrade.

If you don't want to upgrade, you can follow these steps, but you will need to do some searching:
0. update CasaOS to 0.4.4-alpha
1. Use the wget or curl command to fetch the Compose file (e.g., the link I provided: https://raw.githubusercontent.com/docker/awesome-compose/master/nextcloud-redis-mariadb/compose.yaml).
2. Run the docker-compose command to start the above file.

**Comment by inhousejay** [comment]
I want to make sure I am clear on your instructions. I have been reading and studying. You spoke about upgrading to 0.4.4 first. I noticed there are a few alpha versions and i am not sure if I should upgrade through CasaOS or if I should open a terminal window in CasaOS and upgrade it that way. I am also not sure which one to use since I think Raspberry pi is arm64 and not sure how to do this with docker. I think docker was installed with CasaOS but not sure the command to use it. Sorry for being such a newbie on this I have been trying many things for the better part of a month and it has been hard. Sorry I seem like a slow learner.Sent from my iPadOn May 24, 2023, at 4:50 AM, zhanghengxin ***@***.***> wrote:﻿
My suggestion is to install version 0.4.4 and then import and install the Compose file from the link I provided using CasaOS. However, please note that there are significant changes in version 0.4.4, so I recommend checking the changelog before deciding whether to upgrade.
If you don't want to upgrade, you can follow these steps, but you will need to do some searching:
0. update CasaOS to 0.4.4-alpha

Use the wget or curl command to fetch the Compose file (e.g., the link I provided: https://raw.githubusercontent.com/docker/awesome-compose/master/nextcloud-redis-mariadb/compose.yaml).
Run the docker-compose command to start the above file.

**Comment by raller1028** [comment]
@inhousejay 
Hello, based on your request, I have split it into three parts for you:
1.Installing Nextcloud and MariaDB on an external USB.
2.Installing MariaDB.
3.Installing Nextcloud and configuring it to use MariaDB.

Since your Raspberry Pi is based on the ARM64 architecture, I will also try to guide you through the installation of MariaDB and Nextcloud on an ARM64 system.
Regarding the first part, I don't recommend doing it unless your Raspberry Pi's internal storage is very limited.
For the second part, I would like to clarify whether you must install MariaDB using Docker on your Raspberry Pi or if you already have your own MariaDB setup.
As for the third part, you can simply install Nextcloud and then select MariaDB in the configuration page, where you will provide the database address, username, and password.

I hope this information is helpful to you.

**Comment by raller1028** [comment]
If still have problems, please reopen

**Comment by inhousejay** [comment]
Hi -Yes still having problems I have been trying to read and try different methods to solve this problem. Right now I have been able to install Casaos04.4 but the big problem before I go to far is that I have Casaos and pi software installed on the 32gb and I want to install everything on a 1TB San disk external SSD so that I can use it without a problem in the future. I have done many thing but I cannot get it to boot from the USB. I am thinking that it is possibly because the SSD is not externally powered because I have tried a number of ways. Thanks for the info about reopening I have to learn how to do that. Although I have been using computers for 40 years I really feel like a real newbie when it comes to this.  I have tried youtube videos but they have not been too much help since some are unwatchable since they dont go step by step and others just miss the issue for me or doesn't solve the problem.Thanks again Jay Passarella (Inhousejay)Sent from my iPadOn Jun 13, 2023, at 2:37 AM, raller1028 ***@***.***> wrote:﻿
If still have problems, please reopen

**Comment by inhousejay** [comment]
Hi -

Yes still having problems I have been trying to read and try different methods to solve this problem. Right now I have been able to install Casaos04.4 but the big problem before I go to far is that I have Casaos and pi software installed on the 32gb and I want to install everything on a 1TB San disk external SSD so that I can use it without a problem in the future. I have done many thing but I cannot get it to boot from the USB. I am thinking that it is possibly because the SSD is not externally powered because I have tried a number of ways. Thanks for the info about reopening I have to learn how to do that. Although I have been using computers for 40 years I really feel like a real newbie when it comes to this.  I have tried youtube videos but they have not been too much help since some are unwatchable since they dont go step by step and others just miss the issue for me or doesn't solve the problem.
Thanks again 
Jay Passarella (Inhousejay)

**Comment by zhanghengxin** [comment]
@ETWang1991  he need a tutorial.

**Comment by jerrykuku** [comment]
Hi，you can follow this tutorial to learn how to boot from  a USB device.
https://www.tomshardware.com/how-to/boot-raspberry-pi-4-usb 
At the same time I think this seems to be beyond the scope of CasaOS support. If you don't mind, I'd like to close this Issue with your permission.

**Comment by inhousejay** [comment]
Hi -I did try that and it didn’t work. I don’t know if it was the Samsung device I used or something else. Yes you may close this since I have decided to tackle this problem with a different solution.Sent from my iPadOn Sep 3, 2023, at 12:28 PM, 老竭力 ***@***.***> wrote:﻿
Hi，you can follow this tutorial to learn how to boot from  a USB device.
https://www.tomshardware.com/how-to/boot-raspberry-pi-4-usb
At the same time I think this seems to be beyond the scope of CasaOS support. If you don't mind, I'd like to close this Issue with your permission.

**Comment by jerrykuku** [comment]
I hope you can finally resolve this issue. I will close this issue.
