### ISSUE TITLE
[Feedback][Issue] Jackett app installation stuck 83%

### ISSUE THREAD

**Issue by JuhaFIN1** [IceWhaleTech/CasaOS#1114]
### Description

Installed many other apps with no problem but Jackett install stuck 83%. 
Reboot done, no hope. Install again same 83%.
Proxmox / CT / Debian 11, apt update done. Hard disk 60gb, so no space issue.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 92160 
	 - Disk Used: 1643 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:4096M Core:2 Linux casaos 5.15.107-2-pve #1 SMP PVE 5.15.107-2 (2023-05-10T09:10Z) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Edge 
	 - Version: 113.0.1774.50

**Comment by WisdomSky** [comment]
if there's an app that doesn't install using the CasaOS appstore, what I do is use portainer to install it. portainer seems doesn't have a problem installing any docker image. I'm not sure with how CasaOS installs docker images using the appstore, but it seems a little bit unstable compared to portainer,

**Comment by raller1028** [comment]
[Jackett.zip](https://github.com/IceWhaleTech/CasaOS/files/11551361/Jackett.zip)
Can you try importing my jackett.json in a custom installation?

**Comment by m1ntyduck** [comment]
I have exactly the same issue in Proxmox/ ct / debian 11.
Odd I've set it up a few times in the same node/system in testing; now I need, typically it has an issue.

I tried to manually import - same issue.

**Comment by m1ntyduck** [comment]
Created a new container using turnkey core image and get the same outcome - hangs at 83%

**Comment by m1ntyduck** [comment]
A few hours later it just worked...

**Comment by raller1028** [comment]
This will be closed for now, if you still have problems please reopen it.
