### ISSUE TITLE
[Issue] Connect Network Storage - Administrative Shares should not show

### ISSUE THREAD

**Issue by iAlchemy** [IceWhaleTech/CasaOS#1115]
### Description

When connecting network storage the Administrative Share IPC$ should not be added or exposed in the File Browser app as it servers no purpose with respect to the File Browser app.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 225140 
	 - Disk Used: 2631 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7811M Core:4 Linux casaos 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 113.0.0.0

**Comment by raller1028** [comment]
This issue will be fixed in the next version

**Comment by LinkLeong** [comment]
We fixed this issue in version 0.4.4-alpha, you can update this version manually. If you still have problems, please reopen this question.
