### ISSUE TITLE
App 

### ISSUE THREAD

**Issue by CipriyoYT** [IceWhaleTech/CasaOS#112]
**Describe the bug**

Imposible d'ouvrir le magasin des apps

**System infomation**

**Comment by dan3577** [comment]
me too

**Comment by JohnGuan** [comment]
Please use English and re-edit according to the issue template.

**Comment by CosmoFox** [comment]
Multiple versions have been released, does this problem still exist?

**Comment by AuthorShin** [comment]
If @CipriyoYT and @dan3577 still have the problem you guys can open a new issue.
