### ISSUE TITLE
[Alpha][Bug] external link messed up after upgrade to 0.4.4

### ISSUE THREAD

**Issue by sikman5** [IceWhaleTech/CasaOS#1122]
### What happened?

Just doing some bug hunting, Found that all of my external links changed to random character strings, Went to fix them and am locked out of renaming, Removed them and added  back to a different set of random characters, Can't update settings on existing docker containers unless a full reinstall is complete, also every time I update a setting it creates a clone then removes the cloned container. If I find anything else I will provide updates (alpha 0.4.4)

### Screenshots

![image](https://github.com/IceWhaleTech/CasaOS/assets/24449820/e0482337-6b4f-4c54-bce0-8990922c56d6)

![image](https://github.com/IceWhaleTech/CasaOS/assets/24449820/6148aaba-33d2-4d13-8169-474a1451d823)

![image](https://github.com/IceWhaleTech/CasaOS/assets/24449820/b3d79bf7-5b40-491b-8ad5-8ea6df7fd833)

![image](https://github.com/IceWhaleTech/CasaOS/assets/24449820/5e606d64-882a-4a6a-a466-4a9ce3787517)

**Comment by zhanghengxin** [comment]
After reviewing the code, this does not appear to be an issue with the "LinkApp" section, but rather with the container application. It is also possible that I have misunderstood the issue, as the attached image does not seem to correspond to "LinkApp" at the moment.

**Comment by sikman5** [comment]
I tried to change the names again after removing the links, same problem it changes the name for maybe 5 seconds and then goes back to the character strings, Could it be a database issue not updating it correctly? It looks like its some sort of hash code

**Comment by sikman5** [comment]
Another issue just occurred when i updated the URL of the external application, It is now duplicating them whenever i save a new variant of it.

**Comment by raller1028** [comment]
ok, we have found that the random character strings problem is caused by an upgrade and we will fix it as soon as possible.
Can you describe the second question in more detail, or with a video or pictures?

**Comment by sikman5** [comment]
https://www.youtube.com/watch?v=-uTWcakrkJc

**Comment by sikman5** [comment]
Here is the second issue, https://www.youtube.com/watch?v=-uTWcakrkJc If you need anything more please let me know!

**Comment by IaonnisPrysma** [comment]
Can also confirm both of these bugs happened to me also, just upgraded today
