### ISSUE TITLE
File UI fails to upload  if Subinterfaces (VLAN) are enabled. 

### ISSUE THREAD

**Issue by fnetto** [IceWhaleTech/CasaOS#1123]
### Description

2023-05-24T16:55:17.211-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-24T16:55:29.755-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-24T16:55:36.157-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 27712 
	 - Disk Used: 12743 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 113.0.0.0

**Comment by raller1028** [comment]
How did you run this casaos and where did you see this log?

**Comment by fnetto** [comment]
CasaOS running on a ZimaBoard 832 internal Storage.
SSH into OS 
sudo su
cat /var/log/casaos/log.log | grep error

**Comment by fnetto** [comment]
Perhaps this is a file size limitation?  I am able to upload extremely small files. With various extensions.  But the one that I really need ~151KB fails...

**Comment by fnetto** [comment]
root@CasaOS:/var/log/casaos# tail -f log.log | grep error
2023-05-25T18:25:41.025-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-25T18:26:00.225-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-25T18:29:43.201-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-25T18:30:02.145-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-25T18:35:49.025-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-25T18:35:49.025-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-25T18:36:14.881-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
2023-05-25T18:36:15.905-0400    error   path should not be empty        {"func": "v1.PostFileUpload", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/file.go", "line": 519}
^C
root@CasaOS:/var/log/casaos# date
Thu May 25 06:36:48 PM EDT 2023

**Comment by raller1028** [comment]
ok this problem is understood, as a temporary solution can you try refreshing the page and re-uploading it?

**Comment by fnetto** [comment]
With just a page refresh it still fails.
Uploading very small files it works.

**Comment by fnetto** [comment]
Got a new Zimaboard, same model so I can try finding the issue.
Following each step performed on first board what causes the issue is when adding vlans.

As example:

root@CasaOS:/home/casaos# cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

#auto enp2s0
# The first VLAN interface
auto enp2s0.100
iface enp2s0.100 inet static
    address 10.10.100.251
    netmask 255.255.255.0
    gateway 10.10.100.254
#
auto enp2s0.101
iface enp2s0.101 inet static
    address 10.10.101.251
    netmask 255.255.255.0
    gateway 10.10.101.254
#
iface enp2s0.102 inet static
    address 10.10.102.251
    netmask 255.255.255.0
    gateway 10.10.102.254
#
iface enp2s0.103 inet static
    address 10.10.103.251
    netmask 255.255.255.0
    gateway 10.10.103.254

**Comment by fnetto** [comment]
root@CasaOS:/home/casaos# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    0      0        0 enp2s0.100
default         _gateway        0.0.0.0         UG    100    0        0 enp2s0
10.10.10.0      0.0.0.0         255.255.255.0   U     100    0        0 enp2s0
10.10.100.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.100
10.10.101.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.101
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0

**Comment by raller1028** [comment]
Would you like to provide us with the file you uploaded so we can try it out?

**Comment by raller1028** [comment]
It may be necessary to provide the local file path for uploading, as well as specify the destination path for the upload.

**Comment by fnetto** [comment]
Unfortunately it is a config file for UniFi Controller, so I will kindly say no please.
But what I am finding out is to do with the networking setup.  Reviewing setup right now as the issue does not happen with a zimaboard right out of the box..

**Comment by fnetto** [comment]
Okay, so the problem is definitely with VLAN Enabled.
DO you know how to stop adding default route on subinterfaces (VLAN) as I am finding out that upload works is route table has only one default route.  But when I issue an ifup it adds default route...

**Comment by fnetto** [comment]
Okay, there is something else than just default route.
Again, is no VLANs are enabled it works.
But my latest test failed with the following config:

auto enp2s0.100
iface enp2s0.100 inet static
    address 10.10.100.251
    netmask 255.255.255.0
#    gateway 10.10.100.254
#
#
auto enp2s0.101
iface enp2s0.101 inet static
    address 10.10.101.251
    netmask 255.255.255.0
#    gateway 10.10.101.254
#
#
auto enp2s0.102
iface enp2s0.102 inet static
    address 10.10.102.251
    netmask 255.255.255.0
#    gateway 10.10.102.254
#
#
auto enp2s0.103
iface enp2s0.103 inet static
    address 10.10.103.251
    netmask 255.255.255.0
#    gateway 10.10.103.254
root@CasaOS:/home/casaos#
root@CasaOS:/home/casaos# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 enp2s0
10.10.10.0      0.0.0.0         255.255.255.0   U     100    0        0 enp2s0
10.10.100.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.100
10.10.101.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.101
10.10.102.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.102
10.10.103.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.103
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
root@CasaOS:/home/casaos#

Then if I down interfaces it uploads successfully again.
root@CasaOS:/home/casaos# ifdown enp2s0.100
root@CasaOS:/home/casaos# ifdown enp2s0.101
root@CasaOS:/home/casaos# ifdown enp2s0.102
root@CasaOS:/home/casaos# ifdown enp2s0.103
root@CasaOS:/home/casaos# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 enp2s0
10.10.10.0      0.0.0.0         255.255.255.0   U     100    0        0 enp2s0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0

**Comment by raller1028** [comment]
Maybe you need chatGPT@@,Here is the answer I obtained by asking GPT based on your previous question. I hope it is helpful to you.

To prevent the addition of a default route on subinterfaces (VLAN) when using the ifup command, you can modify the network configuration file for the specific interface. Here's how you can achieve that:

Identify the network configuration file associated with the subinterface/VLAN you want to modify. The configuration files are usually located in the /etc/network/interfaces.d/ directory or directly in the /etc/network/interfaces file.

Open the relevant network configuration file using a text editor.

Look for the configuration section related to the subinterface/VLAN you want to modify. It may look something like this:


```
auto eth0.10
iface eth0.10 inet static
    address 192.168.0.10
    netmask 255.255.255.0
```
To prevent the addition of a default route, you need to add the post-up directive followed by the ip route delete default command. This will delete the default route after the interface is brought up. Here's an example:


```
auto eth0.10
iface eth0.10 inet static
    address 192.168.0.10
    netmask 255.255.255.0
    post-up ip route delete default
```
Save the configuration file and exit the text editor.

Restart the network service or bring down and then bring up the specific subinterface/VLAN for the changes to take effect. You can use the ifdown and ifup commands for this purpose.

By adding the post-up directive with the ip route delete default command, you are instructing the system to delete the default route after the interface is brought up, effectively preventing the addition of a default route specifically for that subinterface/VLAN.

**Comment by fnetto** [comment]
Here is the latest...
With this config file upload fails:

` 
root@CasaOS:/home/casaos# cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

#auto enp2s0
auto enp2s0.100
iface enp2s0.100 inet static
    address 10.10.100.251
    netmask 255.255.255.0
    gateway 10.10.100.254
    post-up ip route delete default
#
#
auto enp2s0.101
iface enp2s0.101 inet static
    address 10.10.101.251
    netmask 255.255.255.0
    gateway 10.10.101.254
    post-up ip route delete default
#
#
auto enp2s0.102
iface enp2s0.102 inet static
    address 10.10.102.251
    netmask 255.255.255.0
    gateway 10.10.102.254
    post-up ip route delete default
#
#
auto enp2s0.103
iface enp2s0.103 inet static
    address 10.10.103.251
    netmask 255.255.255.0
    gateway 10.10.103.254
    post-up ip route delete default
root@CasaOS:/home/casaos# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         _gateway        0.0.0.0         UG    100    0        0 enp2s0
10.10.10.0      0.0.0.0         255.255.255.0   U     100    0        0 enp2s0
10.10.100.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.100
10.10.101.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.101
10.10.102.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.102
10.10.103.0     0.0.0.0         255.255.255.0   U     0      0        0 enp2s0.103
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0

`

So, just to be clear, the UI for Files in CasaOS fails only when these subinterfaces are enabled, if I down the subinterfaces the file can upload files successfully. 

Suggestions?

Thanks,

**Comment by fnetto** [comment]
Any suggestions?

**Comment by tigerinus** [comment]
@fnetto - I tried to reproduce this locally but I don't see any problem with file upload.

Can you check if anything is missing in my configs?

```
dietpi@DietPi:~$ cat /etc/network/interfaces
# Location: /etc/network/interfaces
# Please modify network settings via: dietpi-config
# Or create your own drop-ins in: /etc/network/interfaces.d/

# Drop-in configs
source interfaces.d/*

# Ethernet
allow-hotplug eth0
iface eth0 inet dhcp
address 192.168.0.100
netmask 255.255.255.0
gateway 192.168.0.1
#dns-nameservers 9.9.9.9 149.112.112.112

# WiFi
#allow-hotplug wlan0
iface wlan0 inet dhcp
address 192.168.0.100
netmask 255.255.255.0
gateway 192.168.0.1
#dns-nameservers 9.9.9.9 149.112.112.112
wireless-power off
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

auto eth0.100
iface eth0.100 inet static
    address 10.10.100.251
    netmask 255.255.255.0
    gateway 10.10.100.254
#
auto eth0.101
iface eth0.101 inet static
    address 10.10.101.251
    netmask 255.255.255.0
    gateway 10.10.101.254
#
iface eth0.102 inet static
    address 10.10.102.251
    netmask 255.255.255.0
    gateway 10.10.102.254
#
iface eth0.103 inet static
    address 10.10.103.251
    netmask 255.255.255.0
    gateway 10.10.103.254
dietpi@DietPi:~$
dietpi@DietPi:~$ routel
Dst             Gateway         Prefsrc         Protocol Scope   Dev              Table
default         192.168.0.1                                      eth0
10.10.100.0/24                  10.10.100.251   kernel   link    eth0.100
10.10.101.0/24                  10.10.101.251   kernel   link    eth0.101
172.17.0.0/16                   172.17.0.1      kernel   link    docker0
192.168.0.0/24                  192.168.0.25    kernel   link    eth0
10.10.100.251                   10.10.100.251   kernel   host    eth0.100         local
10.10.100.255                   10.10.100.251   kernel   link    eth0.100         local
10.10.101.251                   10.10.101.251   kernel   host    eth0.101         local
10.10.101.255                   10.10.101.251   kernel   link    eth0.101         local
127.0.0.0/8                     127.0.0.1       kernel   host    lo               local
127.0.0.1                       127.0.0.1       kernel   host    lo               local
127.255.255.255                 127.0.0.1       kernel   link    lo               local
172.17.0.1                      172.17.0.1      kernel   host    docker0          local
172.17.255.255                  172.17.0.1      kernel   link    docker0          local
192.168.0.25                    192.168.0.25    kernel   host    eth0             local
192.168.0.255                   192.168.0.25    kernel   link    eth0             local
dietpi@DietPi:~$
```

**Comment by tigerinus** [comment]
@fnetto I'm closing this issue but if you can provide more information of how to reproduce this issue, please feel free to re-open
