### ISSUE TITLE
[Bug] No temperatures or wattage usage on a Ryzen 3 3200U (Debian 11 minimal)

### ISSUE THREAD

**Issue by IaonnisPrysma** [IceWhaleTech/CasaOS#1125]
**Describe the bug**
CasaOS shows no CPU temp info, shows as "0" and no W info at all (when just fresly installed the "0 W" mark appeared alongside the "0 C" mark, but after a system restart it just was gone forever.

**To Reproduce**
1. Install Debian 11 with just Open SSH and Basic Applications, no Desktop.
2. After setting up CasaOS with the usual command, CPU Temp says 0 c (Centigrade grades) and no Watts usage is reported (CPU and MoBo do have the sensors.

**Expected behavior**
CasaOS to show CPU temperature and Watts usage for usual and expected monitoring capabilities.

**Screenshots**
![image](https://github.com/IceWhaleTech/CasaOS/assets/134575902/e104d2bd-ab8c-4596-9c45-5ef5acff6978)

**Desktop (please complete the following information):**
 - OS: Linux 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64
 - Browser: Firefox Stable
 - Version 113.01 (64bits)

**Logs**

run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
[log1.txt](https://github.com/IceWhaleTech/CasaOS/files/11561176/log1.txt)

sudo journalctl -xef -u casaos-user-service
[log2.txt](https://github.com/IceWhaleTech/CasaOS/files/11561177/log2.txt)

sudo journalctl -xef -u casaos-local-storage
[log3.txt](https://github.com/IceWhaleTech/CasaOS/files/11561179/log3.txt)

sudo journalctl -xef -u casaos.service
[log4.txt](https://github.com/IceWhaleTech/CasaOS/files/11561180/log4.txt)

```

**Additional context**
Maybe some debian/linux packet the feature relies on is missing? If so can you share this information and add it to the readme or wiki so it is easier in the future for people with this issue

**Comment by raller1028** [comment]
sorry, this temperature display currently only supports intel cpu

**Comment by IaonnisPrysma** [comment]
Thanks! I've been monitoring it with linux alternatives, still would be amazing to have this working someday
