### ISSUE TITLE
[Feature request] Sheduling apps to turn on and shutdown at given times

### ISSUE THREAD

**Issue by IaonnisPrysma** [IceWhaleTech/CasaOS#1127]
**Is your feature request related to a problem? Please describe.**

I'm actually using CasaOS for a variety of things, one of them is game servers, which consume a good amount of power when on. But I also use it as a File cloud and a DDNS updater, two features... I wouldn't like to sacrifice, and having to turn on and off game servers is... Not bad but a scheduling feature for apps would be fantastic, I don't know if this is already on CasaOS, as it's said nowhere on Wiki or documentation.

**Describe the solution you'd like**

A way inside apps to shedule a "turn on" and "turn off" time

**Comment by raller1028** [comment]
You can try filebrowser and duckdns or other docker applications for file cloud and DDNS updater

**Comment by ETWang1991** [comment]
Is there a Docker that can control the opening and closing of other Dockers, if so, it is a good idea to put it online to the APPStore. But as a system, casa will consider this requirement @IaonnisPrysma

**Comment by raller1028** [comment]
If still have problems, please reopen
