### ISSUE TITLE
 We need a tool that can convert the exported appfile.json to a compose file. 

### ISSUE THREAD

**Issue by zhanghengxin** [IceWhaleTech/CasaOS#1128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Add an option to "Export as Compose" in the feature menu of the legacy application. 

**Additional context**

**Comment by tigerinus** [comment]
an API `/v2/app_management/convert` and a CLI `appfile2compose` will be available upon next v0.4.4 alpha release.
