### ISSUE TITLE
[Alpha][Bug] Check and update for old apps

### ISSUE THREAD

**Issue by CosmoFox** [IceWhaleTech/CasaOS#1129]
### What happened?

Apps, that installed before alpha 0.4.4 lost function "Check then update" and other. There are only Open and Delete.

### Screenshots

![image](https://github.com/IceWhaleTech/CasaOS/assets/9054349/ee171e14-5d37-4a59-ac55-e230255a1d34)

**Comment by tigerinus** [comment]
This is by design of v0.4.4 - we want to deprecate legacy app format by the new docker compose format.

You can install the corresponding compose app in the AppStore. The compose app has option to upgrade.
