### ISSUE TITLE
Pi Hole

### ISSUE THREAD

**Issue by richardmunoz** [IceWhaleTech/CasaOS#113]
**Describe the bug**

Pi hole is not opening keep saying check proxy settings and I don't use a proxy, it is actually turned off, is there something else I can do?

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.9
	 - Disk Total: 58426 
	 - Disk Used: 4805 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7813M Core:4 Linux raspberrypi 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux]
	 - Browser: Edge 
	 - Version: 98.0.1108.56

**Comment by NespoliBT** [comment]
I've had the same problem on my arch machine. It seems like the leatest pihole release is buggy.
You sould try installing a previous version. v5.6 works fine for me.

**Comment by JohnGuan** [comment]
Does this problem still exist?

**Comment by AuthorShin** [comment]
I'm going to close this for now assuming the problem has been solved otherwise @richardmunoz can open a new issue.
