### ISSUE TITLE
[Alpha][Bug] Custom app install failed + many errors

### ISSUE THREAD

**Issue by CosmoFox** [IceWhaleTech/CasaOS#1131]
### What happened?

Trying install Plex manualy:
1. Every click or keypress - lots of errors in console. (see screenshot)
2. On click "Install" got another error in popup (see second screenshot)

### Screenshots

![image](https://github.com/IceWhaleTech/CasaOS/assets/9054349/a85104b4-ebbd-4a25-ac02-bc788086094b)
![image](https://github.com/IceWhaleTech/CasaOS/assets/9054349/4d77f40d-32c3-4dae-9489-247ccf7c34e1)

**Comment by zhanghengxin** [comment]
please give us a file which your installing.
Please provide the file you are trying to install.

**Comment by zhanghengxin** [comment]
@CosmoFox An issue should focus on a single problem. 
These two images are not related to the same issue. To improve the second issue, we need to know your expectations.

**Comment by CosmoFox** [comment]
> Please provide the file you are trying to install. 

No file. Manual input only.

**Comment by zhanghengxin** [comment]
0.4.4 @latest

reinstall it.
