### ISSUE TITLE
[Feedback] Register Appstore command verbose output

### ISSUE THREAD

**Issue by WisdomSky** [IceWhaleTech/CasaOS#1135]
### Description

When registering a new Appstore and it failed, the command does not tell where it failed and why it failed.

For Context, I was attempting to install a custom appstore with 150 Apps based from the fleet of docker images of linuxserver.io. 
How would I know which app's YAML file caused it to fail and why it failed? It only warns us with a message `might fail if app store cannot be validated`. I hope at least it indicated why it failed.

### Additional Information

![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/f7edcb2f-8e9a-4edc-939f-0a461a1cbbd2)

**Comment by tigerinus** [comment]
@WisdomSky voice heard.

BTW - Did you build another `CasaOS AppStore` with 150 apps? That's awesome.

**Comment by tigerinus** [comment]
> @WisdomSky voice heard.
> 
> BTW - Did you build another `CasaOS AppStore` with 150 apps? That's awesome. Can you share the repo of it?

Nevermind, I see the link in your screenshot. Can't wait to see the appstore up online!

**Comment by tigerinus** [comment]
@WisdomSky - I see that you are using `latest` tag for each image, so I think you might want to know how current app update logic works in CasaOS:

Basically it compares the tag of a running app with the tag in AppStore. If both tags are `latest`, there is no way for CasaOS to say "An update is available".

Of course this is not a big deal for apps like Plex, which comes with built-in update check and notification. But there are many apps might want to rely on its host, i.e. CasaOS, to take this responsibility. :)

**Comment by WisdomSky** [comment]
Ohh, so that's why I noticed that the default appstore specifies the image version. 
But wouldn't that be a maintenance headache for the appstore maintainer specially if the appstore gets really big like 1000+ apps? that would mean we have to keep track of every app and update its version everytime a new one comes up.

Why not compare the sha256 digest of the local image to the remote (dockerhub) to check if a new one is available? 
It should be possible by querying the tag of the image:

> https://registry.hub.docker.com/v2/repositories/linuxserver/radarr/tags/latest

there is even a `last_updated` property that can be used to compare the dates if they changed.

![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/defa8608-c6a7-4268-921d-4519a6f644b3)

**Comment by tigerinus** [comment]
Why not use latest tag all the time?

In the past we pull the entire image down to compare the hash with local image, but that makes Check and update super time consuming for users without great internet access speed.

Yes, Docker Hub does provide API to pull the `digest`, but this is not a standard for many other container registries. There are images hosted on somewhere else.


In addition to that, when there is a major version change in some app, say completely redesigned the setting schema for example. Most likely they will continue with latest tag. However manifest file from AppStore most likely stay as is, and thus become incompatible with the major change, and sometime cause app to stop working or behave weirdly.

**Comment by WisdomSky** [comment]
Understandable.

For me, specifying the tag would not be a problem since I'm generating the docker compose files dynamically, so I can just adjust the script to use the actual version rather than the latest tag and just re-run the script to update the listings with new version. 

This is also why I'm able to create 150 docker compose files in short time.  I'm just re-using the maintained portainer app templates list for linuxserver.io images and generate a docker compose file out of it.

**Comment by tigerinus** [comment]
Sure. I will try to make the experience better in future.

For now, run following command before you register

```
sudo tail -f /var/log/casaos/app-management.log
``

Look for any error message during the process (http://tinyurl.com/formatlog is a good tool so you can paste and see the formatted log)

**Comment by WisdomSky** [comment]
> ```shell
> sudo tail -f /var/log/casaos/app-management.log
> ```

Wow, thank  you for this. This is what I'm looking for. After taking a quick peek at the logs, it did sure say what've happened.

![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/10b3af3a-5648-4a51-b05f-91f79cc156ff)

I guess the port is very strict with type during parsing. I'll try not encasing it with quotes.

**Comment by WisdomSky** [comment]
thanks again @tigerinus 

There's still some few things that needed to do, but it now starting to look good.

![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/e06272bb-bd3d-408c-a763-9aee23738917)
![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/a0279ca1-1229-485c-830a-7cc60b949bf3)
![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/f6db359b-b6c2-4d7e-9e7b-3c6be9ee0963)
![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/567f6f86-d0fa-4f99-b2d9-aebc6bb15e7a)
![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/76a3a8ea-730d-4fea-bdac-31786fde56b4)
![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/8699cc80-2795-4bbf-a903-b9d827c57cbe)

**Comment by tigerinus** [comment]
i am literally stunned

**Comment by tigerinus** [comment]
do you know the title, description and tagline supports multi-lang?

in the official appstore we used GitHub Copilot to help added non-english text quickly.

**Comment by WisdomSky** [comment]
Yes, I'm aware of the i18n. I was actually referencing from [IceWhaleTech/CasaOS-Appstore](https://github.com/IceWhaleTech/CasaOS-Appstore), regarding the format.

**Comment by Jiejie-May** [comment]
Hey, WisdomSky, I am May from CasaOS team, Tiger's colleague, I am CasaOS community operation . Your works is very amazing, we would like to make one written interview with you , and make one blog. we want you can share some your experience in CasaOS v0.4.4 and launch the store and apps . so that your story and experience can encourge more developer to join in CasaOS development works. and also your apps can be helpful for more CasaOS uers. can i have your email address? and we can talk more. Thanks a lot!

**Comment by WisdomSky** [comment]
@Jiejie-May hello May, you can reach me through email@paodayag.dev

**Comment by WisdomSky** [comment]
@tigerinus By the way, just came here to say that it is now officially up. 

Appstore Repo: https://github.com/WisdomSky/CasaOS-LinuxServer-AppStore

**Comment by tigerinus** [comment]
> @tigerinus By the way, just came here to say that it is now officially up.
> 
> Appstore Repo: https://github.com/WisdomSky/CasaOS-LinuxServer-AppStore

Awesome... Have you tested the apps working with CasaOS?

**Comment by WisdomSky** [comment]
Yup... tested a couple of them, Plex, qbittorent, webtop, boinc, etc...

**Comment by tigerinus** [comment]
I've added instruction of getting logs after registering appstore to the CLI - will be part of final v0.4.4 release.

Closing this issue now.

**Comment by Jiejie-May** [comment]
> @Jiejie-May hello May, you can reach me through [email@paodayag.dev](mailto:email@paodayag.dev)

Hello, I don't know why I can not deliver out successfully the email to this address. do you have another email address? thanks!

**Comment by WisdomSky** [comment]
@Jiejie-May Hi May, I'm sorry about that. You can reach me out with this one instead: pao.dayag@gmail.com
