### ISSUE TITLE
[Bug] RAM usage not being displayed on a Raspberry Pi 4 2Gb

### ISSUE THREAD

**Issue by hazawer** [IceWhaleTech/CasaOS#1136]
**Describe the bug**
When in System status the CPU for running apps is being displayed but not for RAM 

**To Reproduce**
1. Go to 'System status'
2. Click on 'CPU'
3. Click on 'RAM'

**Expected behavior**
RAM usage for running apps should be displayed

![casaos_cpu](https://github.com/IceWhaleTech/CasaOS/assets/107300640/996b3051-d5d3-4ac0-9eea-48a782d2206b)
![casaos_ram](https://github.com/IceWhaleTech/CasaOS/assets/107300640/6620d577-8ad7-4718-97de-28b8c80687ef)

**Desktop (please complete the following information):**
 - OS: Raspberry PI OS Lite 64-bit
 - Browser Brave
 - Version 0.4.3

**Logs**

run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
```

**Additional context**

**Comment by raller1028** [comment]
You can try using the following commands to read RAM` docker stats`
However, it seems that the Raspberry Pi official documentation does not support reading RAM directly.
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/dc6d3ff8-6e4c-4b96-b200-361e9316d407)

**Comment by TomasValenta** [comment]
@hazawer I have the same issue with Raspberry Pi 4 4G. This solution worked for me: https://github.com/docker/for-linux/issues/1112#issuecomment-699512425. @raller1028 Thank you for the guidance with the `docker stats` 😉

**Comment by raller1028** [comment]
@TomasValenta Thank you for your feedback, we will add this configuration to display the memory usage of the arm architecture in the future.
@hazawer You can directly add` cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1` in /boot/cmdline.txt
Then restart to see the memory usage of the application. Attached is my test case.
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/6e43b805-3fef-4ccf-a2a4-1173b45d024c)

**Comment by hazawer** [comment]
Yep, that worked a treat.
<img width="248" alt="ram_usage" src="https://github.com/IceWhaleTech/CasaOS/assets/107300640/1c76b422-19e0-4ceb-912c-6315b5d17bb4">

**Comment by Levi-Michael** [comment]
> @TomasValenta Thank you for your feedback, we will add this configuration to display the memory usage of the arm architecture in the future. @hazawer You can directly add` cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1` in /boot/cmdline.txt Then restart to see the memory usage of the application. Attached is my test case. ![image](https://private-user-images.githubusercontent.com/57336867/244955235-0c3dd340-6ae6-4915-bb25-35f1abacb42d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTEyMjMsIm5iZiI6MTcwOTM5MDkyMywicGF0aCI6Ii81NzMzNjg2Ny8yNDQ5NTUyMzUtMGMzZGQzNDAtNmFlNi00OTE1LWJiMjUtMzVmMWFiYWNiNDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE0NDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYTFmZGM5ZDY2NDRkNDQwMGRkYjQ3N2ExNmE2YTE4Y2NiYzkxYmRhZWJjZTI2ODc3ZjlmMTZmZDk5NGI4MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eV0yvJGQZbIruwmXIIL-OPBlbW2RkHIR5FRUZt8qEFA)

worked like a magic ty

**Comment by shubhankartrivedi** [comment]
## Update:
Now you have to add `cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1` in `/boot/firmware/cmdline.txt`
With latest RpiOS ✅

**Comment by ioncubekh** [comment]
I have the similar issue my Host is
```
OS: Armbian (24.8.4) aarch64
Host: Radxa ZERO 3
Kernel: 6.1.75-vendor-rk35xx
Uptime: 5 hours, 51 mins
Packages: 1031 (dpkg)
Shell: bash 5.2.21
Terminal: /dev/pts/0
CPU: (4) @ 2.000GHz
Memory: 2653MiB / 3732MiB
```

I don't have ` /boot/cmdline.txt` I do have `armbianEnv.txt` & `boot.cmd`

**Comment by defencedog** [comment]
For above system I edit `/boot/armbianEnv.txt` & added the solution to `extraargs=` line (space separated)

It arguments are properly passed to kernel but bug is still there with latest CasaOS. 

`dmesg` logs:
```
[   15.630904] Kernel command line: root=UUID=eb6a27ef-3932-431f-92fd-e61fea75356c rootwait rootfstype=ext4 splash=verbose console=ttyS2,1500000 console=tty1 consoleblank=0 loglevel=1 ubootpart=f3aeb909-d11b-ec42-a52c-4507e474335c usb-storage.quirks=0x2537:0x1066:u,0x2537:0x1068:u,0x1058:0x25a2:u cma=256M cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1  cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
[   15.631910] Unknown kernel command line parameters "splash=verbose ubootpart=f3aeb909-d11b-ec42-a52c-4507e474335c cgroup_enable=memory cgroup_memory=1", will be passed to user space.
```

**Comment by RobertSamp** [comment]
Just add in the end of the code

"cgroup_enable=memory"

in /boot/firmwarte/cmdline.txt

the cmdline.txt will be like 

console=serial0,115200 console=tty1 root=PARTUUID=5fe53d1e-02 rootfstype=ext4 fsck.repair=yes rootwait cgroup_enable=memory
