### ISSUE TITLE
[Feedback]Issue

### ISSUE THREAD

**Issue by Gaitmanh** [IceWhaleTech/CasaOS#1141]
### Description

Name of added sites in app have gotten a random name,
And i kant update the docker apps animore frome the menu.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.4
	 - Disk Total: 936737 
	 - Disk Used: 28208 
	 - System Info: [Ubuntu 22.10   \l Bit:64 Mem:15712M Core:12 Linux nuc2 5.19.0-42-generic #43-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 18:21:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 113.0.0.0

**Comment by tigerinus** [comment]
The first issue should be fixed by next v0.4.4 alpha release.

Let's track your second issue in #1145
