### ISSUE TITLE
qbittorrent问题

### ISSUE THREAD

**Issue by jonny77** [IceWhaleTech/CasaOS#1142]
### What happened?

卷映射:  
casaOS中 usb移动硬盘路径: /media/devmon/XIJIE-STORA/media
docker容器路径:/downloads
启动日志报错:
chown: changing ownership of '/downloads': Operation not permitted

### Screenshots
<img width="618" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/1962170/a91a1965-86fc-4f1e-a2ad-a25d2ba778c4">
<img width="703" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/1962170/ec3e9ada-854b-4ae0-af1f-47e0941999b9">

_No response_

**Comment by raller1028** [comment]
可以修改config映射的目录,我config映射的是/media/sda1-usb-Hitachi_HTS54757/qbitdownload,然后qbit应用内不需要修改任何东西直接下载就ok

You can modify the directory mapped in the config file. The directory I have mapped in the config file is /media/sda1-usb-Hitachi_HTS54757/qbitdownload. Once you have made this change, there is no need to modify anything within the qBittorrent application itself. You can simply start downloading files as usual.
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/d61c9403-f6c2-4367-90b4-88e70f605ad1)
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/2ef67fa7-168e-4d33-ae2f-eb73aff72ea5)

**Comment by jonny77** [comment]
> 可以修改config映射的目录,我config映射的是/media/sda1-usb-Hitachi_HTS54757/qbitdownload,然后qbit应用内不需要修改任何东西直接下载就ok
> 
> You can modify the directory mapped in the config file. The directory I have mapped in the config file is /media/sda1-usb-Hitachi_HTS54757/qbitdownload. Once you have made this change, there is no need to modify anything within the qBittorrent application itself. You can simply start downloading files as usual. ![image](https://user-images.githubusercontent.com/57336867/241680676-d61c9403-f6c2-4367-90b4-88e70f605ad1.png) ![image](https://user-images.githubusercontent.com/57336867/241680695-2ef67fa7-168e-4d33-ae2f-eb73aff72ea5.png)

不是config问题.是下载路径的配置有问题.启动的时候报这个错误. 然后我给目录设置为777也没有用 下载就一直是0%.不知道是什么情况

**Comment by raller1028** [comment]
你这边方便添加微信reelfy2570吗,然后我们远程看看是什么问题

**Comment by jonny77** [comment]
> 

好的 , 通过下 1

**Comment by jonny77** [comment]
> 你这边方便添加微信reelfy2570吗,然后我们远程看看是什么问题

1
