### ISSUE TITLE
[Feedback]How to clone a small sd Raspberry Pi boot card to a bigger one ?  The original is 128GB ( CASAOS ) m

### ISSUE THREAD

**Issue by Aramis65** [IceWhaleTech/CasaOS#1148]
### Description

How to clone a small sd Raspberry Pi boot card to a bigger one ?

The original is 128GB ( CASAOS ) micro-sd that I would like to clone to a new 512GB micro-sd in order to get more storage ???

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 119786 
	 - Disk Used: 3631 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:3794M Core:4 Linux raspberrypileo 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Safari 
	 - Version: 13.1.2

**Comment by Aramis65** [comment]
Hi, I am using BalenaEtcher to create my images ….. I suppose it does the same as Rufus ?

For my understanding, the expand-rootfs command will look at the booted SD card and allow all the available storage of the larger SD booted ?

**Comment by hazawer** [comment]
From what I understand, correct.

**Comment by LinkLeong** [comment]
We will close the issue, if you have questions, you can reopen it
