### ISSUE TITLE
CasaOS install on opensuse microOS failed...

### ISSUE THREAD

**Issue by intraxit** [IceWhaleTech/CasaOS#1149]
Hi,

I'm trying to install casaOS on opensuse microOS on a raspberry pi, but the install failed, because there is no 'udevil' and 'mergerfs' package in  the opensuse repo's I can install.

Any way to work around this except compiling from source ?

**Comment by jerrykuku** [comment]
There may not be a better way yet, we are trying to use other methods instead of udevil.

**Comment by lfdominguez** [comment]
> package in the opensuse repo's I can install.

Same with AlmaLinux, there is not udevil (latest realease 8 years ago):
![image](https://github.com/IceWhaleTech/CasaOS/assets/5604131/069f04c6-2ba3-4905-a88f-5c18da89caa5)

**Comment by jerrykuku** [comment]
Yes， It's a very old package, We're already working on a way to eliminate that dependency. But it will still take some time.

**Comment by kamasylvia** [comment]
Same problem. Besides `udevil`, Do u have any idea to replace `mergerfs`?

**Comment by jerrykuku** [comment]
> Same problem. Besides `udevil`, Do u have any idea to replace `mergerfs`?

Do you want an alternative to mergerfs?

**Comment by kamasylvia** [comment]
> > Same problem. Besides `udevil`, Do u have any idea to replace `mergerfs`?
> 
> Do you want an alternative to mergerfs?

I would say yes since `mergerfs` is not in opensuse official repo.

---

Today, I tried to install CasaOS on Fedora but an error about missing `udevil` was raised. I read the doc that says only Debian, Ubuntu, and Raspberry are tested. Do u have any plans to test other popular Linux distros such as Fedora, openSUSE, and Arch?

**Comment by jerrykuku** [comment]
This issue has not been updated for a long time, I will close it, if there are still questions you can reopen it.
