### ISSUE TITLE
client version error

### ISSUE THREAD

**Issue by leaf918** [IceWhaleTech/CasaOS#115]
**Is your feature request related to a problem? Please describe.**

Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39
![image](https://user-images.githubusercontent.com/170311/155491950-7c1d0add-cac3-4471-9321-81666d90cb06.png)

**Describe the solution you'd like**
Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39
**Describe alternatives you've considered**
Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39
**Additional context**
Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39

**Comment by LinkLeong** [comment]
Sorry for taking so long to reply to your message, just upgrade the docker version

**Comment by leaf918** [comment]
![chrome_CzIE5LK2nA](https://user-images.githubusercontent.com/170311/166856369-75e5404f-118c-4a44-8059-076470a17727.gif)

raspberry 3 重新安装后，还是不行。
