### ISSUE TITLE
docker setup network interface is needed.

### ISSUE THREAD

**Issue by fimreal** [IceWhaleTech/CasaOS#1150]
Services run by docker need to be bound to a network address, which prevents vulnerable services from being accessed by anyone.

We can use the current dashboard to control the startup port, and it might be easy to add the address as well. 

Here are some examples of starting with docker

```bash
# Accept all requests as they are now
docker run -d --name app -p 80:80 image:tag

# Home network access only
docker run -d --name app -p 192.168.50.200:80:80 image:tag

#Reverse proxy that can be used in docker or host
docker run -d --name app -p 172.17.0.1:80:80 image:tag
```

**Comment by tigerinus** [comment]
Yes, we need this feature for multi-NIC devices. Only selected IP addresses should be bound to the apps.

In fact since v0.4.4 such setting is already possible in the Docker Compose based app backend, we just need to come up with a UI to manage it.

**Comment by fimreal** [comment]
That's great news. I'm looking forward to trying the new version. And thanks for your work 👍
