### ISSUE TITLE
[Bug] unable to connect to SMB share. The password contains characters eg !@#!

### ISSUE THREAD

**Issue by giveaduck12** [IceWhaleTech/CasaOS#1152]
**Describe the bug**
Trying to connect to SMB share. The password contains characters eg !@#!

**To Reproduce**
1. Go to Connect Network Storage
2.  Type SMB address and username and PW with !@#! characters
3. Click on Connect
4. See error: Special characters may cause security problems

**Expected behavior**
connects to SMB share

**Screenshots**
(https://i.imgur.com/Sg4hgPf.png)

**Desktop (please complete the following information):**
 - OS: debian 11
 - Browser  chrome

**Logs**
nil

**Comment by LinkLeong** [comment]
Which version of casaos do you have?

**Comment by LinkLeong** [comment]
We will close this question and reopen it if you have any questions

**Comment by davidstosik** [comment]
@LinkLeong I have reproduced that error with CasaOS 0.4.4. I suspect characters such as `;` or `]`, present in my SMB password, to be the cause.

**Comment by slackerchris** [comment]
@LinkLeong  I too am have the same issue, password contains @ and !

**Comment by roeberp** [comment]
Doesn't like the $ for me.

**Comment by Djuuu** [comment]
Same issue on v0.4.4.1
My username contains only letters, password contains only letters, digits and _spaces_.

In any case, forbidding characters in a _password_ field is bad practice.

**Comment by cleanmachine** [comment]
I took delivery of a ZimaBoard last week and was trying to connect to both my Synology NAS and my TrueNAS box via the Connect Network Storage function in the Files app in CasaOS 0.4.4.1. Both my local network storage boxes have long, strong passwords using the full range of characters, as is good practice. I, too, got the "Special characters may cause security problems" popup and the connect button greyed out.

**Comment by LinkLeong** [comment]
I have followed the issue and I will continue to do so.

**Comment by cleanmachine** [comment]
Thank you. I should note that the username for both my network storage accounts is the same - a five-letter, lowercase word using no caps, numerals or special characters. It's only the passwords that are long (30+ characters) and strong (upper and lower case, numbers and special characters).

**Comment by LinkLeong** [comment]
This issue was fixed in 0.4.4-2, and the update is still in beta, so you can update manually if you need to.

**Comment by cleanmachine** [comment]
Excellent - thank you.

**Comment by LinkLeong** [comment]
I'll close this question and reopen it if you have any questions.

**Comment by cleanmachine** [comment]
Reporting in that this works now. Thanks for your efforts.
