### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by copycraft** [IceWhaleTech/CasaOS#1155]
So i run the installer and it says 404 ip not found : an ip address.

**Comment by raller1028** [comment]
Can you attach a more detailed error message or a screenshot?

**Comment by copycraft** [comment]
now i runned the installer on a fresh install and it says: kalli roling realeas does not hawe a reale file

**Comment by copycraft** [comment]
i use kali linux arm 64 bit

**Comment by copycraft** [comment]
![IMG_20230601_152723](https://github.com/IceWhaleTech/CasaOS/assets/112800296/442f930d-c271-449b-b931-a608fb821a1f)
Hees the error

**Comment by raller1028** [comment]
can you `apt update` successful?

**Comment by copycraft** [comment]
Now it's solved

**Comment by copycraft** [comment]
I did some stuff fyesterday
