### ISSUE TITLE
Hard Drive Storage Will not Create

### ISSUE THREAD

**Issue by Tyleroi** [IceWhaleTech/CasaOS#116]
**Describe the bug**

Cannot create storage volumes through any methodology. Have tried 8 different hard drives including one fresh from the box and all have the same situation: they start the creation process then just stop working. 

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.9
	 - Disk Total: 13105 
	 - Disk Used: 4126 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1826M Core:4 Linux CasaOS 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux]
	 - Browser: Firefox 
	 - Version: 97.0

**Comment by JohnGuan** [comment]
We have also found this problem and are working on it.

**Comment by JohnGuan** [comment]
Looks like a problem that has been solved
