### ISSUE TITLE
[Feedback]SAMBA share for multiple users with passwords

### ISSUE THREAD

**Issue by Vizion-HUN** [IceWhaleTech/CasaOS#1161]
### Description

Hi!
It would be nice to have a small shares section:
- users: here we can add samba-users 
- shares: list of shared folders, we got this, just for the list
- permissions: to add rights to users, RO, RW, no access, etc.

Thank You!
Vizion
Hungary

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 32074 
	 - Disk Used: 9944 
	 - System Info: [Ubuntu 22.04.2 LTS   \l Bit:64 Mem:5933M Core:2 Linux casa 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 114.0.0.0

**Comment by ETWang1991** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/109786132/f70c74cd-dc74-4212-8a13-4b143f4d4d8a)
Do you mean that it is possible to give different account passwords to folders here @Vizion-HUN

**Comment by Vizion-HUN** [comment]
Hi,

yes, something to controll users (kids and wife...), to prevent accidents
with otehr user folders.
I see CasaOS is a "one user" OS now, no problem.
As a workaround, I installed the filebrowser addon: as admin, I added
users, all can access his/her folders and the shared folders only:
[image: users.jpg]

Have a nice day!
Krisztián Vizler




ETWang1991 ***@***.***> ezt írta (időpont: 2023. jún. 14.,
Sze, 11:57):

**Comment by ETWang1991** [comment]
Understood, casaos will become a multi-user system, but not for a while. Multi-user involves a lot of functionality and support work, and we will work on this when the size of the casaos user base reaches the next stage.

**Comment by Vizion-HUN** [comment]
> Thanks @Vizion-HUN for share an alternative solution. It worked for me only in web access, using the FileBrowser app. For sharing via smb, it's not great because allow user to connect as a guest and they have privilege access.

Hi!
Filebrowser is only for web access, it has nothing to do with samba. 
But there is also a samba workaround... :) 
Casa OS uses its own samba configuration file, and updates will not overwrite. Edit this file, instead of the smb.conf:
`nano /etc/samba/smb.casa.conf`

You can add samba users , enable recycle bin, share multiple folders, etc... just like in the regular smb.conf
For detailed info about the settings/possibilities, search "ubuntu server add samba user" or "ubuntu server samba configuration".
