### ISSUE TITLE
[Feedback]Translation (Hungarian) serious error

### ISSUE THREAD

**Issue by Vizion-HUN** [IceWhaleTech/CasaOS#1164]
### Description

Storage translation is very BAD.
Format in Hungarian translation is now Formátum, it is kinda good (it means type of format) , but it is formatting the HDD, so use please "Formázás" instead. Now the text suggests it is an information button, not a disk format tool.
Would be nice, if we could select file system too.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 32074 
	 - Disk Used: 10139 
	 - System Info: [Ubuntu 22.04.2 LTS   \l Bit:64 Mem:1313M Core:2 Linux casa 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 114.0.0.0

**Comment by jerrykuku** [comment]
Thank you for reminding us, we will fix these translation errors as soon as possible.

**Comment by zhanghengxin** [comment]
Hungarian language is truly vast and profound. The modifications have been made, and for the next submission, you can refer to the guidelines provided by this repository.
https://github.com/IceWhaleTech/CasaOS-i18n
![image](https://github.com/IceWhaleTech/CasaOS/assets/24197448/948b17a1-759c-48de-a5d6-f534d1f828da)

**Comment by Vizion-HUN** [comment]
Hi,

Thank You!

Vizler Krisztián

zhanghengxin ***@***.***> ezt írta (időpont: 2023. jún. 19.,
H, 5:50):
