### ISSUE TITLE
[Feedback]App store好像不可以用了

### ISSUE THREAD

**Issue by xpupp** [IceWhaleTech/CasaOS#1169]
### Description

App store好像不可以用了，，提示列表加载失败，图标都看不到了

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 79102 
	 - Disk Used: 2495 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1935M Core:2 Linux debian 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 100.0.4692.71

**Comment by xpupp** [comment]
谢谢您的回复，后来发现是我的docker代理问题，导致不能直接从App store下载。













--

呼拉拉
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
.




在 2023-06-12 15:53:41，"raller1028" ***@***.***> 写道：

可能是网络问题,方便多试几次吗,提供截图或更多信息

**Comment by tigerinus** [comment]
> 谢谢您的回复，后来发现是我的docker代理问题，导致不能直接从App store下载。
> […](#)
> -- 呼拉拉 . 在 2023-06-12 15:53:41，"raller1028" ***@***.***> 写道： 可能是网络问题,方便多试几次吗,提供截图或更多信息 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

可以具体描述一下你是怎么解决的么？可能对于遇到同样问题的朋友有帮助。
