### ISSUE TITLE
Create Storage  failed + All files deleted

### ISSUE THREAD

**Issue by poussun-ops** [IceWhaleTech/CasaOS#117]
**Describe the bug**

A new 1TB SSD is detected by CasaOS, when I try to create a new 'storage', a window opens during 2 seconds 'storage creation in progress', and closes. Nothing else happens, and no storage created

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.9
	 - Disk Total: 13105 
	 - Disk Used: 5585 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1826M Core:4 Linux CasaOS 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 98.0.4758.102

**Comment by poussun-ops** [comment]
I connected the disk on a chromebook via USB, format in ExFat. Reconnected the disk on the ZimaBoard, and now the Storage Creation process works

**Comment by JohnGuan** [comment]
We are already dealing with the issue of creating the storage space.
Also, the issue you mentioned that looks like it was deleted, was it really deleted? Or is it just a problem in FileBrowser?

**Comment by poussun-ops** [comment]
It is really deleted, at each reboot

**Comment by JohnGuan** [comment]
> It is really deleted, at each reboot

By what means is your SSD connected to the ZimaBoard? I tried NVMe and USB, and the files are still there after reboot.

**Comment by poussun-ops** [comment]
The SSD is connected via the SATA cable. I tested an USB key, and no such issue
But in the interface, both are not showed in the same way:
- SSD is not directly listed, but 'merged' with the internal storage. To see it, I must open 'storage' and there I can see the volumes 
- USB key is listed as additional storage on the landing page

**Comment by JohnGuan** [comment]
> The SSD is connected via the SATA cable

I will test the SATA connection again



> But in the interface, both are not showed in the same way

This part of the presentation logic we may need to optimize a bit more

**Comment by JohnGuan** [comment]
Strange, I tested USB, NVMe, SATA and didn't encounter data being deleted. And I talked to my development colleague and it seems that the formatting operation is not actively performed except for manual formatting.
Do you have any ideas?

**Comment by poussun-ops** [comment]
In the GUI, the SSD was not autmatically detected by CasaOS. I had to preformat it in NTFS and/or exFAT to make it 'recognized'
After new volume created, and a reformat, I see two different behaviors, after a reboot : 
- Sometimes, the volume is available. But all files are deleted
- Sometimes, the volume disapeared and I have to recreate a new volume
- The files stay visible in FileBrowser, even if the SSD is disconnected or reformated :)

But in Command line, I See a volume named /DATA, where my files are accessible, even if the volume is not visible in the GUI. But this volume is not visible in other apps (Plex for instance). How could I make DATA visible by other apps ?

**Comment by JohnGuan** [comment]
If you need the application to see the contents of /DATA as well, you need to mount the /DATA directory for the application

**Comment by tigerinus** [comment]
In the upcoming v0.3.7 release a lot of storage issues have been fixed. Please verify in v0.3.7 and re-open of this is still an issue.
