### ISSUE TITLE
cannot install on Fedora 38

### ISSUE THREAD

**Issue by jklm23** [IceWhaleTech/CasaOS#1176]
### Description

![image](https://github.com/IceWhaleTech/CasaOS/assets/30951259/421a2518-2ecc-4137-8ff0-b041c2387252)

**Comment by jerrykuku** [comment]
Yes, we don't currently support Fedora.

**Comment by jerrykuku** [comment]
This issue has not been updated for a long time, I will close it, if there are still questions you can reopen it.

**Comment by wyktron** [comment]
when fedora
