### ISSUE TITLE
[Feedback]Unable to install apps from app store

### ISSUE THREAD

**Issue by suren5455** [IceWhaleTech/CasaOS#1177]
### Description

I'm currently unable to install apps from the app store not sure what may have caused this as I have been able to install adguard and syncthing.
When I click on an application to install the progress bar will appear and remain at 0%, I have refreshed the page as well after a while to see whether it had installed but that is not the case.

is this something you can look into and resolve ?

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 29704 
	 - Disk Used: 7997 
	 - System Info: [Raspbian GNU/Linux 11   \l Bit:32 Mem:3710M Core:4 Linux raspberrypi 5.10.43v64 #1 SMP PREEMPT Tue Jun 15 00:52:48 CEST 2021 aarch64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 113.0.5672.95

**Comment by raller1028** [comment]
Can you type this command in the terminal?
`docker pull whyour/qinglong`
Use it to confirm that your network is pulling the image correctly

**Comment by suren5455** [comment]
Hi,Thanks for getting back to me. That has worked.It gave me a digest code.What do I need to do from here ?Regards,SurenOn 12 Jun 2023 08:48, raller1028 ***@***.***> wrote:
Can you type this command in the terminal?
docker pull whyour/qinglong
Use it to confirm that your network is pulling the image correctly

**Comment by raller1028** [comment]
`docker rmi whyour/qinglong`
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/0ea43c48-5e5f-4805-8822-73a8bc32f309)
