### ISSUE TITLE
Is it possible to install K3s on CasaOS?

### ISSUE THREAD

**Issue by FeynmanZhou** [IceWhaleTech/CasaOS#118]
CasaOS is fully compatible with Ubuntu, Debian, Raspberry Pi OS, and CentOS with one-liner installation. I am curious if it is possible to install [K3s](https://k3s.io/) on CasaOS? Has anyone tried it?

**Comment by tigerinus** [comment]
Current design of CasaOS is in fact a service running on top of Ubuntu. It has UI and management logic of Dockerized apps. However it's not a Linux distro per se.

That said, you could setup and run K3s on the underneath Ubuntu directly.

**Comment by cenobitedk** [comment]
For anyone who is trying this, you need to change the port of CasaOS webUI first. K3s will occupy port 80 and CasaOS webUI will stop working if you don't.
The port can be changed in the CasaOS webUI interface. If you already installed k3s, try this https://docs.k3s.io/upgrades/killall
