### ISSUE TITLE
[Feedback] Update taking forever when trying to update to [0.4.3]

### ISSUE THREAD

**Issue by Fadope1** [IceWhaleTech/CasaOS#1181]
### Description

When I try to update it loads forever and nothing happens

<img width="651" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/68806729/86f93afd-f01d-47ea-821d-7ccfcf0f0aba">

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 27712 
	 - Disk Used: 8119 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 113.0.0.0

**Comment by Kordrad** [comment]
I have the same issue. 
I see in network tab only the same information with "OK Your hardware architecture is: x86_64"
![image](https://github.com/IceWhaleTech/CasaOS/assets/29141389/1cc7d076-8b69-43d6-8952-047715696491)
but it's taking forever.

**Comment by truthreigns** [comment]
I just purchased a a Zimaboard 832 with CasaOs already loaded.  This is the same problem for me when i try to update the system.

**Comment by jameswlane** [comment]
The same issue with a Zimaboard 832; I just took it out of the box and saw it needed an update. It just hangs.

**Comment by kblack227** [comment]
I got a fix. ssh into the zimaboard with "casaos@ipaddress" and run "sudo apt update && sudo apt upgrade" after it finishes then retry running the update again

**Comment by Kordrad** [comment]
> I got a fix. ssh into the zimaboard with "casaos@ipaddress" and run "sudo apt update && sudo apt upgrade" after it finishes then retry running the update again

After second try I can confirm, this also helped me to update. Thank you
![image](https://github.com/IceWhaleTech/CasaOS/assets/29141389/d2ca8077-e816-4b49-982a-30c3b97df09a)

**Comment by Kordrad** [comment]
> > I got a fix. ssh into the zimaboard with "casaos@ipaddress" and run "sudo apt update && sudo apt upgrade" after it finishes then retry running the update again
> 
> Hey, i am new for this.... possibel to explain better how to do? thx

Can you specify in what step do you have a problem? I will try to help you

**Comment by Kordrad** [comment]
Ok, on your router, you have to check what IP your server has. 

Then in your computer you can connect to your zimaboard by this command in terminal 
`ssh casaos@192.168.X.X` 

default password is "casaos"

and just put these command in terminal:

```bash
sudo apt update
sudo apt upgrade
```
And it should upgrade your OS.

If everything did well, you can update the system in `http://casaos.local`. I before update made restart yet

**Comment by davidsmoker** [comment]
Ahhh that's great... better explain! :-)

TOPPIE works with stress  (hahhahha)

Thank you!!!! ;-)

**Comment by truthreigns** [comment]
> I got a fix. ssh into the zimaboard with "casaos@ipaddress" and run "sudo apt update && sudo apt upgrade" after it finishes then retry running the update again



> Ok, on your router, you have to check what IP your server has.
> 
> Then in your computer you can connect to your zimaboard by this command in terminal `ssh casaos@192.168.X.X`
> 
> default password is "casaos"
> 
> and just put these command in terminal:
> 
> ```shell
> sudo apt update
> sudo apt upgrade
> ```
> 
> And it should upgrade your OS.
> 
> If everything did well, you can update the system in `http://casaos.local`. Before update, I made restart yet



> Ok, on your router, you have to check what IP your server has.
> 
> Then in your computer you can connect to your zimaboard by this command in terminal `ssh casaos@192.168.X.X`
> 
> default password is "casaos"
> 
> and just put these command in terminal:
> 
> ```shell
> sudo apt update
> sudo apt upgrade
> ```
> 
> And it should upgrade your OS.
> 
> If everything did well, you can update the system in `http://casaos.local`. Before update, I made restart yet

I tried this fix but i could not log in with terminal.  I get an error message:
$ ssh casaos@192.168.1.67
1687399748 ERROR torsocks[25489]: General SOCKS server failure (in socks5_recv_connect_reply() at socks5.c:527)
ssh: connect to host 192.168.1.67 port 22: Connection refused

**Comment by LinkLeong** [comment]
> > I got a fix. ssh into the zimaboard with "casaos@ipaddress" and run "sudo apt update && sudo apt upgrade" after it finishes then retry running the update again我得到了修复。使用“casaos@ipaddress”ssh 进入 zimaboard，并在完成后运行“sudo apt update && sudo apt upgrade”，然后重试再次运行更新
> 
> > Ok, on your router, you have to check what IP your server has.好的，在您的路由器上，您必须检查您的服务器具有什么IP。
> > Then in your computer you can connect to your zimaboard by this command in terminal `ssh casaos@192.168.X.X`然后在您的计算机中，您可以通过终端 `ssh casaos@192.168.X.X` 中的此命令连接到您的 zimaboard
> > default password is "casaos"默认密码为“Casaos”
> > and just put these command in terminal:只需将这些命令放在终端中：
> > ```shell
> > sudo apt update
> > sudo apt upgrade
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And it should upgrade your OS.它应该升级您的操作系统。
> > If everything did well, you can update the system in `http://casaos.local`. Before update, I made restart yet如果一切正常，您可以在 中 `http://casaos.local` 更新系统。在更新之前，我重新启动了
> 
> > Ok, on your router, you have to check what IP your server has.好的，在您的路由器上，您必须检查您的服务器具有什么IP。
> > Then in your computer you can connect to your zimaboard by this command in terminal `ssh casaos@192.168.X.X`然后在您的计算机中，您可以通过终端 `ssh casaos@192.168.X.X` 中的此命令连接到您的 zimaboard
> > default password is "casaos"默认密码为“Casaos”
> > and just put these command in terminal:只需将这些命令放在终端中：
> > ```shell
> > sudo apt update
> > sudo apt upgrade
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And it should upgrade your OS.它应该升级您的操作系统。
> > If everything did well, you can update the system in `http://casaos.local`. Before update, I made restart yet如果一切正常，您可以在 中 `http://casaos.local` 更新系统。在更新之前，我重新启动了
> 
> I tried this fix but i could not log in with terminal. I get an error message:我尝试了此修复程序，但我无法使用终端登录。我收到一条错误消息： $ ssh casaos@192.168.1.67$ ssh casaos@192.168.1.67 1687399748 ERROR torsocks[25489]: General SOCKS server failure (in socks5_recv_connect_reply() at socks5.c:527)1687399748错误 Torsocks[25489]：袜子服务器故障（在 socks5.c：527 的 socks5_recv_connect_reply（） 中） ssh: connect to host 192.168.1.67 port 22: Connection refusedssh：连接到主机 192.168.1.67 端口 22：连接被拒绝

We can also assist you remotely to solve the problem, do you think it is convenient?

**Comment by LinkLeong** [comment]
> Good morning, I also have this problem with my newly bought 2GB version. I have tried a reboot and a few sudo update/upgrades, with no effect. Is there a way to update CasaOS itself from the command line?
> 
> 早上好，我新买的2GB版本也有这个问题。我尝试过重新启动和一些 sudo 更新/升级，但没有效果。有没有办法从命令行更新 CasaOS 本身？
> 
> ![image](https://user-images.githubusercontent.com/9842595/267907974-6eed698b-8336-48c4-adef-6d91fe064570.png)
> 
> ![image](https://user-images.githubusercontent.com/9842595/267908102-f4009cd4-bd3c-417a-8d92-0a2f6afb7cc5.png)
> 
> ![image](https://user-images.githubusercontent.com/9842595/267908300-23527b8f-9cf8-4a77-9f87-aedecc5f1a32.png)
> 
> Subscribing to this ticket
> 
> 订阅此门票

`curl -fsSL https://get.casaos.io/update | sudo bash`

**Comment by LinkLeong** [comment]
We will close the issue and reopen it if you have any questions.
