### ISSUE TITLE
[Bug] logging into casaos via rdp results in black screen in rdp window and causes casaos to crash

### ISSUE THREAD

**Issue by enthusedcoder** [IceWhaleTech/CasaOS#1183]
**Describe the bug**
When you try to rdp into casaos using the native windows rdp client and using casaos's default credentials (casaos/casaos), the resulting rdp session will just display a black screen:

![image](https://github.com/IceWhaleTech/CasaOS/assets/127647168/de4e9a84-72a2-447c-bb9d-5d954de67534)

Furthermore, if you have the zimaboard connected to a monitor, the normal desktop background that you normally see is replaced with the following image:

![image](https://github.com/IceWhaleTech/CasaOS/assets/127647168/9c94a021-618e-43e8-b705-6054fdab3f0c)

No point in deploying casaos with the software to allow users to connect via rdp if rdp doesn't work, right?

**To Reproduce**
1. Open the native rdp client on a Windows machine (or any machine with an rdp client, as it is likely any rdp client will do)
2. Type "casaos" into the computer input and click ok

![image](https://github.com/IceWhaleTech/CasaOS/assets/127647168/8d63482a-4e0e-4684-a3cb-a217dcb81559)

3. When the xrdp login prompt appears in the rdp window, input the default username and password for casaos (casaos/casaos)

![image](https://github.com/IceWhaleTech/CasaOS/assets/127647168/8de666d7-a220-4e75-a2af-fb090f5650f0)

**Expected behavior**
I would expect the rdp client to be able to allow me to establish a working remote session with casaos and not crash the system

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows (thought not really applicable)
 - Browser: Not at all applicable
 - Version:  Hmm.  Not quite sure how to answer this one.  If it helps, I recently re-installed casaos on my zimaboard using the iso obtained from the link below (found on the "ZimaBoard CasaOS Factory Recovery" page):
 "[ZimaBoard CasaOS image -832/432](https://drive.google.com/file/d/1b-k7d1LzPHNUtem-hOrHB5dDt0_AC6mK/view)
Also, the product page for the zimaboard I purchased contains the text "ZimaBoard 832."  A word of advice: if there is some kind of console command that user's can run to obtain this information more easily and more definitively, it would help to include it in the issue template to allow user's to more easily provide you the information you want.  Kind of like you do with the instructions to collect the logs below.

**Logs**

run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
```

Logs are in attached zip

[casaos-logs.zip](https://github.com/IceWhaleTech/CasaOS/files/11734798/casaos-logs.zip)

**Additional context**

**Comment by LinkLeong** [comment]
We recommend that you use `ssh casaos@ipaddress` to log in

**Comment by enthusedcoder** [comment]
Ok.  Well, I don't care what your recommendation is.  I don't want to login via the console.  I want to login via an rdp client.  Simply submitting a recommendation and then closing this ticket as if it were a solution is absolutely unacceptable.  I have been tracking this issues progress because it is important to me.  I will create a duplicate, open issue if this issue is not reopened.  Is this the kind of support I can expect for the zema board i paid almost $300 for, let me know now and I will return it for a refund so fast it will make your head spin

**Comment by Hedius** [comment]
CasaOS is a pure webinterface. The running operating system is a Debian 11 with wayland.
By default you won't get the old RDP linux solutions to get running there.

This issue is not related to CasaOS. Furthermore, you bought the zimaboard. This does not include any kind of software support.

If you need help with running RDP on debian... I recommend a community forum / askubuntu or any other linux forum....

**Comment by enthusedcoder** [comment]
So I guess that I am just hallucinating the output that I see when I plug the zemaboard into a monitor then, am I?

**Comment by Hedius** [comment]
> So I guess that I am just hallucinating the output that I see when I plug the zemaboard into a monitor then, am I?

You can always install a fresh clean operating system...

**Comment by enthusedcoder** [comment]
You must have missed the part of the original explanation were I explained how I already did that.  During the "version of casaos" section.

**Comment by Hedius** [comment]
With clean OS I meant using a clean Debian installer from https://debian.org and then installing the latest CasaOS release.

I have to do nothing. I am spending my spare time here atm. But I am out. You are so aggressive that you honestly can get someone else to help you.

**Comment by enthusedcoder** [comment]
Ok, then I lose the web interface and all the functionality that the product was supposed to deliver out of the box.  You are right.  You don't have to do anything.  And if that is going to be your take on this, then you actually will have to do one thing: refund my money when I return your POS product back to you

**Comment by Hedius** [comment]
> Ok, then I lose the web interface and all the functionality that the product was supposed to deliver out of the box. You are right. You don't have to do anything. And if that is going to be your take on this, then you actually will have to do one thing: refund my money when I return your POS product back to you

I literally just explained how to do a clean installation of the latest CasaOS release, but apparently you are so ignorant that you missed that. 

Also to make that clear. I am not a member of the company behind this.

And as I mentioned before. CasaOS itself is software in alpha state and zimaboard is a pure hardware product. If you buy a PC you also do not get Windows support by the manufacturer. Only hardware support.

**Comment by enthusedcoder** [comment]
And did I not tell you that I did that PRIOR to submitting this ticket, or can you not read?  What good would installing a fresh casaos instance a **second time** do that the first time did not, smart guy?

**Comment by Hedius** [comment]
No you did not. You used the default image from the casaos site which is outdated. As I have mentioned.

I suggested installing debian and then installing CasaOS.

**Comment by Hedius** [comment]
I explained it now twice. But just to be sure.
1. Install Debian with a desktop environment of your choice. https://www.debian.org/download
2. Run ` curl -fsSL https://get.casaos.io | sudo bash`

**Comment by enthusedcoder** [comment]
So, does apt-get dist-upgrade not work in the image on your website?  For you to sit here and tell me that "you will get a better result by deploying debian and then installing casaos on top of it", and trying to claim that image on your site is out of date just screams of throwing stuff at the wall to see what sticks.  Does apt-get dist-upgrade not work in the casaos image on your website?  I know it does because I have used it to ensure the operating system was fully up to date.  When you throw excuse after excuse as to why your product isn't behaving the way it is supposed to, people will stop believing you.  Rather than try to take my concerns seriously, you disregarded them, closed the ticket, and have been making non-stop excuses to justify it.  This could have gone so much better if you had had the common sense to actually engage with people, but that would only work if you actually put forth the effort to help resolve the issue and were up-front and honest, neither of which did or were.  Maybe consider these things the next time you want to disregard someone's issue.

**Comment by Hedius** [comment]
Not sure why you call it my website. As I have said I am an outsider and not related to the development of this project. I am only offering support from the community.

**Comment by Lauren-ED209** [comment]
@enthusedcoder, I'm Lauren, founder of ZimaBoard team. I sincerely apologize for the poor communication in our previous interactions. Please do not be angry with @Hedius  he has made significant contributions to the Zima and CasaOS community, and our team deeply respects him as a community partner.

The core issue here is that the Zima team did not effectively organize support for the issues you experienced with our existing product. Without a doubt, we should reopen this matter and have our technical colleagues, @LinkLeong and @tigerinus , further investigate and identify the problem, provide short-term solutions, and propose long-term strategies to avoid similar issues in future product releases. We will continue transparent communication within this issue.

If you remain unsatisfied with our product and services, please feel free to reach out to me and our support team at support@icewhale.org. We are committed to providing you with satisfactory service and support.

**Comment by LinkLeong** [comment]
Yes we are having the same problem, now we suggest you log out of your casaos account on zimaboard and log back in with rdp.

**Comment by raller1028** [comment]
https://github.com/IceWhaleTech/CasaOS/assets/57336867/d4ed8b27-af57-4090-aa00-27fe36f01b07

**Comment by tigerinus** [comment]
@enthusedcoder the solution provided by @LinkLeong and @raller1028 comes from https://c-nergy.be/blog/?p=16682 where it also explained the reason behind this issue in details.


There is also another solution at https://catch22cats.blogspot.com/2018/05/xrdp-blank-screen-with-ubuntu-1804.html?m=1 which solves the problem more permanently, even after each rebooting Zimaboard. 

Let this thread know how it goes after you've tried these solutions.

**Comment by LinkLeong** [comment]
We will close the issue and reopen it if you have any questions.
