### ISSUE TITLE
app id 填入无法绑定 无法点击提交

### ISSUE THREAD

**Issue by tslwoainil** [IceWhaleTech/CasaOS#119]
**Describe the bug**

app 填入无法绑定 无法点击提交

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.9
	 - Disk Total: 6595 
	 - Disk Used: 1622 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 0
	 - System Info: [Armbian 20.12 Buster \l Bit:32 Mem:989M Core:4 Linux aml-s812 5.9.0-rc7-aml-s812 #20.12 SMP Sun Dec 13 22:50:05 CST 2020 armv7l GNU/Linux]
	 - Browser: Edge 
	 - Version: 98.0.1108.62

**Comment by JohnGuan** [comment]
Please use English and re-edit according to the issue template.
请使用英语并按照issue模板重新编辑。你也可以加我微信：guanningchuan，我们可以在微信中进行中文交流。
