### ISSUE TITLE
[Feedback]LiveTv does not work in Jellyfin

### ISSUE THREAD

**Issue by mbaluda-ms** [IceWhaleTech/CasaOS#1190]
### Description

When configuring Livetv in Jellyfin via m3u files, playback does not work

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 100220 
	 - Disk Used: 11317 
	 - System Info: [Ubuntu 22.04.2 LTS   \l Bit:64 Mem:15769M Core:4]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 114.0.0.0

**Comment by LinkLeong** [comment]
We suggest you check the official jellyfin instructions or the community for answers
