### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by guimogi** [IceWhaleTech/CasaOS#1192]
**Describe the bug**
App store does not load

**To Reproduce**
1. Go to home
2. Click on App Store

**Expected behavior**
Loading the app store

**Screenshots**

**Desktop (please complete the following information):**
 - OS: casaOS v0.3.6

 - Browser Chrome and IE tested
 - Version v0.3.6
![Captura de tela 2023-06-17 163457](https://github.com/IceWhaleTech/CasaOS/assets/24488433/ca412053-d378-4c15-9c55-323b3f32cccd)

**Comment by tigerinus** [comment]
Can you follow https://wiki.casaos.io/en/troubleshooting/appstore-does-not-load and share your findings?

**Comment by tigerinus** [comment]
Now that v0.4.4 is released, where AppStore loading mechanism is revamped.

Please give it a try and see if this is still an issue.
