### ISSUE TITLE
[Feedback]UPgrade

### ISSUE THREAD

**Issue by davidsmoker** [IceWhaleTech/CasaOS#1194]
### Description

Hi, can not upgrade

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 27712 
	 - Disk Used: 10051 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 114.0.0.0

**Comment by Kordrad** [comment]
I had the same issue. You can find resolve here https://github.com/IceWhaleTech/CasaOS/issues/1181

**Comment by LinkLeong** [comment]
Thanks for your help @Kordrad , we will answer that in another question.
