### ISSUE TITLE
[Feedback]Unable to upgrade OS

### ISSUE THREAD

**Issue by VallisSPV** [IceWhaleTech/CasaOS#1195]
### Description

On clicking the upgrade button the loop spins but nothing happens. Can you help?

Many thanks

Steve

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 27712 
	 - Disk Used: 9841 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 114.0.0.0

**Comment by Kordrad** [comment]
Check this 
https://github.com/IceWhaleTech/CasaOS/issues/1181

**Comment by LinkLeong** [comment]
Thanks for your help @Kordrad , we will answer that in another question.
