### ISSUE TITLE
[Bug] Main Appstore does not load

### ISSUE THREAD

**Issue by WisdomSky** [IceWhaleTech/CasaOS#1196]
**Describe the bug**
The main appstore will not display unless if you installed a third-party appstore.

**To Reproduce**
1. Remove all custom appstores you installed and leave only the main appstore. 
2. Open CasaOS Dashboard and open the Appstore.
3. See the list is empty.

**Expected behavior**
The apps in the main Appstore should be displayed.

**Video**
https://clipchamp.com/watch/rAjO0L6rRvU

**Additional context**

The weird behavior occurred after the[ latest commit](https://github.com/IceWhaleTech/CasaOS-AppStore/commit/6fb68a608d077bc49096814c6e5d933e4ac93edc) of the main branch of the Main Appstore.

    casaos-cli app-management register app-store https://github.com/IceWhaleTech/CasaOS-AppStore/archive/refs/heads/main.zip

But if you use the [commit](https://github.com/IceWhaleTech/CasaOS-AppStore/commit/3b573262f064faa29e72a0169e3d4293e599b3e3) prior to the latest commit instead, it works fine as usual.

    casaos-cli app-management register app-store https://github.com/IceWhaleTech/CasaOS-AppStore/archive/3b573262f064faa29e72a0169e3d4293e599b3e3.zip

With this information, it's surmised that there is something in the latest commit that caused this issue to occur.

**Comment by Pedro1664** [comment]
I have reported this issue on my new machine and not yet received any reply, is a fix being worked on?

**Comment by tigerinus** [comment]
> **Describe the bug** The main appstore will not display unless if you installed a third-party appstore.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Remove all custom appstores you installed and leave only the main appstore.
> 2. Open CasaOS Dashboard and open the Appstore.
> 3. See the list is empty.
> 
> **Expected behavior** The apps in the main Appstore should be displayed.
> 
> **Video** https://clipchamp.com/watch/rAjO0L6rRvU
> 
> **Additional context**
> 
> The weird behavior occurred after the[ latest commit](https://github.com/IceWhaleTech/CasaOS-AppStore/commit/6fb68a608d077bc49096814c6e5d933e4ac93edc) of the main branch of the Main Appstore.
> 
> ```
> casaos-cli app-management register app-store https://github.com/IceWhaleTech/CasaOS-AppStore/archive/refs/heads/main.zip
> ```
> 
> But if you use the [commit](https://github.com/IceWhaleTech/CasaOS-AppStore/commit/3b573262f064faa29e72a0169e3d4293e599b3e3) prior to the latest commit instead, it works fine as usual.
> 
> ```
> casaos-cli app-management register app-store https://github.com/IceWhaleTech/CasaOS-AppStore/archive/3b573262f064faa29e72a0169e3d4293e599b3e3.zip
> ```
> 
> With this information, it's surmised that there is something in the latest commit that caused this issue to occur.

Can you share the log by running

`sudo journalctl -xef -u casaos-app-management`

**Comment by JaviTio** [comment]
Hello ,
I have installed the app today, Debian 11 (Proxmox LXC container) and executed 'wget -qO- https://get.casaos.io | sudo bash'

 i ran "sudo journalctl -xef -u casaos-app-management", 

`Jun 27 12:08:27 CasaOs-Debian11 casaos-app-management[578]: 2023-06-27T12:08:27.917Z        error        error when deserializing        {"err": "[]model.ServerAppList: decode slice: expect [ or n, but found \u0000, error found in #0 byte of ...||..., bigger context ...||...", "content": "{\"code\":401,\"mssage\":\"验签失败\"}", "property": "data.list", "func": "v1.(*appStore).AsyncGetServerList", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/v1/appstore.go", "line": 163}`

I also i get `"content": "{\"code\":401,\"mssage\":\"验签失败\"}"` doing 'curl https://api.casaos.io/casaos-api/v2/app/newlist  -H "Authorization: <token>"'  (follow https://wiki.casaos.io/en/troubleshooting/appstore-does-not-load)
