### ISSUE TITLE
请问这是什么错误？安装失败

### ISSUE THREAD

**Issue by w593062725** [IceWhaleTech/CasaOS#120]
[ INFO ] Install the necessary dependencies: curl smartmontools parted ntfs-3g
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.64.0-4+deb10u2).
ntfs-3g is already the newest version (1:2017.3.23AR.3-3+deb10u1).
parted is already the newest version (3.2-25).
smartmontools is already the newest version (6.6-1).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
[  OK  ] Docker already installed.
[ INFO ] Downloading CasaOS for linux/arm-7...
[ INFO ] https://github.com/IceWhaleTech/CasaOS/releases/download/v0.2.9/linux-arm-7-casaos.tar.gz
curl: (52) Empty reply from server
[FAILED] error 52 in command: ${net_getter} "$casa_url" > "$PREFIX/tmp/$casa_file"
root@arm:~#

**Comment by jerrykuku** [comment]
这个问题应该是从Github拉取安装包的时候出错了，没有拉取到。可以尝试重试，应该是网络环境导致的问题。

**Comment by JohnGuan** [comment]
This looks like a network problem, not a bug.
你可以加我微信：guanningchuan。我们在微信用中文进行交流。
