### ISSUE TITLE
[Feedback][功能请求] 希望添加自定义开机自启动脚本

### ISSUE THREAD

**Issue by Jeblqr** [IceWhaleTech/CasaOS#1205]
### Description

希望添加自定义开机自启动脚本，用于自动开启网卡混杂模式，ddns，etc.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 58322 
	 - Disk Used: 10861 
	 - System Info: [Debian GNU/Linux 12   \l Bit:64 Mem:M Core:2 Linux nas1 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Edge 
	 - Version: 114.0.1823.51

**Comment by tigerinus** [comment]
开机流程是 Linux 系统层面控制的，并非 CasaOS。

建议确定你的 Linux 发行版，然后在网上寻找相关的解决方案。
