### ISSUE TITLE
Key authentication

### ISSUE THREAD

**Issue by H4K0N42** [IceWhaleTech/CasaOS#1218]
**Is your feature request related to a problem? Please describe.**
When I expose port 80 to the internet, I don't want a password as protection

**Describe the solution you'd like**
Key authentication like on this side: [https://www.elster.de/eportal/login/softpse](https://www.elster.de/eportal/login/softpse)

**Describe alternatives you've considered**
2FA with Phone

**Additional context**
![image](https://github.com/IceWhaleTech/CasaOS/assets/78751562/8465994c-46c0-4899-9174-aa003cd3acf8)

**Comment by Circlewarrior08** [comment]
Yes, please do this!! I really really need this!

**Comment by udance4ever** [comment]
I honestly wouldn’t make anything but a simple web server public on port 80 - sounds like a recipe for disaster but I digress!

That said, I’m all up for secure access to CasaOS (and its services) and multiple ways of implementing it.

something to try: install [WG Easy](https://github.com/wg-easy/wg-easy) (it’s in one of the AppStores too) - I couldn’t believe how butt simple it was to create a Wireguard tunnel and have access to your local network.  It’s like magic, you flip the VPN switch and your phone acts like it’s connected over WiFi at home.  I was able to ssh into an administrate local servers and even bring up Emby on my phone and start streaming music while driving!  very very cool and quite thankful for CasaOS (and friends!) for making it this easy.  Give it a try.

**Comment by udance4ever** [comment]
> **Describe the solution you'd like** Key authentication like on this side: https://www.elster.de/eportal/login/softpse

I like this example though. I have Yubikeys I would love to use for authentication.

this issue could be merged with https://github.com/IceWhaleTech/CasaOS/issues/671

**Comment by H4K0N42** [comment]
> [udance4ever](/udance4ever)

Yes, I have now also set up Wireguard tunnels. I only expose the ports that need to be available. Anyway, thanks for the advice

**Comment by udance4ever** [comment]
@H4K0N42 noticed you closed this.  I think you requested a very valuable feature as the transition to more secure forms of authentication is not exactly a straight forward one (it’s kinda a mess if you haven’t experienced it yourself - just look at eBay’s implementation).  This is an opportunity for CasaOS to leapfrog and show what secure access to our own self-hosted data looks like and do away with all our passwords of the past!  Do you not agree?
