### ISSUE TITLE
[Bug] Error loading App Store list. Please try again. 加载 App Store 列表时出错。请重试。 

### ISSUE THREAD

**Issue by Frankzhang854** [IceWhaleTech/CasaOS#1220]
**Describe the bug**
加载 App Store 列表时出错。请重试。

> A clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
```

**System Time**

> Run `timedatectl` and share the output

```
(timedatectl output here)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by LinkLeong** [comment]
You can retry it, yesterday fixed a little

**Comment by LinkLeong** [comment]
We'll keep track of that in this question https://github.com/IceWhaleTech/CasaOS/issues/1215
