### ISSUE TITLE
[Bug] 温度显示不正确

### ISSUE THREAD

**Issue by xjxjin** [IceWhaleTech/CasaOS#1222]
**Describe the bug**
温度显示不正确

> 
希望可以正确显示功耗和cpu温度

> If applicable, add screenshots to help explain your problem.

本地显示这样
<img width="480" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/35513148/85a33a92-e6e0-4c56-aa97-3a157f864b81">

页面显示这样
<img width="305" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/35513148/6a4757ff-0139-43ee-8f31-37134bda1b45">

**Desktop (please complete the following information):**

```
 - OS: [MAC 10.14.6 ]
 - Browser [Edge]
 - Version [v0.4.3]
```

**System Time**
> Run `timedatectl` and share the output

```
               Local time: Fri 2023-06-30 01:02:49 CST
           Universal time: Thu 2023-06-29 17:02:49 UTC
                 RTC time: n/a                        
                Time zone: Asia/Shanghai (CST, +0800) 
System clock synchronized: yes                        
              NTP service: active                     
          RTC in local TZ: no   
```

**Comment by raller1028** [comment]
目前CasaOS只支持cpu直接提供的温度,不支持通过传感器提供的温度.
![image](https://user-images.githubusercontent.com/13556972/249071991-2d847d22-4a02-4b9b-a25f-6c40725da42c.png)
可以通过一下命令来确认你目前的设备获取温度的设备类型:
`cat /sys/devices/virtual/thermal/thermal_zone*/type`
通过以下命令获取对应设备的温度:
`cat /sys/devices/virtual/thermal/thermal_zone*/temp`

这是一些例子:
![image](https://user-images.githubusercontent.com/57336867/250049322-664a30f1-b5ee-453e-b20e-cc16e310dc83.png)
{"cpu-thermal": "39704"}

![image](https://user-images.githubusercontent.com/57336867/250050942-225eea37-4287-41a1-b9b1-a951fa621568.png)
{"acpitz": "31000", "x86_pkg_temp": "31000"}
[更多温度类型参考](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-thermal)
