### ISSUE TITLE
[Bug] Disk merge failed 

### ISSUE THREAD

**Issue by lbr77** [IceWhaleTech/CasaOS#1223]
**Describe the bug**

> When trying to merge disk,it shows up `move /DATA to /var/lib/casaos/files failed` in `POST http://hostname/v2/local_storage/merge/init`,with status 400.

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to `Storage manager`
2. Click on `Merge storages`
3. Select STORAGE1,STORAGE2 and so on.
4. Click on Submit
5. See error

**Expected behavior**

> Expected: Just create a merged storage.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

![](https://github.com/IceWhaleTech/CasaOS/assets/53066066/d696ac91-be51-43ab-8593-382d8a59990e)

**Desktop (please complete the following information):**

```
 - OS: Windows 11
 - Browser: Firefox 
 - Version: 114.0.2
```

**System Time**

> Run `timedatectl` and share the output

```
               Local time: Fri 2023-06-30 22:17:02 CST
           Universal time: Fri 2023-06-30 14:17:02 UTC
                 RTC time: Fri 2023-06-30 14:17:02
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: no
              NTP service: n/a
          RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

Here's the log I think should solve the problem.
I have three partitions relatively mounted on `/,/var,/home`,however hardlink is not accessible between different devices.

```bash
Jun 30 22:18:42 sakura casaos-local-storage[1281]: rename /DATA /var/lib/casaos/files: invalid cross-device link
Jun 30 22:18:42 sakura casaos-local-storage[1281]: {"time":"2023-06-30T22:18:42.571436894+08:00","id":"","remote_ip":"192.168.2.15","host":"192.168.2.19","method":"POST","uri":"/v2/local_storage/merge/init","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0","status":400,"error":"","latency":549644,"latency_human":"549.644µs","bytes_in":23,"bytes_out":57}
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by LinkLeong** [comment]
Based on the error you need to troubleshoot two problems.
1. The directory /var/lib/casaos/files is empty
2. The space on the system disk should be sufficient for the size before the merge (all data from /DATA before the merge will be moved to /var/lib/casaos/files)

**Comment by LinkLeong** [comment]
We will close the issue and reopen it if you have any questions.
