### ISSUE TITLE
[Bug] failed to load apps, please refresh later.

### ISSUE THREAD

**Issue by copycraft** [IceWhaleTech/CasaOS#1224]
pls help

**Comment by LinkLeong** [comment]
We'll keep track of that in this question https://github.com/IceWhaleTech/CasaOS/issues/1215

**Comment by copycraft** [comment]
both

**Comment by syncbricks** [comment]
Please ensure that storage is not removed, or storage link is not changed. if you do so you will get this error.

**Comment by lampsonnguyen** [comment]
what is the fix for this error? reinstall casa os?

**Comment by Massu4** [comment]
Same error here... it worked like a charme till this morning, but now I cannot see apps in the console. Apps are still running well though. 
Do you have any update?

**Comment by MonOttawa** [comment]
same error as well 

> Same error here... it worked like a charme till this morning, but now I cannot see apps in the console. Apps are still running well though. Do you have any update?

**Comment by kinhsman** [comment]
It appears that my docker service wasnt started. I ran the following command and my system is back up:
```
systemctl start docker
```

**Comment by dreadnought-0** [comment]
I am having this issue too.  I uninstall Casa and re-install it and everything comes back.  I install an app or 2 and it gives me the same error.  Tried rebooting, restarting docker and docker service.   Any ideas?   Containers are still online, but not Casa.   Tried on multiple devices, networks, etc.

**Comment by hoetzgit** [comment]
+1

**Comment by valselt** [comment]
> It appears that my docker service wasnt started. I ran the following command and my system is back up:
> 
> ```
> sudo systemctl start docker.service
> ```

this is helping me

**Comment by webportpl** [comment]
sudo systemctl start docker.service only this

**Comment by yanwarpro** [comment]
I try this command and casaos back to show the apps

**Comment by TheDyXer** [comment]
hey i got the same problem but the command didnt works for me

**Comment by cyberphantomcomputers-star** [comment]
> hey i got the same problem but the command didnt works for me

Same here. I have a fresh install of Ubuntu 25.10 and I have just installed Casa and found this issue. It had started on my computer at my office a few days ago running Ubuntu 22.04 server but I havent had time to sort it out. but now that I am seeing in on a brand new install of a new Ubuntu I am starting to this that this might be a problem with the API and Docker talking to each other

**Comment by eNg1ne85** [comment]
It is probably related to new Docker 29 API changes, it can be workaround with this solution: https://github.com/IceWhaleTech/CasaOS/issues/2407
