### ISSUE TITLE
[Alpha][Bug] 

### ISSUE THREAD

**Issue by Mr-Hunter-x** [IceWhaleTech/CasaOS#1226]
### What happened?

app loading error... how to fix this step by step in details...

### Screenshots

![zimaboard](https://github.com/IceWhaleTech/CasaOS/assets/138247524/e57a27d9-4984-43ad-990b-6d10328671bc)

**Comment by tigerinus** [comment]
@Mr-Hunter-x can you follow instructions at https://wiki.casaos.io/en/troubleshooting/appstore-does-not-load and collect the logs for us so we can investigate?

**Comment by tigerinus** [comment]
Now that v0.4.4 is released, where AppStore loading mechanism is revamped. 

Please give it a try and see if it is still an issue.
