### ISSUE TITLE
自定义安装的容器，在casaos上的标题不够整洁，我想修改它

### ISSUE THREAD

**Issue by aaaa223227** [IceWhaleTech/CasaOS#1228]
自定义安装的容器，在casaos上显示的标题不够整洁，我该如何重新命名？
我尝试修改容器主机名，但casaos上的标题并没有变化

**Comment by zhanghengxin** [comment]
已经在开发中了，最新的版本（0.4.4-alpha）是在设置里可以修改。

如果你是自定义的yaml，可以在 yaml 文件中 给 x-casaos.title.custom附值。

**Comment by zhanghengxin** [comment]
fix IceWhaleTech/CasaOS-UI#168
