### ISSUE TITLE
[Bug] get.casaos.io ssl certificate seems to have expired

### ISSUE THREAD

**Issue by thetechlink** [IceWhaleTech/CasaOS#1230]
when trying to install caseos by the following command there is an error about a bad certificate

curl -fsSL https://get.casaos.io | sudo bash

Here is the error

link@famnet-container:~$ curl -fsSL https://get.casaos.io | sudo bash
[sudo] password for link: curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

When going to the web url in firefox is shows a certificate that expired on 7/1/2023

<a href="https://ibb.co/Ttc9yqh"><img src="https://i.ibb.co/VTVf6pB/Screenshot-from-2023-07-01-21-42-56.png" alt="Screenshot-from-2023-07-01-21-42-56" border="0" /></a>

Not sure if this is the proper place to report but thought I would let everyone know. 

Thanks,
Zac

**Comment by jerrykuku** [comment]
Thanks for the heads up, the ssl certificate has been updated. It is now working properly.

**Comment by sseamonsterr** [comment]
I believe that the ssl certificate may have expired again

**Comment by cedenoas** [comment]
I'm getting the same error today....

**Comment by Dev01-D** [comment]
![Screenshot_20241110-090912](https://github.com/user-attachments/assets/ff8fa0a8-917f-4f57-8f85-b6159f4848c9)
Looks like it's still valid?

**Comment by faro75** [comment]
> Thanks for the heads up, the ssl certificate has been updated. It is now working properly.

could you check if the ssl certificate is updated 
thanks

**Comment by thetick1er** [comment]
Hi Cert has expired

**Comment by hohu67** [comment]
could you please again check if the ssl certificate is updated?
I'm not bale to install casaos because of the expired certificate
thanks

**Comment by benjamin-jouanno** [comment]
hey looks like tje Cert has expired again, unable to install as well

**Comment by boyprakasa** [comment]
```
[ INFO ] Install the necessary dependencies: Rclone
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[FAILED] Installation failed, please try again.
```

waiting for the ssl update 😊
