### ISSUE TITLE
[Alpha][Bug] 

### ISSUE THREAD

**Issue by lquessenberry** [IceWhaleTech/CasaOS#1232]
### What happened?

Error: invalid mount config for type "bind": bind source path does not exist

### Screenshots

![Screenshot 2023-07-02 at 20-12-52 CasaOS](https://github.com/IceWhaleTech/CasaOS/assets/5232993/1e6ffb71-fb82-47be-91cc-b0895eb92aed)
![Screenshot 2023-07-02 at 20-13-33 CasaOS](https://github.com/IceWhaleTech/CasaOS/assets/5232993/9ad9c34d-ef36-4e5d-9084-6c51354170ae)

**Comment by Hedius** [comment]
Do not use the docker snap of ubuntu. You need a plain docker installation from the apt package.

**Comment by tigerinus** [comment]
@lquessenberry - have you tried using a regular docker install?

I'm going to assume you've resolved this issue since @Hedius commented a month back. If it still repros, please open this issue again.
