### ISSUE TITLE
[Bug] The system panel cannot display temperature and power correctly

### ISSUE THREAD

**Issue by xjxjin** [IceWhaleTech/CasaOS#1236]
My system is unable to display power and temperature correctly
This is the error log I saw in the background

This is the error log I saw in the background. I saw an API request with a power and temperature of 0. What should I do to ensure that it can display the temperature normally

The version I am using is as follows:

CasaOs: v0.4.3

CPU information: hi3798mv100-series@4 Core processor | armv7l architecture
System version: Ubuntu 20.04.6 LTS
Available storage: 51.0% 3418.0M
Available memory: 38.9% 362.0M | Swap area: 68.7% 351.0M
Start time: 4 days, 13 hours, 58 minutes, 46 seconds
Equipment temperature: 75 ° C

CPU 信息 : hi3798mv100-series@4核处理器 | armv7l架构
系统版本 : Ubuntu 20.04.6 LTS 
可用存储 : 51.0% 3418.0M
可用内存 : 38.9% 362.0M | 交换区：68.7% 351.0M
启动时间 : 4 天 13 小时 58 分钟 46 秒
设备温度 : 75°C

<img width="368" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/35513148/aa02a888-fa75-446d-99df-c7fd7cf57fcb">

`04T14:07:20.100+0800	error	failed to publish event to message bus	{"error": "Post \"http://127.0.0.1:40260/v2/message_bus/event/casaos/casaos:system:utilization\": EOF", "event": {"sys_cpu":"{\"model\":\"arm\",\"num\":4,\"percent\":9.9,\"power\":{\"timestamp\":\"1688450840\",\"value\":\"0\"},\"temperature\":0}","sys_disk":"{\"avail\":3583270912,\"health\":true,\"size\":7031013376,\"used\":3139260416}","sys_mem":"{\"available\":390451200,\"free\":120774656,\"total\":976515072,\"used\":570011648,\"usedPercent\":58.4}","sys_net":"[{\"name\":\"eth0\",\"bytesSent\":3847718805,\"bytesRecv\":2111305574,\"packetsSent\":29815763,\"packetsRecv\":73632782,\"errin\":0,\"errout\":0,\"dropin\":4790,\"dropout\":0,\"fifoin\":0,\"fifoout\":0,\"state\":\"up\",\"time\":1688450840}]","sys_usb":"[{\"avail\":1251986833408,\"children\":null,\"model\":\"ST2000LM007-1R8174\",\"name\":\"sda\",\"size\":2000398933504}]"}, "func": "service.(*notifyServer).SendNotify", "file": "/home/runner/work/CasaOS/CasaOS/service/notify.go", "line": 63}`

**Comment by raller1028** [comment]
If still have problems, please reopen
