### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by pelepep** [IceWhaleTech/CasaOS#124]
**Describe the bug**
Installation is impossible

**To Reproduce**
1. Open terminal 
2. Enter the installation line of command
3. Wait 
5. The error is  ... [  OK  ] Docker already installed.
[ INFO ] Downloading CasaOS for linux/arm-6...
[ INFO ] https://github.com/IceWhaleTech/CasaOS/releases/download/v0.2.9/linux-arm-6-casaos.tar.gz
curl: (22) The requested URL returned error: 404 
[FAILED] error 22 in command: ${net_getter} "$casa_url" > "$PREFIX/tmp/$casa_fil
e"

**Expected behavior**
A quick install 

**Screenshots**
![Sélection_001](https://user-images.githubusercontent.com/6121569/157478298-4fbf7b97-c6cd-400e-b4fa-cb4a93c279d9.png)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS
 - Version : the latest oneRelease date: January 28th 2022

**Comment by yahoyoungho** [comment]
Not a maintainer but what is your exact OS for your pi? (seems like all raspberry pi distro was updated that day).

Also, I was able to install CasaOS yesterday with my pi  (raspberry pi with Bullseye Lite version), so you should give it another try after re-imaging your pi?

**Comment by LinkLeong** [comment]
We are sorry that we do not support arm-6 devices at this time.
