### ISSUE TITLE
[Bug] Cannot get AdguardHome to work (This site can't be reached)

### ISSUE THREAD

**Issue by max21722** [IceWhaleTech/CasaOS#1245]
**Describe the bug**
Cannot get AdguardHome to work

> A clear and concise description of what the bug is.
After the wizard installer, I get a Website unreachable on the port 3000 which is install the app. I tried different settings already.

**To Reproduce**
AdguardHome, make it through installation wizard process and click on the AdguardHome icon to launch the web page.

**System Time**

> Run `timedatectl` and share the output
               Local time: Fri 2023-07-14 08:48:48 EDT
           Universal time: Fri 2023-07-14 12:48:48 UTC
                 RTC time: Fri 2023-07-14 12:48:48
                Time zone: America/New_York (EDT, -0400)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.
I have a zimaboard bought on 2023 july 5th

**Comment by zhanghengxin** [comment]
You have to add  pictures or actions.

**Comment by raller1028** [comment]
@max21722 You can refer to  #1119

**Comment by raller1028** [comment]
This issue will be closed for the time being, if still having problems, please reopen
