### ISSUE TITLE
[Alpha][Bug] CasaOS 0.4.4 translations not added to crowdin.

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#1246]
### What happened?

I check the translations in crowdin and i see that i cant see any new string to translate but i see new text in the webapp of casaos.

https://crowdin.com/project/casaos

### Screenshots

![Screenshot_20230714_225620_Brave](https://github.com/IceWhaleTech/CasaOS/assets/18572939/e8c6c837-1ff8-49ee-ad25-7207d203c707)
![Screenshot_20230714_225735_Brave](https://github.com/IceWhaleTech/CasaOS/assets/18572939/ffdc3d60-6cf0-41c4-a865-f71dc68f7d9f)
![Screenshot_20230714_225838_Brave](https://github.com/IceWhaleTech/CasaOS/assets/18572939/692731bd-3f78-4291-930d-250a1db9d114)
![Screenshot_20230714_225907_Brave](https://github.com/IceWhaleTech/CasaOS/assets/18572939/b66ae162-2933-4574-8ded-f01568974c95)
![Screenshot_20230714_230308_Brave](https://github.com/IceWhaleTech/CasaOS/assets/18572939/fbae4e1a-6940-41d8-ae54-53a0e3e4bb4d)

**Comment by zhanghengxin** [comment]
I will update.

**Comment by AmadeusGraves** [comment]
thanks @zhanghengxin, but i have to reopen the issue because i have encountered some more words to translate.

![image](https://github.com/IceWhaleTech/CasaOS/assets/18572939/75cf77fd-f144-4de8-89a1-2867c7a4a16a)

![image](https://github.com/IceWhaleTech/CasaOS/assets/18572939/22f97b4c-d1a2-4c7b-8028-550596e7a815)

**Comment by AmadeusGraves** [comment]
Related  #1258
