### ISSUE TITLE
Docker imange name is to long to display

### ISSUE THREAD

**Issue by Ranrar** [IceWhaleTech/CasaOS#1250]
**Describe the bug**

> GUI webbog, whern a docker imange name is long. You can not se the system status CPU ore RAM usage of the container.

**To Reproduce**

> install a docker image with a longe  name my eksampel: "05jchambers/legendary-minecraft-geyser-floodgate:latest" 

**Expected behavior**

> I Think the Title name in the docker imange scould be the same under system status. My image is names Minecraft Server and is only displaye under the main icon.

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/95967772/aa3bf02e-1e59-4194-abbd-189a5e8b7111)

**Desktop (please complete the following information):**

```
 - OS: Ubuntu server 20.04
 - Browser Edge on Windows 11
 - CasaOS Version: v0.4.4

**Comment by vkartk** [comment]
@Ranrar For now, you have the option to modify the app setting and update the Container hostname to resolve the Docker image name.
