### ISSUE TITLE
应用中心所有应用都显示的不兼容 armv7 设备

### ISSUE THREAD

**Issue by adl10929** [IceWhaleTech/CasaOS#1251]
### What happened?

有一段时间时间没安装新的应用了，突然发现所有的应用都显示的不兼容 armv7 设备，包括之前安装好的、正在使用的，正在使用的还能正常使用，新应用不能安装了

### Screenshots

![1](https://github.com/IceWhaleTech/CasaOS/assets/62693144/b1fd2e7e-becd-4713-9ed4-7a29ed689a83)
![2](https://github.com/IceWhaleTech/CasaOS/assets/62693144/d93d0d47-9265-4966-ba66-abc134116478)
![3](https://github.com/IceWhaleTech/CasaOS/assets/62693144/ff6b857d-9aa4-4236-9eba-dabb9d4c4969)

**Comment by raller1028** [comment]
因为目前的应用商店部分应用的版本是最新的,但是这个最新版里面不包含armv7的架构
这里显示的是当前应用商店默认安装的版本
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/0a1197bb-aaf4-48ac-b71e-f75205be7cc0)
可以在hub.docker.com看到该版本只支持amd64和arm64,所以如果你想下载对应的armv7版本需要替换掉我上面所说的版本号,再次在商店中点击安装就能安装到你想要的armv7版本
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/4efb89d7-544a-4945-b67e-3fd04e952b85)
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/6b2dd935-7826-40d1-a2a1-2f4dbb054e1d)

**Comment by raller1028** [comment]
If still have problems, please reopen

**Comment by ETWang1991** [comment]
This seems to be a problem caused by Docker's own architecture adjustments. We will discuss and determine an elegant solution to the problem. Please give us a little more time.
这似乎是由于Docker本身的架构调整导致的问题，我们会讨论确定一个即优雅又解决问题的办法，请给我们再多一点时间

**Comment by dpedrinha** [comment]
> This seems to be a problem caused by Docker's own architecture adjustments. We will discuss and determine an elegant solution to the problem. Please give us a little more time. 这似乎是由于Docker本身的架构调整导致的问题，我们会讨论确定一个即优雅又解决问题的办法，请给我们再多一点时间

Any news on that matter?

**Comment by sdlkhfksl** [comment]
![屏幕截图 2024-08-10 135050](https://github.com/user-attachments/assets/76bc4309-00da-46ac-9179-35ea014139f4)
