### ISSUE TITLE
Add old Docker-CLI UI on dashboard

### ISSUE THREAD

**Issue by Voroniyx** [IceWhaleTech/CasaOS#1253]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to have the old UI on the dashbard in the brwoser back for container which are running without compose. Could there support for a docker compose container and not compose based container? 
**Describe alternatives you've considered**
There are no realy alternatives, just add back the ui for compose and not compse based docker container

**Comment by zhanghengxin** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/24197448/ab4b4630-4da3-4cd9-9452-b4e5aee53454)

Whether the answer you were looking for?

**Comment by Voroniyx** [comment]
where do i found this?
This are the only options i get after importing my container to casaos?
![](https://i.imgur.com/yXzThyx.png)
Or did i something wrong while importing it?

**Comment by zhanghengxin** [comment]
your display falls under the category of CLI and uses an older management policy.

now, only Compose Docker can be configured.

If your want add older settings. I will need to add the demand to the product backlog.

**Comment by ETWang1991** [comment]
稍后我们会推出工具，允许你把CLI自动转化成docker compose，之后就可以设置了。请问这样听起来令人满意吗？或者说，你还是希望运行在CLI下？ @Voroniyx

**Comment by Voroniyx** [comment]
@ETWang1991 That sounds good, yet I think the possibility should exist to run apps under CLI, it made it much easier for e.g. newbies like me to get started and therefore the support should be there. You can still make a suppressed warning perhaps.

**Comment by fimreal** [comment]
I don't like docker-compose, it didn't give me anything useful, except for the uglier container names and more virtual network interface. Of course, there is also the issue of incompatible versions.

CasaOS brings me convenient container management and service panels. but if CasaOS wants to pursue container deployment templating, why not directly try using k3s/k8s? The funny thing is, I just switched my home server from the k3s to CasaOS.

less is more! I don't understand why it's necessary to replace Docker-CLI with compose.

**Comment by zhanghengxin** [comment]
In the compose phase, there is a very interesting feature that allows users to share their collection of applications and maintain them as a personal store. This is helpful in getting technically savvy users to help "novice users" and I believe it will lead to a small boom in the future.


Trust me, we are making progress towards a better future.

**Comment by fimreal** [comment]
> 

The goal is to make more apps available quickly by relying on third-party app stores, i.e., off-the-shelf containerized deployment scripts, I guess. 
CasaOS relies on container extensions and doesn't lack the ability to deploy apps. And there are too many competitors that can deploy containers, they just lack a web UI like nastools.

**Comment by Voroniyx** [comment]
@ETWang1991 @zhanghengxin  I think the function to convert legacy container to compose container is a good start
