### ISSUE TITLE
[Alpha][Bug]  Freshly installed casaOS 0.4.4 alpha SMB share asking for password

### ISSUE THREAD

**Issue by pokurt** [IceWhaleTech/CasaOS#1257]
### What happened?

Newly installed casaOS asks for a password which i didnt set.
my smb.conf:
```
...
# IMPORTANT: CasaOS will not provide technical support for any issues
#            caused by unauthorized modification to the configuration.

[global]
## fruit settings
   min protocol = SMB2
   ea support = yes
## vfs objects = fruit streams_xattr
   fruit:metadata = stream
   fruit:model = Macmini
   fruit:veto_appledouble = no
   fruit:posix_rename = yes
   fruit:zero_file_id = yes
   fruit:wipe_intentionally_left_blank_rfork = yes
   fruit:delete_empty_adfiles = yes
   map to guest = bad user
```
my smb.casa.conf:
```
[Media]
comment = CasaOS share Media
public = Yes
path = /DATA/Media
browseable = Yes
read only = No
guest ok = Yes
create mask = 0777
directory mask = 0777
force user = root
```

### Screenshots

![image](https://github.com/IceWhaleTech/CasaOS/assets/43902347/ca90bce7-ff95-4c56-a052-3b6431316ec1)
![image](https://github.com/IceWhaleTech/CasaOS/assets/43902347/bd99fee1-ec35-4af9-9c1d-31289f58c5c5)

**Comment by raller1028** [comment]
@pokurt I'm sorry I can't reproduce your situation, can you please provide me with the steps to reproduce it, I've installed a new v0.4.4 or upgraded from v0.4.3 to v0.4.4, and the login box for smb doesn't pop up. It only pops up when I actively type in the smb address on windows.

**Comment by raller1028** [comment]
`[amd64_casaos043_SMB_test]
comment = CasaOS share amd64_casaos043_SMB_test
public = Yes
path = /DATA/amd64_casaos043_SMB_test
browseable = Yes
read only = No
guest ok = Yes
create mask = 0777
directory mask = 0777
force user = root
`

**Comment by pokurt** [comment]
> @pokurt I'm sorry I can't reproduce your situation, can you please provide me with the steps to reproduce it, I've installed a new v0.4.4 or upgraded from v0.4.3 to v0.4.4, and the login box for smb doesn't pop up. It only pops up when I actively type in the smb address on windows.

Hey seems like it's not an issue with CasaOS but needs to be concerned because we are using guest enabled login for the shared folders. Im on windows 11 beta preview and they seem to change registry keys for File Sharing in the recent build.

I can connect to CasaOS fileshare using my iphone:
![image](https://github.com/IceWhaleTech/CasaOS/assets/43902347/d05ee4c1-6f1d-4356-8f07-95be8be3ee5d)


I was searching internet for a fix and this comment on Microsoft forum helped me to get it back working:
https://techcommunity.microsoft.com/t5/storage-at-microsoft/smb-insecure-guest-auth-now-off-by-default-in-windows-insider/bc-p/3724830/highlight/true#M1448

**Comment by raller1028** [comment]
ありがとう。If still have problems, please reopen.

**Comment by pokurt** [comment]
will close this for now. issue still appears on latest Insider build of windows since they are forcing SMB server to have an authentication. not something related with casaOS but windows.
