### ISSUE TITLE
[Bug] 下载资源安全漏洞

### ISSUE THREAD

**Issue by HellyW** [IceWhaleTech/CasaOS#1261]
**Describe the bug**

观察到下载文件接口为： http://host:port/v3/file?token=TOKEN&path=PATH

去除参数token，修改接口地址为 http://host:port/v3/file?path=PATH  仍可以下载成功

尝试更换PATH为其它访问路径，仍能下载正确文件

e.g:  http://demo.casaos.io/v3/file?path=/DATA/Gallery/20020312-140154-Cab-New-York-2002.jpg

**Comment by raller1028** [comment]
Thank you. We'll fix it soon.

**Comment by LinkLeong** [comment]
We'll fix it in 0.4.4.1, I'll close the issue first, thanks for the feedback!
我们会在0.4.4.1中修复,我会先关闭该问题,感谢反馈!
