### ISSUE TITLE
[Bug] 树莓派在应用中心安装mineos-node以及Cloudflare后都无法启动

### ISSUE THREAD

**Issue by fanmingming** [IceWhaleTech/CasaOS#1265]
如题

**Comment by EmbyTV** [comment]
同样，44新版都无法启动了

**Comment by CorrectRoadH** [comment]
你是0.4.3安装了，然后升级到0.4.4不能用还是在0.4.4之后才装的?🤔我这装完都能正常的用

**Comment by fanmingming** [comment]
> 

全新安装最新版casaos之后。

**Comment by CorrectRoadH** [comment]
> > 
> 
> 全新安装最新版casaos之后。

能不能给我更多的信息，比如日志，比如怎么个无法启动法。是图标点开，然后又跳回casaos。还是点图标然后跳到网页，但是说应用还没有启动之类的。或者能进应用页面但是不能用👀

**Comment by EmbyTV** [comment]
> > > 
> > 
> > 
> > 全新安装最新版casaos之后。
> 
> 能不能给我更多的信息，比如日志，比如怎么个无法启动法。是图标点开，然后又跳回casaos。还是点图标然后跳到网页，但是说应用还没有启动之类的。或者能进应用页面但是不能用👀

我启动docker的时候汇报这个： `Error response from daemon: driver failed programming external connectivity on endpoint emby (90841618fdeaaed7e1f7930eb0f2d4d81b0d84738785a08ac5b10b0dd6c4ca18): invalid transport protocol: 0`

重启docker也不行

**Comment by fanmingming** [comment]
拉取镜像没问题，但是应用安装完成后图标会自己变成灰色。商店内的大多数应用都存在这个问题，我只是试了两个应用的安装都存在一样的问题。

**Comment by CorrectRoadH** [comment]
> `Error response from daemon: driver failed programming external connectivity on endpoint emby (90841618fdeaaed7e1f7930eb0f2d4d81b0d84738785a08ac5b10b0dd6c4ca18): invalid transport protocol: 0`

这看起来像是端口被占用的问题，你可以在设置里换一个HOST的端口，看看能不能启动

**Comment by EmbyTV** [comment]
> 拉取镜像没问题，但是应用安装完成后图标会自己变成灰色。商店内的大多数应用都存在这个问题，我只是试了两个应用的安装都存在一样的问题。

我刚好和你反过来，还都是44版才有的问题，我反而是商店的可以启动，自己自定义的多数都不行

**Comment by EmbyTV** [comment]
> > `Error response from daemon: driver failed programming external connectivity on endpoint emby (90841618fdeaaed7e1f7930eb0f2d4d81b0d84738785a08ac5b10b0dd6c4ca18): invalid transport protocol: 0`
> 
> 这看起来像是端口被占用的问题，你可以在设置里换一个HOST的端口，看看能不能启动

哪个host？

**Comment by CorrectRoadH** [comment]
> 拉取镜像没问题，但是应用安装完成后图标会自己变成灰色。商店内的大多数应用都存在这个问题，我只是试了两个应用的安装都存在一样的问题。

那点那个灰色，过一会又变成灰的吗? 感觉是端口被占用的问题。如果方便的话，能不能远程调试一下，比如私信我，你的联系方式

**Comment by CorrectRoadH** [comment]
> > > `Error response from daemon: driver failed programming external connectivity on endpoint emby (90841618fdeaaed7e1f7930eb0f2d4d81b0d84738785a08ac5b10b0dd6c4ca18): invalid transport protocol: 0`
> > 
> > 
> > 这看起来像是端口被占用的问题，你可以在设置里换一个HOST的端口，看看能不能启动
> 
> 哪个host？

方便私下联系一下，我远程过去看看吗?

**Comment by EmbyTV** [comment]
> > 拉取镜像没问题，但是应用安装完成后图标会自己变成灰色。商店内的大多数应用都存在这个问题，我只是试了两个应用的安装都存在一样的问题。
> 
> 那点那个灰色，过一会又变成灰的吗? 感觉是端口被占用的问题。如果方便的话，能不能远程调试一下，比如私信我，你的联系方式

我找到问题了，我这边就是bridge模式下，一启用UDP就启动不了，就是端口映射那里，纯TCP好像没问题

**Comment by EmbyTV** [comment]
> > > > `Error response from daemon: driver failed programming external connectivity on endpoint emby (90841618fdeaaed7e1f7930eb0f2d4d81b0d84738785a08ac5b10b0dd6c4ca18): invalid transport protocol: 0`
> > > 
> > > 
> > > 这看起来像是端口被占用的问题，你可以在设置里换一个HOST的端口，看看能不能启动
> > 
> > 
> > 哪个host？
> 
> 方便私下联系一下，我远程过去看看吗?

Telegram可以吗

**Comment by EmbyTV** [comment]
果然就是这个UDP的问题，可以多次复现了 @CorrectRoadH

**Comment by CorrectRoadH** [comment]
> > > > > `Error response from daemon: driver failed programming external connectivity on endpoint emby (90841618fdeaaed7e1f7930eb0f2d4d81b0d84738785a08ac5b10b0dd6c4ca18): invalid transport protocol: 0`
> > > > 
> > > > 
> > > > 这看起来像是端口被占用的问题，你可以在设置里换一个HOST的端口，看看能不能启动
> > > 
> > > 
> > > 哪个host？
> > 
> > 
> > 方便私下联系一下，我远程过去看看吗?
> 
> Telegram可以吗

我是OK的

**Comment by EmbyTV** [comment]
> > > > > > `Error response from daemon: driver failed programming external connectivity on endpoint emby (90841618fdeaaed7e1f7930eb0f2d4d81b0d84738785a08ac5b10b0dd6c4ca18): invalid transport protocol: 0`
> > > > > 
> > > > > 
> > > > > 这看起来像是端口被占用的问题，你可以在设置里换一个HOST的端口，看看能不能启动
> > > > 
> > > > 
> > > > 哪个host？
> > > 
> > > 
> > > 方便私下联系一下，我远程过去看看吗?
> > 
> > 
> > Telegram可以吗
> 
> 可以的

已经私发您邮箱了

**Comment by fanmingming** [comment]
Mineos-Node无论怎么搞始终无法启动。更改端口也不行，Cloudflared可正常启动了。😵‍💫

**Comment by CorrectRoadH** [comment]
> Mineos-Node无论怎么搞始终无法启动。更改端口也不行，Cloudflared可正常启动了。😵‍💫 无奈只能在screen通过openjdk来启动mc服务器。😓

🫠 https://hub.docker.com/r/mjeries/mineos-node/tags 这个问题可能是 mineos-node 不支持arm设备，我看这个镜像只提供了amd64的版本，所以可能是因为架构不兼容导致的。
