### ISSUE TITLE
after updating 0.44, the memory footprint becomes larger 0.44版本怎么回退0.43

### ISSUE THREAD

**Issue by zhangf1** [IceWhaleTech/CasaOS#1267]
如题，更新0.44后，内存占用变大，想着回退到0.43或者以前，另外，怎么屏蔽版本更新
As the title suggests, after updating 0.44, the memory footprint becomes larger

**Comment by ETWang1991** [comment]
如果方便的话，麻烦截图看下仪表盘上内存占用率
If it's convenient, could you please take a screenshot of the memory usage on the dashboard?

**Comment by zhangf1** [comment]
不好意思，是安装别的软件内存变大了
