### ISSUE TITLE
[Bug]  the function of update  don't run as expected

### ISSUE THREAD

**Issue by LSP0123** [IceWhaleTech/CasaOS#1274]
**Describe the bug**

> function of update will use the number tag instead of "latest" 

**To Reproduce**
> 1. upload .yaml file to depoly linuxserver/syncthing:latest
> 2. Click on 'update'
> 3. check the seeting of  linuxserver/syncthing:latest
> 4. See linuxserver/syncthing:1.23.5 on seeting
> 6. use portainer to check,will find the 1.23.5 images is using and the latesr version is unsed

**Expected behavior**

> only the latest tag will be used ,the 1.23.5 image will not be download and the container will not be created by 1.23.5

**Screenshots**

> ![image](https://github.com/IceWhaleTech/CasaOS/assets/31061624/2aaa37db-b001-40a2-b39a-9b170dd8ccc7)
![image](https://github.com/IceWhaleTech/CasaOS/assets/31061624/e641248a-edb8-4801-9398-73b3f0814b26)
![image](https://github.com/IceWhaleTech/CasaOS/assets/31061624/b6d389ea-7b0a-445a-b9ed-55426ea47c8e)

**Desktop (please complete the following information):**

```
 - CasaOS: ubuntu server 22.04.2
 - DesktopOS:Windows11 22621.1992 
 - Browser :Firefox 115.0.2 X64 & Edge 115.0.1901.183 X64
```

**System Time**
```
               Local time: Sat 2023-07-22 01:35:01 UTC
           Universal time: Sat 2023-07-22 01:35:01 UTC
                 RTC time: Sat 2023-07-22 01:35:01
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Comment by tigerinus** [comment]
@LSP0123 - if you are talking about the images in AppStore should be using tag `latest` instead of a specific numbered tag, see the pinned issue at https://github.com/IceWhaleTech/CasaOS-AppStore/issues

![image](https://github.com/IceWhaleTech/CasaOS/assets/7172560/f03bbe69-db76-4e1a-9352-41e1d9606fad)

**Comment by tigerinus** [comment]
I am closing this issue for now. 

@LSP0123 - If I misunderstand this issue, feel free to re-open. Cheers!

**Comment by LSP0123** [comment]
@tigerinus ，I have read the  [issue latest ](https://github.com/IceWhaleTech/CasaOS-AppStore/issues/167).

I'm not talking about the images in AppStore. every image which was depolyed by DockerCompose or CLI should not be semmed like come from the AppStore. 

I depoly the image with DockerCompose . the yaml is from the linuxserver.io ,and i want to use the "latest" . so it should not be changed .

I think there should have a tag to define where the images comes from.  OR give user the right to choice the default upgrade solution. 

sorry for open the issue . but i think there have some people want to use the `latest ` 

Thank you for your answer. Cheers!

**Comment by LSP0123** [comment]
@tigerinus 
please re-open this issue

**Comment by tigerinus** [comment]
@LSP0123  - if we add a logic:

- if image tag is `latest` then ignore whatever tag from appstore;
- otherwise use tag from appstore.

Will you be OK with it?

**Comment by LSP0123** [comment]
> @LSP0123 - if we add a logic:
> 
> * if image tag is `latest` then ignore whatever tag from appstore;
> * otherwise use tag from appstore.
> 
> Will you be OK with it?

@CorrectRoadH. Thank you for re-open 

@tigerinus. I think it's not the best way.

Does casaos will add "upgrade all container" function on the feature version?
if added , this logic will distory the container which was wanted to keep on  version .


I think you can add a tag to define the container upgrade logic ,if add Appstore tag ,the container use the appstore logic; if not ,use the image tag.

for example:
```
    images tag                          AppStore            upgrade logic
1. linuxserver/syncthing:1.23.5         Yes                 appstore logic
2. linuxserver/syncthing:1.23.5         No                  keep version & never upgrade
3. linuxserver/syncthing:latest         Yes                 notification user it will be changed to the first one 
                                                            linuxserver/syncthing:1.23.5   Yes  upgrade with appstore
4. linuxserver/syncthing:latest         No                  always use latest images
```

The container which upgrade in appstore logic and verifed by casaos should add a logo on homepage :
![image](https://github.com/IceWhaleTech/CasaOS/assets/31061624/01d6c6c7-488b-4506-a5f0-3994bfcd934f)

**Comment by tigerinus** [comment]
That would require much more work (including frontend changes), which is not likely to happen in near term.

Why wouldn't skipping any app with `latest` tag work for you?

**Comment by LSP0123** [comment]
I know if casaos change the upgrade logic will have many work to do .  the features I've described will not  be implemented in the next release or next next release。But I hope it will be implemented in the future。

Yes，skipping any app with `latest` tag is enough for me now。
I have read   #986(能否提供自动更新全部Docker的功能) . Casaos will have the function that auto upgrade all container in the future.
There will come a day when someone should use a specific version of the image which is also on the AppStore. then , you still have to face it. 
The logic that  skipping any app with `latest` tag is not enough for casaos

I'm just suggesting   &  Thank  you for replay
