### ISSUE TITLE
[Bug] 启动问题

### ISSUE THREAD

**Issue by zhangf1** [IceWhaleTech/CasaOS#1277]
casaos安装在玩客云上，升级0.44版本后，每次插电启动不了，至少需要重新插电4次以上，才能顺利启动。
无法启动是指设备里面没有玩客云，网页无法加载。

**Comment by jerrykuku** [comment]
可以尝试进入终端，输入 `systemctl status casaos-gateway ` 来看看服务有没有启动。

**Comment by raller1028** [comment]
@zhangf1 你好,方便将上面命令的输出贴上来吗

**Comment by zhangf1** [comment]
![Uploading S30725-20163176.jpg…]()

**Comment by zhangf1** [comment]
这是启动后，输入的代码，没启动在路由器里压根找不到设备
![S30725-20163176](https://github.com/IceWhaleTech/CasaOS/assets/103484452/f22a6df0-f3b5-4232-a381-5119c3484e42)

**Comment by zhangf1** [comment]
不能ssh,我重新刷一下吧

**Comment by LinkLeong** [comment]
> 

期待你的结果,如果还是不行,可以反馈一下你的系统.
Looking forward to your results, and if it still doesn't work, feedback on your system.

**Comment by zhangf1** [comment]
已找到问题，应该是外接固态原因，可能是供电不足，拔掉以后可以正常启动

**Comment by LinkLeong** [comment]
感谢反馈,我会关闭该问题,如有疑问可重新打开.
Thanks for the feedback, I will close the issue and reopen it if you have any questions.
