### ISSUE TITLE
Update to 0.4.4 not happening 

### ISSUE THREAD

**Issue by fabitencourt** [IceWhaleTech/CasaOS#1278]
Update 0.4.4 not happening

I've tried many times and it never completes

- OS: linux
 - CasaOS Version: 0.4.3
 - Disk Total: 27712 
 - Disk Used: 13228 
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
 - Remote Version: 0.4.4
 - Browser: Chrome 
 - Version: 90.0.4430.212

**Comment by djfatbody** [comment]
The installer script downloads the 0.4.4 archive but the script incorrectly references the archive for the alpha11 release.  If you edit this line in the install script the process completes successfully.

**Comment by jerrykuku** [comment]
> The installer script downloads the 0.4.4 archive but the script incorrectly references the archive for the alpha11 release. If you edit this line in the install script the process completes successfully.

I will fix this issue soon. Thanks for the heads up.

**Comment by jerrykuku** [comment]
This has now been fixed so you can try again, also is it possible to tell me which way you did the update?

**Comment by jerrykuku** [comment]
Please try `sudo apt-get update --allow-releaseinfo-change`  before update CasaOS.

**Comment by MyLab-odyssey** [comment]
Thank you! This was the trick ;-) Update now worked.
