### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zainmsyed** [IceWhaleTech/CasaOS#1279]
**Describe the bug**
There is no prompt when opening the terminal 
![Screenshot 2023-07-22 at 9 39 32 AM](https://github.com/IceWhaleTech/CasaOS/assets/101473255/3ed76c94-50e5-402a-b226-0ccd29caa8f2)

> A clear and concise description of what the bug is.
Unable to use the terminal because every time it is launched wince the 0.4.4 update it does not show the prompt. The screenshot is attached. This was not an issue before. 

EDIT: Does work in chrome. Doesn't work in brave

**To Reproduce**

> Steps to reproduce the behavior:

1. open terminal
2. login

**Expected behavior**

> A clear and concise description of what you expected to happen.

Should be able to type n terminal

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: Debian 12
 - Browser Brave
 - Version 0.4.4
```

**System Time**

> Run `timedatectl` and share the output

Can't do that because terminal is not working

**Comment by zhanghengxin** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/24197448/9484da41-bfdd-4fe3-9709-430f641c271e)
