### ISSUE TITLE
容器的ipv6端口未开放映射

### ISSUE THREAD

**Issue by lalalale39** [IceWhaleTech/CasaOS#128]
**Describe the bug**
以FileBrowser 为例：应用商店里的FileBrowser 的设置里面主机端口设置好并应用后，在portainer中观察发现PORT CONFIGURATION中增加了0.0.0.0：端口的前缀，导致仅ipv4地址可以访问，ipv6地址加端口号无法访问。
我试过在portainer中修改取消0.0.0.0的前缀，但是未成功，估计和CasaOS的配置有关；而其他利用ssh或者portainer直接安装的容器没有这个问题，均能通过ipv6或者ipv4地址访问。

**Comment by LinkLeong** [comment]
感谢你反馈的这个问题,目前我这边是只绑定了ipv4,我会开个分支解决这个问题.再次感谢你的反馈.

**Comment by LinkLeong** [comment]
已经修复了,会在下个版本迭代的时候发布,再次感谢反馈
