### ISSUE TITLE
[Bug] Unable to update new ZimaBoard to 0.4.4

### ISSUE THREAD

**Issue by radiganmcse** [IceWhaleTech/CasaOS#1280]
I bought a new ZimaBoard and out of box I can't update. When I click "Upgrade Now" it's stuck on this screen. It came with 0.3.6.

![image](https://github.com/IceWhaleTech/CasaOS/assets/48632176/19b6ce98-9d3e-4186-a82e-c9a916342a90)

**Comment by raller1028** [comment]
It could be the network. Can you update it from the command line?
Update command: 
`curl -fsSl https://get.casaos.io/update/v0.4.4-1 | sudo bash`

**Comment by raller1028** [comment]
[2023-07-24 19-02-26.zip](https://github.com/IceWhaleTech/CasaOS/files/12145069/2023-07-24.19-02-26.zip)

**Comment by radiganmcse** [comment]
That didn't work. Here's the output from the terminal

Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 https://download.docker.com/linux/debian bullseye InRelease
Hit:3 http://security.debian.org/debian-security bullseye-security InRelease
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease
Get:5 http://deb.debian.org/debian testing InRelease [168 kB]
Get:6 http://security.debian.org/debian-security testing-security InRelease [48.0 kB]
Get:7 http://deb.debian.org/debian testing-updates InRelease [49.6 kB]
Reading package lists... Done        
E: Repository 'http://deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'bookworm' to 'trixie'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://security.debian.org/debian-security testing-security InRelease' changed its 'Codename' value from 'bookworm-security' to 'trixie-security'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://deb.debian.org/debian testing-updates InRelease' changed its 'Codename' value from 'bookworm-updates' to 'trixie-updates'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

**Comment by raller1028** [comment]
You can try `sudo apt update` first, and then run the update command

**Comment by jerrykuku** [comment]
Please try `sudo apt-get update --allow-releaseinfo-change` before update CasaOS.

**Comment by raller1028** [comment]
@radiganmcse  Please reply to the upgrade failure under this issue https://github.com/IceWhaleTech/CasaOS/issues/1287.
