### ISSUE TITLE
[Bug] USB接口连接阵列柜有一定的概率 能识别成功

### ISSUE THREAD

**Issue by leesonaa** [IceWhaleTech/CasaOS#1281]
开发者您好：
   我的情况是usb口插的铁威马阵列柜，有一定概率 能 挂上 ，这个中途中可能需要重启若干次，/dev里找不到设备，/media/devmon里也没有任何数据

**阵列柜有休眠功能**

复现方式：
- 硬盘柜进入休眠状态后，重启casaos，重启后没有自动挂载
- 硬盘柜没有休眠的时候弹出，拔掉usb接口，再插入识别成NaN

![image](https://github.com/IceWhaleTech/CasaOS/assets/97571961/4f8627b5-a147-4324-8487-eef66fae901d)
![image](https://github.com/IceWhaleTech/CasaOS/assets/97571961/bccff9d4-3ac9-493f-9a27-ddc2bb35920e)
**上面这是正常状态下**

**下面这是重启后的**
![image](https://github.com/IceWhaleTech/CasaOS/assets/97571961/08c65b7d-2fd8-4361-8e58-2a9bfe9a021b)
![image](https://github.com/IceWhaleTech/CasaOS/assets/97571961/07383bb1-f566-4463-bbc5-c6f0fbf810f6)
![image](https://github.com/IceWhaleTech/CasaOS/assets/97571961/2383cc08-0a9f-4fb2-90d9-55b7fc3b47fb)

就算是拔掉usb接口再插回去也没用，阵列柜上的开关重启一下也没用，依旧识别不到。不知道问题出在哪里。

**Comment by jerrykuku** [comment]
请在终端输入 ` systemctl status devmon@devmon.service ` ，把返回的信息反馈一下谢谢。

**Comment by jerrykuku** [comment]
服务都是正常运行的，其它USB设备是否能够正常的挂载？ 或者阵列柜在其它设备上是否能够正常的挂载？

**Comment by jerrykuku** [comment]
我感觉像是你的阵列柜的分区表可能存在问题，是什么分区格式？现在的问题应该已经不是CasaOS的问题，是系统层面手动挂载貌似都不成功。
