### ISSUE TITLE
CLI Clean install Failed

### ISSUE THREAD

**Issue by Mstrrlm** [IceWhaleTech/CasaOS#1283]
**Describe the bug**
Apologize if I’m doing this report incorrectly new to all this 

I followed the Casa OS wiki page for a clean, install through command line. I followed the uninstall, it successfully uninstalled then copied the command to reinstall and this’s what it put out with no apparent install.

   _____                 ____   _____ 
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___  
 | |    / _` / __|/ _` | |  | |\___ \ 
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/ 
                                      
   --- Made by IceWhale with YOU ---

[  OK  ] Your hardware architecture is : x86_64
[  OK  ] Your System is : Linux
[  OK  ] Your Linux Distribution is : debian 
[  OK  ] Memory capacity check passed.
[  OK  ] Disk capacity check passed.
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease                    
Hit:3 https://download.docker.com/linux/debian bullseye InRelease                       
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease                           
Get:5 http://security.debian.org/debian-security testing-security InRelease [48.0 kB]
Get:6 http://deb.debian.org/debian testing InRelease [168 kB]
Get:7 http://deb.debian.org/debian testing-updates InRelease [49.6 kB]
Reading package lists... Done        
E: Repository 'http://security.debian.org/debian-security testing-security InRelease' changed its 'Codename' value from 'bookworm-security' to 'trixie-security'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'bookworm' to 'trixie'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://deb.debian.org/debian testing-updates InRelease' changed its 'Codename' value from 'bookworm-updates' to 'trixie-updates'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
casaos@CasaOS:~$ 

> Steps to reproduce the behavior:

1. Go to Terminal into board
2. Followed Wiki for uninstall 
3. Copied cli commands to install 
4. See above 

**Expected behavior**

> Casaos installation 

**Desktop (please complete the following information):**

```
 - OS: [e.g. iOS] NA
 - Browser [e.g. chrome, safari] NA
 - Version [e.g. 22] NA
```

**System Time**

> Run `timedatectl` and share the output

```
(timedatectl output here)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
>

**Comment by LSP0123** [comment]
> E: Repository 'http://security.debian.org/debian-security testing-security InRelease' changed its 'Codename' value from 'bookworm-security' to 'trixie-security'
> N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
> E: Repository 'http://deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'bookworm' to 'trixie'
> N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
> E: Repository 'http://deb.debian.org/debian testing-updates InRelease' changed its 'Codename' value from 'bookworm-updates' to 'trixie-updates'
> N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

it seemd like that your apt source is using testing channel . you can change it to stable channel or change it like default .and try again

**Comment by Hedius** [comment]
The default image on zimaboards ships with a mix of bullseye and testing repos.

Basically mixing debian 11 and 13 now.

I strongly recommend that people remove the testing source...

**Comment by JohnGuan** [comment]
> The default image on zimaboards ships with a mix of bullseye and testing repos.
> 
> Basically mixing debian 11 and 13 now.
> 
> I strongly recommend that people remove the testing source...

Yes, previously there was a testing repo to solve xrdp compatibility issues so I will remove the testing repo in a later release.

**Comment by raller1028** [comment]
@Mstrrlm Hello can I close this question please?

**Comment by raller1028** [comment]
This issue is temporarily closed, if still have problems please reopen :)
