### ISSUE TITLE
[Bug] An error is reported when the port is selected as TCP+UDP

### ISSUE THREAD

**Issue by tangge233** [IceWhaleTech/CasaOS#1284]
**Describe the bug**

当端口协议设置为 TCP+UDP 后出现了错误。
An error occurred when the port protocol was set to TCP+UDP.

**To Reproduce**

> Steps to reproduce the behavior:

打开容器设置，并将其中一个端口设置为 TCP+UDP
Open the container settings and set one of the ports to TCP+UDP

**Expected behavior**

> A clear and concise description of what you expected to happen.

错误信息（Error message）: Error response from daemon: driver failed programming external connectivity on endpoint marvelous_curtis-main_app-1 (eba4ed835931a19d558b18ab9c2367acf13022021bf5cff5dc213a6e5f112e7d): invalid transport protocol: 0

**Screenshots**

> If applicable, add screenshots to help explain your problem.

![NsxfymOv1ZIokAJ.png](https://s2.loli.net/2023/07/23/NsxfymOv1ZIokAJ.png)
![InYSHU29q7lPTVy.png](https://s2.loli.net/2023/07/23/InYSHU29q7lPTVy.png)

**Desktop (please complete the following information):**

```
 - OS: armbian armv7
 - Browser Edge
 - Version 0.4.4
```

**System Time**

> Run `timedatectl` and share the output

```
Local time: Sun 2023-07-23 22:50:09 CST
           Universal time: Sun 2023-07-23 14:50:09 UTC
                 RTC time: n/a
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

Docker 镜像（Docker Mirror）：superng6/qbittorrentee

**Comment by CorrectRoadH** [comment]
fix in https://github.com/IceWhaleTech/CasaOS-UI/pull/199. It will be fix in next release
