### ISSUE TITLE
[Bug] Can't update CasaOS on my Zimaboard

### ISSUE THREAD

**Issue by Samubrogno** [IceWhaleTech/CasaOS#1287]
**Describe the bug**

> Can't update CasaOS on my Zimaboard. When I click update nothing happens.

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to 'settings'
2. Click on 'update'
3. See error

**Expected behavior**

> Infinite loading.

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/84378461/0bdddc9e-f18c-4cef-b8dc-05d8aacd4316)

**Comment by thomasjpatterson** [comment]
Can confirm, same issue. I was trying to update from out of box (as in brand new delivered) from 0.4.1 and it just sits.

**Comment by vexeval** [comment]
Same here, seems to be stuck on the same screen.
![image](https://github.com/IceWhaleTech/CasaOS/assets/90877660/3b4b5957-658b-4926-90fd-69853f8c9f5a)

**Comment by Cp0204** [comment]
Try update by SSH

**Comment by jerrykuku** [comment]
Login into SSH, try `sudo apt-get update --allow-releaseinfo-change`.

**Comment by vexeval** [comment]
> Login into SSH, try `sudo apt-get update --allow-releaseinfo-change`.

Thanks! Can't believe I forgot to do that!
![image](https://github.com/IceWhaleTech/CasaOS/assets/90877660/c2fabddc-863f-4f12-a0d3-3eae7c5b4e05)

**Comment by raller1028** [comment]
if still have problem, please reopen

**Comment by williamrankin** [comment]
Are there any steps after "sudo apt-get update --allow-releaseinfo-change"?

I'm a noob and still have the same issue after that command

**Comment by williamrankin** [comment]
> if still have problem, please reopen

Can you reopen - I'm a nood and can't find how to do that
