### ISSUE TITLE
[Alpha][Bug] 

### ISSUE THREAD

**Issue by phcl1998** [IceWhaleTech/CasaOS#1289]
### What happened?

在4.3版本之前手动安装的docker应用都是可以设置端口号、ip以及图标，但是最近更新到4.4版本，发现无法应用设置选项没有了。

### Screenshots

![6DO9}H7HN}P WF)KM6L5VNO](https://github.com/IceWhaleTech/CasaOS/assets/125857645/90892d70-5ed9-48df-98c2-a81556eb6a86)

**Comment by phcl1998** [comment]
如果没法设置应用的ip、端口等相关信息，那么我将无法使用域名访问casaos里的应用。还有一点能否添加一个内网外访问自动切换的按键？我在内网访问casaos自动切换到局域网ip，使用外网访问自动切换到域名或者公网ip？

**Comment by ETWang1991** [comment]
Are you clicked the update button in the upper left menu?

**Comment by CorrectRoadH** [comment]
You can see the solve in here: https://www.youtube.com/watch?v=WNEt2ZzrazI🥳
You can see the Announcement in our discord. this is the original text👀
<img width="1045" alt="CleanShot 2023-07-26 at 16 22 16@2x" src="https://github.com/IceWhaleTech/CasaOS/assets/29306285/595b9c34-205d-47ee-bf7d-590c934643d9">

**Comment by phcl1998** [comment]
> Are you clicked the update button in the upper left menu?

没有

**Comment by phcl1998** [comment]
> 总的来说，就是0.4.3升级到0.4.4换一个应用格式，就是更厉害了，需要用户手动把旧应用格式升级成新应用格式，才会有设置面板。👀不过在0.4.4-1引入了自动升级功能。你也可以尝试升级到0.4.4-1(不过还在测试)，想升的话，可以在这里继续联系我或者能在discord中找到升级命令。

我有一台设备可以试试4.4.1，您能提供一下升级命令吗？谢谢！

**Comment by CorrectRoadH** [comment]
> 功能

curl -fsSL https://get.casaos.io/update/v0.4.4-1 | sudo bash

升级完，就有新应用和旧应用的面板，在下面旧应用可以对应用的那个三点点开的菜单里面选rebuild应用，就能自动升级应用了(理论上有失败的可能性)

**Comment by phcl1998** [comment]
> > 功能
> 
> `curl -fsSL https://get.casaos.io/update/v0.4.4-1 | sudo bash`
> 
> 升级完，就有新应用和旧应用的面板，在下面旧应用可以对应用的那个三点点开的菜单里面选rebuild应用，就能自动升级应用了(理论上有失败的可能性)

可以了，谢谢
