### ISSUE TITLE
Feature Request - Read current Docker containers and display

### ISSUE THREAD

**Issue by NightHawkATL** [IceWhaleTech/CasaOS#129]
**Is your feature request related to a problem? Please describe.**
No problem, just suggestion

**Describe the solution you'd like**
I would like the option to choose to allow CasaOS to read the current Docker install and any containers that are already installed to be added as "apps" on the main page after install completes. This would allow CasaOS to be a good contender against portainer, IMO.

**Describe alternatives you've considered**
Portainer

**Additional context**
Just ask if you need any other information.

**Comment by JohnGuan** [comment]
Already implemented in v0.3.1
