### ISSUE TITLE
No Apps Settings Button

### ISSUE THREAD

**Issue by TCDev69** [IceWhaleTech/CasaOS#1292]
**Is your feature request related to a problem? Please describe.**
i need to change sometimes apps settings

**Describe the solution you'd like**
get the settings button back

**Describe alternatives you've considered**
--

**Additional context**
![image](https://github.com/IceWhaleTech/CasaOS/assets/102576942/0d147406-dd94-440c-8ab6-213b32b1d486)

**Comment by ETWang1991** [comment]
Are you clicked the update button in the upper left menu?

**Comment by Zono4ever** [comment]
Same here, after update casaos to v.0.4.4, I dont see the options setting button and update button for the app. :( Need this two options button back they are so helpfull!

**Comment by CorrectRoadH** [comment]
You can see the solve in here: https://www.youtube.com/watch?v=WNEt2ZzrazI🥳
You can see the Announcement in our discord. this is the original text👀
<img width="1045" alt="CleanShot 2023-07-26 at 16 22 16@2x" src="https://github.com/IceWhaleTech/CasaOS/assets/29306285/595b9c34-205d-47ee-bf7d-590c934643d9">

**Comment by TCDev69** [comment]
reinstall all apps, but exporting it
