### ISSUE TITLE
There is no place to view installation logs after installing an app in the app center应用中心安装应用后没有查看安装日志的地方

### ISSUE THREAD

**Issue by aop870325** [IceWhaleTech/CasaOS#1300]
The Alist app is integrated in the App Center, which is a very convenient solution to install Alist again in the docker.
However, one problem is that Alist will generate a random password after installation, and you need to check the installation log to see the Alist login password.
Now, there is no way to view Alist installation log after installation in App Center, so I can't see the Alist login password.
应用中心集成了 Alist 应用，非常方便的解决了在 docker 再次安装 Alist 的操作。
但有个问题就是 Alist 安装完成后会生成一个随机的密码，需要查看安装日志才能看到 Alist 后台登陆密码，
现在应用中心安装完成后没有办法查看 Alist 安装日志，也就查看不了Alist 的登陆密码

**Comment by 1Tourist** [comment]
安装完成后点击alist右上角三个点，打开“设置”，在右上角有个“终端与日志”，在终端中输入“./alist admin”，就可以看到初始账号和密码，一般账号都是“admin”，密码随机
