### ISSUE TITLE
[Bug] Fresh install full of Cache

### ISSUE THREAD

**Issue by Ventrex** [IceWhaleTech/CasaOS#1310]
**Describe the bug**
There is alot of junk/cached items on a fresh device and install.
For example lot of cache in the following folder "/home/casaos/.cache"

**To Reproduce**
Go to the folder "/home/casaos/.cache"
Maybe more folders are filled. But to scared to remove these folders, maybe I break things.

**Expected behavior**
Cleared cache when you do a clean install.
When just installed a clean install the image is already a few gigs in size.  

**Screenshots**
None at this moment

**Desktop (please complete the following information):**
 - OS: CasaOS

**Additional context**
Got a Zimaboard with 4Gb and 32Gig disk.
Had to reinstall this zimaboard and found all those junk/cache files

**Comment by LinkLeong** [comment]
So is your problem that the cache is full when you reinstall casaos, or is it that the cache is full when you get zimaboard, we'll need you to post a couple of screenshots to help us pinpoint the problem if it's convenient, thanks!

**Comment by Ventrex** [comment]
Sadly I don’t know if it was already full when it was shipped.
But the image of it contains the cache.
I followed the tutorial from this site https://docs.zimaboard.com/faq/Restore-factory-settings.html
There you can download 2 images.

Will post screens soon.

**Comment by Ventrex** [comment]
Lucky there is no information but maybe clear the history of root when finish the image
![image](https://github.com/IceWhaleTech/CasaOS/assets/29728210/1a267b35-ef35-41a4-94f4-8c20f2260a9d)

The .cache folder 
![image](https://github.com/IceWhaleTech/CasaOS/assets/29728210/d858cb40-ba59-42fc-bd9d-97ac833fa89c)

Sizewise I don't know the impact.
But maybe some files may contain information about logins. 
For example I see a workgroup 192.168.4.1 in some of the DB files.
![image](https://github.com/IceWhaleTech/CasaOS/assets/29728210/4953cebb-9f94-46d4-884c-0bf1dee6c2ef)

Also found a mozilla profile. This may contain usernames and passwords. 
![image](https://github.com/IceWhaleTech/CasaOS/assets/29728210/2c285599-270c-4a67-99ce-e237e712f374)

**Comment by jerrykuku** [comment]
Thank you for your feedback, we will avoid these cache files in the new version of ZimaBoard pre-installed system. It should be in a clean and brand new state.

**Comment by jerrykuku** [comment]
We have fixed this issue in the new version of the pre-installed system. I will close this issue.
