### ISSUE TITLE
[Bug] store don't load and app can't be reinstalled 

### ISSUE THREAD

**Issue by RSerejo** [IceWhaleTech/CasaOS#1315]
**Describe the bug**

![image](https://github.com/IceWhaleTech/CasaOS/assets/43152685/e551edab-56e9-4fac-8476-937a2091fd58)

> Store don't load and i can't reinstall or update any app.

**To Reproduce** i don't know

> Steps to reproduce the behavior:

NA

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

rebuild even don't work
![image](https://github.com/IceWhaleTech/CasaOS/assets/43152685/f15e00ec-e4f1-4009-9e17-90f4b4beb78b)

```
 - OS: Ubuntu
 - Browser Brave
 - Version 22
```

**System Time**

> Run `timedatectl` and share the output

```
(serejo@casa:~$ timedatectl
               Local time: Thu 2023-08-03 19:28:53 UTC
           Universal time: Thu 2023-08-03 19:28:53 UTC
                 RTC time: Thu 2023-08-03 19:28:54
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
[sudo journalctl -xef -u casaos-gateway.txt](https://github.com/IceWhaleTech/CasaOS/files/12254460/sudo.journalctl.-xef.-u.casaos-gateway.txt)
##
sudo journalctl -xef -u casaos-app-management 
[sudo journalctl -xef -u casaos-app-management.txt](https://github.com/IceWhaleTech/CasaOS/files/12254493/sudo.journalctl.-xef.-u.casaos-app-management.txt)
##
sudo journalctl -xef -u casaos.service 
[sudo journalctl -xef -u casaos.service.txt](https://github.com/IceWhaleTech/CasaOS/files/12254503/sudo.journalctl.-xef.-u.casaos.service.txt)

```

**Additional context**
X

**Comment by RSerejo** [comment]
sudo casaos-uninstall
curl -fsSL https://get.casaos.io/update/v0.4.4-1 | sudo bash
done

**Comment by RSerejo** [comment]
sudo casaos-uninstall
curl -fsSL https://get.casaos.io/update/v0.4.4-1 | sudo bash
done

**Comment by raller1028** [comment]
Hello, is this problem solved? Are there any other problems?

**Comment by raller1028** [comment]
if still have problem, please reopen
