### ISSUE TITLE
[Bug] Can't open Terminal for docker container

### ISSUE THREAD

**Issue by itsMikeLowrey** [IceWhaleTech/CasaOS#1316]
**Describe the bug**

When I try and open the terminal for the docker container after installing it. I am not able to type any input in and the cursor just flashes. Here is a screenshot: https://imgur.com/a/CsCAS6X

**To Reproduce**

1. Fresh install of casaOS [v0.4.4-1](https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.4.4-1)
2. Install any image
3. Once image is installed, attempt to open terminal into docker container.
4. See no terminal given

**Expected behavior**

I expected to be able to get the terminal window to give commands to the container after navigating to the container settings. 

**Screenshots**

https://imgur.com/a/CsCAS6X

**Desktop (please complete the following information):**

```
 - OS: Windows 10 
 - Browser: Chrome
 - Version: Version 115.0.5790.111 (Official Build) (64-bit)
```

**System Time**

```
                Local time: Thu 2023-08-03 23:55:09 UTC
                Universal time: Thu 2023-08-03 23:55:09 UTC
                 RTC time: Thu 2023-08-03 23:55:09
                Time zone: Etc/UTC (UTC, +0000)
                System clock synchronized: yes
               NTP service: active
               RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

The logs output a lot of text. If they are needed I will add them but there was a lot of text so I will save them until they are requested.

**Additional context**

> I am able to run commands into the docker container by using the terminal (found in the global settings) option and typing in, "sudo docker exec monerod /usr/local/bin/monerod status" for example. This process does take a long time, (like 1 minute).  I am not able to simply click the settings tab next to each image and get the terminal like I am on other devices. This device is a radxa zero with only 1gb of ram if that is helpful also. The container terminal might just be timing out, but it is strange that the terminal found in the global setting works fine. Just not the terminal found in the setting for each individual container. The board is running debain 12 also. I also have tried to perform the same tasks with the same results on iPad. The global terminal prompts me for the root password when I use it, but each individual container does not.

**Comment by tigerinus** [comment]
apparently this is caused by a recent change in Golang + Docker.

- https://github.com/moby/moby/issues/45935

we are looking closely at this issue and will measure the best step to take and get this issue addressed soon.

**Comment by itsMikeLowrey** [comment]
That was a super fast response! Let me know if I can give you any more info or help out anyway. Thank you so much.

**Comment by tigerinus** [comment]
> That was a super fast response! Let me know if I can give you any more info or help out anyway. Thank you so much.

It's fixed but pending to be tested.

The fix will be part of next release if all good.
