### ISSUE TITLE
Nextcloud container terminal not working

### ISSUE THREAD

**Issue by tarekela** [IceWhaleTech/CasaOS#1318]
In the Nextcloud container the terminal is not working.
when I go to settings and run the terminal, the window opens, but its not possible to type in it.
Nextcloud is installed from the Appstore. 

System-Informations:
 - OS: linux
 - CasaOS Version: 0.4.4.1
 - Disk Total: 119612 
 - Disk Used: 9808 
 - System Info: [Ubuntu 22.04.2 LTS   \l Bit:64 Mem:15873M Core:4 Linux casaos-server 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
 - Remote Version: 0.4.4.1
 - Browser: Firefox 
 - Version: 116.0

![grafik](https://github.com/IceWhaleTech/CasaOS/assets/141399302/29b783e1-6b52-4139-a0a6-43d6253fad24)

**Comment by itsMikeLowrey** [comment]
I think the bug is being worked on: https://github.com/IceWhaleTech/CasaOS/issues/1316

**Comment by tarekela** [comment]
> I think the bug is being worked on: #1316

**Comment by tarekela** [comment]
> I think the bug is being worked on: #1316

Thank you. That means, it will be fixed in v0.4.4.2.

**Comment by tarekela** [comment]
OK. I installed now the older version:

`sudo casaos-uninstall`
`curl -fsSL https://get.casaos.io/v0.4.4 | sudo bash`

I will leave v0.4.4.1 and wait for 0.4.4.2

Thank you for help.
