### ISSUE TITLE
[Bug] The empty folder which was copyed to another path by Files will be a file not a folder

### ISSUE THREAD

**Issue by LSP0123** [IceWhaleTech/CasaOS#1323]
**Describe the bug**

The empty folder which was copyed to another path by "Files" will be a file not a folder

**To Reproduce**

1.use a normal user to creat a folder 
```
casaos@nas:/DATA/Documents$ mkdir 1
casaos@nas:/DATA/Documents$ ls -al
drwxrwxr-x 1 casaos casaos  2  8月  5 21:36 .
drwxr-xr-x 1 casaos casaos 74  7月 29 23:59 ..
drwxrwxr-x 1 casaos casaos  0  8月  5 21:36 1
```

2.use Files application copy or move the folder to another path
![image](https://github.com/IceWhaleTech/CasaOS/assets/31061624/b78e2b9b-68fa-43c3-9aee-3a213c374ea7)

3.the "folder" whcih is in the new path is a file and its owner is changed to root 
```
casaos@nas:/DATA/Downloads$ ls -al
drwxrwxr-x 1 casaos casaos        3796  8月  5 21:36  .
drwxr-xr-x 1 casaos casaos          74  7月 29 23:59  ..
-rw-r--r-- 1 root   root             0  8月  5 21:36  1

```

**Expected behavior**

the "new" folder should not to be a file and its woner should not be changed  

**Desktop (please complete the following information):**

```
 - OS: Win11 22H2
 - Browser :Edge
 - Version : 115.0.1901.188 
```

**System Time**

> Run `timedatectl` and share the output
```
casaos@nas:/DATA/Downloads$ timedatectl
               Local time: 六 2023-08-05 21:49:20 CST
           Universal time: 六 2023-08-05 13:49:20 UTC
                 RTC time: 六 2023-08-05 13:49:20
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

```

**Additional context**
[[Bug] “FileBrowser” PUID/PGID do not take effect](https://github.com/IceWhaleTech/CasaOS-AppStore/issues/230)
The FileBrowser container which is in the AppStore is used root too. It will also change the owner of the file to root

**Comment by LinkLeong** [comment]
Sorry for replying so late, I checked your problem.
1: the size of folder "1" is not correct, we also tested and did not find the problem of folder to file.
![img_v2_642ebd2c-da5a-42df-8fa0-ea288dc536dg](https://github.com/IceWhaleTech/CasaOS/assets/13556972/4a16d6af-da52-4829-8053-168e699f539d)

2: the change of permissions at present, this bug does exist, this has @ETWang1991  to plan the modification time!

**Comment by LSP0123** [comment]
Add message , The filesystem what i used is 'BTRFS',can you try again on it?
@LinkLeong 

![image](https://github.com/IceWhaleTech/CasaOS/assets/31061624/5656fe76-32d4-47a3-b634-60029ae919c2)

**Comment by LinkLeong** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/545c2328-77b2-43e1-858e-007030df2c8b)

https://github.com/IceWhaleTech/CasaOS/assets/13556972/819aee3b-e440-4e55-bbd2-8ccc19816c5c

I ran the test, but it didn't do what you said.

**Comment by LinkLeong** [comment]
It has been put into version 0.4.4-3 and you can update it to give feedback on the status of the issue.
