### ISSUE TITLE
[Bug] Containers does not detect automounted drives

### ISSUE THREAD

**Issue by Talleyrand-34** [IceWhaleTech/CasaOS#1325]
A lauched container, if configured to read a path, it appears empty when the drive is automounted

**To Reproduce**

1. Setup automount
2. Setup a container to read data from a automounted drive directory (/media/devmon/x) (to test preferebly Jellyfin or nextcloud)
3. Reboot system
4. Check container and the content is not loaded
5. If the container is rebooted it appears correctly

**Expected behavior**

The autodrive is mounted on init and then docker containers boot.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: ARMbian
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
```

**Comment by raller1028** [comment]
Is that what you're trying to say? You plug in a USB and the automount path is /media/devmon/x, but the path you write inside your container is /media/devmon, and then the container doesn't dynamically mount the device you mounted?

**Comment by raller1028** [comment]
Hi, I tried to customize the installation of jellyfin, and mapped the path to the automount when I first installed it, and when jellyfin started for the first time, it was able to check the files under the mapped path normally. So this issue will be closed for now, if you still have problems, please reopen it.
