### ISSUE TITLE
make Web UI field totally editable

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#134]
Hello
Please make Web UI field totally editable like the image below, so in cases like when we are setup a reverse proxy and the container is gonna get a subdomain after the creation when it's got list in Apps when we click on it it will open.
Cause if it's like `mydomain.com:1111` under the Apps when we already setup the subdomain if we click on `mydomain.com:1111` it's not gonna open anything because it's should be `mycontainer.mydomain.com` so when we click on the container image under Apps it will open `mycontainer.mydomain.com` which is the correct address and will open the webpage for us.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/DC5G4Mw/Screenshot-2022-03-22-140457.png" alt="Screenshot-2022-03-22-140457" border="0"></a>

**Comment by LinkLeong** [comment]
First of all, thank you for your feedback, the problem you said we have been discussing, we think not everyone will have such expertise, but we will not ignore the seriousness of the problem, we will find a way to solve the problem.

**Comment by AuthorShin** [comment]
@LinkLeong Thanks for the reply, You can add a toggle above it so if anyone wants it they can enable it or in Setting of CasaOS add a toggle to select between simple mode or advance mode so in this way you can categorize even more options base on this simple or advance mode.

**Comment by LinkLeong** [comment]
Your question we have included, will be updated later, thank you for your feedback

**Comment by AuthorShin** [comment]
It's fixed.
Thank you very much.
