### ISSUE TITLE
[Bug] 关于Failed to load apps, please refresh later.

### ISSUE THREAD

**Issue by yu1chaofan** [IceWhaleTech/CasaOS#1343]
关于Failed to load apps, please refresh later.
已经参考 #1224 #1215 无法解决
arm7架构  

日志:
Aug 20 21:29:24 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:29:24.11790023+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":81125378,"latency_human":"81.125378ms","bytes_in":0,"bytes_out":172}
Aug 20 21:29:29 aml-s812 casaos-app-management[9633]: 2023-08-20T21:29:29.073+0800        error        failed to list compose apps with store info        {"error": "No label \"com.docker.compose.project.config_files\" set on container \"534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4\" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
Aug 20 21:29:29 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:29:29.073682413+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":31135529,"latency_human":"31.135529ms","bytes_in":0,"bytes_out":172}
Aug 20 21:29:34 aml-s812 casaos-app-management[9633]: 2023-08-20T21:29:34.125+0800        error        failed to list compose apps with store info        {"error": "No label \"com.docker.compose.project.config_files\" set on container \"534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4\" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
Aug 20 21:29:34 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:29:34.125797232+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":84559437,"latency_human":"84.559437ms","bytes_in":0,"bytes_out":172}
Aug 20 21:29:39 aml-s812 casaos-app-management[9633]: 2023-08-20T21:29:39.064+0800        error        failed to list compose apps with store info        {"error": "No label \"com.docker.compose.project.config_files\" set on container \"534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4\" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
Aug 20 21:29:39 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:29:39.064360122+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":37888644,"latency_human":"37.888644ms","bytes_in":0,"bytes_out":172}
Aug 20 21:29:44 aml-s812 casaos-app-management[9633]: 2023-08-20T21:29:44.102+0800        error        failed to list compose apps with store info        {"error": "No label \"com.docker.compose.project.config_files\" set on container \"534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4\" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
Aug 20 21:29:44 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:29:44.102686707+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":64686099,"latency_human":"64.686099ms","bytes_in":0,"bytes_out":172}
Aug 20 21:29:49 aml-s812 casaos-app-management[9633]: 2023-08-20T21:29:49.062+0800        error        failed to list compose apps with store info        {"error": "No label \"com.docker.compose.project.config_files\" set on container \"534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4\" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
Aug 20 21:29:49 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:29:49.063193885+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":30348430,"latency_human":"30.34843ms","bytes_in":0,"bytes_out":172}
Aug 20 21:29:54 aml-s812 casaos-app-management[9633]: 2023-08-20T21:29:54.094+0800        error        failed to list compose apps with store info        {"error": "No label \"com.docker.compose.project.config_files\" set on container \"534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4\" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
Aug 20 21:29:54 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:29:54.094456591+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":58123226,"latency_human":"58.123226ms","bytes_in":0,"bytes_out":172}
Aug 20 21:30:15 aml-s812 casaos-app-management[9633]: 2023-08-20T21:30:15.655+0800        error        failed to list compose apps with store info        {"error": "No label \"com.docker.compose.project.config_files\" set on container \"534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4\" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
Aug 20 21:30:15 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:30:15.655441205+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":30491642,"latency_human":"30.491642ms","bytes_in":0,"bytes_out":172}
Aug 20 21:30:15 aml-s812 casaos-app-management[9633]: 2023-08-20T21:30:15.697+0800        error        failed to list compose apps with store info        {"error": "No label \"com.docker.compose.project.config_files\" set on container \"534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4\" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
Aug 20 21:30:15 aml-s812 casaos-app-management[9633]: {"time":"2023-08-20T21:30:15.698156105+08:00","id":"","remote_ip":"10.8.0.2","host":"10.0.0.145","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203","status":500,"error":"","latency":28269596,"latency_human":"28.269596ms","bytes_in":0,"bytes_out":172}
Aug 20 21:54:51 aml-s812 systemd[1]: /lib/systemd/system/casaos-app-management.service:9: PIDFile= references path below legacy directory /var/run/, updating /var/run/casaos/app-management.pid → /run/casaos/app-management.pid; please update the unit file accordingly.

**Comment by yu1chaofan** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/32660987/174a6ace-dc13-4311-b842-6ffdddf52532)

**Comment by CorrectRoadH** [comment]
```
Aug 20 21:29:34 aml-s812 casaos-app-management[9633]: 2023-08-20T21:29:34.125+0800 error failed to list compose apps with store info {"error": "No label "com.docker.compose.project.config_files" set on container "534a9100c868a502a360759c3cbd27e6ea7ef92ccb03c0a5bc0b59f6d67586c4" of compose project", "func": "v2.(*AppManagement).GetAppGrid", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/internal_web.go", "line": 25}
```
似乎是有个容器导致app management崩了🤔 方便和我连接到你的CasaOS过去看看吗? 可以通过邮箱、telegram或者你习惯的方式联系我。

**Comment by yu1chaofan** [comment]
感谢您的回复
http://219.140.86.95:23450/
admin qqwe123

**Comment by CorrectRoadH** [comment]
我给你的评论删掉了🥺防止被别人恶意看到

**Comment by yu1chaofan** [comment]
好的.非常感谢!

**Comment by CorrectRoadH** [comment]
> 好的.非常感谢!

方便留个联系方式吗🤯 你刚刚留的信息提示账号密码错了。

**Comment by yu1chaofan** [comment]
qqqwe123 抱歉

**Comment by CorrectRoadH** [comment]
> qqqwe123

有没有这里的账号密码，我想连上终端用docker看看情况。
<img width="805" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/29306285/b67a6a42-1b01-4771-9a92-c79fb1316f7b">

**Comment by yu1chaofan** [comment]
admin yu12345

**Comment by CorrectRoadH** [comment]
> admin yu12345

🤯这台服务器是没有开ssh吗? 还是ssh改端口了

**Comment by yu1chaofan** [comment]
23451 ssh尝试一下这个端口  麻烦了

**Comment by CorrectRoadH** [comment]
> 23451 ssh尝试一下这个端口 麻烦了

目前判断是 `registry.hub.docker.com/onething1/wxedge` 导致 casaos 的崩溃。我想问一下，1. 是否愿意暂时通过删除 `registry.hub.docker.com/onething1/wxedge` 来恢复 casaos。2.是否愿意分享`registry.hub.docker.com/onething1/wxedge`给我们，让我们在下个版本修复这个问题。👀

**Comment by yu1chaofan** [comment]
可以没问题的  https://t.me/yuccff

**Comment by CorrectRoadH** [comment]
👌加你联系方式了

**Comment by CorrectRoadH** [comment]
fixed in  https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/133

**Comment by ddweier** [comment]
[https://github.com/IceWhaleTech/CasaOS/issues/1941](url)

**Comment by ddweier** [comment]
> 👌加你联系方式

https://github.com/IceWhaleTech/CasaOS/issues/1941

大神可以帮我看一下吗？
