### ISSUE TITLE
[Bug] Always read and write to the mounted storage during operation, preventing the hard disk from automatically hibernating

### ISSUE THREAD

**Issue by zicia** [IceWhaleTech/CasaOS#1356]
运行期间一直对挂载的储存进行读写 阻止硬盘自动休眠
raspberry pi 4b ubuntu20.04

**Comment by LinkLeong** [comment]
你是通过什么方式设置的休眠,能给个你设置休眠的命令吗?
How did you set up hibernation, can you give me the command you used to set up hibernation?

**Comment by zicia** [comment]
> 你是通过什么方式设置的休眠,能给个你设置休眠的命令吗?
> How did you set up hibernation, can you give me the command you used to set up hibernation?

硬盘盒，正常在没有读写的情况下就会自动休眠

**Comment by dmlt** [comment]
> > 你是通过什么方式设置的休眠,能给个你设置休眠的命令吗?
> > How did you set up hibernation, can you give me the command you used to set up hibernation?
> 
> 硬盘盒，正常在没有读写的情况下就会自动休眠

试下用hdparm，说不定会有效果。

**Comment by LinkLeong** [comment]
> > > 你是通过什么方式设置的休眠,能给个你设置休眠的命令吗?
> > > How did you set up hibernation, can you give me the command you used to set up hibernation?
> > 
> > 
> > 硬盘盒，正常在没有读写的情况下就会自动休眠
> 
> 试下用hdparm，说不定会有效果。

是的,我们测试的时候是使用hdparm,进行测试的,你方便的话可以试一下.然后你可以顺便说一下你的硬盘盒的型号.
Yes, we test with hdparm, you can try it if you want. Then you can tell us the model number of your hard disk enclosure.

**Comment by zicia** [comment]
hdparm -B 127 hdparm -S 60下可以休眠了
用的是不知名品牌硬盘盒 带自动待机功能
之前没有特意设置heparm是可以自动休眠的
