### ISSUE TITLE
一个为玩客云创建的项目

### ISSUE THREAD

**Issue by muzihuaner** [IceWhaleTech/CasaOS#136]
https://github.com/muzihuaner/Casaos_Onecloud

提供了一些玩客云可以使用的docker镜像还有其他东西

**Comment by LinkLeong** [comment]
感谢你的贡献

**Comment by JohnGuan** [comment]
感谢你的支持！也欢迎你和我们一起搞事情。但是这个理论上来说不是一个issue，我就先关掉这里了啦~
