### ISSUE TITLE
[Bug] smb  Chinese garbled characters are all question marks 中文乱码 

### ISSUE THREAD

**Issue by 5dprince** [IceWhaleTech/CasaOS#1363]
<img width="1283" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/8513521/e11ac6f9-3c18-42cc-8695-eee6e4f2def3">

Chinese garbled characters are all question marks

中文乱码 ，都是问号

**Comment by LinkLeong** [comment]
After our test, there is no Chinese display abnormal problem, can you give us the name of the two, so that we can further test!
经过我们测试,并未出现中文显示异常问题,你能把名称给我们两个吗,方便我们进一步测试?

**Comment by 5dprince** [comment]
????2
smb://10.0.0.10/downloads/NewMovie/2023Movie/网络谜踪2

<img width="652" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/8513521/ec248998-d09b-4c5b-92e6-4c6ed2aa8fe3">

**Comment by LinkLeong** [comment]
![img_v2_d9bd2757-415b-4f83-a900-80604d5ceafg](https://github.com/IceWhaleTech/CasaOS/assets/13556972/ddb2872c-22d5-4636-abd7-ab9abe37cb71)
建议你换个机器或用手机试试
Suggest you try a different machine or use your cell phone

**Comment by 5dprince** [comment]
> 

OMV最新系统 
尝试加过  charset 无效

**Comment by jerrykuku** [comment]
你安装CasaOS的底层系统是什么？能否输出下 cat /etc/default/locale  这个的信息？ 同时也输出下 OMV的这个信息。

**Comment by 5dprince** [comment]
> 你安装CasaOS的底层系统是什么？能否输出下 cat /etc/default/locale 这个的信息？ 同时也输出下 OMV的这个信息。

LANG="zh_CN.UTF-8"
LANGUAGE="zh_CN:zh"

 尝试了下pve 虚拟的debian12 完全正常， 乱码的是 armbian ，感觉应该从arm查一下

**Comment by LinkLeong** [comment]
This has more to do with the underlying system and cannot be fully adapted at this time
这个和底层系统的关系较大，目前无法完全适配

**Comment by weiyideai520** [comment]
我的也是乱码

<img src="https://img1.imgtp.com/2023/09/30/I6DJwH5Q.png" alt="Screenshot 2023-09-30 073036.png" title="Screenshot 2023-09-30 073036.png" />

**Comment by LinkLeong** [comment]
> 我的也是乱码
> 
> ![Screenshot 2023-09-30 073036.png](https://camo.githubusercontent.com/599f121994d8c2f4996b946217e5266e098edfdedb41380075406540cc66ddcd/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30392f33302f4936444a774835512e706e67)
你可以按照上述的评论进行一下检查.
You could do a bit of checking as per the above comments .

**Comment by math-RJ** [comment]
armbian安装中文环境，用下面这个脚本；
bash <(wget -qO- https://play.cuse.eu.org/casaos_newbie.sh)
为保险起见，运行下列代码，更改为中文。
locale  # 查看当前区域设置
sudo locale-gen zh_CN.UTF-8  # 生成新的区域设置
sudo update-locale LANG=zh_CN.UTF-8  # 设置语言环境
在运行一下locale，如果是zh_CN.UTF-8，修改smb.conf配置文件
display charset = utf8
unix charset = utf8
dos charset = utf8
~~~~~~~~~~~
如果你是其他方式安装的中文，locale是zh_CN.GBK或zh_CN.gb2312
修改配置为：
display charset = cp936
unix charset = cp936
dos charset = cp936
