### ISSUE TITLE
[Bug]  Failed to connect to get.casaos.io port 443: Connection timed out

### ISSUE THREAD

**Issue by ll931217** [IceWhaleTech/CasaOS#1365]
**Describe the bug**

Running the install script `curl -fsSL https://get.casaos.io | sudo bash` ends up failing at `[ INFO ] Install the necessary dependencies: Rclone`. The error shown is:

> curl: (28) Failed to connect to get.casaos.io port 443: Connection timed out

**To Reproduce**

> Steps to reproduce the behavior:

1. Run `curl -fsSL https://get.casaos.io | sudo bash` or `wget -qO- https://get.casaos.io | sudo bash` on a freshly installed raspbian os

**Expected behavior**

It should finish installing successfully

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/12750413/6b2cfb16-3045-4d96-b0d6-c8f4e6691183)

This was the output of `sudo casaos-uninstall`:
![image](https://github.com/IceWhaleTech/CasaOS/assets/12750413/f02c2ab1-9179-49d3-adb6-dfadc0b99eb7)

**Desktop (please complete the following information):**

```
 - OS: Raspbian OS Lite 64-bit
 - Browser: None
 - Version [e.g. 22]
```

**System Time**

> Run `timedatectl` and share the output

```
               Local time: Thu 2023-08-31 10:28:06 CST
           Universal time: Thu 2023-08-31 02:28:06 UTC
                 RTC time: n/a
                Time zone: Asia/Taipei (CST, +0800)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> This was run on a newly installed Raspberry Pi

**Comment by ll931217** [comment]
I did some more testing and this line seems to be the issue in the install script:

```bash
#check installed version of rclone to determine if update is necessary
version=$(rclone --version 2>>errors | head -n 1)
if [ -z "$install_beta" ]; then
    current_version=$(curl -fsS https://get.casaos.io/version.txt) # THIS LINE IS BROKEN
else
    current_version=$(curl -fsS https://beta.rclone.org/version.txt)
fi
```

**Comment by ll931217** [comment]
So I installed `rclone` manually from `https://get.casaos.io/rclone-current-linux-arm64.zip`, and followed the `install.sh` script. Then I removed the function call for `Install_Rclone` and the installation was successful.

**Comment by jerrykuku** [comment]
Thanks for the feedback, I'll fix this as soon as I can. At that time I hope you can help test it.

**Comment by ll931217** [comment]
Sure! Let me know when

**Comment by jerrykuku** [comment]
Hello, I have created a  link for test installation, can you help me to test it? 
Here's the script: `curl -fsSL https://get.casaos.io/v0.4.4-2-test | bash`

**Comment by jerrykuku** [comment]
This Issue hasn't been updated for over 14 days, I will close it. if you still have problems you can reopen it or create a new Issue.

**Comment by mdrijwan** [comment]
i'm having the same issue on my raspberry pi 5
<img width="775" alt="Screenshot 2024-01-18 at 3 54 29 PM" src="https://github.com/IceWhaleTech/CasaOS/assets/22044931/ce657a48-8b62-4503-a684-bd4c0a439667">
output of `timedatectl`
```
Local time: Thu 2024-01-18 15:49:17 +08
           Universal time: Thu 2024-01-18 07:49:17 UTC
                 RTC time: Thu 2024-01-18 07:49:17
                Time zone: Asia/Kuala_Lumpur (+08, +0800)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```
**pi@rrpi:~ $ curl -fsSL https://get.casaos.io/v0.4.4-3-rpi5 | sudo bash
curl: (28) Failed to connect to get.casaos.io port 443 after 129862 ms: Couldn't connect to server**

**Comment by deers** [comment]
is there any solution for this? I have the same error on my zimaboard.
