### ISSUE TITLE
[Bug] 无法删除Legacy Docker Image 安装图标

### ISSUE THREAD

**Issue by baffee** [IceWhaleTech/CasaOS#1367]
在之前的版本，试图手动安装一个Docker的image，结果安装的图标一直无法删除。谢谢
 

- OS: linux
 - CasaOS Version: 0.4.4.1
 - Disk Total: 7042 
 - Disk Used: 2616 
 - System Info: [Armbian 22.11.0-trunk Bullseye \l Bit:32 Mem:990M Core:4 Linux onecloud 6.1.11-meson #23.02.2 SMP Fri Feb 17 22:35:23 UTC 2023 armv7l GNU/Linux]
 - Remote Version: 0.4.4.1
 - Browser: Chrome 
 - Version: 116.0.0.0

**Comment by raller1028** [comment]
你好,请问你遇到的是如下图所示的情况吗?
如果是的话,你可以先点击"import to CasaOS", 然后应用就会变成能删除的状态了
Hi, are you experiencing the situation shown below?
If so, you can click on "import to CasaOS", then the app will be able to be deleted.
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/aaa52c2a-179b-45be-9fbe-c577438de2cb)
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/247f90a6-116b-49c1-962d-1291bc14494f)

**Comment by baffee** [comment]
不太一样，Mouse Hove Over后，点安装没有反应，也没有右上角的三个点。有啥建议吗？
<img width="212" alt="Untitled" src="https://github.com/IceWhaleTech/CasaOS/assets/117062634/c6f1529b-35ac-43ba-aeff-ab982c5efec9">

**Comment by raller1028** [comment]
@baffee 方便把你自定义导入的文件提供给我们试试吗

**Comment by baffee** [comment]
@raller1028 可以的，这个怎么操作？命令行也行

**Comment by raller1028** [comment]
@baffee 方便先加微信reelfy2570 然后远程吗

**Comment by baffee** [comment]
@raller1028 加了，等你通过

**Comment by baffee** [comment]
fixed with great support by Raller1028.

**Comment by eric09230** [comment]
@baffee 請問是如何刪除的呢？我也遇到類似的問題
嘗試手動安裝後失敗 圖標也無法刪除
