### ISSUE TITLE
[Bug] main.go:47:13: pattern api/casaos/openapi.yaml: no matching files found

### ISSUE THREAD

**Issue by tomasalias** [IceWhaleTech/CasaOS#1369]
**Describe the bug**

> A clear and concise description of what the bug is.

2023-09-02 14:58:06: main.go:47:13: pattern api/casaos/openapi.yaml: no matching files found
2023-09-02 14:58:06: [CYCLIC] Build Failed

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to 'Cyclic'
2. Click on 'Build'
3. See error

**Expected behavior**

> A clear and concise description of what you expected to happen.

I expected that build would be successful.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

![Snímek obrazovky 2023-09-02 151113](https://github.com/IceWhaleTech/CasaOS/assets/80042910/97097e87-a2bd-4771-8894-a56186a14bc3)

**Desktop (please complete the following information):**

```
 - OS: Windows
 - Browser: chrome
 - Version 22H2
```

**Comment by LinkLeong** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/530305f9-9961-4277-96f8-c0cef353a6ca)
We are using golang 1.20, but I don't see 1.20 on cyclic.

**Comment by tigerinus** [comment]
@tomasalias - despite that we don't use serverless platform like Cyclic to build CasaOS, CasaOS is a composite of modules from various Git repos (vs monorepro). The `IceWhaleTech/CasaOS` repo is merely one out of the modules for CasaOS. You might want to check if Cyclic supports such projects like CasaOS.
