### ISSUE TITLE
如何更换背景图片？

### ISSUE THREAD

**Issue by muzihuaner** [IceWhaleTech/CasaOS#137]
找不到路径

**Comment by jerrykuku** [comment]
在UI目录中，目前背景图是预置的，暂无方法替换。

**Comment by muzihuaner** [comment]
> 在UI目录中，目前背景图是预置的，暂无方法替换。

那好吧，那麻烦后期出个替换背景的功能，谢谢~

**Comment by jerrykuku** [comment]
This feature is already under development and will be available soon in v0.3.3

**Comment by LinkLeong** [comment]
Thank you for your feedback, we have solved the problem in v0.3.3, I will close the problem, if you have questions, please open a new issue
