### ISSUE TITLE
[Bug] Installation on Ubuntu Desktop 22.04.03 LTS fails

### ISSUE THREAD

**Issue by urbanofreitas** [IceWhaleTech/CasaOS#1381]
**Describe the bug**
I'm trying to install the CasaOS on Ubuntu 22.04.03LTS instance I have in Intel NUC like PC.

I tried to do the install using the CasaOS provided installation script, invoked by running:
` curl -fsSL https://get.casaos.io | sudo bash`

And it fails (Relevant Installation outputs before the error).
[ INFO ] Install the necessary dependencies: Rclone
[NOTICE] Will change rclone from rclone v1.53.3-DEV to rclone v1.61.1.
curl: (23) Failure writing output to destination
[FAILED] Installation failed, please try again.
> A clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

1. Open Bash terminal
2. Run the command ` curl -fsSL https://get.casaos.io | sudo bash`
3. Give the above shared error.

**Expected behavior**
> Having a statement saying CasaOS was installed and it's available in a specific endpoint.

**Screenshots**

**Desktop (please complete the following information):**
```
 - OS: Ubuntu 22.04.03LTS
 - Browser: Not relevant
 - Version: Not relevant
```

**System Time**

> Run `timedatectl` and share the output

```
 Local time: ter 2023-09-05 15:02:07 WEST
Universal time: ter 2023-09-05 14:02:07 UTC
RTC time: ter 2023-09-05 14:02:07
Time zone: Europe/Lisbon (WEST, +0100)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:
Since the installation failed, I didn't collect any of the below indicated logs. I assuming they are not available.
```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**
I tried install the dependency I understood from the CasaOS installation script outputs, by myself, using:
- sudo apt install rclone

Although the installation went well. The CasaOS installation script did not recognized it and still gave the above shared error.

**Comment by jerrykuku** [comment]
It looks like there's a problem installing the specified version of Rclone, which is exactly what we're dealing with, can you install it using the following install script? `curl -fsSL https://get.casaos.io/v0.4.4-2-test | sudo bash `This will help us better pinpoint the problem.

**Comment by SergioVeraLeon** [comment]
Thank you, it solved the problem
Running ubuntu server 22.04 64 bits on raspberry pi 4

**Comment by urbanofreitas** [comment]
I just tried `curl -fsSL https://get.casaos.io/v0.4.4-2-test | sudo bash` and it gave the same error:
```
[ INFO ] Install the necessary dependencies: Rclone
curl: (23) Failure writing output to destination
[FAILED] Installation failed, please try again.
```

Something relevant it might be evident(1) is I'm trying to install CasaOS on Ubuntu 22.04.03LTS Desktop version.

**Comment by jerrykuku** [comment]
I think it's a networking issue.
If your device is an x86 device, you can do the installation of rclone manually, you can follow the code below:
```
curl -O https://downloads.rclone.org/v1.61.1/rclone-v1.61.1-linux-amd64.zip
unzip rclone-v1.61.1-linux-amd64.zip
cd rclone-*-linux-amd64
sudo cp rclone /usr/bin/
sudo chown root:root /usr/bin/rclone
sudo chmod 755 /usr/bin/rclone
```

**Comment by jerrykuku** [comment]
This Issue hasn't been updated for over 14 days, I will close it. if you still have problems you can reopen it or create a new Issue.
