### ISSUE TITLE
一个docker安装两次的需求

### ISSUE THREAD

**Issue by 4277427** [IceWhaleTech/CasaOS#1388]
我想安装两个qBittorrent，分别下载不同的内容，但在应用中心的会把已经安装的docker安装按钮变成打开按钮，无法二次安装。
所以我就把现有的qBittorrent的yaml文件导出来，再用自定义安装的方式导入，但我尝试了修改标题，容器名称，镜像版本，最终结果都是现有qBittorrent被替换。

**Comment by tigerinus** [comment]
@4277427 你可以把导出的自定义 Compose YAML 文件分享一下么？

Can you please share the exported custom Compose YAML file?

**Comment by mtyzaq** [comment]
修改name， store_app_id 安装

**Comment by 4277427** [comment]
> @4277427 你可以把导出的自定义 Compose YAML 文件分享一下么？
> 
> Can you please share the exported custom Compose YAML file?

 @tigerinus 谢谢，按照 @mtyzaq 的方法已经解决了，谢谢二位
