### ISSUE TITLE
How to add an existing docker image

### ISSUE THREAD

**Issue by lcl-101** [IceWhaleTech/CasaOS#139]
**Is your feature request related to a problem? Please describe.**
I want to add the existing docker image
so，How to add an existing docker image
![image](https://user-images.githubusercontent.com/13747322/160342702-18743355-ef3e-44b6-80b8-6ebca1313677.png)

**Comment by LinkLeong** [comment]
We are considering the functionality of existing application imports

**Comment by tigerinus** [comment]
This feature has been implemented.
