### ISSUE TITLE
SSH blank terminal

### ISSUE THREAD

**Issue by Anti-Apple4life** [IceWhaleTech/CasaOS#1390]
**Describe the bug**

Whenever I try to use SSH through CasaOS, I seem to be logged in successfully, but a blank terminal is shown.

**To Reproduce**

Use SSH with a valid login

**Expected behavior**

I expected the web terminal to show the prompt and allow me to enter commands

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/59315931/7422131b-6108-4748-876d-584e0545050d)

**Desktop (please complete the following information):**

```
 - OS: Arch Linux
 - Server OS: Debian 12
 - Browser: Firefox
 - CasaOS Version: v0.4.4.2
```

**System Time**
```
               Local time: Fri 2023-09-08 16:18:04 EDT
           Universal time: Fri 2023-09-08 20:18:04 UTC
                 RTC time: Fri 2023-09-08 20:18:04
                Time zone: America/New_York (EDT, -0400)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Logs**

https://pastebin.com/h8NM3c6Q

**Comment by tigerinus** [comment]
This is supposed to be fixed in v0.4.4-2.

Can you run `casaos-app-management` directly from terminal and share the Git commit hash?

**Comment by raller1028** [comment]
@Anti-Apple4life Can other command line tools ssh to this device?

**Comment by Anti-Apple4life** [comment]
Yes, other tools are able to SSH into this device.

Git commit hash: cda78104f41269823a29f5a0ccf962d23269a1a5

**Comment by LinkLeong** [comment]
Can you check the error message with the developer tools?

**Comment by LinkLeong** [comment]
We will close the issue and reopen it if you have any questions.

**Comment by eidech** [comment]
Can confirm this issue still exists in 0.4.4.3.  It would be nice to have the option to access the terminal over HTTPS through the web interface rather than opening another port to SSH directly when abroad.  This also allows the option of accessing the terminal when on a device that does not have an SSH client installed.

**Comment by Foxtrot-Whiskey** [comment]
Can confirm issue still exists in 0.4.7
Anybody come across any solutions yet?

**Comment by DashCat1243** [comment]
The issue still exists in 0.4.8
Has anybody found a solution yet?

**Comment by smithbill17** [comment]
This issue is STILL present in v0.4.15

**Comment by ehjr5u** [comment]
EVEN STILL exists

**Comment by afandiazmi** [comment]
> > For me, using chrome to access have cause this. Try to use Brave browser, it fixed for me,
> 
> It sometimes STILL gets a blank terminal even with the Brave Browser. It's not as common, but it still exists

Since i install like 9 month ago until now, only work with brave, doesn't work with Chrome

**Comment by crimsonkarma** [comment]
0.4.15 issue still exists. it used to work before on an old server but not on this new one I just made. not sure why browser matters but I use firefox and it worked for me on my old server

**Comment by afandiazmi** [comment]
i suspected maybe extension is cause of the problem
