### ISSUE TITLE
[Bug] Cannot SSH into a server that has only key-based authentication configured.

### ISSUE THREAD

**Issue by w1nsid** [IceWhaleTech/CasaOS#1393]
**Describe the bug**

SSH doesnt work when key based authentication is configured and password authentication disabled.

**To Reproduce**

1. Set sshd config to only accept key based authentication.
2. Access terminal through CasaOs dashboard.

**Logs**

10T20:26:19.274+0100	error	connect ssh error	{"error": "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain", "func": "v1.PostSshLogin", "file": "/home/runner/work/CasaOS/CasaOS/route/v1/ssh.go", "line": 42}

**Comment by jerrykuku** [comment]
The CasaOS web terminal currently only supports username and password login, not key-based login.

**Comment by jerrykuku** [comment]
This issue has not been updated for two weeks, I will close it, if there are still questions you can reopen it.
