### ISSUE TITLE
No Temp/Watt reading in WebUI [Bug] 

### ISSUE THREAD

**Issue by MichNLGithub** [IceWhaleTech/CasaOS#1399]
Hi Team/all,

I use the SuperMicro A1SAM-2750F Mobo with an Intel® Atom processor C2750, SoC ( FCBGA 1283, 20W 8-Core) onboard.

I don't get Temperature and Watt reading in the WebUi.

CasaOS is installed on Debian 12.

**Comment by raller1028** [comment]
https://github.com/IceWhaleTech/CasaOS/issues/1208
@MichNLGithub I hope this helps.

**Comment by MichNLGithub** [comment]
> #1208 @MichNLGithub I hope this helps.

Thanks for sharing, seems that my hardware is not supported yet.
Strange because it's an Microserver, a world wide leader in hardware for servers.

Hope this Bug/fix could be made.
