### ISSUE TITLE
app disappear

### ISSUE THREAD

**Issue by ziotidus** [IceWhaleTech/CasaOS#140]
**Describe the bug**

Hi, 
My app, qbittorrent and plex are disappear bye the menu, but if i use portainer i see that are all two perfect and if i open it they functionally in all..

I attend your reply
Thanks

My mail is: ziotidus@gmail.com

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.10
	 - Disk Total: 59779 
	 - Disk Used: 14183 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:3795M Core:4 Linux rpi-srv 5.10.103-v8+ #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 99.0.4844.82

**Comment by LinkLeong** [comment]
I have written back

**Comment by LinkLeong** [comment]
I will close this issue if you have any questions  you can reopen issues
