### ISSUE TITLE
[Bug]  Failing to download files when installing

### ISSUE THREAD

**Issue by norbee007** [IceWhaleTech/CasaOS#1404]
Hi!

I have trouble installing CasaOs. I am on a fresh install of Raspi OS. I get an error downloading a certain file. I am a noob, but I only followed the instructions of the offical page. I got a link for the log: http://sprunge.us/EskKCc. I tried WIFI, wired connection, and even mobile internet, but the same. Even the installer have trouble starting:
pi@raspberrypi:~ $ curl -fsSL https://get.casaos.io | sudo bash
curl: (7) Failed to connect to get.casaos.io port 443: No gateway to host

The terminal says this:

   _____                 ____   _____ 
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___  
 | |    / _` / __|/ _` | |  | |\___ \ 
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/ 
                                      
   --- Made by IceWhale with YOU ---

[  OK  ] Your hardware architecture is : aarch64
[  OK  ] Your System is : Linux
[  OK  ] Your Linux Distribution is : raspbian 
[  OK  ] Memory capacity check passed.
[  OK  ] Disk capacity check passed.
Találat:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Találat:2 http://archive.raspberrypi.org/debian bullseye InRelease                                 
Találat:3 https://download.docker.com/linux/raspbian bullseye InRelease                            
Reading packages... Finished        
[  OK  ] Current Docker verison is 24.0.6.
[ INFO ] Configuration CasaOS Addons
/tmp/casaos-installer/tmp.k3IeudreJ5 /home/pi
[ INFO ] Downloading https://github.com/IceWhaleTech/CasaOS-Gateway/releases/download/v0.4.4-1/linux-arm64-casaos-gateway-v0.4.4-1.tar.gz...
[FAILED] Failed to download package
pi@raspberrypi:~ $ journalctl -xeu casaos-app-management --no-pager | curl -F 'sprunge=<-' http://sprunge.us
http://sprunge.us/EskKCc
pi@raspberrypi:~ $ 

What can be the problem?
Best Regards!

**Comment by dragonfire1119** [comment]
I would say you need to update your /etc/resolv.conf file and add a different nameserver in like:

```
nameserver 1.1.1.1
```

. You can find the script I built here https://github.com/bigbeartechworld/big-bear-scripts/tree/master/update-etc-resolve, but since you can't resolve URLs, you can copy the contents of run.sh into the server and then run it: 
```
bash run.sh
```


You can also manually change /etc/resolv.conf with vim or nano.

**Comment by LinkLeong** [comment]
@nor
Have you solved your problem?

**Comment by norbee007** [comment]
Even after playing with the DNS servers, it failed to download. I am going to try with another distro on SSD, maybe this helps.

**Comment by LinkLeong** [comment]
Thank you for your feedback, I will close the issue and reopen it if in doubt.
