### ISSUE TITLE
[Bug] remaining files after deleted on shared folder on a remote desktop 

### ISSUE THREAD

**Issue by MikeSato** [IceWhaleTech/CasaOS#1413]
**Describe the bug**

I shared a folder (Desenhos) on an external drive on CasaOS with my Mac, and Im using it for PLEX.
I paste a mkv file on the shared folder from the Mac to do a test.
After I successfully reproduced the movie in PLEX, I deleted the mkv file from my Mac, and consequently the file was deleted on the shared folder on the external drive on CasaOS.
But 2 files remained on the folder .DS_Store and ._.DS_Store.
I did delete these 2 files after, and reproduced the steps again and the files showed up again.

**To Reproduce**

1. Share a Folder on a external drive
2. Share a file on this folder
3. Delete the file from a Remote Desktop
4. Two files will remain on the shared folder on the esternal drive (.DS_Store and ._.DS_Store.)

**See error
See error
Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

 - OS: MacOS Ventura version 13.5.2
 - Mac Mini
 - Browser: Safari Version 16.6 (18615.3.12.11.2)
 - CasaOS v0.4.4.2

```

**System Time**

> Run `timedatectl` and share the output


```
(timedatectl
               Local time: Sun 2023-09-24 16:22:05 UTC
           Universal time: Sun 2023-09-24 16:22:05 UTC
                 RTC time: Sun 2023-09-24 16:22:05
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```
          
**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by LinkLeong** [comment]
.DS_Store and . DS_Store are automatically created by the mac computer, these two files are hidden on the mac computer, as long as you connect the device to the mac will create such a file, you can delete it after disconnecting from the mac.
