### ISSUE TITLE
Incomplete display of close and download buttons

### ISSUE THREAD

**Issue by qiuhaixincn** [IceWhaleTech/CasaOS#1416]
When playing a video on a mobile phone, when the file name is too long, the close and download buttons will be pushed to many positions on the right. It is recommended to reduce the file name to ensure that the close and download buttons can be displayed during playback.

**Comment by jerrykuku** [comment]
Sure, we will fix this issue in the next update.

**Comment by jerrykuku** [comment]
v0.4.5 has been updated with this issue.
