### ISSUE TITLE
[Bug] 看不到硬盘信息

### ISSUE THREAD

**Issue by weiyideai520** [IceWhaleTech/CasaOS#1423]
### What happened?

可以自动挂载分区，但是看不到硬盘信息

----system info----
 - OS: linux
 - CasaOS Version: 0.4.4.2
 - Disk Total: 6996 
 - Disk Used: 2227 
 - System Info: [Armbian 23.8.1 lunar \l Bit:64 Mem:975M Core:4 Linux armbian 6.1.54-ophub #1 SMP Wed Sep 20 10:05:02 EDT 2023 aarch64 aarch64 aarch64 GNU/Linux]
 - Remote Version: 0.4.4.2
 - Browser: Edge 
 - Version: 117.0.2045.43

### Screenshots

<img src="https://img1.imgtp.com/2023/09/30/kgmjSuZB.png" alt="Screenshot 2023-09-30 071712.png" title="Screenshot 2023-09-30 071712.png" />
<img src="https://img1.imgtp.com/2023/09/30/OyZ0TSpn.png" alt="Screenshot 2023-09-30 071718.png" title="Screenshot 2023-09-30 071718.png" />
<img src="https://img1.imgtp.com/2023/09/30/UnGEMsN1.png" alt="Screenshot 2023-09-30 071746.png" title="Screenshot 2023-09-30 071746.png" />

**Comment by LinkLeong** [comment]
我需要`lsblk -O -j`的信息
I need information on `lsblk-O-j`.

**Comment by LinkLeong** [comment]
Did you try refreshing the page?

**Comment by LinkLeong** [comment]
我们会关闭该问题,如有疑问可重新打开.
We will close the issue and reopen it if you have any questions.
