### ISSUE TITLE
[Bug] On installation of CasaOS 0.4.4.2 on Debian 12

### ISSUE THREAD

**Issue by Byte-Minds** [IceWhaleTech/CasaOS#1428]
Volevo segnalare un bug nell'installazione di CasaOS v0.4.4.2 in Debian 12. Alla fine dell'installazione di CasaOS non fornisce l'url di CasaOS per accederci da browser. 
Allego log di installazione.
[Made by IceWhale with.txt](https://github.com/IceWhaleTech/CasaOS/files/12775343/Made.by.IceWhale.with.txt)

**Comment by jerrykuku** [comment]
There is the same question in this issue, can you follow the exchange above to confirm the exact issue? #1400
