### ISSUE TITLE
[Bug] Installation script for CasaOS v0.4.4-2 do not work on raspberry...

### ISSUE THREAD

**Issue by carnock** [IceWhaleTech/CasaOS#1429]
[ INFO ] Downloading https://github.com/IceWhaleTech/CasaOS/releases/download/v0.4.4-alpha7/linux-arm64-casaos-v0.4.4-alpha7.tar.gz...
****[FAILED]** Failed to download package**
pi@raspberrypi4:~ $

**Screenshots**
![image](https://github.com/IceWhaleTech/CasaOS/assets/146243818/e6024084-d85a-4f30-b9b8-419e12b34150)

**Comment by jerrykuku** [comment]
It could be a network problem. You can retry, I have tested the package to download properly.

**Comment by jerrykuku** [comment]
This Issue hasn't been updated for over 14 days, I will close it. if you still have problems you can reopen it or create a new Issue.

**Comment by wilz7** [comment]
i got the same issue
