### ISSUE TITLE
[Bug] 关于AMD Ryzen  CPU的温度检测0.4.4-3还是无法显示

### ISSUE THREAD

**Issue by dmlt** [IceWhaleTech/CasaOS#1430]
![WX20231001-165809@2x](https://github.com/IceWhaleTech/CasaOS/assets/26223986/e146fc21-0326-4548-a014-95fa951b8192)
![WX20231001-170404@2x](https://github.com/IceWhaleTech/CasaOS/assets/26223986/d0ad1cc2-f5e6-4f43-ac65-1101381c9db8)
nvme （nvme温度）
k10temp（amd内核温度）
iwlwifi_1（wifi温度）
amdgpu（amdgpu温度）

如图所示，命令下查看传感器温度文件是可以获取的，面板上无法显示

**Comment by CarlBrianCoombes** [comment]
ok

**Comment by LinkLeong** [comment]
问题问题可以看一下这个issue,[#1208](https://github.com/IceWhaleTech/CasaOS/issues/1208),然后关于tctl相关解释你可以搜索一下.这里给一个帖子https://forums.gentoo.org/viewtopic-t-1098716-start-0.html.简单来说,我们拿的是cpu的真实温度,不是传感器或其他方式的偏移温度.
For questions you can read this issue,https://github.com/IceWhaleTech/CasaOS/issues/1208, and then you can search for tctl related explanations. Here's a post for you https://forums.gentoo.org/viewtopic-t-1098716-start-0.html. Simply put, we're taking the real temperature of the cpu, not the temperature offset by sensors or other means.

**Comment by dmlt** [comment]
> 问题问题可以看一下这个issue,[#1208](https://github.com/IceWhaleTech/CasaOS/issues/1208),然后关于tctl相关解释你可以搜索一下.这里给一个帖子https://forums.gentoo.org/viewtopic-t-1098716-start-0.html 简单来说,我们拿的是cpu的真实温度,不是传感器或其他方式的偏移温度. For questions you can read this issue,#1208, and then you can search for tctl related explanations. Here's a post for you https://forums.gentoo.org/viewtopic-t-1098716-start-0.html. Simply put, we're taking the real temperature of the cpu, not the temperature offset by sensors or other means.

好的了解了。
