### ISSUE TITLE
CasaOS version for MIPS hardware

### ISSUE THREAD

**Issue by wasantosfi** [IceWhaleTech/CasaOS#1439]
**Is your feature request related to a problem? Please describe.**
Unsupported or unknown architecture: mips

**Describe the solution you'd like**
Compact version of CasaOS for MIPS in OpenWRT.

**Additional context**
Linux version 5.10.176 (builder@buildhost) (mipsel-openwrt-linux-musl-gcc (OpenWrt GCC 11.2.0 r20134-5f15225c1e) 11.2.0, GNU ld (GNU Binutils) 2.37)

system type                   : MediaTek MT7688 ver:1 eco:2
machine                         : Onion Omega2+
processor                       : 0
cpu model                      : MIPS 24KEc V5.5
BogoMIPS                      : 385.84
wait instruction             : yes
microsecond timers     : yes
tlb_entries                      : 32
extra interrupt vector  : yes
hardware watchpoint  : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                                    : mips1 mips2 mips32r1 mips32r2
ASEs implemented       : mips16 dsp

MemTotal:           122356 kB
MemFree:            94912 kB
MemAvailable:    76672 kB
Buffers:                52 kB
Cached:               10700 kB

**Comment by jerrykuku** [comment]
Sorry we have no plans for MIPS architecture support. Also currently CasaOS cannot be deployed on OpenWrt.

**Comment by jerrykuku** [comment]
This Issue hasn't been updated for over 14 days, I will close it. if you still have problems you can reopen it or create a new Issue.
