### ISSUE TITLE
App store

### ISSUE THREAD

**Issue by Wzxcvb** [IceWhaleTech/CasaOS#144]
**Describe the bug**

App store doesn't open

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.10
	 - Disk Total: 29358 
	 - Disk Used: 9531 
	 - Sync State: Sync img: false
	Sync Key length: 0
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:3838M Core:4 Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux]
	 - Browser: Chrome 
	 - Version: 100.0.4896.60

**Comment by LinkLeong** [comment]
We are aware of the seriousness of this problem and we are working sincerely to solve it, and the results will be available soon.

**Comment by LinkLeong** [comment]
We have solved the problem in the latest version, please upgrade to experience!
