### ISSUE TITLE
[Bug] Exported AppFile cannot be imported on arm64 Casa

### ISSUE THREAD

**Issue by mcx808** [IceWhaleTech/CasaOS#1441]
**Describe the bug**

I wish to migrate my CasaOS from an x86-64 VM to an arm64 Debian 12 VM. However there is no option to import an appfile on the ARM cersion of CasaOS 0.4.4.2, only docker-compose or docker-cli. 

**To Reproduce**

> Steps to reproduce the behavior:

1. Click 'Install Customized app'
2. Click Import

**Expected behavior**

> AppFile tab should be available

> If applicable, add screenshots to help explain your problem.

<img width="707" alt="Screenshot 2023-10-08 at 17 38 28" src="https://github.com/IceWhaleTech/CasaOS/assets/30801293/87fd3c7d-069f-4d2b-8e1f-54e8e654bab5">
**Desktop (please complete the following information):**

```
 - OS: 0.4.4.2
 - Browser Edge 117
 - Version [e.g. 22]
```

**System Time**

> Run `timedatectl` and share the output

```
               Local time: Sun 2023-10-08 17:45:24 BST
           Universal time: Sun 2023-10-08 16:45:24 UTC
                 RTC time: Sun 2023-10-08 16:45:25
                Time zone: Europe/London (BST, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by LinkLeong** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/eb9cf0c4-cd7a-4a20-adc3-a939cd410178)
You can drag the file here or click upload, either way.

**Comment by mcx808** [comment]
@LinkLeong not with an AppFile (.json) that was exported from another Casa x86 instance I can't.

Drag and drop does nothing, and the file chooser greys out the .json file.

**Comment by raller1028** [comment]
@mcx808 What version of your old casaos (x86_64)

**Comment by mcx808** [comment]
@raller1028  0.4.3

**Comment by raller1028** [comment]
@leesonaa This parameter represents the supported architecture of this application. Simply changing it directly won't work. If you want to install this application for a different architecture, you can refer to this article.https://github.com/IceWhaleTech/CasaOS/issues/1251

@mcx808 You need to export the docker-compose.yml from the x86 casaos first, and then import it into the arm64 casaos

**Comment by mcx808** [comment]
@raller1028 - Well yes that's a workaround I already undertook. I'm reporting a bug that the option to import an appfile is missing from the UI completely on the Arm version. 
Unless this is desired behaviour, but it doesn't make much sense since the only export option on the x64 version is for an AppFile.

**Comment by raller1028** [comment]
It's not just the ARM version missing JSON import, but after the CasaOS App Store upgrade, it only supports the docker-compose.yml format. However, it is true that support for ARM architecture is lacking in some applications in the App Store. Thank you for your feedback. If there are no other issues, I will close this issue

**Comment by mcx808** [comment]
Ah ok - so expected behaviour - I was just in between versions when changing to the compose.yml format.
