### ISSUE TITLE
[Bug] 安装syncthing应用报错no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by xhdou** [IceWhaleTech/CasaOS#1445]
![image](https://github.com/IceWhaleTech/CasaOS/assets/99006410/f9fb771b-6a2f-49d6-8c0f-4004a162367b)
我在安装syncthing应用的时候会报错，我查询了镜像的版本，是1.23.5
![image](https://github.com/IceWhaleTech/CasaOS/assets/99006410/fe066855-1d9f-44f6-b48c-8dda82cb4d71)
我去dockerhub上查询了该版本，是支持armv7的：
https://hub.docker.com/layers/syncthing/syncthing/1.23.5/images/sha256-c0ab9ad0f10ccd71185e8d3cc0c74a3d56276050ce289c3f3baeed9ec95e4505?context=explore
所以为什么我安装不了呢

**Comment by xhdou** [comment]
> 1.首先你给的地址是syncthing官方库的。商店的compose是linuxserver库的。 2.要么手搓docker pull 官方库 要么修改compose.yml的tag https://registry.hub.docker.com/r/linuxserver/syncthing/tags?page=3

我修改了compose.yml的tag并自定义安装了，是可以安装，但不能使用，图标显示的是灰色
![image](https://github.com/IceWhaleTech/CasaOS/assets/99006410/4031952b-1be9-4dd2-8297-a12a2dba533d)

**Comment by raller1028** [comment]
可以参考https://github.com/IceWhaleTech/CasaOS/issues/1251

**Comment by raller1028** [comment]
我这边测试过ok的
[2023-10-13 11-53-42.zip](https://github.com/IceWhaleTech/CasaOS/files/12889298/2023-10-13.11-53-42.zip)

**Comment by dragonfire1119** [comment]
@xhdou You need to have 64 bit OS.

**Comment by dragonfire1119** [comment]
@xhdou Normally this error is from not having a 64 bit OS.

**Comment by xhdou** [comment]
> @xhdou Normally this error is from not having a 64 bit OS.
好像确实是因为系统不是64位的原因，官方以后会提供32位的么，还是我必须得整个64位的啊

**Comment by dragonfire1119** [comment]
> 好像确实是因为系统不是64位的原因，官方以后会提供32位的么，还是我必须得整个64位的啊

据我所知，你需要一个完整的 64 位操作系统来运行 CasaOS 和 Docker。

**Comment by xhdou** [comment]
总结，得要64位操纵系统，各位得要注意下自己的硬件能不能装64位的

**Comment by dragonfire1119** [comment]
Here's how you can do it:

Open a terminal.

```
grep -wo 'lm' /proc/cpuinfo | uniq
```

If the command returns lm, then your CPU supports Long Mode, which means it supports 64-bit.

---

您可以这样做：

打开终端。

```
grep -wo 'lm' /proc/cpuinfo | uniq
```

如果命令返回 lm，那么您的 CPU 支持长模式，这意味着它支持 64 位。

**Comment by Cp0204** [comment]
Please checkout https://github.com/IceWhaleTech/CasaOS-AppStore/pull/343 for solution.
