### ISSUE TITLE
Wheater Service

### ISSUE THREAD

**Issue by Martiiim** [IceWhaleTech/CasaOS#1447]
Casa OS is perfect but theres just one thing that i think is missing and thats an wheater service that maybe could appear between the hours and cpu.
Thanks for the attention

**Comment by ETWang1991** [comment]
Yes, I'm guessing you've set casaos as your browser's home page.

**Comment by JohnGuan** [comment]
@Martiiim Thank you for the feedback!

I think the scenario when CasaOS's WebUI is used as a browser homepage. Weather would be a handy widget.
This is definitely coming. but in the meantime, WebUI widget mechanisms and layout refactoring will be a higher priority.

@ETWang1991  
Let's just log it into a future feature that needs to be implemented.

**Comment by Martiiim** [comment]
> @Martiiim Thank you for the feedback!
> 
> I think the scenario when CasaOS's WebUI is used as a browser homepage. Weather would be a handy widget. This is definitely coming. but in the meantime, WebUI widget mechanisms and layout refactoring will be a higher priority.
> 
> @ETWang1991 Let's just log it into a future feature that needs to be implemented.

Great to hear that it´s coming!
