### ISSUE TITLE
[Bug] Can not open Casaos GUI

### ISSUE THREAD

**Issue by JasonLeeForOnly** [IceWhaleTech/CasaOS#1449]
**Describe the bug**

After I update casaos to the latest version,the GUI can not be opened.I check the status of casaos was actived.What I supposed to do?

**To Reproduce**

1. Update
2. Boom...not working

**Screenshots**
![50a8625c12d29b40d0d946cd3832ded](https://github.com/IceWhaleTech/CasaOS/assets/47520063/f0f29b36-476f-4d27-9cf3-c6f19f26a173)

**Desktop (please complete the following information):**

```
 - OS: Armbin
 - Browser：Chrome
 - Version：latest 
```

**Logs**

![image](https://github.com/IceWhaleTech/CasaOS/assets/47520063/7486b9a1-69da-4aa6-b2a9-303693bf7e9b)

**Comment by LinkLeong** [comment]
Looking at the logs it says you are running out of space on your device, can you delete some data and see what happens?

**Comment by JasonLeeForOnly** [comment]
> Looking at the logs it says you are running out of space on your device, can you delete some data and see what happens?

Actually I got 1GB space left on my device.
I try to delete some data,but the problem was still here.
Finally I try to re-install casaos,the GUI was back to normal.
Thanks for your advice,I'd like to know how much more space would be enough for stable running

**Comment by LinkLeong** [comment]
Actually we don't have a minimum space requirement, but since casaos needs some space to run, it is recommended to have more than 5 gigabytes of storage space. Also if the problem is solved, you can turn it off.
