### ISSUE TITLE
File explorer for containers

### ISSUE THREAD

**Issue by Dysta** [IceWhaleTech/CasaOS#1450]
**Is your feature request related to a problem? Please describe.**
Not related to any kind of problem but more like a pleasant way to access file inside a container. 
Actually we have to go to the settings of the container then in terminal and logs. From this, we can start navigate through the files of a container
![image](https://github.com/IceWhaleTech/CasaOS/assets/25008828/c2746060-1678-4cba-a26e-2ceb9fb5d62f)

**Describe the solution you'd like**
It would be really great if we can have a tab that allow us to explore the files of the container but with a pleasant GUI like the files app.

**Describe alternatives you've considered**
Actually we can use unix cmd in the terminal to navigate but we don't have the tab autocomplete so its error prompt. Also it don't have paste shortcut

**Additional context**
Here is the idea I mean but with the files inside the container
![image](https://github.com/IceWhaleTech/CasaOS/assets/25008828/471228a4-c0db-411c-820b-0ce14e427b8f)

**Comment by ETWang1991** [comment]
This is a bit like MacOS “show package contents”
![image](https:github.com/IceWhaleTech/CasaOS/assets/109786132/e1a2b82d-c22d-4182-9288-2176c67f465e)
Is there any other docker that can do this? @Dysta

**Comment by Dysta** [comment]
All container can do this by using `docker run -it <container_name> sh` if I understand correctly the question

**Comment by JohnGuan** [comment]
If I remember correctly, Files is currently implemented for file management through file system reads and operations. The way you mentioned should be implemented by executing the sh in the container.
Although the result is similar, the implementation is different. Design to a lot of development work.
Do you have any good ideas for a way of file management that can be used both on the host itself and within the container? Maybe we can discuss it.

From a feature requirements perspective, I think maybe what you want is to be able to easily manage container-related files somewhere, such as container configuration files and paths mapped to containers. After all, the perishable data in the image shouldn't be in the scope of what needs to be managed.

**Comment by Dysta** [comment]
For some containers, I like to customize a few things like the internal application code JS/python or HTML/CSS. This is a common operation for me (and probably a small part of the mcommunity) and I was just wondering if this could be implemented.

As a software developer, I realize that this will be asking a lot for only a tiny part of the community. On second thought, this feature isn't really necessary, even for me, as a workaround can be applied and the CasaOS team shouldn't waste much time working on it.
