### ISSUE TITLE
[Bug] 修改容器映射配置后提示地址冲突

### ISSUE THREAD

**Issue by guitarzsr** [IceWhaleTech/CasaOS#1452]
**【BUG简述】**
在CasaOS中修改容器映射（如端口、卷）等配置并保存后，容器无法正常启动，提示地址冲突，需重启宿主系统解决。

------

**【BUG复现】**
以linuxserver/qbittorrent为例
1.初次配置如下，可正常拉取并启动

    volumes:
    - /DATA/AppData/qbittorrent:/config
    - /mnt/:/downloads
    ports:
    - 8080:8080
    - 6881:6881 (udp+tcp)

2.对上述配置做任意修改，如

    volumes:
    - /DATA/AppData/qbittorrent:/config
    - /mnt/:/downloads
    ports:
    - 8080:8080
    - **6882:6882** (udp+tcp)

3.保存并应用，容器可以正常拉取映像（如有更新），但无法正常启动，提示

```
Error response from daemon: Address already in use
```

或

```
Error response from daemon: Cannot restart container 容器ID: Address already in use
```

4.出现BUG后，将容器改回原始配置等方式均无法启动，提示信息不变，需重启宿主系统方可解决冲突问题。

------

**【系统环境】**

已在多台设备上复现此BUG，系统/软件环境如下：

```
- 宿主系统：Debian 12 x64
- CasaOS版本：v0.4.4.2
- 浏览器：Google Chrome
```

硬件环境如下：

```
- J1800+2G+32G（物理直装Debian+CasaOS）

- J1800+4G+64G（物理直装Debian+CasaOS）

- N3160+4G+40G（爱快虚拟机）
```

**Comment by raller1028** [comment]
此问题也线下交流，重装debian12解决此问题,无法复现
