### ISSUE TITLE
[Bug] Files does not gets write in the volumes hosted by share drive in CasaOS

### ISSUE THREAD

**Issue by pratbhoir** [IceWhaleTech/CasaOS#1453]
**Describe the bug**
Files do not gets written in the volumes hosted by share drive in CasaOS

We are able to write files in the volumes of the host folder, but if we add the share drive to casaos, and mount that folder to volumes it is not able to write those files. 
But, from share drive mounted volumes, we are able to read it.

> A clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

I have added the network drive as follow
![image](https://github.com/IceWhaleTech/CasaOS/assets/6724899/f2133946-0f07-402b-b465-0569c54c0cc7)

In Volume, I have used it like below,

![image](https://github.com/IceWhaleTech/CasaOS/assets/6724899/351f368b-9baf-42f8-a0c6-a656dcbe2cbe)

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
```

**System Time**

> Run `timedatectl` and share the output

```
(timedatectl output here)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by LinkLeong** [comment]
It looks like deleting the slice file caused an error, but the file was actually uploaded successfully. This will be fixed in the next release.

**Comment by pratbhoir** [comment]
@LinkLeong You are saying, there is an Issue, right? 
I have added screenshots in original post to show that, have a look. 
My use case was, I wanted to use Share drive for qbittorrent, where once the download is complete, it will automatically move the downloads to share folder,
I am able to create/write files from the files APP, but not from the docker somehow.

**Comment by LinkLeong** [comment]
ok, I understand wrong, there is a problem need to clarify, docker internal mapped file directory if the external program to write a file (host), docker internal is not automatically refreshed to load the file, you have to restart the application, in order to refresh the file, I do not know if it has answered your question.

**Comment by LinkLeong** [comment]
I'll close this question and reopen it if you have any questions.
