### ISSUE TITLE
[Bug] inconsistency in UI

### ISSUE THREAD

**Issue by Dysta** [IceWhaleTech/CasaOS#1454]
**Describe the bug**
Idk if its a bug but there's an inconsistency in the UI. When you install a container, the popout have a clear progress bar. But in the back ground, the global progression is stuck with the current pulled layer and its not very easy to know how much percent have been intalled

> A clear and concise description of what the bug is.

**To Reproduce**
> Steps to reproduce the behavior:

1. install a container

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

![image](https://github.com/IceWhaleTech/CasaOS/assets/25008828/0a4d63a3-23b4-4b2e-bd6c-a04a7d495109)

**Desktop (please complete the following information):**

```
 - OS: Ubuntu 22.04 LTS
 - Browser Firefox
 - Version latest
```

**System Time**

> Run `timedatectl` and share the output

```
               Local time: mer. 2023-10-18 20:14:15 UTC
           Universal time: mer. 2023-10-18 20:14:15 UTC
                 RTC time: mer. 2023-10-18 20:14:15
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by ETWang1991** [comment]
You're right, it's not good

**Comment by jerrykuku** [comment]
First of all, thank you for your suggestion, we initially created the same effect as the installation for the progress bar at the top, but there was a problem that the progress would be displayed incorrectly when the page was refreshed, so we had to abandon this solution. We still need some time to solve this problem, and currently our focus is on adapting the software for the company's hardware products. If we solve this problem over there, we will implement it on CasaOS as soon as possible.
Of course, if the community can provide us with a good solution, we'd appreciate it.

**Comment by zhanghengxin** [comment]
Currently，the progress of the application installation is being stored in the frontend cache,which means it will be lost once the page is refreshed or a new page is opened. that's why such a design was implemented.

if you don't want this ambiguous behavior, my suggestion is to include the information about the current installation progress with the backend via socket.IO .

**Comment by jerrykuku** [comment]
v0.4.5 has been updated with this issue.

**Comment by Dysta** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/25008828/70f4391a-b645-46d5-ab3e-d660018b60a9)
Hello, I reopen this issue since some install can trigger this weird bug
