### ISSUE TITLE
[Bug] latest CasaOS (v0.4.4.2) doesn't refresh the system and network status

### ISSUE THREAD

**Issue by tzabbi** [IceWhaleTech/CasaOS#1457]
**Describe the bug**

CasaOS Gui elements like network and system status doesn't refresh.

**To Reproduce**

1. open the web interface

**Expected behavior**

The system and network status tool should update their values-

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/40226087/fde8f7e1-8a96-45ec-a458-8eb02ac93381)
**Desktop (please complete the following information):**

```
 - OS: Linux Fedora 38
 - Browser firefox 118
 - Version 
```

**System Time**

> Run `timedatectl` and share the output

```bash
$ timedatectl
               Local time: Fri 2023-10-20 09:46:08 CEST
           Universal time: Fri 2023-10-20 07:46:08 UTC
                 RTC time: Fri 2023-10-20 07:46:08
                Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.
I preordered the zimaboard with kickstarter.

**Comment by LinkLeong** [comment]
I need to confirm your use environment, because the network and cpu are using websocket, so need to open the port of websocket, so I need to confirm your cpu and ram have changed?

**Comment by LinkLeong** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/2c8909b2-d7a7-41a5-873a-f0e3ea1ac763)
If it's 832 you can try switching here

**Comment by tzabbi** [comment]
Same behavior, I tried this before.

**Comment by LinkLeong** [comment]
So your problem now is that the cpu refreshes normally, but both networks do?

**Comment by tzabbi** [comment]
My problem is that neither cpu nor network status is refreshing. I just refreshing it when I reload the page.

**Comment by LinkLeong** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/9bcf4e0f-2178-4e4b-a557-31ac46635a70)
Can you take a screenshot of this place, open developer tools, switch to network, select ws and refresh the page.

**Comment by tzabbi** [comment]
![grafik](https://github.com/IceWhaleTech/CasaOS/assets/40226087/aaa6bbd3-22eb-4464-985e-b49ba757af18)

**Comment by tzabbi** [comment]
It seems that this issue is DNS related. When I open the Webinterface with the IP address all works and when I use the Domain, it doesn't work.

**Comment by LinkLeong** [comment]
Yes, if you are on an external network, you need to open the port of the websocket, the port of our socket is randomized, so it is not recommended to access the external network. If there are no other problems, please close the issue, thank you for your feedback.

**Comment by tzabbi** [comment]
Im using the nginx proxy manager to generate a certificate and making the zima board web interface reachable trough a domain. It is not possible to use a domain name without losing this functionality? The nginx proxy manager runs as a docker container  on the zima board. I installed it via the zima appstore.

**Comment by LinkLeong** [comment]
I also need to understand your domain mapping process, what technology are you using to forward or reverse proxy casaos, nginx?

**Comment by LinkLeong** [comment]
`map $http_upgrade $connection_upgrade {
	default upgrade;
	'' close;
}
server {
	listen 443 ssl;
	server_name your-domain.com;
	
	ssl_certificate /etc/nginx/ssl/your-domain.com.crt;
	ssl_certificate_key /etc/nginx/ssl/your-domain.com.key;

	location / {
		proxy_pass http://localhost;
		proxy_http_version 1.1;
		proxy_redirect off;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_read_timeout 3600s;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;
	}
}`
It is recommended that you configure the nginx configuration according to the above, and change the certificate and domain name to your parameters.

**Comment by tzabbi** [comment]
Im Using the docker image of nginx proxy manager from the zima appstore. It generates a certificate for my domain. I configured my home dns server that the request goest to the nginx proxy manager docker container on the zimaboard (same ip) and the nginx proxy manager forwards the request to the configured device (in this case 192.168.1.2).

**Comment by tzabbi** [comment]
Appl

> ```
> map $http_upgrade $connection_upgrade {
> 	default upgrade;
> 	'' close;
> }
> server {
> 	listen 443 ssl;
> 	server_name your-domain.com;
> 	
> 	ssl_certificate /etc/nginx/ssl/your-domain.com.crt;
> 	ssl_certificate_key /etc/nginx/ssl/your-domain.com.key;
> 
> 	location / {
> 		proxy_pass http://localhost;
> 		proxy_http_version 1.1;
> 		proxy_redirect off;
> 		proxy_set_header Host $host;
> 		proxy_set_header X-Real-IP $remote_addr;
> 		proxy_read_timeout 3600s;
> 		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 		proxy_set_header Upgrade $http_upgrade;
> 		proxy_set_header Connection $connection_upgrade;
> 	}
> }
> ```
> 
> It is recommended that you configure the nginx configuration according to the above, and change the certificate and domain name to your parameters.

applied this config now I got a 502 response.

**Comment by tzabbi** [comment]
Fixed it!

I activated the websocket support in the proxy entry via gui:
![image](https://github.com/IceWhaleTech/CasaOS/assets/40226087/0aafe279-3a1b-4740-b64b-6da4c7879a3d)
