### ISSUE TITLE
Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39

### ISSUE THREAD

**Issue by lvfu** [IceWhaleTech/CasaOS#146]
![image](https://user-images.githubusercontent.com/25682116/161394560-27170961-7070-4a76-b366-6c926787c023.png)

![image](https://user-images.githubusercontent.com/25682116/161394575-e6e1ef61-812e-4e13-b0ef-1647ea595c90.png)

1.38是在etc那里边改的

**Comment by LinkLeong** [comment]
手动升级一下docker就行了
