### ISSUE TITLE
[Bug] 电脑端播放挂载的网盘视频文件没有图像，手机端正常

### ISSUE THREAD

**Issue by CGG888** [IceWhaleTech/CasaOS#1462]
电脑端播放挂载的网盘视频文件没有图像，手机端正常
![48](https://github.com/IceWhaleTech/CasaOS/assets/94150682/ffacc006-a8a4-429a-8dd1-78c8e09adaa8)
- 宿主系统：Debian 12 x64
- CasaOS版本：v0.4.4.2
- 浏览器：Google Chrome，Microsoft Edge版本 118.0.2088.61 (正式版本) (64 位)，

**Comment by CGG888** [comment]
![微信图片_20231023081529](https://github.com/IceWhaleTech/CasaOS/assets/94150682/d4691434-1a20-491f-a250-edf4ba1fca18)
手机端播放情况！

**Comment by LinkLeong** [comment]
1. what network disk you mounted
2. How big is your monitor
3. can not use google browser to open f12 to see if there is any error report
4. You can enter the microblogging group to contact us, you can more quickly locate and solve the problem.
1.你挂载的什么网盘
2.你的显示器多大
3.能不能用google浏览器打开f12看看有没有什么报错
4.可以进微信群联系我们(guanningchuan),可以更快速的定位和解决问题.

**Comment by jerrykuku** [comment]
The video playback capability of CasaOS depends on the decoding capability of the client device you are accessing, which will happen if you play a video that the client device browser cannot decode. Is it possible to capture part of your video for us to test, we will test its playback result on different devices.

CasaOS的视频播放能力依赖于，你的访问的客户端电脑的解码能力，如果你播放了一个客户端设备浏览器不能解码的视频，就会出现这种情况。能否截取你的视频的部分片段以供我们进行测试，我们会在不同的设备上测试它的播放结果。

我的初步判断结果是你的客户端电脑的浏览器不能支持播放高帧率的视频。并不一定是高码率。

**Comment by CGG888** [comment]
封神第一部：朝歌风云
https://www.aliyundrive.com/s/pVtEpH6oeEH
提取码: 5y1w
提取一下视频，但是这视频，我用alist挂载后alist是可以播放的，但是你们的调用模式和alist有差异，alist是直接调用阿里云盘的播放地址，casaos是本地代理播放的！有一定的差别，你说的那种情况不排除，如果可以的话，建议挂载到视频直接调用相关网盘的时间地址，那样的话，对于服务器的压力会小很多！

**Comment by jerrykuku** [comment]
这个视频我将它放到casaos本地的硬盘上，直接用casaos的网页播放是可以正常播放的，电脑是 macmini m1 + chrome.

**Comment by CGG888** [comment]
我是挂载在网盘哦！！本地我没有测试过！

**Comment by CGG888** [comment]
本地电脑可以播放，但是通过网页还是没办法播放！！！

**Comment by jerrykuku** [comment]
> 我是挂载在网盘哦！！本地我没有测试过！我换电脑测试一下吧！！！我用的是老婆刷剧的一台电脑！配置比较差！

如果同样是网盘挂载的话，手机和PC都是网页播放 ，但是结果是手机可以播放pc不能，那么可以排除是不是网盘的问题。
差异应该是两台设备的支持上。我附上我使用网页播放的截图。
<img width="1214" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/9485680/fd4d9608-d99a-4f4e-a4d4-65a90e127279">

同时附上我的视频的具体信息：
<img width="830" alt="image" src="https://github.com/IceWhaleTech/CasaOS/assets/9485680/6ce53900-c8c6-4e41-8fb0-8c259c5c8f78">

**Comment by CGG888** [comment]
你那边能不能用win系统测试一下啊！我这边没mac环境！！！！

**Comment by jerrykuku** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/9485680/1f93aa39-b61a-419b-a3fd-50840de7c71a)
这是我在windows11上测试的结果，硬件为AMD5600G 显卡为内置核显。

**Comment by jerrykuku** [comment]
Since this issue has been stagnant for a long time, and the latest CasaOS has updated the video player, you can retest it. I will close this issue for now. Feel free to continue providing feedback if any further issues arise.
