### ISSUE TITLE
[Feature request] Custom avatars for the user account & custom bg for login page

### ISSUE THREAD

**Issue by SleepyPeko** [IceWhaleTech/CasaOS#1463]
Hello, i would ask if there will be custom avatars support for Casaos like when your logging in to the dashboard that it shows your custom avatar instead of the default avatar since i already use CasaOS in my homelab and on private vps servers i own. below is 2 screenshots i would ask changed like instead of the default avatar it will be a custom avatar one. I like the default ones but i like it more if it was a custom avatar. btw all of my servers uses Ubuntu 20.04 LTS or higher. i also forgot to say is that is there gonna be a way to change the login background wallpaper to something else like a custom bg wallpaper or have like a preset option when you are logged into the dashboard. That's all.
![image](https://github.com/IceWhaleTech/CasaOS/assets/25424568/890d83d6-13ac-41be-a152-e40d3701b444)
![image](https://github.com/IceWhaleTech/CasaOS/assets/25424568/d239fde1-73d4-404f-9241-bd2fb632d3a1)
![image](https://github.com/IceWhaleTech/CasaOS/assets/25424568/eb13c196-7ce5-451f-a56a-fbc5af6e61c0)

Kind regards,
James

**Comment by ETWang1991** [comment]
Understand that, CasaOS’s limited development resources will focus on functional features first. Before that, you may be able to change the above 2 pictures by changing the picture files yourself. Maybe @jerrykuku  can tell you the path to the img file.

**Comment by SleepyPeko** [comment]
> Understand that, CasaOS’s limited development resources will focus on functional features first. Before that, you may be able to change the above 2 pictures by changing the picture files yourself. Maybe @jerrykuku  can tell you the path to the img file.      

Oh, I see. Thank you for the reply. I will ask @jerrykuku if he knows the default path for the img file.


@jerrykuku do you happen to know where the default image file for casaOS for Ubuntu like the default location for the file is?

**Comment by jerrykuku** [comment]
> > Understand that, CasaOS’s limited development resources will focus on functional features first. Before that, you may be able to change the above 2 pictures by changing the picture files yourself. Maybe @jerrykuku  can tell you the path to the img file.
> 
> Oh, I see. Thank you for the reply. I will ask @jerrykuku if he knows the default path for the img file.
> 
> @jerrykuku do you happen to know where the default image file for casaOS for Ubuntu like the default location for the file is?

You can find the default avatar image here, file name is :default-avatar.48989365.svg, You can replace it with "Files", but it will be reset after every CasaOS update.
![image](https://github.com/IceWhaleTech/CasaOS/assets/9485680/22424d47-904b-40af-b599-359f5a0614a1)

**Comment by SleepyPeko** [comment]
> > > Understand that, CasaOS’s limited development resources will focus on functional features first. Before that, you may be able to change the above 2 pictures by changing the picture files yourself. Maybe @jerrykuku  can tell you the path to the img file.
> > 
> > 
> > Oh, I see. Thank you for the reply. I will ask @jerrykuku if he knows the default path for the img file.
> > @jerrykuku do you happen to know where the default image file for casaOS for Ubuntu like the default location for the file is?
> 
> You can find the default avatar image here, file name is :default-avatar.48989365.svg, You can replace it with "Files", but it will be reset after every CasaOS update. ![image](https://user-images.githubusercontent.com/9485680/278809448-22424d47-904b-40af-b599-359f5a0614a1.png)

Oh, i see. Thank you
