### ISSUE TITLE
[Bug] CasaOS network share does not handle special characters

### ISSUE THREAD

**Issue by petterbergman** [IceWhaleTech/CasaOS#1465]
**Describe the bug**
Seems that CasaOS network share does not properly handle special characters in folder names of filenames, such as ? or /

**To Reproduce**
1. Open Files app in CasaOS
2. Create a folder and share it
3. Connect to share using MacOS finder
4. Return to CasaOS Files app
5. Right click on an empty space in the shared folder and select new file
6. Name it ? and click submit. You should now see the file ? in the Files UI
7. Go to the network share and wait for the file to appear or reopen to force a refresh

**Results**
In my case I get a file named "_2X68Q~8", but I suspect it might be a random name.

**Expected behavior**
A file named ?

**Screenshots**
<img width="918" alt="Screenshot 2023-10-24 at 14 24 34" src="https://github.com/IceWhaleTech/CasaOS/assets/2000376/47899079-bc8b-421b-b302-a153d0caa628">
<img width="1152" alt="Screenshot 2023-10-24 at 14 23 40" src="https://github.com/IceWhaleTech/CasaOS/assets/2000376/20bfb7ac-9b9a-49cc-99ca-a8cff6a5b6aa">

**Desktop **
macOS Sonoma 14.0 with Safari 17.0

**CasaOS**
Zumaboard CasaOS v0.4.4.2

**Additional context**
This issue was discovered using CasaOS syncthing app to sync files with MacOS using the syncthing app for Mac. There are several characters that when incorporate in the folder of file name will cause this behavior on the network share and in general cause file sync issue. So far, the characters tested to be problematic are : ? and /

**Comment by LinkLeong** [comment]
You can create a directory in the /DATA directory and use it according to your steps. What you have shared is the configuration directory for syncthing.

**Comment by petterbergman** [comment]
Sure. I followed the steps using /DATA as folder, and the result is the same. See attached photos.

<img width="865" alt="Screenshot 2023-10-25 at 16 51 31" src="https://github.com/IceWhaleTech/CasaOS/assets/2000376/babd7b71-879a-492d-bfcd-55454d2d7ea8">
<img width="726" alt="Screenshot 2023-10-25 at 16 49 41" src="https://github.com/IceWhaleTech/CasaOS/assets/2000376/b33bf9da-976c-421d-b2ac-915d6153f061">

**Comment by LinkLeong** [comment]
Understood. First of all, I haven't seen this problem before, but I'll assist you in troubleshooting.
1. you can create a new shared directory and mount it with your phone or Win to see if there are any problems.
2. If there is still a problem, I need to know what applications you have installed.

**Comment by petterbergman** [comment]
This happens if you mount the share on a Mac. It also happens, if I mount the share using the built-in Files app on an iPhone or iPad. It also happens, if I mount/browse the share from Microsoft File Explorer on Windows. I don't have a Linux box to test on.

Are you not able to reproduce this?
![Screen Shot 2023-10-26 at 11 52 15 AM](https://github.com/IceWhaleTech/CasaOS/assets/2000376/6245f9f3-f429-4618-9c59-dca7ac50e00d)

**Comment by LinkLeong** [comment]
Yes, I can't reproduce your question, I can get someone from the community to assist you in responding and see if I can reproduce your question.

**Comment by LinkLeong** [comment]
Not a Mac expert but i would have expect at least the / to fail in a directory name as it could be seen as separating the parts of the path. So for example /home/gavin is a folder called gavin under home. It’s not a folder called “home/gavin” under root. https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

**Comment by LinkLeong** [comment]
> Not a Mac expert but i would have expect at least the / to fail in a directory name as it could be seen as separating the parts of the path. So for example /home/gavin is a folder called gavin under home. It’s not a folder called “home/gavin” under root. https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names不是 Mac 专家，但我希望至少 / 在目录名称中失败，因为它可以被视为分隔路径的各个部分。例如，/home/gavin 是 home 下一个名为 gavin 的文件夹。它不是根目录下名为“home/gavin”的文件夹。https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

This is a reply from the community, I can't pinpoint your problem at the moment, from the way things are going you could try installing casaos on a different server, or reinstall the system and try again.
