### ISSUE TITLE
Homebridhe App store

### ISSUE THREAD

**Issue by mayconpabx** [IceWhaleTech/CasaOS#1468]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It would be amazing to have the Homebridge app available in the app store

**Comment by LinkLeong** [comment]
Are you trying to get the homebridge app to show up in the app store?

**Comment by tduarte** [comment]
Homebridge is available through the [Coolstore](https://github.com/WisdomSky/CasaOS-Coolstore) (3rd-Party App Store Source)
