### ISSUE TITLE
创建储存空间失败

### ISSUE THREAD

**Issue by NebulaCao** [IceWhaleTech/CasaOS#147]
什么时候能修复呢？现在完全不能用

**Comment by LinkLeong** [comment]
你使用的什么系统？是创建存储空间无反应吗？有没有提示需要格式化你的硬盘？

**Comment by NebulaCao** [comment]
> 你使用的什么系统？是创建存储空间无反应吗？有没有提示需要格式化你的硬盘？

`Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~21.04.2
 Built:             Mon Nov  1 00:21:07 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~21.04.2
  Built:            Tue Oct 19 01:00:27 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~21.04.1
  GitCommit:        
 runc:
  Version:          1.0.1-0ubuntu2~21.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:     `

创建储存空间时有提示格式化

点击格式化并创建之后提示  正在创建中。。。

然后就没有然后了

**Comment by NebulaCao** [comment]
3.0依然无法创建存储空间

**Comment by LinkLeong** [comment]
这个我需要先确定问题后面做个小版本更新

**Comment by LinkLeong** [comment]
你能运行一下  lsblk -O -J  内容贴一下或者发我邮箱a624669980@163.com

**Comment by NebulaCao** [comment]
> lsblk -O -J

已发

**Comment by LinkLeong** [comment]
I have replied in the email and we will optimize the issue. Thanks for your feedback
