### ISSUE TITLE
Fixe logs page to the bottom

### ISSUE THREAD

**Issue by Dysta** [IceWhaleTech/CasaOS#1477]
**Is your feature request related to a problem? Please describe.**
When you open logs on the web UI, it's stick to the top and we need to scroll to the bottom to see the latest logs. Thats not very convenient when we have a services that is on since multiple days.

**Describe the solution you'd like**
Directly open the logs to the bottom

**Describe alternatives you've considered**
We need to doom scroll to the bottom atm

**To reproduce**
Open any logs from any apps (even casaos logs) and see that it is at the beginning of the logs and not the end

**Additional context**
![image](https://github.com/IceWhaleTech/CasaOS/assets/25008828/0893cd7d-aec9-4221-b2db-087d42de7f24)
![image](https://github.com/IceWhaleTech/CasaOS/assets/25008828/fdd6d2f4-0466-452c-9076-2640fb7857cc)

**Comment by jerrykuku** [comment]
Ok, we will support this in a future release!

**Comment by jerrykuku** [comment]
v0.4.5 has been updated with this issue.
