### ISSUE TITLE
[Bug] CasaOS存储空间栏无法显示磁盘容量

### ISSUE THREAD

**Issue by sehczaa** [IceWhaleTech/CasaOS#1482]
设备：
友善NanoPC-T4、4+16GB、rk3399

系统：
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

![image](https://github.com/IceWhaleTech/CasaOS/assets/92673198/85fc07d7-1dbb-41da-b3b1-810d9b086054)
![image](https://github.com/IceWhaleTech/CasaOS/assets/92673198/c854a517-4e65-4093-a664-4ff0b0537054)

**Comment by LinkLeong** [comment]
You can see a reference to this question #706
你可看参考一下这个问题

**Comment by sehczaa** [comment]
> You can see a reference to this question #706 你可看参考一下这个问题

感谢解答，我也暂时找到了解决办法
![image](https://github.com/IceWhaleTech/CasaOS/assets/92673198/453647b0-1f98-47df-9d43-307a79af10aa)

**Comment by LinkLeong** [comment]
Thanks for your feedback, I will close this question and reopen it if you have any questions.
感谢你的反馈，我会关闭该问题，如有疑问可重新打开该问题。
