### ISSUE TITLE
Planka and Metabase

### ISSUE THREAD

**Issue by lesliefoster** [IceWhaleTech/CasaOS#1484]
**Is your feature request related to a problem? Please describe.**
Please add Planka and Metabase to CasaOS

**Comment by LinkLeong** [comment]
If you'd like to add applications to CasaOS, please visit the following link to submit a pull request: https://github.com/IceWhaleTech/CasaOS-AppStore/pulls. There, you can suggest adding Planka and Metabase, among others. Thank you for your suggestion!
