### ISSUE TITLE
[Bug] WebUI not reachable, service is running

### ISSUE THREAD

**Issue by DirkSimons** [IceWhaleTech/CasaOS#1497]
Although the service is running , checked by SSH into the casaOS ubuntu 22.04 server, and then run systemctl status casaos, the casaos webui is not reachable, when i was reachable before the weekend.
I know the IP, I know the port.  What am i missing, what can i check, what log do i need to examin?

Tested on:
 - OS: [macos 16, windows 10]
 - Safari, Chrome,n Edge, Firefox
 - Version casaos 0.4.4

**Comment by LinkLeong** [comment]
You can run `bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/casaos-healthcheck/run.sh)"`screenshots for us

**Comment by DirkSimons** [comment]
As requested.
<img width="2240" alt="Screenshot 2023-11-08 at 10 48 29" src="https://github.com/IceWhaleTech/CasaOS/assets/12816040/6f0096dc-6fe2-4423-9ff4-ac43c2b0f073">

**Comment by LinkLeong** [comment]
So you can't access 10.11.240.65:80 now? Can you post a screenshot of your browser opening it? I'd like to know what the status code is.

**Comment by DirkSimons** [comment]
<img width="1237" alt="Screenshot 2023-11-08 at 11 11 44" src="https://github.com/IceWhaleTech/CasaOS/assets/12816040/e7b79515-3588-4c27-b321-0b8447ed7871">
As you can see...   spinning on the tab on load.....

**Comment by DirkSimons** [comment]
<img width="1068" alt="Screenshot 2023-11-08 at 11 13 51" src="https://github.com/IceWhaleTech/CasaOS/assets/12816040/44a5ae9c-6730-4489-8b2c-fe6bed046872">

Safari does the same

**Comment by yq0702** [comment]
I have the same problem

**Comment by Kartofi** [comment]
Try to see from your routers settings if you the server is connected to the same network you are on

**Comment by DirkSimons** [comment]
@Kartofi : I can Ping to it and SSH into it.. Pretty sure I'm on the same network

**Comment by Kartofi** [comment]
Try to reinstall it then

**Comment by yq0702** [comment]
Actually I'm using Ubuntu desktop 20.04 LTS and I have reinstall CasaOS then it work well.  But if I enable ssh then I won't be able to access the webui of CasaOS. Another question can I know how to mount ntfs hard drive on CasaOS. Thank you so much.

**Comment by DirkSimons** [comment]
Found it...   seems to be a firewall problem.  SSH install makes rules to enable port 22, not port 80.  So I did the following in terminal, connected via SSH to the casaOs server:
`sudo ufw allow 80`

done!

**Comment by Kartofi** [comment]
Glad you resolved your problem

**Comment by Janakarpatel** [comment]
I have done everything but I can't access Webui from my laptop, I can access it from my phone browser, and I am using that phone as a hotspot to connect Raspberry Pi for ssh.

**Comment by Kartofi** [comment]
Is your laptop on the same network?

**Comment by Janakarpatel** [comment]
Thanks for the response, I will explain my steps.

I have installed Ubuntu server 22.04LTS on Raspberry 3B+ and configured my mobile hotspot while installing.
Then, I booted the Pi and when it was connected to my phone.
I did SSH through hostname and the laptop is connected to the same phone hotspot.
I install the casaos successfully.
But I can't access that URL from my PC. it shows the site can't reached.
I can access the same URL from my phone that is used for hotspot.
I have also installed UFW and allowed port 80 but it didn't work, then changed port to 81 but didn't work.

**Comment by Kartofi** [comment]
What is the url that you are accessing from your phone?
And if you have the local up of the pi try to ping it from the laptop.
Also another note because it is a phone hotspot I am not 100% if devices can connect to each other (your phone is the host so you can connect but your laptop is just a user*)

**Comment by Janakarpatel** [comment]
The URL is the same. but now I also think, that I should configure it using my router LAN. Thank you for your help. I am going to reinstall it again and get back to you if it still goes on.

**Comment by Kartofi** [comment]
Ig using the router will be a safe bet soooo 
Good luck👍

**Comment by Janakarpatel** [comment]
Thank you 👍
