### ISSUE TITLE
CasaOS Crashes on FX-6300 system

### ISSUE THREAD

**Issue by robtech21** [IceWhaleTech/CasaOS#1504]
Yesterday I installed CasaOS onto an AMD FX-6300 system (overclock to 4.6GHz, no overheating issues at all). The OS I used was a practically barebones install of Debian 12. For some reason, after a while of it working just fine, it will lock up the whole PC after just a few minutes. Is this an OS or hardware incompatibility issue? Thanks.

**Comment by jerrykuku** [comment]
Can you use the top command or the htop command to monitor the system's resource information after booting? We haven't encountered this so far, if you can provide some screenshots it will help us to locate the problem.

**Comment by robtech21** [comment]
> Can you use the top command or the htop command to monitor the system's resource information after booting? We haven't encountered this so far, if you can provide some screenshots it will help us to locate the problem.

Hey, I just remembered to work on this issue. Turns out lowering my overclock from 4.6GHz to 4.5GHz stabilized it and it no longer crashes.
