### ISSUE TITLE
[Bug] Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/debian/ buster: /etc/apt/keyrings/docker.gpg !=

### ISSUE THREAD

**Issue by jayx11** [IceWhaleTech/CasaOS#1506]
**Install script hangs and fails at docker install on Debian 10.13**

**To Reproduce**

> Steps to reproduce the behavior:

1. run install script
2. fail on docker install

**Expected behavior**

> it just work

**Console Logs**
```
[ INFO ] Install the necessary dependencies: Docker
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
+ sh -c 'apt-get update -qq >/dev/null'
+ sh -c 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null'
+ sh -c 'install -m 0755 -d /etc/apt/keyrings'
+ sh -c 'curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg'
+ sh -c 'chmod a+r /etc/apt/keyrings/docker.gpg'
+ sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian buster stable" > /etc/apt/sources.list.d/docker.list'
+ sh -c 'apt-get update -qq >/dev/null'
E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/debian/ buster: /etc/apt/keyrings/docker.gpg !=
E: The list of sources could not be read.
```

**What ive tried**
running the following:
`sudo rm /etc/apt/keyrings/docker.gpg`
`sudo rm /etc/apt/sources.list.d/docker.list`
and then running the script again.

**Desktop (please complete the following information):**

```
 - OS: [Debian 10.13 VM / PVE]
```

**System Time**
```
Local time: Sat 2023-11-11 09:50:31 EST
           Universal time: Sat 2023-11-11 14:50:31 UTC
                 RTC time: Sat 2023-11-11 14:50:31
                Time zone: America/New_York (EST, -0500)
System clock synchronized: yes
              NTP service: inactive
          RTC in local TZ: no
```

**Additional context**

> This is virtualized within Proxmox, but I didn't have an issue installing packages until running the install script

**EDITS**
* formating

**Comment by jerrykuku** [comment]
curl -fsSL https://get.docker.com | bash -s docker  You can use this script to try to install docker manually. 
If the installation is successful, run the CasaOS install command again.

**Comment by jerrykuku** [comment]
This Issue hasn't been updated for over 14 days, I will close it. if you still have problems you can reopen it or create a new Issue.
