### ISSUE TITLE
Can't connect OneDrive to the File app

### ISSUE THREAD

**Issue by jitoxx** [IceWhaleTech/CasaOS#1526]
**Describe the bug**

> I want to integrate my OneDrive with Casaos, but if i want to add it, i receive the error message "AADSTS900144: The request body must contain the following parameter: 'client_id'." from the Microsoft site.

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

![grafik](https://github.com/IceWhaleTech/CasaOS/assets/94313406/a726f8bb-a834-42e9-9033-e5017f0b6125)

```
 - OS: Linux Debian
 - Browser Firefox
```

**System Time**

> Run `timedatectl` and share the output
```
               Local time: Sat 2023-11-25 13:55:14 CET
           Universal time: Sat 2023-11-25 12:55:14 UTC
                 RTC time: n/a
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Logs**
[Logs.txt](https://github.com/IceWhaleTech/CasaOS/files/13464170/Logs.txt)

**Comment by CorrectRoadH** [comment]
Thanks for your feedback. I will to reproduce it and try to fix it

**Comment by CorrectRoadH** [comment]
I can't reproduce it. Could you share more info and reproduce steps.

**Comment by SASKarma** [comment]
I have similar issue. Installed on ubuntu.

**Comment by raller1028** [comment]
Thanks for the feedback, this issue already fixed and please update in terminal again@ @
Update command: `curl -fsSL https://get.casaos.io/update/v0.4.4-3 | bash`

**Comment by SASKarma** [comment]
> curl -fsSL https://get.casaos.io/update/v0.4.4-3 | bash

Thanks. This works now.
