### ISSUE TITLE
[Alpha][Bug] Unable to connect external service in file app

### ISSUE THREAD

**Issue by PandoffYT** [IceWhaleTech/CasaOS#1527]
### What happened?

missing "client_id" in request body

### Screenshots

![3](https://github.com/IceWhaleTech/CasaOS/assets/99325649/c3e804d7-ef7c-4b4c-a5f2-1a836f230703)
![2](https://github.com/IceWhaleTech/CasaOS/assets/99325649/b85da96e-ab6a-4c39-911d-4b5a110f46bc)
![1](https://github.com/IceWhaleTech/CasaOS/assets/99325649/b8f5732d-370a-4c38-8c68-707373bdd1b3)

**Comment by CorrectRoadH** [comment]
duplicate #1526

**Comment by CorrectRoadH** [comment]
Thanks for the feedback, this issue already fixed and please update in terminal again
Update command: curl -fsSL https://get.casaos.io/update/v0.4.4-3 | bash
