### ISSUE TITLE
[Bug] WebUI not functioning correctly (most element does not refresh or change)

### ISSUE THREAD

**Issue by AndreaDiNapoli** [IceWhaleTech/CasaOS#1530]
**Describe the bug**

Several elements of CasaOS web UI are not working properly. 
It seems like all the element that should dinamically appear and update themselve are not functioning correctly.
Some examples:
- CPU/RAM widget does not update itself, but it's stuck at the value it shows when the page is refreshed. The cpu/ram process list is functioning correctly.
- The card that show the progress of a new app installation or an app updating does not appear (the install/update is performed correctly though)
- Console is not accessible

**Screenshot**

https://github.com/IceWhaleTech/CasaOS/assets/88147799/e199cb37-b81a-4381-b459-b125d29bfada

(sorry for the video brightness)

**Desktop:**

```
 - OS: [e.g. iOS] Ubuntu Server
 - Browser [e.g. chrome, safari] Chrome/Brave/Firefox
```

**System Time**

Local time: Mon 2023-11-27 15:13:27 UTC
Universal time: Mon 2023-11-27 15:13:27 UTC
RTC time: Mon 2023-11-27 15:13:27
Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no

**Logs**

[casaos-logs.txt](https://github.com/IceWhaleTech/CasaOS/files/13477099/casaos-logs.txt)

**Comment by zhanghengxin** [comment]
It looks like the socket is not working.

**Comment by AndreaDiNapoli** [comment]
Thank you for answering. What does it mean?

**Comment by zhanghengxin** [comment]
There may be two ways to find the cause:

1、Open the browser console and check the log messages in the console.
2、Switch from HTTPS to HTTP and see if it works in the same environment.

**Comment by AndreaDiNapoli** [comment]
Wow, you were right!
It was a socket problem (I don't understand what it means, because I don't know anything, but after noticing that the http version was functioning correctly, I searched for the ngnix setting related to socket and was able to solve it!)

Thank you!

**Comment by zhanghengxin** [comment]
Could you share your solution？ You can add the Nginx configuration after this issue. This might help more people.
