### ISSUE TITLE
请问我忘记了我的登录密码怎么办呀

### ISSUE THREAD

**Issue by 759071793** [IceWhaleTech/CasaOS#154]
请问我忘记了我的Casaos登录密码怎么办呀

**Comment by jerrykuku** [comment]
如果你可以登录ssh的话。可以使用 cat /casaOS/server/conf/conf.ini 查看到  在[user] section中

**Comment by 759071793** [comment]
> 如果你可以登录ssh的话。可以使用 cat /casaOS/server/conf/conf.ini 查看到 在[user] section中

非常感谢你，找到密码了。
