### ISSUE TITLE
Docker 管理界面建议增加Docker 容器更新功能 

### ISSUE THREAD

**Issue by cnitlib** [IceWhaleTech/CasaOS#155]
**Describe the bug**

Docker 管理界面建议增加Docker 容器更新功能 ，现在没有更新功能 ，容器更新不太方便！

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.0
	 - Disk Total: 12059 
	 - Disk Used: 4714 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:4096M Core:2 Linux CasaOS 5.13.19-6-pve #1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200) x86_64 GNU/Linux]
	 - Browser: Edge 
	 - Version: 100.0.1185.44

**Comment by LinkLeong** [comment]
感谢反馈!我们正在考虑这方便的问题,不出意外的话会在近几个版本加入该功能.

**Comment by JohnGuan** [comment]
这个问题已经在 #167 中讨论了。你也可以加我微信：guanningchuan，我们可以在微信中进行中文交流。
