### ISSUE TITLE
[Bug] App store wont load 

### ISSUE THREAD

**Issue by frankchibu** [IceWhaleTech/CasaOS#1556]
**Describe the bug**
Hi.  Brand new zimaboard 832, on normo google fiber dhcp nothing fancy,  When I click on App Store I get this error
![image](https://github.com/IceWhaleTech/CasaOS/assets/143887871/0fb9086d-5fac-4281-83eb-56a35265a337)

(not sure if that worked it says 'Ther was an error loading the app store please try again later'

thanks, - windowsuser
> A clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
```

**System Time**

> Run `timedatectl` and share the output

```
(timedatectl output here)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by CorrectRoadH** [comment]
Thanks for your feedback. Does the problem still exist now?

**Comment by frankchibu** [comment]
Hi.  I think was my firewall, new install other config changes I'm good.
thanks!
