### ISSUE TITLE
opensuse 15.4 after install all dependence,I got this error .

### ISSUE THREAD

**Issue by wjcroom** [IceWhaleTech/CasaOS#1557]
NFO ] Installing CasaOS...
[ INFO ] Running /tmp/casaos-installer/tmp.0Mugdb8Ai9/build/scripts/setup/script.d/01-setup-gateway.sh...
/tmp/casaos-installer/tmp.0Mugdb8Ai9/build/scripts/setup/script.d/01-setup-gateway.sh: line 18: pushd: opensuse-leap/: No such file or directory
/tmp/casaos-installer/tmp.0Mugdb8Ai9/build/scripts/setup/script.d/01-setup-gateway.sh: line 20: pushd: opensuse-leap: No such file or directory
/tmp/casaos-installer/tmp.0Mugdb8Ai9/build/scripts/setup/script.d/01-setup-gateway.sh: line 23: pushd: suse: No such file or directory
/tmp/casaos-installer/tmp.0Mugdb8Ai9/build/scripts/setup/script.d/01-setup-gateway.sh: line 23: pushd: opensuse: No such file or directory
[FAILED] Failed to run setup script**Describe the solution you'd like**
 

the install path is diffrent with debian. so what can i do /??

**Comment by spuder** [comment]
Related https://github.com/IceWhaleTech/CasaOS/issues/1337#issuecomment-1827044556

[My current theory](https://stackoverflow.com/a/5193087) is that the `setup-gateway.sh` script is using `#!/bin/sh` instead of `#!/bin/bash`

**Comment by LinkLeong** [comment]
Due to.
1. the fix for #1557 should not be in that repository, but in casaos-gateway.
2. We don't plan to support opensuse yet.
3. The risk of this change is not manageable.
For these reasons, this request will not go through. I hope you understand.
