### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jtenniswood** [IceWhaleTech/CasaOS#1558]
<img width="153" alt="Screenshot 2023-12-16 at 16 55 44" src="https://github.com/IceWhaleTech/CasaOS/assets/10881541/020ecdbe-a2c7-43fc-b2d7-cbb89fabd506">

It would be nice if you could hide files that are created by MacOS.
For example when browsing MacOS creates lots of .DS_Store files. It would be good to respect the . as the intention not to show that to users in the file app.

**Comment by jerrykuku** [comment]
v0.4.5 has been updated with this issue.
