### ISSUE TITLE
[Bug] the content is worry when view file in Files 

### ISSUE THREAD

**Issue by CorrectRoadH** [IceWhaleTech/CasaOS#1559]
**Describe the bug**
relation app: https://github.com/IceWhaleTech/CasaOS-AppStore/pull/365
![CleanShot 2023-12-18 at 10 24 11@2x](https://github.com/IceWhaleTech/CasaOS/assets/29306285/80822673-7990-45f9-9552-06007e1dbfaa)
![CleanShot 2023-12-18 at 10 23 58@2x](https://github.com/IceWhaleTech/CasaOS/assets/29306285/40361f5e-ede5-42b0-bf70-6f5a2ff4e0b3)

there is difference between cat password in terminal and files

> A clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
```

**System Time**

> Run `timedatectl` and share the output

```
(timedatectl output here)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by jerrykuku** [comment]
Will be fixed in the next version.
