### ISSUE TITLE
可以加入sd卡或者u盘硬盘格式化挂载卸载或者smb共享后台配置功能嘛？

### ISSUE THREAD

**Issue by stevenliuit** [IceWhaleTech/CasaOS#156]
感觉每次插入sd卡通过命令去格式化和挂载或者开机启动挂载是一个麻烦的事情，和局域网共享文件文件夹一般通用协议是smb或者webdav这种共享方式访问希望官网可以加入这些功能，感觉非常实用。

**Comment by jerrykuku** [comment]
局域网挂载功能会在未来的版本中出现在files中的。

**Comment by stevenliuit** [comment]
smb共享这种会出现嘛

**Comment by jerrykuku** [comment]
会的

**Comment by stevenliuit** [comment]
谢谢

**Comment by JohnGuan** [comment]
这个问题已经在 #168 中讨论了 。你也可以加我微信：guanningchuan，我们可以在微信中进行中文交流。

**Comment by SmartYou1995** [comment]
> 局域网挂载功能会在未来的版本中出现在files中的。

新版本已经有了smb，想问一下webdav还远吗  计划啥时候加入
