### ISSUE TITLE
How to unrestrict this installation prompt

### ISSUE THREAD

**Issue by 1012363036** [IceWhaleTech/CasaOS#157]
requires atleast 5GB disk space (Disk space on / is 4GB).

**Comment by jerrykuku** [comment]
You can download casaos.sh first:
```
wget https://get.icewhale.io/casaos.sh
``` 
And then use vim modify casaos.sh . 
```
vi casaos.sh
```
Will find 'readonly MINIMUM_DISK_SIZE_GB="5"' in line 39, Change it to 3 or 4.
Save it, and 
```
chmod +x casaos.sh
./casaos.sh
```

**Comment by 1012363036** [comment]
Thank you for your answer.

**Comment by JohnGuan** [comment]
Looks like it's already fixed.
