### ISSUE TITLE
[Bug] Cannot connect to server IOS

### ISSUE THREAD

**Issue by Kordrad** [IceWhaleTech/CasaOS#1572]
**Describe the bug**

From a some time I cannot connect to server. Sometimes I see empty folder (in my case "Konrad"), sometimes nothing in folder or just I have an error. 

A month ago, I was able to open my folders, but I don't know why I can't now. 

On my Windows 11 everything works well when I use "Map network drive" 

PS: I use IP address instead of "casaos.local" because on VPN I'm able to connect only via IP address, but this is not important because on `casaos.local` I have the same problem.

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to `casaos.local` -> files -> shared
2. Click on triple dots and open **Get network path**
3. Copy path for **Mac (Finder)** (in my case: `smb://casaos.local/Konrad` or `smb://192.168.50.2/Konrad`)
4. on iPhone open files
5. in menu, select **Connect to Server**
6. in **Server** input provide path from above. 
7. Select **Registered User** and provide credentials that you use to log in `casaos.local`
8. a. ![image](https://github.com/IceWhaleTech/CasaOS/assets/29141389/652dcb98-26ef-4141-83e4-78a2f62393bd) b. See empty folder:![image](https://github.com/IceWhaleTech/CasaOS/assets/29141389/ff315356-e7bd-4587-91a1-bf31c8e94c8f)
9. After that I have connected server, but I see the same message as in **8b**

**Expected behaviour**

After provide credentials on iPhone, I'm able to see my files.

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/29141389/4aa43d03-4c2a-4637-9aea-5f41187b9da4)
![image](https://github.com/IceWhaleTech/CasaOS/assets/29141389/5b03522d-b85e-4bad-909f-ef48a619e9a2)
![image](https://github.com/IceWhaleTech/CasaOS/assets/29141389/6da1d2c6-f1c1-4b1a-8437-652cb7e38477)

**Desktop (please complete the following information):**

```
 - OS: linux
 - CasaOS Version: 0.4.4.2
 - Disk Total: 27712 
 - Disk Used: 19602 
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7789M Core:4 Linux CasaOS 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux]
 - Remote Version: 0.4.4.2
 - Browser: Edge 
 - Version: 120.0.0.0
 
 iPhone:
 - IOS: 17.2.1
 - iPhone 15 pro
```

**System Time**

> Run `timedatectl` and share the output

```
casaos@CasaOS:~$ timedatectl
               Local time: Wed 2023-12-27 04:42:49 EST
           Universal time: Wed 2023-12-27 09:42:49 UTC
                 RTC time: Wed 2023-12-27 09:42:49
                Time zone: America/New_York (EST, -0500)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Comment by Kordrad** [comment]
After update to `v0.4.4.3` I have the same problem

**Comment by xOrb1t** [comment]
Just typed ip address of server, everything works

![IMG_5730](https://github.com/IceWhaleTech/CasaOS/assets/105522815/9862a557-d47e-4e0b-90b3-437a008f3cef)
![IMG_5731](https://github.com/IceWhaleTech/CasaOS/assets/105522815/e197dd9d-ad94-483e-bbf2-b7fd7d51bba9)

**Comment by Kordrad** [comment]
> Just typed ip address of server being in a same network, everything works fine (or smb://ip-address, no specific folder) (just checked with specific folder, also works fine for me, every single time)
> 
> ![IMG_5730](https://private-user-images.githubusercontent.com/105522815/293503371-9862a557-d47e-4e0b-90b3-437a008f3cef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzg0NjcsIm5iZiI6MTcwNDEzODE2NywicGF0aCI6Ii8xMDU1MjI4MTUvMjkzNTAzMzcxLTk4NjJhNTU3LWQ0N2UtNGUwYi05MGIzLTQzN2EwMDhmM2NlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxOTQyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjcwMjdjNTZhN2IwYTM5Y2YwYmNiOTNjYjNjYTQyYjc2MjlhMjk1ZDNlYjU2YzkxNGYxZGIyMjU4ZjExYzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._r8gk5bMWZljh8CnhAXGBQclI2nkJ7BrBDh4M5nOeLM) ![IMG_5731](https://private-user-images.githubusercontent.com/105522815/293503376-e197dd9d-ad94-483e-bbf2-b7fd7d51bba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzg0NjcsIm5iZiI6MTcwNDEzODE2NywicGF0aCI6Ii8xMDU1MjI4MTUvMjkzNTAzMzc2LWUxOTdkZDlkLWFkOTQtNDgzZS1iYmYyLWI3ZmQ3ZDUxYmJhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxOTQyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmY1ODM5NTJmZjRhYjk5NWI2MWRhNzM2NTI0MDhlOGNmNDFmMWNjY2I0OTAyOWU4MmM3YjM3NjU4ZDM3NzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CPSWqExfN0YgG49FR_ST8_jb54ZHJZCr3xm_vTKlQrg)

Weird, after your answer I tried and I had also problem. I restarted my device and after that everything seems to be fine. We will see for how long. Thank you so much
