### ISSUE TITLE
无法创建硬盘空间

### ISSUE THREAD

**Issue by bg4vrg** [IceWhaleTech/CasaOS#158]
**Describe the bug**

操作系统：centos7 mini @esxi7.03
硬盘：一块16g系统盘，一块20g未挂载
目前进入web后发现存储空间为0，存储空间管理器里的存储空间和硬盘里都是空的，无法操作
[root@localhost ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   16G  0 disk 
├─sda1   8:1    0    1G  0 part /boot
├─sda2   8:2    0 13.4G  0 part /
└─sda3   8:3    0  1.6G  0 part [SWAP]
sdb      8:16   0   20G  0 disk 

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.0
	 - Disk Total: 13376 
	 - Disk Used: 3236 
	 - Sync State: Sync img: false
	Sync Key length: 0
	 - System Info: [CentOS Linux release 7.9.2009 (Core) Bit:64 Mem:991M Core:2 Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 100.0.4896.127

**Comment by LinkLeong** [comment]
感谢反馈,centos不在我们测试系统中,我们需要进一步测试才能给你答复.推荐使用Debian

**Comment by bg4vrg** [comment]
非常感谢您的回复！

**Comment by LinkLeong** [comment]
我会关闭该问题,有新的问题你可以新开issue,感谢反馈.
