### ISSUE TITLE
希望增加 文档在线预览 功能

### ISSUE THREAD

**Issue by Marrrrrrrrry** [IceWhaleTech/CasaOS#1582]
在最新版本的casa中，我注意到还没有实现文档在线预览，微软提供了接口
`https://view.officeapps.live.com/op/view.aspx?src=`
用来进行在线预览，保存和转换成pdf下载，希望可以评估并增加该功能

**Comment by Marrrrrrrrry** [comment]
这里是一个简单的示例
https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fraw.githubusercontent.com%2FMarrrrrrrrry%2Ftest%2Fmain%2F%25E6%25B5%258B%25E8%25AF%2595%25E9%25A2%2584%25E8%25A7%2588.docx&wdOrigin=BROWSELINK

**Comment by ETWang1991** [comment]
@jerrykuku 麻烦看看有帮助吗？我们研究下

**Comment by Marrrrrrrrry** [comment]
但是有一个点要注意，src后的url要转换成urlencode不然微软会报404。
再次，微软只接受域名开头作为文件源传入，例如ice.com/1.doc  像1.1.1.1/1.doc会报错，微软仅接受80、443端口传入
最后是我个人的建议，由于我常年套一层cf的cdn，这样微软是拿不到文件的，估计是cf的5秒盾微软过不了，所以要提醒用户不能套要人机验证的cdn

**Comment by jerrykuku** [comment]
我们在即将发布的新版本中增加了三个文件预览器，分别是word,excel和pdf，都是本地渲染。敬请期待。

**Comment by Marrrrrrrrry** [comment]
感谢

**Comment by jerrykuku** [comment]
v0.4.5已经发布，我将关闭这个issue.
