### ISSUE TITLE
应用中心无法打开  

### ISSUE THREAD

**Issue by xiongxuxx** [IceWhaleTech/CasaOS#159]
[ERROR][app.go:124]2022/05/01 19:39:49 [获取docker容器失败 app.sys line:123 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
[ERROR][app.go:59]2022/05/01 19:40:09 [获取docker容器失败 app.getmylist line:42 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
[ERROR][app.go:59]2022/05/01 19:40:55 [获取docker容器失败 app.getmylist line:42 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
[ERROR][app.go:59]2022/05/01 19:41:13 [获取docker容器失败 app.getmylist line:42 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]

设备 玩客云  Armbian 20.12 Buster with Linux 5.9.0-rc7-aml-s812
docker 版本 Docker version 20.10.14, build a224086

卸载 重新装之后 
AAnother process is initializing Nextcloud.

**Comment by JohnGuan** [comment]
Please use English and re-edit according to the issue template.
请使用英语并按照issue模板重新编辑。你也可以加我微信：guanningchuan，我们可以在微信中进行中文交流。
