### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Marrrrrrrrry** [IceWhaleTech/CasaOS#1591]

**Comment by Marrrrrrrrry** [comment]
相应的`协议头://域名/版本/文件类型?token=xxx&bash/文件完整路径`
替换末尾的文件路径也可以实现越权，比如我一个文件夹结构是 /pic/00001.jpg-99999.jpg
那一下就被脱裤了

而且今晚已经完美实现了替换新token和替换文件路径的两种攻击，希望可以尽快修复该漏洞，解决方案我放在 #1592 下，希望修复后早日发版

**Comment by Marrrrrrrrry** [comment]
1

**Comment by Cp0204** [comment]
个人看法这不算漏洞，你这个操作等同于把钥匙拿出来给了张三，并表示 “看！张三居然也能开我家的门”。

token之所以是token，当然是不可泄露的。但是 CasaOS 偷了个懒，直接整个 WebUI 的鉴权 token 用在文件下载，这也无可厚非，但是还用的 GET methods，这点欠考虑。

我的看法：
1. 文件管理器文件下载可以用全局 token（因为这个下载功能只是供admin管理用，不是让你分享出去的），但 token 应该对用户不可显，用 Header 或 POST 传参。
2. 文件分享如 https://github.com/IceWhaleTech/CasaOS/issues/1592 所说，这个方案不错的。

**Comment by Marrrrrrrrry** [comment]
但是你所有的请求都可以被三方抓包，你能保证一辈子所在的局域网中没有这种人吗。我不知道你是不是特地去看的历史记录，但是在非登录状态下就可以下载是很恐怖的事情

**Comment by CorrectRoadH** [comment]
> 但是你所有的请求都可以被三方抓包，你能保证一辈子所在的局域网中没有这种人吗。我不知道你是不是特地去看的历史记录，但是在非登录状态下就可以下载是很恐怖的事情

首先承认确实存在arp攻击然后抓包偷取token的可能。这个安全隐患也确实存在，只是因为相对来说不容易被利用所以没有很高优先级的修复。在未来我们也会用更合适的方式去重构这一块解决这个问题。🥺

**Comment by Marrrrrrrrry** [comment]
我在#1592给了解决方案，而且这个完整原文我提交在https://github.com/IceWhaleTech/CasaOS/security
下，但是好像一直没人处理

**Comment by Marrrrrrrrry** [comment]
@CorrectRoadH

**Comment by CorrectRoadH** [comment]
> 给

奇怪，我们并没有收到🫠
![CleanShot 2024-01-11 at 16 15 58@2x](https://github.com/IceWhaleTech/CasaOS/assets/29306285/8e5a4176-f32c-4599-b930-a01bcf94325d)

**Comment by Cp0204** [comment]
> 但是你所有的请求都可以被三方抓包，你能保证一辈子所在的局域网中没有这种人吗。我不知道你是不是特地去看的历史记录，但是在非登录状态下就可以下载是很恐怖的事情

我的设备在公网环境，所以特别关注安全性。

留意我第一句，把token交出去，就等同于把登录状态交出去了。所以并不是“非登录状态下就可以下载”。

确实不排除被抓包的可能，在这种情况下，不管是下载链接含token，还是其它请求抓 HTTP Header 中的 Authorization 都能抓到。所以也不是“下载链接中含全局token就是漏洞”，当然，会不那么安全，所以我建议放到 GET 或 Header 中传参。

如果你理解了我上一段的内容，可能就不会发出这段反问了。

**Comment by Marrrrrrrrry** [comment]
说实话，我收到你的回复邮件是很懵的，因为这条issue我在发出后10分钟就清空了。在昨天这条issue的状态已经是关闭但你今天回复我,我认为是不礼貌的。

你说我理解你上文就不会反问，事实上我很早就给了解决方案，你说的http header，我在 #1578 中就提出当前无法部署证书，并给出了目前的解决方案。我的机器也在公网，不是只有你一个注重安全体验。

我肯定你说的post请求就get来说不安全，但被局域网arp攻击后，甚至你说的迅雷，还有上次v2ex说的tx会扫描发送的网址。据我测试，token的有效期是3小时以上，这种隐患你让我无视我确实做不到。所以我现在做防火墙限制入站。但我知道很多小白不知道加前置cdn不知道设置入站规则，所以我在这里提出这个问题
