### ISSUE TITLE
[Bug] WebUI Settings `Container Hostname` Misunderstanding

### ISSUE THREAD

**Issue by Cp0204** [IceWhaleTech/CasaOS#1601]
**Describe the bug**

修改当前 0.4.4.3 WebUI 应用设置中 `容器主机名` 字段，会错误地改变  `容器名`，即 docker-compose 中的 [container_name](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#container_name)，而并非真正 `容器主机名`  [hostname](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#hostname)。

Modifying the `Container hostname` field in the current 0.4.4.3 WebUI application settings incorrectly changes the `Container name`, which is [container_name](https://github.com/compose-spec/compose-spec/blob/) in docker-compose, instead of the real `Container hostname` [hostname](https://github.com/compose-spec/compose-spec/blob/master/05-services.md#hostname).

**Expected behavior**

正确开放两个字段设置项：

| 中文 | English | 对应字段 Compose field | 说明 Description |
| - | - | - | - |
| 容器主机名 | Container Hostname |  `hostname` | 容器内部识别的主机名 |
| 容器名 | Container Name | `container_name` | docker管理中显示的容器名，不影响容器内部 |

**Comment by zhanghengxin** [comment]
Assign values to two fields for now.

@ETWang1991  
Whether the new version collects this requirement.

**Comment by Cp0204** [comment]
> Assign values to two fields for now.
> 
> @ETWang1991 Whether the new version collects this requirement.

@zhanghengxin @ETWang1991

https://github.com/IceWhaleTech/CasaOS-UI/commit/b744a7404ae3487f7be03dfaf53ae9fe78d11a3d

把 `container_name` 和 `hostname` 都等于同一个输入字段，是一种处理逻辑，简单和友好。但可能不适用于高级用户， 实际上它们是不同的概念，还是希望在设置UI中区分，并各自修改。

Equating both `container_name` and `hostname` to the same input field is a processing logic that is simple and user-friendly. However, it may not be suitable for advanced users, as they are actually different concepts, and it is desirable to differentiate them in the settings UI and modify them individually.

**Comment by john-clark** [comment]
doing custom via webgui I do not find a way to define hostname, curious to why this was closed
