### ISSUE TITLE
Tips to make VidHub APP connect to CasaOS SMB

### ISSUE THREAD

**Issue by liaol** [IceWhaleTech/CasaOS#1605]
Here is a tips to make VidHub APP connect to CasaOS SMB

Add `max protocol = SMB3_02` to  the global section of `/etc/samba/smb.conf`

Then Run `systemctl restart smbd`

**Comment by leonguyen52** [comment]
I got issue with VidHub while adding CasaOS SMB in File Source. I did tried above method but it didn't work with latest version of Vidhub. However I found that I add both following lines then it worked for me, so just share here to let anyone who got same issue some idea on how to solve it. Just need to add into /etc/samba/smb.conf under [global] section
```
    max protocol = SMB3_02
   client min protocol = CORE
```
