### ISSUE TITLE
日志无法自动刷新

### ISSUE THREAD

**Issue by starkiller43** [IceWhaleTech/CasaOS#161]
**Describe the bug**

日志只能显示到点击日志时的内容，后面增加的内容无法刷新，必须关闭日志窗口重新进入才能看到更新的日志内容。

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.0
	 - Disk Total: 19023 
	 - Disk Used: 8729 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 0
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:M Core:2 Linux CASAOS 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 101.0.4951.41

**Comment by jerrykuku** [comment]
Thanks for the feedback, maybe adding a refresh function to the logs and also grouping the logs by date would be a good feature.

**Comment by ETWang1991** [comment]
@jerrykuku It is recommended to refresh the interface directly when it is opened at regular intervals. Not dependent on refresh button
建议直接在界面打开时，定时刷新。不依赖于刷新按钮

**Comment by ETWang1991** [comment]
这个问题已经解决，可以用新版本试一下，界面开启时，日志定时刷新
