### ISSUE TITLE
[Bug] 更新后把DATA文件夹(分区)下的所有文件全给我清空了

### ISSUE THREAD

**Issue by ChishFoxcat** [IceWhaleTech/CasaOS#1624]
**Describe the bug**

> A clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]
```

**System Time**

> Run `timedatectl` and share the output

```
(timedatectl output here)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

更新后,把我DATA文件夹(分区)下所有文件/文件夹数据全部清空,我的备份数据,我的视频图片全部清除了,但是空间容量没有变

我大部分的docker镜像因为这次更新,都无法启动

**Comment by Cp0204** [comment]
尝试重启？看着像 LocalStorage 服务没有启动

**Comment by kukusyaoran** [comment]
这边遇到的是全新安装，重启系统后所有安装的容器都是灰色没有启动状态，查看日志发现 “/DATA/AppData” 下所有容器映射的目录都不见了，手动创建后再重启系统就正常了
![截屏2024-01-20 20 16 07](https://github.com/IceWhaleTech/CasaOS/assets/3970588/80c9daf2-0d9c-4e5a-98ab-084f5d411d42)

**Comment by EdiFX** [comment]
I'm having the same problem, any solution?

**Comment by ChishFoxcat** [comment]
发现在 `/usr/bin/casaos` 中有部分原始分区和部分原数据，将其复制出我的移动硬盘上，不打算继续使用其数据保存或管理的工具了，docker管理还是不错
