### ISSUE TITLE
[Bug] The application list can’t be scrolled down

### ISSUE THREAD

**Issue by Cp0204** [IceWhaleTech/CasaOS#1626]
v0.4.5，在首页，应用列表无法往下滚动。
v0.4.5, on the home page, the application list can’t be scrolled down.

![image](https://github.com/IceWhaleTech/CasaOS/assets/5239753/e45049d5-8336-470c-8659-cb9c69f65429)

----

#### Problems in this browser:

Cent Browser version 5.0.1002.354 (official) (64-bit) (Chromium 102.0.5005.167)

#### Works fine in this browser:
Microsoft Edge version 121.0.2277.71 (official) stable app, beta channel (64-bit)

**Comment by JochenZhou** [comment]
我的Cent Browser也不行

**Comment by Cp0204** [comment]
该问题经 centbrowser 版主回复，确认是 chrome 内核版本过低导致的。建议用户自行升级浏览器。

This issue has been replied by centbrowser moderators and confirmed to be caused by a low version of the chrome kernel. Users are advised to upgrade their browsers.

> 高度用了个新 CSS 单位，这需要 108 内核版本以上才能识别，从而导致目前版本的百分浏览器无法正常显示滚动条(commit: [Add avatar.](https://github.com/IceWhaleTech/CasaOS-UI/commit/e101450aee8dc80707426094d90900a50f959588))。
>
> ![image](https://github.com/IceWhaleTech/CasaOS/assets/5239753/94fe07ba-6892-4fd4-a4bf-9312522acb0f)

**Comment by Cp0204** [comment]
鉴于 centbrowser 中文用户居多，本 issue 标题做问题现象中文备注，以便查证。

>  登录框高度错误，应用滚筒条无法下拉
> Login box height is wrong, app roller bar can't drop down
