### ISSUE TITLE
VNC shows a BLANK screen.

### ISSUE THREAD

**Issue by dulfe** [IceWhaleTech/CasaOS#163]
**Describe the bug**

Connecting to this server using VNC shows a BLANK screen but keyword and mouse works.

I am using VNC Viewer (RealVNC).

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.0
	 - Disk Total: 27712 
	 - Disk Used: 10285 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux]
	 - Browser: Firefox 
	 - Version: 101.0

**Comment by JohnGuan** [comment]
This doesn't seem to be a problem with the CasaOS software, is this a problem on the ZimaBoard? You could probably try using rdp to access it.

**Comment by AuthorShin** [comment]
@dulfe I'm going to close it for now but if you still have this problem you can open a new issue.
