### ISSUE TITLE
Unable to upload and change OS wallpaper

### ISSUE THREAD

**Issue by cordelljones1996** [IceWhaleTech/CasaOS#1633]
### What happened?

Unable to upload and change OS wallpaper

### Screenshots

![image](https://github.com/IceWhaleTech/CasaOS/assets/61244959/87ec6b0a-cc25-4b3e-821d-b7f5f516c2d0)

**Comment by jerrykuku** [comment]
Will fix it soon.

**Comment by x3llaz** [comment]
I thought it was my Pi5 or my browser.... seems this is a known issue? I can't upload/change my wallpaper too after upgrading to v0.4.5. 😅

**Comment by LinkLeong** [comment]
This problem has been fixed in the latest version, please restart after updating.
