### ISSUE TITLE
[Bug] 文本未对齐

### ISSUE THREAD

**Issue by LSP0123** [IceWhaleTech/CasaOS#1635]
**Describe the bug**

> Appstore内，无简介app的文本未对齐

![image](https://github.com/IceWhaleTech/CasaOS/assets/31061624/1a862374-45cc-41eb-92d6-9897a3a8fbd8)

**Desktop (please complete the following information):**

```
 - OS: win11
 - Browser：firefox/edge
 - Version ： CasaOS 0.4.5
```

**Comment by jerrykuku** [comment]
会在下一版修复
