### ISSUE TITLE
[Alpha][Bug] CasaOs store is constantly loading

### ISSUE THREAD

**Issue by LJakubow** [IceWhaleTech/CasaOS#1656]
### What happened?

As mentioned, casaOs store is constantly loading. Logs from appstore give me those errors:
casaos-app-management[3801]: 2024-01-26T16:13:13.908+0100 info failed to parse compose app - contact the contributor of this app to fix it
{
    "error": "validating : services.twingate-connector.ports must be a list",
    "composeFile": "/var/lib/casaos/appstore/default/Apps/Twingate/docker-compose.yml",
    "func": "service.BuildCatalog.func1",
    "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/appstore.go",
    "line": 369
} and 
casaos-app-management[3801]: 2024-01-26T16:13:51.261+0100 error failed to get store info
{
    "error": "1 error(s) decoding:\n\n* 'screenshot_link': source data must be an array or slice, got string",
    "appStoreID": "unifi-network-application",
    "func": "v2.(*AppManagement).ComposeAppStoreInfoList.func1",
    "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/route/v2/appstore.go",
    "line": 120
}

### Screenshots

![image](https://github.com/IceWhaleTech/CasaOS/assets/77981122/556fa7f1-0a2d-4fbd-a936-d2d27f67f522)

**Comment by joaomcs** [comment]
I get the same issue. I completed uninstall casaos and then re-install but the bug still persists.

**Comment by F-Jay** [comment]
I get the same issue. Did fresh install as well. Issue still persists.

**Comment by carbonbenji** [comment]
get the same issue. Did fresh install and try different DNS Settings on my Router  and server then I try install div App stores (unregistered) and the newest Docker versions (non stable). Issue still persists.
Anybody have other ideas? Or a Fix

**Comment by carbonbenji** [comment]
curl -fsSL https://get.casaos.io/update | sudo bash

Fix the problem

**Comment by dragonfire1119** [comment]
https://github.com/IceWhaleTech/CasaOS-AppStore/pull/374#issuecomment-1912721833

**Comment by josephbwagner** [comment]
> `curl -fsSL https://get.casaos.io/update | sudo bash`
> 
> Fix the problem

This worked for me

**Comment by LSP0123** [comment]
> `curl -fsSL https://get.casaos.io/update | sudo bash`
> 
> Fix the problem

@josephbwagner 

 no use for me 
the casaos is 0.4.6 version

**Comment by GuoYuefei** [comment]
> [IceWhaleTech/CasaOS-AppStore#374 (comment)IceWhaleTech/CasaOS-AppStore#374 （评论）](https://github.com/IceWhaleTech/CasaOS-AppStore/pull/374#issuecomment-1912721833)

good work

**Comment by carbonbenji** [comment]
> > `curl -fsSL https://get.casaos.io/update | sudo bash`
> > 
> > Fix the problem
> 
> @josephbwagner 
> 
>  no use for me 
> the casaos is 0.4.6 version 
> 
> 
> [log.txt](https://github.com/IceWhaleTech/CasaOS/files/14072075/1.txt)
> 

You can update it again, update over web UI makes the problem.

**Comment by LSP0123** [comment]
> > > `curl -fsSL https://get.casaos.io/update | sudo bash`
> > > Fix the problem
> > 
> > 
> > @josephbwagner
> > no use for me
> > the casaos is 0.4.6 version
> > [log.txt](https://github.com/IceWhaleTech/CasaOS/files/14072075/1.txt)
> 
> You can update it again, update over web UI makes the problem.

it was update via ssh

**Comment by LJakubow** [comment]
Ok, so updating lefts me hanging after clearing logs, but from super user i managed to resolve this issue with update
