### ISSUE TITLE
[Bug] AppStore is constantly loading.

### ISSUE THREAD

**Issue by lekpkd** [IceWhaleTech/CasaOS#1657]
**The AppStore isa loading nonstop.**

**Running  on**
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Client**
```
 - OS: Windows 11 Pro x64
 - Browser: Edge
 - Version 121.0.2277.83 (Official build) (64-bit)
```

**Screenshots**

![Screenshot 2024-01-26 232257](https://github.com/IceWhaleTech/CasaOS/assets/8196825/e51bcd83-ca8f-49e1-a67e-bbb5db639d60)

**System Time**

> Run `timedatectl` and share the output

```
Local time: Fri 2024-01-26 23:33:49 +07
Universal time: Fri 2024-01-26 16:33:49 UTC
RTC time: Fri 2024-01-26 16:33:49
Time zone: Asia/Vientiane (+07, +0700)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no
```

**Logs**

[Logs.txt](https://github.com/IceWhaleTech/CasaOS/files/14067212/Logs.txt)

**Comment by dragonfire1119** [comment]
https://github.com/IceWhaleTech/CasaOS-AppStore/pull/374#issuecomment-1912721833

**Comment by dragonfire1119** [comment]
I made a script to fix this: https://community.bigbeartechworld.com/t/fix-the-casaos-app-store-not-loading/593?u=dragonfire1119
