### ISSUE TITLE
[Bug] there is a typo in Install Script

### ISSUE THREAD

**Issue by axolotlagatsuma** [IceWhaleTech/CasaOS#1666]
**Describe the bug**
Typo in install script "wget -qO- https://get.casaos.io | sudo bash"
> A clear and concise description of what the bug is.
Script says "Docker verison" but it supposed to be "Docker version"  
**To Reproduce**
Install with "wget -qO- https://get.casaos.io | sudo bash"
> Steps to reproduce the behavior:

1. Execute the command "wget -qO- https://get.casaos.io | sudo bash"
2. See error

**Expected behavior**
The script is expected to tell docker version

**Screenshots**
![Ekran Görüntüsü - 2024-01-29 19-54-47](https://github.com/IceWhaleTech/CasaOS/assets/154734794/7973c0a5-8113-46de-bed7-96e399c72026)

**Comment by raller1028** [comment]
Thanks for your feedback

**Comment by raller1028** [comment]
Already fix
