### ISSUE TITLE
CasaOS in Proxmox LXC not showning Network & Storage Status.

### ISSUE THREAD

**Issue by Andersonong-github** [IceWhaleTech/CasaOS#1668]
Hi Casa Teams,

Thanks for the fabulous OS created & I'm not sure this is a bugs or only happened to me.. below are my hardware specs.

 - OS: linux
 - CasaOS Version: 0.4.6
 - Disk Total: 30130 
 - Disk Used: 17053 
 - System Info: [Debian GNU/Linux 12   \l Bit:64 Mem:8192M Core:2 Linux casaos 6.5.11-7-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-7 (2023-12-05T09:44Z) x86_64 GNU/Linux]
 - Remote Version: 0.4.6
 - Browser: Chrome 
 - Version: 120.0.0.0

I'm installed in Proxmox LXC. when I access the CasaOS Dashboard. my storage & Network status are showing 0 bytes. I follow the article to configure the IPv4 to DHCP but result still the same.. apprieciated your help. thanks
![image](https://github.com/IceWhaleTech/CasaOS/assets/69752617/60be46ef-de28-4f3a-a7db-eae38bad00a8)

**Comment by tomtheswede** [comment]
Seconded. Installed using a Proxmox helper script on Intel N100 PC with Debian 12 LXC:
bash -c "$(wget -qLO - https://github.com/tteck/Proxmox/raw/main/ct/casaos.sh)"

**Comment by Andersonong-github** [comment]
Hi Sir. 
same also with the script that you provided..

![image](https://github.com/IceWhaleTech/CasaOS/assets/69752617/ab2e701c-a07a-46d4-93e5-897c2dabc40f)

**Comment by LinkLeong** [comment]
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/8a1fe8d6-56d0-4ebb-a44c-5c283962b7b7)
This piece of code is to get the information of the network card, you need to make it clear that you confirm the system is not the system we support, in addition, we are here to get the information of the network card by default is the data of the physical network card.

**Comment by gvillo** [comment]
@LinkLeong experiencing the same, this is what I got after running that command:
![image](https://github.com/IceWhaleTech/CasaOS/assets/11096470/0149458d-e4a1-474f-bfa5-016b4b161e9d)

**Comment by GiorgioRX** [comment]
did anyone found a solution for this?

**Comment by thorracin1** [comment]
Same here any updates

**Comment by ChristoffBo** [comment]
also waiting for a sollution

**Comment by Seniix3** [comment]
Same issue over here.

**Comment by Andersonong-github** [comment]
> ![image](https://private-user-images.githubusercontent.com/13556972/306217916-8a1fe8d6-56d0-4ebb-a44c-5c283962b7b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzkxODYsIm5iZiI6MTcxOTM3ODg4NiwicGF0aCI6Ii8xMzU1Njk3Mi8zMDYyMTc5MTYtOGExZmU4ZDYtNTZkMC00ZWJiLWE0NGMtNWMyODM5NjJiN2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA1MTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0OWQ4MzVjMjU3YTkxNWE3NjZlMjA3ZjY0MDAyMWI2MjNjNmVhYmVmYmJlYTRiNTFmNjFjMjE0YWMzMjkwMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UswoatKZMIdKctRb3LzLfba2-z86EBbIaGKaryeLwfQ) This piece of code is to get the information of the network card, you need to make it clear that you confirm the system is not the system we support, in addition, we are here to get the information of the network card by default is the data of the physical network card. @Andersonong-github

**Comment by Andersonong-github** [comment]
by the way, I'm tried ZimaOS & dashboard are similar as CasaOS. network & storage are wonderful when in Proxmox LXC. Thanks.

**Comment by yeswanthkumar97** [comment]
@Andersonong-github  Can you reply on how you installed ZimaOS in an LXC?

**Comment by Andersonong-github** [comment]
1. Download latest ZimaoS .img.xz file a. Either download directly to Proxmox var/lib.vz/images andunzip.xzb. orlike me, downloaded to PC, unzipped with 7zip and transferred ~4GB file with WinSCP.

2. Create a new VM in Proxmox. Other than the information below, the rest of the settings are your own choice.

3. OS- Select 'Do not use any media' -> Guest OS = Linux and 6.x - 2.6 Kernel.

4. System = BIOS = OVMF (UEFI) - Add and select the EFI storage location = SCSI Controller = VirtIO SCSI Single.

5. Disk - Choose an option here: Delete the default disk, and only the OS will be installed later Increment to scsi 1 and use disk as storage. OS will be on a separate disk later.

6. Mount image to VM Disk. Enter the Promox Server shell, either by ssh or GUI.

7. Confirming the file details. $ qemu-img info /var/lib/vz/images/fFILENAME>.img=>Replace fFILENAME)
 8. Import the .img to the VM$ qm set fVM_ID) --scsi0 [LOCAL_STORAGE>:0,import- from=/var/lib/vz/images/fFILENAME>.img-ReplacefVM_IDtand (FILENAME) -> For example $ qm set 999 --scsi0 local- zfs:0,import-from=/var/lib/vz/images/zimaos_zimacube- 0.4.8.1.img

9. Adjust Boot Order.

10. On the VM, select Options and change the boot order to scsi0.

11.Disable SecureBoot

12. As per, https://www.youtube.com/watch?v=js_Xoa0f8zM 29 -> Select console, Start the VM and mash the esc key - Device Manager >> Secure Boot Configuration >> Attempt Secure Boot >> Enter (to disable) -> Escape and exit.

ZimaOS will now boot. It will not display the P address in the console, so you'll need tc find that yourself or use the application linked in the original instructions
 Video demonstration
https://www.youtube.com/watch?v=K4p0kBwJMg8&t=1s

**Comment by yeswanthkumar97** [comment]
Thanks for your reply but I believe these steps are for installing ZimaOS in a VM. 
In your previous message, you mentioned installing ZimaOS in LXC hence I was curious about the steps.

**Comment by tomshomelab** [comment]
This is still an issue, a friend of mine ran into this doing this installation

**Comment by Rod-Gomes** [comment]
Same issue over here.

**Comment by partisan83** [comment]
Same issue. As I know - good solution is to install CasaOS in UbuntuVM. But. Is there any solution how to migrate current LXC instance to UbuntuVM with all installed applications and its configuration?

**Comment by CaptInsano** [comment]
Came to report same issue.

CasaOS LXC, latest version: Nothing reported under Storage or Network.

![Image](https://github.com/user-attachments/assets/e1dfc437-77bd-49c9-a357-df3a8437b5b7)

@Andersonong-github or a CasaOS team member: can you please re-open this issue as it is not fixed for those of us wishing to remain with an LXC rather than move to a VM.
