### ISSUE TITLE
JS and CSS injection in webinterface

### ISSUE THREAD

**Issue by Slluxx** [IceWhaleTech/CasaOS#1677]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
An option within the interface to inject our own JS and CSS so we can customize our experience.
Alternatively themes for us to play with.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jerrykuku** [comment]
For a simple solution to this problem, I think we can add a blank js and css file to the webui directory so that we can easily inject our own js and css content via files.

**Comment by Slluxx** [comment]
Thats indeed an easy solution.

**Comment by jerrykuku** [comment]
I added two blank files in the following locations to fulfill the previously promised requirements. It will be in the upcoming v0.4.8 update.

/var/lib/casaos/www/css/custom.css
/var/lib/casaos/www/js/custom.js

**Comment by LinkLeong** [comment]
We have released 0.4.8 with a fix for this issue, thanks for your feedback!

**Comment by LinkLeong** [comment]
Thanks for your feedback, we will close this issue and reopen it if you have any questions.
