### ISSUE TITLE
Web page not loading

### ISSUE THREAD

**Issue by Tlicarek** [IceWhaleTech/CasaOS#1683]
**Describe the bug**

> I assigned the same port as casaos have to pterodactyl and they had a conflict. I shut down the pterodactyl but the casa is still not loading.-

**To Reproduce**

> Steps to reproduce the behavior:

1. Install Debian 12.4.0-amd64 distro, with only ssh server and standard system utilities.
2. sudo apt update and upgrade, and install curl
4. put local IP and port in the browser
5. Seeing error

**Expected behavior**

> Expected to load the page after me shutting down the pterodactyl

**Screenshots**

> 
![image](https://github.com/IceWhaleTech/CasaOS/assets/128289714/3b654bf5-0b7c-4028-b787-1eb9bed26f93)

**Desktop (please complete the following information):**

```
 - OS: Linux
 - Browser chrome,edge
 - Version 22
```

**System Time**

> Run `timedatectl` and share the output

![image](https://github.com/IceWhaleTech/CasaOS/assets/128289714/3539cb2a-a7a2-4cf1-9169-4aaede31812a)

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```
I don't know how to send you the logs, but they loaded.

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by NklsCh** [comment]
Have you considered changing the port of casaos to another?
`sudo nvim /etc/casaos/gateway.ini`
Change `port` to a port which is not used maybe 8080
Save and restart

Maybe this would help

**Comment by Tlicarek** [comment]
ok thanks i will trie


st 7. 2. 2024 o 10:55 Niklas Choinowski ***@***.***>
napísal(a):

**Comment by NklsCh** [comment]
Did it work?

**Comment by Tlicarek** [comment]
Thanks it did
________________________________
Od: Niklas Choinowski ***@***.***>
Odoslané: piatok 9. februára 2024 13:54
Komu: IceWhaleTech/CasaOS ***@***.***>
Kópia: Tlicarek ***@***.***>; Author ***@***.***>
Predmet: Re: [IceWhaleTech/CasaOS] Web page not loading (Issue #1683)


Did it work?

**Comment by NklsCh** [comment]
Then pls close this issue.
Pleasure to help ya
