### ISSUE TITLE
Network speed reported wrong on dashboard

### ISSUE THREAD

**Issue by tuzky** [IceWhaleTech/CasaOS#1684]
When downloading a large file from my NAS with SMB the network speed on the graph and in text format below it was wrongly reporting 286MB/s, while my network is 1Gbps... 286MB/s is 286*8 or 2.3Gbps, I could only wish my network and PC are 2.5Gbps interfaces ;-)

Reproduction is easy, download a large file on your own network and see for yourself...

The expected rate is what I could measure on my network switch that reported near line speed traffic on the port to my PC.

![Screenshot 2024-02-05 at 17 28 11](https://github.com/IceWhaleTech/CasaOS/assets/159049483/301e2697-3b1e-4f23-8fcb-9e3b297eb0b3)

![Screenshot 2024-02-05 at 16 37 01](https://github.com/IceWhaleTech/CasaOS/assets/159049483/ef44a1fe-87ff-40d5-b1f5-19d59df6196b)

 - OS: linux
 - CasaOS Version: 0.4.6
 - Disk Total: 100220 
 - Disk Used: 26927 
 - System Info: [Ubuntu 23.10   \l Bit:64 Mem:15776M Core:4 Linux n100dc-itx 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 9 17:03:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux]
 - Remote Version: 0.4.6
 - Browser: Firefox 
 - Version: 122.0

**Comment by LSP0123** [comment]
the same to #1673 @tigerinus

**Comment by jerrykuku** [comment]
Will fix this issue at next update.

**Comment by LinkLeong** [comment]
We have released 0.4.8 with a fix for this issue, thanks for your feedback!

**Comment by LinkLeong** [comment]
Thanks for your feedback, we will close this issue and reopen it if you have any questions.
