### ISSUE TITLE
rclone启动问题

### ISSUE THREAD

**Issue by thankforcat** [IceWhaleTech/CasaOS#1697]
原本我在使用改版的rclone,
但是当我安装CasaOS后, 被替换成了官方的rclone, 我原本rclone挂载的网盘都失效了.

**Comment by jerrykuku** [comment]
CasaOS的网盘挂载功能依赖于rclone,为了更好的对接rclone的api，我们必须使用指定版本。所以才会造成覆盖旧版本的问题。

**Comment by LinkLeong** [comment]
如有其他问题可重新打开,感谢你的反馈.
