### ISSUE TITLE
[Bug] Duplicate installs 

### ISSUE THREAD

**Issue by maam27** [IceWhaleTech/CasaOS#1703]
**Describe the bug**

Installing an app can seem to hang/silently crash, attempting to install again causes the install tile on the dashboard to jump between the 2 installs.

**To Reproduce**

1. try to install an app that takes some time to install
2. let it continue in the background
3. attempt to install again
4. send it to the background again
5. See the progress jump back and forth in the tile

**Expected behavior**

Expected would be one of the following:

1. A second tile if it is indeed a second install
2. Blocking of an install while it is already installing
3. Opening the existing install to show it's current progress

**Comment by CorrectRoadH** [comment]
fixed in https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/158
