### ISSUE TITLE
[Bug] Casaos install but isnt printing ip adress

### ISSUE THREAD

**Issue by Xterplot** [IceWhaleTech/CasaOS#1708]
**Describe the bug**

> I install the casa os but isnt display the ip adress

**Screenshots**

![20240224_215126.jpg](https://github.com/IceWhaleTech/CasaOS/assets/141823466/d11494c1-590d-4004-aa0a-a9a89bdd416a)

**Desktop (please complete the following information):**

```
 - OS: Linux debian 12
 - Browser isn't has browser its terminal only
 - Version 0.4.6
```

**System Time**

> 24.2.2024

**Logs**

> Run following command to collect corresponding logs:

Is in screenshots

**Comment by Tommato12** [comment]
Did you find how to fix this? I have the same issue.

**Comment by dragonfire1119** [comment]
> Did you find how to fix this? I have the same issue.

You can run this script: https://github.com/bigbeartechworld/big-bear-scripts/blob/master/find-your-casaos-ip-and-port/README.md
