### ISSUE TITLE
[Bug] 第一次安装后新建账号，无法进入系统提示“用户名或密码错误”

### ISSUE THREAD

**Issue by ohmyharry** [IceWhaleTech/CasaOS#1710]
设置账号密码后，无法进入系统

通过命令重置后也是如此
`rm /var/lib/casaos/db/user.db && systemctl restart casaos-user-service.service`

细节看图片
<img width="907" alt="截屏2024-02-25 16 29 24" src="https://github.com/IceWhaleTech/CasaOS/assets/1773352/16628d63-0a72-4aa5-bdcf-9430d9b4d9a2">
<img width="853" alt="截屏2024-02-25 16 29 48" src="https://github.com/IceWhaleTech/CasaOS/assets/1773352/8360667c-0649-408b-952c-93c63aff83f1">
<img width="751" alt="截屏2024-02-25 16 30 04" src="https://github.com/IceWhaleTech/CasaOS/assets/1773352/e11539c5-392a-4d45-8ece-565a65f10751">

环境是
CasaOS 0.4.6 on a Debian 11 LXC container in Proxmox 8.0.3

**Comment by CorrectRoadH** [comment]
提示“用户名或密码错误”还有一种可能就是尝试次数太多了，比如在一分钟尝试了5次登录，账号就会被锁。然后前端提示“用户名或密码错误”。这个是用来防暴力破解的🤔 你现在方便再试试吗?

**Comment by ohmyharry** [comment]
> 提示“用户名或密码错误”还有一种可能就是尝试次数太多了，比如在一分钟尝试了5次登录，账号就会被锁。然后前端提示“用户名或密码错误”。这个是用来防暴力破解的🤔 你现在方便再试试吗?

@CorrectRoadH 你好昨天的情况是，第一次登录就提示错误，距离16个小时后，也就是刚刚，重试了也是一样的提示

**Comment by CorrectRoadH** [comment]
> > 提示“用户名或密码错误”还有一种可能就是尝试次数太多了，比如在一分钟尝试了5次登录，账号就会被锁。然后前端提示“用户名或密码错误”。这个是用来防暴力破解的🤔 你现在方便再试试吗?
> 
> @CorrectRoadH 你好昨天的情况是，第一次登录就提示错误，距离16个小时后，也就是刚刚，重试了也是一样的提示

好的，我会马上定位一下问题，然后尝试快速修复一下。

**Comment by CorrectRoadH** [comment]
> > > 提示“用户名或密码错误”还有一种可能就是尝试次数太多了，比如在一分钟尝试了5次登录，账号就会被锁。然后前端提示“用户名或密码错误”。这个是用来防暴力破解的🤔 你现在方便再试试吗?
> > 
> > 
> > @CorrectRoadH 你好昨天的情况是，第一次登录就提示错误，距离16个小时后，也就是刚刚，重试了也是一样的提示
> 
> 您好，您是否方便使用控制台把您登录失败的请求的http code和结果给我截图一下吗?
> 
> 或者是否方便让我直接远程访问debug一下。比如可以留个邮箱方便联系一下。

有可能是user service服务挂了。一种解决方案是重启一下casaos所在的系统。

**Comment by ohmyharry** [comment]
> > > 提示“用户名或密码错误”还有一种可能就是尝试次数太多了，比如在一分钟尝试了5次登录，账号就会被锁。然后前端提示“用户名或密码错误”。这个是用来防暴力破解的🤔 你现在方便再试试吗?
> > 
> > 
> > @CorrectRoadH 你好昨天的情况是，第一次登录就提示错误，距离16个小时后，也就是刚刚，重试了也是一样的提示
> 
> 您好，您是否方便使用控制台把您登录失败的请求的http code和结果给我截图一下吗?
> 
> 或者是否方便让我直接远程访问debug一下。比如可以留个邮箱方便联系一下。

![image](https://github.com/IceWhaleTech/CasaOS/assets/1773352/fec9d613-109b-45bf-85d4-1a601088fdac)
是这个吗，你看下

另外`sudo systemctl restart casaos-user-service` 命令试了也是同样的错误

我的邮箱 ohmyharry@gmail.com

**Comment by topleo** [comment]
@ohmyharry 遇到一样的问题，请问是如何解决
