### ISSUE TITLE
[Bug]  12gb ram usage 

### ISSUE THREAD

**Issue by jarno9981** [IceWhaleTech/CasaOS#1729]
Latest CasaOs On Vmware 
uses 12gb almost full time how

only jellyfin and cloudflare installed

**Comment by mattish91** [comment]
Have you checked what containers are running and how much ram they use? you can do so by pressing the arrow in cpu/ram gauge and then select "ram" to see what applications are eating your ram. 

If you don't see it there, ssh in to your vm and run htop to find what process is eating all your ram. try restarting it or even kill it.

**Comment by jarno9981** [comment]
> Have you checked what containers are running and how much ram they use? you can do so by pressing the arrow in cpu/ram gauge and then select "ram" to see what applications are eating your ram. 
> 
> If you don't see it there, ssh in to your vm and run htop to find what process is eating all your ram. try restarting it or even kill it.

2,5gb each

**Comment by LinkLeong** [comment]
You can run `top` in the terminal to check the RAM occupied by casaos related programs.

**Comment by LinkLeong** [comment]
You can click... in the upper right corner to open settings
![image](https://github.com/IceWhaleTech/CasaOS/assets/13556972/44f05feb-4066-4b5f-bb9e-ddbbca6ac66f)

**Comment by jarno9981** [comment]
for me it does not show any log but how does it help my to find logo location

**Comment by LinkLeong** [comment]
These logs are the output of the program displayed in real time inside the container, and I'm not sure where the docker logs for jellyfin are located. But you can stop jellyfin or casaos to locate the ram occupied by that application.

**Comment by jarno9981** [comment]
> These logs are the output of the program displayed in real time inside the container, and I'm not sure where the docker logs for jellyfin are located. But you can stop jellyfin or casaos to locate the ram occupied by that application.

👍
