### ISSUE TITLE
About the webui port change

### ISSUE THREAD

**Issue by Gendmyb** [IceWhaleTech/CasaOS#1735]
version:Casaos-v0.4.7
Server version:Ubuntu server 22.04LTS
Web server：NGINX/1.18.0
issue:When changing the webui access port in the webpage settings, there will be a warning if the target port is occupied. But after closing the window, the backend binding port behavior does not pause. At the same time, in the (/etc/casaos/gateway.ini) file, you can find that the original port number will be changed to the one that is already occupied. This will result in the inability to access the webui page after restarting the Casaos service.
Frequency: Always

**Comment by LinkLeong** [comment]
We have released 0.4.8 with a fix for this issue, thanks for your feedback!

**Comment by LinkLeong** [comment]
Thanks for your feedback, we will close this issue and reopen it if you have any questions.
