### ISSUE TITLE
[Bug] CasaOS unresponsive when trying to view files uploaded to the device

### ISSUE THREAD

**Issue by jonps97** [IceWhaleTech/CasaOS#1746]
**Describe the bug**
After uploading a mixture of around pictures and videos (around 10GB or 2500 files) to my CasaOS device, the web interface becomes unresponsive when trying to access and view the files, it seems that I cannot do anything until all files have loaded their "preview" image. Trying to open any pictures before all "preview" images are loaded is nearly impossible, and I have not been able to view any video files uploaded to the folder.
> A clear and concise description of what the bug is.

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to 'Files'
2. Navigate to Folder containing files
3. Open said Folder
4. Wait for an undefined amount of time or get a 

**Expected behavior**
Web interface should not freeze, should be able to scro
> A clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: [Ubuntu 22.04.4 LTS x86_64 ]
 - Browser [Brave Browser]
 - Version [v1.64.109]
```

**CasaOS system HW info**

```
OS: Ubuntu 22.04.4 LTS x86_64 
Host: NUC11TNKi7 M11911-404 
Kernel: 6.5.0-26-generic 
Uptime: 1 day, 2 hours, 4 mins 
Packages: 1796 (dpkg), 11 (snap) 
Shell: bash 5.1.16 
Terminal: /dev/pts/0 
CPU: 11th Gen Intel i7-1165G7 (8) @ 4.700GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 1267MiB / 15609MiB
```

**System Time**

> Run `timedatectl` and share the output

```
Local time: lø. 2024-03-23 13:40:34 CET
Universal time: lø. 2024-03-23 12:40:34 UTC
RTC time: lø. 2024-03-23 12:40:34
Time zone: Europe/Oslo (CET, +0100)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by jonps97** [comment]
Forgot to add, running CasaOS version 0.4.7

**Comment by malykhinvi** [comment]
@jonps97 I had the same issue. Hopefully with the fix above the UI will be able to render bigger lists of files
