### ISSUE TITLE
Big [Bug] on qbittorrent or casa itself

### ISSUE THREAD

**Issue by prashantdwivedi** [IceWhaleTech/CasaOS#1748]
**Describe the bug**
Install fresh Caso OS on Raspberry Pi, then attempt to login to qBittorrent. Default login information fails with "unauthorized login" error message.
After installing casa OS four times and qbittorrent, I encountered the same issue.

**Comment by blixten85** [comment]
You need to do 5 things.

1. Shutdown qBittorrent in the casaos GUI
2. open /DATA/AppData/qbittorrent/config/config/qBittorrent.conf
3. add WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
4. start qBittorrent from the casaOS GUI
5. after open qbittorrent, append a trailing / to the end of the adress. i.e http://192.168.50.71:8181/

And the developers should really attend to this asap. It's such an incompetense that they let this hang around like it would be nothing.

**Comment by prashantdwivedi** [comment]
> You need to do 5 things.
> 
> 1. Shutdown qBittorrent in the casaos GUI
> 2. open /DATA/AppData/qbittorrent/config/config/qBittorrent.conf
> 3. add WebUI\Password_PBKDF2="@bytearray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
> 4. start qBittorrent from the casaOS GUI
> 5. after open qbittorrent, append a trailing / to the end of the adress. i.e http://192.168.50.71:8181/
> 
> And the developers should really attend to this asap. It's such an incompetense that they let this hang around like it would be nothing.

I follow your step but still not work
<img width="382" alt="CleanShot 2024-03-27 at 22 15 00@2x" src="https://github.com/IceWhaleTech/CasaOS/assets/6306052/14e83484-92d3-4f75-a3bc-13b48d3c51e9">

**Comment by prashantdwivedi** [comment]
I tried, Hard luck :(

**Comment by blixten85** [comment]
Ok, then i don't know. I left this CasaOS for installation on bare metall through [Swizzin](https://swizzin.ltd/)
And i'm running rTorrent with RuTorrent instead.

**Comment by prashantdwivedi** [comment]
Why do they do it `random password change` anyways thanks, @LSP0123, 🙏🏻

**Comment by slb116763814** [comment]
@LSP0123 
Could you help me?
Why i am download file log always prompt "error: Permission denied", if i don't change the Default Save Path in qBittorrent then can downloading.
![111](https://github.com/IceWhaleTech/CasaOS/assets/27171588/1b647f78-5427-4149-a9c1-6aff2d001d10)
![222](https://github.com/IceWhaleTech/CasaOS/assets/27171588/6415adc1-ffe2-4cbe-ab3e-67f1df49b6b7)
![333](https://github.com/IceWhaleTech/CasaOS/assets/27171588/6d1fcd9f-86e4-42d8-b7b9-618065d679cd)
![444](https://github.com/IceWhaleTech/CasaOS/assets/27171588/f4167395-592a-4f81-a0a7-a1a25758d391)

**Comment by slb116763814** [comment]
@LSP0123 
I tryed it  and follow your steps do again , same issue.
![666](https://github.com/IceWhaleTech/CasaOS/assets/27171588/6b3685e9-a46f-4408-bc75-f6d34821d049)

**Comment by slb116763814** [comment]
yes, running qbittorrent from casaos store.i think the same issue with [https://github.com/IceWhaleTech/CasaOS/issues/1758](url)

![777](https://github.com/IceWhaleTech/CasaOS/assets/27171588/f73e285a-a2d1-4792-b69d-394509fd34f5)
![888](https://github.com/IceWhaleTech/CasaOS/assets/27171588/f2d46e72-a59c-47e5-8b52-fd30582cdb0f)
![999](https://github.com/IceWhaleTech/CasaOS/assets/27171588/1086fc86-6b1f-44ad-b217-218f7b31b850)

**Comment by slb116763814** [comment]
@LSP0123 
It's ready to download now, but I don't think it's download on disk yet.

![1111](https://github.com/IceWhaleTech/CasaOS/assets/27171588/83ffccf8-5fd9-472f-8b94-342267949555)

**Comment by hopiumdust** [comment]
How did you solved? 
I have similar problem, I don't want to change the mount location, please someone can help me.
<img width="814" alt="Screenshot 2024-07-19 at 12 06 37" src="https://github.com/user-attachments/assets/3f3f0a57-3d0a-444f-8d7c-73b44c6e71e5">
<img width="660" alt="Screenshot 2024-07-19 at 12 03 29" src="https://github.com/user-attachments/assets/591c5737-14d4-4c4a-ab31-aa91b9084e4f">
