### ISSUE TITLE
[Bug]  { "message": "store app not found" }

### ISSUE THREAD

**Issue by onlineapps-cloud** [IceWhaleTech/CasaOS#1751]
**Describe the bug**
hi, i cannot Install a customized app, i get error:
![image](https://github.com/IceWhaleTech/CasaOS/assets/69077240/99cd88b5-9958-4c45-99fb-cceca9573bdb)
```
 - OS: [ubuntu 22.04]
 - Browser [firefox]
 -casaos version [ v0.4.8 ]
```

**System Time**

> Run `timedatectl` and share the output

```
timedatectl
               Local time: Tue 2024-03-26 09:47:28 UTC
           Universal time: Tue 2024-03-26 09:47:28 UTC
                 RTC time: Tue 2024-03-26 09:47:28
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

```

**Logs**

> Run following command to collect corresponding logs:

which exactly logs i need to provide?

**Comment by bibucar** [comment]
I also encountered this problem after updating

**Comment by Jefeix** [comment]
:stable or other only :latest

**Comment by Dankni95** [comment]
so we cant pin to custom versions anymore?

**Comment by AdrianChandra** [comment]
Same here, cannot update apps settings 

![storeappnotfound](https://github.com/IceWhaleTech/CasaOS/assets/38415103/025c6aa7-1e68-44bf-8a95-ad92fb1c6bed)

and cannot even install custom app

![messagestoreappnotfound](https://github.com/IceWhaleTech/CasaOS/assets/38415103/a2ae6aab-fa4d-495c-85f8-8699b428c8ef)

**Comment by hqnicolas** [comment]
@ghulamzainulabideen  @smartineindra @onlineapps-cloud 

Just run the Old Casaos!!!!
############################
wget -qO- https://get.casaos.io/v0.4.7 | sudo bash
################################

**Comment by bepp-boop** [comment]
yea it is also happend on Tailscale as well no longer work for 
https://icewhale.community/t/using-tailscale-to-remotely-access-casaos/278

**Comment by mirhen2023** [comment]
@AdrianChandra "adding linuxserver.io in app store" worked for me also.
Thank you very much for your help

**Comment by CorrectRoadH** [comment]
Very thanks for your feedback. The issue has fixed in https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/180 . and CasaOS 0.4.9 has released.
