### ISSUE TITLE
Crafty - cant Update from Version 4.3.0 to Version 4.3.2 [Bug] 

### ISSUE THREAD

**Issue by sotomonk** [IceWhaleTech/CasaOS#1777]
**Describe the bug**

> Hi, the problem is, that i cant Update Crafty from Version 4.3.0 to Version 4.3.2 cause it always say that it is already "up to date"

**To Reproduce**

> --

**Expected behavior**

> Just need to be Updateable 

**Screenshots**

> Thats the Info when you try to update from Version 4.3.0
![image](https://github.com/IceWhaleTech/CasaOS/assets/166325387/2053fc0e-2ddd-4da9-a308-914c13dac885)

**Desktop (please complete the following information):**

```
 - OS: linux
 - CasaOS Version: 0.4.8
 - System Info: [Debian GNU/Linux 12]
 - Browser: Opera 
 - Version: 108
```

**System Time**

> --

**Logs**

> --

**Additional context**

> --

**Comment by SashaRyder** [comment]
You probably have your app set to 4.3.0. Just change that to latest or 4.3.2 and it'll update.
