### ISSUE TITLE
网页Terminal按下ESC便会关闭，会与vi/vim编写程序冲突

### ISSUE THREAD

**Issue by tpishere** [IceWhaleTech/CasaOS#18]
**Describe the bug**
网页Terminal按下ESC便会关闭，会与vi/vim编写程序冲突，导致无法保存文本的修改内容。

**To Reproduce**
1. 打开CasaOS的web网页
2. 点击左上角的Terminal
3. 登录后使用命令`vi test`，随意输入部分内容
4. 点击ESC按钮，Terminal直接退出，第三步的test文本未被保存

**Expected behavior**
希望取消ESC关闭Terminal的功能。

**Desktop (please complete the following information):**
 - OS: [Armbian]
 - Browser [Edge Chromium]
 - Version [0.1.8]

**Comment by LinkLeong** [comment]
我们已经注意到了这个问题,会在最近一次的更新里解决该问题.

**Comment by LinkLeong** [comment]
@tpishere 已修复
