### ISSUE TITLE
CasaOS is not reachable

### ISSUE THREAD

**Issue by LyRooy** [IceWhaleTech/CasaOS#1813]
So i need to turn off/on my router because i have connection problems and now i can't connect to CasaOS this is what healthcheck script shows

![image](https://github.com/IceWhaleTech/CasaOS/assets/79991153/5d3cbdb6-6533-4ea7-b6fa-74efbfaad005)

When i trying to connect via browser i get error "ERR_CONNETION_REFUSED"
also sudo casaos not working properly

**Comment by ianmaicon** [comment]
I'm having the same issue

**Comment by LyRooy** [comment]
This might be not best fix but definitely the fastest. I use BigBearTechWorld script again but this time for reinstall casaos but i keep files and containers. Now everything working fine. 

> I'm having a similar issue

**Comment by ianmaicon** [comment]
What script? I have a lot of files on it

**Comment by dragonfire1119** [comment]
@ianmaicon Here is the video for reinstalling: https://youtu.be/3M_fQGAuzkc I'm glad it's helping people!

**Comment by ianmaicon** [comment]
Will this remove all my containers?
Please say not

**Comment by LyRooy** [comment]
> Will this remove all my containers? Please say not
If you type N then they i 2 and 3 step istead of Y then they stay
