### ISSUE TITLE
go: finding module for package github.com/IceWhaleTech/CasaOS/codegen go: finding module for package github.com/IceWhaleTech/CasaOS/codegen/message_bus go: github.com/IceWhaleTech/CasaOS/cmd/message-bus-docgen imports 	github.com/IceWhaleTech/CasaOS/codegen/message_bus: no matching versions for query "latest" go: github.com/IceWhaleTech/CasaOS/route imports 	github.com/IceWhaleTech/CasaOS/codegen: no matching versions for query "latest"[Bug] 

### ISSUE THREAD

**Issue by fykcy** [IceWhaleTech/CasaOS#1843]
go: finding module for package github.com/IceWhaleTech/CasaOS/codegen
go: finding module for package github.com/IceWhaleTech/CasaOS/codegen/message_bus
go: github.com/IceWhaleTech/CasaOS/cmd/message-bus-docgen imports
	github.com/IceWhaleTech/CasaOS/codegen/message_bus: no matching versions for query "latest"
go: github.com/IceWhaleTech/CasaOS/route imports
	github.com/IceWhaleTech/CasaOS/codegen: no matching versions for query "latest"

This bag can't be pulled down. What's going on and how can we solve it

**Comment by Ns2Kracy** [comment]
Please refer to #1847
