### ISSUE TITLE
problem with dragging shortcuts on touchscreen

### ISSUE THREAD

**Issue by maksimbian** [IceWhaleTech/CasaOS#185]
On test version 0.3.1 it is not possible to use it on the phone, because when scrolling, the shortcuts are dragged, you need to either drag and drop on a long tap, or fixing shortcuts in settings

**Comment by jerrykuku** [comment]
Will check this issue soon.

**Comment by jerrykuku** [comment]
This problem has been fixed in v0.3.1, the current mobile version still needs to be optimized, so temporarily block the sorting function on the mobile side to ensure normal use. Improvements will be made in the future.
