### ISSUE TITLE
[Bug] 安装了新版本后所有app都无法安装

### ISSUE THREAD

**Issue by asheng2587** [IceWhaleTech/CasaOS#1861]
如题，更新完之后无法安装app
报错信息：error pulling image configuration: download failed after attempts=6: dial tcp 108.160.169.55:443: i/o timeout

**Comment by Mahoo12138** [comment]
可能跟 docker 镜像源无法使用有关？可尝试着给 docker 配置代理

**Comment by CorrectRoadH** [comment]
duplicated https://github.com/IceWhaleTech/CasaOS/issues/1864
网络问题，Docker Hub被墙了。与CasaOS本身无关

**Comment by jiehanhk** [comment]
> duplicated #1864 网络问题，Docker Hub被墙了。与CasaOS本身无关

有解決方案嗎?
