### ISSUE TITLE
[Bug] certificate expired for get.casaos.io?

### ISSUE THREAD

**Issue by juliosene** [IceWhaleTech/CasaOS#1895]
Hi!

I`m trying to install CasaOS, however curl refuses to connect to get.casaos.io because the certificate has expired. 

```
# curl -fsSL https://get.casaos.io | sudo bash
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

<img width="554" alt="getcasaos" src="https://github.com/IceWhaleTech/CasaOS/assets/2068562/787d158c-5d7c-4433-af40-d36cbeec2a5e">

**Comment by crnobog69** [comment]
Same error, I got it on Debian 12 just 15 min ago

**Comment by felpsfpp** [comment]
same error, ubuntu server 24 3 min ago

**Comment by felpsfpp** [comment]
here that worked for me
Step 1: wget https://downloads.rclone.org/v1.61.1/rclone-v1.61.1-linux-amd64.deb
Step 2: sudo dpkg -i rclone-v1.61.1-linux-arm64.deb
Step 3: curl -fsSL -k http://get.casaos.io/ | sudo bash

**Comment by juliosene** [comment]
Sounds that everthing is back to normal. 

<img width="563" alt="getcasaos-ok" src="https://github.com/IceWhaleTech/CasaOS/assets/2068562/772ea757-2ab6-4a1b-a902-4d44facde260">
