### ISSUE TITLE
Importing Existing Docker Apps destroy that app

### ISSUE THREAD

**Issue by CosmoFox** [IceWhaleTech/CasaOS#193]
**Describe the bug**
When U importing Existing Docker Apps it`s destroy that app. As example - i had 2 apps - Portainer and Gitlab (Gitlab was created in manual way via CasaOS 0.3.0). After update to 0.3.1 - both apps drops to initial default - so.. gitlab repo destroyed, portainer config destroyed. **crying smile**

**To Reproduce**
As described upper

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - chrome 101
 - Version CasaOS 0.3.1

**Comment by LinkLeong** [comment]
Can you provide the addresses of ducher Hubs for these two applications

**Comment by CosmoFox** [comment]
gitlab/gitlab-ce:latest
portainer/portainer-ce

**Comment by LinkLeong** [comment]
We are aware of the seriousness of this issue, so we have made an emergency update. Sorry for the previous error, you can manually change the mount address to the previous one to fix the problem.  https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.3.1.1

**Comment by CosmoFox** [comment]
Amazing lightning fast reaction. Bless U. Will test it now.

**Comment by CosmoFox** [comment]
Tested. Work as expected.
