### ISSUE TITLE
Add Manual option to the port selection drop down menu

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#195]
### Discussed in https://github.com/IceWhaleTech/CasaOS/discussions/194

<div type='discussions-op-text'>

<sup>Originally posted by **AuthorShin** May 16, 2022</sup>
Hello
Can you please add manual option to the port drop down menu so we can add and adjust one without need to have it in port section.
like this:
<img src="https://i.ibb.co/FXBChg7/Screenshot-2022-05-16-223814.png" alt="Add Manual option to the port selection drop down menu in casaOS"></div>

**Comment by JohnGuan** [comment]
Discussed in https://github.com/IceWhaleTech/CasaOS/discussions/194
