### ISSUE TITLE
Extra informations on already installed app on casaOS after update

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#196]
**Describe the bug**

After updating from 0.3 to 0.3.1 existing apps (the ones that was installed via casaOS) are having extra information and field compare to the last version.

**Expected behavior**

Only show the necessary field and data.

**Screenshots**

Before:
Nginx Proxy Manager
<img src="https://i.ibb.co/PWfzYW1/gdfgdfg928.png" alt="Nginx Proxy Manager casaOS">
Portainer
<img src="https://i.ibb.co/Tb9pdys/56g654g654g9.png" alt="Portainer casaOS">
Komga
<img src="https://i.ibb.co/kypjmVM/kiniubg78g7801.png" alt="Komga casaOS">

After:
Nginx Proxy Manager
<img src="https://i.ibb.co/5WGJCHm/5f541g5df1g04.png" alt="Nginx Proxy Manager casaOS">
Portainer
<img src="https://i.ibb.co/fnkKrsh/454g45b454720.png" alt="Portainer casaOS">
Komga
<img src="https://i.ibb.co/ncn74JZ/Screenshot-2022-05-16-224828.png" alt="Komga casaOS">

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser: Firefox
 - Version: 96

**Comment by LinkLeong** [comment]
We have reconstructed the application management, and now the environment variable information is completely read from the Docker container. After the container is started, some environment variables may be added by itself. This is normal and we won't deal with it for the time being. Thanks for the feedback
