### ISSUE TITLE
[Bug] Cannot access the try casaos

### ISSUE THREAD

**Issue by Romeo-debugger** [IceWhaleTech/CasaOS#1968]
If I try to click try CasaOS in the CasaOS website it does not work.

It redirects to some random website.

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to 'casaos.io'
2. Click on 'live demo'
3. See error

**Expected behavior**

> A CasaOS demo page

**Comment by QXIoa** [comment]
I have the same issue.
