### ISSUE TITLE
Plex Won't Install

### ISSUE THREAD

**Issue by CrimznX1** [IceWhaleTech/CasaOS#1972]
**Describe the bug**

> Error response from daemon: could not select device driver "" with capabilities: [[gpu]]

**To Reproduce**

>  1. Go to apps
     2. Click Plex
     3. Install
     4. shows error message

**Expected behavior**

> Prior to 8/22, everything would install and setup just fine.

**Screenshots**

> What is shown.
<img width="1038" alt="Casa Screenshot showing error" src="https://github.com/user-attachments/assets/8a72d856-dda7-441b-9e94-c47f3313111a">

> What i did to fix
<img width="704" alt="Casa Screenshot showing fix" src="https://github.com/user-attachments/assets/5f1adf50-c1c5-4b42-af2b-eaaddcad5d55">
<img width="324" alt="Casa Screenshot showing fix2" src="https://github.com/user-attachments/assets/116caa7d-351f-49cc-a9d0-84fd57862d0f">
<img width="992" alt="Casa Screenshot showing complete install" src="https://github.com/user-attachments/assets/fe910965-b094-409a-956c-db45cfb94883">

**Comment by MessiasLima** [comment]
I'm facing the same issue

**Comment by CrimznX1** [comment]
I did a another clean install today, and default pull and install from app store seem's to be working fine now. Make sure Casaos is also up to date, mine was at the time.

**Comment by DouglasMacKrell** [comment]
Still facing the same bug.
Currently running CasaOS 0.4.11
I've tried both CasaOS's specific version of Plex - and plex:latest

**Comment by DouglasMacKrell** [comment]
Deeper dive in Portainer shows that one of the two devices was not applied `/dev/dvb` 
After adding the missing device, I now see this error:

![Screenshot 2024-08-24 at 10 17 48 PM](https://github.com/user-attachments/assets/be21132c-e0d0-431c-97e9-a324ac391bae)

**Comment by DouglasMacKrell** [comment]
Sure enough, the `/dev/dvb` folder is no longer there. Could something have been accidentally removed in the recent 0.4.11 update?
![Screenshot 2024-08-24 at 10 22 58 PM](https://github.com/user-attachments/assets/150cff8c-644a-4021-a0cb-1487d155f04e)

**Comment by DouglasMacKrell** [comment]
### OVERVIEW
Circling back one last time - looks like the UI updater doesn't work quite right, and removes some of the GPU files and paths. However, following [THIS TUTORIAL](https://youtu.be/3M_fQGAuzkc?si=haxU3bt5TZcDGh2m) on youtube, and [USING THEIR SCRIPT](https://github.com/bigbeartechworld/big-bear-scripts/tree/master/reinstall-casaos) I was able to get a clean install of CasaOS 0.4.11 - and that has the missing files and Plex will once again install correctly from the app store.

### STEPS TAKEN TO FIX

1. ssh into your device (mine was a Zimaboard) from an external terminal on your network (exe: your laptop on the same wifi). The command should be something like: `ssh casaos@[YOUR-DEVICE-IP-HERE]`
2. Next, we need to run as root, then run a one-line script that uninstalls CasaOS and reinstalls. To do this, C/P and run the following two commands separately and in order:
```
sudo su

bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/reinstall-casaos/run.sh)"
```
3. This will walk you through a few questions, and if you want a clean install agree to everything by pressing `Y` at each step. 
4. When the script completes it will tell you the IP and the URL you can reach the CasaOS UI from (it should be the exact same one you used before if this is a reinstall)
5. Complete the same CasaOS setup steps of creating a username/password
6. Install Plex from the app store - and it should work as expected.

Bit of a nuclear option, but it gets everything up and running again.
