### ISSUE TITLE
[Feature request] - Disk management

### ISSUE THREAD

**Issue by Fredo-Ronan** [IceWhaleTech/CasaOS#1989]
**Is your feature request related to a problem? Please describe.**
I tried installing custom app through the import docker-compose.yaml file feature but it fails on the way of downloading some dependencies and take a lot of storage in my sdcard, i just want a way to find the kind of temp files that already downloaded when the installation was in progress

**Describe the solution you'd like**
I would like the ability to access the sdcard in root privilege or sort of disk management feature on windows system to see easily what is the thing that taking up so much space on storage and delete it safely without damaging the other main filesystem

**Describe alternatives you've considered**
I tried using the native file manager that CasaOS has and change the view to list in order to see the file size, but the size doesn't appear if the file is in the root OS system

**Additional context**
- My CasaOS installation is on top of Armbian Linux system (Armbian_21.08.1_Amlogic-GXL_bullseye_current_5.10.60)

Here you can see the main storage is taking up space to 7 GB of 14GB total storage capacity
![image](https://github.com/user-attachments/assets/e29a82a2-21e1-4fd4-9d3f-58be2d779cb4)

And here you can see the thing that taking up so much space is the /dev/mmcb1k2
![image](https://github.com/user-attachments/assets/55da224a-11d8-4355-96df-67be599e0d40)

But on the file browser, the size indicator says 0 bytes
![image](https://github.com/user-attachments/assets/176cc073-3d05-437e-af66-22182a44a891)

**Comment by georgerappel** [comment]
I thi k you are misunderstanding some things here.

That path /dev/mmcblk1p2 is the filesystem path of the mountpoint "/", as you see ok the first screen, which is your OS root path. This is where all of your operating system files are. If you do anything to that file or the root path, you might end up with a corrupted OS. I don't know why it has 0bytes, maybe it's a symlink, but it's outside of my knowledge how all that works under the hood.

I wouldn't change the size of it either, as if you limit the size of this partition you could end up with more problems, unable to boot, unable to update dependencies or the OS, unable to install more software etc.

I highly suggest you learn how the mount points and the filesystem paths for them work before trying to do anything with system files manually.

If you need to free disk space, maybe try command line commands to clear cache of downloaded apps, or just leave it alone while you learn your way through Linux.

**Comment by lincooln** [comment]
возможно имеет смысл добавить кнопку уборки в меню настроек casaos. эта кнопка запускала бы скрипт очистки старых и неиспользуемых контейнеров docker и старых системных журналов.
возможно casaos делает это фоном. тогда кнопка просто запускала бы этот механизм по запросу. мне кажется это разумным для домашнего использования.
