### ISSUE TITLE
[Alpha][Bug] 更新casaos后，旧应用程序导入重建不了，没有反应

### ISSUE THREAD

**Issue by macrokk** [IceWhaleTech/CasaOS#2008]
### What happened?

更新casaos后，旧应用程序导入重建不了，没有反应

### Screenshots

更新casaos后，旧应用程序导入重建不了，没有反应

**Comment by DigitalElise** [comment]
I am also experiencing the same issue in v0.4.13

**Comment by orchia2000** [comment]
新安装的，也是旧应用程序没有处理按钮。

**Comment by kenhuan** [comment]
添加第三方应用市场显示已添加实际没添加

**Comment by orchia2000** [comment]
旧应用程序待重建，点击导入到casaOS没反应

**Comment by chisenin** [comment]
同样现象，已安装的docker项目显示待重建，但点击没有任何反应，但项目本身运行正常

**Comment by caishanli** [comment]
同样现象，已安装的docker项目显示待重建，但点击没有任何反应，但项目本身运行正常

**Comment by Ancvor** [comment]
me too!

**Comment by zhangqiang-routon** [comment]
有解决方案吗？

**Comment by finvv** [comment]
Same for me, new install v0.4.13, can't import old app, no response

**Comment by maaayz87** [comment]
same. In v0.4.13

**Comment by scckele** [comment]
我也是差不多同样的问题
[Bug] 使用docker run命令创建的应用无法导入casa
[现象]使用docker run命令创建的应用，在casa首页点击导入没有反应。
[系统信息] 
-设备：玩客云
- OS: linux
 - CasaOS Version: 0.4.13
 - Disk Total: 7035 
 - Disk Used: 2068 
 - System Info: [Armbian 24.11.1 bullseye \l Bit:32 Mem:988M Core:4 Linux onecloud 6.6.43-current-meson #1 SMP Sat Jul 27 09:34:11 UTC 2024 armv7l GNU/Linux ]
 - Remote Version: 0.4.13
 - Browser: Chrome 
 - Version: 116.0.5845.97

**Comment by maaayz87** [comment]
您好，我最近正在xxx中，无法亲自回复您的邮件。我将在xx结束后，尽快给您回复。

**Comment by Ns2Kracy** [comment]
will be fixed next version

**Comment by Ns2Kracy** [comment]
fixed in 0.4.14
