### ISSUE TITLE
Harddrive does not sleep/hibernate even it is set so

### ISSUE THREAD

**Issue by WorldCore** [IceWhaleTech/CasaOS#202]
ubuntu22.04硬盘设置休眠后一直读取无法休眠

**Comment by jerrykuku** [comment]
We will check and improve this issue, thank you for your feedback.

**Comment by LinkLeong** [comment]
I tested the problem in version 0.3.2.1 and it did not appear, if you still have the problem, please provide the system version, screenshots of settings and hard drive information

![Image](https://user-images.githubusercontent.com/13556972/174541248-e624cd00-2c32-42cc-a8d0-f7560d6d9bf2.png)
![Image](https://user-images.githubusercontent.com/13556972/174541249-1d9dd852-7b8f-41ee-b6b3-8a727fe5d197.png)
![Image](https://user-images.githubusercontent.com/13556972/174541250-368a14ca-8eeb-4c06-b6a1-452c7e515c69.png)
![Image](https://user-images.githubusercontent.com/13556972/174541251-023f7d31-c364-4db2-b68b-515b15cc3d3f.png)

**Comment by LinkLeong** [comment]
Thank you for your feedback, we have solved the problem in v0.3.3, I will close the problem, if you have questions, please open a new issue
