### ISSUE TITLE
I'm not sure whether this is an issue but i dont have Syncthing installed and somehow Syncthing is using my ram and CPU on CasaOS Dashboard

### ISSUE THREAD

**Issue by MitasTech** [IceWhaleTech/CasaOS#203]

**Comment by CosmoFox** [comment]
approving that problem. After update to 0.3.1 Syncthing removed from installed apps. But container still here. If i`m delete this container - it will back after reboot. And not showing in CasaOS.

**Comment by CosmoFox** [comment]
@Lauren-ED209 i`m attaching screenshots. As i said earlier: If i`m delete this container - it will back after reboot.
![image](https://user-images.githubusercontent.com/9054349/169805557-7ef139f2-f047-458d-8cf7-781bb7107ce1.png)
![image](https://user-images.githubusercontent.com/9054349/169805611-99945995-7a95-4013-b701-ef0d5f32c995.png)
![image](https://user-images.githubusercontent.com/9054349/169805689-02b0d9f1-b441-4ab2-81d3-da019d10a2d7.png)

**Comment by CosmoFox** [comment]
If install syncthing from store, it`s make new instance
![image](https://user-images.githubusercontent.com/9054349/169806601-f7151df1-73d1-4f4f-9d22-36d4cd885bf5.png)

**Comment by JVTEAM** [comment]
I never installed Syncthing and I noticed that container is running.

**Comment by Lauren-ED209** [comment]
We are working on this issue! Will fix in next 2 release. (It involves the development progress of the overall function and the redesign of related modules.)

**Comment by Lauren-ED209** [comment]
We have added this issue to the development plan. So, close this issue. I will keep updating here.
