### ISSUE TITLE
http\https proto

### ISSUE THREAD

**Issue by CosmoFox** [IceWhaleTech/CasaOS#204]
**Describe the bug**
Some apps has own WebUI, who works via https proto. Example on screenshot. UI of that app must work on https.
![image](https://user-images.githubusercontent.com/9054349/168928250-43d18df5-ef8b-42e9-b623-44c9e6325949.png)

So. Let us choose proto for external WebUI like a port choosing now.

**Desktop:**
 - OS: Any
 - Browser Any
 - Version CasaOS 0.3.0 - 0.3.1.1

**Comment by LinkLeong** [comment]
We have added this feature in [v0.3.2](https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.3.2)
