### ISSUE TITLE
今天更新后无法访问web管理页面，docker应用运行正常

### ISSUE THREAD

**Issue by zkhaoo** [IceWhaleTech/CasaOS#206]
如题

**Comment by LinkLeong** [comment]
systemctl status casaos 运行正常吗

**Comment by JohnGuan** [comment]
Please use English to re-edit the question according to the Issue template.
请使用英文重新根据Issue模板编辑问题。也可以加我微信：guanningchuan，我们通过微信进行中文沟通。
