### ISSUE TITLE
[Bug] Add Onedrive in Files

### ISSUE THREAD

**Issue by Zaros67** [IceWhaleTech/CasaOS#2067]
**Describe the bug**

I am trying to add Onedrive but there is only this text and onedrive doesn´t show up
but i have this :

"<p>Just close the page</p><script>window.close()</script>" and no onedrive files

**To Reproduce**

Try to add onedrive in Files

1. Go to 'Files'
2. Click on 'location'
3. Scroll down to 'connect onedrive'

**Screenshots**

![photo_2024-11-27_18-17-26](https://github.com/user-attachments/assets/66d0131e-b6c3-492f-a907-f521e83f68cd)

**Comment by WordWireUK** [comment]
Also have this.

**Comment by australiascripts** [comment]
same

**Comment by Ns2Kracy** [comment]
will be fixed at v0.4.15

**Comment by australiascripts** [comment]
> will be fixed at v0.4.15

when is that due to be released? Same response with Google Drive also fyi

**Comment by Ns2Kracy** [comment]
> > will be fixed at v0.4.15
> 
> when is that due to be released? Same response with Google Drive also fyi

Soon, just this week.

**Comment by Ns2Kracy** [comment]
v0.4.15 has released

**Comment by australiascripts** [comment]
Hello, thanks for the update, Google drive works fine, but there is an issue streaming and opening files file the file app on onedrive. Just hangs.
