### ISSUE TITLE
Scroll bar is missing after update to v0.4.14. I cannot see all the app I installed without zooming out the browser window

### ISSUE THREAD

**Issue by mudithaliyanagama** [IceWhaleTech/CasaOS#2088]
System information

 - OS: linux
 - CasaOS Version: 0.4.14
 - Disk Total: 27712 
 - Disk Used: 26269 
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7789M Core:4 Linux CasaOS 5.10.0-33-amd64 #1 SMP Debian 5.10.226-1 (2024-10-03) x86_64 GNU/Linux ]
 - Remote Version: 0.4.14
 - Browser: Firefox 
 - Version: 133.0

After update, once I logged in I cannot scroll the window and see all the apps I installed in server.  Only 3 rows of apps are fully available. 4th row you cannot see without zooming down the browser window.  Also tested with firefox on android and google chrome on both desktop and android. Having same issue. Kindly fix this issue. Thank you

![image](https://github.com/user-attachments/assets/30b2864a-46ea-4947-8ecf-33239c652c41)

**Comment by Hussienfahmy** [comment]
> scroll

Can we solve it from our side?

**Comment by jerrykuku** [comment]
Will fix it as soon as possible. Thanks for the report.

**Comment by Hussienfahmy** [comment]
Appreciate your quick assistance but I can't install the update.

```
hussien@server:~$ curl -fsSL https://get.casaos.io/update/v0.4.14 | bash
   _____                 ____   _____
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___
 | |    / _` / __|/ _` | |  | |\___ \
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/
   --- Made by IceWhale with YOU ---
[sudo] password for hussien:
- OK Your hardware architecture is : x86_64
Hit:1 http://eg.archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://eg.archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://eg.archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:4 https://pkgs.netbird.io/debian stable InRelease
Hit:5 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:6 https://download.docker.com/linux/ubuntu noble InRelease
Get:7 https://pkgs.tailscale.com/stable/ubuntu noble InRelease
Hit:8 https://apt.repos.intel.com/openvino/2024 ubuntu24 InRelease
Fetched 6,578 B in 1s (4,493 B/s)
Reading package lists... Done
W: https://apt.repos.intel.com/openvino/2024/dists/ubuntu24/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
- INFO Configuration CasaOS Addons
main: line 419: pushd: /tmp/casaos-installer/tmp.GHlO0wOYQ6: Permission denied
```

**Comment by Hussienfahmy** [comment]
Running the command after switching to root user working fine.
Scrolling is working now

**Comment by mudithaliyanagama** [comment]
@jerrykuku 
Thank you very much for the quick reply and fix. It worked.
