### ISSUE TITLE
Code Editor show codes in Center Align format after new update

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#210]
After update 0.3 Code Editor show codes in Center Align format.
<img src="https://i.ibb.co/tJsczMn/Screenshot-2022-05-19-160502.png" alt="Code Editor show codes in Center Align format.">

**Comment by jerrykuku** [comment]
Yes, it will be fixed in the next update.

**Comment by tigerinus** [comment]
Verified this is fixed in the upcoming release
