### ISSUE TITLE
[Bug] cant add onedrive

### ISSUE THREAD

**Issue by Filipko2468** [IceWhaleTech/CasaOS#2107]
**Describe the bug**

> Onedrive dont show up after connection

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to 'Files'
2. Click on 'connect onedrive'
3. Scroll down to 'autenticate'

**Expected behavior**

> onedrive shoud show up

**Desktop (please complete the following information):**

```
 - OS: [Linux]
 - Browser [chrome]
 - Version [0.4.15]
```

**Comment by Filipko2468** [comment]
other connections works exept onedrive

**Comment by Ns2Kracy** [comment]
Sorry about this, but it can be solved by typing `sudo rclone config` on the command line and then deleting all the onedrive configs and reconnecting them in the files

**Comment by Filipko2468** [comment]
> Sorry about this, but it can be solved by typing `sudo rclone config` on the command line and then deleting all the onedrive configs and reconnecting them in the files

it disappeared as soon as i restarted the server
