### ISSUE TITLE
systemctl status casaos 运行正常吗

### ISSUE THREAD

**Issue by zkhaoo** [IceWhaleTech/CasaOS#213]
systemctl status casaos 运行正常吗

_Originally posted by @LinkLeong in https://github.com/IceWhaleTech/CasaOS/issues/206#issuecomment-1129737470_

**Comment by zkhaoo** [comment]
root@DietPi:~# systemctl status
● DietPi
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2022-05-18 07:49:49 BST; 1 day 22h ago
   CGroup: /
           ├─init.scope 
           │ └─1 /sbin/init
           └─system.slice 
             ├─docker-eae26c9eec53ccb5767c966f399b938c911caccbcbddbcd7791a7bbe20eaafe6.scope …
             │ ├─    860 /bin/bash ./docker/docker-entrypoint.sh
             │ ├─   1659 PM2 v5.2.0: God Daemon (/root/.pm2)
             │ ├─   1675 nginx: master process nginx -c /etc/nginx/nginx.conf
             │ ├─   1676 nginx: worker process
             │ ├─   1677 nginx: worker process
             │ ├─   1678 nginx: worker process
             │ ├─   1679 nginx: worker process
             │ ├─   1723 node /ql/static/build/public.js
             │ ├─   1762 node /ql/static/build/app.js
             │ ├─   1823 crond -f
             │ ├─1096342 node /ql/static/build/schedule.js
             │ ├─1639658 bash /usr/local/bin/task raw_8_ckck2.sh
             │ ├─1640026 timeout -k 10s 12h bash raw_8_ckck2.sh
             │ ├─1640027 bash raw_8_ckck2.sh
             │ ├─1650451 bash /usr/local/bin/task okyyds_yydspure_master/jd_cfd_loop.js
             │ ├─1651113 timeout -k 10s 12h node jd_cfd_loop.js
             │ ├─1651118 node jd_cfd_loop.js
             │ ├─1655851 bash raw_8_ckck2.sh
             │ ├─1655852 bash raw_8_ckck2.sh
             │ ├─1655853 bash raw_8_ckck2.sh
             │ ├─1655854 awk /pin=jd_dpnegpDmyJUY; {print NR}
             │ ├─1655855 bash raw_8_ckck2.sh
             │ ├─1655856 jq .[].value
             │ ├─1655857 tr -d [],"
             │ ├─1655866 curl -s --noproxy * http://0.0.0.0:5600/api/envs?searchValue=JD_WSCK -H Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoib1FUeDFaa0ZKNWFveWVvenRBMzR1el80V2Vmd2l1X19waTJiLW96SVdmYjRqN3I4cVRha3dGeHBEdTFxZFN1VWNoIiwiaWF0IjoxNjUyOTY5MTk0LCJleHAiOjE2NTMyMjgzOTR9.9A3wtUGvFQHDByZGtPDgpd98CjgSGultp38KnuEuei1odBNlRJEmyDKY7w44dFEE
             │ └─1655867 jq .data
             ├─haveged.service 
             │ └─264 /usr/sbin/haveged --Foreground --verbose=1
             ├─containerd.service …
             │ ├─    484 /usr/bin/containerd
             │ ├─    774 /usr/bin/containerd-shim-runc-v2 -namespace moby -id eae26c9eec53ccb5767c966f399b938c911caccbcbddbcd7791a7bbe20eaafe6 -address /run/containerd/containerd.sock
             │ ├─    905 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 048c02c02d2afebfe0a4a26b60e6afa1efdbb36ab86f32cfa579e795db4244ed -address /run/containerd/containerd.sock
             │ └─1116259 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 03ab588eaedc07a4fca1339ac583440194bf713e6be0b85a00faab8886c71a78 -address /run/containerd/containerd.sock
             ├─systemd-udevd.service 
             │ └─228 /lib/systemd/systemd-udevd
             ├─cron.service 
             │ └─1621 /usr/sbin/cron -f
             ├─docker.service …
             │ ├─    494 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
             │ ├─    680 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 22000 -container-ip 172.17.0.3 -container-port 22000
             │ ├─    686 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 22000 -container-ip 172.17.0.3 -container-port 22000
             │ ├─    703 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5700 -container-ip 172.17.0.4 -container-port 5700
             │ ├─    710 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 5700 -container-ip 172.17.0.4 -container-port 5700
             │ ├─    750 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 22000 -container-ip 172.17.0.3 -container-port 22000
             │ ├─    756 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 22000 -container-ip 172.17.0.3 -container-port 22000
             │ ├─    813 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 21027 -container-ip 172.17.0.3 -container-port 21027
             │ ├─    820 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 21027 -container-ip 172.17.0.3 -container-port 21027
             │ ├─    867 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8384 -container-ip 172.17.0.3 -container-port 8384
             │ ├─    874 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 8384 -container-ip 172.17.0.3 -container-port 8384
             │ ├─1115955 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 8853 -container-ip 172.17.0.2 -container-port 8853
             │ ├─1115963 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 8853 -container-ip 172.17.0.2 -container-port 8853
             │ ├─1115976 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5443 -container-ip 172.17.0.2 -container-port 5443
             │ ├─1115984 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 5443 -container-ip 172.17.0.2 -container-port 5443
             │ ├─1116000 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 5443 -container-ip 172.17.0.2 -container-port 5443
             │ ├─1116007 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 5443 -container-ip 172.17.0.2 -container-port 5443
             │ ├─1116021 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3000 -container-ip 172.17.0.2 -container-port 3000
             │ ├─1116029 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 3000 -container-ip 172.17.0.2 -container-port 3000
             │ ├─1116043 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 853 -container-ip 172.17.0.2 -container-port 853
             │ ├─1116051 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 853 -container-ip 172.17.0.2 -container-port 853
             │ ├─1116065 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 853 -container-ip 172.17.0.2 -container-port 853
             │ ├─1116072 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 853 -container-ip 172.17.0.2 -container-port 853
             │ ├─1116086 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 784 -container-ip 172.17.0.2 -container-port 784
             │ ├─1116093 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 784 -container-ip 172.17.0.2 -container-port 784
             │ ├─1116107 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 443 -container-ip 172.17.0.2 -container-port 443
             │ ├─1116113 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 443 -container-ip 172.17.0.2 -container-port 443
             │ ├─1116130 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 443 -container-ip 172.17.0.2 -container-port 443
             │ ├─1116137 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 443 -container-ip 172.17.0.2 -container-port 443
             │ ├─1116151 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.17.0.2 -container-port 80
             │ ├─1116157 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 8080 -container-ip 172.17.0.2 -container-port 80
             │ ├─1116173 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 6868 -container-ip 172.17.0.2 -container-port 68
             │ ├─1116181 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 6868 -container-ip 172.17.0.2 -container-port 68
             │ ├─1116195 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 67 -container-ip 172.17.0.2 -container-port 67
             │ ├─1116201 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 67 -container-ip 172.17.0.2 -container-port 67
             │ ├─1116215 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 53 -container-ip 172.17.0.2 -container-port 53
             │ ├─1116223 /usr/bin/docker-proxy -proto tcp -host-ip :: -host-port 53 -container-ip 172.17.0.2 -container-port 53
             │ ├─1116236 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 53 -container-ip 172.17.0.2 -container-port 53
             │ └─1116244 /usr/bin/docker-proxy -proto udp -host-ip :: -host-port 53 -container-ip 172.17.0.2 -container-port 53
             ├─docker-03ab588eaedc07a4fca1339ac583440194bf713e6be0b85a00faab8886c71a78.scope …
             │ └─1116279 /opt/adguardhome/AdGuardHome --no-check-update -c /opt/adguardhome/conf/AdGuardHome.yaml -h 0.0.0.0 -w /opt/adguardhome/work
             ├─systemd-journald.service 
             │ └─215 /lib/systemd/systemd-journald
             ├─docker-048c02c02d2afebfe0a4a26b60e6afa1efdbb36ab86f32cfa579e795db4244ed.scope …
             │ ├─ 964 s6-svscan -t0 /var/run/s6/services
             │ ├─1281 s6-supervise s6-fdholderd
             │ ├─1585 s6-supervise syncthing
             │ ├─1588 syncthing -home=/config -no-browser -no-restart --gui-address=0.0.0.0:8384
             │ └─1648 syncthing -home=/config -no-browser -no-restart --gui-address=0.0.0.0:8384
             ├─smartmontools.service 
             │ └─320 /usr/sbin/smartd -n
             ├─casaos.service 
             │ └─316 /usr/local/bin/casaos -c /casaOS/server/conf/conf.ini
             ├─dbus.service 
             │ └─317 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
             ├─system-getty.slice 
             │ └─getty@tty1.service 
             │   └─483 /sbin/agetty -o -p -- \u --noclear tty1 linux
             ├─ifup@eth0.service 
             │ └─372 /sbin/dhclient -4 -v -i -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0
             └─dropbear.service 
               ├─    332 /usr/sbin/dropbear -p 22 -W 65536
               ├─1587438 /usr/sbin/dropbear -p 22 -W 65536
               ├─1587443 -bash
               ├─1587489 -bash
               ├─1587517 /usr/sbin/dropbear -p 22 -W 65536
               ├─1587660 top
               ├─1655843 bash -c export LANG="en_US";export LANGUAGE="en_US";export LC_ALL="en_US";free;echo finalshell_separator;uptime;echo finalshell_separator;cat /proc/net/dev;echo finalshell_separator;df;echo finalshell_separator;sleep 1;free;echo finalshell_separator;uptime;echo finalshell_separator;cat /proc/net/dev;echo finalshell_separator;df;echo finalshell_separator;
               ├─1655865 ps -HewO lstart ex
               ├─1655868 systemctl status
               ├─1655869 (pager)
               └─1655870 bash -c export LANG="en_US";export LANGUAGE="en_US";export LC_ALL="en_US";free;echo finalshell_separator;uptime;echo finalshell_separator;cat /proc/net/dev;echo finalshell_separator;df;echo finalshell_separator;sleep 1;free;echo finalshell_separator;uptime;echo finalshell_separator;cat /proc/net/dev;echo finalshell_separator;df;echo finalshell_separator;



这样算正常吗？本人小白一个

**Comment by JohnGuan** [comment]
Let's continue the discussion in the original Issue.
在原来的Issue里继续讨论吧。
