### ISSUE TITLE
After Update 3.1.1 CasaOS interface freezes

### ISSUE THREAD

**Issue by JVTEAM** [IceWhaleTech/CasaOS#214]
**Describe the bug**
After a certain amount of time the casaOS.local site no longer functions.  External drive details dissapear and the ram and cpu no longer changes.  The containers continue to function, however if you refresh the page they all dissapear except the file apps.  It also stopped my expressvpn connection.

**To Reproduce**
1. Update to 3.1.1
2. go to casaOS.local
3. wait for a few hours
4. page no longer functions

**Expected behavior**
CasaOS landing page should function normally at all times.

**Desktop (please complete the following information):**
 - OS: CasaOS 
 - Browser Chrome
 - Version 3.1.1

**Additional context**
Worked perfectly up until the 3.1.0 and 3.1.1 update.

**Comment by LinkLeong** [comment]
You can execute `docker ps -a` first to see how it works, we have simulated the situation you said, there is no problem as you said, so you need to provide more information

**Comment by JVTEAM** [comment]
Ok, in terms of running containers. I had radarr, sonarr, jacket and transmission running as well as a command line instance of expressvpn.  I have a usb hard drive connected to the device.  I would say after about 3-4 hours of running is when the casos.local screen stops responding and the hard drive disappears.  This happened after the 3.0.0 update initially eliminated my usb drive and wouldn't reconnect until I physically unplugged it and replugged it in.  This has occured 3 or 4 times since the last update.  I've since had it unplugged since it can't be trusted to be on.

**Comment by JVTEAM** [comment]
Plugged it back in and sometime overnight it happened again.  Here's the screenshot.  You can see my usb drive is gone and the other drive turned red while everything else froze.

![image](https://user-images.githubusercontent.com/20096471/170237718-d13856e1-966e-425e-bf6c-fa0d929ecf84.png)

**Comment by LinkLeong** [comment]
Thank you very much for your feedback, this issue is very important to us, we have found this phenomenon, and are working on the problem, will be solved in the next version.

**Comment by AuthorShin** [comment]
Same problem here multiple freezing lagging and very very slow response although the setup is local.

**Comment by AuthorShin** [comment]
CPU: 0%
RAM: 7%
DISK: 90% free

**Comment by Lauren-ED209** [comment]
I have completed the testing of this bug on 0.3.2 (the internal test environment). Confirmed that the issue is fixed.
