### ISSUE TITLE
BUG: Wireless traffic 

### ISSUE THREAD

**Issue by Protektor-Desura** [IceWhaleTech/CasaOS#222]
When I select the wireless interface in the web page it is not showing anything for traffic, even though the interface ID is correct.

The server host is Ubuntu 20.04.4 LTS with all the latest patches applied.

**Comment by JohnGuan** [comment]
Have you tried rebooting the machine and CasaOS?

**Comment by LinkLeong** [comment]
@JVTEAM This is a bug, we have fixed it.
@Protektor-Desura @JVTEAM  
We found a situation where the wireless card was not getting traffic even though the wireless card charts were working fine. We found that this is a linux system level issue, so we are not dealing with this phenomenon for now (refer to the [link](https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt) ). If you have other questions, please keep asking. Thanks for your feedback!

**Comment by Protektor-Desura** [comment]
I have no idea what you fixed in 0.3.2 but it is monitoring wireless traffic now, at least for me.
