### ISSUE TITLE
Network Status chart data goes negative

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#224]
Hello
On the Network Status chart data goes negative.
<img src="https://i.ibb.co/1vdb992/2.png" alt="Network Status chart data goes negative 1">
<img src="https://i.ibb.co/Q9sB57d/246.png" alt="Network Status chart data goes negative 2">

**Comment by LinkLeong** [comment]
We have fixed this issue in [v0.3.2](https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.3.2)
