### ISSUE TITLE
不能提交设备ID

### ISSUE THREAD

**Issue by baolaimi** [IceWhaleTech/CasaOS#226]
**Describe the bug**

不能提交设备ID。不能完成配置

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.1.1
	 - Disk Total: 6595 
	 - Disk Used: 1578 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 0
	 - System Info: [Armbian 20.12 Buster \l Bit:32 Mem:989M Core:4 Linux aml-s812 5.9.0-rc7-aml-s812 #20.12 SMP Sun Dec 13 22:50:05 CST 2020 armv7l GNU/Linux]
	 - Browser: Chrome 
	 - Version: 86.0.4240.198

**Comment by tigerinus** [comment]
dup #68

**Comment by JohnGuan** [comment]
It's already been discussed in #68 
你也可以加我微信：guanningchuan，我们可以在微信里进行中文讨论。
