### ISSUE TITLE
在线查看文本文件默认居中而不是左对齐

### ISSUE THREAD

**Issue by kkjoy** [IceWhaleTech/CasaOS#231]
更新v0.3.1.1后 在线文件浏览文本的时候默认是居中对齐，且无法改变

**Comment by JohnGuan** [comment]
Duplicated. https://github.com/IceWhaleTech/CasaOS/issues/210
该问题重复了，已确定会在下个版本中解决。你可以加我微信：guanningchuan，我们在微信中用中文进行交流。
