### ISSUE TITLE
图标显示成了通用图标

### ISSUE THREAD

**Issue by cs0663c** [IceWhaleTech/CasaOS#232]
升级3.1.1后docker 图标显示成了通用图标，刷新重启都无效，难道是网络问题？

![image](https://user-images.githubusercontent.com/59052041/170849571-398f50b6-c35c-4164-985a-bf353ee485e2.png)

 - OS: linux
 - CasaOS Version: 0.3.1.1
 - Disk Total: 18014 
 - Disk Used: 5966 
 - Sync State: Sync img: true
sha256:3e86dd0e8a0bcab7e40dc68a77fe00f331a1e9c63971a703c22b1ddf499a5ce1,
Sync Key length: 0
 - System Info: [Debian GNU/Linux 10   \l Bit:64 Mem:3921M Core:4 Linux debian 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux]
 - Browser: Edge 
 - Version: 101.0.1210.53

**Comment by JohnGuan** [comment]
It looks like a network problem.
看起来是网络问题，你有试过开代理吗？因为我这里看是正常的，你可以加我微信：guanningchuan，我们在微信里用中文交流。

**Comment by JohnGuan** [comment]
After a long time without new information, I closed this issue.
