### ISSUE TITLE
back or close buttons

### ISSUE THREAD

**Issue by devrob20** [IceWhaleTech/CasaOS#235]
**Describe the bug**

great, but there are no back or close buttons ? if you open terminal or file manager you need to reload the page to get out ? which is real slow btw

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.1.1
	 - Disk Total: 80444 
	 - Disk Used: 5249 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 0
	 - System Info: [Debian GNU/Linux 10   \l Bit:64 Mem:3946M Core:2 Linux ip-172-26-3-133 4.19.0-20-cloud-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 102.0.0.0

**Comment by JohnGuan** [comment]
I see that these buttons you mentioned are normal.
Or am I missing your point?

![Image](https://user-images.githubusercontent.com/3358477/171546261-ab9146e7-53c1-465f-aea7-5529155888a7.png)

![Image](https://user-images.githubusercontent.com/3358477/171546312-b85cbc47-dce5-47f4-ba4f-469820887c0e.png)

![Image](https://user-images.githubusercontent.com/3358477/171546392-10e6f421-aa7b-4d52-bd9e-6869f69d7801.png)

**Comment by JohnGuan** [comment]
I think the dark mode of UI should be a feature to be discussed.
The same goes for shortcuts. But is this shortcut key out of your personal preference or is there some software? Ctrl+X obviously overlaps with the Cut shortcut key.

Could you be starting these two discussions?

**Comment by devrob20** [comment]
yeah Crtl something that wont interfere or let it set by user to any combo they want

done and done

 :) 

https://github.com/IceWhaleTech/CasaOS/discussions/248
https://github.com/IceWhaleTech/CasaOS/issues/249
