### ISSUE TITLE
Files app doesn't save the downloads with the right name.

### ISSUE THREAD

**Issue by Bira-oliverio** [IceWhaleTech/CasaOS#240]
**Describe the bug**

All files to be downloaded have the same name "download" not the original name.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.1.1
	 - Disk Total: 937291 
	 - Disk Used: 56583 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 0
	 - System Info: [Ubuntu 22.04 LTS   \l Bit:64 Mem:15908M Core:8 Linux ubiratan-Macmini 5.15.0-33-generic #34-Ubuntu SMP Wed May 18 13:34:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 101.0.4951.61

**Comment by jerrykuku** [comment]
Thanks for the feedback, this issue is being fixed and will be updated in the next version.

**Comment by LinkLeong** [comment]
We have fixed this issue in [v0.3.2](https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.3.2)
