### ISSUE TITLE
[performance] CasaOS UI loading time can be slow when accessing from remote

### ISSUE THREAD

**Issue by tigerinus** [IceWhaleTech/CasaOS#242]
**Describe the bug**

When accessing CasaOS from a different place remotely, the loading time can be slow.

**To Reproduce**

1. Switch to mobile data
2. Enable Network view in browser inspector tool
3. Connect to CasaOS UI via VPN

**Expected behavior**
The biggest JS should be just few hundred kilobytes.

**Screenshots**
![image](https://user-images.githubusercontent.com/7172560/171085622-0d2016ce-47a2-4aef-a2f8-2b444e1d7a20.png)

- The same 1.2MB JS file got transfered 3 times.

**Additional context**

Biggest JS of popular sites (potentially more complicated than CasaOS UI):

- Google Map  553kB
- Outlook.com 508kB

**Comment by MitasTech** [comment]
i dont have a problem at all to be honest, i'm currently in another country and i can access my home server without any issues with great speed, just like it was when i was back home.  i'm using Zerotier to connect to the server

**Comment by Lauren-ED209** [comment]
> i dont have a problem at all to be honest, i'm currently in another country and i can access my home server without any issues with great speed, just like it was when i was back home. i'm using Zerotier to connect to the server

thanks for your feedback. I'm using Tailscale with CasaOS remotely. Have similar issue. Remote accessibility is really important for CasaOS. However, for recently Sprint plan, we are focusing on the storage management, compatibility and dashboard customization features, like hiding module and change wallpaper as community suggested. 

I will drive to improve the accessbility ASAP!

**Comment by LinkLeong** [comment]
We have optimized this issue in [v0.3.2](https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.3.2)
