### ISSUE TITLE
Enhancement: Install/uninstall scripts

### ISSUE THREAD

**Issue by JohnGuan** [IceWhaleTech/CasaOS#243]
**Is your feature request related to a problem? Please describe.**

[Abhinav Kulshreshtha](https://www.youtube.com/channel/UC_1h0CFkP55yfqaqOaCA-Eg)‘s comment in this [video](https://www.youtube.com/watch?v=lyNVPxHiVyE).
> Just a warning to all users like me who doesn't mind running bash script directly because they trust and assume that devs are good and smart people, The installation and uninstallation script is really badly written. There is no check if dependencies are installed or not, and it forcefully reinstall all dependencies like curl, parted etc. Discord is full of complaint on this. there is also typo in hostname command. During uninstall, there is whole lot of docker command missing arguments errors,  and this time also, it doesn't check for dependencies and cause bash errors on whiptail.

**Describe the solution you'd like**

1. Detects dependencies and does not reinstall them
2. Fix these errors mentioned

**Comment by LinkLeong** [comment]
Thank you for your feedback, we have solved the problem in v0.3.3, I will close the problem, if you have questions, please open a new issue
