### ISSUE TITLE
BUG: Web SSH client doesn't allow login

### ISSUE THREAD

**Issue by Protektor-Desura** [IceWhaleTech/CasaOS#244]
I am not able to ssh in and login to the server using the web interface. I get the following error after my login and password.

ssh: handshake failed: read tcp 127.0.0.1:26790->127.0.0.1:22: read: connection reset by peer

The server host OS is Ubuntu 20.04.4 LTS and all the updates have been applied.
Still getting the same error on v0.3.1.1 when I try and SSH in the server from the web interface.

login:protektor
password:
ssh: handshake failed: read tcp 127.0.0.1:35742->127.0.0.1:22: read: connection reset by peer
login:

Can you do ssh -v and paste the verbose information here?
No because it isn't a problem with the server or SSH daemon.

I can use Putty from the same machine as running the web client and it works no problem. I am using Chrome Version 101.0.4951.67 (Official Build) (64-bit) on Windows. Firefox 100.0.2 (64-bit) is doing the same exact thing.

The problem is not the SSH daemon, but the what ever the client is in the web interface. As I have said I have no problem getting to the server with other SSH clients, just not the web interface.

**Comment by Protektor-Desura** [comment]
I got 

Jun 03 01:10:15 archon sshd[4050448]: Accepted password for protektor from 192.168.50.110 port 58387 ssh2
Jun 03 01:10:15 archon sshd[4050448]: pam_unix(sshd:session): session opened for user protektor by (uid=0)
Jun 03 02:08:24 archon sshd[4050448]: pam_unix(sshd:session): session closed for user protektor
Jun 03 03:11:30 archon sshd[90701]: Accepted password for protektor from 192.168.50.110 port 60261 ssh2
Jun 03 03:11:30 archon sshd[90701]: pam_unix(sshd:session): session opened for user protektor by (uid=0)
Jun 03 03:14:33 archon sshd[105706]: refused connect from 127.0.0.1 (127.0.0.1)

-- Logs begin at Thu 2022-06-02 07:45:24 CDT, end at Fri 2022-06-03 03:15:51 CDT. --
Jun 03 01:10:15 archon sshd[4050448]: Accepted password for protektor from 192.168.50.110 port 58387 ssh2
Jun 03 01:10:15 archon sshd[4050448]: pam_unix(sshd:session): session opened for user protektor by (uid=0)
Jun 03 02:08:24 archon sshd[4050448]: pam_unix(sshd:session): session closed for user protektor
Jun 03 03:11:30 archon sshd[90701]: Accepted password for protektor from 192.168.50.110 port 60261 ssh2
Jun 03 03:11:30 archon sshd[90701]: pam_unix(sshd:session): session opened for user protektor by (uid=0)
Jun 03 03:14:33 archon sshd[105706]: refused connect from 127.0.0.1 (127.0.0.1)

**Comment by tigerinus** [comment]
All of the sessions, regardless of close or reject, has a duration longer than instantaneous.

E.g. this session gets refused after 2min since it's opened.

    Jun 03 03:11:30 archon sshd[90701]: pam_unix(sshd:session): session opened for user protektor by (uid=0)
    Jun 03 03:14:33 archon sshd[105706]: refused connect from 127.0.0.1 (127.0.0.1)

When u login from the web ssh, does it gives a delay before the error?

**Comment by Protektor-Desura** [comment]
No. I give my login and password then it responds with the error in under a second or two tops.

login:protektor
password:
ssh: handshake failed: read tcp 127.0.0.1:35742->127.0.0.1:22: read: connection reset by peer
login:

**Comment by Protektor-Desura** [comment]
I wonder if the web interface is being relayed through CasaOS web daemon which is why it thinks it is connecting from local (127.0.0.1) instead of showing the real IP of the browser.

**Comment by tigerinus** [comment]
You are correct. SSH is relayed thru WebSocket when accessing from UI.

Do you happen to have a firewall rule that blocks accessing SSH from the same host?
