### ISSUE TITLE
Appstore stuck on loading.

### ISSUE THREAD

**Issue by NLTheaumas** [IceWhaleTech/CasaOS#245]
**Describe the bug**
When I click the blue button to open the appstore, there's a circle going round. It keeps going without seeing any apps.

**To Reproduce**
1. Go to homepage
2. Click on 'App store'

**Expected behavior**
The App store to open, to download and install apps.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [CasaOS]
 - Browser [chrome]
 - Version [n/a]

**Additional context**

**Comment by JohnGuan** [comment]
@NLTheaumas Our initial thought is that it may be a network issue, can you tell us your CasaOS version and where you are located?

**Comment by NLTheaumas** [comment]
I'm on version v0.3.1.1 and I'm located in the Netherlands.

**Comment by NLTheaumas** [comment]
If it helps, when I try downloading qbittorrent manually using docker cli, I get the following error:
"Error response from daemon: Get "https://lscr.io/v2/": dial tcp 18.193.247.98:443: connect: no route to host"

I've used below cli:
docker run -d \
  --name=qbittorrent \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e WEBUI_PORT=8080 \
  -p 8080:8080 \
  -p 6881:6881 \
  -p 6881:6881/udp \
  -v /path/to/appdata/config:/config \
  -v /path/to/downloads:/downloads \
  --restart unless-stopped \
  lscr.io/linuxserver/qbittorrent:latest

**Comment by JohnGuan** [comment]
Can you take a look at your network and firewall settings?
Because I checked the App Store's API server and lscr.io's server and found that they are both running normally.
One thing they have in common is that they are both using AWS services.

**Comment by JohnGuan** [comment]
It looks like the gateway was set up incorrectly and has been fixed in Discord.
https://discord.com/channels/884667213326463016/943513030497558598/981262856798470235

I'll close this issue, if there are still problem feel free to submit a new issue.
