### ISSUE TITLE
Update and app store won't load.

### ISSUE THREAD

**Issue by Tijn4481** [IceWhaleTech/CasaOS#254]
**Describe the bug**
It notes an update to v0.3.0 is available, however this never gets performed, even after running it all night. Aside of this the app store won't open either and all apps previously installed that weren't pre-installed have been removed.
![image](https://user-images.githubusercontent.com/51416698/172211128-1f921d25-ec18-49ad-83d3-f2a53f313f55.png)
![image](https://user-images.githubusercontent.com/51416698/172211150-470924ec-9d91-4326-a5f6-5385f5f7b1d2.png)

**Comment by JohnGuan** [comment]
You can try using a reboot of the machine or CasaOS service and then upgrade.
`systemctl restart casaos.service`

**Comment by Tijn4481** [comment]
I've tried this, as well as rebooting it manually by removing its power, but it doesn't improve the situation.

**Comment by JohnGuan** [comment]
Now the version has been upgraded to v0.3.1.1, can you upgrade to the latest version?

**Comment by moravel** [comment]
Hi, for me, the same , the app store don't load :(
I'm in the v0.3.1.1 version on an ubuntu serveur 22.04

**Comment by moravel** [comment]
in my syslog :+1: 
Jun  9 11:08:06 SERVEURNAME casaos[3753]: Get "https://api.casaos.io/casaos-api/v2/app/category": EOF

Hope it could help

**Comment by Tijn4481** [comment]
My casaos doesn't mention a v0.3.1.1 being available.

**Comment by moravel** [comment]
Ok , I 've find the issue .
For me, in my network I have a subnet in 172.17.40.0/24 or docker use the subnet 172.17.0.0/16
then I 'va just  to change the subnet use by docker .
To do the change in ubuntu server :

Edit /lib/systemd/system/docker.service before start Docker. Add --bip "192.168.1.1/24" at the end of line ExecStart=/usr/bin/dockerd.
systemctl daemon-reload
systemctl start docker

source=> https://stackoverflow.com/questions/52225493/change-default-docker0-bridge-ip-address

**Comment by Tijn4481** [comment]
This worked! Thanks a lot! Any idea where it went wrong?

**Comment by Tijn4481** [comment]
Weird, don't know how that would have happened. This btw didn't solve my update problem.
