### ISSUE TITLE
Multiuser support in the WebUI

### ISSUE THREAD

**Issue by MatusModder** [IceWhaleTech/CasaOS#258]
**Is your feature request related to a problem? Please describe.**
This feature is related to my problem where I want someone else to use selfhosted apps and that others can't see the apps that I want to see

**Describe the solution you'd like**
Settings -> App visibility and Settings -> Add user  

**Describe alternatives you've considered**
I tried pulling Flame dashboard from docker hub and setting it up to be some apps visible (Nextcloud, Jellyfin) and others to be visible only to me (pihole, cockpit)
**Additional context**
It can also utilize adduser command.

**Comment by Lauren-ED209** [comment]
We've been talking about the user permissions system. However, in the short term, our focus will still be on the existing application center, storage and UI customizable function iterations!
However, please believe that multi-account is the core difference between a family cloud and a personal cloud, and we will definitely develop this function in future versions.
If you are interested, please continue to follow our latest developments in the discord group. ;)

**Comment by MatusModder** [comment]
Ok.

**Comment by Lauren-ED209** [comment]
I will close this issue for now. But, no doubt that we will follow up on the design of account system.
If possible, I'd like to invite you to the definition of the feature, when we kicking-off this thread.
