### ISSUE TITLE
Wrong default transmission app password

### ISSUE THREAD

**Issue by Lauren-ED209** [IceWhaleTech/CasaOS#260]
**Describe the bug**

The default password of transmission in notification is "casaos". However, when launching once installed, I can't login properly. 
After checking docker configuration, you will find the default password is "CasaOs"...

**To Reproduce**
1. Go to App Store
2. Install transmission
3. login with casaos / casaos
4. failed to login / error

**Screenshots**
<img width="622" alt="0nzD6GwstQ" src="https://user-images.githubusercontent.com/8243355/172425122-8116bf71-db04-4940-869d-87e8290127eb.png">

**Comment by TheHelloDev** [comment]
Hi there!
I believe this issue should be opened in IceWhaleTech/CasaOS-AppStore as that is where the appfiles are stored.
But anyway, I believe I have found the source of the error, and will make a pull request soon.
Thank you for opening an issue.

**Comment by TheHelloDev** [comment]
I have opened a pull request, which hopefully fixes this.
You can find it [here](https://github.com/IceWhaleTech/CasaOS-AppStore/pull/3).

**Comment by LinkLeong** [comment]
@Lauren-ED209 thanks for the feedback
@TheHelloDev Thank you for your collaboration in revising
Thank you for your support
