### ISSUE TITLE
Option to use storage of external drive for apps

### ISSUE THREAD

**Issue by TheHelloDev** [IceWhaleTech/CasaOS#265]
**I am constantly running out of storage on my micro SD cards, and this would be an appreciated feature.**
As described above, apps are currently allocated space on the micro SD card on which storage is tight, this annoys me. Say, for example, we want to install Nextcloud/Photoprism. Once setup is done **from the app store**, storage on the micro SD card is used for photos or files which you have uploaded. Now, while you could probably set this up manually, it's simply inconvenient.

**The ability to specify where volumes should be from the app store**
Either a pop-up, or an option below the install button, to select volumes.

No alternatives have been considered

**Additional context**
This feature is found in Umbrel, which I switched away from because of its crypto relation.

**Comment by Lauren-ED209** [comment]
It's perfectly right time for this request! We are in the process of sorting out the requirements for storage optimization!
I will be responsible for driving the team's discussion on this feature optimization.

And update here ASAP!

**Comment by Lauren-ED209** [comment]
We have decomposed this request into two function requirements:
1. Docker application migration - solve the problem of application space occupation
2. Docker application data migration - solve the directory configuration problem of application data

The application migration plan has been investigated and will be released in the next 2-3 versions. 
The app data migration plan is still under discussion, and I will organize and determine the feasibility as soon as possible! 

Considering that this is a feature request, and we've converted this request to development tasks. So I close this issue. 
Please feel free to post your concern or idea here still!
