### ISSUE TITLE
Terminal for Apps is not working

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#266]
Hello
Terminal is not working for any of my Apps.
<img src="https://i.ibb.co/LYmkBCh/Screenshot-2022-06-08-225057.png" alt="CasaOS Terminal is not working for any of the Apps">

**Comment by JohnGuan** [comment]
Is the terminal not available for all Apps?

**Comment by JohnGuan** [comment]
Is your WebUI port modified? Will it work properly if you use 80 as the WebUI port?

**Comment by AuthorShin** [comment]
Yes, my Web GUI port is modified.
Unfortunately, because I have other apps and services that are running and using port 80, I cannot confirm if using port 80 for casaOS would fix the terminal or not.

**Comment by LinkLeong** [comment]
Thank you for your feedback.We have fixed this issue in the latest version, you can upgrade to solve the problem
