### ISSUE TITLE
Select all in Apps logs is selecting everything

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#267]
Hello
In the Logs tab of the Apps, when using select all, it will select everything on the casaOS page. When the expected behavior is by pressing select all, it just selects all the logs "just logs", nothing more.

**Comment by jerrykuku** [comment]
Yes, this is a bug, we will fix this and release it in v0.3.2.

**Comment by jerrykuku** [comment]
This issue has been fixed in V0.3.2. I will close it, if the problem still exists, you can reopen it and discuss it.
