### ISSUE TITLE
Can't install CasaOS

### ISSUE THREAD

**Issue by samosaman73** [IceWhaleTech/CasaOS#270]
When executing the install script, (`curl -fsSL https://get.icewhale.io/casaos.sh | bash`) I am given the following error:
```
[ INFO ] https://github.com/IceWhaleTech/CasaOS/releases/download/v0.3.1.1/linux-arm-6-casaos.tar.gz
curl: (22) The requested URL returned error: 404
[FAILED] error 22 in command: ${net_getter} "$casa_url" > "$PREFIX/tmp/$casa_file"
```

**Comment by Hedius** [comment]
Your device is not supported.

Arm6 is not a supported architecture.

Only arm7, arm64, amd64

**Comment by Hedius** [comment]
What would be good here is that the install script would throw an exception for that.

**Comment by samosaman73** [comment]
What Raspberry Pi boards are able to run CasaOS then?

**Comment by Hedius** [comment]
Boards with a arm64 or 7 CPU. Probably the latest generation
