### ISSUE TITLE
Malfunctioning of CPU and RAM usage list

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#272]
Hello
After update `v3.1.1` there are several problem with this part of casaos, for instance :
1. Apps (containers) that I turned off inside the casaos are still inside the list. e.p. Firefox
2. Duplicates. e.p. Benotes
3. In CPU tab some are showing with `0.0%` and some with `0%`
4. In CPU tab the numbers are mostly 0 all the time because it's not updating it frequently, so even if the overall meter showing activity and it's like at 21% in the section tab it shows 0 for all apps.
5. In RAM tab again it shows the one that are powered off with `0 Bytes` in the list

<img src="https://i.ibb.co/bLhMqyy/Screenshot-2022-06-09-202948.png" alt="Ram tab of casaos panel">
<img src="https://i.ibb.co/TqkVrZW/Screenshot-2022-06-09-202816.png" alt="CPU tab of casaos panel">

**Comment by jerrykuku** [comment]
The 0.0% issue has been fixed in v0.3.2. Other issues will be further checked and should be fixed in the next release.

**Comment by jerrykuku** [comment]
We re-checked all the issues you raised and fixed and modified each pair of issues. It will be released in v0.3.2.1. 
If you have already updated to v0.3.2, there is a bug that prevents you from checking for updates in this version, so you will need to update manually using ```curl -fsSL https://get.icewhale.io/casaos.sh | bash``` after v0.3.2.1 has been released.

**Comment by jerrykuku** [comment]
CasaOS 0.3.2.1 has been released, I will close this issue, if the problem still exists you can reopen it.
