### ISSUE TITLE
Docker compose in casaos has 800 characters limit. Requesting it to 5000 or unlimited. 

### ISSUE THREAD

**Issue by bijfy** [IceWhaleTech/CasaOS#273]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jerrykuku** [comment]
This issue has been fixed in V0.3.2. I will close it, if the problem still exists, you can reopen it and discuss it.
