### ISSUE TITLE
No update showing on Dashboard Setting

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#278]
Hello
The new update `v3.2` is out but there is no new update showing on Dashboard Setting.
Also App Store is not loading and the fix on [this issue](https://github.com/IceWhaleTech/CasaOS/issues/254) didn't work for me.

<img src="https://i.ibb.co/C9cpMyf/Screenshot-2022-06-10-194544.png" alt="No update showing on Dashboard Setting">

**Comment by LinkLeong** [comment]
These two problems are the same situation, I will optimize it, thank you for your feedback

**Comment by LinkLeong** [comment]
Thank you for your feedback, we have solved the problem in v0.3.3, I will close the problem, if you have questions, please open a new issue
