### ISSUE TITLE
network enp1s0 error

### ISSUE THREAD

**Issue by redfieldz** [IceWhaleTech/CasaOS#279]
**Describe the bug**

network enp1s0 error no showing activities. 

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2
	 - Disk Total: 936330 
	 - Disk Used: 17381 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7850M Core:4 Linux debian 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux]
	 - Browser: Edge 
	 - Version: 102.0.1245.33

**Comment by jerrykuku** [comment]
I wana to know, what is the WEBUI port of your CasaOS?

**Comment by jerrykuku** [comment]
Since a long time has passed, I will close this issue, if the problem still exists, you can reopen it and give us feedback.
