### ISSUE TITLE
Demo password

### ISSUE THREAD

**Issue by reinethernal** [IceWhaleTech/CasaOS#28]
Demo password not working

**Comment by LinkLeong** [comment]
Already modified back, this is the official version has not yet done not to modify the processing. Thanks for the feedback!

**Comment by reinethernal** [comment]
![image](https://user-images.githubusercontent.com/35932698/143585283-7072b37e-0185-421c-950a-94a9908e7d96.png)

**Comment by LinkLeong** [comment]
sorry,I will deal with this problem as soon as possible.

**Comment by reinethernal** [comment]
thx)

**Comment by JohnGuan** [comment]
> sorry,I will deal with this problem as soon as possible. I will give feedback when its work normally

I think we may need to add a demo mode to the program, where some functions will be disabled

**Comment by LinkLeong** [comment]
@reinethernal  fixed this problem

**Comment by reinethernal** [comment]
Yep, that works! Thank you!

**Comment by scrappy9** [comment]
@LinkLeong  this problem appeared again :(
username also changed from "casaos" to "Casa"
