### ISSUE TITLE
Bug versão 0.3.2

### ISSUE THREAD

**Issue by jlsupremo1** [IceWhaleTech/CasaOS#280]
**Describe the bug**

Ao instalar direto na versão 0.3.2, os APPs instalados não abrem com o click, o dashboard não atualiza nenhuma informação.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2
	 - Disk Total: 224315 
	 - Disk Used: 140669 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 32
	 - System Info: [Ubuntu 20.04.4 LTS   \l Bit:64 Mem:3661M Core:4 Linux casaos 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 102.0.5005.63

**Comment by LinkLeong** [comment]
Sorry for the bad experience, what version was it before you upgraded? Can you provide the name of your app?

**Comment by jlsupremo1** [comment]
> Sorry for the bad experience, what version was it before you upgraded? Can you provide the name of your app?

Hello, I did a clean install directly on the latest version, are all the apps that don't work.

**Comment by LinkLeong** [comment]
Can you take a screenshot of the app you can't open?
like this ![image](https://user-images.githubusercontent.com/13556972/173289773-29924730-2eaf-4cbe-a919-6e767d791230.png)

like this 
![image](https://user-images.githubusercontent.com/13556972/173289863-d3bb1452-9d75-48d1-844b-7f79f25f2c13.png)

Also can you use English?

**Comment by jlsupremo1** [comment]
![casaos](https://user-images.githubusercontent.com/107277100/173343183-816757e4-16f5-4378-8b06-157d4f8440fd.png)
![casaos1](https://user-images.githubusercontent.com/107277100/173343186-c2bc8e44-944c-4aca-94e3-9a039209d230.png)

All apps except Files don't work with the click, but they open manually if you put the IP:porta, but the click even on open doesn't work.

**Comment by jerrykuku** [comment]
Are you using a custom webui port?

**Comment by jlsupremo1** [comment]
no changes were made all default, it was just installed and used.

**Comment by jlsupremo1** [comment]
> Você está usando uma porta webui personalizada?

no changes were made all default, it was just installed and used.

**Comment by JohnGuan** [comment]
@LinkLeong Is it closed?
