### ISSUE TITLE
New install with v3.2 not allowing to change the Web GUI port

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#282]
Hello
recently I installed casaos on a new PC (Debian 11) and after the installation I tried to change the Web GUI port from settings but got the following error: ` strconv.Atoi: parsing "": invalid syntax `

<img src="https://i.ibb.co/9rkcN41/Screenshot-2022-06-11-034931.png" alt=" strconv.Atoi: parsing : invalid syntax ">

**Comment by LinkLeong** [comment]
Sorry for the bad experience for you, we will fix this problem as soon as possible

**Comment by LinkLeong** [comment]
We discuss the need for an upgrade in the next version, or you can make the change manually.

You can change the `server.httpPort` field in the file `/casaOS/server/conf/conf.ini`

![image](https://user-images.githubusercontent.com/13556972/173168573-cdfbb6f8-fd2c-4831-b8d2-440879d9a632.png)

Then restart casaos `systemctl restart casaos`

**Comment by AuthorShin** [comment]
Thank you very much @LinkLeong for the workaround.

**Comment by AuthorShin** [comment]
It's fixed.
Thank you very much.

**Comment by yesbhautik** [comment]
> /casaOS/server/conf/conf.ini

In mine this path is not available yet

**Comment by victorhdchagas** [comment]
I didn't receive error. I can change, works on new Port, but when i reboot, i cant connect into new port and i  cant connect to SSH too.

**Comment by epicalxyz** [comment]
Config file is now located at:
/etc/casaos/gateway.ini
