### ISSUE TITLE
Links to apps not working

### ISSUE THREAD

**Issue by dual3x** [IceWhaleTech/CasaOS#283]
**Describe the bug**

After last update, my links won't work anymore. I click any installed app/container and nothing happens. Not even clicking the 3 dots and Open.

Any fix for this or is it just my install?

Thank you.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2
	 - Disk Total: 59821 
	 - Disk Used: 13967 
	 - Sync State: Sync img: true
	sha256:6b97d52bebca7de621f5a98fc06df4245e68c7f474a3f9603732faf8ffdd687c,
	Sync Key length: 0
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:3794M Core:4 Linux rpi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux]
	 - Browser: Firefox 
	 - Version: 101.0

**Comment by LinkLeong** [comment]
Sorry for the bad experience, what version was it before you upgraded? Can you provide the name of your app?

**Comment by dual3x** [comment]
It's okay and normal to get some bugs and figure it out. Btw, thank you for the support.
I'm coming from v0.3.1 and it kinda happens no matter what app I'm trying to open (nextcloud, vaultwarden, filebrowser, qbittorrent, plex, etc). When I hover I see the open text above but nothing happens when I click. And for some reason the only ones that actually work is the native ones - Files and CasaConnect.

I also tried accessing the dashboard from another pc and mobile phone and I still can't open. Tried it just to make sure it wasn't my pc or the browser.

**Comment by LinkLeong** [comment]
1. Can you help me make a screenshot of the file browser settings
2. Did you open a new page, and if so, what is the URL address?
3.try to use chrome browser

**Comment by ivandiazmolina** [comment]
I have this error as well and temporarily I have fixed it typing in the configuration window the ip. Seem it is not introducing it, that's why it doesn't load.

**Comment by jerrykuku** [comment]
Are you using a custom webui port?

**Comment by dual3x** [comment]
Sorry for the late reply.

1. Screenshot of FileBrowser settings >

![image](https://user-images.githubusercontent.com/106615685/173439882-c4c00040-133b-4908-96c2-506b1972ef39.png)

2. Don't know what you exactly mean but I tried opening it in a new page manually and it works. My url is: http://10.42.10.240:46873/

3. I tried Chrome and same thing as Firefox or Edge.

4. I am using port 90 for the webui. I am using this port since first time I installed and worked well with every update until now.

Thank you for helping me out and I will be glad to help if there is anything else I could provide in order to troubleshoot the issue.

**Comment by dual3x** [comment]
After last update, now works like a charm! Thank you very much for the fast fix!

**Comment by Arcangel1520** [comment]
No respo de despues de una actualización 

![Image](https://github.com/user-attachments/assets/7b780877-6e17-47f5-bf9b-9a6512da3f66)

**Comment by Arcangel1520** [comment]
Pero las aplicaciones si funcionan 

![Image](https://github.com/user-attachments/assets/a1d2e1f2-338f-4227-8941-796542223984)
