### ISSUE TITLE
Environment variables not showing in app Setting window

### ISSUE THREAD

**Issue by SwarleyAUS** [IceWhaleTech/CasaOS#284]
**Describe the bug**

Environment variables are able to be set through the Setting window, but after saving, they do not appear if you reopen the Setting window. The variables are confirmed to have been set by running a printenv from the app terminal.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2
	 - Disk Total: 27712 
	 - Disk Used: 18766 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:3775M Core:4 Linux CasaOS 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 102.0.0.0

**Comment by LinkLeong** [comment]
We will deal with the problem as soon as possible
