### ISSUE TITLE
SSH port connection refused

### ISSUE THREAD

**Issue by jlsupremo1** [IceWhaleTech/CasaOS#286]
![casaos-ssh-port](https://user-images.githubusercontent.com/107277100/173364015-06babbb1-a836-4d99-b576-acc0fc74b900.png)

When the SSH port is not default 22, it is not possible to connect to the terminal, there needs to be an option to change the server's ssh connection port when it is not default 22.

**Comment by Protektor-Desura** [comment]
I had that exact error because in hosts.allow and hosts.deny I did not have 127.0.0.1 (localhost) set to be allowed for SSH. Check your rules to make sure it is allowed because the WEB interface doesn't use the remote client's IP but the webserver itself to do SSH.

**Comment by tigerinus** [comment]
@jlsupremo1 can you check if you have a firewall setup simillar to what @Protektor-Desura described?

BTW - in the coming release we will be adding ability to enable SSH verbose logging, that way we will be able to obtain more details for investigation.

**Comment by jlsupremo1** [comment]
> @jlsupremo1 can you check if you have a firewall setup simillar to what @Protektor-Desura described?
> 
> BTW - in the coming release we will be adding ability to enable SSH verbose logging, that way we will be able to obtain more details for investigation.

Good morning, I don't have a firewall installed, what I notice is that the error appears in the port (22) 127.0.0.1:22, but my server uses ssh port 33591, so I believe it should be in the system settings in the same way as it exists changing the port to WebUI Port:(80) to change the SSH port used as well.

**Comment by jerrykuku** [comment]
@jlsupremo1 Hi, we noticed this issue, CasaOS webSSH can currently only log in using port 22. In a future release, we will add web SSH login with username, password/key, SSH port, and SSH verbose logging parameters.

**Comment by AmadeusGraves** [comment]
Hi! I was in trouble because of this but i solve on ubuntu 22.04 LTS. Take care about this distro because by default ssh is not installed, so you have to do it. Here's a link to install it and modify ssh port to 22. This may help you before of the 0.3.4 release. 

https://www.internetlan.us/2013/02/instalar-y-configurar-ssh-en-ubuntu/

**Comment by LinkLeong** [comment]
Thanks for your feedback, this issue has been updated in 0.3.4, please reopen the issue if you have new problems.
