### ISSUE TITLE
Can't add syncthings

### ISSUE THREAD

**Issue by aporzio1** [IceWhaleTech/CasaOS#29]
**Describe the bug**
When trying to paste the device ID for sync things the submit button is disabled and I can not click it

**To Reproduce**
1. Click on "Go" for syncthings
2. Click next
3. Paste Device ID
4. Submit button stays dimmed and not able to click it to proceed

**Expected behavior**
Should be able to click submit

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Safari
 - Version: 15.1

**Additional context**

**Comment by LinkLeong** [comment]
thinks for the feedback. Did you restart the machine recently

**Comment by aporzio1** [comment]
Yes, restarted and tried again but same thing happens

**Comment by LinkLeong** [comment]
I got it.We will fix this during the working day.I'm sorry to interrupt your experience.

**Comment by LinkLeong** [comment]
This problem has been fixed on Latest Version ,   you can verify it.

**Comment by originalgoon** [comment]
Still experiencing this issue.
Raspberry pi 4 4gb bullseye

**Comment by JohnGuan** [comment]
The problem seems to be solved
