### ISSUE TITLE
Demo return 502

### ISSUE THREAD

**Issue by IITII** [IceWhaleTech/CasaOS#297]
**Describe the bug**
http://demo.casaos.io/
live demo return 502

**To Reproduce**
1. goto https://www.casaos.io/
2. click 'live demo'
3. forward to: 'http://demo.casaos.io/'
6. See error

**Expected behavior**
Demo Site

**Screenshots**
<img width="549" alt="image" src="https://user-images.githubusercontent.com/33705067/173733156-3e3c0fb2-7d89-4225-a13f-9f15e00c1bc7.png">

**Desktop (please complete the following information):**
 - OS: Mac 11.16
 - Browser [chrome]
 - Version [latest stable]

**Additional context**

**Comment by LinkLeong** [comment]
Thank you for your feedback, we have dealt with the urgent
