### ISSUE TITLE
Plex Issues: Port Mapping and Client Application

### ISSUE THREAD

**Issue by Bira-oliverio** [IceWhaleTech/CasaOS#299]
**Describe the bug**

First, the port mapping for the host is missing in the Plex configuration, what gives a error if you try to open it, if you add fill the host port as 32400 it opens normally.

Second, the Plex application available in the store looks like the client application not the server. If you try to include your own media the app redirects to the download of the media server. Maybe a better option to use is the plexinc/pms-docker instead the linuxserver/plex.

Thanks.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2
	 - Disk Total: 948560 
	 - Disk Used: 428745 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 0
	 - System Info: [Ubuntu 22.04 LTS   \l Bit:64 Mem:15908M Core:8 Linux pyassaba-server 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 102.0.5005.115

**Comment by MitasTech** [comment]
3.2 had a lot of issues so they removed it. The latest version currently is 3.1.1. They said that a new version is gonna come out within the next days

**Comment by LinkLeong** [comment]
We have fixed this issue in the latest version, you can upgrade to solve the problem

**Comment by LinkLeong** [comment]
[](url)
