### ISSUE TITLE
UI typo: "unistall"

### ISSUE THREAD

**Issue by belzecue** [IceWhaleTech/CasaOS#30]
**Describe the bug**
UI typo.

**To Reproduce**
Rightclick on any installed app and observe the menu options.

**Expected behavior**
Correct spelling.

**Screenshots**
![image](https://user-images.githubusercontent.com/1931303/143668342-0ca3986b-ed4f-4f78-b35a-d35334c28683.png)

**Comment by jerrykuku** [comment]
Thanks for the correction, we will fix it as soon as possible.

**Comment by jerrykuku** [comment]
It has been updated in the new version.
