### ISSUE TITLE
Loja de app não abre.

### ISSUE THREAD

**Issue by vitorxsceva** [IceWhaleTech/CasaOS#301]
**Describe the bug**

Loja de aplicativos não abre, não disponibilizando a instalação dos mesmos.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 99208 
	 - Disk Used: 7104 
	 - Sync State: Sync img: false
	Sync Key length: 0
	 - System Info: [Ubuntu 22.04 LTS   \l Bit:64 Mem:3891M Core:4 Linux vitorxsceva 5.15.0-39-generic #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Edge 
	 - Version: 102.0.1245.41

**Comment by JohnGuan** [comment]
We've fixed the problem, can you open it now?

**Comment by JohnGuan** [comment]
Duplicate #302
