### ISSUE TITLE
loja de apps

### ISSUE THREAD

**Issue by marcelinuz** [IceWhaleTech/CasaOS#303]
**Describe the bug**

fica carregando indefinidamente

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 37288 
	 - Disk Used: 12568 
	 - Sync State: Sync img: false
	Sync Key length: 0
	 - System Info: [Deepin GNU/Linux 20.6   \l Bit:64 Mem:7957M Core:4 Linux marcelo-PC 5.10.101-amd64-desktop #20.00.05.06-release SMP Mon Mar 14 09:34:55 CST 2022 x86_64 GNU/Linux]
	 - Browser: Edge 
	 - Version: 102.0.1245.44

**Comment by JohnGuan** [comment]
Duplicate #302
