### ISSUE TITLE
Octoprint Store install

### ISSUE THREAD

**Issue by thiagoedson** [IceWhaleTech/CasaOS#304]
**Describe the bug**

Octoprint Store install ? 

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 100220 
	 - Disk Used: 14290 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 32
	 - System Info: [Ubuntu 22.04 LTS   \l Bit:64 Mem:3632M Core:2 Linux cassoneserver 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 102.0.0.0

**Comment by JohnGuan** [comment]
I don't quite understand what you mean, can you expand on that?

**Comment by JohnGuan** [comment]
Sorry, I will close this issue due to the long lack of replies.

**Comment by NTCatx** [comment]
sorry to reply to this thread but i belive they were asking if you could add[Octoprint](https://hub.docker.com/r/octoprint/octoprint) to the app store. I'm Only assuming because im trying to install octoprint on casaos

**Comment by DemonZenki** [comment]
I am trying to install Octoprint onto a CasaOS device, how can this be done? Or is it coming to the App Store?
