### ISSUE TITLE
Feature: Shutdown from Web GUI

### ISSUE THREAD

**Issue by Lauren-ED209** [IceWhaleTech/CasaOS#307]
### Discussed in https://github.com/IceWhaleTech/CasaOS/discussions/253

<div type='discussions-op-text'>

<sup>Originally posted by **Peeeet** June  6, 2022</sup>
### Is your idea related to a problem? Please describe:
I don't see an obvious way to safely shutdown through CasaOS.  Specifically when running on the ZimaBoard... the word "shutdown" is not mentioned anywhere and this, in fact, will be the first thing on this github that even contains the word "shutdown" 🧐
<br>
### Describe the solution you'd like:
A button in the Web UI that shuts down the underlying system (in my case on a ZimaBoard).
<br>
### Describe alternatives you've considered:
SSH is an option, but for such a rudimentary feature, I feel it should be as accessible as so many of the other more advanced features that are already present in the Web UI.

...Unless this system / the ZimaBoard are built to gracefully handle unexpected shutdowns (aka just pullin' the ol' plug) in which case that's an awesome feature and should be ~documented somewhere~ advertised proudly!
<br>
### Additional context
Also this idea is even more pertinent considering the current [bug 244](https://github.com/IceWhaleTech/CasaOS/issues/244) that prevents SSH login from the Web UI 😅</div>

**Comment by mago-kamar** [comment]
Totally agree :)

**Comment by ggantn** [comment]
+1

**Comment by raller1028** [comment]
This feature has been implemented in v0.4.0, if you still have problems, please reopen
