### ISSUE TITLE
[STORY] darkmode support

### ISSUE THREAD

**Issue by Lauren-ED209** [IceWhaleTech/CasaOS#308]
### Discussed in https://github.com/IceWhaleTech/CasaOS/discussions/248

<div type='discussions-op-text'>

<sup>Originally posted by **devrob20** June  2, 2022</sup>
for ppl with low vision darkmode is often a must-have , there is an official way to make html and css work with the darkmode setting of browsers and operating systems.

please implement it.
thanks.

https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/
</div>

## Refer

- https://github.com/IceWhaleTech/CasaOS/discussions/248 (6 upvotes)

**Comment by JohnGuan** [comment]
I also think it is necessary

**Comment by tigerinus** [comment]
I want this in `0.3.6`!

**Comment by tigerinus** [comment]
@Lauren-ED209 - 麻烦转到 CasaOS-Doc

**Comment by tigerinus** [comment]
@jerrykuku - 在正式开发前做背景调研

**Comment by Lauren-ED209** [comment]
move this issue to CasaOS requirement.

https://github.com/IceWhaleTech/CasaOS-Doc/issues/107
