### ISSUE TITLE
[Story] Being able to downgrade to a previous CasaOS release

### ISSUE THREAD

**Issue by Lauren-ED209** [IceWhaleTech/CasaOS#310]
# Summary

This request is derived from the github discussion. Origins is a series of discussions brought about by recent product upgrade issues.

### Discussed in https://github.com/IceWhaleTech/CasaOS/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **MitasTech** June 14, 2022</sup>
I'm on version 3.1.1 and i have about 2.5TB of data on my server. I'm a bit afraid to update to the new update just in case something goes bad because it happened in the past. I really want to update to get the new features and by having this feature would make a lot of people feel safer when updating and also help anyone that actually face issues. 
This is just my opinion of course, but it would be great to have a feature that allows downgrading. </div>

# PM notes

Through the update panel, users can skip update notifications for the current version.
1. Click Update
2. Show the version log with two options, upgrade or skip this version
3. If chosen "skip this version", remove the upgrade notification

Through ssh, users can downgrade CasaOS to a specific version.
1. Open terminal, login in CasaOS
2. Find command from github readme file
3. Enter the command, showing the whole process
- script will detect if CasaOS is installed already
- confirm to uninstall CasaOS (1. Remove CasaOS only. 2. Remove CasaOS and Docker Apps and AppData) 
- Reinstall CasaOS
4. Successfully downgrade to a specific version of CasaOS

## Criteria

- [ ] Criteria 1
- [ ] Criteria 2
- [ ] Criteria 3

# Dev Notes

## Depends on 

- [ ] Story 1
- [ ] Story 2
- [ ] Story 3

# QA Notes

## Checklist 

- [ ] item 1
- [ ] item 2
- [ ] item 3

**Comment by jcwatson11** [comment]
For what it's worth, this appears to already be possible using the casaos.sh script from the README.md file.

Instead of piping the shell script to bash, just download the file:
```
> sudo su - # become root
> curl -fsSL https://get.icewhale.io/casaos.sh # download the shell script
> chmod 744 casaos.sh # make the script executable
> ./casaos.sh -h # show help message, which shows you the -v option for specifying a version to install.
> ./casaos.sh -v 0.2.10 # install casaos version 0.2.10... or specify some other version number.
```

**Comment by Lauren-ED209** [comment]
> For what it's worth, this appears to already be possible using the casaos.sh script from the README.md file.
> 
> Instead of piping the shell script to bash, just download the file:
> 
> ```
> > sudo su - # become root
> > curl -fsSL https://get.icewhale.io/casaos.sh # download the shell script
> > chmod 744 casaos.sh # make the script executable
> > ./casaos.sh -h # show help message, which shows you the -v option for specifying a version to install.
> > ./casaos.sh -v 0.2.10 # install casaos version 0.2.10... or specify some other version number.
> ```

Right. So I will close this issue. After development evaluation, I think it's not necessary for now. Thanks for your suggestion and support! ;)
