### ISSUE TITLE
Bug when opening App Store

### ISSUE THREAD

**Issue by CeruttiMaicon** [IceWhaleTech/CasaOS#312]
**Describe the bug**

Not this installation the store with the applications

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 29640 
	 - Disk Used: 8139 
	 - Sync State: Sync img: false
	Sync Key length: 0
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:923M Core:4 Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux]
	 - Browser: Chrome 
	 - Version: 102.0.0.0

**Comment by JohnGuan** [comment]
Duplicated #302
