### ISSUE TITLE
ssl error <- fix it please

### ISSUE THREAD

**Issue by silversaber** [IceWhaleTech/CasaOS#313]
**Describe the bug**

i set ssl cert at my server.
so browser occur error beacusof protocol
such as ) ws:// or http://

and 

how i do set port 443 duplicately in apps setting
i set reverse proxy using nginx 
such as ) http://192.168.0.2:9000 -> https://domain.domain/portainer/ 

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 46050 
	 - Disk Used: 5984 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 32
	 - System Info: [Ubuntu 22.04 LTS   \l Bit:64 Mem:965M Core:2 Linux instance-20220616-1048-434727 5.15.0-1003-oracle #5-Ubuntu SMP Wed Apr 20 04:50:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Firefox 
	 - Version: 101.0

**Comment by JohnGuan** [comment]
Are subdomains OK? I don't really understand your specific scenario. Currently CasaOS has not been designed for domain binding, SSL, or reverse proxies.

**Comment by JohnGuan** [comment]
Sorry, I will close this issue due to the long lack of replies.
