### ISSUE TITLE
App Store Not Opening

### ISSUE THREAD

**Issue by devenderkg** [IceWhaleTech/CasaOS#319]
**Describe the bug**

App store keeps loading

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 29086 
	 - Disk Used: 1889 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 32
	 - System Info: [Raspbian GNU/Linux 11   \l Bit:32 Mem:923M Core:4 Linux pi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux]
	 - Browser: Edge 
	 - Version: 102.0.1245.44

**Comment by devenderkg** [comment]
I don't know what was wrong with it, but it's working fine now, thanks.

Best Regards
Devender

**Comment by jerrykuku** [comment]
Ok, I will close this issue and if the problem reappears you can reopen it.
