### ISSUE TITLE
App logo is not loading when imported.

### ISSUE THREAD

**Issue by openspeedtest** [IceWhaleTech/CasaOS#320]
App logo is not loading when imported.

This is the exported Json (OpenSpeedTest.json)

`{"custom_id":"7a8c2185-a2b8-4bbb-9493-07f41d7ac943","origin":"custom","network_model":"bridge","index":"","icon":"https://github.com/openspeedtest/Speed-Test/raw/main/images/icons/android-chrome-512x512.png","image":"openspeedtest/latest:latest","envs":[{"container":"PATH","host":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","desc":"","type":0},{"container":"NGINX_VERSION","host":"1.22.0","desc":"","type":0},{"container":"NJS_VERSION","host":"0.7.4","desc":"","type":0},{"container":"PKG_RELEASE","host":"1","desc":"","type":0}],"ports":[{"container":"3000","host":"3000","protocol":"tcp","desc":"","type":0},{"container":"3001","host":"3001","protocol":"tcp","desc":"","type":0}],"volumes":[],"devices":[],"port_map":"3000","cpu_shares":90,"restart":"always","enable_upnp":false,"label":"OpenSpeedTest","description":"SpeedTest","position":false,"host_name":"OpenSpeedTest","privileged":false,"cap_add":[],"cmd":["nginx","-g","daemon off;"],"version":"1.0"}
`

**Comment by LinkLeong** [comment]
Thank you for your feedback, we have solved the problem in v0.3.3, I will close the problem, if you have questions, please open a new issue
