### ISSUE TITLE
Add support for network_mode: "container"

### ISSUE THREAD

**Issue by altShiftDev** [IceWhaleTech/CasaOS#321]
**Is your feature request related to a problem? Please describe.**
The problem is how to network multiple containers together. Currently this can't be done with CasaOS as it only allows for network mode bridge or host. The use case I need is to have one container running a VPN service (Gluetun) which can then provide that VPN access to other containers as needed (transmission/bittorrent clients).

**Describe the solution you'd like**
In the docker settings "network mode" dropdown, a new option is added to the current list (bridge + host) called "container" and when selected, you would have a new dropdown appear below called "Container" which would allow you to select any other running container to route the traffic through (see screenshots below).

This would be the equivalent of `--network=container:gluetun` when using docker from the command line or `network_mode: "container:gluetun"` when using docker from the yml file.

For more info, this is the official instructions from the Gluetun repo on how to network a container to another: https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun

**Describe alternatives you've considered**
I've tried to manually edit the docker json files inside `/var/lib/docker/{appid}/` but I wasn't able to figure out which one to edit and how in order to accomplish this workaround. It seems that these files get overwritten whenever a container restarts. I'll keep looking for command line alternatives to running transmission through gluetun but having the OS support this would be a huge help.

**Additional context**
This video demonstrates the technique through the command line: https://youtu.be/mH7J_2JKNK0?t=330

These screenshot shows this feature demonstrated in the portainer gui: 
<img width="986" alt="image" src="https://user-images.githubusercontent.com/24980556/175611684-9c25a352-79cf-4558-9061-3bf4c11ca7a7.png">
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/24980556/175611734-8efc01c6-aadc-4e76-bd7b-d66d08e5fc96.png">

Video walkthrough of the feature being demonstrated on portainer: https://youtu.be/xbSfaKwyfXE?t=545

**Comment by Lauren-ED209** [comment]
This is very interesting! The original plan is to iterate on the network enhancement module in version 0.4. However, as you provided a very clear, easy-to-implement solution, I will evaluate with the team to check if we can provide a quick response in recent updates. 

But no doubt, it's an important requirement. It's just a matter of sooner or later.

**Comment by Lauren-ED209** [comment]
This suggestion is feasible. Could you share more details about the application scenario? For example, which app do you prefer to communicate with each other based on this network layer? And what are your specific application scenarios?

**Comment by altShiftDev** [comment]
@Lauren-ED209 The use case that I was trying to do is connect a torrent container (e.g. transmission) to a VPN container (e.g. gluetun). Gluetun can be easily setup with any VPN provider and transmission benefits from the pseudo-anonymity of a VPN.

**Comment by Lauren-ED209** [comment]
OK, I'll merge this requirement into the development plan, thanks for your time.

**Comment by Lauren-ED209** [comment]
I have created this requirement in the development plan. Recently we are optimizing the routing layer. I would expect to develop this feature you proposed at exactly the right time when the routing layer development is complete.

I'll close this issue, feel free to share with us on discord or here if you have further ideas!

**Comment by drakoooo** [comment]
Hello, i'm currently struggling to find that feature for the same exact need of op, is it still not implemented ? and if not, are there any simple way to make it work ? I really don't want to setup a Portainer just for that.

**Comment by ElijahHW** [comment]
In the same boat here, running Gluetun in one container and binding that to other containers who need a vpn. This doesn't seem possible to do in CasaOS, yet? Otherwise CasaOS is amazing!

**Comment by chinarut** [comment]
> I have created this requirement in the development plan. Recently we are optimizing the routing layer. I would expect to develop this feature you proposed at exactly the right time when the routing layer development is complete.
>
> I'll close this issue, feel free to share with us on discord or here if you have further ideas!

@Lauren-ED209 could you please provide a link to the development plan?

I feel like we’ve lost the ability to track and trace this issue by closing it when it is not implemented.  please let me know if I’m wrong.

**Comment by hotstormt** [comment]
Hello,

I'm experiencing the same issue mentioned earlier and would like to know whether this functionality has been added to the roadmap or if it has been overlooked. In today's world, using a VPN is essential for maintaining anonymity online, and I believe this feature is crucial for many CasaOS users.

Currently, the limitation of only having bridge or host network modes makes it difficult to integrate essential services like VPNs with other containers, often forcing users to seek alternative, sometimes cumbersome, solutions like manually editing configuration files or using Docker Compose.

Adding a "container" network mode within Docker settings in CasaOS would be a significant improvement and make it much easier for users to ensure their privacy and security when using services like torrents via VPN.

I'd like to emphasize the importance of this request and kindly ask for an update on the status of this functionality in the CasaOS development plan.

Thank you for your attention and for the great work so far!

**Comment by Khapra** [comment]
Experiencing the same issue, wondering if this is being worked upon? The workaround I've found is to run a portainer container and update the network mode through that for other apps. Its still not a perfect workaround as it defaults back to casaos settings after a restart, update or anything making that app reload.

**Comment by CabbageSmell** [comment]
I hope that there is a solution in what I see in the latest version of CasaOS.

In CasaOS app settings for Gluetun, and for Duluge/Qbittorent/Transmission in the Network box, there are choices under "bridge" which I think might be what we are looking for.  

Gluetun Network setting in CasaOS to bridge>gluetun.   
Deluge Network setting in CasaOS to bridge>big-bear-gluetun_default

I am not sure how to test if it is working yet, still brand new at this :)

**Comment by Peybro** [comment]
> I am not sure how to test if it is working yet

You can check the IP for a specific container with this:
`docker run --rm --network=container:sabnzbd alpine:3.18 sh -c "apk add wget && wget -qO- https://ipinfo.io"`
Just replace _sabnzbd_ with any container you're routing through another.

BTW network mode _bridge_ does not route all the traffic through another container.

**Comment by CabbageSmell** [comment]
The network selector in each of the CasaOS containers settings has been of no use for me.  However, by using Docker Compose import, it is possible to get containers connecting through Gluetun.  It is a chore to setup and then every time you update Gluetun you have to redeploy each of the containers which connect to it by exporting and then importing the Docker Compose file.  Would be great if CasaOS devs could figure that out for us.  eg.. using a torrent client container connecting to the internet through Gluetun VPN.

**Comment by danielbarnes175** [comment]
If this is planned, wouldn't marking it for the Future or planned be better than Done? https://github.com/orgs/IceWhaleTech/projects/1

Closing this/marking it as completed seems like a great way to forget about this, which is why I suspect it hasn't been added for nearly 3 years

**Comment by Peybro** [comment]
Isn't the whole project basically dead by now?

**Comment by v4ldimar** [comment]
@Lauren-ED209 @LinkLeong (Im was unsure who to tag).

- What is the current status on CasaOS? Is development still ongoing?
- I personally need the docker container_name feature for reasons already listed in this issue (Transmission & Jackett sharing the Gluetun VPN connection)
- Can this issue be reopened so I can create a PR?
