### ISSUE TITLE
Hard disk identification of lxc container under proxmox

### ISSUE THREAD

**Issue by cmodog** [IceWhaleTech/CasaOS#322]
**Is your feature request related to a problem? Please describe.**
In the lxc container under proxmox, The hard disk cannot be recognized normally.
And the Create Storage function looks like it will format my entire hard drive.

**Describe the solution you'd like**
Identify the hard drive correctly.

**Describe alternatives you've considered**
If "pve" is found in the linux kernel, only loop0 or the root directory is used as storage space.

**Additional context**
![image](https://user-images.githubusercontent.com/53931809/175763408-97b31c66-88d2-4b85-b415-b7939ffd4fc7.png)
<img width="667" alt="image" src="https://user-images.githubusercontent.com/53931809/175763434-29e1adff-5563-4c62-bcea-34fb4e321a2b.png">
<img width="669" alt="image" src="https://user-images.githubusercontent.com/53931809/175763428-c90e51cb-e207-489e-9a87-364d6d7ca618.png">
<img width="670" alt="image" src="https://user-images.githubusercontent.com/53931809/175763442-37040b01-b0a4-4ae0-92f8-51ddb0711843.png">
<img width="599" alt="image" src="https://user-images.githubusercontent.com/53931809/175763473-ab6edff9-51ca-443a-b9dc-b27f60887208.png">

**Comment by jerrykuku** [comment]
Currently we have only done adaptations and tests for physical machine systems and some virtual machine systems. For containerized systems like lxc we have not tested and there are no plans to support it at this time, I will close this issue, thank you very much for your feedback.
