### ISSUE TITLE
Sync YourData not working anymore

### ISSUE THREAD

**Issue by gswec2005** [IceWhaleTech/CasaOS#326]
**Describe the bug**

It worked firsttime, but needed to unregister a device, and it stoped working

Displayed message when trying to install syncthing application:

![image](https://user-images.githubusercontent.com/13799808/176063143-e9162a28-d19a-474d-aeff-c12cf4cafaa0.png)

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 32122 
	 - Disk Used: 13011 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 0
	 - System Info: [Ubuntu 20.04.4 LTS   \l Bit:64 Mem:5941M Core:4 Linux vmnas 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 102.0.0.0

**Comment by JohnGuan** [comment]
That is, Sync your data no longer works after you unregister the device.
Then, when you try to install Syncthing you encounter an error.
Am I understanding this correctly?

**Comment by gswec2005** [comment]
yes, after removing my device, i saw this error after putting new device ID and clicking on Submit in the "Sync Guide Screen" 
![image](https://user-images.githubusercontent.com/13799808/176080969-66059e4d-f4dc-4b11-9dd6-7d0855511ce1.png)

I uninstalled syncthing app, and when trying to reinstall, it showed the error on bug report.

**Comment by gswec2005** [comment]
hello friends, it worked again, when updated to 0.3.3.

@yaoyunnuo  can confirm for you too ?

**Comment by LinkLeong** [comment]
We know this issue has brought you a bad experience and we will update it in v0.3.4.

**Comment by LinkLeong** [comment]
Thanks for your feedback, this issue has been updated in 0.3.4, please reopen the issue if you have new problems.
