### ISSUE TITLE
docker custom install Support label

### ISSUE THREAD

**Issue by leganck** [IceWhaleTech/CasaOS#329]
I need the traefik proxy , which uses labels to work

**Comment by Lauren-ED209** [comment]
Recently we are improving the routing layer. Considering this isn't an issue, I'll close it right now. 
Feel free to communicate with us via discord or this issue if you have further ideas!

**Comment by Lauren-ED209** [comment]
Recently we are improving the routing layer. Considering this isn't an issue, I'll close it right now. 
Feel free to communicate with us via discord or this issue if you have further ideas!

**Comment by leganck** [comment]
> Would you mind to share more details about your scenarios and needs? Based on our understanding, you're going to use labels to build the connection between different apps. Make these casasos docker apps discoverable from the other apps. Is that corrent? If so, what's these apps? And what's the purpose of it?

I use traefik to proxy the casaos application, traefik requires the application's label to specify the port and domain name.
![image](https://user-images.githubusercontent.com/24834938/194735172-25aa7dd4-2461-410d-93c0-e42272afb4ae.png)

**Comment by tigerinus** [comment]
Seriously looking into this. 

Since this is closed, let's track the progress in the other issue that's still open: #773
