### ISSUE TITLE
Nextcloud

### ISSUE THREAD

**Issue by ImOstrovskiy** [IceWhaleTech/CasaOS#33]
How or where i can get nextcloud app file?

**Comment by JohnGuan** [comment]
> How or where i can get nextcloud app file?

Try this:
[Nextcloud.json.zip](https://github.com/IceWhaleTech/CasaOS/files/7615992/Nextcloud.json.zip)
Unzip and import

**Comment by JohnGuan** [comment]
We will also add the Nextcloud one-click install feature to the Featured Apps as soon as possible.

**Comment by ImOstrovskiy** [comment]
> > How or where i can get nextcloud app file?
> 
> Try this: [Nextcloud.json.zip](https://github.com/IceWhaleTech/CasaOS/files/7615992/Nextcloud.json.zip) Unzip and import

Not working(

**Comment by JohnGuan** [comment]
Are there any error messages?

**Comment by ImOstrovskiy** [comment]
> Are there any error messages?

Get a installing loop
