### ISSUE TITLE
Ability to add custom links to dashboard

### ISSUE THREAD

**Issue by devcircus** [IceWhaleTech/CasaOS#333]
**Is your feature request related to a problem? Please describe.**
I thought of this when trying to use an "external" WEB UI url for my installed apps. My apps are running behind nginx reverse proxy, which works correctly, but if you try to use the external ip as the web ui "host", the app will not open when clicked.

**Describe the solution you'd like**
If, in addition to the current app install process (custom or app store), there was a way to just add custom links (with the name, icon, and url of your choice), then we could keep all of our services on the dashboard whether or not they were installed locally within casaos, or not.

**Describe alternatives you've considered**
I've joined the Discord and discussed with others who were having the same issue, but no solutions came up.

**Additional context**
N/A

**Comment by devcircus** [comment]
I noticed Discussion #314, which I believe is basically the same thing I'm asking here. This would be great. As it stands, I have to have a separate dashboard app, with links to all of my services, in addition to casaos which can only link to services installed in casaos.

**Comment by 3rikk** [comment]
+1. Would love to be able to add links to other devices on my network that have web UIs (printer, opnsense, switches, wifi AP, etc). For now I have heimdall installed in a docker container under casaOS and those devices linked there but that is a bit messy. 

Perhaps these could also be in a separate category on the home page, separate from the Apps category. (being able to rename said categories could be cool too)
