### ISSUE TITLE
The time displayed in Files is in real time.

### ISSUE THREAD

**Issue by cs0663c** [IceWhaleTech/CasaOS#335]
![QQ截图20220702150522](https://user-images.githubusercontent.com/59052041/176990521-f5caea6a-144d-40fe-81b2-723ea762e937.png)

files 显示的时间是实时的 
这个不是应该显示文件的创建时间吗？

files shows the time in real time 
Shouldn't this show the creation time of the file?

 - OS: linux
 - CasaOS Version: 0.3.2.1
 - Disk Total: 18014 
 - Disk Used: 7383 
 - Sync State: Sync img: true
Sync Key length: 32
 - System Info: [Debian GNU/Linux 10   \l Bit:64 Mem:3921M Core:4 Linux debian 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux]
 - Browser: Edge 
 - Version: 103.0.1264.37

**Comment by JohnGuan** [comment]
Thanks for your feedback!
I also found this problem, has been confirmed as a bug @jerrykuku

**Comment by jerrykuku** [comment]
Yes this is a bug and it will be fixed in v0.3.3.

**Comment by jerrykuku** [comment]
I will close the issue and if the problem persists you can reopen it.
