### ISSUE TITLE
Version displays V0 and USB drive doesn't mount correctly

### ISSUE THREAD

**Issue by JVTEAM** [IceWhaleTech/CasaOS#339]
Came down to it and noticed my containers weren't working.  The version is listed as V0 and my USB drive shows up, but doesn't show any data on storage and isn't mounted on the file system.

**Comment by LinkLeong** [comment]
1.v0 display problem, you can open the application center to install an application, see if it can be installed successfully.
2. usb mount problem we have been planning, the current version has not been determined.

**Comment by JVTEAM** [comment]
Had to manually remount via linux terminal.  That fixed it

**Comment by LinkLeong** [comment]
Sorry, did you fix the usb mount in your latest installation?

**Comment by JVTEAM** [comment]
> Sorry, did you fix the usb mount in your latest installation?

Manually yes.  However, that is not how the software is supposed to function.

**Comment by LinkLeong** [comment]
Next have @JohnGuan  continue to follow up on your questions

**Comment by JVTEAM** [comment]
> @JVTEAM I'm very sorry for your bad experience, this is really a feature that needs to be improved. This part of the program processing logic has been discussed a lot within our team to improve it step by step. If you have some best practices on mounting please share them with us.

Well I don't think I need to explain this process to developers, but ok.

I just went into the terminal and ld "lsblk" to find my USB drive
I already had a folder I was mounting to, but if not "sudo mkdir ~/folder"
Then "sudo mount /dev/sdb1 /nameoffolder

adding it to fdisk will make it mount everytime, but i haven't done that.  However, up until the last couple releases this standard Linux mounting procedure was unneccesary.

**Comment by tigerinus** [comment]
@JVTEAM - afaik `fdisk` is a partitioning utility. What exactly do you mean by *adding it to fdisk*?

Can you follow the bug report template and provide the exact steps to reproduce this?

**Comment by JohnGuan** [comment]
We mainly use issues to discuss features that have been identified as implemented but have bugs.
Can you put your requirements through Discussions? Thanks!

- https://github.com/IceWhaleTech/CasaOS/discussions/164
