### ISSUE TITLE
can't install filebrowser

### ISSUE THREAD

**Issue by xinmans** [IceWhaleTech/CasaOS#34]
安装app时

报错Installing filebrowser/filebrowser
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /DATA/

但是/DATA目录存在的

xinmans@ubuntu:/DATA/AppData$ ls -ltr
total 44
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 04:33 d7b11c5d-3ea4-45b8-aae3-44316271c74f
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 04:36 faca76f3-4783-48cc-9a12-1042182de52e
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 04:40 e727f2a4-da8c-4632-a1e3-0f9f51c22700
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 04:40 7ee68a06-d3fb-4288-9205-8c231dfa1c4d
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 04:40 2cc50755-37c2-4858-a6e2-a13732154db4
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 05:14 3b144092-fe2d-4892-a3e8-7b544cc8a94a
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 05:19 7375404e-bd81-42b5-b54c-1d66d31bcc8b
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 06:08 ee1497ee-4a0c-4845-a00b-d30364cebca4
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 06:09 a84a7227-9375-4faa-9cc1-50c32879064f
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 06:13 d5ecd2c0-3151-4b76-8642-bd4c08e04fb1
drwxrwxrwx 2 xinmans xinmans 4096 Nov 29 06:14 8eeab918-d239-4728-bc88-c8f541102633
xinmans@ubuntu:/DATA/AppData$ pwd
/DATA/AppData
xinmans@ubuntu:/DATA/AppData$ cd ..
xinmans@ubuntu:/DATA$ ls
AppData  Documents  Downloads  Gallery  Media
xinmans@ubuntu:/DATA$ pwd
/DATA

**Comment by LinkLeong** [comment]
麻烦截一下配置页面的图
