### ISSUE TITLE
WSS support 

### ISSUE THREAD

**Issue by SOVLOOKUP** [IceWhaleTech/CasaOS#342]
**Describe the bug**

Since wss is not supported, the web terminal does not work with https access.
> 由于不支持 wss, 在 https 访问下，web terminal无法使用

```
Mixed Content: The page at 'https://sovlookup.top:8443/ui/#/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://sovlookup.top:21641/socket.io/?EIO=3&transport=websocket'. This request has been blocked; this endpoint must be available over WSS.
```

**To Reproduce**

use https access to casaos, the console can see the error report
> https 访问 casaos ，控制台即可看到报错

**Expected behavior**

Possibility to connect using wss
> 使用 wss 进行连接

**Screenshots**
![image](https://user-images.githubusercontent.com/53158137/177950430-dfbeb830-87db-49f8-91a3-47d1e051657e.png)
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version v0.3.2.1

**Comment by JohnGuan** [comment]
I added the English description for you. We mainly use English to exchange and communicate.
欢迎添加我的微信：guanningchuan 我们可以使用微信群进行中文交流。

**Comment by JohnGuan** [comment]
We do not officially support the use of https in CasaOS' panels at this time.
@jerrykuku Do you have any thoughts on this part of wss functionality? Is it implemented together with https or is there a way for wss to be supported separately?

**Comment by jerrykuku** [comment]
There is no support for https access yet, but it is planned, and I think that wss will be supported together with https support.

**Comment by JohnGuan** [comment]
This is an issue that will be addressed in the future along with the https issue.
I'm closing this issue here for now.
