### ISSUE TITLE
cant remove, format a storage

### ISSUE THREAD

**Issue by gswec2005** [IceWhaleTech/CasaOS#344]
**Describe the bug**

when creating the first storage, it works fine, but when removing, formating that storage, the system dont recognize user password

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.3
	 - Disk Total: 16059 
	 - Disk Used: 7129 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 0
	 - System Info: [Ubuntu 20.04.4 LTS   \l Bit:64 Mem:1983M Core:2 Linux vmcasaosalpha 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 103.0.0.0

![image](https://user-images.githubusercontent.com/13799808/178105455-f2d302f4-9a07-45b0-96ff-4ca76d5c1586.png)

**Comment by jerrykuku** [comment]
We will check this issue as soon as possible, thanks for the feedback.

**Comment by LinkLeong** [comment]
Thanks for your feedback, this issue has been updated in 0.3.4, please reopen the issue if you have new problems.
