### ISSUE TITLE
Help troubleshooting setup on OrangePi Zero2 SBC running Armbian

### ISSUE THREAD

**Issue by Virgus** [IceWhaleTech/CasaOS#347]
Hello,
I'm testing CasaOS on a new OPiZ2 and I'm avoiding latest Armbian (debian for arm cpus) releases because of some known problems
I choosed the bullseye february release and rebooting and hdmi output have no issues, provided that the upgrade is limited as suggested [here on Armbian's forum](https://forum.armbian.com/topic/21185-orangepi-zero-2-wont-start-with-new-fw/#elControls_141727_menu).

The first problem encountered was related to docker-ce install and IPTables and it's not strictly related to CasaOS.

This what I found via cat /var/log/syslog
> Jul  9 09:39:59 CasaOS dockerd[5655]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
> Jul  9 09:39:59 CasaOS dockerd[5655]:  (exit status 4)

And I solved it with:
`sudo update-alternatives --set iptables /usr/sbin/iptables-legacy`
`sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy`

I tried again CasaOS install and got a small bug related to /casaOS/server/conf/conf.ini
> [ INFO ] Putting CasaOS Configuration file in /casaOS/server (may require password)
> mv: cannot stat '/casaOS/server/conf/conf.ini.sample': No such file or directory
> [FAILED] error 1 in command: $sudo_cmd mv -f "$casa_conf_path/conf.ini.sample" "$casa_conf_path/conf.ini"`

I had to rename the file /casaOS/server/conf/conf.conf.sample to conf.ini.sample and re-launch the setup script.
After this step apparently all is fine and I can access the CasaOS GUI

I have a first question at this point: why /casaOS path is removed when I install the packages as a user while it is kept if I install it as root ? And just for curiosity: where can I find conf.ini once /casaOS path is removed ?

Going further I opened the GUI and tried installing pihole/pihole image from the CasaOS App Store
The error msg I'm always getting is the following: 

> "Handler for POST /v1.41/containers/Pi-hole/start returned error: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: unable to start unit \"docker-0d4703b4ef77bdcfdc779addc2f69331fea4e76e7409da36268d3c67a05c71a2.scope\" (properties [{Name:Description Value:\"libcontainer container 0d4703b4ef77bdcfdc779addc2f69331fea4e76e7409da36268d3c67a05c71a2\"} {Name:Slice Value:\"system.slice\"} {Name:Delegate Value:true} {Name:PIDs Value:@au [5658]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): Message recipient disconnected from message bus without replying: unknown"

For completeness I'm attaching the syslog related to this error. I suspect it's docker related, not CasaOS, but unfortunately I'm not experienced enough to go beyond this one: I've spent hours trying to find a possible solutions but I ended up my quest trying to read previous bug reports without success. All what I found related to OCI runtime create failed was related to Nvidia GPUs which is not the case of SBCs. I hope to get some tips and ideas about where/what to look for to troubleshoot this error.

Thanks for this very promising project,
V.

[syslog.txt](https://github.com/IceWhaleTech/CasaOS/files/9076606/syslog.txt)

**Comment by JohnGuan** [comment]
Sorry I don't have any ideas at the moment. It seems like this is an upstream issue regarding docker.
Thank you very much for trying. I think the community participation in contributing installation scripts that our team discussed earlier would be a good idea.

Do you have any thoughts on this issue? @tigerinus

**Comment by tigerinus** [comment]
The CasaOS installation script has been thoroughly tested on popular setup, but can still be less than comprehensive in certain cases. Within the team we've been actively talking about an abstracted structure for installation script, so that if a specific Linux distribution and/or architecture turns out to be unsupported, CasaOS community can always contribute a installation script as an implementation of the abstracted structure.

For now, I'd say keep collecting solutions/workarounds to the issues you're facing. It's definitely valuable information for implementing specific installation script when we get there.

**Comment by tigerinus** [comment]
For the Docker issue u r facing, I can't really tell what exactly is causing it. Unfortunately I don't have the same device to reproduce.

I think the best way is to reach out to the Docker community for solutions. 

Don't forget to share whatever link to your questions over there so we can learn as well.

**Comment by Virgus** [comment]
Thanks to both of you, I've temporarily solved the issues by moving from debian to ubuntu withe the Focal Armbian release with 4.9 kernel version.

To avoid the kernel upgrade I did what suggested in the aforementioned link. If I'll get more info about debian issues or if Armbian will release newer working kernels with OPi Zero 2 I'll post the news here.

Cheers,
V.
