### ISSUE TITLE
CasaOS is not an os

### ISSUE THREAD

**Issue by daniel-widrick** [IceWhaleTech/CasaOS#35]
So I've seen this project posted around several times now. Discussion universally devolves into confusion about the name.

Perhaps the project maintainers should review the name or lay out a roadmap to become a proper OS?

**Comment by aljaxus** [comment]
It's my first time even hearing about this project, but I'll give my two cents;

Since, as I understand it, this project is mean to be a simple solution for a small homelab *(not like multiple servers in a rack homelab, but a reused PC with a few additional drives in it serving as a simple media server, NAS, etc..)* why not base it off Alpine Linux?
You could basically just make an image that users can flash onto a USB and have a bootable USB drive.
Then you just create a simple web UI that adds few simple functions;
- updating the packages
- simple drive management
  - (un)mounting drives
  - format drive
  - mkfs.X drive

I think that using Alpine and just saving only the necessary files via LBU would make this a great, lightweight, fast and simple to setup tool.

**Comment by jerrykuku** [comment]
> It's my first time even hearing about this project, but I'll give my two cents;
> 
> Since, as I understand it, this project is mean to be a simple solution for a small homelab _(not like multiple servers in a rack homelab, but a reused PC with a few additional drives in it serving as a simple media server, NAS, etc..)_ why not base it off Alpine Linux? You could basically just make an image that users can flash onto a USB and have a bootable USB drive. Then you just create a simple web UI that adds few simple functions;
> 
> * updating the packages
> * simple drive management
>   
>   * (un)mounting drives
>   * format drive
>   * mkfs.X drive
> 
> I think that using Alpine and just saving only the necessary files via LBU would make this a great, lightweight, fast and simple to setup tool.

We will consider your suggestion, thank you.

**Comment by zhuwei** [comment]
that is right

**Comment by JohnGuan** [comment]
Very good question and you're right. CasaOS is not an "OS" yet, but we do aim to make it an "OS". As we said in README and Discord, it's still in the very early stages of CasaOS development.

We just don't want to keep our heads in the sand and wait until we've been working on it for a long time and say, "Hey, we've developed a home cloud system called CasaOS, do you want to try it?" . At this point, I don't think it's going to work much better than it does now.

We want to get it out to the community earlier, and talk to the community, discuss it, grow it, and then present it to more people and say, "Hey, our community built a CasaOS, and I can't believe you don't have one in your house. Everyone in our community is using it in their homes!"

You're also right about the roadmap, we don't have a clear roadmap yet, and that's a topic we'll be discussing here and in Discord, and it's becoming clearer after all this time. I think we'll draft one as soon as possible and discuss it together.

Thank you very much for your attention! You and everyone else are very welcome to suggest ideas that we can discuss together to make CasaOS the best choice for a Home Cloud system!😄

**Comment by Daasin** [comment]
> Very good question and you're right. CasaOS is not an "OS" yet, but we do aim to make it an "OS". As we said in README and Discord, it's still in the very early stages of CasaOS development.
> 
> We just don't want to keep our heads in the sand and wait until we've been working on it for a long time and say, "Hey, we've developed a home cloud system called CasaOS, do you want to try it?" . At this point, I don't think it's going to work much better than it does now.
> 
> We want to get it out to the community earlier, and talk to the community, discuss it, grow it, and then present it to more people and say, "Hey, our community built a CasaOS, and I can't believe you don't have one in your house. Everyone in our community is using it in their homes!"
> 
> You're also right about the roadmap, we don't have a clear roadmap yet, and that's a topic we'll be discussing here and in Discord, and it's becoming clearer after all this time. I think we'll draft one as soon as possible and discuss it together.
> 
> Thank you very much for your attention! You and everyone else are very welcome to suggest ideas that we can discuss together to make CasaOS the best choice for a Home Cloud system!😄

So is it currently a linux-based distro? Or running on top of Ubuntu or something? Not been able to find out by searching it up online and interested in knowing 🤔

**Comment by tigerinus** [comment]
My understanding of OS is that it's a broader term and describes the nature of this project literally - It is a `system` to allow home lab (in team's term `family cloud`) to `operate` different server apps for home use. The currently implementation is an layer on top of the Ubuntu distro with dockerization. 

If we take any other OS we find it's technically the same idea - an layer of applications on top of a distro for specific scenarios. 

The app management could be done via native package management, call it `rpm` or `deb`, or dockerized package management which CasaOS embraces.

**Comment by JohnGuan** [comment]
This is an interesting and ongoing topic for some time, and I'm putting it into the discussion.
