### ISSUE TITLE
机顶盒芯片是晶晨S905L 1G+8G,刷入armbian+casaOS

### ISSUE THREAD

**Issue by jackwei1985** [IceWhaleTech/CasaOS#350]
**Describe the bug**

机顶盒芯片是晶晨S905L 1G+8G,刷入armbian+casaOS,发现存储空间容量不能显示，外接存储也不能显示，动图一直在走动。另外偶尔出现容器不能正常运行情况。

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 6496 
	 - Disk Used: 3519 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 32
	 - System Info: [Ubuntu 18.04.2 LTS   \l Bit:64 Mem:833M Core:4 Linux aml 5.0.2-aml-s905 #5.77 SMP PREEMPT Mon Apr 1 17:23:16 MSK 2019 aarch64 aarch64 aarch64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 103.0.0.0

**Comment by JohnGuan** [comment]
Upgrade the latest system to try. If there are still problems send screenshots to make it easier to find the bugs.

**Comment by JohnGuan** [comment]
Sorry, I will close this issue due to the lack of replies for many days. Feel free to open it if you still have questions.
