### ISSUE TITLE
Https for 2FAuth and Bitwarden

### ISSUE THREAD

**Issue by jidpatch** [IceWhaleTech/CasaOS#356]
i installed those two for self hosted passward manager and TTOT but problem is when i try to create account for bitwarden it dosent allow me because it dosent have https . i am noob so do not know how to start

**Comment by JohnGuan** [comment]
The current CasaOS is not yet finished with https support, it will be added later.
I tried vaultwarden though, only the web version doesn't work, but you can use the Bitwarden client normally.

**Comment by JohnGuan** [comment]
Given that this is an https issue, which will be added in the future, I'm closing this issue for now. However, if you encounter problems, you can always post a comment.
