### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by gngpp** [IceWhaleTech/CasaOS#357]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/51810656/179022514-7a72dd39-e116-47c4-a7f3-24f2675e43d1.png">

- 密码不是登录密码？

**Comment by gngpp** [comment]
> <img alt="image" width="720" src="https://user-images.githubusercontent.com/51810656/179022514-7a72dd39-e116-47c4-a7f3-24f2675e43d1.png">
> 
> * 密码不是登录密码？

<img width="725" alt="image" src="https://user-images.githubusercontent.com/51810656/179022729-e4674b5b-e08a-4190-8cbe-b3b52e84640a.png">

**Comment by LinkLeong** [comment]
Sorry, we have found this issue and it will be fixed in v0.3.4.
很抱歉,我们已经发现了这个问题,该问题会在v0.3.4版本中进行修复.

**Comment by LinkLeong** [comment]
Thanks for your feedback, this issue has been updated in 0.3.4, please reopen the issue if you have new problems.
