### ISSUE TITLE
硬盘读不出来

### ISSUE THREAD

**Issue by 895617** [IceWhaleTech/CasaOS#359]
**Describe the bug**

硬盘驱动挂载正常，但是内容无法访问

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.3
	 - Disk Total: 6595 
	 - Disk Used: 2439 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 0
	 - System Info: [Armbian 20.11 Buster \l Bit:32 Mem:988M Core:4 Linux arm 5.9.0-rc7-aml-s812 #20.11 SMP Wed Oct 20 17:53:31 CST 2021 armv7l GNU/Linux]
	 - Browser: Chrome 
	 - Version: 103.0.0.0

**Comment by JohnGuan** [comment]
Please enter the following command in Terminal/SSH. Send us the information displayed so that we can understand exactly what drives are affected.
```
lsblk -o name,type,size,fstype,tran,subsystems
```

**Comment by JohnGuan** [comment]
Too long no reply, I will close this Issue, if there are still questions please open a new Issue.
