### ISSUE TITLE
Basitlik kolaylık sağlar

### ISSUE THREAD

**Issue by serhatyuksel1** [IceWhaleTech/CasaOS#36]
Tested platform
e.g. linux/amd64,linux/arm-v7,linux-arm64

Please export and upload the configuration file of this application

**Comment by serhatyuksel1** [comment]
Help mini🤣🤣🤣

**Comment by LinkLeong** [comment]
Do you want to share the appfile or do you want my side to give you an appfile, what is the name of the app

**Comment by LinkLeong** [comment]
Since you have been replying for a long time, I am going to close the question, if you have a new question, please resubmit the question
