### ISSUE TITLE
Uninstalling imported docker container apps results in wiping ALL your config data from them

### ISSUE THREAD

**Issue by flamingm0e** [IceWhaleTech/CasaOS#360]
**Describe the bug**
Decided to give CasaOS a trial run this weekend and installed it on my NAS (Ubuntu Server 20.04) which was already running all my media stuff (*arrs, nzbhydra, nzbget, etc).

After install, I notice that it will let me import my running docker containers and so I import them (they were running under compose previously).

After several hours, I notice my hydra container is offline, so I go back into my normal CLI and try to run `docker-compose up -d` like I always have.  The containers were under the control of CasaOS so it errored out.  I went into CasaOS and "uninstalled" the apps so that I could run my compose again.  After uninstalling, and running `docker-compose up -d` again, it rebuilt all my containers.  Only this time ALL my configs/databases/EVERYTHING for these apps is gone.  It appears UNINSTALLING in the CasaOS interface literally removes the data in the bind mounts for the configs.

**To Reproduce**
1. Start a docker-compose/container of a supported app manually
2. Create some basic configs
3. Go to CasaOS interface and IMPORT that container
4. Uninstall the app from CasaOS interface
5. Run your container manually again

**Expected behavior**
I expect that it leaves CONFIG files alone during an uninstall, or provide an OPTION to delete the config directories

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103.0.5060.114

**Additional context**
Luckily it didn't delete any of my media in the bind mounts, from what I can see, but this is a devastating blow.  I have been running these containers for over 7 years using these configs, and never had a problem until now.  Luckily I have an old backup of the config directories and can restore some of it, but this makes me sad to have to reconfigure everything.

**Comment by LinkLeong** [comment]
Thank you very much for your feedback, we are sorry for your experience, we know the importance of data and our current shortage, we will work harder to make casaos more robust, at the same time your problem we take very seriously. We hope you can join the discord group to help and monitor us.

**Comment by ETWang1991** [comment]
in this Issue，load all config data；Display and modify data will be mentioned in a new requirement

**Comment by LinkLeong** [comment]
Released in v0.3.5 to solve the problem
