### ISSUE TITLE
Can't create a storage on a encrypted drive

### ISSUE THREAD

**Issue by vitor-mariano** [IceWhaleTech/CasaOS#373]
**Describe the bug**
I have a clean encrypted ext4 partition. When I select the drive to create a storage, it doesn't show up and displays no errors. So if I format the partition to ext4 unencrypted, it works fine.

**Expected behavior**
It should be possible to use an encrypted partition.

**Screenshots**
ext4 [Encrypted] - Doesn't work
![image](https://user-images.githubusercontent.com/2306588/179554826-ec6a6a01-29af-4f13-91de-9a6917e96541.png)
<img width="656" alt="CleanShot 2022-07-18 at 13 33 08@2x" src="https://user-images.githubusercontent.com/2306588/179559422-e2d036ba-73b0-4f76-9464-d1728864580b.png">

ext4 [Unencrypted] - Works fine
<img width="656" alt="CleanShot 2022-07-18 at 13 30 25@2x" src="https://user-images.githubusercontent.com/2306588/179559100-309a2889-c6b7-44f4-bbc9-20fc2779e3d7.png">

**Desktop (please complete the following information):**
 - OS: Linux (Manjaro 21.3)
 - Browser Chrome 102

**Additional context**
I worked around the problem by manually changing on `/etc/fstab` the mounting point of my partition to `/DATA/MyStorageName`. It doesn't show in the storage inside CasaOS, but at least the folder can be accessible by any CasaOS application.

I don't have any logs. If you need them, please tell me how I can get them.

**Comment by JohnGuan** [comment]
This is really a feature that we didn't support when we designed the storage before.
I don't use such a setup, can you expand on the scenarios and pros and cons of its use?

**Comment by vitor-mariano** [comment]
Sure, I would say the pros and cons are the same of full-disk encryption for the OS: protect drive against unauthorized physical access.

Let's imagine a few scenarios where it's useful. I think it's okay to keep the drive unencrypted for users who build their own server and have it installed at home, and will never get rid of their storage drives. Although (probably) most of the users may send their computers to technical assistance, sell (without formating properly), lose or even have their storage drives stolen. In all those cases, the data inside may be leaked. It's a problem, specially if the user has applications like Nextcloud, Jellyfin, Syncthing, where they will certainly contain sensitive personal or business data.

Just a quick test, I plugged my hard drive on another computer, and I got all my private files accessible.
<img width="614" alt="CleanShot 2022-07-19 at 17 19 12@2x" src="https://user-images.githubusercontent.com/2306588/179840820-e1e26f27-aa88-45e6-825f-3959fe07db4b.png">

The only cons I can imagine is that it makes harder to recover the drive in case of fail.

In my opinion this feature will convince the most concerned users and make CasaOS more popular.

**Comment by JohnGuan** [comment]
I think it's good.
I'll convert this into a feature discussion if you don't mind. So that we can better see what others think.

**Comment by JohnGuan** [comment]
I edited it. You can see what else you have to add.
- https://github.com/IceWhaleTech/CasaOS/discussions/382

I'm going to close this issue for now, and we'll continue in the discussion.

**Comment by mvolpato** [comment]
@vitor-mariano can you provide a mini tutorial for your workaround?
