### ISSUE TITLE
[Alpha][Bug]: Should not include password and token information in /var/log/casaos/log.log

### ISSUE THREAD

**Issue by tigerinus** [IceWhaleTech/CasaOS#384]
### What happened?

![image](https://user-images.githubusercontent.com/7172560/180314206-c0a73668-0fc5-47ea-a4f6-3d8ddc95a87d.png)

The log file `/var/log/casaos/log.log` is accesible by anyone on the host. Any malicious app can get this file and upload to internet.

**Comment by LinkLeong** [comment]
Filtered requests with passwords
