### ISSUE TITLE
Why is there no docker image

### ISSUE THREAD

**Issue by pumpkin-nbc** [IceWhaleTech/CasaOS#39]
Install using command
When the network is bad, it will take a long time to install

**Comment by tigerinus** [comment]
@pumpkin-nbc  Would you be able to provide more information about this issue you are experiencing?

**Comment by pumpkin-nbc** [comment]
@tigerinus There is no agent in China, and the direct download timed out

**Comment by tigerinus** [comment]
> @tigerinus There is no agent in China, and the direct download timed out

有没有试过用中国的镜像源？ 有很多配置教程 https://moththe.com/zh-cn/posts/one-click-script/sh_install_docker/

**Comment by pumpkin-nbc** [comment]
@tigerinus docker已经安装完了 后续的相关环境命令就很慢 如果可以打包成镜像 会快很多

**Comment by JohnGuan** [comment]
我们暂时还没有精力去做完整的系统镜像😂
We don't have the energy to do a full system image yet😂

**Comment by pumpkin-nbc** [comment]
@JohnGuan 码我可以和你们一起😂我想试试帮你们打包镜像看看

**Comment by JohnGuan** [comment]
> @JohnGuan 那我可以和你们一起吗😂我想试试帮你们打包镜像看看

非常欢迎！你可以加我微信：guanningchuang，我们在微信里继续交流！
