### ISSUE TITLE
[Bug]: Docker is not running, try to start

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#392]
### What happened?

When installing a fresh CasaOS we faced with `Docker is not running, try to start` error. (It was originally founded on the previous release)
Expected behavior: Install and run/start Docker without problem.
Reporter: @YoussofKhawaja 

### Screenshots

![unknown](https://media.discordapp.net/attachments/987294590627373066/1000034585360465930/unknown.png)

**Comment by jerrykuku** [comment]
Can you run  ```systemctl is-active docker``` and post me a screenshot?

**Comment by AuthorShin** [comment]
@jerrykuku here you go:
<img src="https://i.ibb.co/GkbGtNf/Screenshot-2022-07-25-200544.png">

**Comment by jerrykuku** [comment]
This looks like a Docker installation failure, but I can't get the real results of its installation, so that's why it appears.
I will find a way to solve this problem.

**Comment by Nick-0098** [comment]
i have the same issue; is your appstore working?

**Comment by AuthorShin** [comment]
@Nick-0098 No, my App Store is not working.

**Comment by screwdriver99** [comment]
I solved the issue.
Open a terminal and install docker manually.
After that, run "sudo systemct start docker"
That's it

**Comment by JohnGuan** [comment]
From: https://discord.com/channels/884667213326463016/937284394681516082/1006752405666410516

@JohnGuan:
> I wonder if it is possible for us to detect the docker snap in the script and then prompt the user on how to uninstall the existing docker snap?

@Hedius :
> Hmm you could check if the command snap is available and then check if it is installed
> snap remove or so

**Comment by jerrykuku** [comment]
The new install script should have fixed the problem, I will close it and if there are still any problems you can reopen it.
