### ISSUE TITLE
[Alpha][Bug]: Tooltip for GitHub Icon is not fit the screen

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#393]
### What happened?

Expected behavior: Fit completely inside the screen. (It was originally founded on the previous release)
Reporter: @AuthorShin @zarevskaya 

### Screenshots

https://media.discordapp.net/attachments/987294590627373066/999989570848444477/Capture_decran_du_2022-07-22_12-41-11.png

**Comment by jerrykuku** [comment]
I know this issue. I will fix it in this week.
