### ISSUE TITLE
[Alpha][Bug]: In case of a fresh install, the store need to be reload a second time to appear

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#395]
### What happened?

In case of a fresh install, the store need to be reload a second time to appear or when you uninstall the CasaOS and install it again.
Expected behavior: Load the store at the first time without need to press on `Retry`.
Reporter: @AuthorShin @zarevskaya 

### Screenshots

https://media.discordapp.net/attachments/987294590627373066/999995005101944832/Capture_decran_du_2022-07-22_13-02-20.png?width=1292&height=539

**Comment by LinkLeong** [comment]
it is woking

**Comment by LinkLeong** [comment]
[](url)
