### ISSUE TITLE
[Alpha][Bug]: stuck on Start Installation... when try to install app on VPS

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#396]
### What happened?

When we want to install an app from store or manually it will stuck on `Start Installation... ` but if we refresh the page we will see that the app has been installed.
Expected behavior: To install the app while showing it's installation process and then have the app with the correct icon on the dashboard without having to refresh the webpage.
Reporter: @AuthorShin @zarevskaya
Extra Note: `I guess we have this stuck on Start Installation... in case of a VPS because the MTU is very high and those packets got fragmented so it will not update the UI but the installation process will move forward and we will see that we have the app installed if we refresh the webpage`

### Screenshots

https://media.discordapp.net/attachments/987294590627373066/1000022690251423845/Capture_decran_du_2022-07-22_14-52-29.png?width=1292&height=790

**Comment by LinkLeong** [comment]
Already fixed, will be released in alpha.2
