### ISSUE TITLE
[Alpha][Bug]: stuck on Start Installation... for few minutes then give you an error in case of a VM under ESXi

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#397]
### What happened?

If you try to install an app from store or manually it will stuck on `Start Installation...` for few minutes and then it will show the following error in case of a VM under ESXi:
`
Error response from daemon: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "
408 Request Time-out
\nYour browser didn't send a complete request in time.\n\n"
`

Expected behavior: To install the app while showing it's installation process and then have the app with the correct icon on the dashboard without showing any error.
Reporter: @AuthorShin 

### Screenshots

https://images-ext-2.discordapp.net/external/OJJU1epQQIVZuoI7Fl-VDee-EdEM83-WiPrrRlmv8X0/https/i.ibb.co/6PNbF1h/Screenshot-2022-07-22-174924.png
https://images-ext-2.discordapp.net/external/0SxxBKk-8Ik74d2lw6Sz2cnPkbtTw9zRPIZfwfXOd34/https/i.ibb.co/z2d3xwm/Screenshot-2022-07-22-180145.png
https://images-ext-1.discordapp.net/external/gW-mEo1V9yNqesvDObBljlQIsTJ4nnOA75ASg1AmRMs/https/i.ibb.co/G7LQ9Pw/Screenshot-2022-07-22-180234.png

**Comment by LinkLeong** [comment]
The problem of staying at "Start Installation" has been fixed, but the problem of error reporting is still being found

**Comment by LinkLeong** [comment]
I haven't found the reason for the problem that prompts the error, so the current version will not be fixed for the time being

**Comment by AuthorShin** [comment]
@LinkLeong Did you fixed the issue, since you closed it?
