### ISSUE TITLE
[Bug]: No network activity under Network Status on VPS

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#398]
### What happened?

No network activity under Network Status when download or uploading file or even installing new app on VPS.
Expected behavior: To show the network activity both Tx/Rx under Network Status.
Reporter: @AuthorShin 

### Screenshots

![Image](https://user-images.githubusercontent.com/3358477/181676240-b5c0f094-9f23-46bc-9264-310b352ee996.png)
<!-- https://images-ext-2.discordapp.net/external/j_9OLBtAVrQ4pMPa_50sXMzqKF48u4jpqPDPHFhOFtk/https/i.ibb.co/8DPBpvB/Screenshot-2022-07-22-212427.png --!>

**Comment by LinkLeong** [comment]
I have not been able to have this problem, will this problem still occur in version 0.3.6?

**Comment by AuthorShin** [comment]
@LinkLeong I think the conclusion for this was in my case I was using Cloudflare proxy which was preventing the Web Socket port from connecting to the client/user browser. 
Which is the situation with [this issue](https://github.com/IceWhaleTech/CasaOS/issues/533) too (Having CasaOS opening random port).
Fix for this would be to access the CasaOS without Couldflare proxy and make sure that random Web Socket port is open (it's safe to be open even on a public instance).
Actual solution for this would be that team merge Web Socket port to Web UI port so you can just enable Web Sockets on your Web UI port on Cloudflare and reverse proxy settings.
Unfortunately, currently the team have no further plans for this merger.

**Comment by AuthorShin** [comment]
If your problems with network widget are not the same with this you can open a detailed issue.

**Comment by LinkLeong** [comment]
No network message due to websocket disconnection. Please check and make sure that there is no firewall or port open. I will close the issue, if in doubt please reopen it
