### ISSUE TITLE
[Alpha][Bug]: Non-essential environment variables in the application after install

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#399]
### What happened?

As originally mentioned here #196 and listed as fixed in here [Change log](https://github.com/IceWhaleTech/CasaOS/blob/main/CHANGELOG.md) under `[0.3.2] - 2022-06-10` but it's still exist and if you install an app you can see these environment variables after installation that you didn't set when installing it and all was generated by app/system after installation.
Expected behavior: To only have/show the environment variables which user set when they installed the app.
Reporter: @AuthorShin 

### Screenshots

https://images-ext-1.discordapp.net/external/wN3tJg_gYF6ICAZ24PtBJYZhZtgDPc6Wd9s9OZHejQs/https/i.ibb.co/StSLPB4/Screenshot-2022-07-22-213047.png?width=431&height=849

**Comment by LinkLeong** [comment]
Fixed, it will appear in the alpha.2 version
