### ISSUE TITLE
Broken link in the dashboard after first deployment

### ISSUE THREAD

**Issue by xinity** [IceWhaleTech/CasaOS#4]
the "Install your first App" link in the casaOS dashboard after the installation is broken, it sends to: `https://docs.zimaboard.com/casaos/install-app.html`

while it should send to `https://docs.zimaboard.com/casaos/tutorial/#install-your-first-app`

**Comment by JohnGuan** [comment]
Sorry for the late reply.
It's not actually a link error, it's that we haven't prepared this part of the tutorial yet.
What do you think of the tutorial where we plan to use the file browser as the first app installation?
