### ISSUE TITLE
[Bug]: App Store stuck at loading

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#406]
### What happened?

After installed a fresh CasaOS on Ubuntu when try to open the App Store it will stick at loading.
Expected behavior: To load the App Store without problem.
Reporter: @AuthorShin 

### Screenshots

<img src="https://i.ibb.co/nbkFgr4/Screenshot-2022-07-25-201440.png">

**Comment by InikoMatthewPro** [comment]
me too

**Comment by Fireangel85** [comment]
Hi,
I have the same problem!

**Comment by screwdriver99** [comment]
Same problem here

**Comment by screwdriver99** [comment]
I solved the issue.
Open a terminal and install docker manually.
After that, run "sudo systemct start docker"
That's it

**Comment by Fireangel85** [comment]
Hi Lorenzo,
the problem was the OS version not supporting Docker 20.x, after updating
the OS now the app store works correctly

Il giorno dom 31 lug 2022 alle ore 15:04 Lorenzo Battini <
***@***.***> ha scritto:
