### ISSUE TITLE
Apps slider Icons flickering - website

### ISSUE THREAD

**Issue by edgarwe** [IceWhaleTech/CasaOS#409]
**Describe the bug**
Icons on the slider have some flickering, so it looks like ticky

**To Reproduce**
1. Go to ['casaos.io'](https://www.casaos.io/)
2. Scroll down to Apps
3. See error

**Expected behavior**
Icons slide should not be fluid.

**Screenshots**
![Capture d’écran 2022-07-26 à 10 31 49](https://user-images.githubusercontent.com/47147820/180961359-b5c92b47-a97b-4287-9d04-54f1e525669b.png)

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Browser Firefox Dev edition
 - Version 103.0b9 

**How to fix**
Add a `transform: translate(0)` to this selector : `.app-list .is-72x72 img`

**Comment by jerrykuku** [comment]
Thanks, I have updated this issue.  I'm going to close this issue, if the problem still exists you can reopen it.
