### ISSUE TITLE
Openwrt not support

### ISSUE THREAD

**Issue by duaneya** [IceWhaleTech/CasaOS#41]
_____                 ____   _____
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___
 | |    / _` / __|/ _` | |  | |\___ \
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/

   --- Made by IceWhale with YOU ---

df: unrecognized option: output=size
BusyBox v1.33.1 (2021-09-10 10:29:33 UTC) multi-call binary.

Usage: df [-PkmhT] [FILESYSTEM]...

Print filesystem usage statistics

        -P      POSIX output format
        -k      1024-byte blocks (default)
        -m      1M-byte blocks
        -h      Human readable (e.g. 1K 243M 2G)
        -T      Print filesystem type
bash: line 45: / 1024 / 1024: syntax error: operand expected (error token is "/ 1024 / 1024")

**Comment by jerrykuku** [comment]
Sorry, we currently do not support openwrt.

**Comment by tigerinus** [comment]
@duaneya - can you try installing `coreutils` on openwrt and see if this issue is gone? The package provides an actual implementation of `df` command versus the one built into `busybox`.

See details at https://openwrt.org/packages/pkgdata/coreutils
