### ISSUE TITLE
关于容器卸载问题

### ISSUE THREAD

**Issue by gngpp** [IceWhaleTech/CasaOS#416]
> 未来能否加个容器卸载保留挂载备份的数据？只是单纯删除容器。
- 因为今早跑pcdn容器卸载，结果把挂载的几百G数据给删掉了。

**Comment by gngpp** [comment]
> > 未来能否加个容器卸载保留挂载备份的数据？只是单纯删除容器。
> 
> * 因为今早跑pcdn容器卸载，结果把挂载的几百G数据给删掉了。

这个的前提条件是，我这个容器是手动导入的。（方便排除其他条件引发的问题）

**Comment by ETWang1991** [comment]
This problem will be transformed into a requirement. If the config folder is not empty when the APP is uninstalled, the user will be asked twice whether to delete config folder.
