### ISSUE TITLE
[Bug]: Cant create aditional storage

### ISSUE THREAD

**Issue by gswec2005** [IceWhaleTech/CasaOS#418]
### What happened?

Stuck on "creation in progress" screen, after trying to create a secondary storage.

### Screenshots

- try to create storage:

![image](https://user-images.githubusercontent.com/13799808/181496534-795626f8-05fc-4d3f-835c-1a21037df1f3.png)

- stuck on this screen
![image](https://user-images.githubusercontent.com/13799808/181501317-6becdb5a-399f-499d-9384-336877b7f87c.png)

- forced a reboot and storage1 showedup but it not formated (i created on "format and create"). I saw a file i created using webmin to test
![image](https://user-images.githubusercontent.com/13799808/181501898-43b72449-d97e-4ab6-b17d-92aec1fb986f.png)

- some aditional images
![image](https://user-images.githubusercontent.com/13799808/181502315-c6944ce7-256c-42b8-a628-478b6d96dfc3.png)

- disks on CasaOS
![image](https://user-images.githubusercontent.com/13799808/181502339-ac6d93aa-9de2-4844-80b4-11de2c664876.png)

- proxmox config
![image](https://user-images.githubusercontent.com/13799808/181502384-c356f253-d15b-4810-bc6e-1bf3ce9b4ca2.png)

**Comment by LinkLeong** [comment]
Fixed in 0.3.4.alpha.3

**Comment by klisza1993** [comment]
ive got same issue so waintg for an update ;)

**Comment by llwaini** [comment]
CasaOS V0.3.7 has fixed Format and Create, we recommend that you wait until the release of V0.3.7 (the latest version will be released soon, please check Discord news - https://discord.com/invite/Gx4BCEtHjx)

**Comment by raller1028** [comment]
We will close this issue, please resubmit if you have any questions
