### ISSUE TITLE
Unable download App

### ISSUE THREAD

**Issue by Fireangel85** [IceWhaleTech/CasaOS#420]
**Describe the bug**
When I open the App Store, no apps appear and the circle keeps spinning

**To Reproduce**
1. Go to Home
2. Click on APP store

**Expected behavior**
See list of app to download

**Screenshots**
![image](https://user-images.githubusercontent.com/91123307/181800725-25ad375d-bf87-408a-983e-7437fb208b44.png)

**Desktop (please complete the following information):**
OS: linux
 - CasaOS Version: 0.3.4
 - Disk Total: 13352 
 - Disk Used: 6257 
 - System Info: [Raspbian GNU/Linux 9   \l Bit:32 Mem:926M Core:4 Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux]
 - Remote Version: 0.3.4
 - Browser: Chrome 
 - Version: 103.0.0.0
 - 
**Additional context**

**Comment by screwdriver99** [comment]
Same problem here

**Comment by screwdriver99** [comment]
I solved the issue.
Open a terminal and install docker manually.
After that, run "sudo systemct start docker"
That's it

**Comment by Fireangel85** [comment]
Thanks for support but my problem is different.
the problem was the OS version not supporting Docker 20.x, after updating the OS now the app store works correctly
