### ISSUE TITLE
[FAILED] error 1 in command: $sudo_cmd mv -f "$casa_conf_path/conf.ini.sample" "$casa_conf_path/conf.ini"

### ISSUE THREAD

**Issue by atto1** [IceWhaleTech/CasaOS#421]
[  OK  ] Docker Successfully installed.
[ INFO ] Downloading CasaOS for linux/amd64...
[ INFO ] https://github.com/IceWhaleTech/CasaOS/releases/download/v0.3.4/linux-amd64-casaos.tar.gz
[ INFO ] Extracting...
[ INFO ] Putting CasaOS in /usr/local/bin (may require password)
[ INFO ] Putting CasaOS Configuration file in /casaOS/server (may require password)
mv: 无法获取'/casaOS/server/conf/conf.ini.sample' 的文件状态(stat): 没有那个文件或目录
[FAILED] error 1 in command: $sudo_cmd mv -f "$casa_conf_path/conf.ini.sample" "$casa_conf_path/conf.ini"

**Comment by chsdwyl** [comment]
我也是同样问题，casaos真傻逼

**Comment by chsdwyl** [comment]
[ INFO ] Putting CasaOS in /usr/local/bin (may require password)
[ INFO ] Putting CasaOS Configuration file in /casaOS/server (may require password)
mv: cannot stat '/casaOS/server/conf/conf.ini.sample': No such file or directory
[FAILED] error 1 in command: $sudo_cmd mv -f "$casa_conf_path/conf.ini.sample" "$casa_conf_path/conf.ini"



草你妈隔壁，太折磨小白了。

**Comment by JohnGuan** [comment]
@chsdwyl 请注意你的言辞，别这么激动。我们正在跟进这个问题。
We are following up on this issue.
@jerrykuku I was also contacted by other users today with this problem, but I didn't find this command in the script.
@tigerinus Please assist Jerry appropriately and consider a follow-up to optimize the installation script.

**Comment by jerrykuku** [comment]
I guess you might be using an old installation script, please try it with the new installation script. 
```curl -fsSL https://get.casaos.io | bash```.
We have also updated the old installation script.
If the problem persists you can give feedback here and I will help you solve it as soon as possible.

**Comment by chsdwyl** [comment]
> 我猜您可能使用的是旧的安装脚本，请尝试使用新的安装脚本。 `curl -fsSL https://get.casaos.io | bash`. 我们还更新了旧的安装脚本。 如果问题仍然存在，您可以在这里反馈，我会尽快帮助您解决。

我日你妈个逼

**Comment by jerrykuku** [comment]
The new install script should have fixed the problem, I will close it and if there are still any problems you can reopen it.
