### ISSUE TITLE
Error response from daemon: network oasis not found

### ISSUE THREAD

**Issue by TOomaAh** [IceWhaleTech/CasaOS#43]
Hello, when I try to "install" a container I get the following error: Error response from daemon: network oasis not found

**To Reproduce**
1. Go to '+ App'
2. Click on 'Install'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/28620362/144592411-b9f67937-c3d9-4856-a908-a2e0f4695140.png)

**Desktop:**
 - OS: Ubuntu 20.04 - LTS 64bits
 - Browser Chrome
 - Version latest

**Additional context**
In case I installed docker with snap. I can't install it the normal way.

**Comment by TOomaAh** [comment]
Ok. I run this command and it's work `sudo docker network create oasis`

**Comment by TOomaAh** [comment]
Is it possible to change the path '/DATA/' by default for container?

**Comment by LinkLeong** [comment]
thinks for your feedback, Can you take a screenshot of your app settings? So that we can quickly locate the problem

**Comment by TOomaAh** [comment]
Sorry for the delay in my reply. Basically I put for example '/mnt/user/Media' for my media path. But when I go back to the container settings '/DATA/' appears. Is it possible to change the default path '/DATA'/ so that it is in a specific folder on another disk and not in the root of the system disk.

![image](https://user-images.githubusercontent.com/28620362/145109438-0ca08767-f353-41e3-b7da-b8499f1f5c89.png)

**Comment by tigerinus** [comment]
> Is it possible to change the path '/DATA/' by default for container?

I think parameterizing all paths of CasaOS is generally a good idea. It gives more flexibility for integration with different environments. Not sure what the team thinks @LinkLeong @JohnGuan ?

**Comment by JohnGuan** [comment]
> > Is it possible to change the path '/DATA/' by default for container?
> 
> I think parameterizing all paths of CasaOS is generally a good idea. It gives more flexibility for integration with different environments. Not sure what the team thinks @LinkLeong @JohnGuan ?

This is in our plan 😁

**Comment by JohnGuan** [comment]
IIRC, this issue has been fixed, right? @LinkLeong

**Comment by JohnGuan** [comment]
Just confirmed that the problem has been fixed
