### ISSUE TITLE
sha256 App apeared after update to 0.3.4

### ISSUE THREAD

**Issue by gswec2005** [IceWhaleTech/CasaOS#430]
**Describe the bug**
After update from 0.3.3 to 0.3.4, an sha256 app appeared in dashboard.
- this app dont open configuration screen
- this app dont uninstall
- this app dont start

**To Reproduce**
1. Have a production 0.3.3 system version
2. Update using dropdown menu to 0.3.4 system version

**Expected behavior**
After update, only my apps and CasaOS native apps appear on dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/13799808/182956979-467ffd70-55a6-44d3-913d-96a303051dfb.png)

**Desktop (please complete the following information):**
 - OS: CasaOS 0.3.4
 - Browser: Chrome
 - Version: 103.0.5060.134 (oficial version) 64 bits

**Comment by JohnGuan** [comment]
Does this appear in the list of Apps or in Existing Docker Apps?

**Comment by gswec2005** [comment]
> Does this appear in the list of Apps or in Existing Docker Apps?

Youn say down here? It Only appear on CasaOS Dashboard.

![image](https://user-images.githubusercontent.com/13799808/183891651-b817c318-2d4c-4d62-824b-28053e37fda2.png)

**Comment by JohnGuan** [comment]
@LinkLeong Do you have any ideas?

**Comment by LinkLeong** [comment]
You can run 'docker inspect sha256 | grep -i labels -C 6' and post the contents

**Comment by gswec2005** [comment]
> You can run 'docker inspect sha256 | grep -i labels -C 6' and post the contents @gswec2005

Done!

![image](https://user-images.githubusercontent.com/13799808/184051545-d2ef65db-95f3-4172-8e8e-d89359215764.png)

**Comment by LinkLeong** [comment]
sha256 change to application name or id

**Comment by gswec2005** [comment]
there is no application name, or container to obtain the "containerID"

**Comment by LinkLeong** [comment]
Does this (`sha256`) application still exist, or is this problem currently solved?

**Comment by gswec2005** [comment]
> Does this (`sha256`) application still exist, or is this problem currently solved?

It Exists, like in the start of this post
![image](https://user-images.githubusercontent.com/13799808/184055677-47d0c260-5990-4e2e-9791-00ee674844fc.png)

**Comment by LinkLeong** [comment]
> > Does this (`sha256`) application still exist, or is this problem currently solved?
> 
> It Exists, like in the start of this post ![image](https://user-images.githubusercontent.com/13799808/184055677-47d0c260-5990-4e2e-9791-00ee674844fc.png)

Can you take a bigger screenshot?

**Comment by gswec2005** [comment]
> a

yep

![image](https://user-images.githubusercontent.com/13799808/184056406-416e7f99-3156-4d97-9c3f-71f013c688e4.png)

**Comment by LinkLeong** [comment]
Can you take a picture of the application settings, I need to see the configuration items

**Comment by gswec2005** [comment]
> Can you take a picture of the application settings, I need to see the configuration items

no, i can't.

![image](https://user-images.githubusercontent.com/13799808/184058009-3ea18f11-c0d1-461a-8310-c93bfb22e65f.png)

**Comment by LinkLeong** [comment]
![image](https://user-images.githubusercontent.com/13556972/184058135-dd100c21-a2db-48ae-9add-b420b64d906e.png)
Aren't there three dots here?

**Comment by LinkLeong** [comment]
Put the cursor on

**Comment by gswec2005** [comment]
> ![image](https://user-images.githubusercontent.com/13556972/184058135-dd100c21-a2db-48ae-9add-b420b64d906e.png) Aren't there three dots here?

yes, have three dots, but it don't open config screen after clicking in the settings option
![image](https://user-images.githubusercontent.com/13799808/184058300-fee7ee3e-fedc-4ea2-8c98-a6d657613907.png)

**Comment by LinkLeong** [comment]
Okay, you can run `docker ps -a` and take a screenshot

**Comment by gswec2005** [comment]
![image](https://user-images.githubusercontent.com/13799808/184058902-40c39010-836b-43d1-8646-277dcbd884c1.png)

**Comment by LinkLeong** [comment]
![image](https://user-images.githubusercontent.com/13556972/184061138-02ec3888-d8ef-47a2-be4e-f7f79fe64bb1.png)
It looks like this application, you can run `docker inspect a5986b0b709f | grep -i labels -C 20` . If you need to remove the application you can do `docker rm a5986b0b709f `

**Comment by LinkLeong** [comment]
Sorry for taking so long to reply, you can find "sha256" in the path above


![Image](https://user-images.githubusercontent.com/13556972/184777682-109648d8-fd3f-4b92-9bae-13174de314a6.png)

**Comment by gswec2005** [comment]
> Sorry for taking so long to reply, you can find "sha256" in the path above
> No problem <3

![image](https://user-images.githubusercontent.com/13799808/184874693-43eb62c3-a7a7-44d7-b373-92cc09e77155.png)

**Comment by gswec2005** [comment]
i found that 8384 port is a SyncThing port

![image](https://user-images.githubusercontent.com/13799808/184875043-f04f7e94-7e7f-4ac3-afe2-26e9776e832e.png)


very weird :(

**Comment by LinkLeong** [comment]
Yes, I found this problem, but you need to solve it manually first, sha256 is syncthing, you can remove it manually
