### ISSUE TITLE
AppStore does not load, and i can't install apps

### ISSUE THREAD

**Issue by TommasoRonchin** [IceWhaleTech/CasaOS#438]
The App Store does not load and there is an error message in the browser console

![image](https://user-images.githubusercontent.com/71636408/183460663-62a9d49b-7f66-4ffb-8e36-5483a35f1e29.png)

System info:
 - OS: Linux Ubuntu, on Raspberry pi 4 8gb
 - Browser chrome and safari (on iphone)
 - Version v0.3.4

Please help me!

**Comment by ressonix** [comment]
Running into the same issue here. 
<img width="549" alt="Screen Shot 2022-08-08 at 11 40 42 PM" src="https://user-images.githubusercontent.com/60057409/183559110-234bd13f-f457-4c89-bd42-c92271075f77.png">

**Comment by ressonix** [comment]
If this is a new Casa OS installation, it's possible you might need to update the OS:
`sudo apt update && upgrade`

Then re-run the Casa OS installation script to install Docker. This seemed to have resolved the issue for me.

**Comment by LinkLeong** [comment]
@TommasoRonchin Will other applications install properly? I need to rule out if it's a network issue!
You can try @ressonix's method

**Comment by LinkLeong** [comment]
Since you have not replied for a long time, we will close this question, if you have questions, you can resubmit Issus

**Comment by not-amplify** [comment]
@LinkLeong im still having this same issue
