### ISSUE TITLE
Update Error CasaOS 0.21 to 0.22

### ISSUE THREAD

**Issue by chicato83** [IceWhaleTech/CasaOS#44]
**Describe the bug**

**To Reproduce**
1. Go to 'settings'
2. Click on 'Update'
3. See error

**Expected behavior**
Update CasaOS.
**Screenshots**
Update bug load.
![update](https://user-images.githubusercontent.com/11451030/144698644-c5d9ffd2-7ca6-4dfd-b4a8-177227a038f3.png)
Log Error.
![casa os error update](https://user-images.githubusercontent.com/11451030/144698553-3e526d8c-3b74-481b-9392-5a154d52c552.png)

**Desktop (please complete the following information):**
 - OS: [Raspberry Pi OS lasts]
 - Browser [Brave lasts]
 - Version [CasaOS 0.21]

**Additional context**

[ERROR][system.go:25]2021/12/04 01:20:03 [[[ INFO ] Downloading CasaOS for linux/armv7... [ INFO ] https://github.com/IceWhaleTech/CasaOS/releases/download/v0.2.2/linux-armv7-casaos.tar.gz Aborted, error 22 in command: ${net_getter} "$casa_url" > "$PREFIX/tmp/$casa_file"]]

**Comment by LinkLeong** [comment]
Thank you for your feedback, we found the problem, the fix did not occur so soon, there will be two versions waiting for you to solve the problem.

You can re-execute the following installation to get to the latest version.

**Comment by chicato83** [comment]
Thanks for the fast reply, I did it, and now it updated. Thanks.

**Comment by chicato83** [comment]
I would like to help the project translating to Spanish if you decide to add more language to the casaOS.

**Comment by jerrykuku** [comment]
> I would like to help the project translating to Spanish if you decide to add more language to the casaOS.

We are discussing adding multiple languages and I believe there will be an answer soon. Thank you for your enthusiasm.

**Comment by LinkLeong** [comment]
@chicato83 This problem is fixed in the new version, if the update fails, you can reinstall

**Comment by chicato83** [comment]
Yes, I updated to v0.2.3 without any problems.
Thanks.

**Comment by chicato83** [comment]
About the translation of casaOS I am still interesting to help.

**Comment by JohnGuan** [comment]
> About the translation of casaOS I am still interesting to help.

We are just getting started with i18n and you can currently see the language files here:
[https://github.com/IceWhaleTech/CasaOS-UI/tree/main/src/assets/lang](https://github.com/IceWhaleTech/CasaOS-UI/tree/main/src/assets/lang)

But there is no documentation yet on how to contribute languages, so if you are interested you are welcome to contact me in [Discord](https://discord.gg/knqAbbBbeX) and we can explain to you how to do the translation.
