### ISSUE TITLE
Ram 0 byte problem

### ISSUE THREAD

**Issue by AlexFigas** [IceWhaleTech/CasaOS#440]
**Describe the bug**
Ram usage shows as 0 bytes on all apps.

**To Reproduce**
1. Go to casaos ui
2. Click on 'System Status' and then 'RAM'
3. See error

**Expected behavior**
Show correct ram usage

**Screenshots**
![imagem](https://user-images.githubusercontent.com/65889776/183673144-d58a0b99-331e-4715-ad2e-214922f1d680.png)

**Desktop (please complete the following information):**
 - OS: DietPi
 - Browser: Firefox
 - Version:  v0.3.4

**Comment by GutsyHeart** [comment]
/boot/cmdline.txt
`cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`

**Comment by AlexFigas** [comment]
> /boot/cmdline.txt `cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`

Did that, but now Transmission does not open.

**Comment by AlexFigas** [comment]
it works! thank you!
