### ISSUE TITLE
[App Request] n8n

### ISSUE THREAD

**Issue by JohnGuan** [IceWhaleTech/CasaOS#443]
### App Information

- Name:  n8n
- Short Description: Free and open fair-code licensed node based Workflow Automation Tool. Easily automate tasks across different services.
- Official Website: https://n8n.io/
- GitHub Repository: https://github.com/n8n-io/n8n 
- Docker Image: n8nio/n8n

### Why do you want this app?

- #391 
> @Ploonet:
> n8n is an automation platform, similar to Zapier or Make. What's unique about it is that they offer a self-hosted version. Having it on CasaOS would be great in my opinion.

**Comment by YoussofKhawaja** [comment]
n8n added
