### ISSUE TITLE
[Bug] installation issue on wsl2

### ISSUE THREAD

**Issue by MrEnder0** [IceWhaleTech/CasaOS#447]
**Describe the bug**
When running "curl -fsSL https://get.casaos.io | bash" it fails on WSL with the error "System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down"

**To Reproduce**
1. Use wsl2 on windows 11
2. Run "curl -fsSL https://get.casaos.io | bash"
3. Let it run through the installation
4. Get error

**Expected behavior**
Installs and runs correctly

**Screenshots**
https://i.imgur.com/ZAOE50G.png

**Desktop (please complete the following information):**
 - Windows 11 on wsl2
 - Lastest version

**Additional context**
This is most likely an issue with docker because when running "sudo systemctl start docker" I get the same exact error. This can be gotten around with "sudo /etc/init.d/docker start"

**Comment by tigerinus** [comment]
@MrEnder0 - scratch what I said in 2022.

You actually can install CasaOS on WSL2 in 2023, see https://blog.casaos.io/blog/15.html

Disclaimer - WSL2 is still not supported by CasaOS team. :)
