### ISSUE TITLE
[Alpha][Bug] Storage does not use custom names

### ISSUE THREAD

**Issue by gswec2005** [IceWhaleTech/CasaOS#454]
### What happened?

I created 2 storages, using 2 virtual disks on QEMU, i put "StorageA" and "StorageB" for his names, but CasaOS used default ones.

### Screenshots

![image](https://user-images.githubusercontent.com/13799808/184728266-950db3b1-9fe4-4724-a6f3-842da52508bc.png)

**Comment by LinkLeong** [comment]
1. Is this a disk?
2.Can "StorageA" and "StorageB" be displayed correctly on Win

**Comment by gswec2005** [comment]
> 1. Is this a disk?
Yes, 2 virtual disks 
![image](https://user-images.githubusercontent.com/13799808/184786070-aaa7a32d-644b-4cc5-8f92-b3fb6e85cfa9.png)

> 2.Can "StorageA" and "StorageB" be displayed correctly on Win
We cant share this "Locations with the new sharing feature"

**Comment by LinkLeong** [comment]
Where did you modify the "StroageA", can you take a screenshot?

**Comment by gswec2005** [comment]
> Where did you modify the "StroageA", can you take a screenshot?

When creating a new Storage, here:
![image](https://user-images.githubusercontent.com/13799808/184875443-9348b8cb-a0b6-4d10-b196-2eb16dddca47.png)
![image](https://user-images.githubusercontent.com/13799808/184875851-f74e3be9-f48e-40f3-b7a4-39378bc0df8f.png)

**Comment by LinkLeong** [comment]
Already fixed, will be updated in alpha.2
