### ISSUE TITLE
[Alpha][Bug] Cant create folders or files in the shared location

### ISSUE THREAD

**Issue by gswec2005** [IceWhaleTech/CasaOS#455]
### What happened?

I shared my folders, using the new feature and i cant create folders or files in the shared location

### Screenshots

![image](https://user-images.githubusercontent.com/13799808/184732107-060f0c3f-e40c-4f38-94b0-4b8e2f29bd93.png)

![image](https://user-images.githubusercontent.com/13799808/184742646-791977e9-2d96-42dc-b411-692c0531260c.png)

**Comment by gswec2005** [comment]
Apparently, this occurred when accessing \\[address]\data\[createdstoragename]

when using a generic folder, like MEDIA, its working
![image](https://user-images.githubusercontent.com/13799808/184732332-772d3c41-aafb-40a8-9246-4cfbd46f10c3.png)

**Comment by LinkLeong** [comment]
Resolved, will be released in the next alpha.2 version
