### ISSUE TITLE
[Bug]  Created Storage disappear after reboot

### ISSUE THREAD

**Issue by gswec2005** [IceWhaleTech/CasaOS#456]
### What happened?

I created 2 Storages for some alpha tests. While finding another bugs, i reboot, and one of created Storages disappear.

### Screenshots

![image](https://user-images.githubusercontent.com/13799808/184876219-d29890ca-6a1d-4f0d-813b-8f7acc299394.png)

**Comment by LinkLeong** [comment]
![Image](https://user-images.githubusercontent.com/13556972/185069491-5902b6c7-bd7c-43aa-917d-3fe43af7a7c8.jpg)

I can not reproduce the problem, you try a few more times to see if the problem will be reproduced

**Comment by ETWang1991** [comment]
if Created succeed，its bug

**Comment by gswec2005** [comment]
> ![Image](https://user-images.githubusercontent.com/13556972/185069491-5902b6c7-bd7c-43aa-917d-3fe43af7a7c8.jpg)
> 
> I can not reproduce the problem, you try a few more times to see if the problem will be reproduced

Tried some more times, and the problem occurs all times.

**Comment by gswec2005** [comment]
@LinkLeong  here the result of lsblk -O -J

rsantos@vmcasaosalpha:~$ lsblk -O -J
{
   "blockdevices": [
      {"name":"loop0", "kname":"loop0", "path":"/dev/loop0", "maj:min":"7:0", "fsavail":"0", "fssize":"62M", "fstype":"squashfs", "fsused":"62M", "fsuse%":"100%", "mountpoint":"/snap/core20/1593", "label":null, "uuid":null, "ptuuid":null, "pttype":null, "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":true, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"62M", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":256, "type":"loop", "disc-aln":0, "disc-gran":"4K", "disc-max":"4G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":null, "hctl":null, "tran":null, "subsystems":"block", "rev":null, "vendor":null, "zoned":"none"},
      {"name":"loop1", "kname":"loop1", "path":"/dev/loop1", "maj:min":"7:1", "fsavail":"0", "fssize":"62M", "fstype":"squashfs", "fsused":"62M", "fsuse%":"100%", "mountpoint":"/snap/core20/1611", "label":null, "uuid":null, "ptuuid":null, "pttype":null, "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":true, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"62M", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":256, "type":"loop", "disc-aln":0, "disc-gran":"4K", "disc-max":"4G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":null, "hctl":null, "tran":null, "subsystems":"block", "rev":null, "vendor":null, "zoned":"none"},
      {"name":"loop2", "kname":"loop2", "path":"/dev/loop2", "maj:min":"7:2", "fsavail":"0", "fssize":"67.3M", "fstype":"squashfs", "fsused":"67.3M", "fsuse%":"100%", "mountpoint":"/snap/lxd/21835", "label":null, "uuid":null, "ptuuid":null, "pttype":null, "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":true, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"67.2M", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":256, "type":"loop", "disc-aln":0, "disc-gran":"4K", "disc-max":"4G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":null, "hctl":null, "tran":null, "subsystems":"block", "rev":null, "vendor":null, "zoned":"none"},
      {"name":"loop3", "kname":"loop3", "path":"/dev/loop3", "maj:min":"7:3", "fsavail":"0", "fssize":"67.9M", "fstype":"squashfs", "fsused":"67.9M", "fsuse%":"100%", "mountpoint":"/snap/lxd/22753", "label":null, "uuid":null, "ptuuid":null, "pttype":null, "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":true, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"67.8M", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":256, "type":"loop", "disc-aln":0, "disc-gran":"4K", "disc-max":"4G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":null, "hctl":null, "tran":null, "subsystems":"block", "rev":null, "vendor":null, "zoned":"none"},
      {"name":"loop4", "kname":"loop4", "path":"/dev/loop4", "maj:min":"7:4", "fsavail":"0", "fssize":"43.6M", "fstype":"squashfs", "fsused":"43.6M", "fsuse%":"100%", "mountpoint":"/snap/snapd/14978", "label":null, "uuid":null, "ptuuid":null, "pttype":null, "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":true, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"43.6M", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":256, "type":"loop", "disc-aln":0, "disc-gran":"4K", "disc-max":"4G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":null, "hctl":null, "tran":null, "subsystems":"block", "rev":null, "vendor":null, "zoned":"none"},
      {"name":"loop5", "kname":"loop5", "path":"/dev/loop5", "maj:min":"7:5", "fsavail":"0", "fssize":"47M", "fstype":"squashfs", "fsused":"47M", "fsuse%":"100%", "mountpoint":"/snap/snapd/16292", "label":null, "uuid":null, "ptuuid":null, "pttype":null, "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":true, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"47M", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":256, "type":"loop", "disc-aln":0, "disc-gran":"4K", "disc-max":"4G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":null, "hctl":null, "tran":null, "subsystems":"block", "rev":null, "vendor":null, "zoned":"none"},
      {"name":"sda", "kname":"sda", "path":"/dev/sda", "maj:min":"8:0", "fsavail":null, "fssize":null, "fstype":null, "fsused":null, "fsuse%":null, "mountpoint":null, "label":null, "uuid":null, "ptuuid":"86ccc419-5d14-49ad-9dc8-96398fe3c8de", "pttype":"gpt", "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":false, "rm":false, "hotplug":false, "model":"QEMU_HARDDISK", "serial":"QM00005", "size":"64G", "state":"running", "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":64, "type":"disk", "disc-aln":0, "disc-gran":"512B", "disc-max":"2G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":true, "pkname":null, "hctl":"2:0:0:0", "tran":"sata", "subsystems":"block:scsi:pci", "rev":"2.5+", "vendor":"ATA     ", "zoned":"none",
         "children": [
            {"name":"sda1", "kname":"sda1", "path":"/dev/sda1", "maj:min":"8:1", "fsavail":null, "fssize":null, "fstype":null, "fsused":null, "fsuse%":null, "mountpoint":null, "label":null, "uuid":null, "ptuuid":"86ccc419-5d14-49ad-9dc8-96398fe3c8de", "pttype":"gpt", "parttype":"21686148-6449-6e6f-744e-656564454649", "partlabel":null, "partuuid":"777173f6-5105-47ff-882e-5d20b1ef9247", "partflags":null, "ra":128, "ro":false, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"1M", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":64, "type":"part", "disc-aln":0, "disc-gran":"512B", "disc-max":"2G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":true, "pkname":"sda", "hctl":null, "tran":null, "subsystems":"block:scsi:pci", "rev":null, "vendor":null, "zoned":"none"},
            {"name":"sda2", "kname":"sda2", "path":"/dev/sda2", "maj:min":"8:2", "fsavail":"49.7G", "fssize":"62.9G", "fstype":"ext4", "fsused":"10G", "fsuse%":"16%", "mountpoint":"/", "label":null, "uuid":"cd34fcea-308e-448e-aa83-e6fe26f93b0b", "ptuuid":"86ccc419-5d14-49ad-9dc8-96398fe3c8de", "pttype":"gpt", "parttype":"0fc63daf-8483-4772-8e79-3d69d8477de4", "partlabel":null, "partuuid":"643d1fe2-e06c-43f7-a9b4-857133094d82", "partflags":null, "ra":128, "ro":false, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"64G", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":64, "type":"part", "disc-aln":0, "disc-gran":"512B", "disc-max":"2G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":true, "pkname":"sda", "hctl":null, "tran":null, "subsystems":"block:scsi:pci", "rev":null, "vendor":null, "zoned":"none"}
         ]
      },
      {"name":"sdb", "kname":"sdb", "path":"/dev/sdb", "maj:min":"8:16", "fsavail":null, "fssize":null, "fstype":null, "fsused":null, "fsuse%":null, "mountpoint":null, "label":null, "uuid":null, "ptuuid":"a1d36b90-4887-4408-b732-43b438d8a4ca", "pttype":"gpt", "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":false, "rm":false, "hotplug":false, "model":"QEMU_HARDDISK", "serial":"QM00007", "size":"32G", "state":"running", "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":64, "type":"disk", "disc-aln":0, "disc-gran":"512B", "disc-max":"2G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":true, "pkname":null, "hctl":"3:0:0:0", "tran":"sata", "subsystems":"block:scsi:pci", "rev":"2.5+", "vendor":"ATA     ", "zoned":"none",
         "children": [
            {"name":"sdb1", "kname":"sdb1", "path":"/dev/sdb1", "maj:min":"8:17", "fsavail":"31G", "fssize":"31.3G", "fstype":"ext4", "fsused":"24K", "fsuse%":"0%", "mountpoint":"/DATA/Storage_sdb1", "label":null, "uuid":"2b455184-9896-4a74-a016-c201e142c49f", "ptuuid":"a1d36b90-4887-4408-b732-43b438d8a4ca", "pttype":"gpt", "parttype":"0fc63daf-8483-4772-8e79-3d69d8477de4", "partlabel":"primary", "partuuid":"0804a916-a7ce-45ab-9d02-b6e1763cf2dd", "partflags":null, "ra":128, "ro":false, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"32G", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":64, "type":"part", "disc-aln":0, "disc-gran":"512B", "disc-max":"2G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":true, "pkname":"sdb", "hctl":null, "tran":null, "subsystems":"block:scsi:pci", "rev":null, "vendor":null, "zoned":"none"}
         ]
      },
      {"name":"sdc", "kname":"sdc", "path":"/dev/sdc", "maj:min":"8:32", "fsavail":null, "fssize":null, "fstype":null, "fsused":null, "fsuse%":null, "mountpoint":null, "label":null, "uuid":null, "ptuuid":"55160528-ea62-4aaf-9825-9dbfa5e6b7cb", "pttype":"gpt", "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":false, "rm":false, "hotplug":false, "model":"QEMU_HARDDISK", "serial":"QM00009", "size":"32G", "state":"running", "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":false, "sched":"mq-deadline", "rq-size":64, "type":"disk", "disc-aln":0, "disc-gran":"512B", "disc-max":"2G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":null, "hctl":"4:0:0:0", "tran":"sata", "subsystems":"block:scsi:pci", "rev":"2.5+", "vendor":"ATA     ", "zoned":"none",
         "children": [
            {"name":"sdc1", "kname":"sdc1", "path":"/dev/sdc1", "maj:min":"8:33", "fsavail":null, "fssize":null, "fstype":"ext4", "fsused":null, "fsuse%":null, "mountpoint":null, "label":null, "uuid":"68c2d16f-2e56-4f70-8116-95338744ca0a", "ptuuid":"55160528-ea62-4aaf-9825-9dbfa5e6b7cb", "pttype":"gpt", "parttype":"0fc63daf-8483-4772-8e79-3d69d8477de4", "partlabel":"primary", "partuuid":"1887497a-bd1f-49b9-8f06-9df636d8bd73", "partflags":null, "ra":128, "ro":false, "rm":false, "hotplug":false, "model":null, "serial":null, "size":"32G", "state":null, "owner":"root", "group":"disk", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":false, "sched":"mq-deadline", "rq-size":64, "type":"part", "disc-aln":0, "disc-gran":"512B", "disc-max":"2G", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":"sdc", "hctl":null, "tran":null, "subsystems":"block:scsi:pci", "rev":null, "vendor":null, "zoned":"none"}
         ]
      },
      {"name":"sr0", "kname":"sr0", "path":"/dev/sr0", "maj:min":"11:0", "fsavail":null, "fssize":null, "fstype":null, "fsused":null, "fsuse%":null, "mountpoint":null, "label":null, "uuid":null, "ptuuid":null, "pttype":null, "parttype":null, "partlabel":null, "partuuid":null, "partflags":null, "ra":128, "ro":false, "rm":true, "hotplug":true, "model":"QEMU_DVD-ROM", "serial":"QM00003", "size":"1024M", "state":"running", "owner":"root", "group":"cdrom", "mode":"brw-rw----", "alignment":0, "min-io":512, "opt-io":0, "phy-sec":512, "log-sec":512, "rota":true, "sched":"mq-deadline", "rq-size":2, "type":"rom", "disc-aln":0, "disc-gran":"0B", "disc-max":"0B", "disc-zero":false, "wsame":"0B", "wwn":null, "rand":false, "pkname":null, "hctl":"1:0:0:0", "tran":"ata", "subsystems":"block:scsi:pci", "rev":"2.5+", "vendor":"QEMU    ", "zoned":"none"}
   ]
}

**Comment by llwaini** [comment]
CasaOS V0.3.7 has fixed Format and Create, we recommend that you wait until the release of V0.3.7 (the latest version will be released soon, please check Discord news - https://discord.com/invite/Gx4BCEtHjx)

**Comment by raller1028** [comment]
We will close this issue, please resubmit if you have any questions
