### ISSUE TITLE
[Alpha][Bug] Alignment of Container terminals

### ISSUE THREAD

**Issue by Hedius** [IceWhaleTech/CasaOS#457]
### What happened?

The border of container terminals is not the same on each side. (Right side has the biggest one)... looks strange

### Screenshots

![grafik](https://user-images.githubusercontent.com/14820882/184987677-d6ad866e-5c7a-4d91-819c-4229d3d90f10.png)

**Comment by jerrykuku** [comment]
We are currently unable to support the dark mode of third-party plug-ins.

**Comment by Hedius** [comment]
Ahhhhh totally forgot that plugin.... will disable it next time
