### ISSUE TITLE
[Alpha][Bug] SMB share mounting does not support defining of share names

### ISSUE THREAD

**Issue by Hedius** [IceWhaleTech/CasaOS#459]
### What happened?

It seems like casaos is not using the system resolver?

I have internal hostnames which cannot be resolved by public dns servers.
The used A-Record resolves on the underlying debian system and on my local client.

"dial tcp: lookup nas2.intern.hedservers.com/home: no such host"

Actually, it seems like the name of the share is interpreted as part of the hostname (which is incorrect).

Yeah. Mounting works if Idon't define the share name.

### Screenshots

![grafik](https://user-images.githubusercontent.com/14820882/184989595-ab41ff63-79c3-46f7-9742-122cf3657f12.png)

**Comment by Hedius** [comment]
To add more
![grafik](https://user-images.githubusercontent.com/14820882/184990530-3db8f813-32dc-4504-a517-88b38b117737.png)

It is also not possible to do this with IP/share.

Depending on the SMB server you can hide shares (what I am doing often)
The share are not listed in the root then and it is not possible to access them.

**Comment by LinkLeong** [comment]
I have fixed it according to the product's comments @ETWang1991 , and will update it in alpha.2
