### ISSUE TITLE
Web GUI port

### ISSUE THREAD

**Issue by JChronos** [IceWhaleTech/CasaOS#46]
Is it possible to change the web gui interface port?

**Comment by ammartist** [comment]
+1

**Comment by OberynM** [comment]
+1

**Comment by LinkLeong** [comment]
We are adding this feature as soon as possible

**Comment by LinkLeong** [comment]
The new version already supports modifying the port number @JChronos

**Comment by ammartist** [comment]
Could you attach a screen shot on where to find it?

**Comment by LinkLeong** [comment]
![FireShot Capture 001 - CasaOS - 192 168 2 227](https://user-images.githubusercontent.com/13556972/145675569-23d8cd4d-307d-4c52-9d02-242b0cbd24e7.png)
