### ISSUE TITLE
[Bug] Error while mounting smb shares "Unknown option /I"

### ISSUE THREAD

**Issue by Hedius** [IceWhaleTech/CasaOS#460]
### What happened?

While mounting smb shares the following error msg appears on Debian 11.

root@casaosdebian:~# apt info cifs-utils
Package: cifs-utils
Version: 2:6.11-3.1+deb11u1

### Screenshots

![grafik](https://user-images.githubusercontent.com/14820882/184991806-564221d4-6208-4aa7-b7d4-d13ea1127919.png)

**Comment by LinkLeong** [comment]
![Image](https://user-images.githubusercontent.com/13556972/185085141-ef4c004d-1d5f-432c-b14e-b972b85041a1.png)

We need more information, such as the full command or procedure.

**Comment by Hedius** [comment]
> 
> 
> ![Image](https://user-images.githubusercontent.com/13556972/185085141-ef4c004d-1d5f-432c-b14e-b972b85041a1.png)
> 
> We need more information, such as the full command or procedure.

I don't know the command. All i did is mounting the share in the file app.

**Comment by Hedius** [comment]
Why should i create a bug report for a debian package.... i am talking about your gui...

**Comment by JohnGuan** [comment]
@Hedius Is this problem seen in the monitor of the virtual machine? Because I don't see this prompt when I connect via SSH, is there a way to turn this prompt on in the ssh connection?

**Comment by llwaini** [comment]
Can you describe your mounting process specifically on your side?
For example, using another server to mount CasaOS or using CasaOS to mount another server. What is the exact method and how does the error message appear?
We really need this information.

**Comment by Hedius** [comment]
> @Hedius Is this problem seen in the monitor of the virtual machine? Because I don't see this prompt when I connect via SSH, is there a way to turn this prompt on in the ssh connection?

Yes you cannot see kernel exceptions on the ssh login shell

**Comment by Hedius** [comment]
> Can you describe your mounting process specifically on your side?
> For example, using another server to mount CasaOS or using CasaOS to mount another server. What is the exact method and how does the error message appear?
> We really need this information.

As I said before. All I did was mounting a SMB share with user password in the file app.

Server is a current synology NAS.


I cannot provide really more information.

I looked into the code and the exception was triggered by the smb library you are using.

**Comment by Hedius** [comment]
I will try again later today.
