### ISSUE TITLE
[Alpha][Bug] Error description missing when mounting directories

### ISSUE THREAD

**Issue by Hedius** [IceWhaleTech/CasaOS#461]
### What happened?

When Mounting a smb share fails. Then you only see a short toast message with "Fail." Hower the http response contains a precise error description. Maybe include this in the error msg?

This would help users to understand the cause of the fail.

### Screenshots

![grafik](https://user-images.githubusercontent.com/14820882/184992296-150ba8e7-32b8-4c48-a86a-54e2eaefca79.png)

**Comment by jerrykuku** [comment]
Will fix this issue soon.
