### ISSUE TITLE
[App Request] Uptime Kuma

### ISSUE THREAD

**Issue by bat1939** [IceWhaleTech/CasaOS#463]
### App Information

- Name: Uptime Kuma
- Short Description: A self-hosted monitoring tool
- Official Website: https://uptime.kuma.pet
- GitHub Repository: https://github.com/louislam/uptime-kuma
- Docker Image: louislam/uptime-kuma:1

### Why do you want this app?

This service would provide users with a way to monitor any self-hosted services as well as other sites. 

### Additional information?

How to setup in docker

docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1

**Comment by JohnGuan** [comment]
Initial Uptime Kuma
- https://github.com/IceWhaleTech/CasaOS-AppStore/commit/e0784070f8cf7f78ea223b9deb42a56d3f39c268

@LinkLeong Please test and update to App Store.

**Comment by JohnGuan** [comment]
Done!
