### ISSUE TITLE
[Bug] 网络状况无法正常显示

### ISSUE THREAD

**Issue by dsus4wang** [IceWhaleTech/CasaOS#465]
网络状况,速度显示一直是0
 - OS: linux
 - CasaOS Version: 0.3.4
 - Disk Total: 13758 
 - Disk Used: 4366 
 - System Info: [Armbian 22.08.0-trunk Bullseye \l Bit:64 Mem:1952M Core:4 Linux armbian 5.15.60-flippy-75+o #152 SMP PREEMPT Thu Aug 11 20:37:57 CST 2022 aarch64 GNU/Linux]
 - Remote Version: 0.3.4
 - Browser: Chrome 
 - Version: 104.0.0.0

**Comment by LinkLeong** [comment]
No network message due to websocket disconnection. Please check and make sure that there is no firewall or port open. I will close the issue, if in doubt please reopen it
