### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mago-kamar** [IceWhaleTech/CasaOS#467]
**Describe the bug**
I succesfully added Home Assistant doker.
Unfortunately there is not present "add-ons" in Setting menù
Unfortunately I cannot select the backup in order to restore it

**To Reproduce**
1. Add Home Assistant doker
2. After complete the download, click on Home Assistant doker
3. A new page with Home Assistant  running is showed
4. Click on Settings
5. No "Add-ons" item is present

6. Click on Settings
7. Click on System
8. Click on Backups
9. Click on "Create backup" and wait for the completation
10. You have the backup, but no check box is present in order to select it, to start a restore

**Expected behavior**
The two mentioned function, are essentially for a correct function of Home Assistant

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox 103.0.2 (browsing from a MacBookPro)
 - Version 22.04

**Additional context**
I have an Home Assistant installation on a Raspbarry, and those functions are present and correcly working.
Home assistant versions are the same between CasaOs and my previous installation on a Raspberry

**Comment by mago-kamar** [comment]
![Schermata 2022-08-19 alle 14 44 44](https://user-images.githubusercontent.com/5904838/185621220-6dd11890-f976-49b0-a7fc-0f450fc1635f.png)
here the page with missing Add-ons menù

![Schermata 2022-08-19 alle 14 45 49](https://user-images.githubusercontent.com/5904838/185621390-a75b78b4-70be-446d-8680-bbff50b1d894.png)
Here the correct page from my previous Raspberry installation without using CasaOs


![Schermata 2022-08-19 alle 14 46 48](https://user-images.githubusercontent.com/5904838/185621583-d3b7503c-e502-4674-a92e-dca5fd8bcbb1.png)
Here the backup page with missing check box to allow the selection


![Schermata 2022-08-19 alle 14 47 33](https://user-images.githubusercontent.com/5904838/185621695-965cda55-4d24-4206-adf1-f7976b5b5a73.png)
Here the backup page from my Raspberry, with the correct visualization of the check boxes close to the backup name.

**Comment by AuthorShin** [comment]
Hello @mago-kamar 
Please consider asking you question in Home Assistant community.
https://community.home-assistant.io/
https://discord.com/invite/home-assistant
