### ISSUE TITLE
Podman support?

### ISSUE THREAD

**Issue by RobotsAreCrazy** [IceWhaleTech/CasaOS#47]
Hi, as podman is looking like a natural successor to docker could you consider adding support for it with casaos please?

**Comment by LinkLeong** [comment]
We don't recommend using commands to manage casaos or docker, and podman has no daemon, so we won't consider compatibility with podman for now.

**Comment by JohnGuan** [comment]
We are not yet familiar with podman. Also the whole home cloud app ecosystem is less likely to use podman, so for now we have no plans to support podman.

Is there any reason you see why you think it would be better to use podman? We'd be glad to discuss better technical solutions!

**Comment by ruckc** [comment]
Is love to see podman support as it's rootless by default.  Which makes it a much better security conscious choice.

**Comment by gautamkrishnar** [comment]
> We are not yet familiar with podman. Also the whole home cloud app ecosystem is less likely to use podman, so for now we have no plans to support podman.

Podman command line is compatible with the docker commands. You can simply do `alias docker=podman` it will work fine. 

Learn more about podman: https://docs.podman.io/en/latest/

**Comment by RobotsAreCrazy** [comment]
> We are not yet familiar with podman. Also the whole home cloud app ecosystem is less likely to use podman, so for now we have no plans to support podman.
> 
> Is there any reason you see why you think it would be better to use podman? We'd be glad to discuss better technical solutions!

Hope you look at migrating over to it in time

**Comment by ruckc** [comment]
My primary reason is that podman containers are rootless by default.  With docker it takes effort to ensure the containers are running securely on the host, and anyone that has access to the `docker` socket can essentially elevate themselves to root.  Podman doesn't have these issues... you can choose to run containers with root for privileged use cases, but the default is running as the invoking user.  The podman CLI is also compatible with docker CLI, so supporting podman should be just substituting `podman` for `docker` in shell commands.

**Comment by markstinson** [comment]
Being a paid Linux SA and having to deal SecOps related activities of system currency, errata, compliance for numerous entities who's names are acronyms -- I strongly concur about converting to `podman` instead of `docker`. 

As mentioned above, there is *zero* learning curve as it was designed to be a `docker` drop-in substitute. Plus you don't have to deal with systemctl for its daemon. `podman` **is** the new industry standard.

The *only* thing I can think might be the smallest challenge could be is someone's container using ports below 1024, and to fix that, it's just a config setting away - which could be configured.

**Comment by Lunarequest** [comment]
Also since podman v2 its shipped with a docker compatible rest api https://podman.io/blogs/2020/07/01/rest-versioning.html

**Comment by H3cJP** [comment]
404 error at "https://podman.io/blogs/2020/07/01/rest-versioning.html"

**Comment by Lunarequest** [comment]
https://web.archive.org/web/20200714221404/https://podman.io/blogs/2020/07/01/rest-versioning.html

**Comment by H3cJP** [comment]
yes but why documentation would just be removed instead of redirecting older links to an arquive on the same site for example showing that as an deprecated version? it doesn't make any sense needing to rely on third party sites like https://web.archive.org

**Comment by Lunarequest** [comment]
It was a blog post, its still around but they've changed the layout and i've not had enough time to look into the new url

**Comment by Xeddius** [comment]
This was marked as completed yet I don't see any documented changes or podman support listed anywhere?
