### ISSUE TITLE
[Bug] Plex not creating a new server

### ISSUE THREAD

**Issue by JVTEAM** [IceWhaleTech/CasaOS#474]
I had previously installed the plex app and set it up when I first got the zimaboard.  However, it wasn't working the way I liked so I removed it.  I have since found a new need for it so I reinstalled.  However, when I click the container, open the webapp and sign in to plex there is no sign of a server...just the other ones I have on my account

**To Reproduce**
1. install plex via apps container
2. Click on 'Plex
3. Sign in to plex
4. Don't see a new server

**Expected behavior**
It would ask you to claim or name a server running on the zimaboard

**Comment by llwaini** [comment]
@JVTEAM It is recommended to log into CasaOS directly using the IP so that you can access the Plex server
