### ISSUE TITLE
[Bug] CasaOS v0.3.5 AppStore not working.

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#477]
### What happened?

CasaOS store donk work properly, when i try to install for example Prowlarr. I click in the app to see the description, but not work. Also if i click in install appears the same error. I upload a capture of this error. 

System
OS: Ubuntu 20.04 LTS
RAM: 16GB
CPU: Intel i7-4790

### Screenshots

![image](https://user-images.githubusercontent.com/18572939/186223693-c9bbf395-9523-4190-afd9-beba9a1bce7d.png)

**Comment by LinkLeong** [comment]
It is possible that the network is more stable than the cause, now the problem still exists, where is your area

**Comment by Bartiiee** [comment]
I wanna confirm this issue.
Updated today on my online server (ubuntu 20.04, 8GBram, 4cores) tot latest casaos version and receiving this notification for allmost all applications.  (I think this one is in a datacenter in Germany)
Installed on a desktop at school also (ubuntu 20.04, 8GBram, i5gen 5), same problem (that one is in Belgium)

**Comment by ssouthall6** [comment]
Same problem here, 64-bit Raspian 4GB

**Comment by ssouthall6** [comment]
seems to be resolved

**Comment by Bartiiee** [comment]
Confirming. I can Install everything again. Thanx for fast resolving! (And nice to see that the appstore keeps growing :) )

**Comment by ETWang1991** [comment]
1. Find out why you can't connect
2. Under the premise that 1 is clear, consider removing this prompt if the list successfully loads the cache.

**Comment by AmadeusGraves** [comment]
Confirmed, this issue is resolved, the error will not occur again. I close the issue.
