### ISSUE TITLE
0.3.5文件应用下载错误[Bug] 

### ISSUE THREAD

**Issue by updsky** [IceWhaleTech/CasaOS#483]
更新到0.3.5版本后，在文件应用中下载文件时地址错误，会出现两个主机IP，导致文件无法下载。
如：http://192.168.199.8/ui/://192.168.199.8/v1/file?..................

 - OS: linux
 - CasaOS Version: 0.3.5
 - Disk Total: 29671 
 - Disk Used: 15409 
 - System Info: [openmediavault 6.0.36-2 (Shaitan)   \l Copyright (C) 2009-2022 by Volker Theile. All rights reserved. To manage the system visit the openmediavault web control panel: docker0: 172.17.0.1 docker0: fe80::42:7eff:fe7c:845e eth0: 192.168.199.8 eth0: fe80::dea6:32ff:fecd:8e24 veth8f9fb75: fe80::8c72:e2ff:fe2a:9296 vethbb52ddc: fe80::a02b:85ff:fee6:fba0 vethcd322f7: fe80::68b2:8fff:fe12:8554 vethd7d637b: fe80::14e4:73ff:feb0:8d99 vethe37a02a: fe80::7480:1eff:fef6:5410 vethf3bce33: fe80::38ea:35ff:fe11:81e6 wlan0: 192.168.199.79 By default the web control panel administrator account has the username 'admin' and password 'openmediavault'. It is recommended that you change the password for this account within the web control panel or using the 'omv-firstaid' CLI command. For more information regarding this appliance, please visit the web site: https://www.openmediavault.org Bit:64 Mem:7762M Core:4 Linux Upd-PI4 5.15.56-v8+ #1575 SMP PREEMPT Fri Jul 22 20:31:26 BST 2022 aarch64 GNU/Linux]
 - Remote Version: 0.3.5
 - Browser: Chrome 
 - Version: 104.0.5112.105

**Comment by jerrykuku** [comment]
This bug was fixed in the hot update of v0.3.5.1. I will close this issue, If there are any problems, you can reopen it.
