### ISSUE TITLE
[Bug] 无法导入原有的Docker Apps

### ISSUE THREAD

**Issue by xiongweixp** [IceWhaleTech/CasaOS#484]
系统原来已经安装了一些Docker容器，后来才安装的CasaOS，然后使用主页上的“原有Docker Apps”，“导入到CasaOS”时，总是报 Fail， 看日志，没有任何Error信息

**Comment by LinkLeong** [comment]
Can you be more specific about what applications you imported? You can also contact @JohnGuan  and add the WeChat group to solve the problem more quickly.

**Comment by xiongweixp** [comment]
> Can you be more specific about what applications you imported? You can also contact @JohnGuan and add the WeChat group to solve the problem more quickly.

Every applications installed before,  Include Qinglong,  Emby, Seafile  and  Homeassistant

**Comment by JohnGuan** [comment]
你可以加我微信：guanningchuan，有中文微信群
What is your version of CasaOS?

**Comment by LinkLeong** [comment]
We will close this issue, please resubmit if you have any questions
