### ISSUE TITLE
文件访问上传问题

### ISSUE THREAD

**Issue by stevenliuit** [IceWhaleTech/CasaOS#485]
**Describe the bug**
在Files里上传文件速度慢 下周速度局域网才几百kb 网卡为千兆网卡

**Desktop (please complete the following information):**
 - OS: linux
 - CasaOS Version: 0.3.5.1
 - Disk Total: 3085 
 - Disk Used: 1916 
 - System Info: [Ubuntu 20.04.4 LTS   \l Bit:64 Mem:856M Core:4 Linux hi3798mv200 4.4.35_ecoo_82082468 #1 SMP Wed Aug 24 18:23:02 CST 2022 aarch64 aarch64 aarch64 GNU/Linux]
 - Remote Version: 0.3.5.1
 - Browser: Chrome 
 - Version: 103.0.0.0

**Comment by stevenliuit** [comment]
还有一个问题 DATA能移动到硬盘上嘛？我安装的时候只能装系统上 发现无法安装到硬盘上

**Comment by stevenliuit** [comment]
![image](https://user-images.githubusercontent.com/4044994/187323644-69af8f97-06f0-41fc-b5cd-5149c535b4b2.png)
![image](https://user-images.githubusercontent.com/4044994/187323653-ea6a7c1d-60f1-4b93-88f2-25cc2507a6d3.png)
![image](https://user-images.githubusercontent.com/4044994/187323660-34c1f472-c590-411b-afac-14c57672e96b.png)
网卡为千兆网卡
如果用docker版的FileBrowser速度比File的要快
<img width="824" alt="image" src="https://user-images.githubusercontent.com/4044994/187324453-b8dce02d-96fe-4149-ae3a-6ced996db3ad.png">

**Comment by stevenliuit** [comment]
还有一个问题是 局域网无法发现smb共享，只能通过ip访问

**Comment by stevenliuit** [comment]
用了一段时间发现还是File那个应用 上传速度慢 samba上传速度挺快的 File应用上传也就3兆左右吧
samba能到80兆/s
我的盒子配置是1g运存4g存储 发现上传大于4g的文件 很容易导致磁盘占满 我外挂了一块硬盘到/DATA根目录 发现也不行

**Comment by stevenliuit** [comment]
我的本地磁盘是4GB 然后挂载sata到/DATA分区 发现上传大于4g文件 会在系统/var/lib/casaos/temp生成一堆零散文件 然后我把/var/lib/casaos/temp软链到我挂载的/DATA分区 发现文件上传到download然后还会跑到/temp里

**Comment by stevenliuit** [comment]
我的本地磁盘是4GB 然后挂载sata到/DATA分区 发现上传大于4g文件 会在系统/var/lib/casaos/temp生成一堆零散文件 
这个分片文件大小是不是可以在哪里配置啊

**Comment by llwaini** [comment]
CasaOS V0.3.7 has been fixed, we suggest you wait until V0.3.7 is released (the latest version will be released soon, check Discord News - https://discord.com/invite/Gx4BCEtHjx).

**Comment by LinkLeong** [comment]
We will close this issue, please resubmit if you have any questions
