### ISSUE TITLE
[Bug] 安装Jellyfin出错

### ISSUE THREAD

**Issue by MrLv0816** [IceWhaleTech/CasaOS#486]
### What happened?
玩客云
Welcome to Armbian 20.11 Buster with Linux 5.9.0-rc7-aml-s812 build By BugScaner Support Wifi Adapter
No end-user support: built from trunk

安装后无法正常使用,无法打开页面 已拒绝连接。

### Screenshots

![image](https://user-images.githubusercontent.com/46812909/186690592-3ec44b6c-a13e-4fdc-9576-89044eca764b.png)

**Comment by llwaini** [comment]
玩客云 may not be very compatible, the physical machine, then you are recommended to buy ZimaBoard, you can get more experience - purchase connection https://shop.zimaboard.com/
