### ISSUE TITLE
[Bug] Import fail

### ISSUE THREAD

**Issue by lucascbd** [IceWhaleTech/CasaOS#490]
I've installed Taututlli via docker-compose and I get a "fail" message when I try to import to CasaOS dashboard.

**Comment by LinkLeong** [comment]
Can you provide the docker-compose file where you installed Taututlli?

**Comment by lucascbd** [comment]
---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /DATA/AppData/Tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped

Em seg., 29 de ago. de 2022 às 00:39, link ***@***.***>
escreveu:

**Comment by kanenses** [comment]
same issue

**Comment by rdking62** [comment]
Same issue with uptime-kuma. The docker installed fine but import to casaos fails. Keeps showing up at the bottom to import.

**Comment by LinkLeong** [comment]
This issue has been fixed in 0.3.7.1, please verify in the update to 0.3.7.1, if you have problems, please reopen the issue. @rdking62 @kanenses @lucascbd
