### ISSUE TITLE
[FAILED] Dependency smartmontools  installation failed, please try again manually!

### ISSUE THREAD

**Issue by malefactor666** [IceWhaleTech/CasaOS#491]
Installer fails on "[FAILED] Dependency smartmontools  installation failed, please try again manually!"
with Debian 11.4.0 fresh install running on Hyper-V

Have removed and reinstalled smartmontools manually through apt, but this doesn't work

**Comment by LudoDash** [comment]
*Bump
I'm also having this issue
reinstalled Smartmontools and still having the same issue

**Comment by dissy614** [comment]
Workaround:
`PATH=$PATH:/usr/sbin`
Then re-run the installer.

**Comment by AuthorShin** [comment]
Thank you for reporting the issue, we will try to fix this ASAP.

**Comment by AuthorShin** [comment]
Thanks @dissy614 for the information, (we had the same type of problem for docker in previous versions).

**Comment by bluehysteric** [comment]
Please fix it as soon as possible, it still can't be installed

**Comment by LudoDash** [comment]
> Please fix it as soon as possible, it still can't be installed

read the fix posted by dissy614
its pretty simple.

**Comment by bluehysteric** [comment]
> > Please fix it as soon as possible, it still can't be installed
> 
> read the fix posted by dissy614 its pretty simple.

I tried it, but it still gives me an error message

**Comment by LudoDash** [comment]
> > > Please fix it as soon as possible, it still can't be installed
> > 
> > 
> > read the fix posted by dissy614 its pretty simple.
> 
> I tried it, but it still gives me an error message

then post the environment you are trying to install CasaOS in
eg: os

**Comment by jerrykuku** [comment]
OK, I will check and fix this as soon as possible.

**Comment by bluehysteric** [comment]
> Thank you for reporting the issue, we will try to fix this ASAP.
Is there a solution to the following problem?
https://github.com/IceWhaleTech/CasaOS/issues/507

**Comment by LudoDash** [comment]
> 
 yes, **read** the post by 
dissy614

**Comment by jerrykuku** [comment]
We have fixed this issue in v0.3.6. I will close this issue, if you have any question you can reopen this.

**Comment by tatayer** [comment]
impossible d'installer smartmontools

**Comment by L-udo** [comment]
> impossible d'installer smartmontools 

What?
