### ISSUE TITLE
[Bug] Cannot monitor nvme hardisk tempreture

### ISSUE THREAD

**Issue by luc-yang** [IceWhaleTech/CasaOS#492]
**Describe the bug**
Cannot monitor nvme hardisk tempreture.
The system is Ubuntu 22.04.
It is ok when typing `sensors` in terminal.

luc@R86S:~$ sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +45.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +40.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +40.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:        +40.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:        +40.0°C  (high = +105.0°C, crit = +105.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  (crit = +119.0°C)

nvme-pci-0400
Adapter: PCI adapter
Composite:    +44.9°C  (low  =  -5.2°C, high = +79.8°C)
                       (crit = +84.8°C)

**Comment by AuthorShin** [comment]
What is your NVME SSD exact model?

**Comment by luc-yang** [comment]
=== START OF INFORMATION SECTION ===
Model Number:                       WD Blue SN570 1TB SSD
Serial Number:                      XXXXX
Firmware Version:                   234100WD
PCI Vendor/Subsystem ID:            0x15b7
IEEE OUI Identifier:                0x001b44
Total NVM Capacity:                 1,000,204,886,016 [1.00 TB]

**Comment by LinkLeong** [comment]
Can you provide the name and model of your equipment?

**Comment by LinkLeong** [comment]
You can try `smartctl -a {path}`

**Comment by LinkLeong** [comment]
We have checked this issue and taken care of it, you can upgrade to the latest version and retry the issue.
