### ISSUE TITLE
[Bug] during install of casaos apps or docker compose apps, it will just show "Start Installation" during the whole process

### ISSUE THREAD

**Issue by eugenehw08** [IceWhaleTech/CasaOS#494]
**Describe the bug**
during install of casaos apps or docker compose apps, it will just show "Start Installation" during the whole process

**To Reproduce**
1. i tried a few times to reformat my raspberry pi cm4 OS system and reinstall casaos, but a few times it will show install failed on smarttools, is it this one ?
2. then when try to install new apps in the "App Store" or in docker-compose text file
3. it will just show "Start Installation" during the whole downloading and installation process

**Expected behavior**
it will just show "Start Installation" during the whole downloading and installation process

**Screenshots**
Here is the shot screenshot video file
![image](https://user-images.githubusercontent.com/110435214/187037633-7ffae01f-474c-4eaa-a2d0-40c3e4fba33b.png)

https://user-images.githubusercontent.com/110435214/187037582-21e3bbaf-d6dd-414a-8531-50ba66ac366e.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Mozilla Firefox

**Additional context**

**Comment by AuthorShin** [comment]
Hello @eugenehw08 
Thanks for reporting the problem.
It's a known issue and we will try to fix it as soon as possible but first tell me exactly which of the following problems you are having. [Here](https://github.com/IceWhaleTech/CasaOS/issues/397) and [Here](https://github.com/IceWhaleTech/CasaOS/issues/396)
Are you using VPS?
Any chance that your network is behind NAT or NordVPN?

**Comment by eugenehw08** [comment]
Are you using VPS?  <= i am not using VPS, i am using Raspberry Pi CM4 direct installation inside Debian Bullseye OS
Any chance that your network is behind NAT or NordVPN?  <= i am not on NAD or on NordVPN

**Comment by AuthorShin** [comment]
I'm having the same problem over with VPS.

**Comment by llwaini** [comment]
Install pihole
Device: Raspberry Pi 4B
System: CasaOS v0.3.4 v0.3.5.1 v0.3.6
Installation video：
https://user-images.githubusercontent.com/59589857/190126856-d18d15a0-772c-41e5-9111-c89eae2f2f9d.mp4

**Comment by AuthorShin** [comment]
@llwaini Should I DM you or Link on Discord?

**Comment by llwaini** [comment]
@AuthorShin This is my Discord ID: llwaini#4897 or you send me your ID, I'll add you on this side

**Comment by ETWang1991** [comment]
casaos apps-P1
docker compose apps-P3
