### ISSUE TITLE
[Bug] Cannot create CasaOS account

### ISSUE THREAD

**Issue by DuckyBlender** [IceWhaleTech/CasaOS#497]
**Describe the bug**
Trying to create an account does nothing. When I type `casaos` into the terminal, the output is: https://pastebin.com/y7ggyrKR

**To Reproduce**
1. Install Raspberry Pi OS Lite 64-bit
2. Install CasaOS using the script
3. Try to create an account, does nothing
4. See error when `casaos` is typed in the terminal

**Expected behavior**
Creating an account

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS Lite 64-bit
 - Browser: Brave
 - Version: v0.3.5.1

**Additional context**
This is wierd, because this worked on the exact same system before. I tried on DietPi and the same error is encountered (with the addition to #491 (workaround https://github.com/IceWhaleTech/CasaOS/issues/491#issuecomment-1229225003)

I thought this could be a problem with the SD card, but I formatted the card (from DietPi) and got the exact same error...

**Comment by DuckyBlender** [comment]
I'm going to re-try this, gonna update this comment when I finish.

**Comment by DuckyBlender** [comment]
yep, same problem. running a completely fresh install of raspberry pi OS lite 64-bit and still same error
the only thing i changed from the default config is the username, password and region

**Comment by DuckyBlender** [comment]
Just tried 0.3.6 on an ARM AWS EC2 on Debian 11 and it worked flawlessly, maybe it's the update, maybe it's the raspberry pi??

**Comment by LinkLeong** [comment]
casaos does not need to be executed separately, and casaos needs to specify the configuration file when running, we have tested it on the Raspberry Pi and did not find this problem. Please provide more information if you have any questions
