### ISSUE TITLE
[Bug] CasaOS Unable to update

### ISSUE THREAD

**Issue by voctot** [IceWhaleTech/CasaOS#499]
**Describe the bug**
0.3.4 CasaOS system UI interface cannot be upgraded to version 0.3.5 - click to upgrade and have been waiting.

**To Reproduce**
1. Enter the Casaos UI management interface.
3. Click the settings.
3. Click to update.

**Expected behavior**
CasaOS upgraded to version 0.3.5.

**Screenshots**
![1661937722514](https://user-images.githubusercontent.com/36097179/187645283-00e83cea-2ca9-4bf4-a670-965e58bbcc37.jpg)

**Desktop (please complete the following information):**
 - OS: linux
 - CasaOS Version: 0.3.4
 - Disk Total: 27712 
 - Disk Used: 22836 
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
 - Remote Version: 0.3.5.1
 - Browser: Chrome 
 - Version: 104.0.0.0

**Additional context**
nothing.

**Comment by jerrykuku** [comment]
I need more infomation. If you don't mind you can add my wechat. my wechat ID is jerryk.

**Comment by jhpang32** [comment]
I had the same problem on a raspberrypi

**Comment by jerrykuku** [comment]
If you can't update via webui, you can try this command via SSH
``` curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/main/update.sh | sudo bash ```
It will upgrade your casaos to v0.3.6
