### ISSUE TITLE
[Bug]  CasaOS Terminal Displays Unreadable Text

### ISSUE THREAD

**Issue by 1artist** [IceWhaleTech/CasaOS#503]
![Selection_006](https://user-images.githubusercontent.com/112596293/187814461-685c24bd-4391-4855-a6f0-026a449a9f61.png)
**Describe the bug**
When I SSH connect to my RasPi Lite 64bit OS using the inbuilt CasaOS terminal window what I see in my CasaOS terminal display is a bunch of unreadable text that looks like it is all vertically striped in many colors.

**To Reproduce**
1. Go to 'Terminal & Logs button...'
2. Click on 'Terminal & Logs button....'
3. 'Enter RasPi OS username and password....'

**Expected behavior**
Text inside Terminal should be readable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [RasPI OS Lite 64bit on Pi 4 board]
 - Browser [FireFox]
 - Version [100.0.2]

**Additional context**
The terminal is unusable due to how the text is unreadable.

**Comment by jerrykuku** [comment]
We use xterm to display ssh, maybe this is just a browser and xterm incompatibility issue. We'll get back to you when we test it.

**Comment by jerrykuku** [comment]
I will close the issue and if the problem persists you can reopen it.
