### ISSUE TITLE
[Bug] When we import an already installed app it's not showing any of it's Environment Variables

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#509]
**To Reproduce**
1. Install a container (one with Environment Variables) outside the CasaOS
2. Import it via CasaOS
3. Then you will see that CasaOS not showing any of those (The Environment Variables are still there assign to the container but just CasaOS is not showing them)

**Comment by LinkLeong** [comment]
I need to see your docker's cli

**Comment by AuthorShin** [comment]
@LinkLeong Unfortunately cause of the result of [this issue](https://github.com/IceWhaleTech/CasaOS/issues/528) I had to rest the OS.

**Comment by LinkLeong** [comment]
ok, there is a problem, you can resubmit the issue

**Comment by LinkLeong** [comment]
This issue has been fixed in 0.3.6, I will close the issue, if you have questions, you can ask again.

**Comment by LinkLeong** [comment]
I closed the issue and reopened it if you have any questions.
