### ISSUE TITLE
Can you consider adding a button with a custom link next to the Appstore custom installation（是否可以考虑在Appstore自定义安装旁边添加一个自定义链接的按钮）

### ISSUE THREAD

**Issue by DeshunMie** [IceWhaleTech/CasaOS#514]
For example, nextcloud is not the installed doucker app, but is installed in the local environment. I can't add a shortcut in casaos. Can I add a custom link button or other functions to add a link address to an app（
列如Nextcloud不是安装的doucker app，而是安装在本地环境中。我无法在casaos中加入快捷打式，是否可以通过加入自定义链接按钮或其他功能来实现把链接地址添加成app）

**Comment by wuxs** [comment]
新版可以导入自己启动的docker容器

**Comment by DeshunMie** [comment]
> 新版可以导入自己启动的docker容器

我的意思是应用不是运行在docker容器中，而是直接运行在本地环境中，比如我的Nextcloud就是运行在本地环境中，我该如何把Nextcloud的地址导入到casaos中

**Comment by AuthorShin** [comment]
This feature been added to 0.3.6
