### ISSUE TITLE
[Alpha][Bug] Missing the App log icon in setting for showing the logs of the app

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#522]
### What happened?

Missing the App log icon in setting for showing the logs of the app.

**Comment by zhanghengxin** [comment]
how much your casaos version?
can you try to update it again?

**Comment by zhanghengxin** [comment]
how much your casaos version?
can you try to update it again?

**Comment by zhanghengxin** [comment]
this install script has been update

**Comment by AuthorShin** [comment]
https://i.ibb.co/brrbyGV/Screenshot-2022-09-07-122247.png

**Comment by zhanghengxin** [comment]
due to installation script is old for this problem

**Comment by AuthorShin** [comment]
@zhanghengxin what do you mean by old?

**Comment by zhanghengxin** [comment]
We recently updated the installation script，，，

The reason for this problem is that the package referenced by the installation script is old

**Comment by zhanghengxin** [comment]
#521 #522 
Both problems are for the same reason

**Comment by LinkLeong** [comment]
The problem has been solved, just reinstall 0.3.6-alpha.1
