### ISSUE TITLE
[Alpha][Bug] CasaOS Web UI became inaccessible after running the installation script twice

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#528]
### What happened?

CasaOS Web UI became inaccessible after running the installation script twice.
After running it for the second time it does show this error at the end:
<img src="https://i.ibb.co/9ngD5rN/Screenshot-2022-09-07-124050.png">

**Comment by zhanghengxin** [comment]
wow,,,surprise

**Comment by zhanghengxin** [comment]
give me same time.

**Comment by AuthorShin** [comment]
First it was okay now I'm getting this error even after I uninstalled CasaOS, so right now I cannot install it again :D

**Comment by LinkLeong** [comment]
We're working on this issue urgently and I'll respond when I update the issue.

**Comment by LinkLeong** [comment]
The problem has been solved, just reinstall 0.3.6-alpha.1
