### ISSUE TITLE
[Bug] PhotoPrism icon in App Store is not loading

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#531]
The PhotoPrism icon in the App Store is not loading.
<img src="https://i.ibb.co/zZ6SSP2/Screenshot-2022-09-08-091724.png">
<img src="https://i.ibb.co/phCtqsF/Screenshot-2022-09-08-091741.png">

**Comment by LinkLeong** [comment]
Updated, it takes time for the update to take effect
