### ISSUE TITLE
Why CasaOS opened port 42957?

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#533]
### Discussed in https://github.com/IceWhaleTech/CasaOS/discussions/512

<div type='discussions-op-text'>

<sup>Originally posted by **AuthorShin** September  5, 2022</sup>
Why CasaOS opened port 42957?
and when I want to open it I'm getting the following:
`
Upgrade failed: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
`</div>

Also is it safe to have this port (random I assume) open on a public server? and how we can close this port?

**Comment by LinkLeong** [comment]
1. We started the local port 42957, which is the websocket port, for communication with html.
2. This port is only bound to the local port, which is currently a secure port
3. Active closure of this port will cause some casaos functions to be unavailable

**Comment by AuthorShin** [comment]
Thanks for the answer @LinkLeong we are looking forward to the merge this Web Socket port with the Web UI port.
