### ISSUE TITLE
[Alpha][Bug] Updating to 0.3.6 result in resetting the CasaOS account

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#536]
### What happened?

Updating to 0.3.6 result in resetting the CasaOS account and it's asking for creating an account.

### Screenshots

<img src="https://i.ibb.co/7Q1vFd9/Screenshot-2022-09-08-195827.png">

**Comment by LinkLeong** [comment]
What system are you, all need to install it, there is no operation of the steps

**Comment by AuthorShin** [comment]
@LinkLeong Debian 11 and I had 0.3.5.1 on it but after I run the command for 0.3.6 when I open up the web UI I got this screen asking me to create a new account.

**Comment by AuthorShin** [comment]
Solved

**Comment by OptimusGREEN** [comment]
> Solved

Fancy sharing your solution?

**Comment by AuthorShin** [comment]
> > Solved
> 
> Fancy sharing your solution?

It was the Alpha version script problem that was only for new setups and fresh OSes, that's why since then we have separate update script and install script for Alpha version.
