### ISSUE TITLE
[Bug] Hard to read log format for apps logs

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#537]
### What happened?

App logs are hard to read due to the bad formatting.

### Screenshots

<img src="https://i.ibb.co/2PKkZPq/Screenshot-2022-09-08-215541.png">

Expected look: (From Portainer)

<img src="https://i.ibb.co/WnbRWGc/Screenshot-2022-09-08-220212.png">

**Comment by LinkLeong** [comment]
This is an internal application log, which casaos cannot format

**Comment by AuthorShin** [comment]
@LinkLeong I'm talking about these random characters (in the past versions it wasn't like this).
<img src="https://i.ibb.co/c8LMQyY/Screenshot-2022-09-09-185006.png">

**Comment by LinkLeong** [comment]
Ik heb openspeedtest gecontroleerd en vond geen abnormale logs, wat is deze toepassing en hoe verschijnen de logs?

**Comment by AuthorShin** [comment]
@LinkLeong You can check with this app too. https://hub.docker.com/r/m0ngr31/dailynotes
Those logs are info level.

**Comment by jerrykuku** [comment]
Docker's logs sometimes add 8 bytes of information to the header, we will fix this issue in v0.3.8.

**Comment by AuthorShin** [comment]
Looks like it's fixed on V0.3.8. Thanks Jerry @jerrykuku
