### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AuroraFrowned** [IceWhaleTech/CasaOS#54]
**Describe the bug**

**To Reproduce**
wget -qO- https://get.icewhale.io/casaos.sh | bash

**Expected behavior**
树莓派4B 8G
casaos.service - CasaOS Service
   Loaded: loaded (/usr/lib/systemd/system/casaos.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-12-12 03:25:41 CST; 841ms ago
  Process: 4873 ExecStart=/usr/local/bin/casaos -c /casaOS/server/conf/conf.ini (code=exited, status=203/EXEC)
 Main PID: 4873 (code=exited, status=203/EXEC)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Centos8
 - Version [v0.2.3]

**Additional context**

**Comment by AuroraFrowned** [comment]
> 

还有问题就是，安装失败后，无法再次ssh进入系统了
只能重新刷机

**Comment by JohnGuan** [comment]
你是在树莓派上装的CentOS吗？你有试过Raspberry Pi OS吗？

**Comment by AuroraFrowned** [comment]
> 你是在树莓派上装的CentOS吗？你有试过Raspberry Pi OS吗？

换系统就成功了
