### ISSUE TITLE
Problem with translations in CasaOS

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#540]
The CasaOS translation is giving a lot of problems because it is so decentralised. In the i18n project, there are some translations and in the CasaOS UI project there are others. We are getting to a point where it is very difficult to translate or find all the entries.

That's why I think we should centralise translations with an internationalisation software such as 
[Tolgee](https://tolgee.io/)
[Lokalise](https://learn.lokalise.com/translation-software/?utm_source=google&utm_medium=cpc&utm_campaign=EMEA_LOK_Search_Localization_General&utm_content=140445750131-607668921797&utm_term=localization%20software&cq_src=google_ads&cq_cmp=16629418796&cq_term=localization%20software&cq_plac=&cq_net=g&cq_plt=gp)
[Poeditor](https://poeditor.com/)
[Weblate](https://weblate.org/en/)

I have also been noticing that translations done in the i18n project are not being ported to the UI project. If any of these alternatives are implemented we will have no more problems with localisation, everything will be automatic and it will be less of a burden for the developers.

**Comment by jerrykuku** [comment]
I agree, so we're already testing weblate. should be open this week.

**Comment by AmadeusGraves** [comment]
Perfect, when it is available in weblate, I will continue with the translation of CasaOS. Best regards.

**Comment by jerrykuku** [comment]
Hi, You can visit our weblate site here: https://hosted.weblate.org/projects/casaos/ui/, if any question please let me know.
I will continue to improve the setup of the site so that everyone can help translate more easily.

**Comment by AmadeusGraves** [comment]
wonderful, I'll start translating, thank you!

**Comment by AmadeusGraves** [comment]
Spanish translation completed for now

**Comment by CosmoFox** [comment]
Hello! I made huge translate in weblate.org for russian lang. How soon it will be applyed? Asking becouse some words was "blind translated", and i wanna fix it ASAP.
