### ISSUE TITLE
代理或上传安装包

### ISSUE THREAD

**Issue by q2316367743** [IceWhaleTech/CasaOS#541]
希望能够增加代理设置，或者自行上传安装包，有一些地方无法访问github.com，总是超时，无法升级

**Comment by k997** [comment]
在shell里面设置 `export ALL_PROXY=socks5://<代理地址>:<代理端口>`即可代理shell全部流量

**Comment by k997** [comment]
> 希望能够增加代理设置，或者自行上传安装包，有一些地方无法访问github.com，总是超时，无法升级

在 shell 里面设置 `export ALL_PROXY=socks5://<代理地址>:<代理端口>` 即可代理 shell 全部流量

**Comment by ETWang1991** [comment]
This issue will be addressed in the following requirements
https://github.com/IceWhaleTech/CasaOS-Doc/issues/124
