### ISSUE TITLE
[Bug] CasaOS settings not saving and CPU wattage not  working properly

### ISSUE THREAD

**Issue by AlexFigas** [IceWhaleTech/CasaOS#544]
**Describe the bug**
CasaOS Settings not saving:
Settings I like to have (Screenshot 1) don't save after a page refresh (Screenshot 2)

CPU wattage not working properly:
Always shows 0 watts. (Screenshot 3)

**To Reproduce**
1. Simply open CasaOS UI

**Expected behavior**
CasaOS UI settings should save.
Wattage should appear the current wattage used.

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/65889776/189495873-49e5a388-af05-455b-ab2d-c5848ddc5b3b.png)
2.
![image](https://user-images.githubusercontent.com/65889776/189495876-217ecc54-7f8b-49ff-b4c6-4284891561e4.png)
3.
![image](https://user-images.githubusercontent.com/65889776/189495892-83be59df-f882-47ea-a1d6-20e060b7b867.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 and Ubuntu 22.04 LTS (both happen the same), the Server is Dietpi v8.8
 - Browser: Firefox
 - Version: 0.3.6

**Comment by LinkLeong** [comment]
Can you provide the name and model of your equipment?

**Comment by AlexFigas** [comment]
> Can you provide the name and model of your equipment?

The server is a Raspberrpi 3b+

**Comment by llwaini** [comment]
The current CasaOS power consumption display only supports Intel CPU.

**Comment by AuthorShin** [comment]
About the issue about settings are not saving, team found the problem the problem and will fix it in the next version.
If not you can open a new issue.
