### ISSUE TITLE
[Bug] Cannot mount a HDD

### ISSUE THREAD

**Issue by Gladosator** [IceWhaleTech/CasaOS#551]
**Describe the bug**
So the "Create Storage" option does not work and when I do it normally through linux none of the apps except the Files app see it however if I access my rpi4 with SSH and navigate to /mnt/ it is there.

**To Reproduce**
1. Plug in a HDD
2. Click on 'The Storage monitor'
3. See it not working
4. Follow this tutorial on how to mount a drive : https://www.youtube.com/watch?v=KA-D60qhNm0
5. Install an app like Jellyfin
6. Add a library
7. Go to "/" then /mnt/
8. See it not appearing

**Expected behavior**
The "Create Storage" button activating in the first place!

**Screenshots**
IDK what screenshots to put here but I can provide you with some if you tell me regarding what.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Microsoft Edge for Windows 7
 - Version Windows 7 and Microsoft Edge is this "105.0.1343.33 (Official build) (64-bit) "

**Additional context**
None

**Comment by LinkLeong** [comment]
1. Can you provide the model number of your equipment?
2. is the hdd disk confirmed to be recognized? I need a screenshot of `ls /dev`.

**Comment by Gladosator** [comment]
So as for th hard drive sorry no but I run Casa on a raspberry pi 4 Model B+ with 4GB of ram and here is the requested screen shot:
<img width="1440" alt="Screenshot 2022-09-15 at 20 57 53" src="https://user-images.githubusercontent.com/65889266/190487065-868e3473-9cf9-47d1-acf2-7d79b4c0d16c.png">

**Comment by lazee486** [comment]
I have 3x seagate barracuda disks, btrfs file system. only 1 disk is mounting, whether i choose format or just create
![image](https://user-images.githubusercontent.com/43401332/196035544-a3019deb-7524-4b4e-9425-7550bb796157.png)
![image](https://user-images.githubusercontent.com/43401332/196035567-6cced1f7-8b12-4e94-9844-4a4d60cbb6c7.png)
![image](https://user-images.githubusercontent.com/43401332/196035588-d761337b-2cb1-414b-a2aa-e023570ce4b3.png)
also not sure how to set downloads to anywhere besides the 250g

**Comment by raller1028** [comment]
@lazee486 v0.4.3 fixed an issue where "when a disk has no partitions and is mounted directly, the storage will display disk information."When your disk has partitions, directly mounting /dev/sda will not display disk information in the storage. So if you want your disk information to be displayed, you may need to follow the mounting method mentioned above.
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/2d0caaea-d5c0-4c81-b07e-400ddbda8b36)
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/95b21f78-724c-4d8a-801e-5c009cf10744)

**Comment by LinkLeong** [comment]
I will close the question, if you still have questions please reopen the question
