### ISSUE TITLE
[App Request] Plex (but the server version)

### ISSUE THREAD

**Issue by Gladosator** [IceWhaleTech/CasaOS#552]
### App Information

- Name: Plex Server
- Short Description: A home for all your media and compatible with the Plex app on every platform
- Official Website: https://www.plex.tv/
- GitHub Repository: https://github.com/plexinc/pms-docker
- Docker Image: plexinc/pms-docker

### Why do you want this app?

Because it' dumb to only have the Normal app without the Server functionality since CasaOS is supposed to be for a home **server** and also the server app has all of the normal apps functionality.

**Comment by Gladosator** [comment]
Well for one You can host your media on it so You can access it with other devices. Even remotely!

**Comment by AlexFigas** [comment]
> Well for one You can host your media on it so You can access it with other devices. Even remotely!

humn
But we already have that in CasaOS...

![image](https://user-images.githubusercontent.com/65889776/189970687-b6a576dd-135e-4920-8aab-a1edbb58c248.png)

this is Plex Media Server

**Comment by Gladosator** [comment]
No I tried that and it does not support hosting media.

**Comment by AlexFigas** [comment]
> No I tried that and it does not support hosting media.

It does support it. I use it. It is Plex Media Server like any other. You're making it the wrong way.

Join our Discord for more info.

**Comment by Gladosator** [comment]
You must have a older version where I think it was a part of the main package.

**Comment by Gladosator** [comment]
> Oh really then tell me what this means ![OH RLY](https://user-images.githubusercontent.com/65889266/190209554-deda6d0f-6c79-46ec-b52b-58378bea8911.PNG)

The button BTW redirects to the page where you can download Plex Media Server for all platforms or use the docker container and the docker container just redirects to the github page linked in the App Request

**Comment by AlexFigas** [comment]
humn weird.
I have the plex media server using CasaOS install.

**Comment by jmwinn21** [comment]
I think what you may actually be missing is the Plex Claim token. You need to go to https://www.plex.tv/claim/ and generate a claim token. Then copy that token and set it as a PLEX_CLAIM environment variable in your container.

**Comment by victorbadila** [comment]
I also have the Plex app from the CasaOS apps list, I can host media and stream it from other devices, no problem. I didn't have to add any claim token or such, it simply works.

**Comment by thedroidkid** [comment]
Yeah plex server is definitely there I use it daily...

**Comment by kilvn** [comment]
> 

PLEX set_ CLAIM is still useless, the same problem as upstairs



> 作者

**Comment by kilvn** [comment]
> 我认为您实际上可能缺少的是 Plex Claim 令牌。您需要转到https://www.plex.tv/claim/并生成声明令牌。然后复制该令牌并将其设置为容器中的 PLEX_CLAIM 环境变量。



PLEX set_ CLAIM is still useless, the same problem as upstairs



> > 哦真的然后告诉我这是什么意思![哦](https://user-images.githubusercontent.com/65889266/190209554-deda6d0f-6c79-46ec-b52b-58378bea8911.PNG)
> 按钮 BTW 重定向到您可以为所有平台下载 Plex Media Server 或使用 docker 容器的页面，而 docker 容器只是重定向到 App Request 中链接的 github 页面

**Comment by kilvn** [comment]
> I think what you may actually be missing is the Plex Claim token. You need to go to https://www.plex.tv/claim/ and generate a claim token. Then copy that token and set it as a PLEX_CLAIM environment variable in your container.

OK，It works!
