### ISSUE TITLE
[App Request] Nginx Proxy Manager

### ISSUE THREAD

**Issue by Najihel** [IceWhaleTech/CasaOS#558]
### App Information

- Name: Nginx Proxy Manager
- Short Description: Expose your services easily and securely 
- Official Website: https://nginxproxymanager.com
- GitHub Repository: https://github.com/NginxProxyManager/nginx-proxy-manager
- Docker Image: https://hub.docker.com/r/jc21/nginx-proxy-manager

### Why do you want this app?

It could be very usefull to add Nginx Proxy Manager into CasaOS to permit to expose apps through HTTP and HTTPs (Let's Encrypt)

**Comment by JohnGuan** [comment]
Initial NginxProxyManager
- https://github.com/IceWhaleTech/CasaOS-AppStore/commit/61b759d8a1e62e9ac1d176e6e18d542a1aad1743

**Comment by JohnGuan** [comment]
@LinkLeong Please test and update to App Store.

**Comment by JohnGuan** [comment]
Done!
