### ISSUE TITLE
Add an option to change the dashboard background image

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS#56]
Add an option to change the dashboard background image. This would help to visually, immediately distinguish between different hosts.

**Comment by JohnGuan** [comment]
What kind of pictures would you like to use as background? Upload it yourself or would you like some image source like Bing or Unsplash?

**Comment by rodhammond** [comment]
These options would be great:
1. Upload local image.
2. Use the Bing "Image of the Day". Be advised there are different Bing Image regions. Each region has a different image of the day. Awesome if you could determine the user's Bing image region and set the background accordingly.
3.  Upload image from user provided URL.

**Comment by JohnGuan** [comment]
This issue has been discussed here #191 , go ahead and join in.
