### ISSUE TITLE
【System Request】Unraid

### ISSUE THREAD

**Issue by ZQiannnn** [IceWhaleTech/CasaOS#560]
Site: https://unraid.net/
Unraid is a nas system based on linux

**Comment by llwaini** [comment]
@ZQiannnn What do you want the Unraid installation method or?

**Comment by ETWang1991** [comment]
I guess you wants a UNRAID-like Nas feature, which is already in development and will be released soon

**Comment by ThaBlazee** [comment]
Will the Nas feature support zfs/be able to import zfs arrays?
that would be awesome

**Comment by ETWang1991** [comment]
@ThaBlazee We've worked hard to already support ZFS-like capabilities. You can use the beta version of this feature in version 0.4.1, but be careful to back up your data and it is recommended that you use it during initialization.
https://blog.casaos.io/blog/v041.html

**Comment by ETWang1991** [comment]
![Image](https://user-images.githubusercontent.com/109786132/219609275-0efa9011-469b-4b55-bc75-2ad7c7c14d2c.png)
