### ISSUE TITLE
Add a RSS feed reader

### ISSUE THREAD

**Issue by spazziale** [IceWhaleTech/CasaOS#562]
The CasaOS webpage is gorgeous and I think many people (like me) have setted their instance as the default page for the browser.
So it could be helpful  to have an rss feed reader. I suggest to not reinvent the wheel and use something like the news feeder app from nextcloud ( so the streams are also synced through devices )

**Comment by otaviotscha** [comment]
What about FreshRSS?
- [Website](https://freshrss.org/)
- [DockerHub](https://hub.docker.com/r/freshrss/freshrss)
