### ISSUE TITLE
ShortCut feature not activated

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS#57]
Please activate the dashboard "Shortcut" feature in the general, public release.

Thanks

**Comment by JohnGuan** [comment]
😂Where did you see the Shortcut feature?
Can you talk about how you would use this feature?

We actually only had this feature in the design drawings, but we discussed it internally and felt it might not be a particularly necessary feature. I'm glad you brought it up, and I'd love to know your further thoughts!😁

**Comment by rodhammond** [comment]
Here: https://blog.zimaboard.com/wp-content/uploads/2021/10/20211019-164527.png (bottom of image "Shortcuts")

There also seems to be code referencing this feature in your  github source.

Thanks

**Comment by rodhammond** [comment]
- I have Portainer, PiHole, and Netdata installed on my CasaOS server. Netdata was installed from source, PiHole using Ansible, and Portainer usng the +App dashboard container feature. The shortcut feature would allow access for services not installed through the +App dashboard interface. Additionally, the dashboard app icon doesn't seem to open my Portainer container web page.

- You could also add an option to convert a "search" results or web page to a dashboard shortcut for future quick reference. Very similar to web browsers like Chrome.

-  You could also allow importing a browser shortcut html file for quickly creating favorite shortcuts from home PC.

**Comment by rodhammond** [comment]
- I have Portainer, PiHole, and Netdata installed on my CasaOS server. Netdata was installed from source, PiHole using Ansible, and Portainer usng the +App dashboard container feature. The shortcut feature would allow access for services not installed through the +App dashboard interface. Additionally, the dashboard app icon doesn't seem to open my Portainer container web page.

- You could also add an option to convert a "search" results or web page to a dashboard shortcut for future quick reference. Very similar to web browsers like Chrome.

-  You could also allow importing a browser shortcut html file for quickly creating favorite shortcuts from home PC.

**Comment by tenfar** [comment]
> * I have Portainer, PiHole, and Netdata installed on my CasaOS server. Netdata was installed from source, PiHole using Ansible, and Portainer usng the +App dashboard container feature. The shortcut feature would allow access for services not installed through the +App dashboard interface. Additionally, the dashboard app icon doesn't seem to open my Portainer container web page.
> * You could also add an option to convert a "search" results or web page to a dashboard shortcut for future quick reference. Very similar to web browsers like Chrome.
> * You could also allow importing a browser shortcut html file for quickly creating favorite shortcuts from home PC.

I needed the same feature，so i took some time to enable the feature base on exist codebase with some ugly modification. the source code is in my repo.  you can try to compile it by yourself.

**Comment by JohnGuan** [comment]
This issue has been discussed here #177 , go ahead and join in. It seems to be a very hot need.
