### ISSUE TITLE
System failure when using CasaOS (hardware: ZimaBoard 432) to upload a 20G file

### ISSUE THREAD

**Issue by zhangxian1386** [IceWhaleTech/CasaOS#570]
**Describe the bug**
I opened webui from another computer and uploaded a movie (about 20 gigabytes) to my external mechanical hard drive. Everything looked fine at the time, about 20 megabytes per second upload speed. Then I just hung up and left it alone.
The next morning I looked and saw that the upload task had failed, I tried again and it still didn't work, it just said error. Then I restarted in the terminal and in the WebUI screen I noticed that the system disk was red.
So I restarted my device and connected the monitor. to see what was happening and then I noticed that I couldn't get into Debian properly and was stuck at the loading screen.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.6
	 - Disk Total: 27712 
	 - Disk Used: 9371 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7802M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
	 - Remote Version: 0.3.6
	 - Browser: Chrome 
	 - Version: 105.0.0.0

**Comment by ChainRythm** [comment]
Experiencing the same problem on ZimaBoard 832. When using CasaOS Files GUI to upload a file, the system writes temp files in 1mb chunks to /var/lib/casaos/tmp/[GUID?]/*. These chunks seem to be used for upload retry. Once the disk is full the upload will fail and the system will encounter out of space issues. had to rm * in [GUID?] folder to fix the issue. Not sure how doable this would be, but I would suggest using destination path as the tmp folder to avoid this issue.

**Comment by raller1028** [comment]
This issue has been fixed in 0.3.7.1, please verify in the update to 0.3.7.1, if you have problems, please reopen the issue.
