### ISSUE TITLE
[App Request] Gitea

### ISSUE THREAD

**Issue by Najihel** [IceWhaleTech/CasaOS#574]
### App Information

- Name: Gitea
- Short Description: Git with a cup of tea - The goal of this project is to make the easiest, fastest, and most painless way of setting up a self-hosted Git service.
- Official Website: https://gitea.io
- GitHub Repository: https://github.com/go-gitea/gitea
- Docker Image: https://hub.docker.com/r/gitea/gitea

### Additional information?

Docker installation : https://docs.gitea.io/fr-fr/install-with-docker/

**Comment by wiedymi** [comment]
Please, add it.

**Comment by JohnGuan** [comment]
Initial Gitea
- https://github.com/IceWhaleTech/CasaOS-AppStore/commit/7964a52da3023ed3e78541afd795da2429c65d4e

@LinkLeong  Please test and update to App Store.

**Comment by JohnGuan** [comment]
Done!
