### ISSUE TITLE
[Bug] Error response from daemon: invalid mount config for type "bind"

### ISSUE THREAD

**Issue by tricalancer67** [IceWhaleTech/CasaOS#575]
### What happened?

Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /DATA/AppData/Transmission/config

**Comment by LinkLeong** [comment]
We have tried many times without the problem you described, you can try more. If the problem is not solved please reopen the problem

**Comment by hexWars** [comment]
你好，我也遇上了这个问题，casa版本0.3.8

服务器配置如下：
OS: Ubuntu 22.04.1 LTS x86_64 
Kernel: 5.15.0-56-generic 
CPU: Intel i5-6200U (4) @ 2.800GHz 
GPU: NVIDIA GeForce 940MX 
GPU: Intel Skylake GT2 [HD Graphics 520] 
内存4G

所有的应用全部无法下载，全部会报错`[Bug] Error response from daemon: invalid mount config for type "bind"`，不知如何解决

**Comment by TipanLogic** [comment]
have the same problem

**Comment by Hedius** [comment]
The docker snap is not supported


1. Replace the docker snap with apt package.

**Comment by rudra-code-creator** [comment]
> The docker snap is not supported
> 
> 1. Replace the docker snap with apt package.

How do I do that Hedius?

**Comment by Liparu** [comment]
I did the following and CasaOS works now:

1. I uninstalled docker snap

`sudo snap remove docker --purge`

2. I uninstalled docker apt package, in case there was any present (I tried installing it, like Hedius suggested, but then the Appstore wouldn't work)

`sudo apt remove docker`

3. I unistalled CasaOS

`sudo casaos-uninstall`

4. I installed CasaOS again, CasaOS will install the right version of Docker automatically

`curl -fsSL https://get.casaos.io | sudo bash`

That's it.

**Comment by hqnicolas** [comment]
thanks @Liparu

**Comment by haywardgg** [comment]
Had the same issue, but https://github.com/IceWhaleTech/CasaOS/issues/575#issuecomment-2040104041 fixed it for me.

**Comment by conversem** [comment]
Thanks this worked! Docker came preinstalled with Ubuntu Server. Entirely removing docker worked.

What I did:

First find all docker instances:
`dpkg -l | grep docker`

1. Purge Docker Packages
Run the following command to remove all Docker-related packages:

`sudo apt purge -y docker-compose docker.io python3-compose python3-docker python3-dockerpty
`
2. Remove Dependencies and Unused Packages
Clean up any remaining dependencies and unused packages:
```
sudo apt autoremove -y
sudo apt autoclean
```

3. Verify Removal
Check if any Docker packages are still installed:

`dpkg -l | grep docker`

Also, confirm that the docker command is no longer available:

`docker --version`

4. Remove Residual Files
Double-check and manually remove any Docker-related directories or files if they still exist:

```
sudo rm -rf /var/lib/docker
sudo rm -rf /etc/docker
sudo rm -rf /usr/lib/docker
sudo rm -rf /usr/share/docker
```
5. Reboot the System
After purging and cleaning everything, reboot your system to ensure all processes and files are cleared:

`sudo reboot`
