### ISSUE TITLE
通过动态域名访问casaos时，小组件不能显示网速

### ISSUE THREAD

**Issue by rxy0924** [IceWhaleTech/CasaOS#581]
**Describe the bug**
本地局域网访问时小组件显示网速，但通过外网访问时不显示

系统信息
 - OS: linux
 - CasaOS Version: 0.3.6
 - Disk Total: 5978 
 - Disk Used: 1039 
 - System Info: [Armbian 22.11.0-trunk Jammy \l Bit:64 Mem:1954M Core:4 Linux armbian 5.15.70-flippy-77+o #180 SMP PREEMPT Sat Sep 24 09:59:51 CST 2022 aarch64 aarch64 aarch64 GNU/Linux]
 - Remote Version: 0.3.6
 - Browser: Chrome 
 - Version: 86.0.4240.198

**Comment by LinkLeong** [comment]
The web widget is sent through the websocket port, so you also need to open the websocket port in the firewall, check the specific port in the developer tools.
网络小组件是通过websocket端口进行发送的,所以你还需要在防火墙打开websocket的端口,具体请在开发者工具中查看具体端口.
