### ISSUE TITLE
Update app manually

### ISSUE THREAD

**Issue by Ludo-code** [IceWhaleTech/CasaOS#585]
Hello, I make this feature request to add a button on each app installed in casaos to update it manually from just a simple click instead of update manually with docker command line... 

I don't have seen other issue that mentioned that so I put my. 

Thanks for our reply :)

**Comment by ETWang1991** [comment]
We have paid attention to this issue, and after the current version is released, we will turn our attention back to APP management including upgrade related issues.

**Comment by Ludo-code** [comment]
Thanks you I will wait for this improvements :)

**Comment by mbox5** [comment]
> We have paid attention to this issue, and after the current version is released, we will turn our attention back to APP management including upgrade related issues.

This is not a small issue. It's the #1 reason I still can't throw my 100% support behind CasaOS and become your super-fan. I have it running on my LAN, it's working well but it can be better, app upgrades being the #1 issue for me. Thanks!

**Comment by mojothemonkey2** [comment]
For this I think we need to change the way CasaOS is handling dockers slightly..

So currently, when we stop/start an app, it does `docker stop <container>`
The container is not destroyed, so we can't change the image it is using.

Instead, when we stop an app, we should destroy the container (and can strip the network too, ie same as `docker-compose down`).
And re-start the app like we do initially (effectively `docker-compose up`).
(I think this is how it works already if we change app settings).

If meanwhile, we have pulled an updated image, it will fire up with the new image.
So then we can have apps check-for and download new versions (pull images) in the background, and restart to switch to the new version.

Asside: also be good to remove the feature that prevents changing the image name once an app has been created. To allow for choosing a specific version of an app.

**Comment by Ludo-code** [comment]
Hello, do you know already in which release the feature will be available?

**Comment by tigerinus** [comment]
@Ludo-code - will try to get this implemented in v0.4.2

**Comment by raller1028** [comment]
@Ludo-code  v0.4.2 has been released, you can try to update the app manually
