### ISSUE TITLE
[Alpha][Bug] `Device not found` after bonding Network Interface Controllers (NICs) into one

### ISSUE THREAD

**Issue by wsnhjll** [IceWhaleTech/CasaOS#588]
### What happened?

Appears after installation bonding_masters: error fetching interface information: Device not found 
IP access denied

**Comment by cogscides** [comment]
Yeah, same for me. But it happened with v0.4.2.

**Comment by tigerinus** [comment]
@wsnhjll @cogscides - can you please provide more context and details about this issue?

**Comment by tigerinus** [comment]
@wsnhjll @cogscides - it'd be great if one of you can confirm the steps to reproduce this issue.

Can you confirm if it's something like what's described in https://www.ubuntu-server.com/ubuntu/how-to-set-up-network-bonding-ubuntu-20-04/?

Thanks.

**Comment by Applejuicelolmc** [comment]
I also got this error when installing CasaOS 0.4.4 on a Debian 12 LXC container in Proxmox 8.0.3 and no IP adress is being shown

![image](https://github.com/IceWhaleTech/CasaOS/assets/47336045/a479a079-1a4b-4188-9388-9a083cff9dab)

I'm able to access the internet and update this container, so I'm not sure what the problem is?

I also took a look at the link below, but my setup didn't include setting up network bonding. 

> @wsnhjll @cogscides - it'd be great if one of you can confirm the steps to reproduce this issue.
> 
> Can you confirm if it's something like what's described in https://www.ubuntu-server.com/ubuntu/how-to-set-up-network-bonding-ubuntu-20-04/?
> 
> Thanks.

I just installed a fresh Proxmox iso on my Lenovo M715Q, created a Debian 12 LXC container and installed CasaOs on it. Both Proxmox and Debian 12 were completely updated before installing CasaOS.

I'm not sure what I can provide more that can help but feel free to ask.

**Comment by raller1028** [comment]
Sorry, we don't support finding NICs in LXC containers at the moment, but we'll figure out how to support it in the future :)

**Comment by AlrinXNI** [comment]
I got this too, and  I modified  /etc/casaco/gateway.ini, set a port not used in the OS before, and rebooted CASAOS. And now, the new port is working fine.

**Comment by ohmyharry** [comment]
> I also got this error when installing CasaOS 0.4.4 on a Debian 12 LXC container in Proxmox 8.0.3 and no IP adress is being shown
> 
> ![image](https://private-user-images.githubusercontent.com/47336045/256022427-a479a079-1a4b-4188-9388-9a083cff9dab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NDM4NjUsIm5iZiI6MTcwODg0MzU2NSwicGF0aCI6Ii80NzMzNjA0NS8yNTYwMjI0MjctYTQ3OWEwNzktMWE0Yi00MTg4LTkzODgtOWEwODNjZmY5ZGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDA2NDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMmM2MTIxMjAxMjBkMTJhZTBhODY2NWYzYmFlMTFkNzhhZDI0YjQ2Y2QxZmU2MmYxNTBhMmU2MmE2YzgyMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QHFsvxLoRQQcCQmk3P1u82jG0qNrJpgs-r6ZuYduapE)
> 
> I'm able to access the internet and update this container, so I'm not sure what the problem is?
> 
> I also took a look at the link below, but my setup didn't include setting up network bonding.
> 
> > @wsnhjll @cogscides - it'd be great if one of you can confirm the steps to reproduce this issue.
> > Can you confirm if it's something like what's described in https://www.ubuntu-server.com/ubuntu/how-to-set-up-network-bonding-ubuntu-20-04/?
> > Thanks.
> 
> I just installed a fresh Proxmox iso on my Lenovo M715Q, created a Debian 12 LXC container and installed CasaOs on it. Both Proxmox and Debian 12 were completely updated before installing CasaOS.
> 
> I'm not sure what I can provide more that can help but feel free to ask.

I got this too, the same environment

**Comment by ohmyharry** [comment]
> I got this too, and I modified /etc/casaco/gateway.ini, set a port not used in the OS before, and rebooted CASAOS. And now, the new port is working fine.

Thanks,it works
