### ISSUE TITLE
Additional Docker Shells

### ISSUE THREAD

**Issue by tandhadmin** [IceWhaleTech/CasaOS#594]
Login to an app's Docker instance via a shell in the apps settings page within CasaOs

Might be nice to include a drop down for sh or ash as well as bash. For instance the eclipse-mosquitto Docker image uses sh not bash.

**Comment by tigerinus** [comment]
this issue has been addressed by https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/62

It turns out that `/bin/sh` will always exists (unless it's a distro-less image). To use a different shell, just run that shell from `sh`.
