### ISSUE TITLE
[Bug] Cann't access to my Casaos

### ISSUE THREAD

**Issue by edrun** [IceWhaleTech/CasaOS#598]
1、Zimaboard
2、Casos 0.3.6 

Work with cookbook for only 2-3 hours. And then can't access casaos with http://casaos.local or http://ip addr , the 80 port is forbidden.

But the dockers work well via http://zimaboard ip addr:port
Where to find the right port of my casaos http://ipaddr:port ?
And how to set my own port for CasaOS?

**Comment by jerrykuku** [comment]
Hi，you can use this command ```sudo systemctl status casaos-gateway``` check the casaos gateway service first.
and you can find the right port of casaos in /etc/casaos/gateway.ini .

**Comment by edrun** [comment]
@jerrykuku  Solved! It works well now on my Zima. TKS
