### ISSUE TITLE
Install directly using docker

### ISSUE THREAD

**Issue by xiaoyaohanyue** [IceWhaleTech/CasaOS#61]
Use docker compose directly to complete the installation, because I need to point to another port. I have installed aapanel and installed docker on aapanel. So is there any way to install it directly in docker with commands?

**Comment by LinkLeong** [comment]
Sorry, we don't plan to do this, do you want casaOS to manage existing docker applications?

**Comment by bexem** [comment]
> Sorry, we don't plan to do this, do you want casaOS to manage existing docker applications?

Is that actually possible? I currently have a simple ubuntu server running on my RaspberryPi4 with few docker containers, would it be possible to install CasaOS and manage the existing containers (and macvlans)? Or do I have to start from scratch? 

Sorry I know it might be off-topic but the quoted question is exactly what I was searching!

**Comment by xiaoyaohanyue** [comment]
> Sorry, we don't plan to do this, do you want casaOS to manage existing docker applications?

Is not what it means. I want to use aapanel to manage casaOS. Because I have installed LNMP environment and Docker via aapanel. Therefore, I want to directly use aapanel's built-in Docker manager to install and configure casaOS

**Comment by JohnGuan** [comment]
Have you tried the new version of CasaOS yet? Does it meet your needs.

**Comment by xiaoyaohanyue** [comment]
Maybe my meaning is not clear. What I want is to use "docker run..." Or docker-compose to complete casaos installation

**Comment by xiaoyaohanyue** [comment]
> Have you tried the new version of CasaOS yet? Does it meet your needs.

Sorry， I don't find any DockerFile or docker-compose.yml or 'docker run' command to install CasaOS

**Comment by tigerinus** [comment]
> Maybe my meaning is not clear. What I want is to use "docker run..." Or docker-compose to complete casaos installation

CasaOS doesn't run via Docker. It depends on certain capabilities, such as direct access to harddrives, which Docker doesn't come with.
