### ISSUE TITLE
[Bug] All Tube Download

### ISSUE THREAD

**Issue by ltnhawk** [IceWhaleTech/CasaOS#613]
All Tube Download

This docker does not work at all. I installed it but when I try to open it won't work. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the followinginformation):**

**Additional context**

**Comment by raller1028** [comment]
What is the exact model of your hardware device?
AllTubeDownload currently only supports x86 architecture

**Comment by ltnhawk** [comment]
I'm using a RaspberryPi 4B with ssd.

Oct 26, 2022 3:37:51 AM raller1028 ***@***.***>:

**Comment by raller1028** [comment]
RaspberryPi architecture is arm, and AllTubeDownload currently only supports amd64 architecture
