### ISSUE TITLE
[App Request] Web Browser in a docker 

### ISSUE THREAD

**Issue by ltnhawk** [IceWhaleTech/CasaOS#614]
### App Information

- Name: 
- Short Description: 
- Official Website: 
- GitHub Repository: 
- Docker Image:

**Comment by AuthorShin** [comment]
Please add descriptions completely.

**Comment by yesbhautik** [comment]
Name: google chrome
Short Description: a Brower
Official Website: https://www.google.com/intl/en_in/chrome/
GitHub Repository: https://github.com/GoogleChrome/developer.chrome.com
Docker Image: no idea

use own personal browser anywhere with servers high speed and pre login accounts and bookmarks
