### ISSUE TITLE
希望在安装脚本中添加检测本地已下载包的功能

### ISSUE THREAD

**Issue by MengChenJack** [IceWhaleTech/CasaOS#616]
众所周知的原因，国内访问github很慢，如果下载失败则每次打开安装脚本都会从头开始。如果能加入检测功能，就能节省大量时间，就不需要一遍一遍重复下载了

**Comment by ETWang1991** [comment]
最近墙内安装的稳定性有所提高，可以再试一下。不过最终解决这个问题，需要整合更多的资源，需要再多一些时间。

**Comment by jerrykuku** [comment]
目前依赖包已经是只安装需要的包，CasaOS的包也使用了OSS进行国内的分流，相信下载速度已经得到一定程度的改善，这个议题已经很久没有更新了，我将关闭它，如果还有问题的话，你可以重新的打开它并反馈给我们。
