### ISSUE TITLE
[Bug] CPU Wattage 0.0W, Top CPU/RAM usage 0

### ISSUE THREAD

**Issue by oddsun** [IceWhaleTech/CasaOS#626]
**Describe the bug**
In the web dashboard, the CPU wattage is 0.0W always. The CPU/RAM usage is 0%/0 for all apps.

**To Reproduce**
1. Go to web dashboard
2. See the widgets

**Expected behavior**
CPU wattage and Top CPU/RAM usage should be non-zero

**Screenshots**
<img width="1488" alt="Screen Shot 2022-10-24 at 12 05 34 PM" src="https://user-images.githubusercontent.com/1161465/197573173-7675536f-f0b3-47f1-a848-8efa8ef6263d.png">

<img width="1485" alt="Screen Shot 2022-10-24 at 12 05 53 PM" src="https://user-images.githubusercontent.com/1161465/197573205-ec63643f-6e6a-4088-ac3c-d8f0b841c43e.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04.5 LTS (Raspberry Pi 4, 4GB)
 - Browser: Chrome
 - Version: 106

**Additional context**

**Comment by Ludo-code** [comment]
Same problem on Chrome, Firefox, Vivaldi, Brave.
With Ubuntu Desktop 22.10 on raspberry pi 4b+ 8go

**Comment by zhanghengxin** [comment]
are you in a  virtual machine?

**Comment by Ludo-code** [comment]
No virtual machine for me it's only phisical.

**Comment by tengqian** [comment]
me too,phisical machine
os:ububtu server 22.04 lts x86_64

**Comment by LinkLeong** [comment]
The current power consumption supports Intel's cpu, if you still have questions, please reply to the hardware specific model.

**Comment by ETWang1991** [comment]
![cpubug](https://user-images.githubusercontent.com/109786132/199391505-5cf48913-da51-4315-a799-d5aa59668a0b.png)
