### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by chiragnahata** [IceWhaleTech/CasaOS#631]
I have installed casaos on my server but it got installed as local ip I mean cannot access it from outside. Please help

![image](https://user-images.githubusercontent.com/63905783/198080079-187497c9-7214-43fc-a21b-22ebb54d48d2.png)

I have tried with the port 81  but cannot reach . http://ipaddress:81/

![image](https://user-images.githubusercontent.com/63905783/198080229-d98700c3-ec81-4f98-8b2b-f776aa5eeabf.png)
![image](https://user-images.githubusercontent.com/63905783/198080277-f2fd6bba-2421-4d1a-a982-0da33c5b2b14.png)
![image](https://user-images.githubusercontent.com/63905783/198080331-e1e25b4c-aad2-40ee-88b7-24539aeb37e6.png)
![image](https://user-images.githubusercontent.com/63905783/198080398-29652b2c-41f0-4b31-a25e-6b8452aeb73a.png)

https://discord.com/channels/884667213326463016/1021362958292500531

**Comment by yesbhautik** [comment]
same issue

**Comment by LostPoE** [comment]
same issue
