### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Niu-jinjian** [IceWhaleTech/CasaOS#632]
### What happened?

Hello, I have successfully installed CasaOS and provided the access address to me, but I cannot access it with my browser. Its service status is running. I see that many people have been discussing this problem. Please handle it. Thank you

### Screenshots

![image](https://user-images.githubusercontent.com/104963854/198083999-f79d940f-d813-4926-973b-e05e972a86cc.png)
![image](https://user-images.githubusercontent.com/104963854/198084142-37e94d6c-2009-41ce-99a6-1b1de22aad41.png)

**Comment by tigerinus** [comment]
@Niu-jinjian - can you run following commands to collect some logs for us?

```bash
sudo systemctl list-units --type service | grep casa

sudo journalctl -xef -u casaos-gateway.service
```

**Comment by tigerinus** [comment]
@Niu-jinjian - I'm closing this bug for now. 

If you have more info, please re-open.

**Comment by sudahlah** [comment]
I encountered the same thing while connecting using ethernet. Any update on this? What was the resolution?
