### ISSUE TITLE
[Alpha][Bug] I can not update CasaOS from 0.3.6 to 0.3.7

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#633]
### What happened?

It is impossible to update CasaOS, the software does not notify of the new update. Is there any way to fix it? Is it possible to update manually with commands?

### Screenshots

![image](https://user-images.githubusercontent.com/18572939/198344147-50a7a38c-7ba5-4b7a-8983-489660bcde9c.png)

**Comment by AmadeusGraves** [comment]
searching for problems, I found that you can run this command. Is it still functional?

`curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/main/update.sh | sudo bash`

**Comment by tigerinus** [comment]
Update from UI typically rolls out few days after the release.
