### ISSUE TITLE
[Bug] Missing Apps in app store

### ISSUE THREAD

**Issue by cj2tech** [IceWhaleTech/CasaOS#634]
**Describe the bug**

**To Reproduce**
1. Open App Store
2. Scroll Down 

**Expected behavior**
The app store is missing advertised apps listed:

- Radarr
-  Tautulli
- DuckDNS
- Couch Potato
- Nginx
- nzbget

**Screenshots**
![image](https://user-images.githubusercontent.com/9431091/198507680-30357702-c2ec-43f9-b5f6-c11bb2afb64f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]106.0.5249.121

**Additional context**
Host hardware

- Raspberry Pi 4
- Debian GNU/Linux 11 (bullseye) x64
- CasaOS version v0.3.7

**Comment by JohnGuan** [comment]
Radarr is back.
The rest Link and I will check again.

**Comment by JohnGuan** [comment]
@cj2tech Nzbget It's in the picture you show

- Tautulli
- DuckDNS
- Couch Potato
- Nginx

The above is not adapted, you can submit it here.

- https://github.com/IceWhaleTech/CasaOS/issues/431
