### ISSUE TITLE
[Bug] 更新后小组件问题 以及USB硬盘未自动挂载 [附带临时解决方法]

### ISSUE THREAD

**Issue by curtisrecords** [IceWhaleTech/CasaOS#635]
1. 在更新后页面左侧小组件（磁盘）不显示硬盘容量大小 显示为0B/0B 且点击进入后无显示挂载磁盘 显示为空
2. 更新前使用USB插入硬盘 CasaOS自动挂载至/DATA 后更新 部分容器无法正常启动 排查之后发现硬盘并未自动挂载
```bash
sudo mkdir /mnt/casaoshdd
sudo fdisk -l
sudo mount /dev/sdb /mnt/casaoshdd
```
成功挂载之后在 CasaOS内修改部分容器的目标目录为 /mnt/casaoshdd 之后解决 如果需要长期自定义挂载目录 或者要CasaOS文件管理识别 请挂载到 /DATA/whatever 目录 如果需要持续性的自动挂载 请修改fstab文件。

**Comment by curtisrecords** [comment]
- 补充一下 在CasaOS内启动Container的时候 希望右下角可以给出错误详情 而不是单纯提示error 这点希望可以优化下~ 在上方问题排障的时候确实造成了一些困扰 后面cli进去尝试启动docker某个特定的container的时候才发现原来是磁盘挂载问题//

**Comment by tigerinus** [comment]
更新后 storage 服务没有自行启动的问题已经修复，运行下列命令获得最新更新：

```bash
curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/main/update.sh | sudo bash
```

自动挂载问题在 0.3.8 会改进
