### ISSUE TITLE
关于CN大陆的辛酸玩家

### ISSUE THREAD

**Issue by haust-lyb** [IceWhaleTech/CasaOS#637]
The installation script does not work in the Medieval continent

大佬，可否搞一个中国大陆可以安装的脚本啊，这个脚本github的很多东西在天朝没法下载到，系统很好，拜托了，或者提供完整的镜像？总之，给一个大陆可用的方案吧，万分感谢o(╥﹏╥)o

master, can you make a script that can be installed in mainland China. Many things in this script github can't be downloaded in China. The system is very good. Please, or provide a complete mirror? In short, give a plan available in the mainland, thank you very much 

o(╥﹏╥)o

**Comment by luc-yang** [comment]
get仓库目录下有cn_install.sh，https://github.com/IceWhaleTech/get/blob/main/cn_install.sh，可以稳定安装，目前支持到0.3.6版本。

**Comment by tigerinus** [comment]
@haust-lyb 完整方案正在实现中。

暂时请用 @luc-yang 的方法安装，不好意思。
