### ISSUE TITLE
Storage Widget [Bug] 

### ISSUE THREAD

**Issue by seawolf82** [IceWhaleTech/CasaOS#638]
**Describe the bug**
After upgraded CasaOs version to 0.3.7 the widget storage don't work anymore

![Cattura](https://user-images.githubusercontent.com/6764404/198611584-5921cc11-4465-41e2-9279-b636e8ca1c54.PNG)

 - OS: linux
 - CasaOS Version: 0.3.7
 - Disk Total: 59870 
 - Disk Used: 10023 
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1849M Core:4 Linux HomeServer 5.15.74-v8+ #1595 SMP PREEMPT Wed Oct 26 11:07:24 BST 2022 aarch64 GNU/Linux]
 - Remote Version: 0.3.7
 - Browser: Firefox 
 - Version: 106.0

**Comment by Ludo-code** [comment]
same problem after updating 0.3.6 to 0.3.7 on my ubuntu desktop 22.10

**Comment by tigerinus** [comment]
We fixed an issue where storage service failed to start just about 2 days ago.

@seawolf82 @Ludo-code - try this fix:

```bash
curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/main/update.sh | sudo bash
```

**Comment by Ludo-code** [comment]
This as working for me thanks you @tigerinus
