### ISSUE TITLE
[Error] Unable to open the home page.

### ISSUE THREAD

**Issue by Ma-Mingli** [IceWhaleTech/CasaOS#639]
![90F41577-B713-41B9-BDF0-E12BA477BF61](https://user-images.githubusercontent.com/91407828/198679458-194d0f06-c4f8-477e-a8b8-aec586418685.png)

**Comment by tigerinus** [comment]
If you do `curl localhost:80` what does it return (assuming you didn't change the port) ?

**Comment by Maml2021** [comment]
Is it like this?![4B58E672-BCF2-419B-B553-C99D605171F1](https://user-images.githubusercontent.com/91407828/198897860-037e437a-0ed7-43ed-bdd4-4562e2a4b00b.jpeg)

**Comment by Maml2021** [comment]
@tigerinus

**Comment by tigerinus** [comment]
This means the homepage is being served fine.

Check your firewall settings on the device, the router as well as your client computer.

**Comment by Maml2021** [comment]
@tigerinus It's a white screen, and the computer browser can be opened from time to time. The iPad can't open the homepage directly, and it's always white.

**Comment by Maml2021** [comment]
![F6EDEC58-FB2D-4FAC-AB90-BCCF2701764C](https://user-images.githubusercontent.com/91407828/198899306-abb8f46c-c0f4-430b-95b7-7dfed009bd62.png)

**Comment by tigerinus** [comment]
@zhanghengxin can you take a look?

**Comment by zhanghengxin** [comment]
first use “Vue.js devtools” in web
such as https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

then 
![image](https://user-images.githubusercontent.com/24197448/198914641-9559875e-f6bf-405f-bb0c-82b267cd14ed.png)

select the part of white screen as following
![image](https://user-images.githubusercontent.com/24197448/198914997-0ca2bb7b-cbce-4822-9f99-556f801b671d.png)

**Comment by Maml2021** [comment]
@zhanghengxin The computer browser can be refreshed now. The iPad browser is still open with a white screen, and the iPad browser can't do this, can it?

**Comment by Maml2021** [comment]
Wait, I'll simulate the mobile browser with a computer browser and try what state it is.

**Comment by zhanghengxin** [comment]
> @zhanghengxin The computer browser can be refreshed now. The iPad browser is still open with a white screen, and the iPad browser can't do this, can it?

you can do it in mac browser,。

**Comment by Maml2021** [comment]
@zhanghengxin The problem is I'm an iPad, not a MAC computer
I just tried computer simulation, mobile browser can open the homepage
The iPad just turns on the white screen

**Comment by Maml2021** [comment]
Is it possible that there is a problem with the mobile phone's UI adaptation, and what methods can the iPad use to obtain error information

**Comment by zhanghengxin** [comment]
i have found it. let me trace it and lock in

**Comment by Maml2021** [comment]
@zhanghengxin Hello, I found the demo.casaos.io demo station. Both Apple phones and iPad have white screens, but Android phones are normal.
![AB54F16B-BB50-4BB3-B520-74C71BF3B8C8](https://user-images.githubusercontent.com/91407828/198969381-e35bde8f-1ae5-42f8-bf09-706a050bb391.jpeg)
![F1C7A1B0-0C30-466D-8EDF-367F3A8FE665](https://user-images.githubusercontent.com/91407828/198969390-e12a6f24-8e19-49e7-a6cc-640734752484.png)

**Comment by zhanghengxin** [comment]
> @zhanghengxin Hello, I found the demo.casaos.io demo station. Both Apple phones and iPad have white screens, but Android phones are normal. ![AB54F16B-BB50-4BB3-B520-74C71BF3B8C8](https://user-images.githubusercontent.com/91407828/198969381-e35bde8f-1ae5-42f8-bf09-706a050bb391.jpeg) ![F1C7A1B0-0C30-466D-8EDF-367F3A8FE665](https://user-images.githubusercontent.com/91407828/198969390-e12a6f24-8e19-49e7-a6cc-640734752484.png)

you update the demo??

**Comment by Ma-Mingli** [comment]
@zhanghengxiWhat? I didn't update the demo. It's just that yesterday, when I turned on the demo, it also showed a white screen. I had a whim to use the Android phone and it turned on. At first glance, it was the same as the version I installed, so please remind me that you can use the demo to find out what caused the iPad and Apple phones to turn on the white screen.

**Comment by zhanghengxin** [comment]
i have resolve the problem !
you can try to rerun the script which install or update

look: https://github.com/IceWhaleTech/CasaOS#quick-setup-casaos

**Comment by zhanghengxin** [comment]
> @zhanghengxiWhat? I didn't update the demo. It's just that yesterday, when I turned on the demo, it also showed a white screen. I had a whim to use the Android phone and it turned on. At first glance, it was the same as the version I installed, so please remind me that you can use the demo to find out what caused the iPad and Apple phones to turn on the white screen.


It's not the same problem，，，，，，the issue only occurs in version 0.3.7，but demo‘s version is 0.3.6

**Comment by zhanghengxin** [comment]
but!!,i just tried it and didnt find any problem

**Comment by Ma-Mingli** [comment]
@zhanghengxin OK, it's hard. Because of the network problem, I have to go to the proxy upgrade. I will try to upgrade again later. I just log on to the demo, and the iPad is also blank. So I can use my Android phone to open it normally. Last night, I watched the demo, and it will be 0.3.6 and 0.3.7. I never touched it. 0.3.6 iPad can open, and 0.3.7 iPad is blank

**Comment by zhanghengxin** [comment]
> @zhanghengxin OK, it's hard. Because of the network problem, I have to go to the proxy upgrade. I will try to upgrade again later. I just log on to the demo, and the iPad is also blank. So I can use my Android phone to open it normally. Last night, I watched the demo, and it will be 0.3.6 and 0.3.7. I never touched it. 0.3.6 iPad can open, and 0.3.7 iPad is blank

what does will be" mean?  --
“and it will be 0.3.6 and 0.3.7. I never touched it. 0.3.6 iPad can open, and 0.3.7 iPad is blank”

but What I saw was that it was okay  <iphone/0.3.6>
![image](https://user-images.githubusercontent.com/24197448/199170296-31d80200-f4a3-48e5-966a-e6fe88e78608.png)

**Comment by Ma-Mingli** [comment]
@zhanghengxin It's all right. Thank you for your hard work!

**Comment by Ma-Mingli** [comment]
Maybe I didn't make it clear. I mean that the casaos version 0.3.6 iPad and iPhone can be turned on normally, and the casaos version 0.3.7 iPad and iPhone are white screens.

**Comment by zhanghengxin** [comment]
solution ：：re-run installation or upgrade script on the terminal

https://github.com/IceWhaleTech/CasaOS#quick-setup-casaos
