### ISSUE TITLE
[Bug] cannot upgrade from v0.2.3 to v0.3.7 (new ZimaBoard)

### ISSUE THREAD

**Issue by jlgeering** [IceWhaleTech/CasaOS#642]
**Describe the bug**

error shown in the logs after clicking the update button on a new zimaboard that came with casaos v0.2.3:

[ERROR][system.go:27]2022/10/28 16:11:01 [[[ INFO ] Downloading CasaOS for linux/amd64... [ INFO ] https://github.com/IceWhaleTech/CasaOS/releases/download/v0.3.7/linux-amd64-casaos.tar.gz Aborted, error 22 in command: ${net_getter} "$casa_url" > "$PREFIX/tmp/$casa_file"]]

it seems like this file is missing:

https://github.com/IceWhaleTech/CasaOS/releases/download/v0.3.7/linux-amd64-casaos.tar.gz

it did exist for version v0.3.6:

https://github.com/IceWhaleTech/CasaOS/releases/download/v0.3.6/linux-amd64-casaos.tar.gz

there seem to be a version for v0.3.7 with a different filename, but this is not picked up by the installer

https://github.com/IceWhaleTech/CasaOS/releases/download/v0.3.7/linux-amd64-casaos-v0.3.7.tar.gz

**Comment by jlgeering** [comment]
any chance to add the missing file to the release?

**Comment by jlgeering** [comment]
or is there a way to tell the updater to try installing v0.3.6 instead of v0.3.7?

(maybe using the command line instead of the gui)

**Comment by tigerinus** [comment]
@LinkLeong - do you remember if v0.2.x uses the same `update.sh` as the newer versions?

**Comment by tigerinus** [comment]
@jlgeering - if you can't wait for a fix, try following command in your terminal as a workaround

```bash
curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/main/update.sh | sudo bash
```

**Comment by LinkLeong** [comment]
It has been resolved, now it can be upgraded normally, the upgrade will not be automatic, and it needs to be refreshed manually
