### ISSUE TITLE
[Bug] Network Status Pannel do not work

### ISSUE THREAD

**Issue by decadenceqi** [IceWhaleTech/CasaOS#645]
**Describe the bug**
Network Status Pannel do not work.
网络状况面板不生效，不会显示当前网卡流量

**To Reproduce**
main page
首页

**Screenshots**
<img width="352" alt="截屏2022-10-31 14 40 51" src="https://user-images.githubusercontent.com/6396992/198947019-69c0adc8-caad-4ec9-99e8-d4db47cae2f0.png">

**Desktop (please complete the following information):**
 - OS: mac os 13
 - Browser edge
 - Version 106.0.1370.34

**Additional context**
- hardware system: debian bullseye
- casaos version: v0.3.7

**Comment by Ludo-code** [comment]
Hello, you can take a look to the #638 issue on the github...

You can find in this the line who have solved the storage widget. 
```
curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/main/update.sh | sudo bash
```

**Comment by decadenceqi** [comment]
> Hello, you can take a look to the #638 issue on the github...
> 
> You can find in this the line who have solved the storage widget.
> 
> ```
> curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/main/update.sh | sudo bash
> ```


Maybe I didn't make it clear. I mean the Network Status Pannel didn't work. Not the Storage Pannel.

**Comment by Ludo-code** [comment]
I think this can solve the network panel too.
Otherwise you can wait a more competent guys.

**Comment by decadenceqi** [comment]
> I think this can solve the network panel too. Otherwise you can wait a more competent guys.

still thanks

**Comment by jerrykuku** [comment]
How many NICs do you have, and can't each one display status?
You can add my wechat to join our webchat group. I can get more information.
My wechat id is: jerryk

**Comment by decadenceqi** [comment]
> jerryk

3个网卡，每个都不好使，我已经发送微信申请了

**Comment by decadenceqi** [comment]
问题已经由jerrykuku排查了。

由于我用了第三方的内网穿透服务，给casaos套了https的外网访问地址，而流量显示协议依然使用的ws进行通讯，所以一直连接不上。

**Comment by Dids** [comment]
What was the fix for this? I installed the latest Debian 11 (with non-free firmware for the NICs), and my network graph isn't being updated either. Only one of the NICs is plugged in, which in this case is `enp2s0`.

**Comment by decadenceqi** [comment]
> What was the fix for this? I installed the latest Debian 11 (with non-free firmware for the NICs), and my network graph isn't being updated either. Only one of the NICs is plugged in, which in this case is `enp2s0`.

if you are using https proxy，the network graph will be failed.   wss is not supported

**Comment by hrhktkbzyy** [comment]
> 问题已经由jerrykuku排查了。
> 
> 由于我用了第三方的内网穿透服务，给casaos套了https的外网访问地址，而流量显示协议依然使用的ws进行通讯，所以一直连接不上。

你好，我也是搭配了一个内网穿透 frp 使用，网络和硬盘panel都错误。最后您解决这个问题了吗？

**Comment by decadenceqi** [comment]
> > 问题已经由jerrykuku排查了。
> > 由于我用了第三方的内网穿透服务，给casaos套了https的外网访问地址，而流量显示协议依然使用的ws进行通讯，所以一直连接不上。
> 
> 你好，我也是搭配了一个内网穿透 frp 使用，网络和硬盘panel都错误。最后您解决这个问题了吗？

没有，后面就没再使用 casaos 了
