### ISSUE TITLE
Safari 16.1 show the empty page.

### ISSUE THREAD

**Issue by nanshenwei** [IceWhaleTech/CasaOS#647]
**Describe the bug**
Safari 16.1 show the empty page. But everything good with Chrome

**To Reproduce**
1. open to 'safari'
2. enter cassos password

**Expected behavior**
Show the casaos home  page

**Screenshots**
<img width="2276" alt="image" src="https://user-images.githubusercontent.com/40733582/199207975-3c8f1e0d-ac66-4cd5-a08d-d695ea05e9be.png">

**Desktop (please complete the following information):**
 - OS: MacOS 13.0
 - Browser: Safari
 - Version: Safari 16.1 (18614.2.9.1.12)

**Comment by nanshenwei** [comment]
This Bug meet in Casaos v0.3.7 never  seen it before 0.3.7
Casaos v0.3.7 run in Zimaboard

**Comment by zhanghengxin** [comment]
#639
