### ISSUE TITLE
Cant Update AdGuardHome installed from CasaOS Store. [Bug] 

### ISSUE THREAD

**Issue by klisza1993** [IceWhaleTech/CasaOS#651]
When i click "update" its says - "Auto-update failed. Please [follow these steps](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#manual-update) to update manually."
also Cli isnt avaiable:  error" OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown"

**Comment by LinkLeong** [comment]
Are you trying to update the app within the app?

**Comment by klisza1993** [comment]
Yeap. Exacly.

**Comment by klisza1993** [comment]
> Are you trying to update the app within the app?

Yep.

**Comment by LinkLeong** [comment]
The application's update and auto-update features are not yet complete. The update is completed in the in-app play.
