### ISSUE TITLE
0.3.7版本内存占用过大，安装后什么都不做 内存占用300多M还在持续上升 

### ISSUE THREAD

**Issue by zhong1260310** [IceWhaleTech/CasaOS#658]
### Description

0.3.6 版本没这问题   ， 0.3.7 无限增长内存 导致卡死       ，是否能添加  自主选择版本号安装或者降级，最好添加国内镜像源，希望获得解决  谢谢

**Comment by zhong1260310** [comment]
0.3.7  功能上比0.3.6 增加一些 易用性增加了

**Comment by LinkLeong** [comment]
The memory leak problem has been solved in 0.3.7.1, thank you for your feedback.
内存泄露问题已在0.3.7.1解决,感谢你的反馈.

**Comment by zhong1260310** [comment]
> 内存泄漏问题已在 0.3.7.1 中解决，感谢您的反馈。 内存泄露问题已在0.3.7.1解决，感谢你的反馈.

感谢开发组  ，

**Comment by zhong1260310** [comment]
> 

感谢开发组    另外请问是否会考虑加 加国内源，下载安装更方便

**Comment by zhong1260310** [comment]
> 内存泄漏问题已在 0.3.7.1 中解决，感谢您的反馈。内存泄露问题已在0.3.7.1解决，感谢你的反馈.

感谢开发组 ，另外请问是否会考虑加 加国内源，下载安装更方便
