### ISSUE TITLE
[Bug] My CPU is a bit cold

### ISSUE THREAD

**Issue by Lars-** [IceWhaleTech/CasaOS#661]
**Describe the bug**
The temperature indicator in the system status widget reports -263200 degrees Celsius

**To Reproduce**
1. Simply open CasaOS

**Expected behavior**
Report a normal temperature

**Screenshots**
<img width="195" alt="image" src="https://user-images.githubusercontent.com/5690934/199953548-e87b6cef-c1bb-49a9-82a3-d5a823749104.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 107.0.5304.88

**Additional context**
I think I once saw it at a normal temperature, but I don't know why. It runs on an Intel NUC and it's the only application on the system.

**Comment by LinkLeong** [comment]
I'm sorry we don't offer a Win client, how do you run it in Win?

**Comment by Lars-** [comment]
I don't run it on Windows. I open the browser on Windows. I run it on Debian 11.

**Comment by raller1028** [comment]
Can you provide the name and model of your equipment?

**Comment by LinkLeong** [comment]
Can you run "cat /sys/class/thermal/thermal_zone0/temp" and "cat /sys/class/hwmon/hwmon0/temp1_input" and give me the results?

**Comment by Lars-** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/5690934/200324299-d82492d1-33c7-44de-831b-f3750d48f7e9.png">

**Comment by mojothemonkey2** [comment]
submitted a fix for this #677 
my first "go" at golang ;), so please check for weirdness.

basically, the cpu temp is not always in thermal_zone 0.
so we need to find the right zone by the name in "type".
this can have many values, depending on platform. so search by list of strings, like others have done eg:
https://github.com/ThomasKaiser/sbc-bench/blob/master/sbc-bench.sh#L952

**Comment by LinkLeong** [comment]
Thanks for the submission @mojothemonkey2 , I've merged it and will update it in a later release.

**Comment by raller1028** [comment]
@Lars-  This problem has been fixed in v0.3.8, can you upgrade to v0.3.8 to verify if this problem has been fixed?

**Comment by Lars-** [comment]
Done, it works now! Thank you all!
