### ISSUE TITLE
[Bug] Unable to install on a Oracle Cloud Instance

### ISSUE THREAD

**Issue by victorllgarcia** [IceWhaleTech/CasaOS#672]
**Describe the bug**
After the installation I receive the private ip as the installation link and I'm unable to access it either via the public ip or the private ip. Port 80 is open.

**To Reproduce**

1. Go to oracle and create a new instance
2. SSH into it. Update and upgrade it 
3. Install casaOS
4. See the error

**Desktop (please complete the following information):**
 - Browser any

**Logs**

run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
```

*unable to generate any logs 

**Additional context**

**Comment by victorllgarcia** [comment]
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
Nov 10 01:15:16 oracle-1 systemd[1]: Starting CasaOS Gateway...
░░ Subject: A start job for unit casaos-gateway.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit casaos-gateway.service has begun execution.
░░ 
░░ The job identifier is 1930.
Nov 10 01:15:16 oracle-1 casaos-gateway[6816]: v0.3.6
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] PROVIDE        *service.State <= main.main.func4()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] PROVIDE        *service.Management <= github.com/IceWhaleTech/CasaOS-Gateway/service.NewManagementService()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] PROVIDE        *route.ManagementRoute <= github.com/IceWhaleTech/CasaOS-Gateway/route.NewManagementRoute()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] PROVIDE        *route.GatewayRoute <= github.com/IceWhaleTech/CasaOS-Gateway/route.NewGatewayRoute()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] PROVIDE        *route.StaticRoute <= github.com/IceWhaleTech/CasaOS-Gateway/route.NewStaticRoute()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] PROVIDE        fx.Lifecycle <= go.uber.org/fx.New.func1()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] PROVIDE        fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] PROVIDE        fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] INVOKE                main.run()
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.438Z        error        Failed to load routes        {"error": "open /var/run/casaos/routes.json: no such file or directory", "filepath": "/var/run/casaos/routes.json", "func": "service.NewManagementService", "file": "/home/runner/work/CasaOS-Gateway/CasaOS-Gateway/service/management.go", "line": 31}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] HOOK OnStart                main.run.func1() executing (caller: main.run)
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.440Z        info        Management service is listening...        {"address": "127.0.0.1:38969", "filepath": "/var/run/casaos/management.url", "func": "main.run.func1.1", "file": "/home/runner/work/CasaOS-Gateway/CasaOS-Gateway/main.go", "line": 174}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] HOOK OnStart                main.run.func1() called by main.run ran successfully in 1.708923ms
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] HOOK OnStart                main.run.func2() executing (caller: main.run)
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.441Z        info        Checking if port is available...        {"port": "80", "func": "main.run.func2", "file": "/home/runner/work/CasaOS-Gateway/CasaOS-Gateway/main.go", "line": 219}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.446Z        info        New gateway is listening...        {"address": "[::]:80", "func": "main.reloadGateway", "file": "/home/runner/work/CasaOS-Gateway/CasaOS-Gateway/main.go", "line": 326}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] HOOK OnStart                main.run.func2() called by main.run ran successfully in 5.529891ms
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [Fx] HOOK OnStart                main.run.func3() executing (caller: main.run)
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.446Z        info        Static web service is listening...        {"address": "127.0.0.1:35125", "filepath": "/var/run/casaos/static.url", "func": "main.run.func3", "file": "/home/runner/work/CasaOS-Gateway/CasaOS-Gateway/main.go", "line": 279}
Nov 10 01:15:16 oracle-1 systemd[1]: Started CasaOS Gateway.
░░ Subject: A start job for unit casaos-gateway.service has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit casaos-gateway.service has finished successfully.
░░ 
░░ The job identifier is 1930.
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.460Z        info        Notified systemd that gateway is ready        {"func": "main.main.func3", "file": "/home/runner/work/CasaOS-Gateway/CasaOS-Gateway/main.go", "line": 125}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.529Z        info        request:        {"path": "/ping", "param": null, "query": {}, "method": "GET", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 200 |    2.587765ms |       127.0.0.1 | GET      "/ping"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.533Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |    1.029282ms |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.648Z        info        request:        {"path": "/ping", "param": null, "query": {}, "method": "GET", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 200 |      184.12µs |       127.0.0.1 | GET      "/ping"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.695Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |     229.441µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.696Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |     167.841µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.697Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |      153.24µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.698Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |     162.881µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.699Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |      149.84µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.807Z        info        request:        {"path": "/ping", "param": null, "query": {}, "method": "GET", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 200 |      184.44µs |       127.0.0.1 | GET      "/ping"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.915Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |     239.681µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.916Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |     205.121µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.916Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |      177.72µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.917Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |       159.2µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.918Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |      159.24µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.919Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |      172.64µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.919Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |      164.88µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.920Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |      171.88µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.921Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |     284.881µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.922Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |      300.28µs |       127.0.0.1 | POST     "/v1/gateway/routes"
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: 2022-11-10T01:15:16.923Z        info        request:        {"path": "/v1/gateway/routes", "param": null, "query": {}, "method": "POST", "func": "middleware.WriteLog.func1", "file": "/home/runner/go/pkg/mod/github.com/!ice!whale!tech/!casa!o!s-!common@v0.0.0-20220909125858-92fc5b2e0ae5/middleware/gin.go", "line": 56}
Nov 10 01:15:16 oracle-1 casaos-gateway[6820]: [GIN] 2022/11/10 - 01:15:16 | 201 |     279.801µs |       127.0.0.1 | POST     "/v1/gateway/routes"

**Comment by tigerinus** [comment]
@victorllgarcia - In general, cloud environment is not something we support, but if you do `curl localhost:80` on the VM itself, what does it return?

**Comment by tigerinus** [comment]
@victorllgarcia - closing this issue for now. If have any update, please follow up here.
