### ISSUE TITLE
Unable to enter device-id in Sync Guide

### ISSUE THREAD

**Issue by brentgl** [IceWhaleTech/CasaOS#68]
**Describe the bug**
When entering device-id in sync your data section of casaos, the submit button is greyed out and non clickable

**To Reproduce**
goto sync your data
get device  identification from synctrayzor xxxxxx-xxxxxx-xxxxxx-xxxxxx
windows selected then next
after entering device-id click on submit

**Desktop (please complete the following information):**
Raspberry Pi 3B - Casaos v0.2.4

Desktop - Windows 10
Browser - Tried Chrome, Edge & Firefox - same on all

**Comment by kevinmarchese** [comment]
Same Issue as @brentgl

**Comment by LinkLeong** [comment]
We have noticed this problem, you can try to restart the machine to see if it can be solved, we will continue to follow up on this issue in later versions

**Comment by LinkLeong** [comment]
We have fixed this problem, you can try it out.

**Comment by brentgl** [comment]
Updated to v0.2.8

No change here, submit button still greyed out

Should it be fixed in v.0.2.8? or later one?

Thanks
Brent

**Comment by LinkLeong** [comment]
![image](https://user-images.githubusercontent.com/13556972/151528438-a8ccd6d6-3799-43c9-958e-4482a7d26167.png)

Can you click here to resubmit a issue?

**Comment by jerrykuku** [comment]
Thanks for the feedback, we will try to fix this issue.

**Comment by llwaini** [comment]
The bug has been fixed and will be online in the latest versio.

**Comment by LinkLeong** [comment]
We have fixed this issue in [v0.3.2](https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.3.2)
