### ISSUE TITLE
[Alpha][Bug] 未设置WebUI的应用可点击

### ISSUE THREAD

**Issue by Cp0204** [IceWhaleTech/CasaOS#687]
### What happened?

0.3.8未设置WebUI的应用可点击，会重复打开当前页，0.3.7正常点击是没反应的

**Comment by zhanghengxin** [comment]
"0.3.8未设置WebUI的应用可点击"
这个具体步骤是什么？

**Comment by Cp0204** [comment]
> "0.3.8未设置WebUI的应用可点击" 这个具体步骤是什么？

升级到0.3.8a1，应用-设置，Web UI 所有内容清空，保存。
点击应用图标，会链接到当前页面。

预期效果：点击无反应，不能点击，0.3.7是这样的。

**Comment by zhanghengxin** [comment]
好家伙！！收到👌🏻
》》前提：
有一个同学在 0.3.8 提了一个[pr](https://github.com/IceWhaleTech/CasaOS-UI/issues/92) ，当 Nginx 配置路径之后，端口存在也可以点开。

》》在上面基础上修改为：
当打开的页面与当前页面已知时，拒绝打开并提示“The opening page is the same as the current page”
@tigerinus  @ETWang1991 
文案确认一下。

**Comment by zhanghengxin** [comment]
这个问题将在 alpha.6 发版。

**Comment by Cp0204** [comment]
```
if ((item.host != "" || item.port != "" || item.index != "") && item.state == 'running' )
```
这样呢？没有填信息不打开；填了任一信息，则允许打开；

**Comment by Cp0204** [comment]
> ```
> if ((item.host != "" || item.port != "" || item.index != "") && item.state == 'running' )
> ```
> 
> 这样呢？没有填信息不打开；填了任一信息，则允许打开；

这样似乎更优雅。

0.3.7 仅判断端口也有障碍，例如我使用aria2，希望点击打开 http://ariang.mayswind.net/latest，就只能host填ariang.mayswind.net，端口不填打不开，填个80提示重复，只能#0来“修补”。 

建议：
1. host、port、port，都不填，点击无效；
2. host、port、port，填了其一，可点开；
3. 保存设置时不强制验证`Duplicate port:XXX`，改`Duplicate port:XXX, continue?`

**Comment by zhanghengxin** [comment]
> > ```
> > if ((item.host != "" || item.port != "" || item.index != "") && item.state == 'running' )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样呢？没有填信息不打开；填了任一信息，则允许打开；
> 
> 这样似乎更优雅。
> 
> 0.3.7 仅判断端口也有障碍，例如我使用aria2，希望点击打开 http://ariang.mayswind.net/latest ，host填ariang.mayswind.net，端口不填打不开，填个80提示``Duplicate port:80`，只好填个#0来“花式修补”。
> 
> 建议：
> 
> 1. host、port、index，都不填，点击无效；
> 2. host、port、index，填了其一，可点开；
> 3. 保存设置时不强制验证`Duplicate port:XXX`，改`Duplicate port:XXX, continue?`

兄弟，多提提 pr 呀！！

你的这个修改，我考虑过！ 有两个场景是无法这样解决的： 1、当 casaos 原本的页面被修改为其他应用，则默认应用将无法打开。2、当 casaos 被代理，在设置中填写和 casaos 地址相同地址，将会打开同样的页面。

**Comment by zhanghengxin** [comment]
> > ```
> > if ((item.host != "" || item.port != "" || item.index != "") && item.state == 'running' )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样呢？没有填信息不打开；填了任一信息，则允许打开；
> 
> 这样似乎更优雅。
> 
> 0.3.7 仅判断端口也有障碍，例如我使用aria2，希望点击打开 http://ariang.mayswind.net/latest ，host填ariang.mayswind.net，端口不填打不开，填个80提示``Duplicate port:80`，只好填个#0来“花式修补”。
> 
> 建议：
> 
> 1. host、port、index，都不填，点击无效；
> 2. host、port、index，填了其一，可点开；
> 3. 保存设置时不强制验证`Duplicate port:XXX`，改`Duplicate port:XXX, continue?`

第三个问题：我了解了一下，这个需求应该是在流程中的，你可以查一下，或者再提一个。大概率在0.4 版本以后才会修改。

**Comment by Cp0204** [comment]
> > > ```
> > > if ((item.host != "" || item.port != "" || item.index != "") && item.state == 'running' )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这样呢？没有填信息不打开；填了任一信息，则允许打开；
> > 
> > 
> > 这样似乎更优雅。
> > 0.3.7 仅判断端口也有障碍，例如我使用aria2，希望点击打开 http://ariang.mayswind.net/latest ，host填ariang.mayswind.net，端口不填打不开，填个80提示``Duplicate port:80`，只好填个#0来“花式修补”。
> > 建议：
> > 
> > 1. host、port、index，都不填，点击无效；
> > 2. host、port、index，填了其一，可点开；
> > 3. 保存设置时不强制验证`Duplicate port:XXX`，改`Duplicate port:XXX, continue?`
> 
> 兄弟，多提提 pr 呀！！
> 
> 你的这个修改，我考虑过！ 有两个场景是无法这样解决的： 1、当 casaos 原本的页面被修改为其他应用，则默认应用将无法打开。2、当 casaos 被代理，在设置中填写和 casaos 地址相同地址，将会打开同样的页面。

不好意思，我没能理解这两个场景

1. _当 casaos 原本的页面被修改为其他应用_，是指80端口，casaos 改到其他端口？_默认应用_，是指"App Store"和"Files"？

2. _当 casaos 被代理，在设置中填写和 casaos 地址相同地址，将会打开同样的页面。_填写相同的地址当然会打开同样的页面。

能够举一下具体参数的例子吗？一起想想怎么解决。

**Comment by zhanghengxin** [comment]
> 
> 不好意思，我没能理解这两个场景
> 
> 1. **当casaos 原本的页面被修改为其他应用**，是指80端口，casaos 改到其他端口？**默认应用**，是指"App Store"和"Files"？
> 2. **当 casaos 被代理，在设置中填写和 casaos 地址相同地址，将会打开同样的页面。** 填写相同的地址当然会打开同样的页面。
> 
> 能够举一下具体参数的例子吗？一起想想怎么解决。

- 就默认页面不是 casaos-ui，是其他应用，你什么都不填写的情况下，应该是跳转到这个默认页面，而不是留在 casaos 界面。
- 第二个情况，当casaos端口为 81 时，修改端口，跳转位置依然是在 casaos-ui

**Comment by Cp0204** [comment]
> > 不好意思，我没能理解这两个场景
> > 
> > 1. **当casaos 原本的页面被修改为其他应用**，是指80端口，casaos 改到其他端口？**默认应用**，是指"App Store"和"Files"？
> > 2. **当 casaos 被代理，在设置中填写和 casaos 地址相同地址，将会打开同样的页面。** 填写相同的地址当然会打开同样的页面。
> > 
> > 能够举一下具体参数的例子吗？一起想想怎么解决。
> 
> * 就默认页面不是 casaos-ui，是其他应用，你什么都不填写的情况下，应该是跳转到这个默认页面，而不是留在 casaos 界面。
> * 第二个情况，当casaos端口为 81 时，修改端口，跳转位置为 80.

很抱歉，我还是没能明白**默认页面不是 casaos-ui** 的意思。

- 当casaos端口为 81 时，如WebUI修改端口为82，跳转到HOST:82；如留空，跳转到HOST（http默认80，https默认443）是合乎逻辑的。

另外，我刚闪出另一个方案，见：
> https://github.com/IceWhaleTech/CasaOS/issues/702 
> Describe alternatives you've considered

**Comment by zhanghengxin** [comment]
> 很抱歉，我还是没能明白**默认页面不是 casaos-ui** 的意思。
> 
> * 当casaos端口为 81 时，如WebUI修改端口为82，跳转到HOST:82；如留空，跳转到HOST（http默认80，https默认443）是合乎逻辑的。
> 
> 另外，我刚闪出另一个方案，见：
> 
> > #702
> > Describe alternatives you've considered

上面的内容，我重新更新了一下，标注了“需求”，“操作”，以及“结果”。

**Comment by Cp0204** [comment]
> 前提：默认页面（localhost:80）不是 casaos-ui，是其他应用，期望：不填写的情况下，跳转到这个默认页面，而不是留在 casaos 界面。 ===》 但是根据你pr，什么都不写，会不能跳转，需求不能完成。
> 第二个情况，当casaos端口为 81 时，修改其他应用端口为 81 端口，路径为空。 ===》在不考虑后端校验是否通过的情况下，点击挑战满足你的条件，造成重复打开的问题。

明白了，可是我觉得这两个场景都是人为问题啊。
1. 什么都不填，就不应该有跳转期望，点击没反应是符和逻辑的；如果期望打开默认http，可以手动填个80端口。
2. WebUI设置填什么端口就跳转什么端口，casaos已经是81了，应用填个81，当然还是重复打开casaos的81。

我理解的用户期望，就是他所填写的WebUI设置。

**Comment by zhanghengxin** [comment]
启动状态的应用，应该被点击呀。

**Comment by Cp0204** [comment]
> 启动状态的应用，应该被点击呀。

启动状态且有填WebUI参数，应该被点击没错。 但没填WebUI参数的，我认为可以不响应。

不是所有应用都有WebUI，假设什么都不填，都跳转到80，反而逻辑上会造成困惑。

**Comment by zhanghengxin** [comment]
第一个肯定不行：
原因1、如果这样子的话，最好的体验是：需要在 webUI 附近标注注释，解释各种行为，相应的，在保存时也要提醒用户不填写会不能打开页面。

原因2、用户会遇到，默认页面无法打开的，除非，他手动填写 80 端口。我认为让用户过多操作是失败产品的表现。我期望是给用户必要的选项，以帮助更多的用户使用linux。当然，这个也有解决方法，默认设置 80 端口，，，但是问题又来了，也会多很多的操作，每个应用都修改么。。。

so，直接干掉这种可能比较好。


第二个：
另外，目前产品不曾考虑无界面的APP。这是个不错的建议。我觉得有时间应该调研一下，这方面的需求多不多。

**Comment by Cp0204** [comment]
> 

WebUI端口在AppStore安装应用是有预设的。普通用户可以直接点开，没有必要去手动修改，也不会增加使用难度。

按现在的逻辑，没有填WebUI的应用默认都打开80，没有意义，也没有办法正常使用应用。
