### ISSUE TITLE
建议增加国内的升级支持

### ISSUE THREAD

**Issue by cnmyn** [IceWhaleTech/CasaOS#688]
开始使用casaos，用官网的get.casaos.io始终安装不上，差点放弃了，后来在其他网站上看到加cn-顺利安装，但是现在有新版本提示升级，始终升级不了，可能与国内github使用环境有关，希望国内支持一下
体验了casaos，至少在docker管理器方面，还是挺好用的！

**Comment by cnmyn** [comment]
![Screenshot_2022-11-20-09-22-27-798_alook browser](https://user-images.githubusercontent.com/35393836/202878250-e1d3ec26-7c6a-4e06-9362-b21b7be97052.jpg)

**Comment by cnmyn** [comment]
还建议增加自动升级的开关，有时外出很久，不到方便点升级

**Comment by CarlZhang18** [comment]
我在bilibili的CasaOS的官方账号说马上就会有国内的安装脚本了

**Comment by Cp0204** [comment]
> 

0.3.8起，安装脚本已支持国内外源。

**Comment by CarlZhang18** [comment]
> > 我在bilibili的CasaOS的官方账号说马上就会有国内的安装脚本了
> 
> 0.3.8起，安装脚本已支持国内外源。

那现在0.3.7如何update到0.3.8 在国内

**Comment by zhanghengxin** [comment]
curl -fsSL https://cn-get.casaos.io | bash

**Comment by toplinuxsir** [comment]
@zhanghengxin 
手动升级如何进行?

**Comment by cnmyn** [comment]
> @zhanghengxin 手动升级如何进行?

curl -fsSL https://get.casaos.io/update/v0.3.8 | bash
