### ISSUE TITLE
[Bug] No initial password prompt on CasaOS v0.3.8

### ISSUE THREAD

**Issue by Virgus** [IceWhaleTech/CasaOS#691]
Hello, I've been using CasaOS for a while and it's wonderful !

I just started a new install from scratch on a debian 11 OS running on an OrangePi Zero 2. The same SBC that was previously running CasaOS v0.3.3 on Armbian. I had to move to debian because of some problems affecting Armbian that are still unsolved.

The CasaOS setup script downloaded and installed v0.3.8 and everything went fine but there's no initial password settings GUI. I tried already to uninstall CasaOS and run the setup again: the GUI asks for a password despite the initial password was not set.

I don't know how to access the main GUI and I wonder if there is a command line to force a password change and access the interface.
Thanks, kind regards. V.

**Comment by zhanghengxin** [comment]
cloud you describe it in more detail

**Comment by Virgus** [comment]
> I had the same problem, visiting `http://{HOST}/#/welcome` manually worked for me.

Thanks it worked perfectly.
Yesterday, thinking about a cache issue, I tried with several browsers and the page opened was `http://{HOST}/#` but I didn't think to just add "welcome" and continue.

**Comment by Virgus** [comment]
> Could you describe it in more detail

The first url proposed was the login screen even though no user was set.

Despite the small issue, it would be great to know where CasaOS users and passwords are stored.

**Comment by raller1028** [comment]
This issue will be fixed and verified in 0.4.0, if there are still problems, please reopen
