### ISSUE TITLE
[Bug] 安装完成后，未打开初始密码设置页面

### ISSUE THREAD

**Issue by yalunkong** [IceWhaleTech/CasaOS#693]
**Describe the bug**
在oracle上用wget -qO- https://get.casaos.io | bash 安装好casaos之后，登录时打开的页面是http://xxx.xxx.xxx/#/login，并要求输入密码，未出现初始密码设置页面
手动将上述地址更改为http://xxx.xxx.xxx/#/welcome之后，问题解决
新安装的casaos版本应该是0.3.3

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome
 - Version 11.2

**Comment by raller1028** [comment]
这个问题会在下个版本得到修复,你这边方便添加微信guanningchuan,加入我们的微信交流群吗

**Comment by raller1028** [comment]
如果还有问题的话,请重新打开
