### ISSUE TITLE
[Alpha][Bug] CPU usage is not logic

### ISSUE THREAD

**Issue by Ludo-code** [IceWhaleTech/CasaOS#695]
### What happened?

If i set htop and the cpu usage of casaos, the result is different... I have take a screen after a refresh of casaos page.

### Screenshots

![2022-11-22 11_20_27-Paramètres](https://user-images.githubusercontent.com/56892223/203290181-1818801c-c062-41ff-956c-9b4f3fb8464a.png)

**Comment by raller1028** [comment]
CPU% is the occupancy rate of a single core cpu, not the occupancy rate of all cpus. The cpu% of casaos shows the total cpu usage, and there is a certain delay
