### ISSUE TITLE
[Alpha][Bug] can't set password

### ISSUE THREAD

**Issue by Ludo-code** [IceWhaleTech/CasaOS#696]
### What happened?

Hello,

The minimum requirements for password in casaos are 5 caracters, but if you set a password of exactly 5 caracters, he doesn't work with no message from ui.

You can test with a password like 12345

**Comment by raller1028** [comment]
This problem will be fixed in 0.4.0, the minimum password limit for current registration is 6 digits
![image](https://user-images.githubusercontent.com/57336867/203462558-8e24fc37-90ce-4daa-a0f6-b66c3453ef8b.png)
