### ISSUE TITLE
Demo Casaos is not opening 

### ISSUE THREAD

**Issue by 3am-solver** [IceWhaleTech/CasaOS#697]
### Description

http://demo.casaos.io/ url is missing

**Comment by raller1028** [comment]
My side of the test is normal, your side of the error report convenient to tell us?

![image](https://user-images.githubusercontent.com/57336867/203463481-3928aadb-4e9d-43fb-8ab2-825b08f99d20.png)

**Comment by Ludo-code** [comment]
> My side of the test is normal, your side of the error report convenient to tell us?
> 
> ![image](https://user-images.githubusercontent.com/57336867/203463481-3928aadb-4e9d-43fb-8ab2-825b08f99d20.png)
> 

The error have been solved a few times after the issue created. I have checked it and at the moment of the issue have been created demo.casaos.io telling me error 404.

**Comment by tigerinus** [comment]
Demo is public accessible by everyone. It is possible someone changes settings while others are visiting.

Regardless, the demo site is restored per hour. If you are unable to visit it for more than 1hr, please open this issue again.

Thanks!

**Comment by fdfytr** [comment]
<img width="663" alt="Screenshot 2023-01-06 at 13 04 46" src="https://user-images.githubusercontent.com/61352041/211018068-f434b308-6ca1-493d-8d30-3d89104a646e.png">

http://demo.casaos.io/#/login
