### ISSUE TITLE
Upgrade failed!

### ISSUE THREAD

**Issue by toplinuxsir** [IceWhaleTech/CasaOS#699]
### What happened?

When upgrade from 0.3.7.1 to 0.3.8 from web ui , 
click the upgrade button , and the UI always frozen there(see picture below) ?

Can upgrade manully ? any doc ?
thanks!

### Screenshots

![截图 2022-11-23 10-26-03](https://user-images.githubusercontent.com/1111353/203458243-e1562732-fa62-4401-85e1-a17d079e9f11.png)

**Comment by raller1028** [comment]
Upgrade cmd: curl -fsSL https://get.casaos.io/update | sudo bash

**Comment by raller1028** [comment]
You can enter the casaos WeChat exchange group by adding WeChat guanningchuan

**Comment by toplinuxsir** [comment]
@ral

> Upgrade cmd: curl -fsSL https://get.casaos.io/update | sudo bash

Thanks, It works!
