### ISSUE TITLE
[Issue] Attached SSD is getting new name after power OFF and ON

### ISSUE THREAD

**Issue by pmvamsi-coder** [IceWhaleTech/CasaOS#700]
### Description

Storage attached to the Zimaboard is getting a new storage name after every power on and off situation. Containers that are linked using this SSD are getting failed.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.3.8
	 - Disk Total: 27712 
	 - Disk Used: 13202 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
	 - Remote Version: 0.3.8
	 - Browser: Safari 
	 - Version: 16.1

**Comment by pmvamsi-coder** [comment]
External storage added from the CasaOS web UI is not permanent.. whenever the device is restarted the same SSD is getting added with the same name with  **-1**, at last every time

**Comment by pmvamsi-coder** [comment]
Edited **/etc/fstab** file manually but the option from CasaOS UI is not working.

**Comment by pmvamsi-coder** [comment]
![image](https://user-images.githubusercontent.com/61499149/203896706-c8bcfe15-e985-49a2-9643-f31de5de14c3.png)
its creating a new folder everytime whenever its switched ON.

**Comment by raller1028** [comment]
This problem has been fixed in v0.4.0, if there is still a problem, please reopen

**Comment by pmvamsi-coder** [comment]
I am currently using v0.4.0 but the problem still exists.
