### ISSUE TITLE
Show recommended apps toggle button missing in v 0.3.8

### ISSUE THREAD

**Issue by Virgus** [IceWhaleTech/CasaOS#703]
Dear all,
I'm just setting up a new CasaOS v0.3.8 instance and found that the option to show/hide recommended apps has been removed.
It was really useful, specially when accessing the GUI from a mobile phone. I'd love to have this feature back as it is on v0.3.7.1
Thanks for this great tool !

**Comment by zhanghengxin** [comment]
are you sure？

We have never done this requirement

**Comment by zhanghengxin** [comment]
ok ，i will recover

**Comment by zhanghengxin** [comment]
it will be resolved in version 0.4.0

**Comment by AuthorShin** [comment]
0.4.0? really? Why so late when it was already implemented in the previous versions?

**Comment by zhanghengxin** [comment]
Because Recommended Apps is going to be more and more important. We think the hidden features should be removed. But if you need it, he will appear in 0.4.0

**Comment by AuthorShin** [comment]
@zhanghengxin Can you elaborate more please?

**Comment by Virgus** [comment]
> it will be resolved in version 0.4.0

Thanks, maybe the option could be modified to be hidden only on mobile phones ? Or maybe just positioned at the bottom of the screen ? I like to hide recommended apps so that I can see the GUI info on my smartphone without having to scroll down.

**Comment by zhanghengxin** [comment]
This part has a big change in the next version, it will be redefined, you can look forward to it!

**Comment by zhanghengxin** [comment]
[AuthorShin](https://github.com/AuthorShin) @AuthorShin 
[Virgus](https://github.com/Virgus) @Virgus 

recommended apps will be cut
And, A new feature will be added.
But the new function cannot be switched off.
If you still have a need for this, you can submit an issue after you have experienced it.
