### ISSUE TITLE
[Issue] CPU temp didn't show

### ISSUE THREAD

**Issue by Nightels** [IceWhaleTech/CasaOS#705]
### Description

In the previous version it worked fine, but after I updated, it isn't.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.3.8
	 - Disk Total: 222793 
	 - Disk Used: 17614 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:5536M Core:2 Linux wyse 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux]
	 - Remote Version: 0.3.8
	 - Browser: Chrome 
	 - Version: 108.0.0.0

**Comment by mojothemonkey2** [comment]
this will be the same as #694
my fault - while fixing #661 with support for specific cpu thermal_zones, it removes the default zone0.
I'll incorporate this too. PR coming soon.

**Comment by mojothemonkey2** [comment]
PR https://github.com/IceWhaleTech/CasaOS/pull/708

**Comment by LinkLeong** [comment]
> PR #708

merged,will be released in the next version
