### ISSUE TITLE
[Bug] CasaOS not installing correclty 

### ISSUE THREAD

**Issue by gjchester** [IceWhaleTech/CasaOS#709]
**Describe the bug**

CasaOS is not correctly installing in an Ubuntu 20.10.21 LTS install VM hosted on is on Proxmox 7.3.3

Initially reported by RickyTech#8197 in Discord - https://discord.com/channels/884667213326463016/1019493411146956850/1045020076681744454

Ricky was using VMware and did not report the Ubuntu server OS version

Error seen is 

main: Line 507: pushd /tmp/casaos-installer/tmp.WGpJ4m6kdo: Permission Denied

**To Reproduce**
1. Create fresh machine from Ubuntu image
2. Ru the CasaOS once click installer  - curl -fsSL https://get.casaos.io | bash
3. Error seen before install complete

I do not think CasaOS is in a running state there are no processes called casaos running 

**Expected behavior**
CasaOS should instlal without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/6544336/203929667-fb8bdc5c-e709-4144-bdc5-4a60ac57a571.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu LTS 20.10.21

**Logs**

No logs created as CasaOS is not installing, there no obvious failure in systemctl

**Additional context**
Upgrading thest VM to Ubuntu 22.04 and retryign

**Comment by gjchester** [comment]
Did an inplace upgrade to latest Ubuntu LTS (20.04.1 LTS).   Same error.  Will wipe the VM and try an frsh 22.04.1 as a start point

![image](https://user-images.githubusercontent.com/6544336/203942433-381d2af1-9baa-4d5a-bf8e-c0b5d5b6915d.png)

![image](https://user-images.githubusercontent.com/6544336/203942569-39b22fa0-181d-4be0-aac5-8e33c6d05e98.png)

**Comment by gjchester** [comment]
Same issue seen on "pure"  Debian 
![image](https://user-images.githubusercontent.com/6544336/204025064-b9625105-d6b2-4130-a210-0c6bdc936005.png)

![image](https://user-images.githubusercontent.com/6544336/204025138-dcff120c-cb43-42bb-9190-a501b1933438.png)


All installs have been a straight out of the iso install, other than an `apt-get update && apt-get update ` after build to get them up to date.

**Comment by mojothemonkey2** [comment]
What if you try `curl..  | sudo bash` ? (sudo after pipe, instead of at start)

**Comment by gjchester** [comment]
Perfect, why didnt I think of that   :)   Needs reflecting back to the instructions page...
