### ISSUE TITLE
Server not listening on IPv4

### ISSUE THREAD

**Issue by hussainalhaddad** [IceWhaleTech/CasaOS#71]
Hi

I just installed CasaOS, and it seems like it's only listening to port 80 on IPv6.

Is there a way to force it to run on IPv4 only?

Thanks

![image](https://user-images.githubusercontent.com/55337126/150090369-a5b8709b-ab9b-4ff7-8c8a-c66031074bef.png)

**Comment by LinkLeong** [comment]
It's a display issue, you can test it using `nc -zv 127.0.0.1 80`

![image](https://user-images.githubusercontent.com/13556972/150112615-9c5f8f5b-3210-4c60-87e6-b7ea465e4aa4.png)
