### ISSUE TITLE
[Feedback] INFO Installing CasaOS....卡了很久

### ISSUE THREAD

**Issue by xianxin21** [IceWhaleTech/CasaOS#710]
### Description

通过网页升级0.3.8，在INFO Installing CasaOS....卡了很久。
通过ssh升级0.3.8，在/usr/bin/casaos-gateway  卡了很久。

### Additional Information

![111](https://user-images.githubusercontent.com/75621417/203996258-c6775369-1a21-4b78-87cd-b096122c14b8.jpg)
![222jpg](https://user-images.githubusercontent.com/75621417/203996293-faf23b07-823c-4260-9fc4-6d6ca10a56fa.jpg)

**Comment by tigerinus** [comment]
@xianxin21 重新刷新再更新能成功不？

有问题可以添加微信 guanningchuan  受邀入群跟进。
