### ISSUE TITLE
[Bug] CasaOS text blocks buttons

### ISSUE THREAD

**Issue by StarrFox** [IceWhaleTech/CasaOS#711]
**Describe the bug**
The casaOS text blocks the shared button in the file browser partially; you can still click it in the spots not covered by the text though

**To Reproduce**
1. open file browser

**Expected behavior**
the text is under the file browser

**Screenshots**
![image](https://user-images.githubusercontent.com/43019162/204000784-bc3c0726-fee6-4127-908e-93eee2db47aa.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Arch linux
 - Browser [e.g. chrome, safari]: firefox
 - Version [e.g. 22]:  v0.3.8

**Comment by AuthorShin** [comment]
Yeah I can reproduce this, also the icons on the left down corner are overlapping as well.

**Comment by jerrykuku** [comment]
Thanks for the feedback, We will fix this isssue asap.

**Comment by StarrFox** [comment]
based on the above commit I think https://github.com/zhanghengxin/CasaOS-UI/blob/316234edd2882fabe609dfbccbe28366bd885ca9/src/components/ContactBar.vue#L110 might also need to be 30

**Comment by raller1028** [comment]
Your suggestion has been fixed in v0.4.0, if there have any problem, please reopen the problem
