### ISSUE TITLE
Support for custom runtime, like nvidia-runtime for HWA video encoding

### ISSUE THREAD

**Issue by marsweed** [IceWhaleTech/CasaOS#712]
CasaOS doesn't allow apps to access GPU probably bcz it doesn't support custom runtime. but when you install the same docker app outside of casaos, it works fine.

I was having problem with Unmanic not working and giving error when using NVENC for encoding. but i guess the feature might also help with HWA in apps just as Jellyfin and Plex

**Comment by marsweed** [comment]
while am not sound enough in this stuff and if i can understand what you are asking, docker app use two types on commands to have access to GPU (came to know of second one recently) and CasaOS support none of them. i am linking the two methods used by two different apps in the pictures below. please neglect if am not doing it right and let me know how can i assist more

[Unmanic](https://imgur.com/a/Hwub1Nq) uses "--runtime=nvidia"
[jellyfin](https://imgur.com/a/8hNTi6i) uses "--gpus all"

i am yet to find apps that use jellfin's method but i have seen few which use "--runtime=nvidia" when they need to use GPU

**Comment by tigerinus** [comment]
We are actively moving current app management to Docker Compose based, to leverage the full parameters of compose format.

Technically you should be able to specify GPU related parameters by then.

e.g. https://www.howtogeek.com/devops/how-to-run-docker-compose-containers-with-gpu-access/

**Comment by tigerinus** [comment]
official source: https://docs.docker.com/compose/gpu-support/

**Comment by pbzh** [comment]
Indeed, HWA with nvidia gpu works. I've two plex and one emby docker running without an issue, running ubuntu server 22.04, GTX 1050 TI as a VM on a ESX 8 host. Just follow [this](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) guide and just ad "“default-runtime”: “nvidia” to  your docker daemon.json file:

`{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
    "default-runtime": "nvidia"
}`

Hope this helps :-)

btw all other containers shouldn't be affected by the nvdidia runtime!

**Comment by tigerinus** [comment]
> official source: https://docs.docker.com/compose/gpu-support/

this capability is indirectly provided by switching CasaOS Apps over to docker compose files in v0.4.4

check the doc above.

**Comment by bigverm23** [comment]
> > official source: https://docs.docker.com/compose/gpu-support/
> 
> this capability is indirectly provided by switching CasaOS Apps over to docker compose files in v0.4.4
> 
> check the doc above.

how do I switch an app over to docker compose?

**Comment by geman220** [comment]
> fIndeed, HWA with nvidia gpu works. I've two plex and one emby docker running without an issue, running ubuntu server 22.04, GTX 1050 TI as a VM on a ESX 8 host. Just follow [this](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) guide and just ad "“default-runtime”: “nvidia” to your docker daemon.json file, example [here](https://medium.com/@jgleeee/building-docker-images-that-require-nvidia-runtime-environment-1a23035a3a58)
> 
> Hope this helps :-)
> 
> btw all other containers shouldn't be affected by the nvdidia runtime!
> 
> edit: and don't forget to add following env vars:
> 
> * NVIDIA_VISIBLE_DEVICES=all
> * NVIDIA_DRIVER_CAPABILITIES=all

I believe I’ve followed your instructions but hw transcoding isn’t working for me. 

The two relevant errors from Plex are 

 [ffmpeg] - cannot load libcuda.so.1
[ffmpeg] - could not dynamically load cuda
