### ISSUE TITLE
[Feedback]casaos appstore customized installation (other location) bug 

### ISSUE THREAD

**Issue by mightymacs** [IceWhaleTech/CasaOS#713]
### Description

Given zimaborad only have 32GB storage, I customized the installation for pihole into /mnt/Storage1 in my external ssd driver.

After the installation, I couldn't open the app from casos web UI browser directly, but I could access it through the port from the web browser. then I realized it is a bug 
![image](https://user-images.githubusercontent.com/26417515/204083932-ad6d08be-24cf-4dea-b303-f68e004a576b.png)
![image](https://user-images.githubusercontent.com/26417515/204083938-b6b3b56f-d637-4ff6-872a-4d78a8ad5415.png)

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.3.8
	 - Disk Total: 27712 
	 - Disk Used: 13151 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux]
	 - Remote Version: 0.3.8
	 - Browser: Edge 
	 - Version: 107.0.1418.56

**Comment by raller1028** [comment]
@mightymacs  Can you show your pihole setting?

**Comment by mightymacs** [comment]
![微信截图_20221129141143](https://user-images.githubusercontent.com/26417515/204526054-3defc6b4-cccb-452b-8caf-8e490143d6ed.png)
![微信截图_20221129141221](https://user-images.githubusercontent.com/26417515/204526060-0a2cd370-e386-43b7-9299-8ab3c4df1274.png)

**Comment by raller1028** [comment]
You can try as follow


![Image](https://user-images.githubusercontent.com/57336867/204769442-a981055d-8ba1-438b-ada1-39e5ee5fd941.png)

**Comment by raller1028** [comment]
If you still have problems, please reopen
