### ISSUE TITLE
[Feedback][Feature Request] Startpage as a search engine option

### ISSUE THREAD

**Issue by Ploonet** [IceWhaleTech/CasaOS#723]
### Description

As a user
I would like to select StartPage as a default search engine
So that I can use the search bar with my preferred search engine

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.3.8
	 - Disk Total: 59790 
	 - Disk Used: 9882 
	 - System Info: [Raspbian GNU/Linux 11   \l Bit:32 Mem:7898M Core:4 Linux raspberrypi 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux]
	 - Remote Version: 0.3.8
	 - Browser: Firefox 
	 - Version: 107.0

**Comment by ETWang1991** [comment]
![Image](https://user-images.githubusercontent.com/109786132/204414340-fa6994d7-7875-46c5-97b7-9e94224e48a6.png)

Do you mean you can add a custom search engine here?

**Comment by Ploonet** [comment]
A custom one, or just directly startpage.com as an option. :)

But yes I mean here

**Comment by AuthorShin** [comment]
I requested the same thing here https://github.com/IceWhaleTech/CasaOS/issues/133 long ago but no body cared :( So I add it manually to `/casaOS/server/conf/conf.ini` in the previous versions which is now is accessible at `/etc/casaos/casaos.conf`.

**Comment by ETWang1991** [comment]
We'll add startpage.com in a recent update
