### ISSUE TITLE
HDD Sleep state

### ISSUE THREAD

**Issue by Dvalin21** [IceWhaleTech/CasaOS#730]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would it be possible to allow CasaOS to have HDD going into sleep state when system is idle?

**Comment by ggantn** [comment]
+1

**Comment by LinkLeong** [comment]
We tested "hdparm", but it didn't work as expected. Do you have any solution?

**Comment by LinkLeong** [comment]
We will close this issue, please reopen it if you have any questions.
