### ISSUE TITLE
[Feature Request] Folder Binding funtion.

### ISSUE THREAD

**Issue by Dvalin21** [IceWhaleTech/CasaOS#731]
**Is your feature request related to a problem? Please describe.**
Some apps/containers will only look in the root folder on the drive that the OS is installed on.
I'm unable to map via docker compose to a different HDD that is installed. Also while trying to accomplish this
the naming scream changed on the other HDD. (Example: I installed Jellyfin. I was able to map to separate storage from app. Same thing with Frigate (not in the app store). When I would try to map to the other storage it would just create a folder with the storage name in the root folder of the OS installed hdd.)

**Describe the solution you'd like**
Add feature to bind folders from OS HDD to the secondary HDD that is installed. 
Also to bind from OS HDD to smb://. I know that smb:// is able to be access by CasaOS, but yet not the containers.

**Comment by tigerinus** [comment]
@Dvalin21 

I can see more than one feedbacks here. Can you please clarify each? It'd be great to provide few screenshots to help better understanding the issue.

**Comment by tigerinus** [comment]
Closing the issue for now. @Dvalin21 - once you are able to clarify the questions, please re-open.

P.S. it'd be great if you can open a new issue per question, so we can track.
