### ISSUE TITLE
[Feedback]挂载阿里云盘fuse

### ISSUE THREAD

**Issue by zhainan678** [IceWhaleTech/CasaOS#733]
### Description

这是挂载的阿里云盘fuse
/mnt/aliyundrive:/Media \
挂载阿里云盘fuse 后 jellyfin/jellyfin在媒体库不显示
docker run -d --name jellyfin
 	-v /DATA/AppData/Jellyfin/config:/config \
 	-v /DATA/AppData/jellyfin/cache:/cache \
	-v /mnt/aliyundrive:/Media \
	-p 8096:8096 \
	-p 8920:8920 \
	--user 1000:1000 \
	--device /dev/dri/card0:/dev/dri/card0 \
	--device /dev/dri/renderD128:/dev/dri/renderD128 \
	--restart unless-stopped \
	jellyfin/jellyfin

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.3.8
	 - Disk Total: 199538 
	 - Disk Used: 8727 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:M Core:2 Linux debian11 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux]
	 - Remote Version: 0.3.8
	 - Browser: Chrome 
	 - Version: 108.0.0.0

**Comment by LinkLeong** [comment]
经测试未发现问题
`# 新建文件夹 aliyunfuse 和 子目录
mkdir -p /volume2/docker/aliyunfuse/media

# 进入目录
cd /volume2/docker/aliyunfuse

# 一键启动
docker run -d \
   --name aliyundrive-fuse \
   --restart unless-stopped \
   --privileged \
   --device /dev/fuse:/dev/fuse \
   --restart unless-stopped \
   -v $(pwd)/media:/mnt/aliyundrive:shared \
   -e TZ=Asia/Shanghai \
   -e REFRESH_TOKEN=<你的 refresh token> \
   messense/aliyundrive-fuse
`

`
# 再新建两个子目录
mkdir -p {cache,config}

# 硬件支持硬解的一键启动
docker run -d \
   --name jellyfin \
   -v $(pwd)/config:/config \
   -v $(pwd)/cache:/cache \
   -v $(pwd)/media:/media \
   -p 8096:8096 \
   --device=/dev/dri/renderD128 \
   --device /dev/dri/card0:/dev/dri/card0 \
   --restart unless-stopped \
   jellyfin/jellyfin`

--device 可选

**Comment by LinkLeong** [comment]
We will close this issue, please reopen it if you have any questions.
