### ISSUE TITLE
[Feedback][问题] 显示异常

### ISSUE THREAD

**Issue by hexWars** [IceWhaleTech/CasaOS#736]
### Description

安装报错(在一个关闭了的issue中我反馈了)，不得已使用原生的Docker安装项目

安装了一个项目之后casaOS面板出现了我安装的项目

但是在我安装第二个docker项目之后，原来安装的项目就消失了，很异常

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.3.8
	 - Disk Total: 478562 
	 - Disk Used: 11921 
	 - System Info: [Ubuntu 22.04.1 LTS   \l Bit:64 Mem:3816M Core:4 Linux ubuntu 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.3.8
	 - Browser: Firefox 
	 - Version: 107.0

**Comment by hexWars** [comment]
我大概知道问题了，系统版本不对，以及系统好像自动装了docker导致两个docker混用了

**Comment by raller1028** [comment]
如果没有问题的话,我们会关闭该问题,如果还有问题请重新打开.
