### ISSUE TITLE
Support fedora

### ISSUE THREAD

**Issue by git-Hmmm** [IceWhaleTech/CasaOS#740]
**Is your feature request related to a problem? Please describe.**
Yes I want to install casaos on fedora

**Describe the solution you'd like**
Please test and support fedora too.

**Describe alternatives you've considered**
Currently I use cockpit which is good enough for me, I wanted to test your app center, I've seen on YouTube videos it has one-click install feature so I wanted to try it out with my podman installation.

**Additional context**
Currently this is what I get when I run automated script
```
   _____                 ____   _____ 
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___  
 | |    / _` / __|/ _` | |  | |\___ \ 
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/ 
                                      
   --- Made by IceWhale with YOU ---

[  OK  ] Your hardware architecture is : x86_64
[  OK  ] Your System is : Linux
[FAILED] Your Linux Distribution is : fedora We have not tested it on this system and it may fail to install.
```

**Comment by tigerinus** [comment]
@git-Hmmm - as much as I'd love to add support of Fedora, we are currently swamped by other items in the TODO list. 

Will probably address this in the next iteration.

**Comment by jerrykuku** [comment]
The previous installation script forced off the possibility to continue the installation, now this option is reopened so that you can continue to try the installation, but since we have not done exhaustive testing, feel free to give us feedback on the installation results.

**Comment by Lord-Vlad** [comment]
I tried installing on Fedora Server 39 and after installing all dependencies and adjusting the installer script, I get stuck on the setup script. I get an error on "01-setup-gateway.sh" line 18 and 20: "pushd: fedora/: file or directory not found".
