### ISSUE TITLE
[Bug] Storage name with extra -1 after rebooting

### ISSUE THREAD

**Issue by klisza1993** [IceWhaleTech/CasaOS#743]
**Describe the bug**
After setup external storage(SATA) CasaOS changing name of mounted storage after next boot/reboot, which also changing mounting point for docker configurations(volumes) so lets say i have named new storage as "whatever" then after reboot new name is "Whatever-1" and "-1" is added everytime i'll reboot device, you can see this in logs.

**To Reproduce**
1 ADD new storage 
2. name it as you want
3. format it
4. REBOOT machine

**Screenshots**
![image](https://user-images.githubusercontent.com/76993967/206293357-5203d368-99fb-4bff-89bd-266caac3ff1f.png)

**Logs**

run following command to collect corresponding logs:

Dec 07 21:42:35 debian casaos-local-storage[629]: v0.3.8
Dec 07 21:42:35 debian casaos-local-storage[644]: 2022-12-07T21:42:35.522+0100        info        Checking serial disk mount...        {"func": "service.(*diskService).CheckSerialDiskMount", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/disk.go", "line": 476}
Dec 07 21:42:35 debian casaos-local-storage[644]: 2022-12-07T21:42:35.529+0100        info        previously persisted mount point        {"volume": {"id":1,"uuid":"671b55cc-0740-43c6-99e4-ca2464b45242","mount_point":"/mnt/doker-1-1","created_at":1670445400}, "func": "service.(*diskService).CheckSerialDiskMount", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/disk.go", "line": 492}
Dec 07 21:42:35 debian casaos-local-storage[644]: 2022-12-07T21:42:35.529+0100        info        previously persisted mount point        {"volume": {"id":2,"uuid":"81d64585-702d-4542-abef-8b5be8334ee9","mount_point":"/mnt/obrazy","created_at":1670445461}, "func": "service.(*diskService).CheckSerialDiskMount", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/disk.go", "line": 492}
Dec 07 21:42:35 debian casaos-local-storage[644]: 2022-12-07T21:42:35.550+0100        info        trying to re-mount...        {"path": "/dev/sda1", "mount point": "/mnt/obrazy", "func": "service.(*diskService).CheckSerialDiskMount", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/disk.go", "line": 512}
Dec 07 21:42:35 debian casaos-local-storage[644]: 2022-12-07T21:42:35.551+0100        info        mount point already exists, using new mount point        {"path": "/dev/sda1", "mount point": "/mnt/obrazy-1", "func": "service.(*diskService).CheckSerialDiskMount", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/disk.go", "line": 525}
Dec 07 21:42:35 debian casaos-local-storage[644]: 2022-12-07T21:42:35.551+0100        info        trying to mount...        {"path": "/dev/sda1", "mountPoint": "/mnt/obrazy-1", "func": "service.(*diskService).MountDisk", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/disk.go", "line": 343}
Dec 07 21:42:35 debian casaos-local-storage[644]: /bin/bash -c source /usr/share/casaos/shell/local-storage-helper.sh ;do_mount /dev/sda1 /mnt/obrazy-1
Dec 07 21:42:35 debian casaos-local-storage[644]: Mount point: /mnt/obrazy-1
Dec 07 21:42:35 debian casaos-local-storage[644]: /usr/sbin/partprobe -s /dev/sda1
Dec 07 21:42:35 debian casaos-local-storage[644]: /dev/sda1: loop partitions 1
Dec 07 21:42:35 debian casaos-local-storage[644]: /usr/bin/lsblk --pairs --bytes --output-all /dev/sda1
Dec 07 21:42:35 debian casaos-local-storage[644]: NAME="sda1" KNAME="sda1" PATH="/dev/sda1" MAJ:MIN="8:1" FSAVAIL="232376520704" FSSIZE="235152474112" FSTYPE="ext4" FSUSED="358604800" FSUSE%="0%" FSVER="1.0" MOUNTPOINT="/mnt/obrazy-1" LABEL="" UUID="81d64585-702d-4542-abef-8b5be8334ee9" PTUUID="28dadd68-136d-4467-9fb3-72cca45c529a" PTTYPE="gpt" PARTTYPE="0fc63daf-8483-4772-8e79-3d69d8477de4" PARTTYPENAME="Linux filesystem" PARTLABEL="primary" PARTUUID="26ef599a-fdff-4a92-b8cd-20cd4931ba1a" PARTFLAGS="" RA="128" RO="0" RM="0" HOTPLUG="0" MODEL="" SERIAL="" SIZE="240057375232" STATE="" OWNER="root" GROUP="disk" MODE="brw-rw----" ALIGNMENT="0" MIN-IO="512" OPT-IO="0" PHY-SEC="512" LOG-SEC="512" ROTA="0" SCHED="mq-deadline" RQ-SIZE="64" TYPE="part" DISC-ALN="0" DISC-GRAN="512" DISC-MAX="2147450880" DISC-ZERO="0" WSAME="0" WWN="0x50026b778248e63e" RAND="0" PKNAME="sda" HCTL="" TRAN="" SUBSYSTEMS="block:scsi:pci" REV="" VENDOR="" ZONED="none" DAX="0"
Dec 07 21:42:35 debian casaos-local-storage[644]: /usr/bin/partx --pairs --bytes --output-all /dev/sda1
Dec 07 21:42:35 debian casaos-local-storage[644]: NR="1" START="34" END="468862094" SECTORS="468862061" SIZE="240057375232" NAME="primary" UUID="26ef599a-fdff-4a92-b8cd-20cd4931ba1a" TYPE="0fc63daf-8483-4772-8e79-3d69d8477de4" FLAGS="0x0" SCHEME="gpt"
Dec 07 21:42:35 debian casaos-local-storage[644]: 2022-12-07T21:42:35.869+0100        info        1 volume(s) with mount point updated in db by UUID        {"uuid": "81d64585-702d-4542-abef-8b5be8334ee9", "mount point": "/mnt/obrazy-1", "func": "service.(*diskService).UpdateMountPointInDB", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/disk.go", "line": 405}
Dec 07 21:42:35 debian casaos-local-storage[644]: /usr/sbin/smartctl -a /dev/sda -j
Dec 07 21:42:36 debian casaos-local-storage[644]: 2022-12-07T21:42:36.019+0100        info        Notified systemd that local storage service is ready        {"func": "main.main", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/main.go", "line": 243}
Dec 07 21:42:36 debian casaos-local-storage[644]: 2022-12-07T21:42:36.019+0100        info        LocalStorage service is listening...        {"address": "127.0.0.1:41247", "func": "main.main", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/main.go", "line": 248}
Dec 07 21:42:36 debian systemd[1]: Started CasaOS Local Storage Service.

**Comment by ChainRythm** [comment]
Same here. Manually re-mounting to correct path fixes issue until next reboot.

**Comment by Dvalin21** [comment]
Yeah I had the same thing going on

**Comment by zaosoula** [comment]
@Dvalin21 The issue have been fixed in the [v0.4.0](https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.4.0) release

**Comment by raller1028** [comment]
If you still have problems, please reopen
