### ISSUE TITLE
[Feedback]Access the terminal 

### ISSUE THREAD

**Issue by dgtl** [IceWhaleTech/CasaOS#747]
### Description

How do it reset my password to use the terminal window?

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.3.8
	 - Disk Total: 27712 
	 - Disk Used: 10933 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
	 - Remote Version: 0.3.8
	 - Browser: Chrome 
	 - Version: 108.0.0.0

**Comment by jerrykuku** [comment]
Terminal windows use your linux system user and password, not CasaOS's.

**Comment by jerrykuku** [comment]
Since it has been too long without a reply, I will close this issue, if you still have questions, you can reopen it.
