### ISSUE TITLE
什么时候出硬盘挂载功能?谢谢

### ISSUE THREAD

**Issue by jiayouzl** [IceWhaleTech/CasaOS#75]
什么时候出硬盘挂载功能?谢谢

**Comment by LinkLeong** [comment]
磁盘挂载今天会更新,紧接着会更新文件管理.感谢反馈!

**Comment by jiayouzl** [comment]
> 磁盘挂载今天会更新,紧接着会更新文件管理.感谢反馈!

牛逼plus!你们这个完善了Nas都能淘汰了哈哈哈哈.其实绝大部分人用Nas就用了些基础功能,你们这个也支持docker扩展性也没的说.
