### ISSUE TITLE
[Bug] /mnt/Storge repeat create  when reboot

### ISSUE THREAD

**Issue by lwj1994** [IceWhaleTech/CasaOS#753]
**Describe the bug**
![image](https://user-images.githubusercontent.com/10978048/207095793-787c6fee-0087-4e36-b356-988a3e348124.png)
I Add a ssd named "WD20" , and when i reboot, it will create WD20-1 Again.

```bash
➜  /mnt ls
WD20  WD20-1
```

**Comment by LinkLeong** [comment]
This issue has been fixed in 0.4.0 and will be released later.

**Comment by lwj1994** [comment]
It appears again at v0.4.1

**Comment by lwj1994** [comment]
@LinkLeong

**Comment by AmadeusGraves** [comment]
It's resolved in v0.4.2
