### ISSUE TITLE
[Bug] Missing app in App Store

### ISSUE THREAD

**Issue by kinott** [IceWhaleTech/CasaOS#755]
Hi.
App n8n is added to CasaOS App Store, but I don't see it in apps list.
That can be important. 

**To Reproduce**
1. Go to App Store (I see 40 apps in list, including 1 community app)
2. Try to find n8n
3. I don't see it, do you?

**Expected behavior**
The app should be added to App Store a couple of months ago, as declared [here](https://github.com/IceWhaleTech/CasaOS/issues/443#issuecomment-1248999594)

**Desktop**
 - OS: linux
 - CasaOS Version: 0.4.0
 - Disk Total: 15014 
 - Disk Used: 9327 
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1949M Core:2 Linux kinott-test 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux]
 - Remote Version: 0.4.0
 - Browser: Safari 
 - Version: 16.1

**Logs**
:"error","ts":1669951630.0230503,"msg":"CPUThermalZone not found. CPU Temp will not be displayed.","func":"service.GetCPUThermalZone","file":"/home/runner/work/CasaOS/CasaOS/service/system.go","line":332}
run following command to collect corresponding logs:

Thank you

**Comment by LinkLeong** [comment]
Thank you for your feedback, the problem has been fixed, if you have questions, you can reopen the problem.
