### ISSUE TITLE
[Feedback][Issue] Transmission won't install

### ISSUE THREAD

**Issue by bhodisattva** [IceWhaleTech/CasaOS#760]
### Description

Yellow warning bubble pops up, explaining: 'protocol must be tcp, udp or both'.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 230569 
	 - Disk Used: 24535 
	 - System Info: [Ubuntu 22.04.1 LTS   \l Bit:64 Mem:3784M Core:4 Linux tahiti 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.0
	 - Browser: Chrome 
	 - Version: 108.0.0.0

**Comment by tigerinus** [comment]
fixed via https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/25
