### ISSUE TITLE
[Feedback]APP拖动、APP图标、网络状况

### ISSUE THREAD

**Issue by ws245909346** [IceWhaleTech/CasaOS#761]
### Description

1.在手机端，APP拖动调整位置功能，容易导致页面无法上下滑动；
2.大陆网络环境，APP商店所有图标、简介图片和主页个别APP图标显示不正常，可开放功能用户上传图标；
3.主页左侧网络状况功能在远程登录时失效。

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 15269 
	 - Disk Used: 9332 
	 - System Info: [Ubuntu 22.04.1 LTS   \l Bit:64 Mem:5898M Core:2 Linux ubuntu-server 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.0
	 - Browser: Edge 
	 - Version: 108.0.1462.54

**Comment by zhanghengxin** [comment]
1、我在本地测试了一下，认为你是打开了 PC 浏览模式，因为在手机端，目前不支持调整位置功能，只有在手机端打开 PC 浏览模式，但这样会导致无法上下滑动。


2、第二个功能可能会在后续版本修复。


3、这个已经在 0.4.1完成修复。近期会上新。

**Comment by ws245909346** [comment]
感谢回复，确实是手机端用的电脑模式。希望CasaOS越来越好

在 2022-12-19 10:31:47，"不需要知道我来自何方--myStar" ***@***.***> 写道：


1、我在本地测试了一下，认为你是打开了 PC 浏览模式，因为在手机端，目前不支持调整位置功能，只有在手机端打开 PC 浏览模式，但这样会导致无法上下滑动。

2、第二个功能可能会在后续版本修复。

3、这个已经在 0.4.1完成修复。近期会上新。
