### ISSUE TITLE
[Bug] The external disk cannot be mounted correctly.

### ISSUE THREAD

**Issue by Top20000316** [IceWhaleTech/CasaOS#762]
When an external disk is connected to the device via USB, it can not be mounted correctly.
The page shows that a new device has been connected, but the storage space cannot be created in the storage space manager. The prompt "Please connect a disk to create a storage space" is displayed.

The disk appears to be recognized as a removable storage device, which is mounted on /media/devmon.
And it can not be shared in Lan in the app File.

(My device has no SATA interface, so I can only connect the disk through USB. TAT...)

 - OS: linux
 - CasaOS Version: 0.4.0
 - Disk Total: 7042 
 - Disk Used: 1702 
 - System Info: [Armbian 23.02.0-trunk Bullseye \l Bit:32 Mem:990M Core:4 Linux onecloud 6.1.0-meson #trunk SMP Tue Dec 13 20:11:12 UTC 2022 armv7l GNU/Linux]
 - Remote Version: 0.4.0
 - Browser: Chrome 
 - Version: 102.0.0.0

**Comment by raller1028** [comment]
Storage Manager currently only displays SATA devices. Do you want to share external disks?

**Comment by Top20000316** [comment]
> Storage Manager currently only displays SATA devices. Do you want to share external disks?

Thanks for your reply.

Yep! I'm sorry that there's no SATA interface on my device...
I have tried editing the flie /etc/samba/smb.conf to share the external disk. But it didn't work. And as I said, I can't share my disk in app File. In other words, it cannot be mapped in my computer.

Could you tell me a solution? 
Thanks again!

**Comment by Top20000316** [comment]
Additionally, the u-disk can't be read in docker containers, too. (Maybe it's the same issue. THX.)

**Comment by LinkLeong** [comment]
The u-disk permission problem, there is no plan to fix it, we will consider it in the next big version, thanks again for your feedback.
