### ISSUE TITLE
[Bug] Error in connecting to the smb network storage

### ISSUE THREAD

**Issue by heqfeeling** [IceWhaleTech/CasaOS#763]
### What happened?

Unable to create smb network storage

### Screenshots

![image](https://user-images.githubusercontent.com/18085264/208280038-a4ac2819-f7d7-437a-a925-486d1c3f5584.png)

**Comment by LinkLeong** [comment]
How are you sharing on the server side, do you have a configuration for server side sharing? You can add WeChat 'guanningchuan' we solve problems faster

**Comment by heqfeeling** [comment]
> How are you sharing on the server side, do you have a configuration for server side sharing? You can add WeChat 'guanningchuan' we solve problems faster

使用的是smb1.0的协议，window可以访问，通过mount命令挂载到目录下也可以访问

**Comment by LinkLeong** [comment]
Currently casaos does not support 1.0 protocol, we will adjust according to the feedback, thank you for your feedback, if there are still problems, you can reopen the issue.
