### ISSUE TITLE
[Bug] Error will be reported when entering the container terminal

### ISSUE THREAD

**Issue by heqfeeling** [IceWhaleTech/CasaOS#764]
![image](https://user-images.githubusercontent.com/18085264/208280208-dc2fddc2-4f3d-424e-a26c-bd87a366d926.png)

Hopes to provide bin/bash and bin/sh shells

**Comment by ETWang1991** [comment]
Roger, will provide options later

**Comment by tigerinus** [comment]
dup https://github.com/IceWhaleTech/CasaOS/issues/653
