### ISSUE TITLE
Live demo page incorrect password

### ISSUE THREAD

**Issue by rewanthtammana** [IceWhaleTech/CasaOS#765]
**Describe the bug**
I tried accessing the live demo page & it says password error.

**To Reproduce**
1. Go to http://demo.casaos.io/#/login
2. Username `casaos`, password `casaos`
3. It says incorrect password

**Expected behavior**
![image](https://user-images.githubusercontent.com/22347290/208358491-e4f8effd-e2b4-4b6a-a62a-92271aad4f09.png)

I followed these instructions & expected it to work but it isn't working.

**Screenshots**
![image](https://user-images.githubusercontent.com/22347290/208358388-2bb1cb9c-a252-461f-a3cc-d6c5ea2271cc.png)

**Comment by zhanghengxin** [comment]
This is the browser setting, and it means that the link is not secure enough

**Comment by rewanthtammana** [comment]
But there's no relation b/w secure link and incorrect password. It's working now, not really sure why.
