### ISSUE TITLE
[Bug] Issue script install

### ISSUE THREAD

**Issue by Nzxxxt** [IceWhaleTech/CasaOS#769]
Hello all, 

I am currently having a problem installing CasaOS on my raspberry. 
I followed the installation instructions by doing the following command:

`curl -fsSL https://get.casaos.io | sudo bash`

But nothing happens, no action starts even with or without sudo or with wget or curl : 

<img width="631" alt="Capture d’écran 2022-12-20 à 01 42 00" src="https://user-images.githubusercontent.com/67876146/208556088-86ebb327-9ca3-464b-b084-e0d87ce8d8f9.png">

I have checked the required packages and I have: bash, mv, rm, tr, grep, sed, curl/wget, tar, smartmontools, parted, ntfs-3g, net-tools

Do you have any solutions ? 

Thanks by advance

**Comment by Top20000316** [comment]
I met this problem too. It worked well when I tried it again.

**Comment by asdjgfr** [comment]
same issue

**Comment by Nzxxxt** [comment]
@jerrykuku I just tried again and still the same problem, do you have additional info if the server is functional?

**Comment by jerrykuku** [comment]
@Nzxxxt  Hi, you can try this `curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/v0.3.8-jerry/v0.4.0_install.sh | sudo bash` , if still have problem please let me know.

**Comment by stisko** [comment]
> @Nzxxxt Hi, you can try this `curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/v0.3.8-jerry/v0.4.0_install.sh | sudo bash` , if still have problem please let me know.

No, The same thing happens again. Only the CasaOs logo is appeared.

**Comment by jerrykuku** [comment]
> > @Nzxxxt Hi, you can try this `curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/v0.3.8-jerry/v0.4.0_install.sh | sudo bash` , if still have problem please let me know.
> 
> No, The same thing happens again. Only the CasaOs logo is appeared.

What's the distro of your Linux system?

**Comment by stisko** [comment]
> > > @Nzxxxt Hi, you can try this `curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/v0.3.8-jerry/v0.4.0_install.sh | sudo bash` , if still have problem please let me know.
> > 
> > 
> > No, The same thing happens again. Only the CasaOs logo is appeared.
> 
> What's the distro of your Linux system?

Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by jerrykuku** [comment]
> > > > @Nzxxxt Hi, you can try this `curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/v0.3.8-jerry/v0.4.0_install.sh | sudo bash` , if still have problem please let me know.
> > > 
> > > 
> > > No, The same thing happens again. Only the CasaOs logo is appeared.
> > 
> > 
> > What's the distro of your Linux system?
> 
> Distributor ID: Debian Description: Debian GNU/Linux 11 (bullseye) Release: 11 Codename: bullseye

It's weird, I've been using Debian bullseye for installation testing. Please give me some more time to run some tests.

**Comment by jerrykuku** [comment]
> > > > @Nzxxxt Hi, you can try this `curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/v0.3.8-jerry/v0.4.0_install.sh | sudo bash` , if still have problem please let me know.
> > > 
> > > 
> > > No, The same thing happens again. Only the CasaOs logo is appeared.
> > 
> > 
> > What's the distro of your Linux system?
> 
> Distributor ID: Debian Description: Debian GNU/Linux 11 (bullseye) Release: 11 Codename: bullseye

Can you test `curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/v0.3.8-jerry/v0.4.0_install.sh | sudo bash` again? I fixed a potentially problematic method.

**Comment by stisko** [comment]
@jerrykuku, Unfortunately, no change. :-(

**Comment by jerrykuku** [comment]
> @jerrykuku, Unfortunately, no change. :-(

Hi, I fixed the problem, can you try again?

**Comment by Nzxxxt** [comment]
It work for me ! Thanks for your actions @jerrykuku ✌️

**Comment by ILYAdragan** [comment]
огромная спасибо  помогло
