### ISSUE TITLE
[Bug] Attached SSD will get a new name after power OFF and ON

### ISSUE THREAD

**Issue by pmvamsi-coder** [IceWhaleTech/CasaOS#770]
**Describe the bug**
The storage attached to the Zimaboard gets a new storage name after each power on and off condition. Containers linked using this SSD are failing. External storage added from CasaOS web UI is not permanent.. the same SSD with the same name is added with -1 at last to the folder name every time the device restarts. Edited /etc/fstab file manually but the option from CasaOS UI is not working. 
The issue was already mentioned at https://github.com/IceWhaleTech/CasaOS/issues/700, but it was closed without being resolved.
**To Reproduce**
The problem repeats whenever the power is turned on and off.
**Expected behavior**
It should not create a new folder with some number suffix at the end for an already attached SSD whenever the power is turned on and off.

**Screenshots**
![](https://user-images.githubusercontent.com/61499149/203896706-c8bcfe15-e985-49a2-9643-f31de5de14c3.png)

**Desktop (please complete the following information):**
 - OS: linux
 - CasaOS Version: 0.3.8
 - Disk Total: 27712 
 - Disk Used: 13202 
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
 - Remote Version: 0.3.8
 - Browser: Safari 
 - Version: 16.1

**Comment by raller1028** [comment]
Sorry, we tried to reproduce this issue in v0.4.0 but it didn't happen, can you confirm if this issue still exists in v0.4.0? And you can try again with this command 'curl -fsSL https://get.casaos.io/update | sudo bash' to confirmif the issue is fixed?

**Comment by CosmoFox** [comment]
> Sorry, we tried to reproduce this issue in v0.4.0 but it didn't happen, can you confirm if this issue still exists in v0.4.0? And you can try again with this command 'curl -fsSL https://get.casaos.io/update | sudo bash' to confirmif the issue is fixed?

Confirming. 0.4.0. Problem is here.

**Comment by pmvamsi-coder** [comment]
> Sorry, we tried to reproduce this issue in v0.4.0 but it didn't happen, can you confirm if this issue still exists in v0.4.0? And you can try again with this command 'curl -fsSL https://get.casaos.io/update | sudo bash' to confirmif the issue is fixed?

Even after the update .. issue is there.

**Comment by LinkLeong** [comment]
You can try unplugging the hard drive and deleting all the wrong folders and try again. If the problem persists, please provide feedback on the hardware and disk information and access type

**Comment by pmvamsi-coder** [comment]
I have tried unplugging and re plug the hard disk several times but the same issue is there. Also I have shared the device info in the previous comments. 
It's Zimaboard top model.

**Comment by CosmoFox** [comment]
> I have tried unplugging and re plug the hard disk several times but the same issue is there. Also I have shared the device info in the previous comments. It's Zimaboard top model.

same situation. Unmounted, then unplugged m2 disk. Then back. Reboot. Problem is there.

**Comment by CosmoFox** [comment]
> @pmvamsi-coder @CosmoFox Sorry, I didn't reproduce this issue in v0.4.0/v0.4.1, but we found that <my-ssd-name> will become <my-ssd-name-1> after version update, but this will only happen when we upgrade, ssd name will not be added after shutdown/reboot, can you try to upgrade to v0.4.1 and then reboot/shutdown 3 times to check  if this problem still exist?

At the moment I already have a clean installation of 0.4.1. The problem is no gone. 

And also after the update from 0.4.0 to 0.4.1 the problem also disappeared.

**Comment by raller1028** [comment]
In version 0.4.1 you reproduced the problem by directly powering off reboot or using reboot command by terminal?

**Comment by CosmoFox** [comment]
> At the moment I already have a clean installation of 0.4.1. The problem is no gone.

Sorry, mistake. The problem is ~~no~~ gone. Everything ok!!

**Comment by pmvamsi-coder** [comment]
issue still there 
![image](https://user-images.githubusercontent.com/61499149/216314865-f8f7c2b0-6da5-4d23-822b-4f09b4f43fc1.png)

**Comment by pmvamsi-coder** [comment]
> issue still there
> ![image](https://user-images.githubusercontent.com/61499149/216314865-f8f7c2b0-6da5-4d23-822b-4f09b4f43fc1.png)

![image](https://user-images.githubusercontent.com/61499149/216315287-f0dd547d-533d-4454-8f56-0ae91e0b2f93.png)

**Comment by raller1028** [comment]
@pmvamsi-coder Can you share your operation to reproduce the problem in detail？@ @ thanks

**Comment by pmvamsi-coder** [comment]
> @pmvamsi-coder Can you share your operation to reproduce the problem in detail？@ @ thanks

Whenever the board is switched off and turned on, folders are automatically generated

**Comment by LinkLeong** [comment]
The problem of directory accumulation due to upgrade has been solved in 0.4.2

**Comment by LinkLeong** [comment]
I checked the logic and only when the folder to be mounted is not empty, a new directory is created. So according to your description, the folder to be mounted is not empty after reboot, and we did not check the possibility that it is not empty. Have you configured the automount manually?

**Comment by pmvamsi-coder** [comment]
> I checked the logic and only when the folder to be mounted is not empty, a new directory is created. So according to your description, the folder to be mounted is not empty after reboot, and we did not check the possibility that it is not empty. Have you configured the automount manually?

Yes. Why because if I didn't configure it manually every time the drive is getting connected with new name with numbers as suffix. Applications that are using this path will not work if this is the case.

**Comment by raller1028** [comment]
@pmvamsi-coder v0.4.2 has been released, can you try to verify whether the problem still exists?

**Comment by pmvamsi-coder** [comment]
The issue was resolved after the software update. I would like to express my gratitude for your prompt attention and efforts in addressing the issue.

**Comment by pmvamsi-coder** [comment]
after the updated

**Comment by andresslacson1989** [comment]
this happens to me as well I am on v0.4.15, everytime it reboots it changes to random string. I have to remount everytime. I have a 2Tb samsung shield t7 mounted via usb, I have my AppData files inside it so it's a hassle whenever it reboots to remount the disk again.

**Comment by stevedee78** [comment]
I have the same problem. It's annoying to have to adjust the Docker paths after every reboot.

**Comment by Demasterpl** [comment]
I can confirm that this continues to happen. Using 0.4.15 with Samsun MZ-V7S00B/AM 500GB SSD. If the power is pulled on the device OR if I tell the device to reboot this problem persists. Very annoying.
