### ISSUE TITLE
[Bug] strconv.Atoi: parsing "": invalid syntax

### ISSUE THREAD

**Issue by Lixar91** [IceWhaleTech/CasaOS#774]
## Describe the bug
When I try to use a docker container without specifying any particular port in the URL, the program doesn't allow me to save the app settings.

## To Reproduce
1. Go to the settings of any app.
2. Delete the port under Web UI or go to an app which wasn't assigned a port under the Web UI section before the 0.4.0 update.
3. Click on Save
4. See error: `strconv.Atoi: parsing "": invalid syntax`

## Expected behavior
Be able to save the app settings (it worked in previous versions)

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/59791946/209075626-dfa0bc48-b001-4845-b701-fa6c0191cecb.PNG)

## Server information:
 - OS: `Debian 11 x64`
 - CasaOS Version:  `v0.4.0 `

**Comment by zaosoula** [comment]
Hello, the fix for this bug will be shipped on the next release 
https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/18
