### ISSUE TITLE
[Feedback]无法挂载磁盘

### ISSUE THREAD

**Issue by Han-GK** [IceWhaleTech/CasaOS#775]
### Description

/dev/sda1       146G   61M  139G   1% /media/devmon/sda1-ata-WDC_WD1600BEVT-2
磁盘已被自动挂载，但在web页面不显示有磁盘接入

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 6136 
	 - Disk Used: 2737 
	 - System Info: [Armbian 20.07 Bionic \l Bit:64 Mem:1771M Core:4 Linux arm-64 5.8.0-arm-64 #20.07 SMP PREEMPT Mon Aug 3 15:48:29 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux]
	 - Remote Version: 0.4.0
	 - Browser: Edge 
	 - Version: 108.0.1462.54

**Comment by raller1028** [comment]
![Image](https://user-images.githubusercontent.com/57336867/211449392-5ecfba45-61ff-4f5f-b453-15091a986d55.png)



![Image](https://user-images.githubusercontent.com/57336867/211449545-18f617e2-755e-43cd-879d-b33cad1f6cf5.png)

1.你是通过usb转sata线接入ssd吗请问你这边是这两个地方都没有显示磁盘接入吗

**Comment by Han-GK** [comment]
更换系统版本后已解决该问题
