### ISSUE TITLE
App-install Progress Bar

### ISSUE THREAD

**Issue by mojothemonkey2** [IceWhaleTech/CasaOS#779]
Working example of app install progress bar.

- separate the status log messages from the progress updates.
- progress bar showing total % for install.
  this consists of sum of download "current" progress, plus sum of extract "currrent" progress, out of the sum of "total" progress (times 2). (eg if all layers downloaded, but nothing extracted, we'll be at 50%).

note: the progress bar will be seen to "jump backwards" at times. this is when a new layer begins to download, and we need to add it's size to the total.

PR to follow.

**Comment by mojothemonkey2** [comment]
PR https://github.com/IceWhaleTech/CasaOS-UI/pull/100

**Comment by mojothemonkey2** [comment]
Demo:
[Screen recording 2022-12-24 6.03.23 PM.webm](https://user-images.githubusercontent.com/117033380/209446986-c083b33d-2272-47c5-af20-aff6eaf2cb3b.webm)

**Comment by AuthorShin** [comment]
Thanks for the PR, honestly this is a feature I've been looking forward to.
I think we should add an estimated / expected time or download speed or maybe some sort of indication so that if it seems to be stuck, the user can see if it's just processing or something crashed.

**Comment by jerrykuku** [comment]
Currently the app installation has a relatively accurate progress display and we have made some improvements based on your PR, thanks for the PR, this issue has not been updated for a long time and the functionality has been completed, for better maintenanceissues I will close it, if there are still problems you can reopen it and give us feedback.
