### ISSUE TITLE
[Bug] Cannot edit apps

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#786]
When on V0.4.0 I try to edit an app I get `strconv.Atoi: parsing "": invalid syntax`.

**Comment by tigerinus** [comment]
@AuthorShin - do you mean saving in the Settings dialog?

**Comment by AuthorShin** [comment]
> @AuthorShin - do you mean saving in the Settings dialog?

@tigerinus 
Yes, I open an already installed app and change some settings and when I try to save it but it show me this error.

**Comment by tigerinus** [comment]
This should be fixed by https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/18

**Comment by tigerinus** [comment]
dup https://github.com/IceWhaleTech/CasaOS/issues/774

**Comment by jerrykuku** [comment]
@AuthorShin Hi, has this issue been fixed? We look forward to your reply.

**Comment by AuthorShin** [comment]
@jerrykuku Hey Jerry, sorry for the late reply. Yes, as of 0.4.4 it was fixed and that's the last version I used.
