### ISSUE TITLE
[Feature] Set default net metric

### ISSUE THREAD

**Issue by CosmoFox** [IceWhaleTech/CasaOS#788]
I have a few net ifaces, and wanna see one of them every time, when reloading Casa panel.
Now it`s resetting to wired connection, against selected wireless.

![image](https://user-images.githubusercontent.com/9054349/209552388-9db321e3-83f7-4d0c-93df-6e8852fc82f6.png)

**Comment by zhanghengxin** [comment]
It will show in 0.4.1-alpha

**Comment by CosmoFox** [comment]
Yes it`s work on 0.4.1 update. Tnx you!
