### ISSUE TITLE
[Bug] v0.3.8更新至v0.4.0失败

### ISSUE THREAD

**Issue by QueenLoli** [IceWhaleTech/CasaOS#789]
**Describe the bug**
更新时从github下载失败.

**Expected behavior**
使用wget -qO- https://get.casaos.io/update | bash更新，停留在：
Dowloading https://github.com/IceWhaleTech/CasaOS-AppManagement/releases/download/v0.4.0-alpha7/linux-amd64-casaos-app-management-migration-tool-v0.4.0-alpha7.tar.gz
无法下载导致不能更新

**Comment by raller1028** [comment]
你好,我这边用wget -qO- https://get.casaos.io/update | bash更新是可以正常升级,你那边能排查下是否是网络问题吗?有问题可以添加微信 guanningchuan 受邀入群跟进

**Comment by jerrykuku** [comment]
由于目前更新脚本中的 migration-tool 依然是从github中进行下载，部分国内网络用户由于无法正常访问github从而导致下载失败。
我们会在近期进行修复，以保证所有用户都能顺畅的下载到更新。
