### ISSUE TITLE
硬盘挂载在/DATA下

### ISSUE THREAD

**Issue by cs0663c** [IceWhaleTech/CasaOS#79]
![image](https://user-images.githubusercontent.com/59052041/150975238-eefe831f-6d9c-4684-b885-6b1ea8d6f11f.png)

**Comment by LinkLeong** [comment]
硬盘是挂在了/DATA目录下,这里不再显示挂载的磁盘,而是合并在一起显示了.你现在有什么问题?

**Comment by LinkLeong** [comment]
![FireShot Capture 006 - CasaOS - 192 168 20 244](https://user-images.githubusercontent.com/13556972/150991394-19554178-da47-408a-8ff6-6b19a01cda17.png)

**Comment by cs0663c** [comment]
> 硬盘是挂在了/DATA目录下,这里不再显示挂载的磁盘,而是合并在一起显示了.你现在有什么问题?

没哟合并显示，另一个盘250G，我认为他该显示出来。话哟浏览器时常显示不出已装的app 得重新加载，这个是edge问题吗？

![image](https://user-images.githubusercontent.com/59052041/151179847-5ac19b7b-b5d3-41a2-bb04-fab10e78db09.png)

**Comment by LinkLeong** [comment]
你可以发一个json文件给我吗,`lsblk -O -J`
app显示不出来的问题:你安装了多少应用呢?

**Comment by LinkLeong** [comment]
还有需要什么帮助吗?

**Comment by JohnGuan** [comment]
No further information is available.
