### ISSUE TITLE
[Feedback] Web UI has too much reliance on public services.

### ISSUE THREAD

**Issue by SpiralBrad** [IceWhaleTech/CasaOS#794]
### Description

- Web UI login pulls swiper.min.js from cdn.jsdeliver.net.  ...Why?  Bundle it locally.
- Icons for custom apps attempt to pull from https://icon.casaos.io/main/all/ 
- Who knows what else

I understand certain things require this, such as the built-in app store...  But basic things like the above should avoid pulling resources from the public web. 

Please keep this software quiet and not pinging a bunch of public servers needlessly during solely local usage.

**Comment by jerrykuku** [comment]
Well it's a good question.
1. swiper.min.js is referenced by a third-party component, and we will find a way to fix it.
2. About https://icon.casaos.io/main/all/, We maintain a library of icons ourselves and would like to help users automatically populate a portion of their custom application icons.

**Comment by SpiralBrad** [comment]
Re: 2, I'd prefer a one-time icon download at the time of custom-application creation, as opposed to a perpetual hitting of your server / requiring it to still exist.

**Comment by jerrykuku** [comment]
We will consider this issue carefully.

**Comment by jerrykuku** [comment]
We will make a big upgrade to the app store and app installation in the next version, when the app icon resources will be downloaded to local in advance.

**Comment by jerrykuku** [comment]
In version 0.4.4-alpha, the app store data has been localized as much as possible, and the front-end UI has been kept as free of online resources as possible. You can try to update v0.4.4-alpha.
Since this issue has not been updated for too long, I will close it. If there are still any problems you can reopen it.
