### ISSUE TITLE
[Bug] failed to upgrade from 0.3.6 to latest

### ISSUE THREAD

**Issue by tigerinus** [IceWhaleTech/CasaOS#795]
**Describe the bug**

Just get a 0.3.6 CasaOS and try to upgrade to latest from UI.

**Comment by tigerinus** [comment]
Will talk to Arun who reported this issue via email.

**Comment by shanff** [comment]
I had an issue  upgrading from UI.  I ran an apt upgrade via SSH, rebooted, then the UI upgrade worked flawlessly.

**Comment by tigerinus** [comment]
> I had an issue upgrading from UI. I ran an apt upgrade via SSH, rebooted, then the UI upgrade worked flawlessly.

Current update process is problematic. We will re-do the whole update process in near future.
