### ISSUE TITLE
[Bug] Issue : Can't add network storage

### ISSUE THREAD

**Issue by pascals07** [IceWhaleTech/CasaOS#798]
### Description

Can't add network storage to Casa OS, it failed with an error 

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 7963 
	 - Disk Used: 1677 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:2048M Core:2 Linux casaos 5.15.74-1-pve #1 SMP PVE 5.15.74-1 (Mon, 14 Nov 2022 20:17:15 +0100) x86_64 GNU/Linux]
	 - Remote Version: 0.4.0
	 - Browser: Safari 
	 - Version: 16.2

**Comment by LinkLeong** [comment]
Are you trying to mount smb? Do you have a screenshot of the error report added? It's easy for us to troubleshoot the problem.
