### ISSUE TITLE
挂载硬盘

### ISSUE THREAD

**Issue by ai371908858** [IceWhaleTech/CasaOS#80]
您好，请教一下，我是用树莓派4B,安装的，系统时UBUNTU20.04,安装后挂载的硬盘无法显示，应该怎么解决

**Comment by ai371908858** [comment]
![c8c33bfd357d15b1651bf28829fd82be70316b352a789d47ee2fcbf903abeb12QzpcVXNlcnNcSEdTXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1w2MTc2MzQyM192MlxJbWFnZUZpbGVzXEZCRDYxNjA0LTFBQUQtNGUxOC05MzdGLURENzEzMDA5ODlERC4zNjBfdGh1bWI=](https://user-images.githubusercontent.com/33067840/151001817-551ba6f1-19f5-46c2-a582-43438eb890cd.png)
![61f0d17a505574868fe8d956f82847f69c55229db68b1f6f4b16d2019ceee0fcQzpcVXNlcnNcSEdTXEFwcERhdGFcUm9hbWluZ1xEaW5nVGFsa1w2MTc2MzQyM192MlxJbWFnZUZpbGVzXDE2NDMxMjI0NjMyNzBfRTNDRkMxRDUtNTNBQi00Yzc2LTkyRTMtRDg2OTVGOEJCQTQ2LnBuZw==](https://user-images.githubusercontent.com/33067840/151001846-e680365e-f336-49ee-8007-c29fd8f9b578.png)

**Comment by LinkLeong** [comment]
1.目前usb会自动挂载到/DATA目录下,名称是USB_Storage[1-10]
![image](https://user-images.githubusercontent.com/13556972/151096061-aa38aab6-67c0-4052-a666-a9329462a0ed.png)
2.目前usb挂载上后首页存储大小变为改变,这个功能年后会加
3.上面的图显示磁盘/dev/sda没有自动挂载吗?

**Comment by ozdroid** [comment]
> 

可以增加关闭自动挂载的选项吗？我自己本身已经挂载硬盘。然而和你这个自动挂载冲突的

**Comment by LinkLeong** [comment]
你是通过什么方式挂载的,fstab吗?

**Comment by chmdir** [comment]
cm311-1a, armbian + casaos , 插上硬盘就是自动挂载有冲突  ，一会看见一会消失， 请问 casaos的自动挂载 或armbian 的自动挂载 怎么取消

**Comment by tigerinus** [comment]
新的 v0.3.7 做了大量存储方面的改进，等正式发布了你可以试试看这个问题是否还存在。

如果有新的问题，可以微信加 guanningchuang 在群里聊。
