### ISSUE TITLE
[Bug] n8n default configuration persists the wrong folder, causing data loss

### ISSUE THREAD

**Issue by MaddoScientisto** [IceWhaleTech/CasaOS#802]
**Describe the bug**
When installing n8n from the app store the container is created with this path:
host: `/DATA/AppData/n8n/.n8n` container: `.n8n`
This is wrong, it results in losing data, I lost my data multiple times when changing environment variables.
The correct directory to persist is: `/home/node/.n8n`
This is were the data is actually stored.

**To Reproduce**
1. Go to 'App Store'
2. Click on 'n8n'
3. Install it
4. Look at the settings in the mounts section

**Expected behavior**
`/home/node/.n8n` should be in the container path instead of just `.n8n`

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 109.0b7

**Comment by JohnGuan** [comment]
@MaddoScientisto Thank you for your feedback, the problem has been fixed.
- https://github.com/IceWhaleTech/CasaOS-AppStore/commit/1655eb3dff412ec86dfe75fe11634cf510e7b8e9
@LinkLeong Please update the API data

**Comment by JohnGuan** [comment]
@jerrykuku @LinkLeong 
Modified and verified successfully
