### ISSUE TITLE
[Feedback]rclone挂载问题

### ISSUE THREAD

**Issue by shukuan** [IceWhaleTech/CasaOS#810]
### Description

使用rclone挂载WebDAV到/DATA/Media下，使用Files可以看到挂载文件，但是读取时报错。

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 27712 
	 - Disk Used: 6810 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:M Core:4 Linux MINIX 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux]
	 - Remote Version: 0.4.0
	 - Browser: Chrome 
	 - Version: 108.0.0.0

**Comment by raller1028** [comment]
你WebDAV挂载的是不是阿里云盘?我们测试是可以正常读取的,如果不行请检查你的WebDAV服务

**Comment by raller1028** [comment]
如果还有问题,请重新打开

**Comment by SmartYou1995** [comment]
遇到了同样的问题  解决了吗
