### ISSUE TITLE
[Alpha][Bug] Custom app installation can not take a docker-compose file containing more than 1 service.

### ISSUE THREAD

**Issue by mithubindia** [IceWhaleTech/CasaOS#816]
### What happened?

Casa OS is a fantastic platform.  While we were trying to add a custom application ( Wordpress to be precise ) using standard docker-compose  file containing 2 services e.g. wordpress and db.  Some how , Casaos only takes 1 service at a time.  Finally, when we factored the docker-compose file, we could  run the our application ( Wordpress ).  Kindly consider this as a bug.

**Comment by tigerinus** [comment]
as early as v0.4.4 we will be switching CasaOS App model over to Docker Compose, which will come with full features. Stay tuned.

**Comment by tigerinus** [comment]
closing since this is done in v0.4.4
