### ISSUE TITLE
[Feedback]Can't load app store

### ISSUE THREAD

**Issue by Dylan-G** [IceWhaleTech/CasaOS#820]
### Description

Can't load app store

vue.esm.js:629 [Vue warn]: Error in created hook: "TypeError: Cannot read properties of undefined (reading 'total')"

found in

---> <AppPanel> at src/components/Apps/AppPanel.vue

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 28463 
	 - Disk Used: 17155 
	 - System Info: [Ubuntu 22.04.1 LTS   \l Bit:64 Mem:1984M Core:4 Linux orangepi3-lts 5.16.17-sun50iw6 #3.0.4 SMP Tue May 31 11:34:23 CST 2022 aarch64 aarch64 aarch64 GNU/Linux]
	 - Remote Version: 0.4.0
	 - Browser: Chrome 
	 - Version: 109.0.0.0

**Comment by zhanghengxin** [comment]
Which version? An upgrade might do the trick.

**Comment by Dylan-G** [comment]
0.4.0

**Comment by RSerejo** [comment]
There was an error when loading App Store list. Please try again. 

Ubuntu server 20.04

**Comment by zavenvar** [comment]
Have the same issue in just installed version
CasaOS: v0.4.1
Ubuntu: 22.04

**Comment by keiron26** [comment]
same here 
 CasaOS v0.4.1
 Raspberry Pi OS
 Raspberry Pi 2

**Comment by arstum** [comment]
same situation

OS: Arch Linux x86_64
Kernel Release: 6.1.14-1-lts
WM: DWM
(xfs)

**Comment by zhanghengxin** [comment]
> same situation casaos -v v0.4.0 OS: Arch Linux x86_64


Is v0.4.2 still available?
