### ISSUE TITLE
[Bug]  Android phone Cannot access SAMBA

### ISSUE THREAD

**Issue by fei1554973967** [IceWhaleTech/CasaOS#821]
samba pc Can access，Android phone Cannot access

**Comment by zhanghengxin** [comment]
Which version？

**Comment by 1554973967** [comment]
0.4.0  0.4.1

**Comment by tigerinus** [comment]
@fei1554973967 if you setup samba on a different machine, without CasaOS, are you able to access it from your phone?

**Comment by tigerinus** [comment]
if this is still happening, please provide more info about the app you are using.

closing for now.
