### ISSUE TITLE
[Feedback]Unifi-Controller no funciona

### ISSUE THREAD

**Issue by victorarvelogarcia** [IceWhaleTech/CasaOS#822]
### Description

Hola.
La versión de Unifi parece que da problemas.
Podrían actualizarla, por favor.
Gracias...

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 29725 
	 - Disk Used: 10786 
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:3827M Core:4 Linux PuntoLimpio 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux]
	 - Remote Version: 0.4.0
	 - Browser: Chrome 
	 - Version: 108.0.0.0

**Comment by JohnGuan** [comment]
@victorarvelogarcia Do you have a recommended version?

**Comment by JohnGuan** [comment]
I've set the version in the app's profile to the latest.
