### ISSUE TITLE
[Feature Request]希望增加数据目录迁移到挂载磁盘的功能

### ISSUE THREAD

**Issue by cellistV** [IceWhaleTech/CasaOS#826]
希望开发者增加数据目录迁移到挂载磁盘的功能，可以解决设备本身储存空间小的问题。

**Comment by cellistV** [comment]
希望开发者增加数据目录迁移到挂载磁盘的功能，解决设备储存空间小的问题。

**Comment by ETWang1991** [comment]
可以试一下最新版本的“磁盘合并”功能，插入SATA硬盘后，可以合并存储。把设备存储空间与外置空间合并成一个大盘用。

![Image](https://user-images.githubusercontent.com/109786132/215691201-cf075a35-37cb-4838-9544-8f7001d8536b.png)

**Comment by cellistV** [comment]
> 可以试一下最新版本的“磁盘合并”功能，插入SATA硬盘后，可以合并存储。把设备存储空间与外置空间合并成一个大盘用。
> 
> ![Image](https://user-images.githubusercontent.com/109786132/215691201-cf075a35-37cb-4838-9544-8f7001d8536b.png)

感谢回复
是的，已经注意到了此项功能，但用U盘连接的SSD和HHD都不能显示为硬盘，所以没法用这个功能。

**Comment by raller1028** [comment]
@cellistV 最新版casaos v0.4.3-alpha已经发布,新版本增加了usb设备的磁盘合并功能,可以麻烦你帮忙测试一下这个功能是否ok吗?
更新命令: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash

**Comment by cellistV** [comment]
> @cellistV 最新版casaos v0.4.3-alpha已经发布,新版本增加了usb设备的磁盘合并功能,可以麻烦你帮忙测试一下这个功能是否ok吗? 更新命令: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash
---
root@armbian:~# curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash

   _____                 ____   _____ 
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___  
 | |    / _` / __|/ _` | |  | |\___ \ 
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/ 
                                      
   --- Made by IceWhale with YOU ---

- OK Your hardware architecture is : aarch64
tee: /var/log/casaos/upgrade.log: No space left on device
---
![image](https://user-images.githubusercontent.com/86347487/228720388-c3726b93-9bc4-4cc8-890d-56031465d81d.png)
不知为何显示剩余空间不足。

**Comment by raller1028** [comment]
@cellistV 你试试df -h /tmp看看还有多少空间

**Comment by raller1028** [comment]
方便加微信来看看这个问题吗 reelfy2570

**Comment by Pulset** [comment]
> @cellistV 最新版casaos v0.4.3-alpha已经发布,新版本增加了usb设备的磁盘合并功能,可以麻烦你帮忙测试一下这个功能是否ok吗? 更新命令: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash 新 命令 ： curl - fsSLhttps://get.casaos.io/update/v0.4.3-alpha|使用 sudo bash

开启这个功能之后，后面安装的软件优先是安装在内置存储还是外置存储？我的设备本身存储就小，想把整个casaos安装到外置存储，要怎么操作？
