### ISSUE TITLE
Unable to recognize SSD capacity information

### ISSUE THREAD

**Issue by didiniao** [IceWhaleTech/CasaOS#83]
<img width="316" alt="截屏2022-01-26 下午2 53 47" src="https://user-images.githubusercontent.com/5102605/151116746-d079930e-285d-403d-963e-2cf6ae8767a4.png">
**Describe the bug**

Intel P4610 1.6T SSD Unrecognized Information

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.6
	 - Disk Total: 100280 
	 - Disk Used: 12591 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Ubuntu 20.04.3 LTS   \l Bit:64 Mem:64216M Core:16 Linux cloud 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 96.0.4664.110

**Comment by LinkLeong** [comment]
Thanks for your feedback, we have started to investigate this problem, the recent update will include this issue

**Comment by LinkLeong** [comment]
Can you join discord,We need more information.   link:https://discord.com/invite/knqAbbBbeX

**Comment by didiniao** [comment]
When the system is mounted using the volume group method, the capacity information cannot be displayed.
<img width="647" alt="截屏2022-01-26 下午3 23 02" src="https://user-images.githubusercontent.com/5102605/151124411-27be4203-19d5-4e0c-a32f-9a8b6ce089ad.png">

**Comment by onewithforce** [comment]
Hi,

Can confirm the storage display information broke after the upgrade to newer versions.
Initially it was working fine (0.24 if not mistaken). 
Also NFS mounted shared are not displayed as well 

root@Casa:/home/alex# lshw -class disk
  *-disk
       description: SCSI Disk
       product: QEMU HARDDISK
       vendor: QEMU
       physical id: 0.0.0
       bus info: scsi@0:0.0.0
       logical name: /dev/sda
       version: 2.5+

**Comment by onewithforce** [comment]
After update to new version (0.2.8) it works fine (at least for vDisk [Qemu]).

**Comment by LinkLeong** [comment]
I am very sorry, due to the problem of my work error, the relevant tools could not be installed during the upgrade, so the data could not be displayed. I suggest you to reinstall v0.2.8 directly, thank you for your feedback!

**Comment by LinkLeong** [comment]
Thank you for your feedback, are there any questions now?
