### ISSUE TITLE
[Bug]  v0.4.1 "Ghost button" Clone

### ISSUE THREAD

**Issue by CosmoFox** [IceWhaleTech/CasaOS#830]
**Describe the bug**
New istalled app has new cool button "Clone"
![2023-01-19_18-08-14](https://user-images.githubusercontent.com/9054349/213479137-e5328256-5750-4b95-bf11-747159b9263b.png)

When you open settings and then save it - this button "Clone" disappears
![2023-01-19_18-09-12](https://user-images.githubusercontent.com/9054349/213479463-8c0b67c4-497b-4eb9-9931-bee10ff003c1.png)

**To Reproduce**
1. Update to 0.4.1
2. Install app & check new button is here
3. Open app settings & save it
4. button "Clone" disappears

**Comment by jerrykuku** [comment]
Yes, I saw it, and we will fix it in the next release.

**Comment by CosmoFox** [comment]
> Yes, I saw it, and we will fix it in the next release. 

Hope you add the "update container" button too

**Comment by jerrykuku** [comment]
> > Yes, I saw it, and we will fix it in the next release.
> 
> Hope you add the "update container" button too

We are working on this feature, one of the main features of v0.4.2.

**Comment by tigerinus** [comment]
fixed by https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/35
