### ISSUE TITLE
[Bug] 更新4.1版本后在屏幕宽度为481-765px的设备上ui显示错误

### ISSUE THREAD

**Issue by winter2048** [IceWhaleTech/CasaOS#833]
![image](https://user-images.githubusercontent.com/31879147/213841905-9410e8fb-be56-4d35-b82e-e713a4ccb744.png)

**Comment by thedroidkid** [comment]
Seeing this as well on my phone.

**Comment by jerrykuku** [comment]
这个问题将在v0.4.2进行修复。

**Comment by raller1028** [comment]
![Image](https://user-images.githubusercontent.com/57336867/217185856-dce06d89-1d87-4d96-9e9c-680a9cbf7649.png)
