### ISSUE TITLE
[Feedback][Feature Request]

### ISSUE THREAD

**Issue by multiregis** [IceWhaleTech/CasaOS#836]
### Description

Add a symbolic link to USB shared drives in Root/DATA. Great job. Thanks.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 29672 
	 - Disk Used: 7057 
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:924M Core:4 Linux raspberrypi 5.10.17-v7+ #1414 SMP Fri Apr 30 13:18:35 BST 2021 armv7l GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Opera 
	 - Version: 94

**Comment by tigerinus** [comment]
while this is a great feature to be added, the challenge is that symbolic link might not be always accessible by Docker apps.

That said, you should be able to find the quick link to any mounted disk in the file browser:

![image](https://user-images.githubusercontent.com/7172560/215222451-9d99dd2c-ba7e-4754-b3ea-0881a8df8cca.png)

(if you don't see the link to the USB drive, please file a bug!)
