### ISSUE TITLE
A security vulnerability which will lead to controller the system

### ISSUE THREAD

**Issue by stArl23** [IceWhaleTech/CasaOS#84]
**Describe the bug**
Here is a security vulnerability will lead to controller the system.
**Detail**
https://www.star123.top/2022/01/08/A-vulnerability-in-CasaOS/#more and  the password is sent to Guan.Ningchuan@gmail.com.

**Comment by JohnGuan** [comment]
Thank you for your support! Bravo!
We are fixing this issue.
感谢铁子！

**Comment by LinkLeong** [comment]
感谢铁子

**Comment by LinkLeong** [comment]
我们在昨天发布的0.2.7版本修复了该问题,感谢您的反馈.

**Comment by stArl23** [comment]
收到，涉及漏洞的代码已修复，该漏洞已提交cve，如果有官方确认，注意查收，祝CasaOS越来越好。
the code involved in the vulnerability has been fixed, and the vulnerability has been submitted to cve. If there is official confirmation, please pay attention to check it. I wish CasaOS better and better.
