### ISSUE TITLE
[Feedback][Feature Request] Suggestion for Adding Multiple Storage Devices to Demo

### ISSUE THREAD

**Issue by onyxz7** [IceWhaleTech/CasaOS#840]
Hi, I would like to suggest adding storage devices to the demo so that we can see how work the storage manager functions with multiple devices, including options such as RAID, etc...

Thank you!

**Comment by JohnGuan** [comment]
Since our demo is deployed in a cloud server and refreshed regularly. So it may not be convenient to demo, but you can actually install the experience, and virtual machine is also a good choice.
