### ISSUE TITLE
[Bug]Pihole default URL Incorrect

### ISSUE THREAD

**Issue by chadless1** [IceWhaleTech/CasaOS#841]
### Description

Hello,

Just installed pihole docker app. When I click on the app/link to open pihole it takes you to the default apache page. The pihole url should be http://your_ip_address/admin. The container is missing the /admin in the url. Adding /admin to the container under settings in the "Web UI" section solved the link issue and sends you to the pihole login page.

just FYI.

thanks,
Chad

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 31949 
	 - Disk Used: 3633 
	 - System Info: [Ubuntu 20.04.5 LTS   \l Bit:64 Mem:512M Core:1 Linux tester 5.13.19-2-pve #1 SMP PVE 5.13.19-4 (Mon, 29 Nov 2021 12:10:09 +0100) x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Firefox 
	 - Version: 108.0

**Comment by JohnGuan** [comment]
Fixed!
- https://github.com/IceWhaleTech/CasaOS-AppStore/commit/de7c2724d01748db03d1d48e31d5a5d8ff33a16c

@LinkLeong Please update the app store data

**Comment by raller1028** [comment]
Confirmed!
