### ISSUE TITLE
[Bug] samba

### ISSUE THREAD

**Issue by QueenLoli** [IceWhaleTech/CasaOS#843]
**Describe the bug**

**To Reproduce**
连接smb，并使用具有管理权限的账户
然后在casaos自带的文件里推出这个smb链接

**Expected behavior**
smb链接内文件全部被删

**Screenshots**

**Desktop (please complete the following information):**
 - OS: debian lxc
 - Browser [edge]

**Comment by LinkLeong** [comment]
增加了了在删除挂载点之前的判断.

**Comment by QueenLoli** [comment]
这个bug摧毁掉我接近20g的照片和视频……

**Comment by LinkLeong** [comment]
由于我们的不严谨给您造成的严重损失,非常抱歉.我们没有任何解释的权利,我们能做的只能是更好的优化和完善CasaOS.
另外,如有数据恢复需要可加我们微信,我们协助你进行尝试恢复.
