### ISSUE TITLE
[Feature Request] Custom DNS

### ISSUE THREAD

**Issue by MushiTheMoshi** [IceWhaleTech/CasaOS#844]
### What happened?

Awesome work done here, really appreciated, app is very nice and well designed.

Looking for some help to resolve custom dns.

Can't resolve custom dns, would like a way to pass `docker --dns` argument somehow in the WEBUI.

Regards

**Comment by MushiTheMoshi** [comment]
NOTE: I know I can mount a resolv.conf as a volume in /etc/resolv.conf and use it, just looking for a native way to do it from the WEBUI.

**Comment by tigerinus** [comment]
@MushiTheMoshi - is this a bug from a feature which is supposed to work or a feature request?

Can you be more specific on your scenario?

**Comment by MushiTheMoshi** [comment]
Is a feature request, renamed title accordingly.

**Comment by tigerinus** [comment]
Great. Thanks for submitting a feature request!

Can you go thru the expected behavior from a user's perspective?

**Comment by tigerinus** [comment]
Closing for now - once you have more details please leave comments here.
