### ISSUE TITLE
[Bug] 设置环境变量时，无法保存value包含 “=” 的值 

### ISSUE THREAD

**Issue by guwf563** [IceWhaleTech/CasaOS#849]
“=”后面的内容都会消失。
举例，我在配置一段json格式的值，如：{certs="/data/vw.crt",key="/data/vw.key"}，保存后，重新进入页面只能看到 {certs

**Comment by jerrykuku** [comment]
谢谢反馈，已经复现此问题，我们将安排修复此问题。

**Comment by tigerinus** [comment]
fixed by https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/36
