### ISSUE TITLE
[Bug] smartctl invalid parameter

### ISSUE THREAD

**Issue by jeremyit** [IceWhaleTech/CasaOS#850]
CasaOS use SmartmonTools to check HDD health. 
In syslog I have that for each disk, I am on zimaboard : 
I've looked at smartcl man pages, you have to a value after -n

`Jan 29 12:53:40 zima01 casaos-local-storage[703]: /usr/sbin/smartctl -a -n /dev/sda -j
Jan 29 12:53:40 zima01 casaos-local-storage[703]: smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.10.0-21-amd64] (local build)
Jan 29 12:53:40 zima01 casaos-local-storage[703]: Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org
Jan 29 12:53:40 zima01 casaos-local-storage[703]: =======> INVALID ARGUMENT TO -n: /dev/sda
Jan 29 12:53:40 zima01 casaos-local-storage[703]: =======> VALID ARGUMENTS ARE: never, sleep[,STATUS], standby[,STATUS], idle[,STATUS] <=======
Jan 29 12:53:40 zima01 casaos-local-storage[703]: Use smartctl -h to get a usage summary
Jan 29 12:53:40 zima01 casaos-local-storage[703]: 2023-01-29T12:53:40.007+0100#011error#011failed to exec shell - smartctl exec error#011{"func": "service.(*diskService).SmartCTL", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/disk.go", "line": 149}`

**Comment by LinkLeong** [comment]
Thank you for the reminder, this function has been moved to another repository [storage](https://github.com/IceWhaleTech/CasaOS-LocalStorage/blob/915e42218366c4caa69d174762c5621e1411dfea/pkg/utils/ command/command_helper.go), but we will still handle our current code, thanks for the reminder
