### ISSUE TITLE
[Feedback] Spindown HDD

### ISSUE THREAD

**Issue by jeremyit** [IceWhaleTech/CasaOS#853]
### Description

I've worked on standby HDD with zimaboard and Casaos.
HDPARM doesn't  work.
hd-idle work like a charm but ! only if CasaOS services are down. I've did multiple try, I think that is caused by Casaos storage management or smartctl called by Casaos for smart check.

**Comment by jeremyit** [comment]
Finally not Casaos but hd-idle issue

**Comment by ETWang1991** [comment]
We have found the cause of this problem and estimate that it will be solved in version 0.4.3

**Comment by jeremyit** [comment]
I found the root cause is udisks2 
If this service down then spindown works

**Comment by LinkLeong** [comment]
Thank you for your feedback, we also found the problem, but at the moment we can't remove the dependency of udisks2, do you have any better suggestion?

**Comment by LinkLeong** [comment]
We will close the issue and reopen it if you have any questions.
