### ISSUE TITLE
Error when installing CasaOS on Linux Mint[Bug] 

### ISSUE THREAD

**Issue by thedroidkid** [IceWhaleTech/CasaOS#855]
**Describe the bug**
I receive the following error when installing CasaOS on Linux Mint. 

/tmp/casaos-installer/tmp.fcgiAWnw7h/build/scripts/setup/script.d/01-setup-gateway.sh: line 18: pushd: linuxmint/vera: No such file or directory
/tmp/casaos-installer/tmp.fcgiAWnw7h/build/scripts/setup/script.d/01-setup-gateway.sh: line 20: pushd: linuxmint: No such file or directory
/tmp/casaos-installer/tmp.fcgiAWnw7h/build/scripts/setup/script.d/01-setup-gateway.sh: line 22: pushd: ubuntu debian: No such file or directory
[FAILED] Failed to run setup script

**To Reproduce**
Just try installing CasaOS on a clean Mint Linux box.

**Expected behavior**
Since Mint Linux is based on Ubuntu I would expect it to install. I understand it is not fully supported. 

**Desktop (please complete the following information):**
 NAME="Linux Mint"
VERSION="21.1 (Vera)"

**Additional context**

**Comment by cloete2023** [comment]
I have the exact same problem:

NAME="Linux Mint"
VERSION="21.1 (Vera)"

To Reproduce
Just try installing CasaOS on a clean Mint Linux box.

/tmp/casaos-installer/tmp.fcgiAWnw7h/build/scripts/setup/script.d/01-setup-gateway.sh: line 18: pushd: linuxmint/vera: No such file or directory
/tmp/casaos-installer/tmp.fcgiAWnw7h/build/scripts/setup/script.d/01-setup-gateway.sh: line 20: pushd: linuxmint: No such file or directory
/tmp/casaos-installer/tmp.fcgiAWnw7h/build/scripts/setup/script.d/01-setup-gateway.sh: line 22: pushd: ubuntu debian: No such file or directory
**[FAILED] Failed to run setup script**

I have successfully installed it on Linux Lite 6, which is also based on Ubuntu

**Comment by tigerinus** [comment]
fixed by https://github.com/IceWhaleTech/CasaOS-Gateway/pull/31 and similar PRs for other repos.
