### ISSUE TITLE
CentOS7 安装失败

### ISSUE THREAD

**Issue by cat0i** [IceWhaleTech/CasaOS#856]
OK  ] Your hardware architecture is : x86_64
[  OK  ] Your System is : Linux
[FAILED] Your Linux Distribution is : rhel fedora We have not tested it on this system and it may fail to install.

![Snipaste_2023-02-02_11-00-56](https://user-images.githubusercontent.com/41892758/216220809-42dd1250-2817-4803-8ef1-7bce1d6e77c2.png)

**Comment by sydaint** [comment]
我也是这个情况 貌似脚本不支持centos

**Comment by jerrykuku** [comment]
这个问题应该是安装脚本有一点小问题，阻拦了继续安装，现在已经修复，可能的话请重新尝试一次，如果有问题欢迎反馈给我。

**Comment by cat0i** [comment]
> 这个问题应该是安装脚本有一点小问题，阻挠了继续安装，现在已经修复，可能的话请重新尝试一次，如果有问题请来找我。

非常抱歉，我再次尝试发现还是无法安装。在运行脚本后，安装依赖后就不再继续下去了。难道因为云服务器的原因吗？是腾讯云的云服务器。
![image](https://user-images.githubusercontent.com/41892758/217122050-101efa93-aee9-41da-9a24-18505b222983.png)

**Comment by jerrykuku** [comment]
这个可能是包管理器更新或者安装依赖的时候出错了，你可以先尝试手动安装如下依赖
'wget' 'curl' 'smartmontools' 'parted' 'ntfs-3g' 'net-tools' 'udevil' 'samba' 'cifs-utils' 'mergerfs'
以及使用如下命令手动安装docker
`curl -fsSL https://get.docker.com | bash`
最后再次尝试安装CasaOS

**Comment by sydaint** [comment]
![微信图片_20230207203547](https://user-images.githubusercontent.com/15535097/217246664-be1d5971-a4fe-4a88-bdc5-7684ce1b62ff.png)
我这边使用命令安装也是失败了。
提示没有udevil软件包，查了下在ubuntu及Archlinux上应该是可以安装，尝试编译安装到centos没有成功。应该是usb即插即用的包。

**Comment by jerrykuku** [comment]
这个包确实没有 centos 的版本

**Comment by jerrykuku** [comment]
由于目前无法给centos添加上这个依赖，我们也正在积极的调研解决依赖问题的方法，你可以尝试手动下载安装脚本手动修改下，
`readonly CASA_DEPANDS_PACKAGE=('wget' 'curl' 'smartmontools' 'parted' 'ntfs-3g' 'net-tools' 'udevil' 'samba' 'cifs-utils' 'mergerfs' 'apparmor')`
`readonly CASA_DEPANDS_COMMAND=('wget' 'curl' 'smartctl' 'parted' 'ntfs-3g' 'netstat' 'udevil' 'samba' 'mount.cifs' 'mount.mergerfs' 'apparmor_parser')` 删除这两行中的udevil，再进行安装测试。我将关闭这个issue。
