### ISSUE TITLE
[Alpha][Bug]  app is always on running status

### ISSUE THREAD

**Issue by arch3rPro** [IceWhaleTech/CasaOS#858]
### What happened?

I create a app by using the appfiles，but when i start and open it ，the web site display the app is running。

CasaOS version： 0.4.1
appfile：[appfile](https://github.com/arch3rPro/Vuldocker/blob/master/Tools/Acunetix/AppFile/Acunetix.json)

But in the v0.3.6 ，it's OK

### Screenshots

![image](https://user-images.githubusercontent.com/30855883/216872860-95b8a9a9-0757-402b-bfdb-61859e4f4f22.png)

**Comment by lxlarcadelxl** [comment]
I got the same problem. I wanted to try out CasaOS and after installing an app through the appshop (Alltubedownload) or with a compose file (doublecommander).
Syncthing installation worked tho.

![image](https://user-images.githubusercontent.com/23142574/216923898-54bc4bb5-1d6a-4175-93cf-f6fbb280417c.png)

**Comment by jerrykuku** [comment]
This issue will be fixed in the next release.

**Comment by jerrykuku** [comment]
This issue have already fixed in v0.4.2， I will close this issue and if you still have problems you can reopen it.
