### ISSUE TITLE
Add bookmarks for existent apps installed.

### ISSUE THREAD

**Issue by bahachammakhi** [IceWhaleTech/CasaOS#86]
I just installed and tried casaOS its just amazing, great work !. 

I want to search for how to add existent apps on the dashboard like putting the app name, logo, and link ( port ) to access it.

there is anyway. I can do that?

**Comment by jerrykuku** [comment]
We are not currently developing this feature, but it is under discussion.

**Comment by JohnGuan** [comment]
This requirement is being discussed at https://github.com/IceWhaleTech/CasaOS/discussions/177
