### ISSUE TITLE
[Bug] Got "Error response from daemon" when install an app

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#866]
Hello
I got the following error when install an app and try to turn it on because when I install an app it's icon is gray and when I try to open it I got the following error:
```
Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `apparmor_parser apparmor_parser --version` failed with output: error: exec: "apparmor_parser": executable file not found in $PATH
```

**Comment by dnmnhat** [comment]
I fixed this error by :
sudo apt-get install apparmor

**Comment by AuthorShin** [comment]
> 

It worked, thank you so so much.

**Comment by tigerinus** [comment]
The root issue is tracked by https://github.com/moby/moby/issues/44970

For now we will update the setup script temporarily adding this dependency.

**Comment by tigerinus** [comment]
https://github.com/containerd/containerd/releases/tag/v1.6.18 contains the fix of this issue.

The new package has just been released to all Linux distros.

**Comment by AuthorShin** [comment]
@tigerinus Hello
I just installed Debian 11 on VPS and install CasaOS on it but got the same error after installing apps and cannot run them.
containerd is version=1.6.18

**Comment by jerrykuku** [comment]
I re-added apparmor as a CasaOS installation dependency to fix the problem. You can try installing it again.
