### ISSUE TITLE
login screen will not display  if logout

### ISSUE THREAD

**Issue by insert0003** [IceWhaleTech/CasaOS#87]
**Describe the bug**

login screen will not display  if logout, just background is shown.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.7
	 - Disk Total: 58354 
	 - Disk Used: 2449 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:32 Mem:491M Core:4 Linux DietPi 5.10.60-sunxi #21.08.2 SMP Tue Sep 14 16:28:44 UTC 2021 armv7l GNU/Linux]
	 - Browser: Chrome 
	 - Version: 96.0.4664.45

![image](https://user-images.githubusercontent.com/11204704/151351993-69092df9-8623-4939-981a-eb23d74c3bc6.png)

**Comment by jerrykuku** [comment]
You can try rolling back to the previous version using the following script.

`curl -fsSL https://get.icewhale.io/casaos.sh | bash -s -- -v v0.2.6`

We will fix this problem as soon as possible.Thanks for submitting your feedback.

**Comment by insert0003** [comment]
0.2.6 is worked, Thanks a lot.

**Comment by jerrykuku** [comment]
Version 0.2.8 has been released, this issue has been fixed and can be updated.

**Comment by insert0003** [comment]
It's worked. Closed
