### ISSUE TITLE
[Feedback] 

### ISSUE THREAD

**Issue by 392377870** [IceWhaleTech/CasaOS#870]
### Description

重启后不能重新挂载已经插入的内存卡

**Comment by raller1028** [comment]
你这边能提供更详细的信息吗,我这边重启后内存卡还是能自动挂载上

![Image](https://user-images.githubusercontent.com/57336867/218965019-1b2632f4-3a8e-4cab-99c0-4aed7f39c3a1.png)

**Comment by raller1028** [comment]
如果仍有问题,请重新打开

**Comment by 392377870** [comment]
好的，我试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IceWhaleTech/CasaOS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月22日(星期三) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IceWhaleTech/CasaOS] [Feedback]  (Issue #870)





 
如果仍有问题,请重新打开
