### ISSUE TITLE
[Bug] 无法修改端口

### ISSUE THREAD

**Issue by cat0i** [IceWhaleTech/CasaOS#873]
![OHBYPJ BBPW84YHUK VLHDH](https://user-images.githubusercontent.com/41892758/217544970-f81e2f17-5b1f-415c-a11f-9449b50df826.png)
装了宝塔、dokcer，会冲突吗

**Comment by cat0i** [comment]
ubuntu的系统22.04

**Comment by raller1028** [comment]
![Image](https://user-images.githubusercontent.com/57336867/218957606-cb5e8790-0f28-4818-a795-4baa982d89a8.png)

修改你宝塔里面的安全配置后,就能够更改casaos的端口了
