### ISSUE TITLE
(Bug) App store not loading

### ISSUE THREAD

**Issue by keiron26** [IceWhaleTech/CasaOS#874]
### Description

The app store is not working getting error There was an error when loading App Store list. Please try again.

it is a fresh install on raspberry os lite 

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 59661 
	 - Disk Used: 2223 
	 - System Info: [Raspbian GNU/Linux 11   \l Bit:32 Mem:743M Core:4 Linux raspberrypi 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Opera 
	 - Version: 94

**Comment by RSerejo** [comment]
same here

Ubuntu server 20.04

**Comment by RSerejo** [comment]
same is happing with "casaos live demo"

**Comment by CosmoFox** [comment]
same here

Ubuntu desktop 22

**Comment by keiron26** [comment]
> same is happing with "casaos live demo"

must be a server issue then

**Comment by keiron26** [comment]
> same is happing with "casaos live demo"

i just tried it and its ok with me with casa os demo

**Comment by piptravels** [comment]
Damn I just got here, ya'll started the party without me? Pi 4 Fresh install Ubuntu Server 22.04.1. worked last night...no joy today lol

**Comment by solaire-git** [comment]
same here.

Ubuntu 20.04, running the latest version of CasaOS.

**Comment by mikebgrep** [comment]
Same here `There was an error when loading App Store list. Please try again.` 
Raspberry Pi 4 Raspian OS

**Comment by Lexime1986** [comment]
i just installed casaos and i thought i fucked up seeing the error

**Comment by keiron26** [comment]
> i just installed casaos and i thought i fucked up seeing the error

i thought exactly the same 

it is a clearly a their end server issue

**Comment by wochgn** [comment]
Same. Debian 12 aarch64  - "There was an error when loading App Store list. Please try again."

**Comment by Self-adjointOperator** [comment]
Same.Debian 11 with the latest version of casaOS.

**Comment by mikebgrep** [comment]
I think is fixed already

**Comment by jerrykuku** [comment]
The current version of CasaOS gets the app store data from a remote server, but from the next version onwards all the store data will be self-deployed, which should solve this problem.

**Comment by tigerinus** [comment]
For anyone experiencing this issue, appreciated if you can help to troubleshoot with following steps

(Also see https://wiki.casaos.io/en/troubleshooting/appstore-does-not-load)

Run through following command to check if AppStore API returns app catalog

```shell
curl https://api.casaos.io/casaos-api/token
```

If successful, a JSON payload like sample below will be returned

```json
{
   "code" : 200,
   "data" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIiwiZXhwIjoxNjc2NDI0MDIzLCJpc3MiOiJnaW4tYmxvZyJ9._nj5ZFUsicx5q5swKh1cwUdooslnK582By3o3K-P_u4",
   "mssage" : "ok"
}
```

Copy the token in `data` above and replace the `<token>` below with it

```shell
curl https://api.casaos.io/casaos-api/v2/app/newlist  -H "Authorization: <token>"
```

If AppStore API is running, a JSON payload of app catalog will be returned.
