### ISSUE TITLE
[Bug] 100% CPU USE

### ISSUE THREAD

**Issue by Ebusicano** [IceWhaleTech/CasaOS#876]
A process called casaos-app-management is using 100%. In the console the service is bugged and shows 300% cpu use.

**Comment by tigerinus** [comment]
> A process called casaos-app-management is using 100%. In the console the service is bugged and shows 300% cpu use.

@Ebusicano - Can you share the log of casaos-app-management when high CPU usage took place?

the command is `journalctl -xef -u casaos-app-management`

**Comment by tigerinus** [comment]
Closing this for now. @Ebusicano - if you still see this happening, please re-open with more details. Thanks!

**Comment by Ebusicano** [comment]
I uninstalled casaos until it get repaired or updated. I really like
casaOS, but i cant have it with that problem. Guess they can update it soon.

**Comment by javier-house** [comment]
Aug 16 13:06:13 pve casaos-app-management[1581]: {"time":"2023-08-16T13:06:13.496811872+08:00","id":"","remote_ip":"192.168.166.166","host":"192.168.166.250","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0","status":200,"error":"","latency":112175063,"latency_human":"112.175063ms","bytes_in":0,"bytes_out":454}
Aug 16 13:06:18 pve casaos-app-management[1581]: {"time":"2023-08-16T13:06:18.806324532+08:00","id":"","remote_ip":"192.168.166.166","host":"192.168.166.250","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0","status":200,"error":"","latency":121981048,"latency_human":"121.981048ms","bytes_in":0,"bytes_out":454}
Aug 16 13:06:23 pve casaos-app-management[1581]: {"time":"2023-08-16T13:06:23.583575724+08:00","id":"","remote_ip":"192.168.166.166","host":"192.168.166.250","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0","status":200,"error":"","latency":121946404,"latency_human":"121.946404ms","bytes_in":0,"bytes_out":454}
Aug 16 13:06:28 pve casaos-app-management[1581]: {"time":"2023-08-16T13:06:28.568361008+08:00","id":"","remote_ip":"192.168.166.166","host":"192.168.166.250","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0","status":200,"error":"","latency":122116979,"latency_human":"122.116979ms","bytes_in":0,"bytes_out":454}
^AAug 16 13:06:33 pve casaos-app-management[1581]: {"time":"2023-08-16T13:06:33.569060379+08:00","id":"","remote_ip":"192.168.166.166","host":"192.168.166.250","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0","status":200,"error":"","latency":122264394,"latency_human":"122.264394ms","bytes_in":0,"bytes_out":454}
