### ISSUE TITLE
[Bug] CentOS7安装失败

### ISSUE THREAD

**Issue by Kirito1193** [IceWhaleTech/CasaOS#882]
[root@HKlw5uu5z1 ~]# curl -fsSL https://get.casaos.io | sudo bash

   _____                 ____   _____ 
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___  
 | |    / _` / __|/ _` | |  | |\___ \ 
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/ 
                                      
   --- Made by IceWhale with YOU ---

[  OK  ] Your hardware architecture is : x86_64
[  OK  ] Your System is : Linux
[NOTICE] Your Linux Distribution is : rhel fedora We have not tested it on this system and it may fail to install.
[  OK  ] Memory capacity check passed.
[  OK  ] Disk capacity check passed.
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * centos-sclo-rh: mirror.fcix.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
No packages marked for update
which: no udevil in (/usr/sbin:/sbin:/bin:/usr/sbin:/usr/bin)
[ INFO ] Install the necessary dependencies: udevil 
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * centos-sclo-rh: mirror.fcix.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
No package udevil available.
Error: Nothing to do
[root@HKlw5uu5z1 ~]# 

<img width="519" alt="Snipaste_2023-02-10_09-26-42" src="https://user-images.githubusercontent.com/82529036/217977087-27eeea17-2209-4f6a-b271-cf4f34c9aa81.png">

**Comment by jerrykuku** [comment]
看上去是centos 没有 udevil这个依赖。目前暂时没办法支持。

**Comment by wvkmind** [comment]
# Download & Extract
    mkdir /tmp/udevil-next && cd /tmp/udevil-next
    wget -O udevil-next.tar.gz https://github.com/IgnorantGuru/udevil/tarball/next
    tar xzf udevil-next.tar.gz
    cd IgnorantGuru-udevil-*

    # Build, & Install
    ./configure --prefix=/usr
    make
    sudo make install

    # Remove Temporary Files
    cd / && rm -rf /tmp/udevil-next
