### ISSUE TITLE
[Feedback]bug report

### ISSUE THREAD

**Issue by JohnXiong2** [IceWhaleTech/CasaOS#883]
### Description

jackett can not launch

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 80389 
	 - Disk Used: 8290 
	 - System Info: [Debian GNU/Linux 10   \l Bit:64 Mem:3946M Core:2 Linux ip-172-26-0-59 4.19.0-22-cloud-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Chrome 
	 - Version: 109.0.0.0

**Comment by raller1028** [comment]
This problem will be fixed in v0.4.2, current version if you need to use jackett can directly access the corresponding port

![Image](https://user-images.githubusercontent.com/57336867/218953684-ab501066-c59b-4c33-acc7-c9989a6f95ab.png)
