### ISSUE TITLE
[Feedback]Blank top bar

### ISSUE THREAD

**Issue by roll0ver** [IceWhaleTech/CasaOS#886]
### Description

Web UI is missing any control elements on the top bar, even after a restart. Edge browser does not show navbar buttons, Firefox does

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 27712 
	 - Disk Used: 13247 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7802M Core:4 Linux CasaOS 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Edge 
	 - Version: 109.0.1518.78

**Comment by raller1028** [comment]
Can you provide more information or screenshots?
