### ISSUE TITLE
[Feedback][问题] 页面登录时默认显示一个用户名， 为什么不能填写用户名密码？ 

### ISSUE THREAD

**Issue by Andy1i** [IceWhaleTech/CasaOS#887]
### Description

登录时默认显示用户名， 这样是不是有安全风险， 是否可以用户名和密码都让用户进行输入

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 232180 
	 - Disk Used: 10931 
	 - System Info: [openmediavault 6.0.24-1 (Shaitan)   \l Copyright (C) 2009-2022 by Volker Theile. All rights reserved. To manage the system visit the openmediavault web control panel: docker0: 172.17.0.1 wlp8s0: 192.168.31.66 wlp8s0: fe80::323a:64ff:fe6e:485d By default the web control panel administrator account has the username 'admin' and password 'openmediavault'. It is recommended that you change the password for this account within the web control panel or using the 'omv-firstaid' CLI command. For more information regarding this appliance, please visit the web site: https://www.openmediavault.org Bit:64 Mem:7866M Core:4 Linux omv-system 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) x86_64 GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Chrome 
	 - Version: 109.0.0.0

**Comment by ETWang1991** [comment]
你好，稍晚考虑提供多账户登录的功能，目前CasaOS仅单账户可用
Hi, we will consider providing multi-account login later, currently CasaOS is only available for single account

**Comment by ETWang1991** [comment]
如果您不希望在公网上暴露用户名，您可以使用admin这样没有个人信息的用户名
If you do not want to expose your username on the public web, you can use a username without personal information like admin

**Comment by Andy1i** [comment]
> 你好，稍晚考虑提供多账户登录的功能，目前CasaOS仅单账户可用 Hi, we will consider providing multi-account login later, currently CasaOS is only available for single account

单用户登录时， 让用户输入账户名和密码， 不默认填充用户名呢？

**Comment by Andy1i** [comment]
> 如果您不希望在公网上暴露用户名，您可以使用admin这样没有个人信息的用户名 If you do not want to expose your username on the public web, you can use a username without personal information like admin

现在是默认填充上了用户名的， 不默认填充用户名不就可以了嘛~

**Comment by ETWang1991** [comment]
> > 如果您不希望在公网上暴露用户名，您可以使用admin这样没有个人信息的用户名 If you do not want to expose your username on the public web, you can use a username without personal information like admin
> 
> 现在是默认填充上了用户名的， 不默认填充用户名不就可以了嘛~

理解你的意思，这样会增加安全性，但会降低便利性。
不过经过讨论，决定在新版本中，不默认填充用户名了，最近的版本会修改。

**Comment by purpletoad2020** [comment]
> > > 如果您不希望在公网上暴露用户名，您可以使用admin这样没有个人信息的用户名 If you do not want to expose your username on the public web, you can use a username without personal information like admin
> > 
> > 
> > 现在是默认填充上了用户名的， 不默认填充用户名不就可以了嘛~
> 
> 理解你的意思，这样会增加安全性，但会降低便利性。 不过经过讨论，决定在新版本中，不默认填充用户名了，最近的版本会修改。

刚刚更新了新版本，发现需要输入用户名了，但是任何一个用户名都进不去了？有解吗？

**Comment by jerrykuku** [comment]
这个问题已经在v0.4.2中进行了修改，看下是否满足你的需求？ 如果你登陆过会帮你自动填充用户名，但是全新的机器需要输入。
