### ISSUE TITLE
[Feedback]Terminal

### ISSUE THREAD

**Issue by MrYDeath** [IceWhaleTech/CasaOS#888]
### Description

Hi
I can`t login to terminal , on home screen , 
I try casaos / casaos , my nick/password , root/root ... nothing ....

### Additional Information

	 - OS: linux
![casaos](https://user-images.githubusercontent.com/97698559/218263423-c2707e5f-fe9a-464f-a195-2e4e27a7f6fd.jpg)

	 - CasaOS Version: 0.4.1
	 - Disk Total: 110638 
	 - Disk Used: 7361 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:M Core:2 Linux debian 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Chrome 
	 - Version: 110.0.0.0

**Comment by CosmoFox** [comment]
install openssh-server first.

**Comment by jerrykuku** [comment]
It's your debian ssh user and password

**Comment by raller1028** [comment]
If there are still problems, please reopen

**Comment by MrYDeath** [comment]
Hi the problem with log and use terminal, I find another topic and try to solve my problem. 
It's work when I add a local LAN address in firewall. And everything is work perfect. 
Greetings ppl.
