### ISSUE TITLE
[Feedback]AdGuardHome - Preparing for launch 

### ISSUE THREAD

**Issue by Jeanoo** [IceWhaleTech/CasaOS#891]
### Description

AdGuardHome
the "Preparing for launch" does not lead anywhere 

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 28863 
	 - Disk Used: 11029 
	 - System Info: [Raspbian GNU/Linux 11   \l Bit:32 Mem:922M Core:4 Linux paulohome 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Firefox 
	 - Version: 109.0

**Comment by jerrykuku** [comment]
Thanks for the feedback, we will fix this bug in the v0.4.2 release, You can update the v0.4.2 alpha via
 `curl -fsSL https://get.casaos.io/update/v0.4.2-alpha | bash`, If the problem persists, please let us know.

**Comment by Jeanoo** [comment]
don't work
` sudo curl -fsSL https://get.casaos.io/update/v0.4.2-alpha | bash

   _____                 ____   _____
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___
 | |    / _` / __|/ _` | |  | |\___ \
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/

   --- Made by IceWhale with YOU ---

- OK Your hardware architecture is : armv7l
Atteint▒:1 http://archive.raspberrypi.org/debian bullseye InRelease
Atteint▒:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Atteint▒:3 https://download.docker.com/linux/raspbian bullseye InRelease
Lecture des listes de paquets... Fait
- INFO Configuration CasaOS Addons
main: ligne 387 : pushd: /tmp/casaos-installer/tmp.BUzBEKMf2q: Permission non accord▒e
`

**Comment by jerrykuku** [comment]
Sorry, my bad, please use `curl -fsSL https://get.casaos.io/update/v0.4.2-alpha | sudo bash`

**Comment by Jeanoo** [comment]
the update was successful, but AdGuardHome was not

**Comment by tigerinus** [comment]
I think this is a dup of #913 #905 

@Jeanoo - we've released a hotfix - can you update from terminal and see if this is fixed?


```shell
curl -fsSL https://get.casaos.io/update| sudo bash
```

**Comment by Jeanoo** [comment]
sorry tigerinus AdGuardHome doesn't work

**Comment by tigerinus** [comment]
Can you run 

```
sudo journalctl -xe -u casaos-app-management | grep git
```

Just to make sure you are running the same build that has the fix.

**Comment by Jeanoo** [comment]
f▒v 26 13:25:10 paulohome casaos-app-management[2569]: git commit: a4*********************************************5d
f▒v 26 13:33:09 paulohome casaos-app-management[5169]: git commit: e1*********************************************eb
f▒v 26 13:37:54 paulohome casaos-app-management[2059]: git commit: e1*********************************************eb

**Comment by Jeanoo** [comment]
f▒v 26 13:25:10 *home casaos-app-management[2569]: git commit: a4*********************************************5d
f▒v 26 13:33:09 *home casaos-app-management[5169]: git commit: e1*********************************************eb
f▒v 26 13:37:54 *home casaos-app-management[2059]: git commit: e1*********************************************eb

**Comment by tigerinus** [comment]
Your build should be correct, as it matches the commit hash `e1717f9f1a44f6986b9f324ee3ab64d9678d5aeb`

I just can't reproduce your issue. AdGuard runs fine on the same build on my machine.

What happens if you visit AdGuard web UI directly? Can you check for the WebUI port from its settings.
