### ISSUE TITLE
[Bug] 设置Docker Web UI 无法打开指定端口

### ISSUE THREAD

**Issue by BEF841CA** [IceWhaleTech/CasaOS#892]
**Describe the bug**
设置Docker Web UI 无法打开指定端口

**To Reproduce**
![image](https://user-images.githubusercontent.com/83743162/218626966-65685246-e8a1-4b87-beeb-913ec493396f.png)
设置Web UI 为 8848 端口
![image](https://user-images.githubusercontent.com/83743162/218626694-fb218597-ef28-44c7-903e-dedb7227305b.png)
实际打开地址
http://192.168.7.8/#/launch?appDetailData=%7B%22id%22%3A%2261fc4de03f70f2039bc94c450dbb3f32607e0b4a90ed3d6ce1d6363dad6018bc%22,%22name%22%3A%22Nacos%22,%22icon%22%3A%22http%3A%2F%2F192.168.7.8%3A8848%2Fnacos%2Fconsole-ui%2Fpublic%2Fimg%2Fnacos-logo.png%22,%22state%22%3A%22running%22,%22custom_id%22%3A%22f4c369bd-8b39-4596-8733-f3d36edcf6f9%22,%22index%22%3A%22%2Fnacos%22,%22port%22%3A%228848%22,%22slogan%22%3A%22%22,%22type%22%3A%22%22,%22image%22%3A%22nacos%2Fnacos-server%22,%22volumes%22%3A%22%22,%22latest%22%3Afalse,%22host%22%3A%22192.168.7.8%22,%22protocol%22%3A%22http%22,%22created%22%3A1676343123,%22appstore_id%22%3A0%7D

修改配置
![image](https://user-images.githubusercontent.com/83743162/218627367-42575481-3d4b-46de-9e3d-19274565de4b.png)
可以正常打开网站
![image](https://user-images.githubusercontent.com/83743162/218627475-a1a0b127-e4a6-4ea4-b500-8f615480bb06.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 
 - Browser Microsoft Edge 版本 110.0.1587.41 (正式版本) (64 位)
 - Version 0.4.1

**Logs**

run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
```

**Additional context**

**Comment by zhanghengxin** [comment]
第一次启动过程会非常慢，你需要先排除这种可能。在一分钟之后，他会弹出直接打开的按钮。你可以试试。
You need to rule out the possibility that the first boot will be very slow. After a minute, he pops up a button that opens directly. You can try it.


我会在尝试这个应用之后继续回复。
I'll keep replying after I try the app.

**Comment by BEF841CA** [comment]
> 第一次启动过程会非常慢，你需要先排除这种可能。在一分钟之后，他会弹出直接打开的按钮。你可以试试。您需要排除第一次启动非常慢的可能性。一分钟后，他弹出一个直接打开的按钮。你可以试试。
> 
> 我会在尝试这个应用之后继续回复。试用该应用程序后，我会继续回复。

等待一段时间后，还是保持在准备启动的页面，并没有弹出直接打开的按钮

**Comment by zhanghengxin** [comment]
> 
> 等待一段时间后，还是保持在准备启动的页面，并没有弹出直接打开的按钮

0.4.2 修复了这个问题。你可以通过更新脚本更新到 0.4.2alpha
更新脚本： curl -fsSL https://get.casaos.io/update/v0.4.2-alpha | sudo bash
国内更新脚本： curl -fsSL https://get.casaos.io/update/v0.4.2-alpha/cn | sudo bash

**Comment by BEF841CA** [comment]
> 

我更新到0.4.2后，还是存在问题，下面是我的配置
![image](https://user-images.githubusercontent.com/83743162/219277953-1373c007-4322-441c-aa39-6a9f9b0f500d.png)
![image](https://user-images.githubusercontent.com/83743162/219278063-c0b8f25d-028b-4464-abc5-852e4dc6dc67.png)
点击APP 后，跳转到APP准备启动的页面
![image](https://user-images.githubusercontent.com/83743162/219278535-c8ff9d88-fbf0-4c17-8539-dce026ae3a7a.png)
过一会提示  App 可能不可用 请 点击这里 打开 app。如果它无法工作，请稍后重启或重试。
![image](https://user-images.githubusercontent.com/83743162/219278611-9cac675b-c84f-49ac-8aa1-6625054d611f.png)
点击后才能打开我的APP

**Comment by zhanghengxin** [comment]
我这边大致锁定问题方向了。
能够提供一下 cli 的安装方式吗？

**Comment by BEF841CA** [comment]
> 我这边大致锁定问题方向了。 能够提供一下 cli 的安装方式吗？

curl -fsSL https://get.casaos.io | sudo bash

**Comment by BEF841CA** [comment]
> > curl -fsSL https://get.casaos.io | sudo bash
> 
> 是你的这个应用，其他的应用是OK 的。

docker run -d \
-e MODE=standalone \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=192.168.7.xxx \
-e MYSQL_SERVICE_USER=xxxx \
-e MYSQL_SERVICE_PASSWORD=xxxx \
-e MYSQL_SERVICE_DB_NAME=nacos \
-p 8848:8848 \
--name nacos \
--restart=always \
nacos/nacos-server
