### ISSUE TITLE
[Feedback]Impossible to install ad-dons

### ISSUE THREAD

**Issue by Jeanoo** [IceWhaleTech/CasaOS#893]
### Description

Impossible to install ad-dons on Home assistant

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 28863 
	 - Disk Used: 11087 
	 - System Info: [Raspbian GNU/Linux 11   \l Bit:32 Mem:922M Core:4 Linux paulohome 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Firefox 
	 - Version: 109.0

**Comment by JohnGuan** [comment]
The official Docker image version does not offer the Addons option.
There are some third-party images available, so we can look for them later.
Which Addons do you need?

**Comment by JohnGuan** [comment]
We are closing this issue due to too long lack of response.
This issue depends mainly on the problem with the original Docker application of Home Assistant.
We'll keep an eye on it when we have time, but we can't make changes immediately.
