### ISSUE TITLE
[Feedback]Translation error

### ISSUE THREAD

**Issue by n1c0la84** [IceWhaleTech/CasaOS#897]
### Description

The word "Open" is translated in Italian in the wrong way. The right word in Italian is "Apri" not "Opri".

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 29483 
	 - Disk Used: 8309 
	 - System Info: [openmediavault 6.1.9-1 (Shaitan)   \l Copyright (C) 2009-2023 by Volker Theile. All rights reserved. To manage the system visit the openmediavault workbench: br-0e1f77f52b94: 172.18.0.1 docker0: 172.17.0.1 eth0: 192.168.1.10 By default the workbench administrator account has the username 'admin' and password 'openmediavault'. It is recommended that you change the password for this account within the workbench or using the 'omv-firstaid' CLI command. For more information regarding this appliance, please visit the web site: https://www.openmediavault.org Bit:64 Mem:7812M Core:4 Linux raspberrypi4 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Chrome 
	 - Version: 110.0.0.0

**Comment by jerrykuku** [comment]
Thanks for the feedback, we will update this bug in the v0.4.2 release

**Comment by raller1028** [comment]
v0.4.2 has fixed this problem, if there are still problems, please reopen
