### ISSUE TITLE
[Feedback]账户或密码错误问题

### ISSUE THREAD

**Issue by Abole** [IceWhaleTech/CasaOS#901]
### Description

输入密码显示我输入错误，但是把访问地址的/login删掉，就能正常访问，多次更改密码，打开app时仍然显示我密码错误

**Comment by zhanghengxin** [comment]
请问如何复现？

How to do make it happen again?

**Comment by jerrykuku** [comment]
目前我们测试没有出现这个问题，你可以尝试使用隐私模式打开，看看问题是否依然存在？
