### ISSUE TITLE
[Issue] Apps do not start

### ISSUE THREAD

**Issue by Jerakin** [IceWhaleTech/CasaOS#905]
### Description

I have installed AdGuardHome and PiHole the behavior is the same for both.

If I try to click on an app it goes to the launch redirect where it is stuck on "Preparing to launch". If I try to navigate directly to the app though the selected port I get a "Unable to connect" error.

This is fresh install of Ubuntu and pretty much a fresh install of CasaOS, had to uninstall docker from snap and install it with apt before installing apps worked at all.

I also installed "Home Assistant" and I can start that through the button and through browsing to the url directly

After reinstalling PiHole I can access it through the url directly but not through the icon button. 

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 58245 
	 - Disk Used: 8393 
	 - System Info: [Ubuntu 22.04.1 LTS   \l Bit:64 Mem:7832M Core:4 Linux home-server 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Firefox 
	 - Version: 110.0

**Comment by raller1028** [comment]
1. v0.4.2 fix launch redirect problem
2. PiHole and ADGuardHome two apps need 53 this port, while downloading will appear conflict, the next version of the application center will be revised to solve this problem

**Comment by Jerakin** [comment]
Thanks for the fix! Pi-Hole now launches **but** AdGuardHome does **not**
