### ISSUE TITLE
[Feedback]系统状态cpu获取不到温度

### ISSUE THREAD

**Issue by phcl1998** [IceWhaleTech/CasaOS#906]
### Description

cpu显示温度为0°

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 224992 
	 - Disk Used: 12049 
	 - System Info: [Armbian 22.11.4 Jammy \l Bit:64 Mem:7420M Core:4 Linux uefi-x86 5.15.80-x86 #22.11.1 SMP Wed Nov 30 11:34:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.4.1
	 - Browser: Chrome 
	 - Version: 95.0.4638.69

**Comment by merlinmxn** [comment]
可以吧？什么设备？虚拟机吗？

**Comment by phcl1998** [comment]
> 可以吧？什么设备？虚拟机吗？

中兴ct340（小主机）  AMD GX-415GA SOC

**Comment by phcl1998** [comment]
![屏幕截图 2023-02-21 101232](https://user-images.githubusercontent.com/125857645/220230108-26f99a4f-3f71-4977-a1a9-dc4b9fdfc2b8.png)

- root@uefi-x86:~# cat /proc/version
- Linux version 5.15.80-x86 (root@285c76ebe462) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #22.11.1 SMP Wed Nov 30 11:34:07 UTC 2022

**Comment by phcl1998** [comment]
> > 可以吧？什么设备？虚拟机吗？
> 
> 中兴ct340（小主机）AMD GX-415GA SOC
物理机

**Comment by LinkLeong** [comment]
我们目前没有amd设备,我测试了我们不同类型的inter的设备,均没有发现该问题.我们在/sys/devices/virtual/thermal/thermal_zone这个位置获取的温度,可能的话你可以尝试获取一下温度告诉我们.或者也可以添加我们的微信群,我们可以一起解决这个问题.

**Comment by phcl1998** [comment]
> 我们目前没有amd设备,我测试了我们不同类型的inter的设备,均没有发现该问题.我们在/sys/devices/virtual/thermal/thermal_zone这个位置获取的温度,可能的话你可以尝试获取一下温度告诉我们.或者也可以添加我们的微信群,我们可以一起解决这个问题.
你好，微信群是多呢？
