### ISSUE TITLE
[Bug] Casa not see wlan iface

### ISSUE THREAD

**Issue by CosmoFox** [IceWhaleTech/CasaOS#909]
**Describe the bug**
Casa v0.4.1 dont show at monitoring panel wlan iface.

**Screenshots**
![bug](https://user-images.githubusercontent.com/9054349/220070952-fb670b1e-f566-4a82-84ed-6b06520a6f65.png)

**Desktop (please complete the following information):**
 - OS: ubuntu-22.04
 - CPU: intel i7-1260p
 - WIFI: Intel AX201NGW

**Comment by CosmoFox** [comment]
Tested with another wifi card. Same problem!
OS: ubuntu-22.04
CPU: intel i7-1260p
WIFI: Intel **AX211NGW**

**Comment by CosmoFox** [comment]
> 

![image](https://user-images.githubusercontent.com/9054349/222364720-d8c75049-a62f-4f47-b751-5c1a079ecbb3.png)

**Comment by CosmoFox** [comment]
But wlo1 here

![image](https://user-images.githubusercontent.com/9054349/222366276-38ad55ff-3a10-47b4-931d-14a3f160cadc.png)

**Comment by CosmoFox** [comment]
![image](https://user-images.githubusercontent.com/9054349/222366958-dcdfd667-cc45-4817-b7fd-c8e4f01579a8.png)

command `ls /sys/class/net/ | grep -v "$(ls /sys/devices/virtual/net/)"` removing wLO1

**Comment by CosmoFox** [comment]
but if add new key "-w" - look like a solution
![image](https://user-images.githubusercontent.com/9054349/222367541-d4f7811b-6cfb-49bd-a383-c683e2256a85.png)

**Comment by CosmoFox** [comment]
Yeah! It`s works! Pls add this to next version.
![image](https://user-images.githubusercontent.com/9054349/222368547-cc689d25-3b9d-4f55-8471-ecc84266960d.png)

**Comment by jerrykuku** [comment]
This is very important information for us and we appreciate your feedback. I think the "lo" in the virtual network causes the removal of "wlo1". I will contact @LinkLeong  to fix this code.

**Comment by CosmoFox** [comment]
> This is very important information for us and we appreciate your feedback. I think the "lo" in the virtual network causes the removal of "wlo1". I will contact @LinkLeong to fix this code.

There is an easier answer:
if `grep -v` :
is "abc" in "abcd" - **true**. It`s 'partial' search

if `grep -v -w` :
is "abc" in "abcd" - **false**. It`s exact what you need, because there can be many similar names in the system and you use an exception by names of interfaces

**Comment by raller1028** [comment]
@CosmoFox casaos0.4.3-alpha has been released, can you help test if this issue still exists? 
Update command: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash

**Comment by CosmoFox** [comment]
> @CosmoFox casaos0.4.3-alpha has been released, can you help test if this issue still exists? Update command: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash

will alpha version update later to stable in regular way?

**Comment by CosmoFox** [comment]
> @CosmoFox casaos0.4.3-alpha has been released, can you help test if this issue still exists? Update command: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash

Any way. Yes I can. Installed. And yes - it`s works.
So U can close ticket.
