### ISSUE TITLE
[Bug]  Casa update fails

### ISSUE THREAD

**Issue by stmiba** [IceWhaleTech/CasaOS#911]
**Describe the bug**
Update from 0.3.2.1 to 0.4.1 fails. Click the "Upgrade Now" button result sin a spinning icon and the update never completing. There are no messages and the pop up window never closes.

**To Reproduce**
Click "Update" in setting menu.
Click "Upgrade Now" in pop up window.
See screenshot in screenshots section

**Expected behavior**
Upgrade should happen

**Screenshots**
<img width="680" alt="Screenshot 2023-02-20 at 12 33 48" src="https://user-images.githubusercontent.com/46076448/220170887-7d20e931-45b6-4f9c-89ce-d84403ab5af7.png">

**Desktop (please complete the following information):**
 - OS: linux
 - CasaOS Version: 0.3.2.1
 - Disk Total: 13253 
 - Disk Used: 5409 
 - Sync State: Sync img: true
linuxserver/syncthing:latest,
Sync Key length: 32
 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1826M Core:2 Linux CasaOS 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux]
 - Browser: Chrome 
 - Version: 109.0.0.0
**Logs**

Unable to run commands.

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos.service
```

**Additional context**

**Comment by afritsch89** [comment]
Tried installing via curl, it fails on dependencies, mine won't get past rclone.

` INFO ] Running /tmp/casaos-installer/tmp.96vfJH074W/build/scripts/setup/script.d/06-setup-app-management.sh...
🟩 Running setup-app-management.sh...
Initializing config file...
'/etc/casaos/app-management.conf.sample' -> '/etc/casaos/app-management.conf'
Enabling service...
Created symlink /etc/systemd/system/multi-user.target.wants/casaos-app-management.service → /lib/systemd/system/casaos-app-management.service.
✅ setup-app-management.sh finished.
[ INFO ] Install the necessary dependencies: Rclone 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4669  100  4669    0     0   7567      0 --:--:-- --:--:-- --:--:--  7555

The latest version of rclone rclone v1.61.1 is already installed.

[FAILED] Installation failed, please try again.
casaos@CasaOS:~$ sudo apt remove rclone
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'rclone' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 248 not upgraded.`

I thought it was maybe installed on the host so i tried to remove it there,

Also uninstalled and tried a fresh install, same error but I did notice during uninstall it couldn't remove containers or images response from Damon was "not found"

**Comment by raller1028** [comment]
@stmiba  you can use command to update to v0.4.2 
update command: `curl -fsSL https://get.casaos.io/update | sudo bash`

@afritsch89 v0.4.2-hotfix1 has been fixed this problem, you can try to install again
install command: `curl -fsSL https://get.casaos.io | sudo bash`

**Comment by stmiba** [comment]
> @stmiba you can use command to update to v0.4.2 update command: `curl -fsSL https://get.casaos.io/update | sudo bash`
> 
> @afritsch89 v0.4.2-hotfix1 has been fixed this problem, you can try to install again install command: `curl -fsSL https://get.casaos.io | sudo bash`
> 
> if still have problem, please reopen

I have no command line access to the machine. Not sure why.
If I try to use the terminal within Casa, I get the following message: "ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain"
If I try to ssh from a remote machine, I get "permission denied".

**Comment by stmiba** [comment]
Never mind. I found the default id and password on reddit.
To be honest with you, it's kind of frightening to me that the developer provided a default id and password without telling me it existed. Add to that the fact that the id is a member of the sudo group.
That's a major security hole.
