### ISSUE TITLE
[Bug] Cant update to 0.4.2

### ISSUE THREAD

**Issue by CosmoFox** [IceWhaleTech/CasaOS#912]
Awesome release0.4.2 is here!
But… Casa 0.4.1 dont see updates…

![image](https://user-images.githubusercontent.com/9054349/220351105-1708ac7a-68cc-49d7-8b8d-3bb3b0bbfa0c.png)

**Comment by afritsch89** [comment]
Don't. It borked my system, lost all containers, can't install new containers.

**Comment by tigerinus** [comment]
> Don't. It borked my system, lost all containers, can't install new containers.

What do you mean by lost all containers? Do you see containers in broken states or no container at all after upgrade? What's the error message when you trying to install new containers? Do you do it via CasaOS or `docker run`?

**Comment by afritsch89** [comment]
> > Don't. It borked my system, lost all containers, can't install new containers.
> 
> What do you mean by lost all containers? Do you see containers in broken states or no container at all after upgrade? What's the error message when you trying to install new containers? Do you do it via CasaOS or `docker run`?

Sorry, so after the update on the web gui all of my containers were gone.

All installed via CasaOS.

I was on 0.4.1 I think (upgraded it a few days ago when I got the ZimaBoard)

I was able to get my apps to show back up by forcibly removing Rclone (installer would hang on it because it already existed), then using the curl one liner you guys provide on the site.

But after that non of the containers would start, just forever sit on "Preparing to launch" (I would refresh the page to be sure)

I then did a fresh install of Debian and used the curl one liner which seemed to work but I could not install any apps from the app store.

I ended up running casaos-uninstall and then curled 0.4.1, now everything is working.

**Comment by tigerinus** [comment]
> But after that non of the containers would start, just forever sit on "Preparing to launch" (I would refresh the page to be sure)

That's a health check issue. We will be releasing a fix (0.4.2.1) shortly.

Is this unable to launch issue what you mean by "lost all containers"?

**Comment by tigerinus** [comment]
> > > But after that non of the containers would start, just forever sit on "Preparing to launch" (I would refresh the page to be sure)
> > 
> > 
> > That's a health check issue. We will be releasing a fix (0.4.2.1) shortly.
> > Is this unable to launch issue what you mean by "lost all containers"?
> 
> No, initially all my docker apps where simply "gone" from the web UI and I couldn't re install them from the appstore.

That's because the backend service was still loading. Once loaded, the app list will show up.

**Comment by AmadeusGraves** [comment]
Good morning, I leave this comment on this task for anyone who is unable to update their CasaOS. I believe this command is still functional. Correct me if I am wrong @tigerinus.

`curl -fsSL https://raw.githubusercontent.com/IceWhaleTech/get/main/update.sh | sudo bash`

**Comment by tigerinus** [comment]
Officially it's

```
curl -fsSL https://get.casaos.io/update | sudo bash
```

**Comment by CosmoFox** [comment]
> > Awesome release0.4.2 is here! But… Casa 0.4.1 dont see updates…
> > ![image](https://user-images.githubusercontent.com/9054349/220351105-1708ac7a-68cc-49d7-8b8d-3bb3b0bbfa0c.png)
> 
> @CosmoFox - can you try update again? Thanks!

was same.. so i used curl -fsSL https://get.casaos.io/update | sudo bash

**Comment by tigerinus** [comment]
@CosmoFox - what exactly is the update issue you are experiencing? Can you share any log or screenshot?

**Comment by CosmoFox** [comment]
no longer exists, since it was updated a long time ago with the help of the command `curl -fsSL https://get.casaos.io/update | sudo bash`
