### ISSUE TITLE
[Feedback]Issue. Cant load Emby

### ISSUE THREAD

**Issue by BorisNanev** [IceWhaleTech/CasaOS#913]
### Description

trying to start emby from casaos shows App may not be available but opening from IP and port work fine.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 112389 
	 - Disk Used: 6599 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7811M Core:4 Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Opera 
	 - Version: 95

**Comment by BorisNanev** [comment]
![Opera Snapshot_2023-02-21_170154_192 168 1 213](https://user-images.githubusercontent.com/125994050/220381026-7bf16e19-0247-40fd-8d8d-0590072b1a38.png)

**Comment by tigerinus** [comment]
related #905

**Comment by zhanghengxin** [comment]
duplicate #905

**Comment by raller1028** [comment]
v0.4.2-hotfix1 has been fixed this problem, you can update again

**Comment by tigerinus** [comment]
@BorisNanev - We've fixed this issue in `v0.4.2-1`.

If you are already running `v0.4.2`, please manually run the following commands to patch:

```
wget https://github.com/IceWhaleTech/CasaOS-AppManagement/releases/download/v0.4.2-1/linux-amd64-casaos-app-management-v0.4.2-1.tar.gz -O app-management.tar.gz
tar zxvf app-management.tar.gz
sudo systemctl stop casaos-app-management
sudo cp -rv build/sysroot/usr/bin/casaos-app-management /usr/bin/casaos-app-management
sudo systemctl start casaos-app-management
rm app-management.tar.gz
```

Let us know how it goes. Thanks!

**Comment by BorisNanev** [comment]
***@***.***:~ $ sudo systemctl start casaos-app-management
Job for casaos-app-management.service failed because the control process
exited with error code.
See "systemctl status casaos-app-management.service" and "journalctl -xe"
for details.

This is what messageiget and now i get message: failedto load apps please
try later.

На ср, 22.02.2023 г. в 18:01 ч. Tiger Wang ***@***.***>
написа:

**Comment by BorisNanev** [comment]
***@***.***:~ $ journalctl -xe
░░ the configured Restart= setting for the unit.
Feb 22 20:12:05 raspberrypi systemd[1]: Stopped CasaOS App Management
Service.
░░ Subject: A stop job for unit casaos-app-management.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A stop job for unit casaos-app-management.service has finished.
░░
░░ The job identifier is 2956 and the job result is done.
Feb 22 20:12:05 raspberrypi systemd[1]: casaos-app-management.service:
Start request repeated too quickly.
Feb 22 20:12:05 raspberrypi systemd[1]: casaos-app-management.service:
Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit casaos-app-management.service has entered the 'failed' state
with result 'exit-code'.
Feb 22 20:12:05 raspberrypi systemd[1]: Failed to start CasaOS App
Management Service.
░░ Subject: A start job for unit casaos-app-management.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit casaos-app-management.service has finished with a
failure.
░░
░░ The job identifier is 2956 and the job result is failed.
Feb 22 20:12:10 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState eth0
Feb 22 20:12:10 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState wlan0
Feb 22 20:12:10 raspberrypi casaos-message-bus[688]:
{"time":"2023-02-22T20:12:10.032863216+02:00","id":"","remote_ip":"127.0.0.1","host>
Feb 22 20:12:15 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState eth0
Feb 22 20:12:15 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState wlan0
Feb 22 20:12:15 raspberrypi casaos-message-bus[688]:
{"time":"2023-02-22T20:12:15.073420503+02:00","id":"","remote_ip":"127.0.0.1","host>
Feb 22 20:12:20 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState eth0
Feb 22 20:12:20 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState wlan0
Feb 22 20:12:20 raspberrypi casaos-message-bus[688]:
{"time":"2023-02-22T20:12:20.032654595+02:00","id":"","remote_ip":"127.0.0.1","host>
Feb 22 20:12:25 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState eth0
Feb 22 20:12:25 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState wlan0
Feb 22 20:12:25 raspberrypi casaos-message-bus[688]:
{"time":"2023-02-22T20:12:25.070704307+02:00","id":"","remote_ip":"127.0.0.1","host>
Feb 22 20:12:30 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState eth0
Feb 22 20:12:30 raspberrypi casaos[774]: /bin/bash -c source
/usr/share/casaos/shell/helper.sh ;CatNetCardState wlan0
lines 1206-1243/1243 (END)

this is the error log i think

На ср, 22.02.2023 г. в 20:07 ч. Boris Nanev ***@***.***> написа:

**Comment by BorisNanev** [comment]
This is the other one(sorry for spam, i'm still learning.

***@***.***:~ $ systemctl status casaos-app-management.service
● casaos-app-management.service - CasaOS App Management Service
     Loaded: loaded (/lib/systemd/system/casaos-app-management.service;
enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-02-22 20:21:39 EET;
32s ago
    Process: 2765 ExecStartPre=/usr/bin/casaos-app-management -v
(code=exited, status=203/EXEC)
        CPU: 2ms

Feb 22 20:21:39 raspberrypi systemd[1]: casaos-app-management.service:
Scheduled restart job, restart counter is at 5.
Feb 22 20:21:39 raspberrypi systemd[1]: Stopped CasaOS App Management
Service.
Feb 22 20:21:39 raspberrypi systemd[1]: casaos-app-management.service:
Start request repeated too quickly.
Feb 22 20:21:39 raspberrypi systemd[1]: casaos-app-management.service:
Failed with result 'exit-code'.
Feb 22 20:21:39 raspberrypi systemd[1]: Failed to start CasaOS App
Management Service.
Feb 22 20:21:47 raspberrypi systemd[1]: casaos-app-management.service:
Start request repeated too quickly.
Feb 22 20:21:47 raspberrypi systemd[1]: casaos-app-management.service:
Failed with result 'exit-code'.
Feb 22 20:21:47 raspberrypi systemd[1]: Failed to start CasaOS App
Management Service.

На ср, 22.02.2023 г. в 20:13 ч. Boris Nanev ***@***.***> написа:

**Comment by tigerinus** [comment]
@BorisNanev 

If you run following commands in directly in terminal. What does it return?

```
/usr/bin/casaos-app-management -v
/usr/bin/casaos-app-management -c /etc/casaos/app-management.conf
```

**Comment by BorisNanev** [comment]
***@***.***:~ $ /usr/bin/casaos-app-management -v
-bash: /usr/bin/casaos-app-management: cannot execute binary file: Exec
format error

***@***.***:~ $ /usr/bin/casaos-app-management -c
/etc/casaos/app-management.conf
-bash: /usr/bin/casaos-app-management: cannot execute binary file: Exec
format error

that's from both commands.

Thx very much for your assistance.

На ср, 22.02.2023 г. в 20:48 ч. Tiger Wang ***@***.***>
написа:

**Comment by BorisNanev** [comment]
I make a quick uninstall without deleting containers and after install all
works perfectly. Thanks for responding and keep good work because this is
absolutely awesome.

На ср, 22.02.2023 г. в 20:54 ч. Boris Nanev ***@***.***> написа:

**Comment by tigerinus** [comment]
`Exec format error` typically means you downloaded the package for wrong architecture, e.g. AMD64 vs ARM64.

Glad that it works out for you. Keep us updated for any issues in future.

**Comment by BorisNanev** [comment]
Thanks, I will.
