### ISSUE TITLE
[Feedback][Issue] Error in access the "share" disks/folders

### ISSUE THREAD

**Issue by mazieri** [IceWhaleTech/CasaOS#916]
### Description

I update to 0.4.2 but still does not work the access to my disks in samba share... I fixed them changing "guest user = root" to "force user = root" in /etc/samba/smb.casa.conf... is it the best way ? probably not, but it worked to me

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 14480 
	 - Disk Used: 2905 
	 - System Info: [Armbian 22.11.1 Bullseye \l Bit:64 Mem:3863M Core:6 Linux orangepi4-lts 5.15.80-rockchip64 #22.11.1 SMP PREEMPT Wed Nov 30 11:12:47 UTC 2022 aarch64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Safari 
	 - Version: 16.3

**Comment by tigerinus** [comment]
@mazieri do `cat /etc/samba/smb.casa.conf` and paste the content here.

**Comment by mazieri** [comment]
@tigerinus here 

```
[B]
comment = CasaOS share B
public = Yes
path = /media/devmon/B
browseable = Yes
read only = No
guest ok = Yes
create mask = 0777
directory mask = 0777
#guest account = root
force user = root

[A]
comment = CasaOS share A
public = Yes
path = /media/devmon/A
browseable = Yes
read only = No
guest ok = Yes
create mask = 0777
directory mask = 0777
#guest account = root
force user = root
```

**Comment by tigerinus** [comment]
`guest account` specifies the Unix account that guest users should be assigned when connecting to Samba without authentication. 

`force user` specifies the Unix account that all files created by users on the share should belong to

Can you elaborate on *still does not work the access to my disks in samba share.*?

**Comment by raller1028** [comment]
@mazieri Do you share from the Mac or Windows? I can share from the Windows side normally, and casaos can mount normally

**Comment by Amychan67899123** [comment]
![image](https://user-images.githubusercontent.com/111632440/220926871-462b6712-c88d-4242-8dae-c3a59b57be15.png)、

I also encountered the same problem, it is not accessible with the default configuration, and it is OK to add it according to the configuration of the owner

**Comment by mazieri** [comment]
> @mazieri Do you share from the Mac or Windows? I can share from the Windows side normally, and casaos can mount normally

I share from the CasaOS in my Orange Pi and try to access in the windows and Mac

**Comment by SchnappiZeik** [comment]
> 

我现在用0.4.3还是这样子。在新版本发布之前，有什么方法可以解决？
同时，挂截ntfs的U盘和硬盘都很容易出问题。自带的file里查看不到文件，会提示某mp4文件，input/output错误。

**Comment by raller1028** [comment]
@SchnappiZeik 你这边方便添加微信群,提供更多关于这个问题的信息吗有问题可以添加微信 guanningchuan 受邀入群跟进。

**Comment by raller1028** [comment]
@mazieri casaos0.4.3-alpha has been released, fixing samba related problems, can you please try again to see if there are still problems with samba?
update command: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash

**Comment by mazieri** [comment]
@raller1028 seems to be working, if need any tests, just tell to me I will try

**Comment by raller1028** [comment]
@mazieri Thanks, if have any problem, please reopen
