### ISSUE TITLE
I want to force the installation of casaos on 512RAM servers  How to do this

### ISSUE THREAD

**Issue by truman1998** [IceWhaleTech/CasaOS#918]
I want to force the installation of casaos on 512RAM servers

How to do this

[FAILED] requires atleast 1GB physical memory.

**Comment by jerrykuku** [comment]
Actually this is a wrong hint, the minimum installation memory recommended by CasaOS is 400MB.
What's device?

**Comment by jerrykuku** [comment]
Have you tried it again? Have you tried it again? I will close this issue and if you still have problems you can reopen it.
