### ISSUE TITLE
[Alpha][Bug] CasaOS 0.4.2: Update Container Error

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#920]
### What happened?

When the docker container is updated with the new functionality, data such as environment variables are lost.
For example when I upgraded nextcloud, all environment variables are gone.

Docker version 23.0.1
Ubuntu 22.04 LTS

### Screenshots

After
![Selección_1605](https://user-images.githubusercontent.com/18572939/221041456-2d6e508c-37f4-41c5-b2c4-63557e6f301c.png)

Before
![Selección_1606](https://user-images.githubusercontent.com/18572939/221041631-30e9529c-f850-43e5-8b2c-11a3758b2e08.png)

**Comment by tigerinus** [comment]
dup of #915 ?

**Comment by AmadeusGraves** [comment]
Yes, sorry, i didn't see it because it was closed. Thanks.
