### ISSUE TITLE
[Bug] debian11.6安装时提示架构错误

### ISSUE THREAD

**Issue by 2944721178** [IceWhaleTech/CasaOS#927]
环境
X86 ESXI8.0
系统
debian11.6 bios引导
报错
[FAILED] Aborted, unsupported or unknown architecture: i686
运行命令
curl -fsSL https://get.casaos.io | sudo bash

**Comment by raller1028** [comment]
你好,我们目前不支持32位的设备

**Comment by jerrykuku** [comment]
目前CasaOS 只能支持amd64也就是64位架构的系统无法支持32系统，你可以重新启动一个64位架构的Debian虚拟机重新尝试安装，我将关闭这个Issue，如果你在64位架构的系统中依然存在安装问题，你可以重新打开这个Issue向我们反馈。
