### ISSUE TITLE
[Alpha][Bug] Terminal

### ISSUE THREAD

**Issue by AmadeusGraves** [IceWhaleTech/CasaOS#929]
### What happened?

The CasaOS terminal has some bugs. When you copy a command and paste it into the terminal, sometimes the command appears in the terminal duplicated and when you try to delete the duplicity you can't, and you have to press Enter to try again.

The characters in the terminal are widely spaced, to the point of being unreadable. 
![Selección_1613](https://user-images.githubusercontent.com/18572939/222186121-a608349f-1fca-4123-984e-783d7cddf1a6.png)

In some docker containers, when entering the terminal it fails because it is running with the /bin/bash command when it should be /bin/ash. 

![Selección_1614](https://user-images.githubusercontent.com/18572939/222186500-b12c4be9-8624-42b4-9180-312caa888564.png)

**Comment by tigerinus** [comment]
This should be fixed in v0.4.3

**Comment by tigerinus** [comment]
the second issue has been addressed by https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/62

**Comment by ngabika** [comment]
When will version 0.4.3 come out?
Or how can I test it?
TY :)

**Comment by tigerinus** [comment]
Alpha testing starts this week if not later.

Watch the issue list or the #casaos-alpha channel on Discord for notice.

**Comment by raller1028** [comment]
@ngabika casaos0.4.3-alpha has been released, can you help to test if this problem still exists?
update command: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash
