### ISSUE TITLE
[Feedback]USB外置硬盘SMB共享失败提示无权限

### ISSUE THREAD

**Issue by lnnnnnnjx** [IceWhaleTech/CasaOS#936]
### Description

机内储存空间可以被SMB共享正常读取。但是通过外接的USB设备可以点击开始共享。但是局域网内设备无法正常访问。

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 7055 
	 - Disk Used: 2899 
	 - System Info: [Armbian 23.02.0-trunk Jammy \l Bit:32 Mem:990M Core:4 Linux onecloud 6.1.9-meson #trunk SMP Thu Feb 2 15:42:54 UTC 2023 armv7l armv7l armv7l GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Edge 
	 - Version: 110.0.1587.63

**Comment by jerrykuku** [comment]
这个应该是权限问题，我们将在v0.4.3进行修复，如果你愿意尝试的话，可以手动修改 /etc/samba/smb.casa.conf 中的 USB设备的配置项 将 guest account=root  改成 force user=root,保存后 使用systemctl restart smbd 进行重启再次尝试。

**Comment by lnnnnnnjx** [comment]
感谢。可以直接给我修改代码吗。我是小白。如果很麻烦的话我就等更新好了。再次感谢

老竭力 ***@***.***>于2023年3月8日 周三23:00写道：

**Comment by jerrykuku** [comment]
这个涉及到控制台操作，我建议你等待版本更新，就快发布了。

**Comment by lnnnnnnjx** [comment]
感谢大佬。我静候更新

老竭力 ***@***.***>于2023年3月9日 周四08:46写道：

**Comment by jerrykuku** [comment]
我先关闭这个issue.如果更新后问题依旧你可以重新打开它并反馈给我们，谢谢。
