### ISSUE TITLE
[Feedback]CasaOS will not update. from 0.4.1 to 0.4.2

### ISSUE THREAD

**Issue by pacaflva** [IceWhaleTech/CasaOS#937]
### Description

CasaOS is stuck at 0.4.1 on new factory configured ZimaBoard 8/32. The update to 0.4.2 starts, prints the architecture message, and then appears to hang there forever with no error messages. All prior updates have been applied.

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.1
	 - Disk Total: 27712 
	 - Disk Used: 9574 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Chrome 
	 - Version: 106.0.5249.126

**Comment by jerrykuku** [comment]
If you can login via ssh, use this command to update to 0.4.2
`curl -fsSL https://get.casaos.io/update | sudo bash` .

**Comment by pacaflva** [comment]
Linux CasaOS 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Mar 8 08:27:32 2023 from 192.168.1.87
***@***.***:~$ su -
Password:
***@***.***:~# curl -fsSL https://get.casaos.io/update | sudo bash

   _____ ____ _____
  / ____| / __ \ / ____|
 | | __ _ ___ __ _| | | | (___
 | | / _` / __|/ _` | | | |\___ \
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/

   --- Made by IceWhale with YOU ---

- OK Your hardware architecture is : x86_64
Hit:1 http://ftp.us.debian.org/debian bullseye InRelease
Get:2 https://download.docker.com/linux/debian bullseye InRelease [43.3 kB]
Ign:3 http://ftp.us.debian.org/debian bullseye-security InRelease
Hit:4 http://deb.debian.org/debian testing InRelease
Hit:5 http://security.debian.org/debian-security testing-security InRelease
Hit:6 http://ftp.us.debian.org/debian bullseye-updates InRelease
Err:7 http://ftp.us.debian.org/debian bullseye-security Release
  404 Not Found [IP: 64.50.233.100 80]
Hit:8 http://deb.debian.org/debian testing-updates InRelease
Reading package lists... Done
E: The repository 'http://ftp.us.debian.org/debian bullseye-security 
Release' does not hav
e a Release file.
N: Updating from such a repository can't be done securely, and is therefore 
disabled by de
fault.
N: See apt-secure(8) manpage for repository creation and user configuration 
details.
***@***.***:~#




























--- Original message ---
From: 老竭力 ***@***.***
Sent: March 8, 2023 9:56:43 AM
To: IceWhaleTech/CasaOS ***@***.***
CC: pacaflva ***@***.***, Author ***@***.***
Subject: Re: [IceWhaleTech/CasaOS] [Feedback]CasaOS will not update. from 
0.4.1 to 0.4.2 (Issue #937)

**Comment by pacaflva** [comment]
I flashed the OS recovery image and updated CasaOS without updating the underlying Linux and that worked fine, so there's something in the Linux updates which caused the CasaOS update failure.
-------- Original message --------From: 老竭力 ***@***.***> Date: 3/8/23  9:56 AM  (GMT-05:00) To: IceWhaleTech/CasaOS ***@***.***> Cc: pacaflva ***@***.***>, Author ***@***.***> Subject: Re: [IceWhaleTech/CasaOS] [Feedback]CasaOS will not update. from 0.4.1 to 0.4.2 (Issue #937) 
If you can login via ssh, use this command to update to 0.4.2
curl -fsSL https://get.casaos.io/update | sudo bash .

**Comment by raller1028** [comment]
If there are any problems, please reopen
