### ISSUE TITLE
[Feedback]n2800 功耗，温度。无法显示

### ISSUE THREAD

**Issue by HL5570** [IceWhaleTech/CasaOS#939]
### Description

功耗为 0w   温度常驻26度
Debian

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 58827 
	 - Disk Used: 32277 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:M Core:4 Linux debian 6.0.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) x86_64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Edge 
	 - Version: 110.0.1587.63

**Comment by HL5570** [comment]
cpu n2800

**Comment by jerrykuku** [comment]
请问cpu占用率和内存占用率的显示是在动态的变化么？

**Comment by HL5570** [comment]
> 请问cpu占用率和内存占用率的显示是在动态的变化么？

可以的

**Comment by LinkLeong** [comment]
你可以试一下这个命令`cat /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj`,看看有没有输出结果

**Comment by HL5570** [comment]
> 你可以试一下这个命令`cat /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj`,看看有没有输出结果

没有输出。

**Comment by LinkLeong** [comment]
我们目前是°这个位置的数据来确定功耗,你可以看一下主机上如何查看,我可以做个兼容.或者微信群联系我们,我们可以远程协助.

**Comment by HL5570** [comment]
> 我们目前是°这个位置的数据来确定功耗,你可以看一下主机上如何查看,我可以做个兼容.或者微信群联系我们,我们可以远程协助.

请问一下微信群是多少？

**Comment by LinkLeong** [comment]
@HL5570 微信号guanningchuan

**Comment by LinkLeong** [comment]
根据查询,cpu的温度是现实的,但是由于类型问题显示的没有变化.cpu功耗问题,经查询确实该cpu确实不支持功耗查询.我将会关闭该问题,如有疑问可重新打开.
