### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by brentgl** [IceWhaleTech/CasaOS#94]
Unable to enter Device Identification to enable Sync

submit button greyed out still after entering device identification.

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.8
	 - Disk Total: 28801 
	 - Disk Used: 6437 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Raspbian GNU/Linux 11   \l Bit:32 Mem:922M Core:4 Linux casaos 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux]
	 - Browser: Chrome 
	 - Version: 97.0.4692.71

**Comment by LinkLeong** [comment]
Did you just try again, it is possible that the program has not yet started.There is no problem to read the logs.Or you can try rebooting the device, then wait a few minutes and try again

**Comment by brentgl** [comment]
I rebooted the device, tried and same problem.
Then I waited 3 minutes or so and tried and success.  It allowed me to proceed with the sync setup.

Many thanks for your help
Brent

**Comment by jerrykuku** [comment]
> I rebooted the device, tried and same problem. Then I waited 3 minutes or so and tried and success. It allowed me to proceed with the sync setup.
> 
> Many thanks for your help Brent

Ok, We will test it again.
