### ISSUE TITLE
[Feedback][问题]自动挂载的USB硬盘不能用于下载？

### ISSUE THREAD

**Issue by SchnappiZeik** [IceWhaleTech/CasaOS#941]
### Description

exFat的硬盘不能用于下载？smb共享也不行。
是需要手动挂载并开启权限么？

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 7064 
	 - Disk Used: 2160 
	 - System Info: [Armbian 23.02.0-trunk Bullseye \l Bit:32 Mem:990M Core:4 Linux onecloud 6.1.9-meson #trunk SMP Thu Feb 2 15:42:54 UTC 2023 armv7l GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Safari 
	 - Version: 16.3

**Comment by jerrykuku** [comment]
这个问题我们可能要先测试下。

**Comment by raller1028** [comment]
@SchnappiZeik 
你好我们这边有试过用玩客云设备挂载exfat的硬盘,然后可以正常读写,smb共享也ok

**Comment by raller1028** [comment]
如果有任何问题,请重新打开
