### ISSUE TITLE
[Feedback] R4S关机后无法启动

### ISSUE THREAD

**Issue by yueeyuee** [IceWhaleTech/CasaOS#943]

**Comment by yueeyuee** [comment]
更正：如果是通过SSH输入 poweroff或reboot 命令关闭或重启，则不会出现问题。

**Comment by raller1028** [comment]
你好请问现在这个问题解决了吗

**Comment by yueeyuee** [comment]
> 你好请问现在这个问题解决了吗

问题已解决，谢谢关注。
-----------------------------
属于我自己的问题，自动挂载磁盘选项开启了，然后我手动配置了fstab，导致系统无法启动。
希望能在设置中增加点按开启或关闭按钮时弹窗确认，避免误触，请采纳 谢谢。

**Comment by jerrykuku** [comment]
会考虑这个选项，鉴于此问题已经解决，我将关闭这个issue。如果还有新的问题可以重新提交。
