### ISSUE TITLE
[Bug] Unable to update CasaOS

### ISSUE THREAD

**Issue by chiragnahata** [IceWhaleTech/CasaOS#945]
I am unbale to update casaos
https://discord.com/channels/884667213326463016/1021362958292500531/threads/1084127877374681150

**Comment by AmadeusGraves** [comment]
Duplicated #912

**Comment by AmadeusGraves** [comment]
Go to this issue to resolve this problem, cheers

**Comment by LinkLeong** [comment]
We will close the question and resubmit it if you have any questions.
