### ISSUE TITLE
[Feedback]apps not coming up

### ISSUE THREAD

**Issue by dave3691** [IceWhaleTech/CasaOS#946]
### Description

when I load it, the apps don't always come up can't figure it out. thanks  Dave

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 29667 
	 - Disk Used: 13760 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:909M Core:4 Linux raspberrypi 5.15.61-v8+ #1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 aarch64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Edge 
	 - Version: 110.0.1587.69

**Comment by raller1028** [comment]
Are you unable to open the appstore?

**Comment by raller1028** [comment]
If there are any problems, please reopen
