### ISSUE TITLE
[Feedback]软件安装异常

### ISSUE THREAD

**Issue by ernest5201314** [IceWhaleTech/CasaOS#947]
### Description

一直在走进度安装不了

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 13658 
	 - Disk Used: 2131 
	 - System Info: [Armbian 22.08.0-trunk Jammy \l Bit:64 Mem:1954M Core:4 Linux armbian 5.15.62-flippy-76+o #168 SMP PREEMPT Sun Aug 21 22:25:51 CST 2022 aarch64 aarch64 aarch64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Chrome 
	 - Version: 100.0.4896.60

**Comment by LinkLeong** [comment]
你能提交一下应用名称吗,我们来进行测试.

**Comment by kyomic** [comment]
我的也是，错误提示：加载列表出错

环境：
Linux onecloud 6.1.9-meson #trunk SMP Thu Feb  2 15:42:54 UTC 2023 armv7l armv7l armv7l GNU/Linux
CasaOS Version: 0.4.2


安装 qBittorrent应用时，http://192.168.1.14/v1/apps/75响应

`{
    "success": 200,
    "message": "ok",
    "data": {
        "id": 75,
        "title": "qBittorrent",
        "description": "The qBittorrent project aims to provide an open-source software alternative to µTorrent.",
        "tagline": "Free BitTorrent downloader",
        "tags": null,
        "icon": "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/icon.png",
        "screenshot_link": [
            "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/screenshot-1.jpg",
            "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/screenshot-2.jpg"
        ],
        "category": "Downloader",
        "category_id": 0,
        "category_font": "tray-arrow-down",
        "port_map": "8080",
        "image_version": "latest",
        "tip": "[{\"content\":\"Default Account\",\"value\":\"\"},{\"content\":\"Username: \",\"value\":\"admin\"},{\"content\":\"Password: \",\"value\":\"adminadmin\"},{\"content\":\"\",\"value\":\"\"},{\"content\":\"Default Accessible Path in qBittorrent\",\"value\":\"\"},{\"content\":\"DATA Path: \",\"value\":\"/DATA\"},{\"content\":\"Downloads Path: \",\"value\":\"/DATA/Downloads\"},{\"content\":\"Media Path: \",\"value\":\"/DATA/Media\"},{\"content\":\"The paths of other DATA subdirectories in CasaOS are also similar.\",\"value\":\"\"},{\"content\":\"Please make sure you use the correct path when using qBittorrent.\",\"value\":\"\"}]",
        "envs": [
            {
                "container": "TZ",
                "host": "$TZ",
                "desc": "TimeZone",
                "type": 3
            },
            {
                "container": "PUID",
                "host": "$PUID",
                "desc": "Run qBittorrent as specified uid.",
                "type": 3
            },
            {
                "container": "PGID",
                "host": "$PGID",
                "desc": "Run qBittorrent as specified gid.",
                "type": 3
            },
            {
                "container": "UMASK",
                "host": "002",
                "desc": "Run qBittorrent as specified UMASK.",
                "type": 3
            }
        ],
        "ports": [
            {
                "container": "8080",
                "host": "8080",
                "protocol": "tcp",
                "desc": "WebUI HTTP Port",
                "type": 0
            }
        ],
        "volumes": [
            {
                "container": "/config",
                "host": "/DATA/AppData/$AppID/config",
                "type": 3,
                "desc": "qBittorrent config directory."
            },
            {
                "container": "/DATA",
                "host": "/DATA",
                "type": 1,
                "desc": "qBittorrent Accessible directory."
            }
        ],
        "devices": [],
        "network_model": "bridge",
        "image": "hotio/qbittorrent:latest",
        "index": "/",
        "created_at": "2021-12-28T16:06:53Z",
        "updated_at": "2022-04-12T10:11:42Z",
        "state": 0,
        "author": "CasaOS Team",
        "min_memory": 256,
        "min_disk": 1024,
        "thumbnail": "https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/qBittorrent/thumbnail.jpg",
        "healthy": "",
        "plugins": null,
        "origin": "official",
        "type": 0,
        "query_count": 0,
        "developer": "qBittorrent",
        "host_name": "",
        "privileged": false,
        "cap_add": null,
        "cmd": null,
        "architectures": null,
        "latest_digests": null
    }
}`

安装接口响应：v2/message_bus/event/casaos-ui/casaos-ui:appstore:appstore_install
`{
    "name": "casaos-ui:appstore:appstore_install",
    "properties": {
        "access_id": "jPlM0waQdsWt41qyjqd3T",
        "casaos_lang": "zh_cn",
        "device_id": "xxx",
        "value": "qBittorrent"
    },
    "sourceID": "casaos-ui",
    "timestamp": "2023-03-15T23:17:53+08:00",
    "uuid": "0ec59139-ac52-4f3e-ae47-ea603549db86"
}`

界面响应：

![Uploading 截屏2023-03-15 <img width="881" alt="截屏2023-03-15 下午11 21 50" src="https://user-images.githubusercontent.com/590839/225357780-411b098d-c71a-4dbb-9c44-b3b5900b811b.png">11.21.50.png…]()

**Comment by kyomic** [comment]
<img width="881" alt="截屏2023-03-15 下午11 21 50" src="https://user-images.githubusercontent.com/590839/225357962-112d7008-7d7a-4e01-bbc0-fdab1c114831.png">

**Comment by LinkLeong** [comment]
我们看了一下目前商店是不支持arm-7设备安装的,请问你是通过什么方式安装的呢,方便提供命令吗? @kyomic

**Comment by raller1028** [comment]
@ernest5201314 @kyomic 
casaos0.4.3-alpha已经发布了，能帮忙测试一下这个问题是否还存在吗？
更新命令： curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash

**Comment by kyomic** [comment]
> @ernest5201314 @kyomic casaos0.4.3-alpha已经发布了，能帮忙测试一下这个问题是否还存在吗？ 更新命令： curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash


感谢各位大老，升级后已经修复此问题
