### ISSUE TITLE
[Feedback]Loss of function

### ISSUE THREAD

**Issue by mozhouxulang** [IceWhaleTech/CasaOS#948]
### Description

The system cannot provide the function of playing .ts files

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 7055 
	 - Disk Used: 1347 
	 - System Info: [Armbian 23.02.0-trunk Jammy \l Bit:32 Mem:990M Core:4 Linux onecloud 6.1.9-meson #trunk SMP Thu Feb 2 15:42:54 UTC 2023 armv7l armv7l armv7l GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Edge 
	 - Version: 111.0.0.0

**Comment by raller1028** [comment]
If there are any problems, please reopen
