### ISSUE TITLE
容器安装出错

### ISSUE THREAD

**Issue by edwardho1994** [IceWhaleTech/CasaOS#95]
**Describe the bug**

安装adguardhome的时候有问题，对比直接终端安装，好像少了一些端口设置。例如没有了类似这样的端口设置:::3000->3000/tcp，导致最后是打不开容器的

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.8
	 - Disk Total: 19023 
	 - Disk Used: 2173 
	 - Sync State: Sync img: true
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:M Core:1 Linux debian 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 97.0.4692.99

**Comment by LinkLeong** [comment]
非官方应用需要在安装时自行设置
![image](https://user-images.githubusercontent.com/13556972/152741683-ca06d7f8-0a5b-4849-b84d-9448f328ccdf.png)

**Comment by JohnGuan** [comment]
It looks like the problem has been solved
