### ISSUE TITLE
[Feedback]应用暂时不可用

### ISSUE THREAD

**Issue by adl10929** [IceWhaleTech/CasaOS#959]
### Description

应用商店里面应用安装之后，不能访问，下载安装都正常，提示应用暂时不可用

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 14635 
	 - Disk Used: 9449 
	 - System Info: [Raspbian GNU/Linux 10   \l Bit:32 Mem:1887M Core:4 Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Edge 
	 - Version: 110.0.1587.69

**Comment by Endless-zby** [comment]
打开管理员权限，再刷新
[](https://byzhao-blog-1257201044.cos.ap-beijing.myqcloud.com/blog/2023318-0r3uzhzhsr1679073305449.png)

**Comment by Endless-zby** [comment]
https://byzhao-blog-1257201044.cos.ap-beijing.myqcloud.com/blog/2023318-0r3uzhzhsr1679073305449.png

**Comment by raller1028** [comment]
@Endless-zby 你好,部分应用刚安装好并不能立刻使用,需要等待一段时间初始化才能使用,理论上只需要等待一段时间,不需要打开管理员权限再刷新

**Comment by raller1028** [comment]
如果有任何问题,请重新打开
