### ISSUE TITLE
无法自动获取使用终端命令安装的docker容器

### ISSUE THREAD

**Issue by edwardho1994** [IceWhaleTech/CasaOS#96]
**Describe the bug**

用终端安装的docker容器，不会直接出现在Apps里面

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.8
	 - Disk Total: 19023 
	 - Disk Used: 2173 
	 - Sync State: Sync img: true
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:M Core:1 Linux debian 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 97.0.4692.99

**Comment by LinkLeong** [comment]
感谢反馈,casaos本身有一个数据库来记录应用程序是否是通过casaos安装的,我们还在考虑要不要兼容已安装的docker应用.

**Comment by JohnGuan** [comment]
This feature is already available in v0.3.1.
