### ISSUE TITLE
[Feedback] 安装应用只有filebrower可用，别的都不行

### ISSUE THREAD

**Issue by KeoJam** [IceWhaleTech/CasaOS#962]
### Description

安装应用只有filebrower可用，别的都不行，查看容器中的日志，看到没有创建相应的目录及配置文件
<img width="405" alt="3647DC16-8E8D-45e1-96A9-C68BEC1706C5" src="https://user-images.githubusercontent.com/7858697/225851839-20e6511b-8aa7-430a-8cdc-b95b0810ccd8.png">
![Dingtalk_20230317162525](https://user-images.githubusercontent.com/7858697/225852010-8382ed47-87e2-411b-b16d-6dc46c792160.jpg)

**Comment by KeoJam** [comment]
最后解决了，通过手动创建DATA/AppData/HomeAssistant/config 等目录并给777权限 再重新安装应用，是否是安装的脚本执行有问题？

**Comment by raller1028** [comment]
@KeoJam 你这边的设备信息可以发出来吗,看看我们这边能不能复现,或者你这边方便再安装下最新的0.4.3-alpha,看看这个问题是否还存在?
安装命令: curl -fsSL https://get.casaos.io/v0.4.3-alpha | sudo bash
更新命令: curl -fsSL https://get.casaos.io/update/v0.4.3-alpha | sudo bash

**Comment by raller1028** [comment]
If you still have problems, please reopen
