### ISSUE TITLE
挂载硬盘系统已显示，Jellyfin找不到外挂硬盘[Feedback] 

### ISSUE THREAD

**Issue by adl10929** [IceWhaleTech/CasaOS#967]
### Description

  
![微信图片_20230320200203](https://user-images.githubusercontent.com/62693144/226333540-fa7a39cd-0993-4c76-81de-a2ab71de40c6.png)
![微信图片_20230320200215](https://user-images.githubusercontent.com/62693144/226333558-f265fdaa-947d-4a14-9b84-57f6dd6631ba.png)
CasaOS正常访问挂载硬盘，Jellyfin找不到外挂硬盘，Sybcthing上面也找不到硬盘

**Comment by jerrykuku** [comment]
这个需要修改应用的挂载参数才能正确识别。具体可通过点击应用右上角三个点->设置来进行调整

**Comment by adl10929** [comment]
> 这个需要修改应用的挂载参数才能正确识别。具体可通过点击应用右上角三个点->设置来进行调整

![微信截图_20230321082149](https://user-images.githubusercontent.com/62693144/226492940-fc120561-5b88-45ed-8ef6-25ccb692fabb.png)
麻烦看一下怎么修改

**Comment by yueeyuee** [comment]
把硬盘挂载到 /DATA 目录下。
好像是因为casaos安装的应用默认只有 /DATA 目录访问权限。

【其它】
硬盘挂载到 /DATA 目录下方法：
1. 关闭casaos自动挂载，否则重启后还是会自动挂载到 root目录。
2. 配置”/etc/fstab“文件，用UUID配置挂载。（当然用其它的配置挂载也可以，只是我喜欢用UUID。）
3. 注意进行第二步配置的时候一定要关闭自动挂载，否则会冲突无法启动系统。
4. 其它分享两篇文档供您参考：
①https://zhuanlan.zhihu.com/p/250658106
②https://www.runoob.com/linux/linux-comm-chmod.html

**Comment by yueeyuee** [comment]
5. 挂载好了注意赋予挂载磁盘权限，权限不正确的症状就是无法修改或增添文件。参考文档②

**Comment by raller1028** [comment]
@adl10929 还有其他问题吗,如果没有的话,这个问题将会关闭
