### ISSUE TITLE
[Bug] Syncthing has no way to add external drives 

### ISSUE THREAD

**Issue by ahnkle** [IceWhaleTech/CasaOS#973]
**Describe the bug**
Syncthing is intended to back up or save data, but zima unit does not allow external storage to be used by syncthing.

**To Reproduce**
1. Plug in external disk
2. view using Files
3. Go to synthing to use disk to store data
4. disk is not available to syncthing

**Expected behavior**
Syncthing should be able to access external storage to store data on it.

**Desktop (please complete the following information):**
 - OS: Casaos

**Comment by raller1028** [comment]
@ahnkle You can use `chmod 777 /path/to/yourExternalStorage` to enable Syncthing to access your external storage, or change the PUID/GUID from 1000 to 0 to enable Syncthing to access your external storage, but this will prevent Syncthing from starting properly when you change the PUID back to 1000.
We recommend you to use the first way, add your external storage to Syncthing's settings and change the permissions of the external storage to 777.

![Image](https://user-images.githubusercontent.com/57336867/228745217-e70b6125-f6d2-41f4-a6ce-47567b1d8052.png)

**Comment by ahnkle** [comment]
Thank you.
Now able to access external drive.
