### ISSUE TITLE
[Alpha][Bug] Merge storages - Premission

### ISSUE THREAD

**Issue by ngabika** [IceWhaleTech/CasaOS#977]
### What happened?

if I merge 2 USB HHDs, the applications running in the docker do not have permission to write to the folders, e.g.: AppData. So the plex app cannot run properly. I have attached a Plex log screenshot

### Screenshots

Starting Plex Media Server. . . (you can ignore the libusb_init error)
PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server

![image](https://user-images.githubusercontent.com/93099472/227635807-a7e8e6e1-ae5f-46c5-aeca-7dc9521608ed.png)

**Comment by raller1028** [comment]
@ngabika You mentioned merge two usb HHDs, can you tell me how you merge it, and can you provide the linux version and the way to install plex. I installed plex from the app store, and it seems that plex is able to read and write /config/Library/Application Support/Plex Media Server normally.

![Image](https://user-images.githubusercontent.com/57336867/228721368-476ce0ce-ce63-4b18-b16c-1991a3443d60.png)

**Comment by ETWang1991** [comment]
Maybe you can bypass this problem by changing the folder location. For example, use one of the manually created folders.

**Comment by raller1028** [comment]
If there are any problems, please reopen
