### ISSUE TITLE
[Feedback]File Explorer: Can't Mount Network SMB share W/Only Special Characters in PW

### ISSUE THREAD

**Issue by ISolox** [IceWhaleTech/CasaOS#980]
### Description

Cannot mount an SMB with an account password with only special characters. Says 'Special characters may cause security issues'

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 241343 
	 - Disk Used: 29282 
	 - System Info: [Orange Pi 1.1.0 Jammy \l Bit:64 Mem:7689M Core:8 Linux orangepi5 5.10.110-rockchip-rk3588 #1.1.0 SMP Fri Jan 6 15:58:17 CST 2023 aarch64 aarch64 aarch64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Firefox 
	 - Version: 111.0

**Comment by jerrykuku** [comment]
Due to security issues, CasaOS disables certain insecure characters, you may need to change the username or password of your Samba service, or enable the guest user.

**Comment by LinkLeong** [comment]
We will close the issue, if you have questions, you can reopen it
