### ISSUE TITLE
[Bug] Remove app modal not rendering properly

### ISSUE THREAD

**Issue by pieterhouwen** [IceWhaleTech/CasaOS#983]
**Describe the bug**
When removing an app the confirmation window shows not interpreted div statements

**To Reproduce**
1. Install any app
2. Try to remove app installed in 1.

**Expected behavior**
Modal window shows normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/10866686/228217790-dfc2de54-d810-4e3e-a600-d2b8f3fc918b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chromium
 - Version 110.0.5481.84 (Official Build, ungoogled-chromium) (64-bit)

**Comment by raller1028** [comment]
@pieterhouwen Which version of casaos are you using, can you try switching the language to English and see if the error is still there?

**Comment by pieterhouwen** [comment]
@raller1028 The language bar was empty but the interface language was already in English. Maybe force the language to be English when setting it up for the first time for new users?

Am running v0.4.2

**Comment by raller1028** [comment]
@pieterhouwen The default language is English, what is the problem with the empty language bar you mentioned? Can you provide a screenshot or a more detailed description?

**Comment by zhanghengxin** [comment]
Will be solved in the next version.

**Comment by jerrykuku** [comment]
This issue has been resolved and I will close it, if there are still new questions you can reopen it.
