### ISSUE TITLE
[Feedback]Apps will not install

### ISSUE THREAD

**Issue by leonsantore** [IceWhaleTech/CasaOS#984]
### Description

Can not get apps to install??

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 27712 
	 - Disk Used: 8233 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7802M Core:4 Linux CasaOS 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Chrome 
	 - Version: 111.0.0.0

**Comment by raller1028** [comment]
Can you provide a more detailed screenshot or error message?

**Comment by raller1028** [comment]
if have any problem, please reopen
