### ISSUE TITLE
Mount devices

### ISSUE THREAD

**Issue by est1712** [IceWhaleTech/CasaOS#99]
**Describe the bug**

I formatted a drive and created a mount point and mounted device on ubuntu 20.04. Added device to fstab and saved it. After rebooting every single time, casaOS creates and mounts device to /DATA/USB_Storage1 or *_Storage2 is created.

Is this a bug or is there a fix?

JT

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.8
	 - Disk Total: 58419 
	 - Disk Used: 4637 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Ubuntu 20.04.3 LTS   \l Bit:64 Mem:3793M Core:4 Linux cpls0043 5.4.0-1050-raspi #56-Ubuntu SMP PREEMPT Thu Jan 13 13:09:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 97.0.4692.99

**Comment by LinkLeong** [comment]
shell 
`rm /casaOS/server/shell/assist.sh
rm /etc/systemd/system/usb-mount@.service`

You can temporarily disable auto-mounting, we will deal with this issue in subsequent releases

**Comment by JohnGuan** [comment]
Multiple versions have been released, does this problem still exist?

**Comment by swanux** [comment]
I ran into the problem today, that my whole `/casaOS` folder was missing...
Easy fix is to put the `usb-mount.sh` script there manually - and after that it seems to work properly - but still, looks like a somewhat related bug to me.

**Comment by tigerinus** [comment]
> I ran into the problem today, that my whole `/casaOS` folder was missing... Easy fix is to put the `usb-mount.sh` script there manually - and after that it seems to work properly - but still, looks like a somewhat related bug to me.

Please open a new issue to track the problem if it still happens. Thanks.
