### ISSUE TITLE
what happens when i open settings and click save button?

### ISSUE THREAD

**Issue by onlineapps-cloud** [IceWhaleTech/CasaOS#992]
hi, question is: what happens when i open settings and click save button?
question is because i have container that loose all data when i do this! if i restart casaos, container not lose data, just when i open settings and click save (without made any changes in setting page!), container is reseted by default (like after fresh install).
why just don't close settings window if i don't made any changes, without restarting docker container when i click save button?
docker container: https://hub.docker.com/r/shellngn/pro
casaos version:  v0.4.2
settings page:
![image](https://user-images.githubusercontent.com/69077240/229383284-0d894e7d-25f7-4a49-9357-52b16d10a471.png)
video demonstration:

https://user-images.githubusercontent.com/69077240/229383481-3f7f06ee-1693-4d7d-af62-48914243c986.mp4

**Comment by Hedius** [comment]
This is not a bug. Editing a container causes it to be deleted and being recreated with the new settings. You have to ensure that all data which should be persistent is stored in volumes. The container file system itself gets wiped each time.

This is not a design choice of casaos. This is how containers work.
