### ISSUE TITLE
[Bug] Install a customized app Environment variables does not support `$`

### ISSUE THREAD

**Issue by Erik-Handeland** [IceWhaleTech/CasaOS#993]
**Describe the bug**
Cannot supply Env Var that contains a `$`. After saving the looking back at settings the value is set to null.

**To Reproduce**
1. Install a customized app
2. Add a environmental variable which has a value that contains a $ i.e `$test$data$`
3. Save and open settings again
4. Key value will be shown as empty

**Expected behavior**
That `$test$data$` should be displayed when I view the key value from settings. Or that I should be able to escape the key

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser:  Safari
 - Version 16.3 

**Additional context**
I'm guessing this has to do with how CasaOS save custom apps probably as JSON and runs docker containers using `docker run`. This would explain why when I try importing my docker cli using the tool `docker run ... -e "API_KEY=\$API-KEY"` the escaped dollar sign isn't resent as `\$` is not valid JSON. Double escaping `\\$` also did not work solve my issue.

**Comment by CorrectRoadH** [comment]
Suppose you want to set $ as the value in the environment. You must write two $. like `$$test$$data$$`,
