### ISSUE TITLE
exec与noexec

### ISSUE THREAD

**Issue by 392377870** [IceWhaleTech/CasaOS#994]
挂载的时候怎样切换exec与noexec？还有就是arm设备中的内置闪存卡每次通话挂载，必须弹出来再插进去才行

**Comment by jerrykuku** [comment]
会尽快修复所有usb挂载的时候全部都是noexec的问题。

**Comment by raller1028** [comment]
@392377870 v0.4.3已经修复这个问题,可以帮忙看看这个问题还存在吗
更新命令: `curl -fsSL https://get.casaos.io/update | sudo bash`

**Comment by 392377870** [comment]
> @392377870v0.4.3已经修复这个问题，可以帮忙看看这个问题还存在吗 更新指令：`curl -fsSL https://get.casaos.io/update | sudo bash`

确实修复了这个问题，现在正常了，什么时候修复sd卡开机自动挂载？

**Comment by jerrykuku** [comment]
exec with noexec has been fixed for a long time and I will close this issue.
