### ISSUE TITLE
[Bug] The attribute for volume can not be applied in CasaOS

### ISSUE THREAD

**Issue by everiori** [IceWhaleTech/CasaOS#996]
**Describe the bug**
I mount a volume as ReadOnly like below, but when I try to create a file under this read only folder inside the docker, the file still can be created, which means that the ReadOnly attribute is not applied inside the container
I set the same attribute with docker run, the ReadOnly attribute gets applied exactly as what I want.

/root/testmount:/root/testmount:ro

**Comment by everiori** [comment]
I am not so sure if this is a bug or a feature, pls help

**Comment by raller1028** [comment]
The processes in the Docker container are running as root user, which means that even if you set the folder permissions to read-only, Docker still has write access. If you want to restrict the access of the processes in the Docker container to the folder permissions, you can take the following steps:

chmod 444 /path/to/yourdir

This command sets the folder permissions to "read-only for owner, group members, and other users," so processes in the Docker container will not be able to create, modify, or delete files in that folder.

You can also set Docker environment variables to control the user ID and group ID used by the processes in the container. By setting these variables, you can make the processes in the Docker container run under a different user identity than on the host, thus better controlling their access permissions. For example, you can set the following variables:

-e "PUID=1000" -e "PGID=1000"

This will make the processes in the Docker container run with user ID 1000 and group ID 1000. You can change these values as needed to match different users and groups on the host.


![Image](https://user-images.githubusercontent.com/57336867/231369530-ecdc3c38-e185-4170-957f-c861d306eec0.png)

**Comment by raller1028** [comment]
You can install the Docker app using the command line and add permission parameters in the command line.

**Comment by raller1028** [comment]
If still have problems please reopen
