### ISSUE TITLE
Eject failed

### ISSUE THREAD

**Issue by onlineapps-cloud** [IceWhaleTech/CasaOS#997]
hi, i connected SMB share, but, i cannot disconnect them, eject failed:
![image](https://user-images.githubusercontent.com/69077240/230411257-487e752c-5ebd-4820-8346-9987136f839d.png)
also i cannot conect to smb share that have `-` in user name! i have user with `-`
![image](https://user-images.githubusercontent.com/69077240/230411875-6577e568-d09a-4d8d-bb39-02ce683420a5.png)

**Comment by onlineapps-cloud** [comment]
upd. after reboot OS i able to eject SMB share.

**Comment by raller1028** [comment]
can you provide your casaos version, for username and password input we have temporarily specified that certain special characters cannot be entered

**Comment by onlineapps-cloud** [comment]
`can you provide your casaos version` this bug i received on 0.4.2 version, now on 0.4.3 this bug not persist (i checked right now)
