### ISSUE TITLE
[虫子]

### ISSUE THREAD

**Issue by beichen123-hub** [IceWhaleTech/CasaOS#999]
After I upgraded to V0.4.3., the storage did not show my storage space, there was no way to merge the space, and the programs I installed did not open properly 

![QQ20230407-093027](https://user-images.githubusercontent.com/70616669/230522257-30ec1d30-67e7-495f-8f15-f573c68deeb6.png)
![QQ20230407-093050](https://user-images.githubusercontent.com/70616669/230522278-634517b3-6a47-49ef-acea-ed11010e81be.png)

**Comment by raller1028** [comment]
@beichen123-hub 可以提供你的设备信息吗,或者方便添加微信guanningchuan,受邀进微信群跟进

**Comment by beichen123-hub** [comment]
我已经添加您的微信。I have added your wechat
